### ISSUE TITLE
Installation Contao 3 Erweiterungen

### ISSUE THREAD

**Issue by Jaaaan** [contao/contao-manager#103]
Hallo!

Bisher war es mir noch nicht gelungen, mittels Contao Manager jegliche Contao 3 Erweiterungen zu installieren. Sollte nicht eine Rückwärtskompatibilität mit bestehenden Contao 3–Erweiterungen beibehalten bleiben oder müssen doch die Entwickler diese erst freigeben?
```
  Problem 1
    - Installation request for <Erweiterung> -> satisfiable by <Erweiterung>.
    - Conclusion: remove contao/calendar-bundle 4.4.0
    - Conclusion: don't install contao/calendar-bundle 4.4.0
```

**Comment by aschempp** [comment]
Das ist vermutlich ein Fehler in der Erweiterung. Welche hast du versucht?

**Comment by Jaaaan** [comment]
Die Contao 4 Bundles lassen sich einwandfrei installieren, jedoch keine Contao 3 Erweiterungen mit dem CM. Beispielsweise:
- bugbuster/backend_user_online
- martin-kozianka/contao-fullcalendar
- dklemmt/contao_dk_mmenu

**Comment by aschempp** [comment]
Keine dieser Erweiterungen wurde leider für Contao 4 freigegeben. Am besten weisst du die Entwickler über GitHub darauf hin, die nötigen Anpassungen sind unter https://github.com/contao-community-alliance/composer-plugin/blob/master/README.md dokumentiert.
