### ISSUE TITLE
Selfupdate of CM (1.0.0-beta2 to 1.0.0-beta3)

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao-manager#104]
The following message pops up after runing the selfupdate:
`ERROR 500 Catchable Fatal Error: Argument 3 passed to Contao\ManagerApi\Process\ConsoleProcessFactory::__construct() must be an instance of Contao\ManagerApi\Process\ServerInfo, instance of Symfony\Bridge\Monolog\Logger given, called in phar:///home/contao/public_html/domain.ch/web/contao-manager.phar.php/api/Resources/cache/apiProdProjectContainer.php on line 766 and defined`

Refresh the page and everything is okay.

**Comment by aschempp** [comment]
I assume this message was visible in the task console?

**Comment by netzarbeiter** [comment]
It was shown in the error overlay.
