### ISSUE TITLE
Contao Installtool - 404 Not Found

### ISSUE THREAD

**Issue by stefanabg** [contao/contao-manager#105]
Hallo,
ich habe nach einigen Schwierigkeiten Contao 4.4 über den Contao Manager installiert und kann diesen nun auch aufrufen. Zum Schluss erschien die Meldung, dass ich nun in das Install Tool wechseln solle, was ich auch wollte. Leider erhalte ich dabei immer wieder nur die Meldung, dass die Seite nicht existiert. 
Der Root Pfad der Subdomain ist der Web Ordner, wie gefordert. Die Berechtigungen passen auch und leider wird im zugehörigen Log nichts angezeigt (es existiert nicht unter /var/log).

**Comment by aschempp** [comment]
Welche URL sieht du beim öffnen des Install-Tools?

**Comment by stefanabg** [comment]
Ich sehe die Domain https://contaovier.*.de/contao/install

**Comment by aschempp** [comment]
dann liegt das Problem wohl an deiner Serverkonfiguration (z.B. Nginx). Hat allerdings nichts mit dem Manager zu tun, bitte wende dich am besten an's Community Forum.
