### ISSUE TITLE
Konsolentask öffnet sich obwohl Login nötig ist und im Hintergrund auch geladen wird

### ISSUE THREAD

**Issue by BugBuster1701** [contao/contao-manager#107]
Ich bin angemeldet im CM und warte solange, dass normalerweise bei der nächsten Aktion umgelenkt wird zur Login Seite. Das funktioniert auch an einigen Stellen, nicht jedoch beim Pakete aktualisieren oder Löschen. In dem Moment wo ich auf "Änderungen anwenden" klicke passiert das:
![cm100beta4-fehler](https://user-images.githubusercontent.com/1218809/27432668-5a5f9f4c-5751-11e7-810d-0d8a4e03c1a0.png)

Das lässt sich auch nicht abbrechen, geht nur über "F5" Browser refresh.

**Comment by jscholtysik** [comment]
Gleiches Problem hier... Schon mehrmals ausprobiert. Hier sollte eine Abfrage stattfinden, ob der Login noch gültig ist und dann notfalls noch einmal die Loginmaske kommen und nicht sofort der Konsolentask starten

**Comment by aschempp** [comment]
Fixed in 4b35fa350eb3f7f44f32cd27955549dcb2bdd150

**Comment by jscholtysik** [comment]
Bei All-Inkl kam beim Login mit der Beta4 kurzzeitig ein Error 500. Nach einem Refresh dann ein Error 400, dann lief aber die Aktualisierung des Contao Managers auf Beta5 durch.
