### ISSUE TITLE
Problem Hetzner Beta 4

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao-manager#109]
Mit Beta 2 kann bei Hetzner Level 4 die Installation noch fehlerfrei abgeschlossen werden. Mit der Beta 4 ist kein Abschluss mehr möglich.
Process terminated with exit code 1
Reason: General error
Siehe auch https://community.contao.org/de/showthread.php?67084-Hinweise-zum-Contao-Manager&p=443396&viewfull=1#post443396

**Comment by heimseiten** [comment]
Kann ich bestätigen. Beta 3 und Beta 4 funktionieren bei Hetzner nicht mehr:

[api-2017-06-22.txt](https://github.com/contao/contao-manager/files/1094837/api-2017-06-22.txt)

**Comment by mlwebworker** [comment]
Kleine Ergänzung: eine Beta 2 aupgedatet auf eine Beta 4 (Autoupdate beim Starten des Mangers) bringt als Fehlermeldung soetwas wie "Konsolentask nicht ausführbar" (habe ich leider zu schnell weggeklickt). Der Versuch danach eine Erweiterung (z.B. Isotope) zu installieren endet mit:

```
Writing lock file
Generating optimized autoload files

Killed

Process terminated with exit code 137
Reason: Kill (terminate immediately)
```

**Comment by mlwebworker** [comment]
Problem bleibt in der beta 5 erhalten.

**Comment by fiedsch** [comment]
Ich bekomme hier folgendes: 

```
# start wie erwartet
# viele Installing ...
  - Installing contao/newsletter-bundle (4.4.0): Downloading (100%)
Generating autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
--------------------------------------------------------
Exception occured: Project could not be created.
# und letztlich:
Chained exception: The php executable could not be found.
```

Die php cli executable steht aber in der contao-manager/manager.json korrekt drin:
``` 
 "php_cli": "\/usr\/bin\/php",
``` 

Check: Auf der Console
``` 
which php 
/usr/bin/php

php -v 
PHP 7.0.20 (cli) (built: Jun  8 2017 18:29:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
``` 

Im Contao-Manager bekommt man

```
ERROR 500 Unknown installation status
Some files were found on your server but no known Contao version could be detected.
You must either manually repair your application or remove the following files and folders to install Contao:

 - install-5950bf4b08bf1
```

Wenn man das Unterverzeichnis `install-5950bf4b08bf1` (mit den Downloads) löscht, läuft der CM wieder und man kann die Contao-Installation erneut starten, was natürlich zum selben Ergebnis führt.

**Comment by heimseiten** [comment]
Mit der beta 2 funktioniert es gut. Diese kann hier heruntergeladen werden:
https://share.heimseiten.de/contao-manager_beta_2.zip

Wenn ein automatische Update ausgeführt wird, kann die neue Datei mit der alten Datei (beta2) überschreiben werden. Oder kann das automatische Update ausgeschaltet werden?

**Comment by aschempp** [comment]
Die Probleme mit Hetzner wurden in der 1.0.0-beta6 behoben.

**Comment by fiedsch** [comment]
```
php contao-manager.phar.php self-update
# läuft erfolgreich durch und zeigt dann im FE Contao Manager 1.0.0-beta6
```

> Die Probleme mit Hetzner wurden in der 1.0.0-beta6 behoben.

leider nicht alle :-( 

In "PHP-Binary" steht jetzt  `/usr/bin/php70` was auf der Konsole folgendes ergibt
```
PHP 7.0.20 (cli) (built: Jun  8 2017 18:29:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```
also passen sollte, aber nach Klick auf "Contao installieren"  bekomme ich immer:
```
ERROR 404 No active task 
```
d.h. es scheitert bereits der Download der Pakete.

**Comment by aschempp** [comment]
Die Beta6 hat leider einen Fehler bei der Installation, wird gleich in der Beta7 behoben. Alles andere (bestehende Installation) müsste damit funktionieren.

**Comment by fiedsch** [comment]
Kurzes Feedback: 

* funktioniert jetzt
* musste das `self-update` auf der Konsole anstoßen um die Beta7 zu bekommen

#einfachmaldankesagen

**Comment by aschempp** [comment]
Weil es nicht funktioniert hat, oder weil nicht von allein durch? Der Manager prüft nur jede Stunde…

**Comment by fiedsch** [comment]
Ich hatte einige Zeit einen Reload des laufenden Managers und auch einen neuene Login probiert, es wurde aber kein self-update ausgeführt. Wahrscheinlich war ich nur zu ungeduldig und hab's dann auf der Konsole angestoßen. Fehler gabe es keine, also alles OK. Danke.

**Comment by standing-bear** [comment]
Also bei mir läuft die Beta7 auf Hetzner Level 4 nicht!?

```
Using version ^2.0 for madeyourday/contao-rocksolid-slider
/usr/www/users/pigs/cto44/composer.json has been updated
Loading composer repositories with package information
Updating dependencies

Killed

Process terminated with exit code 137
Reason: Kill (terminate immediately)
```

Das kommt bei allen Paketen, die ich installieren wollte.

**Comment by Aybee** [comment]
Gerade mit der beta 13 probiert. Gleiche Fehler. Installation läuft fehlerfrei durch, aber bei der Installation einer ersten kleinen Erweiterung (easy_themes) kommt
`Process terminated with exit code 137`
Und später dann auch `ERROR 500` und eine Bedienung des Managers ist dann nicht mehr möglich, auch nicht nach löschen von contao-manager/cache.

**Comment by standing-bear** [comment]
Das will hier leider keiner wissen! Der Manager läuft so gut wie nirgends. Habe inzwischen x verschiedene Server probiert. Kann man u. a. [hier ](https://github.com/contao/contao-manager/issues/90) nachlesen.
Aber wenn zu viel kritisiert/gemeckert wird, wird das Ticket eben geschlossen ... Problem gelöst.

**Comment by Aybee** [comment]
Ja, diese Fehler sollten über die Software aufgefangen werden, sodass man wenigsten einen Hinweis bekommt, woran es liegt und was man dann machen soll. So wie bisher ist das nichts, mein Kunde war stocksauer.
