### ISSUE TITLE
Check for highlighted keywords CSS

### ISSUE THREAD

**Issue by Toflar** [contao/contao-manager#11]
I've implemented highlighting the search terms in package name and description in 2f078001978b108f4560c0ec539033396a5fa104 and used `<mark>` for this. Chrome apparently highlights this in yellow already but maybe we should make sure it's present in our CSS anyway?

**Comment by aschempp** [comment]
This is obsolete with the latest version (see https://github.com/contao/contao-manager/tree/develop)
