### ISSUE TITLE
PHP Binary für Mittwald

### ISSUE THREAD

**Issue by IdeeAnhang** [contao/contao-manager#110]
Leider ist es nicht Möglich bei Mittwald den Contao Manager beta 4 nicht zu installieren. 
Es wird die PHP Binary nicht gefunden und der Pfad dazu nicht akzeptiert. Egal welche PHP Version genutzt wird.

**Comment by aschempp** [comment]
Wir sind bereits direkt mit Mittwald in Kontakt um den Manager zu testen, in einer der nächsten Versionen sollte das korrekt funktionieren.

**Comment by BugBuster1701** [comment]
[Forum](https://community.contao.org/de/showthread.php?67104-Installation-Contao-4-4-Contao-Manager&p=443591&viewfull=1#post443591) meint: /usr/local/bin/php_cli
Funktioniert das?

**Comment by MaCo7** [comment]
Mittwald: /usr/local/bin/php_cli  hat bei mir funktioniert!

**Comment by aschempp** [comment]
Mittwald wurde in Beta 11 der bekannten Liste von Hostern hinzugefügt und dieses Problem gelöst.
