### ISSUE TITLE
Contao Manager und all inkl.com

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao-manager#111]
Manchmal erkennt der Contao Manager bei all inkl.com die eingestellte PHP 7.1 Version selbständig manchmal muß ich den PHP-Binary Pfad angeben. Die weiteren Dinge funktionieren in beiden Fällen einwandfrei. Dieses soweit zur Info und Unterstützung an die Contao Programmierer.

**Comment by BugBuster1701** [comment]
Wie wäre denn der manuelle Pfad? `/usr/bin/php71` ?

**Comment by fritzmg** [comment]
`/usr/bin/php` für die neueste Version, ansonsten `/usr/bin/php56`, `/usr/bin/php71` etc.

**Comment by BugBuster1701** [comment]
So ist es auch definiert im CM, sollte daher auch gefunden werden. Ich dachte vielleicht weicht das ja was ab von.
https://github.com/contao/contao-manager/blob/develop/api/Resources/config/providers.yml#L33-L40

**Comment by aschempp** [comment]
Ich denke das liegt daran dass ipinfo.io manchmal keine Resultate liefert. Dürfte mit 8aa4a1571379451f814961a1f30b1ba5ac3f591b so weit wie möglich behoben sein.
