### ISSUE TITLE
Error: Konsolentask beendet! Der Hintergrundprozess wurde abgebrochen oder unerwartet 

### ISSUE THREAD

**Issue by NinaG** [contao/contao-manager#112]
Am Ende der Contao-Installation via Contao Manager erhalte ich bei All-Inkl jedes Mal die Meldung: 
`Konsolentask beendet!
Der Hintergrundprozess wurde abgebrochen oder unerwartet beendet. Bitte prüfen Sie das Konsolenprotokoll.`

Schau ich mir darunter im schwarzen Fenster die grünen Protokoll-Infos an, steht dort nichts von einem Fehler. Lauter Haken und Erfolgsmeldungen, siehe hier: https://community.contao.org/de/showthread.php?67159-Konsolentask-beendet!-Der-Hintergrundprozess-wurde-abgebrochen-oder-unerwartet

Es fehlt aber der Schlusssatz "Finished without error".

Ich habe nicht die geringste Ahnung, was hier falsch gelaufen sein soll. Wenn ich den Button "Bestätigen und Schließen" anklicke, erscheint normal die Manager-Ansicht und darin die Auflistung von Contao und den Core-Erweiterungen. Auch hier kein Fehler erkennbar. 

Wenn ich mich später in den Manager einlogge, aktualisiert sich dieser erfolgreich (mit der Finished ohne Error-Meldung am Ende). Klicke ich dann auf "Pakete aktualisieren", macht er das scheinbar erfolgreich, aber am Ende zeigt er dann auch die obige Fehlermeldung von wegen Konsolentask beendet.

Gibt es irgendein Log o.ä. das ich noch prüfen kann um zu verstehen, was hakt?

**Comment by planepix** [comment]
Gleiches Verhalten kann ich bestätigen (allinkl, Business-Paket).

**Comment by MDevster** [comment]
Es hilft im Web eine .htaccess Datei mit php_value max_execution_time 300 anzulegen.

**Comment by BugBuster1701** [comment]
Bei mir nicht. In meiner php.ini steht schon auf 120 Sekunden, der angebliche Abbruch erfolgt viel eher.

**Comment by Schmidty2** [comment]
Ich habe das Problem bei HostEurope (WebServer Medium), PHP CLI Version 5.6.30.
Wenn ich die Konsolenbefehle direkt ausführe läuft alles, über den Contao-Manager beta 5 habe ich nach 10-20 Sekunden die gleichen Meldungen. Die max_execution_time steht auf 240 sekunden.

**Comment by aschempp** [comment]
könnt ihr bitte testen ob dieses Problem mit der Beta7 behoben ist?

**Comment by BugBuster1701** [comment]
Bisher alles gut (lokal), teste noch beim Hoster morgen.
