### ISSUE TITLE
??

### ISSUE THREAD

**Issue by matrix73** [contao/contao-manager#115]
Task cd8d1fb4f00d2159d47b424996b5882c started.
Loading composer repositories with package information
Updating dependencies
Nothing to install or update
Generating optimized autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
08:49:33 ERROR     [console] Error thrown while running command "contao:install-web-dir --env=prod". Message: "Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src/Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/web/.htaccess" because target file could not be opened for writing." ["error" => Symfony\Component\Filesystem\Exception\IOException {trace: { …} …},"command" => "contao:install-web-dir --env=prod","message" => "Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src/Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/web/.htaccess" because target file could not be opened for writing."] []
08:49:33 ERROR     [console] Command "contao:install-web-dir --env=prod" exited with code "1" ["command" => "contao:install-web-dir --env=prod","code" => 1] []

                                                                               
  [Symfony\Component\Filesystem\Exception\IOException]                         
  Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src  
  /Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/web/.ht  
  access" because target file could not be opened for writing.                 
                                                                               

contao:install-web-dir [--no-dev] [-u|--user USER] [-p|--password [PASSWORD]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<path>]

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception
--------------------------------------------------------
Exception occured: An error occurred while executing the "contao:install-web-dir" command: 08:49:33 ERROR     [console] Error thrown while running command "contao:install-web-dir --env=prod". Message: "Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src/Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/web/.htaccess" because target file could not be opened for writing." ["error" => Symfony\Component\Filesystem\Exception\IOException {trace: { …} …},"command" => "contao:install-web-dir --env=prod","message" => "Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src/Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/web/.htaccess" because target file could not be opened for writing."] []
08:49:33 ERROR     [console] Command "contao:install-web-dir --env=prod" exited with code "1" ["command" => "contao:install-web-dir --env=prod","code" => 1] []

                                                                               
  [Symfony\Component\Filesystem\Exception\IOException]                         
  Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src  
  /Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/web/.ht  
  access" because target file could not be opened for writing.                 
                                                                               

contao:install-web-dir [--no-dev] [-u|--user USER] [-p|--password [PASSWORD]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<path>]

#0 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/cent7/...')
#3 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/cent7/...')
#4 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/cent7/public_html/web/contao-manager.phar.php(55): require('phar:///var/www...')
#12 {main}
Chained exception: An error occurred while executing the "contao:install-web-dir" command: 08:49:33 ERROR     [console] Error thrown while running command "contao:install-web-dir --env=prod". Message: "Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src/Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/web/.htaccess" because target file could not be opened for writing." ["error" => Symfony\Component\Filesystem\Exception\IOException {trace: { …} …},"command" => "contao:install-web-dir --env=prod","message" => "Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src/Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/web/.htaccess" because target file could not be opened for writing."] []
08:49:33 ERROR     [console] Command "contao:install-web-dir --env=prod" exited with code "1" ["command" => "contao:install-web-dir --env=prod","code" => 1] []

                                                                               
  [Symfony\Component\Filesystem\Exception\IOException]                         
  Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src  
  /Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/web/.ht  
  access" because target file could not be opened for writing.                 
                                                                               

contao:install-web-dir [--no-dev] [-u|--user USER] [-p|--password [PASSWORD]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<path>]

#0 /var/www/cent7/public_html/vendor/contao/manager-bundle/src/Composer/ScriptHandler.php(72): Contao\ManagerBundle\Composer\ScriptHandler::executeCommand('contao:install-...', Object(Composer\Script\Event))
#1 /var/www/cent7/public_html/vendor/contao/manager-bundle/src/Composer/ScriptHandler.php(35): Contao\ManagerBundle\Composer\ScriptHandler::addWebEntryPoints(Object(Composer\Script\Event))
#2 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication(Object(Composer\Script\Event))
#3 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(205): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Contao\\ManagerB...', 'initializeAppli...', Object(Composer\Script\Event))
#4 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#5 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(307): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', false)
#6 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Command/UpdateCommand.php(158): Composer\Installer->run()
#7 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#8 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(147): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#9 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#10 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#11 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/cent7/...')
#12 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/cent7/...')
#13 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///var/www/cent7/public_html/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/cent7/public_html/web/contao-manager.phar.php(55): require('phar:///var/www...')
#21 {main}
--------------------------------------------------------

Process terminated with exit code 1
Reason: General error

**Comment by BugBuster1701** [comment]
> "Failed to copy "/var/www/cent7/public_html/vendor/contao/manager-bundle/src/Command/../Resources/web/.htaccess" to "/var/www/cent7/public_html/**web/.htaccess" because target file could not be opened for writing**.


The Contao Manager has no write permissions in the web/ directory.
