### ISSUE TITLE
Bei der Paket-Suche Anzeigen, ob ein Paket bereits installiert ist

### ISSUE THREAD

**Issue by Schmidty2** [contao/contao-manager#118]
Kann bei der Paket/Bundle-Suche eine Anzeige z.B. ein Symbol hinzugefügt werden, wenn das Bundle bzw. Paket bereits in der Contao-Installation installiert ist.
Oder ein ausgegrautes Symbol wenn nicht installiert und ein farbiges Symbol wenn installiert.

**Comment by aschempp** [comment]
Duplicate of #73
