### ISSUE TITLE
Contao-manager.phar.php returns 404 on timmehosting.de

### ISSUE THREAD

**Issue by fbasara-loft48** [contao/contao-manager#119]
**Steps to reproduce**
- Setup website via timmehosting control panel (nginx / PHP 7)
- Set domain path to `/path/to/contao/web`
- Upload `contao-manager.phar` to `/web` via ftp in binary mode
- Rename `contao-manager.phar` to `contao-manager.phar.php`
- Open `mydomain.tld/contao-manager.phar.php`
- Server returns 404

**Comment by fritzmg** [comment]
Your problem probably has nothing to do with the Contao Manager. See  https://community.contao.org/de/showthread.php?67183-Contao-manager-phar-php-404-Fehler-phpinfo()-im-gleichen-Ordner-funktioniert

**Comment by fbasara-loft48** [comment]
@fritzmg Will investigate, and report back.

**Comment by aschempp** [comment]
Zitat von @leofeyer zur Konfiguration von Nginx:

> Ich hatte es am Anfang. Hab dann die Nginx-Konfiguration so angepasst, dass der PATH korrekt gestrippt wurde. 
>
>  ```  location ~ \.php(?:/|$) {
>  fastcgi_split_path_info ^(.+?\.php)(/.*)$;
>    if (!-f $document_root$fastcgi_script_name) {
>      return 404;
>    }
>    fastcgi_pass 127.0.0.1:9000;
>    …
>  }
>```
>
> Wichtig ist, dass man nicht `\.php$` verwendet, wie es sonst in Nginx üblich ist. Man muss `\.php(?:/|$)` verwenden.
>
> Das ist auch bei Symfony so.
> Überall wo nach dem `.php` noch ein Pfad kommt.
> Anstatt eines Queries.

**Comment by fbasara-loft48** [comment]
Current nginx directive provided by timmehosting
`fastcgi_split_path_info ^(.+\.php)(/.*)$;`

Will try changing it to 
`fastcgi_split_path_info ^(.+?\.php)(/.*)$;`

**Comment by fbasara-loft48** [comment]
That's my current nginx config (right) compare to the default one (left)
https://www.diffchecker.com/y2BQOOMG

Domain is still pointing towards `path/to/contao/web`

**Comment by fbasara-loft48** [comment]
Could this point to the error? Or is it an ordinary `not found` event

`[2017-06-27 09:52:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: http://domain.tld/contao-manager.phar" at /root/contao44/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: http://domain.tld/contao-manager.phar at /root/contao44/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: http://domain.tld/contao-manager.phar at /root/contao44/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:67)"} []`

**Comment by fbasara-loft48** [comment]
Could this be of any use?

`2017-06-27 09:56:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: http://mydomain.tld/contao-manager.phar.php/" at /root/contao44/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: http://mydomain.tld/contao-manager.phar.php/ at /root/contao44/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: http://mydomain.tld/contao-manager.phar.php/ at /root/contao44/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:67)"} []
`

**Comment by aschempp** [comment]
Looks like your server is processing all files through app.php (the Contao entry point). Most likely because the forward slash in the file name does not work, as leo pointed out in his config example.

**Comment by fbasara-loft48** [comment]
@aschempp Thanks for the support. Already contacted them, they have no plans of supporting the beta at the moment. I believe it's just a configuration error, yet they didn't seem to be interested in supporting something that is not "stable" yet.

**Comment by fritzmg** [comment]
> Already contacted them, they have no plans of supporting the beta at the moment.

It's not a problem with the Contao Manager (directly). Does `http://mydomain.tld/test.php/` or `http://mydomain.tld/test.php/foo` work for example?

@aschempp does the Contao Manager append the `/` automatically?

**Comment by aschempp** [comment]
Yes it does, to make relative URLs work

**Comment by fbasara-loft48** [comment]
> Does http://mydomain.tld/test.php/ or http://mydomain.tld/test.php/foo work for example?

Yes, it does.

**Comment by fbasara-loft48** [comment]
Turns out it was indeed a misconfiguration.
Changed `location ~ ^/(app|app_dev|config|install)\.php(/|$) {`
to  and removed `proc_open` from `disable_functions`

I am now seeing an API Error, which has nothing to do with this issue.

Thanks to everyone!

**Comment by aschempp** [comment]
👍 

If you want to know the details of the API error, just look at the browser console and the HTTP requests. see https://github.com/contao/contao-manager/issues/123

**Comment by fbasara-loft48** [comment]
Thanks, will do!
