### ISSUE TITLE
Ignore file .ftpquota during installation

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#120]

**Comment by felixpfeiffer** [comment]
Same with the DS_Store file in Mac.

**Comment by jscholtysik** [comment]
Same with directory "usage" at All-Inkl.

See https://github.com/contao/contao-manager/issues/89

**Comment by k-webdesign** [comment]
- 100-40-5-monochrome.png
- favicon.ico
- index.html

at netcup
