### ISSUE TITLE
ERROR 500 - Hosting cyon

### ISSUE THREAD

**Issue by fenepedia** [contao/contao-manager#126]
Fehler:

```
ERROR 500 integrity.process.title
integrity.process.detail
```

PHP 7.1
Manger Beta7

Dachte eigentlich dass der Manager bei cyon schon problemlos geklappt hat.

**Comment by aschempp** [comment]
Komisch dass keine korrekte Meldung kommt. Sie sollte sagen dass proc_open nicht aktiv ist, das musst du im my.cyon aktivieren.

**Comment by fenepedia** [comment]
Hier mal kurz ein Screenshot, was muss ich alles aktivieren?
![bildschirmfoto 2017-06-30 um 14 25 29](https://user-images.githubusercontent.com/566448/27736947-9a93a666-5da6-11e7-88e6-5ccc640e6095.png)

**Comment by fenepedia** [comment]
Hab jetzt proc_open und proc_close aktiviert. Jetzt sieht es gut aus. Reicht das?

**Comment by aschempp** [comment]
Ja. Muss mir aber noch ansehen warum die korrekte Meldung nicht kam.

**Comment by aschempp** [comment]
Fixed in c23be9d2e1610f8ab9fa691b5de18e9cef68fd66
