### ISSUE TITLE
Automatisches Update deaktivierbar machen

### ISSUE THREAD

**Issue by dmolineus** [contao/contao-manager#127]
Dass der Contao Manager sich per automatisches Update selbst aktualisiert, sollte dringend optional sein.

Leider gibt es immer wieder die Situation wo ein Update ein unerwartetes und vorher nicht vorhandenes Problem mit sich bringt (z.b. derzeit beta2 auf beta7). Ein Administrator sollte demnach selbst die Kontrolle behalten können, ob ein Update gerade durchgeführt werden soll.

**Comment by aschempp** [comment]
Ich bin vehement gegen eine solche Option. Ein defekter Manager sollte repariert werden, eine alte Version nutzen ist keine sinnvolle Lösung. In kürzester Zeit werden die Leute diverse verschiedene Versionen nutzen mit denen wir uns herumschlagen müssen.

Sollte jemand dies wirklich wollen, man kann den Manager auch selber kompilieren und die Option entfernen…

**Comment by dmolineus** [comment]
> Ich bin vehement gegen eine solche Option. Ein defekter Manager sollte repariert werden, eine alte Version nutzen ist keine sinnvolle Lösung. 

Es geht ja nur um das Zurückhalten einer defekten oder inkompatiblen Variante. Ein Hinweis, dass ein Update verfügbar ist, wird meines Erachtens doch von den meisten auch genutzt und ein Update durchgeführt. 

Ist für ein Produktivsystem halt ärgerlich, wenn es durch ein automatisches Update temporär nicht mehr nutzbar ist. Aber irgendwie ist das wohl gerade trendy...

**Comment by BugBuster1701** [comment]
Da bleibt dir dann nur übrig, das last_update in der Datei contao-manager/manager.json hochzusetzen.

**Comment by aschempp** [comment]
Bitte nicht 😉

**Comment by agoat** [comment]
> Ich bin vehement gegen eine solche Option. Ein defekter Manager sollte repariert werden, eine alte Version nutzen ist keine sinnvolle Lösung. In kürzester Zeit werden die Leute diverse verschiedene Versionen nutzen mit denen wir uns herumschlagen müssen.

Natürlich sollte ein defekter Manager möglichst schnell geupdated werden. Aber vielleicht ist ja das update defekt bzw. bringt diverse Probleme.
Wie @dmolineus bereits anregte, geht es mehr um das vorübergehende zurückhalten eines Updates. Vielleicht möchte ich auf dem Productionserver nur ein bundle updaten aber das Manager Update später machen (um mögliche Probleme zu vermeiden - die aktuelle Version lief ja bereits auf meinem Server).

Wie wäre es wenn nach der Anmeldung bzw. jetzt bei der Beta11 Version beim System Check ein Hinweis auf eine neue Version kommt, mit der Frage ob man diese übergehen möchte. Dann käme der Updatehinweis jedesmal beim Anmelden und wird sicherlich nach dem dritten mal auch ausgeführt.

Und Support gibt's nur für die neueste Version.
