### ISSUE TITLE
Check for missing ZIP support

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [contao/contao-manager#129]
When install ext from Contao Manager get error "Installation failed, reverting composer.json to its original content."

**Comment by aschempp** [comment]
The console message should tell you why this happens, probably because a dependency could not be resolved.

**Comment by 15w34r0n3D4y** [comment]
Using version ^2.0 for madeyourday/contao-rocksolid-custom-elements
/var/www/contao-cm/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 1 install, 0 updates, 0 removals
    <warning>Failed to download madeyourday/contao-rocksolid-custom-elements from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/5.6/cli/php.ini</warning>
    <warning>Now trying to download from source</warning>
  - Installing madeyourday/contao-rocksolid-custom-elements (v2.0.2): 
Installation failed, reverting /var/www/contao-cm/composer.json to its original content.
--------------------------------------------------------
**Exception occured: Unable to launch a new process.**

**Comment by aschempp** [comment]
> Failed to download madeyourday/contao-rocksolid-custom-elements from dist: The zip extension and unzip command are both missing, skipping.

Looks like your server does not supply basic Composer requirements. We should add a integrity check for that.

**Comment by 15w34r0n3D4y** [comment]
Ok I install zip unzip and php5.6-zip and now get error...

Using version ^2.0 for madeyourday/contao-rocksolid-custom-elements
/var/www/contao-cm/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 1 install, 0 updates, 0 removals
  - Installing madeyourday/contao-rocksolid-custom-elements (v2.0.2): Downloading (100%)
    <warning>**Failed to download madeyourday/contao-rocksolid-custom-elements from dist: Unable to launch a new process.**</warning>
    <warning>Now trying to download from source</warning>
  - Installing madeyourday/contao-rocksolid-custom-elements (v2.0.2): 
Installation failed, reverting /var/www/contao-cm/composer.json to its original content.
--------------------------------------------------------
Exception occured: Unable to launch a new process.

**Comment by 15w34r0n3D4y** [comment]
I tried in terminal with command "composer require madeyourday/contao-rocksolid-custom-elements@v2.0.2" and  get error:

"Could not find package madeyourday/contao-rocksolid-custom-elements@v2.0.2 at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability"

and then need install old version contao-rocksolid-custom-elements (v2.0.1) and old version works fine.

**Comment by aschempp** [comment]
Please keep this open, as I said we need to add a check for this issue in the Manager.

**Comment by 15w34r0n3D4y** [comment]
Ok, sorry.

Btw how can I terminate first process when installation complete? 
I get everytime when install new package "Unable to launch a new process." error and need everytime restart server, then can install normal package.

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
