### ISSUE TITLE
No valid JSON - background-process.get.json

### ISSUE THREAD

**Issue by fenepedia** [contao/contao-manager#130]
ERROR 500 Config file "…/web/manager/contao-manager/background-process.get.json" does not contain valid JSON.

Version: beta7
PHP 7

**Comment by Toflar** [comment]
What does it contain? :)

**Comment by fenepedia** [comment]
So wie es aussieht killt der den Prozess.

Hier die JSON:
`{"commandline":"\/usr\/bin\/php7-cgi '-q' '\/home\/.sites\/954\/site8878563\/web\/manager\/web\/contao-manager.phar.php' 'tenside:runtask' 'background-process' '-v' '--no-interaction'","cwd":"\/home\/.sites\/954\/site8878563\/web\/manager","timeout":null,"idleTimeout":null,"pid":636075,"status":"started"}`

**Comment by aschempp** [comment]
Fixed in 1.0.0-alpha8

**Comment by andre5tz** [comment]
Hallo,

ich habe aktuell die gleiche Fehlermeldung mit Contao Manager Beta 13.
**ERROR 500 Cannot delete a running process.** 

In der background-process.get.json steht folgender Inhalt:
`{"id":"background-process","commandline":"\/opt\/plesk\/php\/7.1\/bin\/php '-q' '\/var\/www\/vhosts\/...\/httpdocs\/...\/contao-4-4-lts\/web\/contao-manager.phar.php' 'tenside:runtask' 'background-process' '-v' '--no-interaction'","cwd":"\/var\/www\/vhosts\/...\/httpdocs\/...\/contao-4-4-lts","status":"ready","meta":{"type":"upgrade"},"timeout":0}`

Wenn ich nun die Datei background-process.get.json lösche und in Plesk die php-Einstellungen für den Server "übernehme" (Einstellung in Plesk), dann kann ich den Conato Manager wieder 1x zum Aktualisieren der Pakete nutzen.
Zumindest in den Versionen vor der Beta 13 oder 12 lief es, bin mir da nicht ganz sicher.
Provider ist netclusive.de.

Viele Grüße und vielen Dank :-)
André

**Comment by andre5tz** [comment]
Kurz nach meinem Fehlerbericht ging dann beim Contao-Manager gar nichts mehr. Ich habe dann [über die Konsole](https://community.contao.org/de/showthread.php?68988-Contao-Manager-1-0-0-beta12-Error-500&p=461261&viewfull=1#post461261) 
`wget https://getcomposer.org/download/1.6.2/composer.phar
php composer.phar update`
ausgeführt und nun ist wieder alles problemlos durchgelaufen!?
Vielleicht war einfach nur in meiner Installatin was "kaputt", was der Contao-Manager nicht reparieren konnte.

**Comment by Webstylerin** [comment]
Ja, das kann durch aus sein, habe auch schon eine unvollständige Manager-Installation via Composer reparieren können. :)

**Comment by aschempp** [comment]
Zur Info, das geht auch direkt über den Manager. `php contao-manager.phar.php composer update` ;)
