### ISSUE TITLE
Unterscheidung "Contao 4 Bundles" und  "Contao 3 Erweiterungen" problematisch

### ISSUE THREAD

**Issue by Metis77** [contao/contao-manager#131]
Im Contao Manager werden Contao Module unterschieden nach "Contao 4 Bundles" und  "Contao 3 Erweiterungen".

**Eindruck veralteter Module**
Diese Unterscheidung legt dem nicht so involvierten Anwender nahe, das Contao 3 Erweiterungen schon oder bald outdated sind.
Das vermittelt einen völlig falschen Eindruck.

Im letzten Jahr haben wir viel Geld und Zeit in die Entwicklung von Contao Modulen investiert, die explizit auch für Contao 4 geschrieben wurden.
Um so enttäuschter bin ich nun von der Darstellung dieser Module.

**Durchsuchbarkeit**
Des weiteren macht diese Trennung es echt schwierig, module zu suchen. Weil so muss man immer ein beiden Listen suchen.

Ich würde daher vorschlagen, beide Listen zusammen zu fassen.
Bei jeder einzelnen Erweiterung dann aber per Info unterscheiden: "Contao Bundle" oder "Contao Erweiterung". Ohne die Version 3 zu nennen.

**Comment by aschempp** [comment]
Diese Unterscheidung existiert wegen technischen Limitierungen von packagist.org, der Quelle aller Composer-Packete. Wir sind hier bereits mit den Composer-Entwicklern in Kontakt um dies entsprechend anzupassen.

**Comment by Metis77** [comment]
Ah super!

Vielleicht macht es aber auch jetzt schon Sinn, einfach die Bezeichnung zu ändern.

Ich fände  "Contao Bundle" und "Contao Erweiterung" weniger verwirrend.
So entsteht nicht der Eindruck, etwas veraltetes zu installieren, wie wenn man auf "Contao 3 Erweiterungen" klickt.

**Comment by aschempp** [comment]
In Version 1.0.0-beta9 ist die Option nun nicht mehr nötig 😎

**Comment by Metis77** [comment]
Super! Danke euch.
