### ISSUE TITLE
Onebit.cz: Error 500 Unerwarteter Status API

### ISSUE THREAD

**Issue by jankout** [contao/contao-manager#132]
Hallo liebes Entwicklerteam, 

wenn ich den Contao-Manager bei dem tschechischen Anbieter onebit.cz aufrufe, kommt gleich die Fehlermeldung _Error 500 Unerwarteter Status API_. 

http://contao4.kcrehlo.cz/contao-manager.phar.php

Kann ich es irgendwie selber beeinflussen? Danke.

**Comment by jankout** [comment]
Jetzt gibt es folgende Fehlermeldung: integrity.process.detail. Siehe http://contao4.kcrehlo.cz/contao-manager.phar.php Muss ich etwas seitens des Anbieters aktivieren lassen?

**Comment by aschempp** [comment]
Die Meldung ist leider aktuell noch kaputt, wäre aber diese hier: https://github.com/contao/contao-manager/blob/develop/api/Resources/i18n/de.yml#L8-L10

Auf deinem Server scheint *proc_open* nicht verfügbar.

**Comment by jankout** [comment]
Verstehe. Danke. Ich habe den Anbieter bereits kontaktiert. Er argumentiert, dass er das aus Sicherheitsgründen nicht erlauben möchte. 

Sonst fehlt im deutschen Text bei Wort _Kommandozeilentasks_ ein _D_. Hier der ganze korrigierte Text.

'Die Funktionen "proc_open" und "proc_close" sind notwendig, um Kommandozeilentasks im Hintergrund auszuführen. Bitte fragen Sie bei Ihrem Hosting-Anbieter nach, warum die Funktionen nicht verfügbar sind; weder der Contao Manager noch Contao 4 laufen ohne sie.'

**Comment by aschempp** [comment]
Danke für die Textkorrektur, ich habe sie auf www.transifex.com eingepflegt. Ohne *proc_open* kann der Manager leider nicht funktionieren, dagegen kann ich nichts tun. Das *Sicherheitsargument* ist aber eher eine Ausrede bzw. ein Problem dieses Anbieters, denn viele Hoster erlauben das und bei korrekter Serverkonfiguration dürfte das auch kein Problem sein.

**Comment by jankout** [comment]
Verstehe. Ich kenne das bei anderen Anbietern auch, dass sie es ohne jegliche Ausreden anbieten. Dieser ist wirklich schlecht.
