### ISSUE TITLE
Automaschiner Logout

### ISSUE THREAD

**Issue by dmolineus** [contao/contao-manager#134]
Läuft die Session ab, so sollte automatisch auch eine Meldung im Contao Manager kommen, am besten mit Loginform. 

Desweiteren wäre es super, wenn man die Dauer der Session konfigurieren könnte.

**Comment by aschempp** [comment]
Dazu müsste der Manager in regelmässigen Abständen ein API-Ping machen…

**Comment by x-christian-romeni** [comment]
Ja, das ständige neu einloggen ist etwas nervig.. Vor allem weil man entweder das Passwort von Contao (Login) oder das vom Manager speichern kann.. Weil selbe Domain und so... Also muss man sich ständig entweder hier oder da neu einloggen.
Wäre super wenn es hier eine Möglichkeit gibt..

**Comment by frontendschlampe** [comment]
> Vor allem weil man entweder das Passwort von Contao (Login) oder das vom Manager speichern kann.. Weil selbe Domain und so... 

mit einem Passwortmanager ist das kein Problem ;-)
