### ISSUE TITLE
Installation von Metapackages

### ISSUE THREAD

**Issue by dmolineus** [contao/contao-manager#135]
Bisher konnte man Composer Pakete vom Typ Metapackages installieren (z.b. bei [MetaModels](https://github.com/metamodels/bundle_all)). Manuell über Composer funktioniert es weiterhin auch wunderbar. D.h. die geladenen Abhängigkeiten, vom Typ Contao-Bundle werden korrekt geladen.

Leider lassen sich Metapackages derzeit nicht über den Contao Manager installieren. Außerdem erfolgt der Hinweis, dass das Paket inkompatibel wäre. 

Klar könnte ich den Typ zu contao-bundle ändern, ein Symfony-Bundle hinzufügen und das Manager Plugin definieren... 

Ich fände es allerdings super, wenn der Contao Manager zukünftig auch Metapackages installieren kann (auch auf die Gefahr hin, dass eines tatsächlich inkompatibel sein könnte).

**Comment by aschempp** [comment]
Interessantes Problem. Wie könnte der Manager erkennen ob das Metapackage für Contao ist oder nicht? Wir erlauben ja (aktuell) keine Installation von Paketen die nicht für Contao vorgesehen sind (PHP Libraries).

**Comment by dmolineus** [comment]
Darüber habe ich auch schon nachgedacht. Theoretisch könnte er prüfen ob die Abängigkeiten des Metapackage vom Typ `contao-bundle` oder `contao-module` sind und dann das Paket akzeptieren.

Ist natürlich aufwendiger von der Überprüfung, aber möglich. 

Darauf zu prüfen, dass mindestens eins die Anforderungen akzeptiert, halte ich nicht für hilfreich. Wenn dann sollte ja das contao-bundle seine Abhängigkeiten von Dritt-Bundles definieren und diese über das Plugin konfigurieren.

**Comment by Toflar** [comment]
Ich würde da eher den Weg wählen, dass wir die Radios wie sie jetzt sind behalten, wobei das erste und per default gewählte einfach nach `contao-bundle` und `contao-module` filtert und das andere wäre dann `beliebige Pakete`. 99.9% aller User werden ersteres verwenden und müssen nichts spezielles tun/wissen und die anderen dürften dann etwas mehr von Composer etc. verstehen und dann gibt es imho auch keinen Grund, dort nochmal irgendwas zu prüfen (abgesehen davon, dass Dritt-Bundles nicht per API durchforstet werden können).

**Comment by aschempp** [comment]
Das sehe ich eben nicht so. Der Manager sollte gar nichts zur Installation anbieten was nicht funktionieren kann. Wenn du als Entwickler eine Library benötigst, dann kannst du die per Kommandozeile installieren und der Manager erkennt die. Aber dann bist du ja Entwickler.

Eine weitere Auswahl wird zwangsläufig dazu führen dass Leute nach *event* suchen, sich *league/event* installieren und dann schreiben dass nichts funktioniert…

**Comment by BugBuster1701** [comment]
Würde es denn nicht reichen, wenn das Metapackage nur den Typ zu contao-bundle ändert?
Das muss doch selber kein Managed Bundle sein, hauptsache die Abhängigkeiten sind es, wo es nötig ist.

**Comment by aschempp** [comment]
Bitte teste es nochmals in der Beta9. Metapackages werden jetzt auch gefunden aber könnte sein dass er sie als nicht-installierbar markiert weil sie kein contao/core-bundle requiren. Das wär dann ein Bug den ich noch korrigieren muss.

**Comment by dmolineus** [comment]
Metapackages sind noch als Nicht-Installierbar markiert. Beispiel contao-bootstrap/bundle

Ich hatte auch testweise mal mit dem Type contao-bundle probiert, konnte es dennoch nicht installieren. Kann es sein, dass nicht alle Branches überprüft werden auf Kompatibilität (es lag noch kein Release vor, nur ein Github Branch).

**Comment by aschempp** [comment]
contao-bootstrap/bundle is now correctly detected in the package indexer

**Comment by zonky2** [comment]
@aschempp have the manager a new indexer? it´s not possibel to install contao-bootstrap/bundle now

![screens](https://user-images.githubusercontent.com/1045318/44363384-5caa2580-a4c4-11e8-8582-a1e6ecf8ec8e.jpg)

**Comment by aschempp** [comment]
Yeah, that's a bug in the [package-indexer](https://github.com/contao/package-indexer/) @Toflar. Instead of checking the dependency of `contao/core-bundle` on the metapackage it should check the dependency of the dependencies…

**Comment by aschempp** [comment]
Can you please create a new issue because this one has already been fixed and closed.

**Comment by zonky2** [comment]
related https://github.com/contao/contao-manager/issues/322
