### ISSUE TITLE
Contao Manager hangs

### ISSUE THREAD

**Issue by b-fender** [contao/contao-manager#138]
Hi!

Debian Jessie
Apache 2.4.10
PHP 5.6.30 (CLI)
contao-4.4.1 "managed" Version
Contao Manager 1.0.0-beta8

Auf lokalem Entwicklungs-Webserver mit Virtual Box mit ausreichend RAM. (5GB)

Bei mir bleibt der Contao Manager mit "Konsolentask gestartet" hängen. In der Konsole gibt es aber keine Fehlermeldung. Abbrechen mit "Abbrechen" lässt sich der Prozess auch nicht.
Eine Installation ohne Contao Manager lief ohne Probleme durch.

Im Logfile
contao-manager/task-background-process.log auch keine Meldung dazu.

Meldungen des Konsolentasks:

Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 5 updates, 0 removals

    Updating symfony/symfony (v3.3.4 => v3.3.5): Downloading (100%)
    Updating friendsofsymfony/http-cache-bundle (2.1.0 => 2.1.1): Downloading (100%)
    Updating terminal42/header-replay-bundle (1.0.0 => 1.1.1): Downloading (100%)
    Updating knplabs/knp-time-bundle (1.7.3 => 1.7.4): Downloading (100%)
    Updating tecnickcom/tcpdf (6.2.12 => 6.2.13): Downloading (100%)
    Writing lock file
    Generating optimized autoload files

    Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

Added/updated the web/app_dev.php file.
Added/updated the web/app.php file.

// Clearing the cache for the prod environment with debug
// false

[OK] Cache for the "prod" environment (debug=false) was successfully cleared.

// Warming up the cache for the prod environment with debug
// false

[OK] Cache for the "prod" environment (debug=false) was successfully warmed.

Trying to install assets as relative symbolic links.

  Bundle                   Method / Error    

✔ ContaoCoreBundle relative symlink
✔ ContaoCalendarBundle relative symlink
✔ ContaoCommentsBundle relative symlink
✔ ContaoFaqBundle relative symlink
✔ ContaoNewsBundle relative symlink
✔ ContaoNewsletterBundle relative symlink

[OK] All assets were successfully installed.

Added/updated the system/initialize.php file.

  Symlink                                 Target / Error                                                  

✔ web/files/theme files/theme
✔ web/system/modules/mobile_menu/assets system/modules/mobile_menu/assets
✔ system/themes/flexible vendor/contao/core-bundle/src/Resources/contao/themes/flexible
✔ web/assets assets
✔ web/system/themes system/themes
✔ system/logs var/logs

Ein paar (Fehler)meldungen aus: contao-manager/logs/api-2017-07-19.log:

[19-Jul-2017 18:37:05 Europe/Berlin] [2017-07-19 18:37:03] request.INFO: Matched route "task_put". {"route":"task_put","route_parameters":{"_controller":"contao_manager.controller.tasks:putTask","_route":"task_put"},"request_uri":"http://contao4.debian.local/contao-manager.phar.php/api/task?_locale=de","method":"PUT"} []
[19-Jul-2017 18:37:05 Europe/Berlin] [2017-07-19 18:37:03] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[19-Jul-2017 18:37:05 Europe/Berlin] [2017-07-19 18:37:03] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[19-Jul-2017 18:37:05 Europe/Berlin] [2017-07-19 18:37:03] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[19-Jul-2017 18:37:05 Europe/Berlin] [2017-07-19 18:37:03] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"zzzzzz\", authenticated=true, roles=\"\"))","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[19-Jul-2017 18:37:05 Europe/Berlin] [2017-07-19 18:37:03] security.DEBUG: **Guard authenticator set no success response: request continues.** {"authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[19-Jul-2017 18:37:05 Europe/Berlin] [2017-07-19 18:37:03] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []

**Comment by aschempp** [comment]
Die Meldung scheint doch erfolgreich? Was genau ist das Problem?

**Comment by b-fender** [comment]
Das Problem ist, dass das Konsolenfenster sich nicht schliesst, und auch nicht schliessen lässt. Und bei jedem Öffnen wieder erscheint. Ich hatte allerdings zuerst Contao 4.4.1 per contao/install installiert.
Und dann nachträglich den Contao Manager ins /web Verzeichnis geladen und ausgeführt.
Das mag der Grund dafür gewesen sein, dass es hier stehenblieb... Die (Neu)Installation von Contao 4.4.1 direkt über den Contao-Manager hat aber soweit funktioniert.

**Comment by herrrilke** [comment]
ich habe das gleiche problem.

contao 4.4.1 installiert und nachträglich den CM geladen und ausgeführt.
der lief dann soweit, zeigte die installierten erweiterungen und ich konnte die zur verfügung stehenden sehen.

beim versuch mittels CM die backup erweiterung zu laden, erhalten ich die meldung

`Error: "Out of memory (allocated 73568256)`
 
zugewiesen waren 128 MB RAM, nun habe ich 256 MB freigegeben, kann aber den CM nicht mehr beenden.

ich komme immer nur zurück auf das modale fenster:

<>---------------------------------------------------------------------<> 
"Pakete werden installiert"

Konsolentask gestartet …
 
[Abbrechen]
<>---------------------------------------------------------------------<> 

jedoch gibt [Abbrechen] zwar einen JS alert aus, hat aber keine erkennbare funktion.
auch eine anmeldung ein einem neuen browser bringt nur dieses fenster wieder zur anzeige.

**Comment by herrrilke** [comment]
post im forum ist hier: https://community.contao.org/de/showthread.php?67084-Hinweise-zum-Contao-Manager&p=446720&viewfull=1#post446720

**Comment by b-fender** [comment]
"Out of memory" ist in meiner Fehlermeldung (s.o) allerdings nicht enthalten.
Bei mir gibt es keine Fehlermeldung.

**Comment by herrrilke** [comment]
nein, da hast du recht.
aber das verhalten der modalen meldung ist das gleiche: sie läßt sich nicht schließen, nicht zurücksetzen, ist bei erneuter anmeldung stets wieder vorhanden und blockiert so den ganzen CM.

**Comment by b-fender** [comment]
so ist es!
Jedenfalls liegt es wohl nicht (nur) am memory-limit.

**Comment by b-fender** [comment]
Mit dem letzten Update des Contao Managers ist der Fehler "Contao Manager hangs" bei mir zumindest verschwunden und alles läuft soweit prima. Danke!

**Comment by herrrilke** [comment]
hallo,
bei mir nicht (version .10)

**Comment by b-fender** [comment]
Sorry!
Bei Dir kommt aber auch noch das Memory Limit dazu, zu wenig RAM für Composer-Prozesse...
Damit wird der Contao-Manager wohl sowieso nicht funktionieren.
Habe das Ticket trotzdem nochmal für Dich geöffnet...

**Comment by herrrilke** [comment]
danke für's wieder öffnen!
btw: das problem hängt nicht am memory limit: das liegt nun bei 1024 MB. 
aber: gleiches bild, der CM beta 10 hängt bei allen aktionen.

**Comment by WebDucer** [comment]
Hab das gleiche Problem. Beim Versuch die Pakete zu aktualisieren, hat sich der CM aufgehängt. Nach der Anmeldung erscheint sofort das modale Fenster, das sich nicht mehr schließen lässt. Es sind auch keine Fehlermeldungen zu sehen.

Wie kann ich es korrigieren (gern auch über SSH).

```bash
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 1 update, 0 removals
  - Updating fritzmg/contao-sharebuttons (2.0.0 => 2.0.1): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

 Added/updated the web/app_dev.php file.
 Added/updated the web/app.php file.

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  


 // Warming up the cache for the prod environment with debug                    
 // false                                 
```

**Comment by aschempp** [comment]
Du müsstest die Prozess-Dateien im `/contao-manager` Ordner manuell löschen.

**Comment by WebDucer** [comment]
Danke. Hat gut geklappt.
