### ISSUE TITLE
ERROR 500 bei Mittwald

### ISSUE THREAD

**Issue by NinaG** [contao/contao-manager#139]
Ich habe eine C4.3-Website auf einem Account auf einem Managed vServer L bei Mittwald mit PHP 7.1.1 und MySQL 5.6.19. Das Update per SSH auf C4.4 hat funktioniert und die Website läuft.

Wenn ich aber versuche den Contao Manager aufzurufen, kommt nur:
```
ERROR 500 Unknown installation status
Some files were found on your server but no known Contao version could be detected.
You must either manually repair your application or remove the following files and folders to install Contao:

 - .gitignore
 - README.md
 - app
 - assets
 - composer.json
 - composer.lock
 - files
 - system
 - templates
 - var
 - vendor
```

Laut composer habe ich:
```
 composer info
clue/stream-filter                 v1.3.0    A simple and modern approach...
composer/ca-bundle                 1.0.7     Lets you find a path to the ...
contao-components/ace              1.2.6     ACE code editor integration ...
contao-components/chosen           1.1.7     Chosen integration for Conta...
contao-components/colorbox         1.6.4     Colorbox integration for Con...
contao-components/colorpicker      1.4.0.1   Color picker integration for...
contao-components/compass          0.12.2.1  Compass integration for Cont...
contao-components/contao           7.1.1     Contao Open Source CMS compo...
contao-components/datepicker       2.2.0.3   Date picker integration for ...
contao-components/dropzone         4.3.0     DropZone integration for Con...
contao-components/highlight        8.9.1     Highlight.js integration for...
contao-components/html5shiv        3.7.3     HTML5 Shiv integration for C...
contao-components/installer        1.2.5     Contao components installer
contao-components/jquery           1.12.4    jQuery integration for Conta...
contao-components/jquery-ui        1.12.1    jQuery UI integration for Co...
contao-components/mediabox         1.5.4.1   Mediabox integration for Con...
contao-components/mediaelement     4.1.3     MediaElement.js integration ...
contao-components/mootools         1.6.0.4   MooTools integration for Con...
contao-components/respimage        1.4.2     Respimage.js integration for...
contao-components/simplemodal      2.0.5     SimpleModal integration for ...
contao-components/swipe            2.0.6.1   A JavaScript touch slider wi...
contao-components/tablesort        3.4.8     Contao Open Source CMS table...
contao-components/tablesorter      2.0.5.5   jQuery tablesorter integrati...
contao-components/tinymce4         4.6.2.1   TinyMCE 4 integration for Co...
contao/calendar-bundle             4.4.1     Adds calendar functionality ...
contao/comments-bundle             4.4.1     Adds comments functionality ...
contao/core-bundle                 4.4.1     Contao 4 core bundle
contao/faq-bundle                  4.4.1     Adds FAQ functionality to Co...
contao/image                       0.3.4     Contao image library
contao/imagine-svg                 0.1.4     Contao Imagine SVG library
contao/installation-bundle         4.4.1     Required to install and upda...
contao/listing-bundle              4.4.1     Allows to list arbitrary dat...
contao/manager-bundle              4.4.1     Contao 4 manager bundle
contao/manager-plugin              2.1.0     Contao 4 manager plugin
contao/news-bundle                 4.4.1     Adds news functionality to C...
contao/newsletter-bundle           4.4.1     Adds newsletter functionalit...
doctrine/annotations               v1.4.0    Docblock Annotations Parser
doctrine/cache                     v1.6.1    Caching library offering an ...
doctrine/collections               v1.4.0    Collections Abstraction library
doctrine/common                    v2.7.2    Common Library for Doctrine ...
doctrine/dbal                      v2.5.12   Database Abstraction Layer
doctrine/doctrine-bundle           1.6.8     Symfony DoctrineBundle
doctrine/doctrine-cache-bundle     1.3.0     Symfony Bundle for Doctrine ...
doctrine/inflector                 v1.1.0    Common String Manipulations ...
doctrine/lexer                     v1.0.1    Base library for a lexer tha...
fig/link-util                      1.0.0     Common utility implementatio...
friendsofsymfony/http-cache        2.0.1     Tools to manage HTTP caching...
friendsofsymfony/http-cache-bundle 2.1.1     Set path based HTTP cache he...
guzzlehttp/guzzle                  6.3.0     Guzzle is a PHP HTTP client ...
guzzlehttp/promises                v1.3.1    Guzzle promises library
guzzlehttp/psr7                    1.4.2     PSR-7 message implementation...
imagine/imagine                    v0.6.3    Image processing for PHP 5.3
jdorn/sql-formatter                v1.2.17   a PHP SQL highlighting library
jeremykendall/php-domain-parser    3.0.0     Public Suffix List based URL...
knplabs/knp-menu                   2.2.0     An object oriented menu library
knplabs/knp-menu-bundle            2.1.3     This bundle provides an inte...
knplabs/knp-time-bundle            1.7.4     Knplabs time bundle makes yo...
leafo/scssphp                      v0.6.7    scssphp is a compiler for SC...
league/uri                         4.2.2     URI manipulation library
lexik/maintenance-bundle           v2.1.1    This bundle allows you to pl...
matthiasmullie/minify              1.3.46    CSS & JS minifier
matthiasmullie/path-converter      1.1.0     Relative path converter
michelf/php-markdown               1.7.0     PHP Markdown
monolog/monolog                    1.23.0    Sends your logs to files, so...
nelmio/cors-bundle                 1.5.3     Adds CORS (Cross-Origin Reso...
nelmio/security-bundle             2.4.0     Extra security-related featu...
oyejorge/less.php                  v1.7.0.14 PHP port of the Javascript v...
paragonie/random_compat            v2.0.10   PHP 5.x polyfill for random_...
patchwork/utf8                     v1.3.1    Portable and performant UTF-...
php-http/client-common             1.5.0     Common HTTP Client implement...
php-http/discovery                 1.2.1     Finds installed HTTPlug impl...
php-http/guzzle6-adapter           v1.1.1    Guzzle 6 HTTP Adapter
php-http/httplug                   v1.1.0    HTTPlug, the HTTP client abs...
php-http/message                   1.6.0     HTTP Message related tools
php-http/message-factory           v1.0.2    Factory interfaces for PSR-7...
php-http/promise                   v1.0.0    Promise used for asynchronou...
phpspec/php-diff                   v1.1.0    A comprehensive library for ...
phpunit/php-token-stream           1.4.11    Wrapper around PHP's tokeniz...
psr/cache                          1.0.1     Common interface for caching...
psr/container                      1.0.0     Common Container Interface (...
psr/http-message                   1.0.1     Common interface for HTTP me...
psr/link                           1.0.0     Common interfaces for HTTP l...
psr/log                            1.0.2     Common interface for logging...
psr/simple-cache                   1.0.0     Common interfaces for simple...
sensio/distribution-bundle         v5.0.20   Base bundle for Symfony Dist...
sensio/framework-extra-bundle      v3.0.26   This bundle provides a way t...
sensiolabs/ansi-to-html            v1.1.3    A library to convert a text ...
sensiolabs/security-checker        v4.0.4    A security checker for your ...
simplepie/simplepie                1.5       A simple Atom/RSS parsing li...
swiftmailer/swiftmailer            v5.4.8    Swiftmailer, free feature-ri...
symfony/monolog-bundle             v2.12.1   Symfony MonologBundle
symfony/polyfill-intl-icu          v1.4.0    Symfony polyfill for intl's ...
symfony/polyfill-mbstring          v1.4.0    Symfony polyfill for the Mbs...
symfony/polyfill-php56             v1.4.0    Symfony polyfill backporting...
symfony/polyfill-php70             v1.4.0    Symfony polyfill backporting...
symfony/polyfill-util              v1.4.0    Symfony utilities for portab...
symfony/swiftmailer-bundle         v2.6.2    Symfony SwiftmailerBundle
symfony/symfony                    v3.3.5    The Symfony PHP framework
tecnickcom/tcpdf                   6.2.13    TCPDF is a PHP class for gen...
terminal42/header-replay-bundle    1.1.0     Send preflight requests for ...
true/punycode                      v2.1.1    A Bootstring encoding of Uni...
twig/twig                          v1.34.4   Twig, the flexible, fast, an...
ua-parser/uap-php                  v3.4.7    A multi-language port of Bro...
webmozart/assert                   1.2.0     Assertions to validate metho...
webmozart/path-util                2.3.0     A robust cross-platform util..`
```
Ich habe geschaut, ob da irgendeine „unerlaubte“ Datei oder ein Ordner wäre. Aber die Struktur sieht für mich normal aus:

```
app/
assets/
files/
system/
templates/
var/
vendor/
web/
.gitignore
composer.json
composer.lock
README.md
```

**Comment by NinaG** [comment]
Vielleicht relevant: Der Composer ist auf diesem Webspace global in der aktuellsten Version 1.4.2 installiertd.
Der Contao Manager  hat die Version 1.0.0-beta8.

Es gibt zu dem ganzen Vorgang auch einen Thread im Forum:
https://community.contao.org/de/showthread.php?67453-ERROR-500-Unknown-installation-status

**Comment by aschempp** [comment]
Composer ist für den Manager nicht relevant, da die Phar-Datei auch den Composer enthält. Das Problem ist vermutlich dass der Manager deinen PHP-Binary nicht findet, und entsprechend auch die Contao-Version nicht finden kann. Dazu muss ich allerdings erst den Installationsprozess umbauen (siehe #76) 😞 

Du könntest temporär eine `manager.json` von einem anderen Hosting kopieren und den Pfad entsprechend eintragen.

**Comment by NinaG** [comment]
Hm, die manager.json liegt ja eigentlich eine Ebene unter /web im Ordner /contao-manager/. 
Dieser ganze Ordner ist auf diesem Webspace gar nicht erst da. Soll ich also den kompletten Ordner rüberkopieren und dann die manager.json anpassen?

**Comment by BugBuster1701** [comment]
Aus dem Forum hier zur Ergänzung:
```
Beim Aufruf auf Kommandozeile von "php contao-manager.phar.php composer update"kommt :
Contao Manager 1.0.0-beta8
Usage: command [options] [arguments]
...
Notice: Undefined index: argv in phar:///html/c4/web/contao-manager.phar.php/api/console on line 59
```

**Comment by NinaG** [comment]
Ich habe folgendes gemacht:
Auf der Basisebene einen Ordner /contao-manager/ angelegt und darin die manager.json mit dem Minimalinhalt (Pfad so, wie er bei Mittwald gebraucht wird):
```
{
    "php_cli": "\/usr\/local\/bin\/php_cli",
}
```

Nun kann ich das erste Mal den Manager aufrufen (sehe die Aufforderung das Loginkonto anzulegen).

**Comment by NinaG** [comment]
Alles funktioniert nun.

**Comment by HStrandel** [comment]
**Ich glaube, dass ich hier auf meinem dedizierten Server die gleiche Problematik habe.**
Habe dazu auch einen Eintrag im Contao-Forum gemacht:
https://community.contao.org/de/showthread.php?67490-Nach-Installation-Package-Manager-nicht-aufrufbar.

Ich kann die Installation von Contao 4.4.1 erfolgreich durchführen und mich auch ins Backend von Contao einloggen. Der Contao-Manager meldet, dass der Konsolentask erfolgreich abgeschlossen ist.

-> Klick auf "Bestätigen & Schliessen" führt zurück auf den Startbildschirm des Contao Managers und verbleibt in einer "Endlosschleife".

Nach sehr langem warten versuche ich https://abc.xyz/contao-manager.phar.php/#/login nochmals aufzurufen und erhalten dann einen Error 500.

Contao funktioniert weiterhin aber ich kann keine Extensions/Packages installieren, da der Contao Manager dies irgendwie nicht zulässt.

**Eigener dedizierter Webserver mit Litespeed (kompatibel Apache):**
- SSL Let's encrypt
- 2GB RAM
- Composer 1.4.2
- PHP 7.1.

Installation mit Firefox durchgeführt.

**Log (/var/logs/)**
[2017-07-23 18:13:04] request.INFO: Matched route "contao_index". {"route":"contao_index","route_parameters":{"_toke n_check":true,"_controller":"Contao\\CoreBundle\\C ontroller\\FrontendController::indexAction","_scop e":"frontend","_locale":null,"_route":"contao_inde x"},"request_uri":"https://abc.xyz/","method":"GET"} []
[2017-07-23 18:13:04] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBun dle\\Security\\ContaoAuthenticator"} []
[2017-07-23 18:13:04] request.INFO: Matched route "contao_index". {"route":"contao_index","route_parameters":{"_toke n_check":true,"_controller":"Contao\\CoreBundle\\C ontroller\\FrontendController::indexAction","_scop e":"frontend","_locale":null,"_route":"contao_inde x"},"request_uri":"https://https://abc.xyz/","method":"GET"} []
[2017-07-23 18:13:04] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBun dle\\Security\\ContaoAuthenticator"} []
[2017-07-23 18:13:04] app.CRITICAL: An exception occurred. {"exception":"[object] (Contao\\CoreBundle\\Exception\\InternalServerErro rHttpException(code: 0): No root page found at /home/abcxyz/public_html/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:109, Contao\\CoreBundle\\Exception\\NoRootPageFoundExce ption(code: 0): No root page found at /home/abcxyz/public_html/vendor/contao/core-bundle/src/Resources/contao/classes/Frontend.php:340)"} []

Bedanke mich für jeden Hinweis / Hilfe.
Hans

**Comment by aschempp** [comment]
Es scheint als läuft die Contao-Installation nicht richtig. Kannst du per SSH mal folgenden Befehl ausführen und sehen was du bekommst?
`vendor/bin/contao-console contao:version`

**Comment by codiso** [comment]
Bis heute lief meine Contao 4.4.2 Installation mit dem Manger problemlos.
Dann hatte ich einen Bug in Contao und ich bin auf ein Backup zurück gegangen.
Konnte mich in das Backend von Contao sauber einloggen und die Symlinks neu anlegen, danach ging wieder alles von Seiten des Backend und des Frontend. Nur der Manager will  nicht mehr ???

<img width="876" alt="bildschirmfoto 2017-08-04 um 20 56 12" src="https://user-images.githubusercontent.com/2002902/28982805-63c22bf4-7957-11e7-9a08-f2ad9bb90f0d.png">

An der Ordnerstruktur und an composer.json, composer.lock habe ich keine Veränderung vorgenommen. Manager zeigt den Login und danach den zu sehenden Screen :-(

Wie bekomme ich den Manager wieder zum Laufen ???

**Comment by vier7** [comment]
Schließe mich codiso an, gibt es schon einen Workaround für den Fehler 500?

**Comment by HStrandel** [comment]
**Antwort an @aschempp** 

Der Ordner [~/public_html/vendor/bin] ist leer.
Somit führt der Befehl "vendor/bin/contao-console contao:version" zur folgenden Fehlermeldung: No such file or directory.

Habe die ganze Installation nochmals neu ausgeführt mit "Version 1.0.0-beta10" -> führt zum gleichen Ergebnis.

**Comment by HStrandel** [comment]
**Antwort an @aschempp** 

Da ich eine saubere Installation mit dem contao-manager (Beta 10) nicht hinbekommen habe, habe ich nun die gesamte Installation mit dem Composer (V. 1.5.1) gemacht:
"composer create-project contao/managed-edition ."

Danach habe ich die gewünschten Extension mit "composer require ..." installiert.
Es läuft nun alles sauber. Vielen Dank für Deine Bemühungen.

**Comment by aschempp** [comment]
Ich denke das Problem liesse sich lösen indem der `vendor` Ordner gelöscht und über Kommandozeile neu installiert wird. Am einfachsten vermutlich über `web/contao-manager.phar.php composer install`.

**Comment by janoschbatschi** [comment]
Selbe Problem hier mit Hetzner Level19

`vendor/bin/contao-console contao:version` liefert 4.4.3

Habe den `vendor` Ordner gelöscht und über `web/contao-manager.phar.php composer install` wieder sauber installiert. 

Aufruf von `contao-manager.phar.php` bringt

> ERROR 500 Unknown installation status
> Some files were found on your server but no known Contao version could be detected.
> You must either manually repair your application or remove the following files and folders to install Contao:
> 
> - README.md
> - app
> - assets
> - composer.json
> - composer.lock
> - favicon.ico
> - files
> - isotope
> - system
> - templates
> - var
> - vendor

**Comment by arno1979** [comment]
Ich möchte dieses Ticket noch mal ergänzen, weil ich gestern offensichtlich einen ganzen Webserver bei Mittwald mit der Verwendung des Contao Managers in der aktuellen Version 1.0.0-beta10 abgeschossen habe.

Ausgangssituation:
- Contao Manager im Ordner /web abgelegt
- Subdomain zum testen zeigt in den /web Ordner
- verwendet wird PHP 5.6

Als ich dann den Contao Manager gestartet habe, bekam ich lediglich die Kopfzeile mit dem Hinweis auf eine unsichere Verbindung angezeigt. Das Design vom Manager war sichtbar, aber die Eingabemaske zum Anlegen einen Manager Accounts ist nie erschienen.

Nach einiger Wartezeit habe per Reload versucht den Manager neu zu starten. Da war dann der Server aber schon ausgestiegen und ich bekam den 500er von Mittwald angezeigt.

Mittwald schrieb uns dazu:

> Ursache war das Ihr Server an das maximale Prozesslimit gestoßen ist, da sich folgenden Contao-Script 1000-fach selbst aufgerufen hat.

In dem Fall besonders unangenehm, weil auch noch andere Pakete auf dem Server davon betroffen waren und mehrere Webseiten dadurch ausgefallen sind.

Ich selber bin ehrlich gesagt gar nicht auf die Idee gekommen, dass der Manager der Auslöser für die Probleme sein könnte, weil ich von anderen Hostern und lokalen Installation zwar mit kleineren Problemen des Managers vertraut bin, aber nichts in dieser Größenordnung.

Ich weiß ja auch gar nicht, was dazu führt, dass der Manager sich selber endlos aufruft, vermute aber mal, dass er sich bei der Suche nach der PHP-Binary irgendwie verschluckt.
Mit dem Hinweis von Nina Gerling auf das manuelle Eintragen des PHP-Pfades in die `manager.json` konnte ich die Probleme jedenfalls umgehen.

Besser wäre es aber natürlich, wenn der Manager solche Probleme auch mit einer entsprechenden Fehlermeldung abfangen würde.

Viele Grüße
Arno

**Comment by martinschumann** [comment]
Bei (den mir bekannten) Mittwald-Paketen linkt `/usr/local/bin/php` auf das CGI-Binary ('cgi-fcgi') und nicht das CLI-Binary.

Der PhpExecutableFinder erwartet das verständlicherweise nicht.

Auch nach manueller Angabe des CLI-Binary in der `manager.json` und erfolgreicher Installation gibt der Manager die Usage-Klausel des CGI-Binary aus (wie BugBuster1701 schrieb):

    php web/contao-manager.phar.php about --json
    Contao Manager 1.0.0-beta10
    
    Usage:
      command [options] [arguments]
    
    Options:
      -h, --help            Display this help message
    ...

Eine Prüfung durch php_sapi_name() wäre natürlich das Beste.

**Comment by aschempp** [comment]
Mittwald wurde in Beta 11 der bekannten Liste von Hostern hinzugefügt und dieses Problem gelöst.
