### ISSUE TITLE
Document "forgot password"

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#14]
The password can currently be reset by deleting the `users.json` file in the `contao-manager` directory. We should add a topic about that to the Contao Manager manual.

**Comment by fenepedia** [comment]
https://github.com/fenepedia/contao-docs-fork/blob/feature/manager/manager/de/faq.md#contao-manager-zugangsdaten-vergessen

**Comment by aschempp** [comment]
New link: https://docs.contao.org/manual/installation/contao-manager/#hast-du-die-zugangsdaten-vom-contao-manager-vergessen

**Comment by netzarbeiter** [comment]
New link with the language prefix.

https://docs.contao.org/manual/de/installation/contao-manager/#hast-du-die-zugangsdaten-vom-contao-manager-vergessen

**Comment by aschempp** [comment]
The german link has been added in e072aaeb897634fda6a13014a7b815859ec87b46. I'm keeping the ticket open because we miss any other language still.

**Comment by aschempp** [comment]
This has been implemented a while ago in d815ee29e79fe86fb68b32ab45713b6faaf8c804
