### ISSUE TITLE
Beta 9 Suche nach Paketen funktioniert nicht

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao-manager#140]
Beta 9  - Bei Pakete suchen wird "Konnte keine Ergebnisse laden. Sind Sie online?" angezeigt. Siehe auch https://community.contao.org/de/showthread.php?67463-Contao-Manager-zeigt-keine-Pakete-zur-installation-an&p=446232#post446232

**Comment by aschempp** [comment]
Das liegt an Browser-seitigen Erweiterungen welche Javascript blockieren.

**Comment by aschempp** [comment]
Added in 883b9f6270b3e6b094fc1a2400fe31b03af87259
