### ISSUE TITLE
[beta9] Compatible packages listed as “incompatible”

### ISSUE THREAD

**Issue by ausi** [contao/contao-manager#141]
If you search for `terminal42/contao-changelanguage` the extension is listed as “incompatible”.

![contao-manager-search](https://user-images.githubusercontent.com/367169/28540206-bcc9c924-70b4-11e7-9cdd-9a2423fec893.png)

I think it is related to [contao/package-indexer Command/IndexCommand.php:210](https://github.com/contao/package-indexer/blob/376446e0551d39a144fd4c423d05ee952c517a3e/src/Command/IndexCommand.php#L210) because extensions that require `contao/core` in any version are marked as `$supported = false`.

**Comment by aschempp** [comment]
Fixed in https://github.com/contao/package-indexer/commit/4e47184a0b013087fee9afcac69e110d5a5384ef
