### ISSUE TITLE
W3W PHP binary Fehler

### ISSUE THREAD

**Issue by polyneo-florian** [contao/contao-manager#142]
Ich habe mit der Beta10 des Contao Managers versucht, die aktuellste Contao 4 bei w3w (https://www.w3w.de/ - Profi-Norm-Account) zu installieren.
SSL-Zertifikat für Subdomain welche direkt auf das web-Verzeichnis zeigt vorhanden, PHP 7.0.21 läuft soweit. Aufruf der .phar.php ohne Probleme, auch das Anlegen des Nutzer-Accounts klappt.

Mein Problem liegt jetzt darin, dass er mir mitteilt "This path does not contain a valid PHP binary.".
Allerdings habe ich bereits zwei Varianten des Pfades zum PHP 7 binary, welche ich direkt vom Support erhalten habe, ausprobiert - leider ohne Erfolg (/usr/bin/php70 und aufgelöst /usr/local/php2470/bin/php).

Kann hier das Problem beim Manager oder falsch gesetzten PHP-Einstellungen liegen, oder muss einfach doch noch ein richtiger Pfad her und die bisherigen zwei waren fehlerhaft?

**Comment by aschempp** [comment]
Der Fehler kann eigentlich nur zwei Gründe haben:
 1. der Pfad existiert gar nicht, bzw. keine ausführbare Datei. Es gibt Hoster bei denen SSH-Benutzer eine andere Umgebung haben als der Webprozess und die Pfade entsprechend anders sind.
 2. Die PHP-Binary gibt beim abrufen der Version einen Fehler aus oder kann z.B. keine Phar-Dateien verarbeiten. Wenn die Ausgabe nicht wie erwartet der Version entspricht sondern z.B. erst eine Fehlermeldung wegen einer falschen Konfiguration auf CLI kommt, kann der Manager dies nicht verarbeiten.

Am einfachsten wäre es in diesem Fall das per SSH zu prüfen, falls ein entsprechender Zugang vorhanden ist.

**Comment by polyneo-florian** [comment]
Danke für das Feedback Andreas.

Laut w3w-Support existiert der Pfad.
Unterstützt wird phar, sowohl laut Support als auch laut phpinfo.

SSH ist vorhanden, wie kann ich das also am einfachsten testen?

**Comment by aschempp** [comment]
Mit folgendem Befehl:

/pfad/zu/php /pfad/zu/contao-manager.phar.php about

**Comment by polyneo-florian** [comment]
Bekomme zumindest keinen Fehler angezeigt... :

 ------------------ -----------------------------------------------------------------------------------------------
  Contao Manager
 ------------------ -----------------------------------------------------------------------------------------------
  Version            1.0.0-beta10
  Environment        prod
  Debug              false
  Cache directory    phar:///home/www/polyneo/contao4-test/contao4/web/contao-manager.phar.php/api/Resources/cache
  Contao directory   /home/www/polyneo/contao4-test/contao4
  Data directory     /home/www/polyneo/contao4-test/contao4/contao-manager
 ------------------ -----------------------------------------------------------------------------------------------
  PHP
 ------------------ -----------------------------------------------------------------------------------------------
  Version            7.0.21
  Intl locale        en_US
  Timezone           Europe/Berlin
 ------------------ -----------------------------------------------------------------------------------------------
  Server
 ------------------ -----------------------------------------------------------------------------------------------
  IP                 91.233.xx.xx
  Hostname           xxxx.prohost.de
  Network Owner      (...)
  Country            Germany
  Operating System   Linux (...)
  Architecture       64 bits
 ------------------ -----------------------------------------------------------------------------------------------

**Comment by polyneo-florian** [comment]
Habe es nochmals mit mehreren Varianten des PHP Binary Pfades getestet, per SSH habe ich absolut keine Probleme, aber der Contao Manager zickt bei jeder Möglichkeit und will den Pfad nicht anerkennen...

Mittlerweile nutze ich die per Composer installierte Managed Edition für meine Test-Zwecke (läuft problemlos), für die Zukunft wäre der Contao Manager dann schon trotzdem schön. Aber ist ja aktuell auch noch die Beta, daher kommt Zeit kommt Rat. ;)

**Comment by aschempp** [comment]
Kannst du mir Zugang zum entsprechenden System ermöglichen? Meine Email findest du in meinem Profil.

**Comment by polyneo-florian** [comment]
@Georg-Git Aktuell noch nicht, allerdings habe ich das Problem nicht weiter verfolgt, da ich das ganze mittlerweile direkt per SSH umsetze.
Zeitnah will ich mir aber den Contao Manager in aktueller Version nochmal anschauen - sollte das Problem noch bestehen und ich eine Lösung finden lasse ich es euch wissen.

**Comment by Georg-Git** [comment]
OK - ich habe endlich die Lösung für Contao 4 auf einem w3w Server:

1.) PHP Pfad für PHP 7.2:
/usr/local/php2472/bin/php_
(Der Unterstrich am Ende ist die Lösung!)

2.) .user.ini Datei im root mit folgendem Einträgen:
opcache.enable = 0
memory_limit = 256M

3.) Leider bricht der Contao Manager dann ab, weil im root die .user.ini Datei liegen und noch eine andere config Datei von w3w.

Also muss man Contao noch eine Ebene tiefer installieren, z.B.
/contao4/web/contao-manager.phar.php

Und die Contao Domain muss dann natürlich auf den Pfad /contao4/web/ zeigen.

=> Dann klappt es auch auf w3w Server mit dem Contao Manager ....

**Comment by polyneo-florian** [comment]
Vielen Dank für die Lösung @Georg-Git ! 👍

**Comment by aschempp** [comment]
👍  am besten legt ihr die Info in's entsprechende Wiki dann sehen es alle gleich :)
