### ISSUE TITLE
Problem mit Upload-Datei

### ISSUE THREAD

**Issue by Thoni** [contao/contao-manager#143]
Hallo,

bei dem multifileupload von derhaeuptling funktioniert der Upload nicht.

Grund: Die Upload-Datei muss von zwei Symlinks weitergeleitet werden.

web/system/modules/multifileupload/assets -> ../../../../system/modules/multifileupload/assets
system/modules/multifileupload -> ../../vendor/derhaeuptling/contao-multi-file-upload-with-dropzone

Bei der zweiten Weiterleitung geht die Datei scheinbar verloren.
Setzt man beim ersten symlink das Ziel des zweiten ein, so funktioniert es.

Kann man künftig nicht einfach von Contao-Manager beide symlinks auf das 'echte' ziel setzen lassen?

Gibt es noch eine Möglichkeit, in die Erweiterung etwas einzusetzen, was den Fehler behebt?

Viele Grüße
Thoni

**Comment by aschempp** [comment]
Der Contao Manager hat damit nichts zu tun. Falls dies ein Contao 3 Modul ist, wird der Symlink vom [composer plugin](https://github.com/contao-community-alliance/composer-plugin] gemacht. Der Entwickler müsste das Problem aber wohl selber analysieren und eine Lösung finden.
