### ISSUE TITLE
EDIS - PHP-CLI Pfade

### ISSUE THREAD

**Issue by saress** [contao/contao-manager#144]
Hallo Andreas,

unser österreichischer Hosting-Provider EDIS hat netterweise die entsprechenden PHP-CLI Pfade für die von Contao 4 unterstützten PHP-Versionen in einem Knowledge-Base Eintrag zusammengefasst:

**PHP 7.1**
/usr/local/bin/edis-php-cli-71-stable-openssl
/usr/local/bin/edis-php-cli-71-stable-nognutls
 
**PHP 7.0**
/usr/local/bin/edis-php-cli-70-stable-openssl
/usr/local/bin/edis-php-cli-70-stable-nognutls

**PHP 5.6**
/usr/local/bin/edis-php-cli-56-stable-openssl
/usr/local/bin/edis-php-cli-56-stable-nognutls
 
**PHP 5.5**
/usr/local/bin/edis-php-cli-55-stable-openssl
/usr/local/bin/edis-php-cli-55-stable-nognutls

Weitere Details zu den PHP-Einstellungen finden sich hier:

[EDIS PHP Settings](https://support.edis.at/kb/a93/nuetzliche-infos-zu-php-eigenen-einstellungen-mittels-_user_ini-und-beispiel-php_ini-dateien.aspx)
[EDIS Webseite](http://www.edis.at/de/home/)

Es wäre super, wenn Du die providers.yml entsprechend ergänzen könntest.

Vielen Dank und beste Grüße
Sascha

**Comment by aschempp** [comment]
kannst du mir bitte mit dem Kommandozeilen-Belfehl `php web/contao-manager.phar.php about` die zusätzlich nötigen Informationen abrufen?

**Comment by aschempp** [comment]
Ich habe EDIS in 9a3ec7e2f911cb59d9af7a0c823ed774f2f96589 in die Liste aufgenommen, allerdings kann ohne Hostnamen keine automatische Erkennung stattfinden.
