### ISSUE TITLE
Installation contao 4.4 impossible

### ISSUE THREAD

**Issue by AgenceUpMotion** [contao/contao-manager#145]
I am the installation video of Contao 4.4 with the contao manager but this one blocks at this stage:

Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
✔ system/logs var/logs

Can you help me ?

I have tested on PC and MAC, as well as on Safari, Firefox and Chrome

**Comment by AgenceUpMotion** [comment]
The consol : 


Setting up Your Contao Application

Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
✔ system/logs var/logs
Annuler
 Cacher la console
Installing contao/managed-edition (4.4.2)
  - Installing contao/managed-edition (4.4.2): Downloading (100%)
Created project in /home/romainguuz/www/contao4/install-598845c8736ef
Loading composer repositories with package information
Installing dependencies from lock file
<warning>Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.</warning>
Package operations: 105 installs, 0 updates, 0 removals
  - Installing contao-components/installer (1.2.5): Downloading (100%)
  - Installing contao-components/ace (1.2.6): Downloading (100%)
  - Installing contao-components/chosen (1.1.7): Downloading (100%)
  - Installing contao-components/colorbox (1.6.4): Downloading (100%)
  - Installing contao-components/colorpicker (1.4.0.1): Downloading (100%)
  - Installing contao-components/compass (0.12.2.1): Downloading (100%)
  - Installing contao-components/contao (7.1.1): Downloading (100%)
  - Installing contao-components/datepicker (2.2.0.3): Downloading (100%)
  - Installing contao-components/dropzone (4.3.0): Downloading (100%)
  - Installing contao-components/highlight (8.9.1): Downloading (100%)
  - Installing contao-components/html5shiv (3.7.3): Downloading (100%)
  - Installing contao-components/jquery (1.12.4): Downloading (100%)
  - Installing contao-components/jquery-ui (1.12.1): Downloading (100%)
  - Installing contao-components/mediabox (1.5.4.1): Downloading (100%)
  - Installing contao-components/mediaelement (4.1.3): Downloading (100%)
  - Installing contao-components/mootools (1.6.0.4): Downloading (100%)
  - Installing contao-components/respimage (1.4.2): Downloading (100%)
  - Installing contao-components/simplemodal (2.0.5): Downloading (100%)
  - Installing contao-components/swipe (2.0.6.1): Downloading (100%)
  - Installing contao-components/tablesort (3.4.8): Downloading (100%)
  - Installing contao-components/tablesorter (2.0.5.5): Downloading (100%)
  - Installing contao-components/tinymce4 (4.6.2.1): Downloading (100%)
  - Installing twig/twig (v1.34.4): Downloading (100%)
  - Installing symfony/polyfill-util (v1.4.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.10): Downloading (100%)
  - Installing symfony/polyfill-php70 (v1.4.0): Downloading (100%)
  - Installing symfony/polyfill-php56 (v1.4.0): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.4.0): Downloading (100%)
  - Installing symfony/symfony (v3.3.5): Downloading (100%)
  - Installing symfony/polyfill-intl-icu (v1.4.0): Downloading (100%)
  - Installing psr/simple-cache (1.0.0): Downloading (100%)
  - Installing psr/log (1.0.2): Downloading (100%)
  - Installing psr/link (1.0.0): Downloading (100%)
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing psr/cache (1.0.1): Downloading (100%)
  - Installing fig/link-util (1.0.0): Downloading (100%)
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)
  - Installing doctrine/inflector (v1.1.0): Downloading (100%)
  - Installing doctrine/collections (v1.4.0): Downloading (100%)
  - Installing doctrine/cache (v1.6.2): Downloading (100%)
  - Installing doctrine/annotations (v1.4.0): Downloading (100%)
  - Installing doctrine/common (v2.7.3): Downloading (100%)
  - Installing webmozart/assert (1.2.0): Downloading (100%)
  - Installing webmozart/path-util (2.3.0): Downloading (100%)
  - Installing true/punycode (v2.1.1): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing php-http/message-factory (v1.0.2): Downloading (100%)
  - Installing clue/stream-filter (v1.3.0): Downloading (100%)
  - Installing php-http/message (1.6.0): Downloading (100%)
  - Installing php-http/discovery (1.2.1): Downloading (100%)
  - Installing php-http/promise (v1.0.0): Downloading (100%)
  - Installing php-http/httplug (v1.1.0): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.0): Downloading (100%)
  - Installing php-http/guzzle6-adapter (v1.1.1): Downloading (100%)
  - Installing php-http/client-common (1.5.0): Downloading (100%)
  - Installing friendsofsymfony/http-cache (2.0.1): Downloading (100%)
  - Installing friendsofsymfony/http-cache-bundle (2.1.1): Downloading (100%)
  - Installing terminal42/header-replay-bundle (1.1.1): Downloading (100%)
  - Installing tecnickcom/tcpdf (6.2.13): Downloading (100%)
  - Installing swiftmailer/swiftmailer (v5.4.8): Downloading (100%)
  - Installing symfony/swiftmailer-bundle (v2.6.3): Downloading (100%)
  - Installing simplepie/simplepie (1.5): Downloading (100%)
  - Installing sensio/framework-extra-bundle (v3.0.26): Downloading (100%)
  - Installing phpunit/php-token-stream (1.4.11): Downloading (100%)
  - Installing phpspec/php-diff (v1.1.0): Downloading (100%)
  - Installing patchwork/utf8 (v1.3.1): Downloading (100%)
  - Installing oyejorge/less.php (v1.7.0.14): Downloading (100%)
  - Installing nelmio/cors-bundle (1.5.3): Downloading (100%)
  - Installing michelf/php-markdown (1.7.0): Downloading (100%)
  - Installing matthiasmullie/path-converter (1.1.0): Downloading (100%)
  - Installing matthiasmullie/minify (1.3.46): Downloading (100%)
  - Installing jeremykendall/php-domain-parser (3.0.0): Downloading (100%)
  - Installing league/uri (4.2.2): Downloading (100%)
  - Installing leafo/scssphp (v0.6.7): Downloading (100%)
  - Installing knplabs/knp-time-bundle (1.7.4): Downloading (100%)
  - Installing knplabs/knp-menu (2.2.0): Downloading (100%)
  - Installing knplabs/knp-menu-bundle (2.1.3): Downloading (100%)
  - Installing imagine/imagine (v0.6.3): Downloading (100%)
  - Installing doctrine/doctrine-cache-bundle (1.3.0): Downloading (100%)
  - Installing jdorn/sql-formatter (v1.2.17): Downloading (100%)
  - Installing doctrine/dbal (v2.5.13): Downloading (100%)
  - Installing doctrine/doctrine-bundle (1.6.8): Downloading (100%)
  - Installing contao/imagine-svg (0.1.4): Downloading (100%)
  - Installing contao/image (0.3.4): Downloading (100%)
  - Installing contao/core-bundle (4.4.2): Downloading (100%)
  - Installing contao/calendar-bundle (4.4.2): Downloading (100%)
  - Installing contao/comments-bundle (4.4.2): Downloading (100%)
  - Installing contao/faq-bundle (4.4.2): Downloading (100%)
  - Installing contao/listing-bundle (4.4.2): Downloading (100%)
  - Installing monolog/monolog (1.23.0): Downloading (100%)
  - Installing symfony/monolog-bundle (v2.12.1): Downloading (100%)
  - Installing ua-parser/uap-php (v3.4.7): Downloading (100%)
  - Installing nelmio/security-bundle (2.4.0): Downloading (100%)
  - Installing lexik/maintenance-bundle (v2.1.1): Downloading (100%)
  - Installing contao/manager-plugin (2.1.0): Downloading (100%)
  - Installing sensiolabs/ansi-to-html (v1.1.3): Downloading (100%)
  - Installing composer/ca-bundle (1.0.7): Downloading (100%)
  - Installing sensiolabs/security-checker (v4.0.5): Downloading (100%)
  - Installing sensio/distribution-bundle (v5.0.20): Downloading (100%)
  - Installing contao/installation-bundle (4.4.2): Downloading (100%)
  - Installing contao/manager-bundle (4.4.2): Downloading (100%)
  - Installing contao/news-bundle (4.4.2): Downloading (100%)
  - Installing contao/newsletter-bundle (4.4.2): Downloading (100%)
Generating autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

 Added/updated the web/.htaccess file.
 Added/updated the web/app_dev.php file.
 Added/updated the web/app.php file.

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  


 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   


 Trying to install assets as relative symbolic links.

 --- ------------------------ ------------------ 
      Bundle                   Method / Error    
 --- ------------------------ ------------------ 
  ✔   ContaoCoreBundle         relative symlink  
  ✔   ContaoCalendarBundle     relative symlink  
  ✔   ContaoCommentsBundle     relative symlink  
  ✔   ContaoFaqBundle          relative symlink  
  ✔   ContaoNewsBundle         relative symlink  
  ✔   ContaoNewsletterBundle   relative symlink  
 --- ------------------------ ------------------ 

 [OK] All assets were successfully installed.                                   


 * system
 * system/config
 * templates
 * web/system
 * files
 * assets/css
 * assets/js
 * system/cache
 * system/modules
 * system/themes
 * system/tmp
 * web/share
 * assets/images

 Added/updated the system/initialize.php file.


 --- ------------------------ ---------------------------------------------------------------- 
      Symlink                  Target / Error                                                  
 --- ------------------------ ---------------------------------------------------------------- 
  ✔   system/themes/flexible   vendor/contao/core-bundle/src/Resources/contao/themes/flexible  
  ✔   web/assets               assets                                                          
  ✔   web/system/themes        system/themes                                                   
  ✔   system/logs              var/logs                                                        
 --- ------------------------ ----------------------------------------------------------------

**Comment by aschempp** [comment]
Looks like everything is ok?

**Comment by AgenceUpMotion** [comment]
No, I still have the problem

**Comment by AgenceUpMotion** [comment]
http://prod-web.fr/contao44/manager2/web/contao-manager.phar.php/#/install

ID;upmotion
Password : testcontao

Looke this ?

**Comment by aschempp** [comment]
I can't access that file. You cannot run the manager or Contao in a subfolder right now, you should create a subdomain for the installation.

**Comment by AgenceUpMotion** [comment]
Same bug with a subdomain
Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication.....Since 1h
