### ISSUE TITLE
Installation wird nicht vollständig beendet. CM bleibt im Contao-Installieren Dialog

### ISSUE THREAD

**Issue by webmurkser** [contao/contao-manager#149]
Ich versuche seit mehreren Tagen via contao-manager Beta10 die aktuelle Contao 4.4.x zu installieren. Folgendes passiert beim Aufruf von CM:
# Kurz:
-  Benutzer und Passwort setzen. Klappt
- Die automatische "suche" nach dem PHP-Binary ist soweit erfolgreich (mehr dazu später). Also auch OK
- Installation Startet und führt bis zum Dialog: "Installtool". Man könnte nun die Contao 4.4 vervollständigen. 

Leider bleibt der contao-manager dann in diesem Dialog stehen 
![grafik](https://user-images.githubusercontent.com/8065885/29377099-fddd1cbe-82ba-11e7-8dee-42d5060fb8cb.png)

hat man nun Contao 4.4.x installiert oder nicht (spielt keine Rolle) - sehe ich im Hintergrund nicht wie bei anderen Servern die Paketliste und das Suchfeld zum installieren von weiteren Erweiterungen. Ich sehe den Startdialog mit dem Benutzernamen, GitToken und PHP-Binary. Ein refresh dieser Seite quittiert der CM mit folgendem Bild:
![grafik](https://user-images.githubusercontent.com/8065885/29377071-e7217614-82ba-11e7-8a03-2e73c5f5447b.png)

# Lang:
Mein erster Webspace bei diesem Provider funktioniert problemlos. Dieser den ich für bekannte betreuen soll will einfach nicht. Der Support ist bemüht - allerdings sehen wir nichts in den Logs. Die Verzeichnisse: contao-manager/logs, var/logs sind leer. Keine Dateien vorhanden.

Wenn der CM startet - findet er folgende PHP-Binary:
![php-binary-automatisch](https://user-images.githubusercontent.com/8065885/29377618-a30d4c30-82bc-11e7-985a-d6410a2611df.jpg)

Es funktioniert nach Rücksprache mit dem Support auch folgender Pfad:
![server-php-geht](https://user-images.githubusercontent.com/8065885/29377658-bec5e7fc-82bc-11e7-8c02-e40cb166af05.jpg)

Egal welchen Pfad man wählt - Ergebnis ist immer das Bild oben - kein Zugriff nach der Installation auf den CM. Der Support würde gerne Helfen und diesen Webspace der nicht funktioniert zum laufen zu bekommen. Das Problem ist nur, dass man ohne Logs irgendwie nicht weiter kommt! Der bereits erwähnte Webspace der funktioniert, ist auf einem andern Server der wohl einen anderen PHP-Handler hat. 

Ich habe die letzten Tickets hier überflogen, und diesen _contao-manager.phar.php about_ ausgeführt. Zuerst der Server auf dem es **NICHT** geht (Ausgabe ist identisch für beide Pfade zur PHP-Binary): 
![server-funktioniert-nicht](https://user-images.githubusercontent.com/8065885/29377821-45ca441e-82bd-11e7-9272-9c1f017d520b.jpg)

und hier der Server auf dem es **FUNKTIONIERT**:
![server-funktioniert](https://user-images.githubusercontent.com/8065885/29377934-a426cda2-82bd-11e7-8bae-c3fca26ea719.jpg)

Es ist also alles gleich. Ich habe beide Webspaces identisch konfiguriert. Die Installation sowohl mit https als auch nur http durchgeführt, alle PHP-module sind auf beiden Webspaces identisch aktiviert. Die PHP.ini identisch konfiguriert. 
Vervollständige ich die Installation von Contao 4.4.x kann ich ganz normal mit contao arbeiten. Jedoch eine Modulinstallation o. Ä. scheitert dann - weil ich den CM nicht mehr aufrufen kann. 

Ich habe beide Webspaces nach dem CM Einsatz verglichen (vor Contao-Installation) bis auf den Unter-Ordner in: var/cache/prod/pools/dieserOrdner
sind alle Dateien identisch. Auf beiden Webspaces.  

Der SSH Zugang ist vorhanden - und der Support ist wie gesagt bereit weitere Details zu nennen bzw. Einstellungen zu tätigen. Gibt es einen "Debug" Modus den ich bei der Installation einschalten kann? Hier noch die Konsolenausgabe (des Servers auf dem es nicht geht) nach Abschluss des CM und vor contao-Installtool:

[konsolenausgabe.txt](https://github.com/contao/contao-manager/files/1229136/konsolenausgabe.txt)

**Comment by aschempp** [comment]
Die Meldung des *Unknown installation status* kommt, wenn der Manager die Contao-Version nicht korrekt erkennen kann. Das passiert über `pfad/zu/php vendor/bin/contao-console contao:version`. Vielleicht siehst du dort eine falsche Ausgabe?

Ein weitere guter Ansatz wäre sicherlich eine PHP-Info (`php -i`) der beiden Systeme zu vergleichen. Vermutlich ist auf einem der Hosts etwas falsch konfiguriert, beispielsweise die Default Timezone nicht gesetzt.

Falls alles nichts hilft müsste ich mir das Live ansehen, dazu benötige ich SSH Zugangsdaten zum entsprechenden Server (meine Email findest du in meinem Profil).

**Comment by mooslee** [comment]
Hallo,
ich hab das gleiche Fehlerbild, selbst mit CM Beta12.
Wenn ich _/usr/local/bin/php vendor/contao/manager-bundle/bin/contao-console contao:version_ ausführe bekomme ich die Aktuelle Contao Version(4.4.8) zurück.

habt ihr schon eine Lösung gefunden?

**Comment by aschempp** [comment]
Das gleiche Fehlerbild? Du meinst dass der Prozess nicht beendet wird?

**Comment by mooslee** [comment]
Ja, genau wie webmurkser es beschrieben hat.

Ich hab im Grundverzeichnis error_log noch etwas gefunden:
> [11-Dec-2017 19:34:08 Europe/Berlin] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/XXXX/XXXX/install-5a2ece837bb03/vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php on line 628
> [11-Dec-2017 19:34:08 Europe/Berlin] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/XXXX/XXXX/install-5a2ece837bb03/vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php on line 628

**Comment by Toflar** [comment]
Das sind Applikations-Fehler mit PHP 7.2.

**Comment by webmurkser** [comment]
Klar. Mit PHP 7.0.22

**Comment by xchs** [comment]
@Toflar bezieht sich auf die von @fhirscher  geposteten Warnungen im Log.

Hast Du den Contao Manager bereits auf die stabile Version 1.0.0 aktualisiert?

**Comment by webmurkser** [comment]
@xchs Habe das nun auch geprüft. Mit dem contao-manager 1.0.1 ist das Problem nicht mehr vorhanden.
