### ISSUE TITLE
Allow installation outside web folder

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#150]
The manager work outside the web folder like this:

 - Upload phar to document root
 - If current folder is "web", install Contao in the parent folder
 - If current folder is not "web", install Contao in the current folder and move the Contao Manager to web folder. Redirect the user and tell how to correctly setup the hosting account.

This is totally safe as Contao 4 will simply show a message about wrong document root (if not running on localhost).

**Comment by fritzmg** [comment]
Careful, someone on the forum reported that his account's document root was called `web` already.
