### ISSUE TITLE
Feature: repositories: {}

### ISSUE THREAD

**Issue by Sioweb** [contao/contao-manager#151]
Guten Morgen & danke erstmal :)

ich konnte am Wochenende eines meiner Module gut auf C4 updaten - echt Klasse mit dem Manager. Jetzt hätte ich gerne noch ein Feature dazu, wäre es möglich noch weitere Repositories + Pakete anzugeben? Es ist manchmal nötig, dass Pakete weitere Inhalte installieren müssen, die pro Installation individuell erstellt werden.

![repositories](https://user-images.githubusercontent.com/1318048/29504687-bc8c009c-8641-11e7-908f-10e81f16242e.png)

Konkret habe ich ein Modul mit lizenzierten Funktionen, welche an eine Domain und einen Zeitraum gebunden werden sollen. Dafür generiere ich eine / mehrere PHP-Klassen und lade sie in ein Repository welches dynamisch auf meinem Server erzeugt wird. Deswegen können bzw. sollen diese auch nicht auf Packagist geladen werden.

Nach der Generierung muss der Benutzer das Repository und das Paket von Hand in die composer.json schreiben um den Content zu bekommen. Nun wäre es gut wenn das auch einfach über den Manager laufen könnte.

```
{
    ...
    "require": {
        "sioweb/LIZENSE_PACKAGE": "*"
    },
    ...
    "repositories": [
        {
            "type": "git",
            "url": "DOMAIN/LIZENSE_PACKAGE.git"
        }
    ]
}
```
--- 

Mit ist natürlich klar, dass der Code danach generell auch böswillig / absichtlich geklaut und reproduziert werden kann, aber so kann ich gleichzeitig Code anbieten welcher den Kunden ggf. erinnert die Lizenz zu erweitern wenn es zeit wird, ggf. auf neue Versionen aufmerksam machen, wenn das Spamfrei möglich ist. Der Vorteil ist *etwas* Sicherheit, auch Service und ich kann Extra-Inhalte als Extra-Paket anbieten ohne die Funktion des Gerüsts anzugreifen.

**Comment by aschempp** [comment]
Was stellst du dir hinter dem Plus Symbol vor?

Generell: Aktuell ist solch eine Funktion nicht möglich, soll aber irgendwann dazukommen. Die `composer.json` lässt sich aber ganz einfach über FTP bearbeiten, und per Kommandozeile (`php web/contao-manager.phar.php composer require …`) lassen sich auch alle Pakete installieren.

**Comment by Sioweb** [comment]
ja genau über den Manager lässt sich das ganz easy aktualisieren, nachdem das per FTP angepasst wurde. Wenn auf das Plus geklickt wird, sollte ein Eingabefeld erscheinen für eine URL damit der Manager einen Typ Git mit dieser URL in die composer.json einfügt und ein Eingabefeld mit dem Paket was hinzugefügt werden soll. Dann kann der Manager das Paket aus dem neuen Repo ziehen, passiert ja alles automatisch.

Also im Grunde soll man über das Plus die composer.json erweitern und dann aktualisieren. Dann braucht man nicht die composer.json anzufassen.

Grundsätzlich nur ein Nice2Have.

**Comment by Sioweb** [comment]
![repositories](https://user-images.githubusercontent.com/1318048/29517592-200f7ed0-8676-11e7-8de2-9e2130bb14c9.png)

**Comment by dmolineus** [comment]
Wenn dann wäre es gut, dass man grundsätzlich die Repositories verwalten kann. Sprich Artefacts, ein privates Packagist usw. Warum es bei dir bei einem Package angesiedelt ist, erschließt sich mir nicht ganz.

Wenn so ein Feature kommt, wäre es super, dass die Pakete auch über die Suche auffindbar wären. Wie das technisch möglich ist, da ja Algolia zum Einsatz kommt, sei mal dahingestellt. :)

**Comment by Sioweb** [comment]
Ich hab ein Repo pro Package, da ich nicht weiß, wie ich mehrere Packages über ein Repo anbieten soll o:

Private Packages, zumindest meine, dürfen nicht suchbar sein. Das sind Domainspezifische Inhalte, aber wenn es möglich ist, könnte die Suche bestimmt durch einen Flag oder einer Sperre verhindert werden.

**Comment by aschempp** [comment]
Das hat mich eben auch verwundert, die Eingabe eines Repositories bei einem einzelnen Paket macht für mich auch keinen Sinn.

Grundsätzlich stimme ich euch zu. Allerdings gibt es zwei Dinge dazu:
 1. haben wir noch ganz andere, wichtigere Baustellen. Beispielsweise Installations-Reparatur und alles was im Install-Tool ist
 2. Soll der Manager zu einem AppStore ausgebaut werden, und in diesem Moment sollten solche Dinge wohl eher darüber laufen. Aber hierzu besteht noch kein konkretes Konzept.

**Comment by amenk** [comment]
Gibt es zum Thema AppStore weitere Überlegungen / Links? Ich weiß nicht, wie groß das Paid-Contao-Content Ecosystem eigentlich ist. Ich denke z.B. mit packagist.com for vendors könnte man hier recht unkompliziert was auf die Beine Stellen, wenn man möchte :-)
Ich habe das hier mit Tim von Premium-Contao-Themes mal andiskutiert: https://forum.premium-contao-themes.com/forum/feature-request/15389-installation-via-composer?_=1559326693796

**Comment by aschempp** [comment]
Ja es gibt Überlegungen dazu, einige wurden auch am [Contao Camp in München](https://contao.camp) diskutiert. Aktuell ist es bereits möglich, [kommerzielle Pakete in der Manager-Suche anzeigen zu lassen](https://github.com/contao/package-metadata/blob/master/docs/de/README.md#öffentliche-vs-privateproprietäre-pakete), in der nächsten Version wird auch eine unkomplizierte Installation möglich sein.

Ob man Private Packagist verwendet oder eine andere Lösung, ist dem Manager grundsätzlich egal. Es muss einfach via Composer funktionieren. Private Packagist hat leider relativ hohe Kosten, welche (aus meiner persönlichen Sicht) nur mit einem Lizenz-Abo für eine Erweiterung tragbar wären.

**Comment by Sioweb** [comment]
Ho!

ich nehme an, es gibt noch keine digitale Kopie zu den Store-Ideen?

In Leipzig haben ja auch schon einige gemeint, sie nutzen [Satis](https://github.com/composer/satis). Ggf. würde es ja schon reichen dem "App-Store" einen Link zur package.json von Satis zu hinterlegen.

Meine Pakete werden alle mit htaccess geschützt und müssten lokal

**Comment by Sioweb** [comment]
Ho!

ich nehme an, es gibt noch keine digitale Kopie zu den Store-Ideen?

In Leipzig haben ja auch schon einige gemeint, sie nutzen Satis. Ggf. würde es ja schon reichen dem "App-Store" einen Link zur package.json von Satis zu hinterlegen. Nur kann es hier sein, dass viele Repos zu enorm mehr Last führen können, evt. wäre es zusätzlich noch sinnvoll, dem Benutzer vor der "private search" alle App-Store-User/Vendors anzugeben, die bei der Suche berücksichtigt werden sollen.

Meine Pakete werden alle mit htaccess geschützt, daher wäre es grundsätzlich egal ob die gefunden werden. Die Installation ist nur per auth.json möglich.

Meine eigenen Satis Repositories (Accounting etc.) pflege ich in Contao - ein Modul legt mir dann pro User / Lizenzkäufer ein Ordner in Satis + Pakete an die er nutzen darf. Einzig dumme ist nur, dass der Benutzer sein Repo in die composer.json eintragen muss :)

Evt. kann ich mit dem Ansatz - oder irgendwie so - weiterhelfen?

**Comment by aschempp** [comment]
Contao Manager 1.2 unterstützt nun private Pakete. Infos unter https://docs.contao.org/dev/guides/publishing-bundles/#private-and-commercial-packages
