### ISSUE TITLE
call date_default_timezone_set(), if no default timezone is set

### ISSUE THREAD

**Issue by saibotd** [contao/contao-manager#152]
Some webhosters define no timezone in their php.ini. In this case Contao Manager may stop working unexpectedly. To work around this, I'd suggest adding 

`if(!date_default_timezone_get()) date_default_timezone_set('Europe/Berlin');`

somewhere in the code base.

**Comment by Toflar** [comment]
This is already the case: https://github.com/contao/contao-manager/blob/develop/build/stub.php#L46
So if none was set, `UTC` will be used. But anyway, a php setup with no timezone set is a dangerous setup. Tell your hoster to fix that problem :)

**Comment by saibotd** [comment]
I've replicated the error and you are right, the error occurs in one of the packages:

> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /var/www/vhosts/sttgs.de/dev/tobitest/install-59ad6d82e165f/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php:50
Stack trace:
#0 /var/www/vhosts/sttgs.de/dev/tobitest/install-59ad6d82e165f/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(50): DateTime->__construct('tomorrow')
#1 /var/www/vhosts/sttgs.de/dev/tobitest/install-59ad6d82e165f/var/cache/prod/appProdProjectContainer.php(1747): Monolog\Handler\RotatingFileHandler->__construct('/var/www/vhosts...', 10, 200, true, NULL)
#2 /var/www/vhosts/sttgs.de/dev/tobitest/install-59ad6 in /var/www/vhosts/sttgs.de/dev/tobitest/install-59ad6d82e165f/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php on line 50
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception

Is it possible to fix this from Contao Managers side?

> But anyway, a php setup with no timezone set is a dangerous setup. Tell your hoster to fix that problem :)

Yes, I can change this on the server, but this seemed like an easy fix for a problem that may occur for many end-users.

**Comment by Toflar** [comment]
> Is it possible to fix this from Contao Managers side?

No, one of the big advantages of having the manager is that it is completely independent from the application which - in comparison to Contao 3.5 - ensures that if you configure/install something that doesn't work, you can still access the manager even if the application is broken.
So no, the Manager cannot fix this because it does not influence how the application works itself.

The Managed Edition would need to do the very same as the Manager but to be honest, I'd vote against it. A php setup without a timezone is a broken setup. An application should not try to fix that in my opinion.

**Comment by saibotd** [comment]
> A php setup without a timezone is a broken setup. An application should not try to fix that in my opinion.

I agree, just thought it may help adoption (on crappy hosts ;)

**Comment by Toflar** [comment]
Sure, ideas are always welcome 😄
