### ISSUE TITLE
Add an XCache check to the Phar stub

### ISSUE THREAD

**Issue by leofeyer** [contao/contao-manager#153]
It seems that XCache does not handle .phar files, either.

https://stackoverflow.com/questions/33897200/php-fatal-error-uncaught-exception-pharexception-with-message-halt-compile

I have had several complaints regarding the Live Update Phar, so I guess we should add a check in the `stub.php` file (and also in the Contao Check - see https://github.com/contao/check/issues/133).

**Comment by aschempp** [comment]
Is this still relevant? I never got any complaints about this …

**Comment by leofeyer** [comment]
¯\\_(ツ)_/¯

We are checking it in the Contao check (see https://github.com/contao/check/pull/138/files) and in the Live Update, because people had issues with it. No idea if they still have or if XCache can handle .phar files meanwhile.

**Comment by Toflar** [comment]
XCache is dead. No release for 4 years and not compatible with PHP 7 so... :)
