### ISSUE TITLE
CM 1.0.0-beta10 - Internetwerk - Installation / Update bricht ab

### ISSUE THREAD

**Issue by Pantos** [contao/contao-manager#155]
Die Installation/Updates von Contao mit dem Contao-Manager (1.0.0-beta10) brechen bei dem Webhoster Internetwerk mit folgender Fehlermeldung ab:

Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 2 updates, 0 removals
  - Updating doctrine/inflector (v1.1.0 => v1.2.0): Downloading (100%)
  - Updating terminal42/header-replay-bundle (1.2.1 => 1.3.0): Downloading (100%)
Writing lock file
Generating optimized autoload files
Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

Exception occured: The php executable could not be found.
0 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
1 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
2 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/web/...')
3 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/web/...')
4 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
5 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
6 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
7 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
8 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
9 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
10 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
11 /var/www/web/htdocs/contao/web/contao-manager.phar.php(55): require('phar:///var/www...')
12 {main}
Chained exception: The php executable could not be found.
0 /var/www/web/htdocs/contao/vendor/contao/manager-bundle/src/Composer/ScriptHandler.php(72): Contao\ManagerBundle\Composer\ScriptHandler::executeCommand('contao:install-...', Object(Composer\Script\Event))
1 /var/www/web/htdocs/contao/vendor/contao/manager-bundle/src/Composer/ScriptHandler.php(35): Contao\ManagerBundle\Composer\ScriptHandler::addWebEntryPoints(Object(Composer\Script\Event))
2 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication(Object(Composer\Script\Event))
3 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(205): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Contao\\ManagerB...', 'initializeAppli...', Object(Composer\Script\Event))
4 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
5 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(307): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', false)
6 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Command/UpdateCommand.php(158): Composer\Installer->run()
7 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
8 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(147): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
9 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
10 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
11 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/web/...')
12 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/web/...')
13 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
14 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
15 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
16 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
17 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
18 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
19 phar:///var/www/web/htdocs/contao/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
20 /var/www/web/htdocs/contao/web/contao-manager.phar.php(55): require('phar:///var/www...')
21 {main}

Process terminated with exit code 1
Reason: General error

Werde aktuell nicht ganz schlau aus der Fehlermeldung. PHP wurde aus meiner Sicht korrekt erkannt...

**Comment by fritzmg** [comment]
Die Fehlermeldung lautet
```
Exception occured: The php executable could not be found.
```
Hast du den Pfad zur PHP Executable manuell eingetragen?

Komisch ist jedoch, dass das _nach_ dem erfolgreichem Update der Packages passiert. Das bedeutet ja, dass eine gültige PHP Executable bereits verfügbar war.

**Comment by Pantos** [comment]
With Contao Manager 1.0.0-beta19 it works perfect!
