### ISSUE TITLE
After update to Contao 4.4.6: Chrome doesn't show the configurations wheels properly

### ISSUE THREAD

**Issue by jscholtysik** [contao/contao-manager#156]
After the update to Contao 4.4.6 the Chrome Version 61.0.3163.100 sometimes does not show the configuration wheels right of the orange version field in a proper way as the screenshot shows:

![bildschirmfoto 2017-09-28 um 10 29 59](https://user-images.githubusercontent.com/1425566/30956779-9d0ab2ee-a438-11e7-8fcb-7148cc06c2f9.png)

When I refresh Chrome, other configuration wheels are cutted, every refresh some others or none of them.

![bildschirmfoto 2017-09-28 um 10 41 51](https://user-images.githubusercontent.com/1425566/30957155-b3509bda-a439-11e7-9893-26d219e4aaab.png)

![bildschirmfoto 2017-09-28 um 10 42 52](https://user-images.githubusercontent.com/1425566/30957182-d4d2e1b4-a439-11e7-8c9b-2a2e0302dedb.png)

Firefox 55.0.3 and Safari 11.0 on macOS 10.13 are fine.

The Contao Manager is Beta 10.

Contao 4.4.5 did not have this problem.

This issue concerns to all of my Contao 4.4.6 installations.

**Comment by aschempp** [comment]
The Contao Manager has no relation to the Contao version at all, so the update cannot be the reason for this... does the issue change/disappear if you resize the window?

**Comment by jscholtysik** [comment]
No, same issue at resize:

![bildschirmfoto 2017-09-29 um 06 53 54](https://user-images.githubusercontent.com/1425566/31001305-13eb7632-a4e3-11e7-9f5d-a6a8de0fb7ce.png)

**Comment by jscholtysik** [comment]
Also on Windows 10 and all browsers there are no problems, so it seems to be a problem with macOS and Google Chrome...

**Comment by jscholtysik** [comment]
Seems to be the same problem like here with the new .blink class in Contao for Google Chrome:

https://github.com/contao/core/issues/8801

**Comment by Aybee** [comment]
I can not confirm this
- Windows 10
- Chrome Version 61.0.3163.100 (Offizieller Build) (32-Bit)
- Contao Manager 1.0.0-beta10

I see no relation with 8801 as there are no generated classes in BODY like with Contao.

**Comment by jscholtysik** [comment]
@Aybee: See my note above:

> Also on Windows 10 and all browsers there are no problems, so it seems to be a problem with macOS and Google Chrome...

macOS 10.13 High Sierra, Google Chrome Versions 61.0.3163.100 and also in the newest one, 62.0.3202.62:

![bildschirmfoto 2017-10-18 um 15 26 27](https://user-images.githubusercontent.com/1425566/31721104-be9fa618-b418-11e7-8888-2a42093cfffd.png)

**Comment by Aybee** [comment]
Ak, ok, sorry. I overlooked this.
