### ISSUE TITLE
Frage Zugang CM über SSH

### ISSUE THREAD

**Issue by swinde** [contao/contao-manager#158]
Wäre es möglich den CM einen SSH Zugriff zu ermöglichen? 
http://php.net/manual/en/function.ssh2-connect.php

Das die würde die Speicherprobleme verringern wenn nicht sogar beseitigen.

**Comment by aschempp** [comment]
Das habe ich mir auch schon überlegt, halte ich aber für viel zu kompliziert. Die Speicherprobleme sollten sich dadurch eben gar nicht ändern, denn der Manager führt bereits alles auf Kommandozeile aus (und nicht im Webprozess!)

**Comment by swinde** [comment]
Bei DF gibt es da schon Unterschiede, der CM bricht ab wegen zu wenig Speicher, per Konsole mit SSH Zugriff funktioniert es. 

Hilfetext bei DF
Nutzungshinweise für SSH-Accounts:
> SSH Zugänge unterliegen anderen Limits als ein Zugriff über den Webserver, diese sind um den Faktor 3 höher, abgesehen von der Anzahl der gleichzeitigen Prozesse, diese sind auf 12 für alle Logins zusammen limitiert. Die Priorität aller Aufrufe ist niedriger, um auch mit länger andauernden Skripten keine Präsenzen zu beeinträchtigen. Die maximale Laufzeit von Skripten und Programmen ist nicht mehr auf 90s limitiert, sondern nur noch durch CPU Sekunden.

**Comment by fritzmg** [comment]
@aschempp der Contao Manager spawned ja auch nur einen separaten Prozess via PHP. Je nach Hosting Umgebung gelten da dann immer noch Limits (im Gegensatz zu der direkten Ausführung über SSH). Das Problem gibt es ja auch mit dem detached mode des composer-client in Contao 3. Bekannt ist das bei den Hostern 1&1, Alfahosting und DomainFactory.

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
