### ISSUE TITLE
The Contao Manager failed to start a console task

### ISSUE THREAD

**Issue by robvis** [contao/contao-manager#160]
I'm already trying to get the contao-manager working for days and tried almost everything, but no success.
Every time CM is complaining about the console task like "The background task was cancelled or stopped unexpectedly. Please check the console protocol"
**Please can anyone help me out.**
Try to load the Rocksolid extentions.
My system is CentoS 6.7 with PHP5.6.13 in an OpenVZ container.
Contao 4.4.6
I extended the memory_limit to 3G (in php.ini)

Addtional info:
<details>
Just tried to install Rocksolid_slider and got below console output with an error at the end.
<pre>
Using version ^2.0 for madeyourday/contao-rocksolid-slider
/var/www/clients/client2/web28/web/slagerij/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 1 install, 0 updates, 0 removals
  - Installing madeyourday/contao-rocksolid-slider (v2.0.1): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
22:57:26 ERROR     [console] Error thrown while running command "contao:install-web-dir --env=prod". Message: "The directory "/tmp/e2bacbbe1b1502f00a2382607967b200" is not writable." ["error" => Symfony\Component\Filesystem\Exception\IOException { …},"command" => "contao:install-web-dir --env=prod","message" => "The directory "/tmp/e2bacbbe1b1502f00a2382607967b200" is not writable."] []

                                                                          
  [Symfony\Component\Filesystem\Exception\IOException]                    
  The directory "/tmp/e2bacbbe1b1502f00a2382607967b200" is not writable.  
                                                                          

contao:install-web-dir [--no-dev] [-u|--user USER] [-p|--password [PASSWORD]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<path>]

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

Installation failed, reverting /var/www/clients/client2/web28/web/slagerij/composer.json to its original content.
--------------------------------------------------------
Exception occured: An error occurred while executing the "contao:install-web-dir" command: 22:57:26 ERROR     [console] Error thrown while running command "contao:install-web-dir --env=prod". Message: "The directory "/tmp/e2bacbbe1b1502f00a2382607967b200" is not writable." ["error" => Symfony\Component\Filesystem\Exception\IOException { …},"command" => "contao:install-web-dir --env=prod","message" => "The directory "/tmp/e2bacbbe1b1502f00a2382607967b200" is not writable."] []

                                                                          
  [Symfony\Component\Filesystem\Exception\IOException]                    
  The directory "/tmp/e2bacbbe1b1502f00a2382607967b200" is not writable.  
                                                                          

contao:install-web-dir [--no-dev] [-u|--user USER] [-p|--password [PASSWORD]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<path>]

#0 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/client...')
#3 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(83): Tenside\Core\Task\Runner->run('/var/www/client...')
#4 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php(55): require('phar:///var/www...')
#12 {main}
Chained exception: An error occurred while executing the "contao:install-web-dir" command: 22:57:26 ERROR     [console] Error thrown while running command "contao:install-web-dir --env=prod". Message: "The directory "/tmp/e2bacbbe1b1502f00a2382607967b200" is not writable." ["error" => Symfony\Component\Filesystem\Exception\IOException { …},"command" => "contao:install-web-dir --env=prod","message" => "The directory "/tmp/e2bacbbe1b1502f00a2382607967b200" is not writable."] []

                                                                          
  [Symfony\Component\Filesystem\Exception\IOException]                    
  The directory "/tmp/e2bacbbe1b1502f00a2382607967b200" is not writable.  
                                                                          

contao:install-web-dir [--no-dev] [-u|--user USER] [-p|--password [PASSWORD]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<path>]

#0 /var/www/clients/client2/web28/web/slagerij/vendor/contao/manager-bundle/src/Composer/ScriptHandler.php(72): Contao\ManagerBundle\Composer\ScriptHandler::executeCommand('contao:install-...', Object(Composer\Script\Event))
#1 /var/www/clients/client2/web28/web/slagerij/vendor/contao/manager-bundle/src/Composer/ScriptHandler.php(35): Contao\ManagerBundle\Composer\ScriptHandler::addWebEntryPoints(Object(Composer\Script\Event))
#2 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication(Object(Composer\Script\Event))
#3 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(205): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Contao\\ManagerB...', 'initializeAppli...', Object(Composer\Script\Event))
#4 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#5 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(307): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', false)
#6 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Command/RequireCommand.php(180): Composer\Installer->run()
#7 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Composer\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#8 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(147): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#9 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#10 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#11 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/client...')
#12 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(83): Tenside\Core\Task\Runner->run('/var/www/client...')
#13 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/clients/client2/web28/web/slagerij/web/contao-manager.phar.php(55): require('phar:///var/www...')
#21 {main}
--------------------------------------------------------

Process terminated with exit code 1
Reason: General error
</pre>
</details>

**Comment by aschempp** [comment]
This is actually an issue in Contao core but should be fixed in the latest version?

/cc @contao/developers

**Comment by Toflar** [comment]
No. I guess you refer to https://github.com/contao/core-bundle/issues/1107 but that's unrelated. We still write to `sys_get_tmp_dir()` and many applications do. I think this is simply a wrong php configuration. The php temporary directory is set to `/tmp` where the user has no access to. So either the user must have access to it or the php settings have to be adjusted correctly.

**Comment by leofeyer** [comment]
I had this issue in the develop branch with the new Symfony lock service. The old lock handler did create the directory if it did not exist, but the new lock service does not, so this is how I fixed it:

https://github.com/contao/core-bundle/blob/d9bd533f968c4b3db5f3cf1517542250998b482c/src/Command/AbstractLockedCommand.php#L70

**Comment by robvis** [comment]
Thanks for the quick response.
I replaced the AbstractLockedCommand.php.
Still same issue. Now additional below error 500

ERROR 500 Unknown installation status
Some files were found on your server but no known Contao version could be detected.
You must either manually repair your application or remove the following files and folders to install Contao:

- .gitignore
- README.md
- app
- assets
- composer.json
- composer.lock
- files
- system
- templates
- var
- vendor

**Comment by robvis** [comment]
Solved.
The /tmp/e2bacbbe1b1502f00a2382607967b200 folder was created with root.
thanks a lot for your help.
