### ISSUE TITLE
Der Contao Manager konnte einen Konsolentask nicht starten!

### ISSUE THREAD

**Issue by robvis** [contao/contao-manager#161]
Ich habe verschiedene Extentions from Rock-Solid aufgeladen mit guten Erfolg.
Aber dann hat der Konsolentask Problem wieder angefangen.
Bitte haben Sie eine Vorschlag zum loeschen dieser Problem?
Danke.

**Comment by robvis** [comment]
Any help on this issue?

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
