### ISSUE TITLE
Don't copy and overwrite app_dev.php 

### ISSUE THREAD

**Issue by matmah** [contao/contao-manager#162]
Overwriting app_dev.php when running cache:warmup makes it hard to use this entry point for development.

To develop, someone has to add ip's to access this file and every cache:warmup command will overwrite app_dev.php and make every changes in this file invalid.

**Comment by Toflar** [comment]
That's the desired behavior, otherwise we cannot make sure a valid `app_dev.php` is provided.
Just copy it, name it `app_foobar.php` and use this entry point instead.

**Comment by leofeyer** [comment]
> Overwriting app_dev.php when running cache:warmup

Do you really mean `cache:warmup`? The file should not be overwritten during cache warmup.

**Comment by matmah** [comment]
@leofeyer No, you're right. I mean the composer script Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication

@Toflar Of cource it's desired by contao, but it's not a desired behavior of symfony applications. Dev Entry Point is for development and has to be modified for development reasons. It will be added to VCS and should be deleted in deployment stage for security reasons. And why should I create a new file which does exactly the same except another ip permissions? It's just a duplicate of code and more overhead to create and maintanance new files for each project.

Is there a possibility to don't copy app_dev.php to production when tunning composer update/install? Argument --no-dev do also copy this file to web directory.

**Comment by Toflar** [comment]
Our `app_dev.php` is intended to be deployed. It is protected and cannot be accessed from the outside. It is important for regular users to be able to "enable the debug mode".

The `install-web-dir` command does provide a `--no-dev` option (https://github.com/contao/manager-bundle/blob/master/src/Command/InstallWebDirCommand.php#L74), I'm not sure if you can pass arguments to scripts from the composer.json though.

@leofeyer please move the issue to the manager-bundle. It is not related to the manager.

**Comment by matmah** [comment]
OK, then please rename contao dev entry point to another one than symfony dev entry point.

**Comment by Toflar** [comment]
👎  on this.

**Comment by aschempp** [comment]
Contao *Managed Edition* has it's own behavior, it's not a regular Symfony application in certain aspects. There are multiple simple solutions to your problem:
 1. Rename the entry point
 2. Use a password instead of adding custom IPs
 3. Disable the default Composer script and initialize the application on your own.

All of them solve your edge-case, I don't think it's reasonable to me.
