### ISSUE TITLE
Strato Webhosting

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao-manager#163]
Bei Strato Webhosting fehlt für den Contao Manager und Contao 4.4.x die PHP Erweiterung "PHP intl" laut Beiträgen im Contao Forum.
Kann Contao 4.4 auf Strato Webhosting irgendwie installiert werden?
Bei Contao 3.5.x funktioniert der Composer nicht bei Strato Webhosting.

**Comment by do-while** [comment]
Bisher ist es keinem gelungen, die intl ist für Contao 4 notwendig!

https://github.com/contao/contao-manager/wiki

**Comment by Toflar** [comment]
Übrigens: `intl` ist für jede PHP-Applikation die Internationalisierung anbieten will Pflichtprogramm und wird seit PHP 5.3 mit PHP mitgeliefert (muss aktiviert werden, was bei Strato wohl nicht der Fall ist). Contao stellt da keine aussergewöhnlichen Anforderungen :)

**Comment by sdahlmann** [comment]
Ich würde gerne wissen, ob für Contao 4.4.7 selbst oder nur für den Contao Manager die PHP intl Erweiterung erforderlich ist?
Ich hatte es vorhin überraschenderweise geschafft, auf einem Strato Webhosting ein Contao 4.4.7 ohne Fehler zu installieren. Contao 4.4.7 habe ich dazu auf den Strato Server per FTP hochgeladen.
Aufruf von Backend und Frontend hat sauber geklappt.
Nur der Contao Manager bzw. der Composer mittels SSH-Konsole hat nicht funktioniert  um Erweiterungen zu installieren. Unter Contao 3.5.x funktioniert übrigens der Composer auch nicht sauber.
Kann mann eventl. ähnlich wie bei (https://www.strato.de/faq/article/2051/Wie-kann-ich-in-meinem-Webhosting-Paket-IonCube-installieren.html) beschrieben mit der PHP Erweiterung/Anwendung IonCube, die PHP intl Erweiterung nachträglich bei Strato installieren bei einem Strato Hosting?
Ich mache hier das Thema nochmals auf, da ich als Webdesigner mehrere Kunden habe mit Contao 3.5.x und Strato Hosting, welches die Kunden schon vorher hatten und ich es vorhin überraschend geschafft hatte Contao 4.4.7 auf Strato zu installieren (Mann muss auch sehen, dass Strato nicht gerade ein kleiner Webhoster ist, der mittlerweile zu United Internet gehört).
Gerne stelle ich den Contao Programmierern einen Strato Hosting Zugang inkl. SSH Zugang mit einer Contao 4.4.7 Installation zur verfügung.
Ich hatte bei Strato wegen PHP intl nochmals nachgefragt und die Antwort ist, dass es bedauerlicherweise nicht verfügbar ist bei shared-hosting.
