### ISSUE TITLE
Provide more logging or feedback

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-manager#164]
I tried the Contao Manager on [easyname ](https://github.com/contao/contao-manager/wiki/easyname). However as I have mentioned in the Wiki, the Contao Manager is unable to identify a valid PHP binary, even though the path `/usr/bin/php7` should be valid:
```
~$ /usr/bin/php7 -v
PHP 7.0.8 (cli) (built: Jun 24 2016 12:15:19) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.8, Copyright (c) 2002-2016, by ionCube Ltd.
```
As far as I can see the reason for why the Contao Manager is not able to identify the provided PHP binary path as valid is swallowed [here](https://github.com/contao/contao-manager/blob/1.0.0-beta10/api/Process/PhpExecutableFinder.php#L84-L90):
```php
try {
    $process = (new Process($commandline))->mustRun(null, array_map(function () { return false; }, $_ENV));

    return json_decode(trim($process->getOutput()), true);
} catch (RuntimeException $e) {
    return null;
}
```
The exception is not logged anywhere, nor is it returned to the front end. Thus it is difficult to figure out what the actual problem is.

**Comment by aschempp** [comment]
These issues mostly happen if the webserver is running in a chroot environment that is different from the shell access. Can you maybe ask the server administrator if that is the case?

**Comment by fritzmg** [comment]
Hm, well the shared hosting environment of easyname is set up more restrictive than most other shared hosting environments (that I encountered at least). So I think there is not much point in investigating this any further. I'll close the issue. (Though I still think that more feedback/logging would be helpful.)
