### ISSUE TITLE
Connection refused after installation with contao manager

### ISSUE THREAD

**Issue by JLBA** [contao/contao-manager#166]
Hi everyone,

Trying to install Contao 4.4 mithw Manager 1.0.0 beta10 in MAMP Pro 4.2.1. The installation starts well. I create my id and pswd. Then, I'm asked to login but my id and pswd are refused. I suppressed users.json 3times but still the same pb.
What to do ? Thanks.

**Comment by aschempp** [comment]
Please check the XHR requests in your browser console if you can see any errors in the request/response data.
