### ISSUE TITLE
Strato Webhosting

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao-manager#168]
**Ich würde gerne wissen, ob für Contao 4.4.7 / Symphony selbst oder nur für den Contao Manager die "PHP intl" Erweiterung erforderlich ist?**

**Ich hatte es vorhin überraschenderweise geschafft, auf einem Strato Webhosting Paket "PowerWeb S" ein Contao CMS 4.4.7 ohne Fehler zu installieren. Contao 4.4.7 habe ich dazu auf den Strato Server per FTP hochgeladen.
Aufruf von Backend und Frontend hat sauber geklappt.**

Nur der Contao Manager bzw. der Composer mittels SSH-Konsole hat nicht funktioniert  um Erweiterungen zu installieren. Unter Contao 3.5.x funktioniert übrigens der Composer auch nicht sauber.

Kann mann eventl. ähnlich wie bei (https://www.strato.de/faq/article/2051/Wie-kann-ich-in-meinem-Webhosting-Paket-IonCube-installieren.html) beschrieben mit der PHP Erweiterung/Anwendung IonCube (ioncube_loader_sun_5.3.so), die PHP intl (intl.so) Erweiterung nachträglich bei Strato installieren bei einem Strato Hosting.

Ich mache hier das Thema nochmals auf, da ich als Webdesigner mehrere Kunden habe mit Contao 3.5.x und Strato Hosting, welches die Kunden schon vorher hatten und ich es vorhin überraschend geschafft hatte Contao 4.4.7 auf Strato zu installieren (Mann muss auch sehen, dass Strato nicht gerade ein kleiner Webhoster ist, der mittlerweile zu United Internet gehört).
Gerne stelle ich den Contao Programmierern ein Strato Hosting Zugang inkl. SSH Zugang mit einer Contao 4.4.7 Installation zur verfügung.
Ich hatte bei Strato wegen PHP intl nochmals nachgefragt und die Antwort ist, dass es bedauerlicherweise nicht verfügbar ist bei shared-hosting.

**Comment by Toflar** [comment]
Für Contao selbst. Die PHP Extension `intl` ist das PHP-Gateway für die [ICU Bibliothek](https://de.wikipedia.org/wiki/International_Components_for_Unicode), der offiziellen Unicode Bibliothek für alles was mit Internationalisierung zu tun hat (Datumsformate, Transliteration z.B. für unsere Seitenaliase, Zeitzonen, Zahlen- und Währungsformatierungen, etc. pp.). Sie ist somit Pflichtprogramm für **jede** multilinguale PHP-Applikation.

**Comment by sdahlmann** [comment]
Update bezüglich Strato Webhosting: Ich gerade mit einem Mitarbeiter vom

**Comment by sdahlmann** [comment]
Update bezüglich Strato: Laut dem Strato Support soll Strato shared Webhosting die PHP Extension intl unterstützen. Mir wurde dieses explizit auf Nachfrage so gesagt. Ich hatte diesbezüglich gestern (16.11.2017) mit dem Support nochmals telefoniert.
Des Weiteren habe ich raus gefunden, dass das PHP Memory Limit bei Strato 256 MB aktuell beträgt und PHP 7.x unterstützt wird.
Vielleicht können die Strato Problem doch irgendwie bezüglich dem Contao Manager noch gelöst werden. Ich stelle dafür gerne ein Strato Webhosting mit Zugangsdaten und SSH-Zugang den Contao Programmierern zu Verfügung.

**Comment by aschempp** [comment]
`Intl` wird im Hintergrund von Abhängigkeiten benötigt. Beispielsweise um internationale URL-Aliase automatisch zu generieren. Bei einer manuellen Installation kann es vorkommen dass du nie in ein Problem läufst, aber irgendwann knallt's halt weil die Abhängigkeit fehlt. Deshalb prüft der Manager diese Anforderung im Voraus.
