### ISSUE TITLE
Add read-more link

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#17]
Read-More link should point to packagist if the package is on there

**Comment by Toflar** [comment]
@discordier can you provide this information in tenside?

**Comment by aschempp** [comment]
*bump*

**Comment by discordier** [comment]
I can hardcode for packagist but there is no generic way to generate a link from repository.
Maybe we want to use the support/manual link also.

**Comment by aschempp** [comment]
Implemented based on Packagist search results.
