### ISSUE TITLE
Error 400 - XSRF token does not match

### ISSUE THREAD

**Issue by Anke** [contao/contao-manager#170]
Hallo,

mein allererster Versuch, Contao 4.4.x latest mit dem Contao-Manager zu installieren.

Der Check hat grünes Licht gegeben (df.eu Managed Hosting, PHP 7.7.1), die Installation des CM hat geklappt.

Beim anschließenden Versuch, Contao zu installieren, erhalte ich die Fehlermeldung "Error 400 - XSRF tolen does not match". 

Da ich über einen solchen Fehler nirgendwo was Geschriebenes finden kann, mache ich vielleicht etwas falsch, aber was?

Gruß,
Anke

**Comment by xchs** [comment]
Hast Du Dir die Infos zu DF im [Contao Manager Wiki](https://github.com/contao/contao-manager/wiki/Domainfactory) bereits angesehen? Du könntest versuchen, den Contao Manager (respektive Composer) via SSH auf der Konsole aufzurufen.

**Comment by Anke** [comment]
Danke für das schnelle Feedback! Das hat sich gerade erledigt, nachdem ich was über die Tokenübergabe gefunden habe. Ich hatte die Installation im Firefox 57++ versucht, in FF 56 hat es jetzt funktioniert - nach Deaktivieren einiger Sicherheitsaddons (was ich in Quantum allerdings auch getan hatte).
