### ISSUE TITLE
Problem bei 1&1 SSD Hosting

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao-manager#173]
Wenn ich auf einem aktuellen 1&1 SSD Kundenhosting (1&1 Unlimited Plus) Contao Erweiterungen über den Contao Manager installieren möchte bekomme ich folgende Fehlermeldung:

Using version ^2.2 for terminal42/contao-easy_themes /homepages/9/d710082824/htdocs/contao/composer.json has been updated Loading composer repositories with package information Updating dependencies Error: "Out of memory (allocated 484450304) (tried to allocate 8192 bytes)" in phar:///homepages/9/d710082824/htdocs/contao/web/contao- manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/G enericRule.php on 36 mmap() failed: [12] Cannot allocate memory mmap() failed: [12] Cannot allocate memory [Symfony\Component\Debug\Exception\OutOfMemoryException] Error: Out of memory (allocated 484450304) (tried to allocate 8192 bytes) Exception trace: () at phar:///homepages/9/d710082824/htdocs/contao/web/contao- manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/G enericRule.php:36 tenside:runtask [-h|--help] [-q|--quiet] [-v|vv|vvv|-- verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-- disable-events] [--] <command> <taskId> Process terminated with exit code 255 Reason: Unknown error

Ich habe vom 1&1 Support folgende Antwort bezüglich der Speicherfehlermeldung bekommen:

Sehr geehrter Herr Dahlmann,
vielen Dank für Ihre Anfrage.
Ihrem Benutzer stehen auf der Shell maximal 768MB zu Verfügung. Die Zuteilung von mehr Speicher würde die Stabilität des Servers gefährden.
Im Shared Webhosting kann ich Ihnen daher leider keine Lösung anbieten.
Freundliche Grüße
1&1 Kundenservice

Diese Antwort von 1&1 macht mich bezüglich dem Contao Manager und dem Composer doch sehr Nachdenklich. Ich kann 1&1 verstehen, dass diese bei einem shared-hosting nicht mehrere GB RAM zur Verfügung stellen können / wollen.
Ich hatte 1&1 die Fehlermeldung und weitere Dinge wie auch die Zugangspasswörter zu der Contao installation 1&1 zukommen lassen, damit 1&1 sich im Detail ein Bild von dem Problem machen kann. Dieses hatte ich telefonisch mit einem 1&1 Supportmitarbeiter so vereinbart.
Sind für den Contao Manager und Composer um Erweiterungen zu installieren mehrere GB RAM auf der shell des Hostingsservers erforderlich?
Ich wollte lediglich 3 kleine Erweiterungen installieren und schon bei der ersten kam der Speichererror.
Mich würde es sehr freuen, wenn mich jemand von den Contao Programmierern da im Detail aufklären könnte, was für Hostinganforderungen an Speicher der Contao Manager und der Composer hat. Wieviel Speicher von welchen wird mindestens durchschnittlich gebraucht, was natürlich davon Abhängt, wieviele und welche Erweiterungen man installiert hat bzw. installieren möchte.
Hilft bei diesem Problem eventl. der angedachte Contao Cloud Server für die Installation von Contao Erweiterungen. Gerne beteilige ich mich diesbezüglich bei einem Spendenaufruf regelmäßig mit einem kleinen Betrag.
Gerne kann ich den Contao Programmierern einen Zugang zu dem 1&1 Hosting bereit stellen inkl. SSH-Zugang für die genauere Analyse des Problems.

Ergänzung noch: Wenn ich Contao 3.5.31 LTS installiere auf 1&1 funktioniert die Installation von Erweiterungen mit dem Composer auch nicht.
Wenn ich die Erweiterungen Manuell ins Module Verzeichnis bei Contao 3.5.31 LTS schiebe kann ich die Datenbank sauber updaten und die Erweiterungen nutzen.
Bei Contao 4.4.8 geht es Prinzip auch nur teilweise werden neue Datenbankeinträge angezeigt aber das Updaten geht nicht sauber der Datenbank.

Insgesamt kann ich leider im Moment nur vom 1&1 Shared-Hosting abraten oder man sollte darauf kein Contao CMS Verwenden, am besten sorgar kein CMS welches den Composer verwendet.

**Comment by aschempp** [comment]
Duplicate of #90
