### ISSUE TITLE
Disable IP check 

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao-manager#175]
In Contao 3 konnte man den IP Check im Backend abschalten. In Contao 4 geht das  über app/config/config.yml

```
contao:
  security:
    disable_ip_check: true
```
Wäre es möglich bzw. sinnvoll diese Einstellungen künftig im Manager mit zu ermöglichen?

**Comment by aschempp** [comment]
Diese Einstellung ist in Contao 4.5 nicht mehr vorhanden. Ich denke nicht dass eine entsprechende Option lediglich für die 4.4 Sinn macht, da man die Einstellung doch eher selten braucht.

**Comment by mlwebworker** [comment]
Danke für die Info. Da hast Du völlig recht.
