### ISSUE TITLE
Contao-Manager 1.0.0-beta11: Installation fehlgeschlagen

### ISSUE THREAD

**Issue by thomrit** [contao/contao-manager#177]
Ich wollte mit dem Contao-Manager 1.0.0-beta11 Contao installieren, ist leider fehlgeschlagen.

Kurz nach beginn der Installation kommt die Meldung: «Konsolentask beendet!
Der Hintergrundprozess wurde abgebrochen oder unerwartet beendet. Bitte prüfen Sie das Konsolenprotokoll.»
Im Konsolenprotokoll steht nichts, eine lehre schwarze Fläche!

Gehe ich zur ServerLog-Datei habe ich folgende Meldung:

`[Fri Dec 01 13:00:53.701852 2017] [-:error] [pid 49872:tid 34712176640] [client 31.165.105.180:51348] FastCGI: server "/var/run/hcgi/63359" stderr: [2017-12-01 13:00:53] app.ERROR: Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: "No active task" at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/api/Controller/TaskController.php line 136 {"exception":"[object] (Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\NotFoundHttpException(code: 0): No active task at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/api/Controller/TaskController.php:136)"} [], referer [url]http://c-manager.webdesign-contao-basel.ch/contao-manager.phar.php/[/url]`

Im Verzeichniss /contao-manager befinden sich folgende Dateien:
contao-manager
-contao-manager/background-process.err.log
-background-process.get.json
-background-process.set.json
-contao-manager/config.json
-manager.json
-tenside-tasks.json
-users.json

In der Datei: -contao-manager/background-process.err.log

Steht folgendes:
`[2017-12-01 13:00:55] app.WARNING: Forking disabled by configuration, execution will block until the command has finished. [] []
[2017-12-01 13:00:55] console.ERROR: Error thrown while running command "tenside:runtask background-process -v --no-interaction". Message: "Task not found: background-process" {"error":"[object] (InvalidArgumentException(code: 0): Task not found: background-process at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php:76)","command":"tenside:runtask background-process -v --no-interaction","message":"Task not found: background-process"} []
[2017-12-01 13:00:55] console.DEBUG: Command "tenside:runtask background-process -v --no-interaction" exited with code "1" {"command":"tenside:runtask background-process -v --no-interaction","code":1} []

                                      
  [InvalidArgumentException]          
  Task not found: background-process  
                                      

Exception trace:
 () at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php:76
 Tenside\CoreBundle\Command\RunTaskCommand->execute() at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php:240
 Symfony\Component\Console\Command\Command->run() at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php:61
 Tenside\CoreBundle\Command\RunTaskCommand->run() at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/vendor/symfony/console/Application.php:876
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/vendor/symfony/console/Application.php:216
 Symfony\Component\Console\Application->doRun() at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/api/ApiApplication.php:71
 Contao\ManagerApi\ApiApplication->doRun() at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at phar:///home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php/api/console:83
 require() at /home/ritzhae/www/c-manager.webdesign-contao-basel.ch/web/contao-manager.phar.php:55

tenside:runtask [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--disable-events] [--] <command> <taskId>`

**Comment by aschempp** [comment]
This should be fixed in Beta12, please update to the latest version.

**Comment by arboc** [comment]
Seit der Beta 15 tritt dieser oder ein ähnlicher Fehler bei uns auf:
```
[06-Mar-2018 13:39:51 Europe/Berlin] [2018-03-06 13:39:51] app.WARNING: Forking disabled by configuration, execution will block until the command has finished. [] []
[06-Mar-2018 13:39:51 Europe/Berlin] [2018-03-06 13:39:51] app.ERROR: Attempted to run task background-process twice. [] []
[06-Mar-2018 13:39:51 Europe/Berlin] [2018-03-06 13:39:51] app.ERROR:  [] []
[06-Mar-2018 13:39:51 Europe/Berlin] [2018-03-06 13:39:51] console.DEBUG: Command "tenside:runtask background-process -v --no-interaction" exited with code "1" {"command":"tenside:runtask background-process -v --no-interaction","code":1} []
```

**Comment by mimamuxx** [comment]
Habe die Beta18 und habe in drei Installationen jetzt das Problem!
Hoster All-Inkl. Contao einmal mit 4.4.14. und zweimal mit 4.4.16
-> No active task at phar:///www/htdocs/.../web/contao-manager.phar.php/api/Controller/TaskController.php:172

Habe gerade eine schlechte Internetverbindung (hohe Delay). Kann das etwas damit zu tun haben?
