### ISSUE TITLE
Unterstützte Hoster: hostfactory

### ISSUE THREAD

**Issue by christian-schattat** [contao/contao-manager#179]
Der Hoster hostfactory bzw. OptimaNet Schweiz AG (https://www.hostfactory.ch) könnte auch mit in das Dropdown der unterstützten Hoster aufgenommen werden. Der Contao-Manager läuft dort seit Anfang an problemlos.

<img width="957" alt="manager server konfiguration" src="https://user-images.githubusercontent.com/10039087/33524386-b7a5d0f8-d81c-11e7-854e-2485f8d50b67.png">

Und ein Detail: Das Label vor dem Dropdown 'Configuration' ist noch nicht übersetzt. ;-)

**Comment by aschempp** [comment]
Wenn du das entsprechend im Wiki dokumentierst ist das machbar ;-)

**Comment by christian-schattat** [comment]
Wieder etwas gelernt :-) Ich habe die Seite für Hostfactory im Wiki ergänzt.
