### ISSUE TITLE
Production build issues react warning

### ISSUE THREAD

**Issue by discordier** [contao/contao-manager#18]
When building via `gulp --production` the following is logged in the console, we should fix this before final release.

> bundle.js:20 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

**Comment by Toflar** [comment]
Fixed in 5d653451c4f0a5b655a3aa3e5528052d7c8ec9c3. Yet another 70kb gone :)

**Comment by discordier** [comment]
:dancers:
