### ISSUE TITLE
PHP executable cmd-line arguments

### ISSUE THREAD

**Issue by spotbot2k** [contao/contao-manager#181]
I had a few unpleasent hours trying to get 4.4 and manager to run on a cPanel managed server and while it is not directly an cPanel or Manager issue, it would be nice to be able to add some command line arguments to the php executable directly in the GUI. For example

`/bin/php -d allow_url_fopen=1`

By now it is not posible to add it eather in GUI, nor in manager.json - manager will mark the php configuration as invalid. As a temprary solution I use bash wrapper script, but it is not realy comfy.

**Comment by aschempp** [comment]
This was initially possible, but I have removed this option for security reasons. It would not be possible to correctly escape the arguments. However, it is possible to register your provider and provide the respective options, feel free to provide a PR for https://github.com/contao/contao-manager/blob/develop/api/Resources/config/servers.yml

**Comment by SchwalenbergJe** [comment]
I am having a similiar issue.
The Contao Manager is not useable for me anymore.
The first setup fails with the error: "The PHP setting "allow_url_fopen" is not enabled on the server."

allow_url_fopen is allowed on my hosted Server (which I have also confired with a phpinfo).
I was able to add a ""php_cli": "/usr/bin/php7.0 -d allow_url_fopen=1" command to the manager.json in previous versions.

My hoster is Host Europe, which is also available in the servers.yml, which you have linked.
But this configuration is not enough, obivously.

Any ideas on how to fix this?

**Comment by spotbot2k** [comment]
> feel free to provide a PR
It is a custom server, so adding it to a common config won't be that helpful as the software/hardware configuration can varray - the PHP path is mostly the same, but the list of arguments is sever speciffic. Anyway - thanks for the answer and a great job.

> Any ideas on how to fix this?
I haven't had anything to do with hosteurope for years, but if you have enough rights for it you can try the wrapper solution as well. Create a text file with .sh extention and following content:

`#!/bin/bash
OUTPUT="$(/usr/bin/php7.0 -d allow_url_fopen=1 $@)"
echo "${OUTPUT}"`

Make it executable by typing chmod +x %FILENAME%.sh in terminal/SSH. Use this file as PHP-executable in manager.

**Comment by SchwalenbergJe** [comment]
Unfortunately it is just a hosted Server without SSH access.
I think we definitely need something to add custom configurations.

**Comment by Toflar** [comment]
As @aschempp already pointed out, we cannot offer custom configuration for security reasons. I don't understand why this is discussed then.

However, I think that we might want to pass on a set of php directives by default. Like these:

```ini
allow_url_fopen = 1
memory_limit = -1
max_execution_time = -1
```

Imho, when changing these values is not allowed, the parameters are just ignored. If the `php.ini` settings already match these settings it doesn't harm either. So it would just be a default list of directives that are always passed on and would help on some systems and just be ignored otherwise.

**Comment by SchwalenbergJe** [comment]
This would be a nice solution.
Can you estimate if and when this is going to be added?

Because at the moment the manager is not usable for me and I would really like to continue working with it.

**Comment by aschempp** [comment]
As I said, we can easily add that to a hosting configuration. Some already have that (https://github.com/contao/contao-manager/blob/develop/api/Resources/config/servers.yml#L105). So if you can provide the information we need to add your server, we could fix that in the next version.

**Comment by SchwalenbergJe** [comment]
For me, it is just the "allow_url_fopen = 1" option which is missing for the hosteurope server.

Would be great if you can add this for the next version, thank you!
Hope there is one coming soon.

**Comment by SchwalenbergJe** [comment]
I also remember having problems with te sys_temp_dir variable. 
I need to set that manually on my hoster. 

Of course this can‘t be set in the predefined configuration but do you think this option can, somehow, be added to the manager?

**Comment by aschempp** [comment]
Added in a05081485d2a38ad857ae3b125124363dd87e8c2

Regarding the sys_temp_dir, I don't think we can add a fix or configuration option for every possible hosting misconfiguration…
