### ISSUE TITLE
Ignore insecure HTTP for 127.0.0.1

### ISSUE THREAD

**Issue by Loilo** [contao/contao-manager#185]
It's not too uncommon practice among developers to set up custom TLDs for local development (e.g. I've got `*.contao` for my Contao 4 projects).

The manager warns about not having HTTPS in this environment, and since you can't hide the warning, it can get seriously annoying.

However, when accessing those local domains, the `$_SERVER['REMOTE_ADDR']` is still `127.0.0.1`, so maybe we can add this case as an exception for the warning?

**Comment by aschempp** [comment]
This message is shown using javascript, so the only think I know is the current domain. There is no `$_SERVER` variable. Except if you can come up with a javascript solution to detect localhost?

**Comment by Loilo** [comment]
Not entirely sure, but I don't think it's possible.
I hadn't looked on the source code but I seeing all the things the manager does with PHP, I thought it had a way to communicate with it.

**Comment by aschempp** [comment]
Yeah, the Manager has an API written in PHP (https://docs.contao.org/books/manager/api/). However, that API does not really care about the encryption of the connection. Maybe we could also solve this by just confirming the HTTPS error and close it in the browser…

**Comment by Loilo** [comment]
Would certainly be a possibility.

**Comment by aschempp** [comment]
Closing this as not feasible.
