### ISSUE TITLE
Fehlinstallation mit Contao-Manager (beta12)

### ISSUE THREAD

**Issue by thomrit** [contao/contao-manager#186]
Hallo

Ich habe Contao 4.4.8 schon drei mal mit dem Contao-Manager (betta12) Installiert. 

In der Analyse des Problems habe ich gesehen, dass die Installation irgendwie nicht richtig abgeschlossen wird.

Effekt:
Nach der Installation mit dem neuen Contao-Manager (Beta12) 
habe ich festgestellt dass unter Layout > Eingebundene Module die Icons «Das Modul aktiviere/deaktivieren» fehlen.

Nach der Installation bleibt der Ordner «install-5a24f80a378c5» zurück.

In diesem Ordner befinden sich eben diese Dateien die Contao vermisst: z.B. wrench.svg
vendor/icons/images
var

Fehler in Logdatei
`[2017-12-03 14:27:58] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: http://pmworks.webdesign-contao-basel.ch/system/themes/flexible/icons/wrench.svg" at /home/ritzhae/www/pmworks.webdesign-contao-basel.ch/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: http://pmworks.webdesign-contao-basel.ch/system/themes/flexible/icons/wrench.svg at /home/ritzhae/www/pmworks.webdesign-contao-basel.ch/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: http://pmworks.webdesign-contao-basel.ch/system/themes/flexible/icons/wrench.svg at /home/ritzhae/www/pmworks.webdesign-contao-basel.ch/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:66)"} []
`

**Comment by Toflar** [comment]
Da fehlt wohl der Symlink. Kannst du uns etwas über dein System verraten? Windows?

**Comment by thomrit** [comment]
Hallo Yanick

Die Installationen habe ich auf einem Hostpoint-Server gemacht.
Ich selbst arbeite mit OSX Browser Google-Chrome

Gruss Thomas

**Comment by thomrit** [comment]
Hallo Janick
Die Installation mit Contao-Manager funktioniert immer noch nicht bei Hostpoint.
Es bleibt immer noch der Install-Ordner mit Dateien zurück.
Habe von Hostpoint folgende Error-Logs bei der Installation mit Contao-Manager erhalten:

`[[Fri Jan 19 10:31:56.283924 2018] [-:error] [pid 65591:tid 34695391232] [client MYIP] FastCGI: server "/var/run/hcgi/93484" stderr: [2018-01-19 10:31:56] request.INFO: Matched route "task_status". {"route":"task_status","route_parameters":{"_controller":"contao_manager.controller.tasks:putTaskStatus","_route":"task_status"},"request_uri":"http://DOMAIN.CH/contao-manager.phar.php/api/task/status?_locale=de","method":"PUT"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 10:31:56.283954 2018] [-:error] [pid 65591:tid 34695391232] [client MYIP] FastCGI: server "/var/run/hcgi/93484" stderr: [2018-01-19 10:31:56] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 10:31:56.283964 2018] [-:error] [pid 65591:tid 34695391232] [client MYIP] FastCGI: server "/var/run/hcgi/93484" stderr: [2018-01-19 10:31:56] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 10:31:56.283973 2018] [-:error] [pid 65591:tid 34695391232] [client MYIP] FastCGI: server "/var/run/hcgi/93484" stderr: [2018-01-19 10:31:56] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 10:31:56.283982 2018] [-:error] [pid 65591:tid 34695391232] [client MYIP] FastCGI: server "/var/run/hcgi/93484" stderr: [2018-01-19 10:31:56] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\\\Component\\\\Security\\\\Guard\\\\Token\\\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\\"rh\\", authenticated=true, roles=\\"\\"))","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 10:31:56.283991 2018] [-:error] [pid 65591:tid 34695391232] [client MYIP] FastCGI: server "/var/run/hcgi/93484" stderr: [2018-01-19 10:31:56] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 10:31:56.283999 2018] [-:error] [pid 65591:tid 34695391232] [client MYIP] FastCGI: server "/var/run/hcgi/93484" stderr: [2018-01-19 10:31:56] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 10:31:56.284009 2018] [-:error] [pid 65591:tid 34695391232] [client MYIP] FastCGI: server "/var/run/hcgi/93484" stderr: [2018-01-19 10:31:56] app.ERROR: Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: "No active task" at phar:///home/USER/www/hochuliarch.ch/web/contao-manager.phar.php/api/Controller/TaskController.php line 136 {"exception":"[object] (Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\NotFoundHttpException(code: 0): No active task at phar:///home/USER/www/hochuliarch.ch/web/contao-manager.phar.php/api/Controller/TaskController.php:136)"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:07:54.278537 2018] [core:error] [pid 53481:tid 34695384064] [client MYIP] AH00037: Symbolic link not allowed or link target not accessible: /home/USER/www/hochuliarch.ch/web/assets, referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:07:54.278550 2018] [core:error] [pid 53482:tid 34695409664] [client MYIP:51144] AH00037: Symbolic link not allowed or link target not accessible: /home/USER/www/hochuliarch.ch/web/assets, referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:07:54.278554 2018] [core:error] [pid 53486:tid 34695394304] [client MYIP:51145] AH00037: Symbolic link not allowed or link target not accessible: /home/USER/www/hochuliarch.ch/web/assets, referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:07:54.428106 2018] [core:error] [pid 53486:tid 34695394304] [client MYIP:51145] AH00037: Symbolic link not allowed or link target not accessible: /home/USER/www/hochuliarch.ch/web/assets, referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:08:53.011963 2018] [-:error] [pid 53484:tid 34695379968] [client MYIP:51153] FastCGI: server "/var/run/hcgi/93485" stderr: [2018-01-19 12:08:52] request.INFO: Matched route "task_status". {"route":"task_status","route_parameters":{"_controller":"contao_manager.controller.tasks:putTaskStatus","_route":"task_status"},"request_uri":"http://DOMAIN.CH/contao-manager.phar.php/api/task/status?_locale=de","method":"PUT"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:08:53.011996 2018] [-:error] [pid 53484:tid 34695379968] [client MYIP:51153] FastCGI: server "/var/run/hcgi/93485" stderr: [2018-01-19 12:08:52] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:08:53.012005 2018] [-:error] [pid 53484:tid 34695379968] [client MYIP:51153] FastCGI: server "/var/run/hcgi/93485" stderr: [2018-01-19 12:08:52] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:08:53.012013 2018] [-:error] [pid 53484:tid 34695379968] [client MYIP:51153] FastCGI: server "/var/run/hcgi/93485" stderr: [2018-01-19 12:08:52] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:08:53.012023 2018] [-:error] [pid 53484:tid 34695379968] [client MYIP:51153] FastCGI: server "/var/run/hcgi/93485" stderr: [2018-01-19 12:08:52] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\\\Component\\\\Security\\\\Guard\\\\Token\\\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\\"rh\\", authenticated=true, roles=\\"\\"))","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:08:53.012032 2018] [-:error] [pid 53484:tid 34695379968] [client MYIP:51153] FastCGI: server "/var/run/hcgi/93485" stderr: [2018-01-19 12:08:52] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:08:53.012040 2018] [-:error] [pid 53484:tid 34695379968] [client MYIP:51153] FastCGI: server "/var/run/hcgi/93485" stderr: [2018-01-19 12:08:52] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer http://DOMAIN.CH/contao-manager.phar.php/
[Fri Jan 19 12:08:53.012050 2018] [-:error] [pid 53484:tid 34695379968] [client MYIP:51153] FastCGI: server "/var/run/hcgi/93485" stderr: [2018-01-19 12:08:52] app.ERROR: Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: "No active task" at phar:///home/USER/www/hochuliarch.ch/web/contao-manager.phar.php/api/Controller/TaskController.php line 136 {"exception":"[object] (Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\NotFoundHttpException(code: 0): No active task at phar:///home/USER/www/hochuliarch.ch/web/contao-manager.phar.php/api/Controller/TaskController.php:136)"} [], referer http://DOMAIN.CH/contao-manager.phar.php/

`

**Comment by kikmedia** [comment]
Was ich gemacht habe:

- Subdomain unter -> Domains angelegt
- Webseite -> Webseite angelegt, Docroot nach ~/www/c4test.hochuli1.myhostpoint.ch/web
- mit dem Dateiexplorer nach Explorer ~/www/c4test.hochuli1.myhostpoint.ch/ gewechselt
- dort Einstellungen getroffen: [PHP]
```
allow_url_fopen = On
memory_limit = 2G
max_execution_time = 900
``` 
- sowie PHP 7.1 eingestellt
- ins Verzeichnis /web gewechselt, dort 'Einstellungen übernehmen' ausgewählt
- den Manager aufgerufen, der sofort eine user.ini bemängelt 
- den Inhalt der user.ini gesichert und dann die user.ini entfernt
- erneut den Manager aufgerufen
- auf 'Contao installieren' geklickt, nachdem ich die user.ini wieder angelegt habe
- gewartet - bei mir hat das rund 15 Minuten gedauert

Als Rest verbleibt ein Ordner mit Installationsdateien oberhalb des /web-Verzeichnisses. Den kann man einfach löschen.

Was weiterhin ein Problem ist: Die user.ini, an der sich der Manager bei der initialen Prüfung stört. Wegmachen und schnell wieder anlegen kann ja nicht die dauerhafte Lösung sein, oder?

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
