### ISSUE TITLE
Systemprüfung nach Update meldet Installationsprobleme für Contao

### ISSUE THREAD

**Issue by pandroid** [contao/contao-manager#187]
Nach dem automatischen Update führt der CTOM eine Systemprüfung durch. Diese meldet, dass für die Contao-Installation "Installationsprobleme erkannt" wurden. Diese müssen behoben werden, bevor der CTOM verwendet werden kann.

Leider wird nicht angezeigt, welche Probleme das sind. Wie kann ich den CTOM wieder zum Arbeiten bringen?

Der Server (MAMP Pro auf Mac OS X) und alle anderen Komponenten laufen laut Prüfung korrekt. Screenshot anbei.
![bildschirmfoto 2017-12-06 um 09 27 58](https://user-images.githubusercontent.com/1230552/33652170-aa66b81e-da68-11e7-837a-42646239303a.png)

**Comment by MaCo7** [comment]
Bei mir hat das problemlos geklappt mit MampPro. IN der alten Manager.json konnte man einen ähnlichen Fehler durch unterschiedliche PHP Versionen in Mamp provozieren und hier ggf. anpassen. In der neueren manager.json gibt es keinen Eintrag mehr zur PHP Version. Vielleicht an anderer Stelle? Durch anpassen des Versionseintrages konnte man den Fehler abstellen. Hoffe mien Beitrag war hilfreich. VG

**Comment by pandroid** [comment]
MAMP läuft mit mehreren Hosts auf unterschiedlichen PHP-Versionen. Das hat bislang auch keine Probleme bereitet und ist projektbedingt ja auch notwendig. 

Ich habe jetzt mal die manager.json verglichen

CTOM beta10
`"secret": "XYZ",
"last_update": "2017-11-30T10:49:03+01:00",
    "php_cli": "\/Applications\/MAMP\/bin\/php\/php7.1.8\/bin\/php",
    "php_can_fork": false,
    "php_force_background": false`

CTOM beta12
`"last_update": "2017-12-06T12:25:30+01:00",
    "php_can_fork": false,
    "php_force_background": false,
    "server": "mamp_mac",
    "latest_version": "1.0.0-beta12"`

Auch wenn ich den php_cli Eintrag in die neue beta12 Version kopiere, bleibt es bei den o.a. Problemen. Hier mal das Log.

[api-2017-12-06.log](https://github.com/contao/contao-manager/files/1535002/api-2017-12-06.log)

@MaCo7 Hast Du auch unterschiedliche PHP-Versionen auf deinem MAMP laufen?

**Comment by aschempp** [comment]
Die `php_cli` ist nicht nötig (und wird nicht gelesen) wenn der Server nicht `custom` ist.
Kannst du bitte in der Browser-Konsole nachsehen was du einen Fehler siehst und was du im Netzwerk-Tab beim Request nach `api/server/contao` als Antwort bekommst?

**Comment by pandroid** [comment]
Vor der Prüfung meldet die Konsole:
`Failed to load resource: the server responded with a status of 401 (Unauthorized) für http://dhl-adressen-4:8888/contao-manager.phar.php/api/session?_locale=de`

Nach Abschluss der Systemprüfung meldet die Konsole zusätzlich `GET http://dhl-adressen-4:8888/contao-manager.phar.php/api/server/contao?_locale=de 500 (Internal Server Error)` für vendor.937a1aa5e204e223c949.js:16

Bis zum Request api/system/contao komme ich scheinbar gar nicht.
![bildschirmfoto 2017-12-07 um 10 53 13](https://user-images.githubusercontent.com/1230552/33709190-e08323b8-db3c-11e7-8d10-df1593d7caeb.png)

**Comment by aschempp** [comment]
Der 401 ist korrekt, du musst dich ja einloggen. Schau mal bitte nach was du für Response-Daten beim 500er bekommst. Sorry, ich meinte natürlich `api/server/contao` ^^

**Comment by pandroid** [comment]
Ich hoffe, da habe ich jetzt das richtige für Dich rausgesucht!? ;-)

![bildschirmfoto 2017-12-07 um 11 30 11](https://user-images.githubusercontent.com/1230552/33710838-1bdd21e8-db42-11e7-97a6-c5c06683c974.png)
![bildschirmfoto 2017-12-07 um 11 30 21](https://user-images.githubusercontent.com/1230552/33710842-1fff7e2e-db42-11e7-819e-02e1c5b4e23a.png)

**Comment by aschempp** [comment]
Hmm. Das HTML was ausgeliefert wird stammt nicht vom Contao Manager, sondern von Apache. Kann es sein dass dein Server die Meldung vom Manager abfängt und seine eigene Fehlerseite ausliefert? Ich kann mich wage erinnern dass sich dies konfigurieren lässt, kann dir aber leider auch nicht auswendig sagen wo. Vielleicht kannst du dazu deinen Hoster kontaktieren?

**Comment by pandroid** [comment]
Der Hoster bin ich. Das ist ein lokaler MAMP Pro auf Mac OS X. ;-)

**Comment by pandroid** [comment]
Keine Ahnung, ob es weiterhilft. Das hier gibt die apache_error.log aus:
`[Thu Dec 07 12:48:49 2017] [error] [client ::1] FastCGI: comm with server "/Applications/MAMP/fcgi-bin/php7.1.8.fcgi" aborted: idle timeout (30 sec), referer: http://dhl-adressen-4:8888/contao-manager.phar.php/
[Thu Dec 07 12:48:49 2017] [error] [client ::1] FastCGI: incomplete headers (0 bytes) received from server "/Applications/MAMP/fcgi-bin/php7.1.8.fcgi", referer: http://dhl-adressen-4:8888/contao-manager.phar.php/`

**Comment by pandroid** [comment]
Ich bin hier leider immer noch nicht weiter. Könnt Ihr vielleicht doch noch etwas mit dem o.a. error.log des apache anfangen?

**Comment by aschempp** [comment]
ich kann daran leider nichts machen, es scheint ein Problem deines Servers und nicht des Contao Managers zu sein.
