### ISSUE TITLE
Contao Manager BETA 12 seems to be not working on HOST EUROPE

### ISSUE THREAD

**Issue by niccaballero** [contao/contao-manager#188]
After an update from Contao-Manager BETA 10 to BETA 12 the system check on HOST EUROPE brings the following message in german: 
"Serverkonfiguration – Es wurde kein valides PHP Programm auf dem Server gefunden."

**Comment by niccaballero** [comment]
<img width="962" alt="bildschirmfoto 2017-12-06 um 18 04 10" src="https://user-images.githubusercontent.com/3225092/33685308-efc45d0c-daaf-11e7-8c06-a3384a399a4c.png">

**Comment by xchs** [comment]
According to the information in the [Contao Manager Wiki](https://github.com/contao/contao-manager/wiki/HostEurope), the Contao Manager will not work correctly for "Webhostings" plans. What's you hosting plan?

**Comment by aschempp** [comment]
Please try a custom configuration and manually enter your binary path. Let me know which binary works, I might need to add it to the configuration.

**Comment by aschempp** [comment]
@niccaballero did you find the correct path for your PHP binary?

**Comment by niccaballero** [comment]
Hi Andreas, thank you for your message and the answer is "no", in the PLESK Configuration Panel I set the PHP-Version 7.1.9 for Contao 4.4. There is a phpinfo() page about our website => http://www.bannerfarm-ae.com/phpinfo.php

HOST EUROPE has a page about the PHP Versions and the correct path for PHP 7.0 is:
 /usr/bin/php7.0 
but PHP 7.1.9 is not listened there:
https://www.hosteurope.de/faq/webhosting/skripte/skript-pfadangaben/

**Comment by niccaballero** [comment]
![php-host-europe](https://user-images.githubusercontent.com/3225092/34412432-f08d65d6-ebbb-11e7-8e84-5cd5cc29bd9e.png)

**Comment by niccaballero** [comment]
I tried: 
**/opt/plesk/php/7.1/**
but the Contao-Manager told me that there is no PHP binary found

**Comment by ausi** [comment]
@niccaballero `/opt/plesk/php/7.1/` is the path to a directory, not to the PHP binary. You could try if `/opt/plesk/php/7.1/bin/php` or `/opt/plesk/php/7.1/php` works.

**Comment by niccaballero** [comment]
Thank you sooooo much, it works!!  ;-)
**/opt/plesk/php/7.1/bin/php**
