### ISSUE TITLE
Contao Manager 1.0.0-beta12 : Netcup Webhosting 8000

### ISSUE THREAD

**Issue by osae83** [contao/contao-manager#189]
Hallo zusammen.

leider klappt die Serverkonfiguration nicht.
-----
Serverkonfiguration
Es wurde kein valides PHP Programm auf dem Server gefunden.
-----

**Comment by aschempp** [comment]
Please try a custom configuration and let us know about the PHP binary path. Apparently the wiki documentation is incorrect: https://github.com/contao/contao-manager/wiki/netcup

**Comment by osae83** [comment]
For example, I call PHP scripts via this path:
/usr/local/php71/bin/php

But unfortunately contao-manager doesn't recognize it

**Comment by osae83** [comment]
Jetzt geht alles, proc_open war noch deaktiviert :/ hatte ich gestern total übersehen

**Comment by aschempp** [comment]
hmm, und der Manager hat dir nicht gesagt dass proc_open fehlt?

**Comment by osae83** [comment]
ne, das hatte er nicht angezeigt auf der CM-Webseite. Sonst hätte ich ja etwas genauer nachgeguckt aber so dachte ich halt es wäre ein Bug.

**Comment by xchs** [comment]
Wenn ich mich nicht täusche, dann kam in der Beta10 noch eine entsprechende Meldung.
