### ISSUE TITLE
Feature: Add settings for language shortcuts in the URLs

### ISSUE THREAD

**Issue by jankout** [contao/contao-manager#192]
It would be great to have the possibility to set the language shortcuts for the URLs directly in the Contao Manager. Thank you.

**Comment by aschempp** [comment]
You mean whether to use language prefixes? prependLanguage ?

**Comment by jankout** [comment]
yes.

**Comment by aschempp** [comment]
Duplicate of https://github.com/contao/contao-manager/issues/116
