### ISSUE TITLE
Fehler: kein valides PHP Programm auf dem Server gefunden.

### ISSUE THREAD

**Issue by Sascha07** [contao/contao-manager#193]
Habe Contao 4.4.8 mal testweise am Sonntag beim Hoster Netcup installiert.

Hat auch alles funktioniert. Wenn ich jetzt allerdings den Contao-Manager aufrufe und mich einlogge muss ich erneut "netcup" auswählen. Danach wird erneut die Serverkonfiguration überprüft und ich erhalte folgende Fehlermeldung. 

"Serverkonfiguration
Es wurde kein valides PHP Programm auf dem Server gefunden" (siehe auch Screenshot)

Hoster weiß anscheinend auch nicht weiter und sagt: "Bitte kontaktieren Sie einmal den Contao-Support, ob hier etwas geändert wurde."

PS: Website + Contao-Backend funktioniert weiterhin einwandfrei

![screen01](https://user-images.githubusercontent.com/1426080/33886767-eb05c796-df47-11e7-9472-5d1c0b7a1507.jpg)

**Comment by xchs** [comment]
Siehe https://github.com/contao/contao-manager/issues/189

**Comment by Sascha07** [comment]
Soll ich weitere Kommentare hier schreiben oder unter https://github.com/contao/contao-manager/issues/189?
