### ISSUE TITLE
Hostinganbieter Netzone fehlt

### ISSUE THREAD

**Issue by claudiabarfuss** [contao/contao-manager#197]
Der Hoster Netzone aus der Schweiz: https://www.netzone.ch/ fehlt noch in der Liste. Vielen Dank fürs Einfügen.

**Comment by aschempp** [comment]
Wenn du alle benötigten Daten im Wiki ergänzt füge ich das gerne in der nächsten Version hinzu.

**Comment by claudiabarfuss** [comment]
Sorry, aber welche Daten brauchst du genau? URL und PHP-Pfad?

**Comment by xchs** [comment]
> URL und PHP-Pfad?

Ja und ggf. noch die unterstützten Pakete.

**Comment by claudiabarfuss** [comment]
Diese Angaben habe ich von Netzone bekommen: 

/usr/bin/php7.2
/usr/bin/php7.1
/usr/bin/php7.0
/usr/bin/php5.6

https://www.netzone.ch/

**Comment by xchs** [comment]
Bist Du Kunde dort? Kannst Du den Contao Manager z. B. mit `/usr/bin/php7.1` installieren?

**Comment by claudiabarfuss** [comment]
Ja, das ging problemlos. Wenn es Probleme geben sollte stehen sie zur Verfügung um Anpassungen vorzunehmen. Auch mit günstigstem Hostingpaket.

**Comment by xchs** [comment]
Ich habe die Informationen ins Wiki übertragen: https://github.com/contao/contao-manager/wiki/NetZone

**Comment by claudiabarfuss** [comment]
Super, vielen Dank.

**Comment by aschempp** [comment]
Wird in der nächsten Version ausgeliefert (siehe https://github.com/contao/contao-manager/commit/4c473fa85d9fd686bc2a6daaf08dd59fd9fc2432)
