### ISSUE TITLE
Show badge für abandoned packages

### ISSUE THREAD

**Issue by dmolineus** [contao/contao-manager#198]
Composer provides information about abandoned packages. It would be useful to see a abandoned badge when searching for packages in the same manner as the not compatible badge is shown.

**Comment by aschempp** [comment]
That badge should already be available, but abandoned packages are sorted last so you might not see them… Did you search for a specific abandoned package (that is supported, because the not-supported badge overrides abandoned)?

**Comment by dmolineus** [comment]
Okay, i noticed it for a package which is also unsupported and didn't know that only one badge is shown. I guess everything is working so I close this issue.
