### ISSUE TITLE
Feature Request: update --dry-run Option im Contao-Manager

### ISSUE THREAD

**Issue by Nepomuk1** [contao/contao-manager#199]
Die "--dry-run" Option geht auf der Console via Composer.

Diese Option auch im Contao-Manager wäre echt nicht schlecht, denn nicht jeder hat einen Consolen-Zugang. So kann vorher noch eine Überprüfung erfolgen.

**Comment by xchs** [comment]
@Nepomuk1 Habe gesehen, dass es diesbezüglich bereits einen Feature Request gibt: https://github.com/contao/contao-manager/issues/174

Du könntest also das Ticket hier schließen.

**Comment by aschempp** [comment]
Duplicate of #174
