### ISSUE TITLE
Standardvorgaben für Version verlässt den LTS Zweig

### ISSUE THREAD

**Issue by Nepomuk1** [contao/contao-manager#200]
beta13
Contao Open Source CMS steht auf 4.4.*
alle restlichen bundles stehen auf ^4.4

Beim 'Pakate aktualisieren' bleibt Contao im 4.4-LTS Zweig, die Bundles wechseln aber auf 4.5.
Stand heute sind das: 
Contao = 4.4.11
comments, listing und newsletter = 4.5.0
Hab hier https://getcomposer.org/doc/articles/versions.md#caret-version-range- nachgeschaut und
die bundles auf 4.4.* eingestellt, jetzt bleiben auch Diese im LTS-Zweig.

Bug oder Gedankenfehler von mir?

**Comment by AgentCT** [comment]
Bei mir ist es gerade auch zum unfreiwilligen Wechsel einiger Pakete auf Contao 4.5 gekommen.

**Comment by aschempp** [comment]
Das ist ein Fehler in den Abhängigkeiten von Contao, welche in der nächsten Version behoben werden. Der Manager kann daran nichts ändern. Eine temporäre Lösung ist in deinem Manager die Version aller Pakete auf `4.4.*` zu setzen.
