### ISSUE TITLE
creation of .env file

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-manager#202]
I think it would make sense if the Contao Manager offered the functionality to create a username and password for the `app_dev.php` (i.e. the creation of the `.env` file), so that inexperienced users can more easily create this file themselves.

**Comment by aschempp** [comment]
Absolutely. The necessary foundation has been added in Contao 4.5 (see `vendor/bin/contao-api`).

**Comment by aschempp** [comment]
Implemented in 3eda509590a408df94a9d41215cf9959cdbe3f90
