### ISSUE TITLE
Update: php Pfade 1blu Hostinganbieter (War: Zugangsdaten für 1blu Hostinganbieter nicht gelistet)

### ISSUE THREAD

**Issue by cjlisten** [contao/contao-manager#203]

**Comment by xchs** [comment]
Welche Pakete werden denn unterstützt und wie lautet der PHP-Pfad?

**Comment by cjlisten** [comment]
PHP 7.1, PHP 5.6, ich nutze aktuell PHP 5.6 mit Contao 4.4.8. Den Pfad weiß ich leider nicht, sonst könnte ich ihn im Contao Manager selbst eingeben. 1blu bietet auch an, Contao 4.4.7 über sog. easyapps zu installieren. Das probiere ich jetzt mal, vielleicht finde ich dann den Pfad heraus.

Danke für die rasche Reaktion
Claus

**Comment by xchs** [comment]
Du könntest ggf. auch direkt beim Support nachfragen, wie denn die PHP-CLI Pfade lauten.

**Comment by cjlisten** [comment]
Danke für den Tipp, war aber nicht nötig. Ich habe einfach die vorgeschlagene Angabe übernommen: /opt/php5361/bin/php. Damit geht's.

**Comment by cjlisten** [comment]
Ich glaube, ich habe die Pfade in showphp gefunden:

Configuration File (php.ini) Path | /opt/php5.6.31/etc
Loaded Configuration File | /opt/php5.6.31/etc/php.ini

**Comment by xchs** [comment]
> Ich habe einfach die vorgeschlagene Angabe übernommen: /opt/php5361/bin/php

Wahrscheinlich müsste das `/opt/php5631/bin/php` lauten und nicht `/opt/php5361/bin/php`, denn gemeint ist sicherlich PHP 5.6. Trotzdem würde ich sicherheitshalber auch noch beim Hoster nachfragen und eine Bestätigung einholen. Vielleicht gibt es ja auch noch andere Binarys bzw. PHP-Pfade, wo z. B. nur die Major- und Minor-Version angegeben werden muss.

**Comment by cjlisten** [comment]
Update: Wie vorgeschlagen, habe ich beim Support die Pfade erfragt:

> Bitte verwenden Sie folgende Pfade, je nach Version:
> 
> /usr/bin/php56/php5
> /opt/php7/bin/php
> 

Wäre toll, wenn 1blu mit dieser Info jetzt auch im Contao Manager vorkonfiguriert würde.

**Comment by xchs** [comment]
> Wäre toll, wenn 1blu mit dieser Info jetzt auch im Contao Manager vorkonfiguriert würde.

Ich füge das gerne im Wiki hinzu, wenn Du mir noch sagst, mit welchem Paket von 1blu Du den Contao Manager getestet hast.

**Comment by cjlisten** [comment]
Gern: Ich nutze PerformancePackL, mit PerformancePackM sollte es auch gehen, mit XL und XXL sowieso.

https://www.1blu.de/webhosting/performancepakete/

**Comment by xchs** [comment]
Ok, danke: https://github.com/contao/contao-manager/wiki/1blu

**Comment by aschempp** [comment]
Added in 4c473fa85d9fd686bc2a6daaf08dd59fd9fc2432 and  c24b463804604914a811f51e6b818cc99c8be237
