### ISSUE TITLE
dogado SSD-Webhosting und Contao Manager

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao-manager#204]
Der Contao Manager funktioniert bei dogado Webhosting bei dem SSD-Webhosting "WEB XL 2.0" Paket (Webspace und MySQL-Datenbank auf SSD) einwandfrei.
Andere Pakete bei dogado habe ich nicht getestet.
Auch Contao Erweiterungen lassen sich sauber installieren und updaten.
Der Contao Manager erkennt den PHP-Pfad "/opt/plesk/php/7.1/bin/php" automatisch bei aktiviertem PHP 7.1.8 beim Hosting.
Andere PHP-Versionen bei dogado Webhosting habe ich bisher nicht getestet.
Insofern könnte dogado GmbH in die Hostingliste zum auswählen beim Contao Manager mit aufgenommen werden.
Contao 4.5.1-MySQL-Info: Bei dogado SSD-Webhosting wird "innodb_large_prefix" nicht unterstützt und kann laut Support zur Zeit auch nicht aktiviert werden. Es muss wie auf "https://github.com/contao/managed-edition#innodb-large-prefix" beschrieben verfahren werden inkl. den Einträgen "charset: utf8" und "collate: utf8_unicode_ci" bei der Installation von Contao 4.5.1, damit es beim aktualliseren der Datenbank nicht zu fehlern kommt. Der Zeichensatz der MySQL-Datenbank kann auf "utf8mb4-unicode" in phpMyAdmin bei dogado eingestellt werden bei den einzelnen Datenbanken, was aber nichts bringt, da der utf8-Zeichensatz verwendet werden muss, damit es nicht zu Fehlern kommt bei der Datenbankaktuallisierung.

**Comment by aschempp** [comment]
Ist in https://github.com/contao/contao-manager/commit/4c473fa85d9fd686bc2a6daaf08dd59fd9fc2432 ergänzt.
