### ISSUE TITLE
Neuer Hosting Anbieter für Contao Manager

### ISSUE THREAD

**Issue by andreasbrauchle** [contao/contao-manager#205]
Folgender Hosting-Anbieter sollte für den Contao Manager aufgenommen werden:

www.netzone.ch

**Comment by kikmedia** [comment]
Könntest Du mit weiteren Informationen beitragen? Die PHP-Versionen und -Pfade wären extrem nett.

**Comment by andreasbrauchle** [comment]
Hallo

Folgend die Angaben zu den Versionen und Pfaden:

Die PHP-Binaries befinden sich unter /usr/bin/

je nach gewünschter PHP-Version lautet der Pfad dann:

/usr/bin/php7.2
/usr/bin/php7.1
/usr/bin/php7.0
/usr/bin/php5.6

Mit besten Grüssen,

Andreas Brauchle
Senior Project Management Consultant/Trainer
[cid:image003.jpg@01D1F8A9.9AD3D370]
4Projects GmbH
Hauptsitz Verwaltung
Hofmattstrasse 180
CH - 5277 Hottwil

Tel. Schweiz 062 875 10 00
Tel. Ausland +41 62 875 10 00

andreas.brauchle@4projects.ch<mailto:andreas.brauchle@4projects.ch>
www.4projects.ch<http://www.4projects.ch/>

Unterrichtsstandorte in Dietikon und Bern-Zollikofen
4Projects – für besseres Projektmanagement

Von: Carolina M. Koehn [mailto:notifications@github.com]
Gesendet: Dienstag, 9. Januar 2018 11:57
An: contao/contao-manager <contao-manager@noreply.github.com>
Cc: Andreas Brauchle - 4Projects <andreas.brauchle@4projects.ch>; Author <author@noreply.github.com>
Betreff: Re: [contao/contao-manager] Neuer Hosting Anbieter für Contao Manager (#205)


Könntest Du mit weiteren Informationen beitragen? Die PHP-Versionen und -Pfade wären extrem nett.

**Comment by xchs** [comment]
Ich habe diesbezüglich schon vor knapp einer Woche einen Wiki-Eintrag erstellt: https://github.com/contao/contao-manager/wiki/NetZone

Siehe dazu auch https://github.com/contao/contao-manager/issues/197

**Comment by aschempp** [comment]
Fixed in https://github.com/contao/contao-manager/commit/4c473fa85d9fd686bc2a6daaf08dd59fd9fc2432
