### ISSUE TITLE
Erweiterte Angaben zu installierten Paketen

### ISSUE THREAD

**Issue by fkaminski** [contao/contao-manager#207]
Im CM (1.0.0-beta13) werden über die Paket Suche inkompatible Pakete/Erweiterungen, basierend auf der aktuell installierten Contao Version, so gekennzeichnet und können nicht installiert werden.

Es wäre evtl. hilfreich bei den bereits installierten Paketen bzw.  externen Erweiterungen
zusätzliche Angaben zu erhalten:

- Bis zur welcher Contao Version ein Paket freigegeben ist
- Ob eine neuere Version des Paketes vorliegt

**Comment by aschempp** [comment]
Diese Information is aktuell über packagist.org (im More-Link) verfügbar.

**Comment by fkaminski** [comment]
Schon,
ich dachte wenn man bereits inkompatible Pakete auszeichnen kann, 
das man dann eh auf diese Informationen zugreifen kann/könnte.

Insofern wäre es schön diese Angaben sofort einzusehen und nicht erst über die externen Links gehen zu müssen bzw. erst nach einer Aktualisierung feststellen zu müssen das z.B. Contao nicht aktualisiert werden kann da eine installierte Erweiterung nicht für die avisierte Contao Update Version freigegeben ist. (Dies evtl. auch in Zusammenhang mit [#199](https://github.com/contao/contao-manager/issues/199)
