### ISSUE TITLE
Fehler in beta13: Solver will zu viel Speicher, Installation wird abgebrochen

### ISSUE THREAD

**Issue by cjlisten** [contao/contao-manager#208]
Der Fehler tritt erst seit beta13 auf. Die beta13 ließ micht nicht einmal Contao 4.4.12 installieren. Mit einem Contao-Manager beta10 aus einer älteren Installation konnte ich die 4.4.12 dagegen installieren, aber beide Versionen weigern sich, die Rocksolid-Pakete zu installieren, auch nicht einzeln.

Hosting: 1blu PerformancePaketL

Hier die Fehlermeldung (Habe die Pfade am Anfang gekürzt. Contao ist in einem eigenen Unterordner, der Manager wie es sich gehört im darin liegenden Ordner web.)

> Using version ^2.2 for madeyourday/contao-rocksolid-custom-elements
[…]/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Error: "Allowed memory size of 1610612736 bytes exhausted (tried to allocate 268435456 bytes)" in phar:/// […] web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/Solver.php on 220

                                                                               

>   [Symfony\Component\Debug\Exception\OutOfMemoryException]                     
  Error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate  
   268435456 bytes)                                                            

>                                                                                
> 
> Exception trace:
>  () at phar:/// […] /web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/Solver.php:220
> 
> tenside:runtask [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--disable-events] [--] <command> <taskId>
> 
> Segmentation fault
> 
> 
> Process terminated with exit code 139
> Reason: Segmentation violation

**Comment by fritzmg** [comment]
Das ist vermutlich kein Fehler der beta13. Dass das dependency resolving jetzt plötzlich mehr Speicher braucht als damals ist nicht ungewöhnlich und auch sogar zu erwarten.

**Comment by arboc** [comment]
Ich habe einen ähnlichen Fehler mit der beta13 und php7.1 beim Aktualisieren der Pakete:

```
Loading composer repositories with package information
Updating dependencies
Error: "Out of memory (allocated 454041600) (tried to allocate 50331656 bytes)" in phar:///kunden/426841_70794/rp-hosting/5146045/6146045/vernetzt/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/RuleSet.php on 83

mmap() failed: [12] Cannot allocate memory
mmap() failed: [12] Cannot allocate memory
mmap() failed: [12] Cannot allocate memory

Process terminated with exit code 255
Reason: Unknown error
```

über die bash kann ich ein update machen.

**Comment by fritzmg** [comment]
@arboc welcher Hoster?

**Comment by arboc** [comment]
https://jweiland.net/

Im Contao-Manager ist derselbe Pfad zur Binary eingetragen, wie ich ihn in der bash genutzt habe.

**Comment by fritzmg** [comment]
Der Hoster hat vermutlich den maximalen Speicherverbrauch des Web Prozesses (und allen Forks davon) limitiert - oder einfach kein swap file definiert.

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
