### ISSUE TITLE
Ist es möglich, Infomaniak (CH) hinzufügen im Contao-Manager Install tool ?

### ISSUE THREAD

**Issue by najbo** [contao/contao-manager#209]
Hallo,

Infomaniak ist eine wichtige schweizer Hosting Company.

Ich habe diese Seite vorbereitet : https://github.com/contao/contao-manager/wiki/Infomaniak
Leider ist es mir noch unmöglich, mit dem -d parameter memory_limit=1024 (Max. ist 1'280MB) zu testen.

Die Memory Limit beträgt sich momentan auf 128MB.

Besten Dank und MfG

Jan Boesch
CH-2520 La Neuveville

**Comment by aschempp** [comment]
Was im Wiki ist wird immer in der nächsten Version ausgeliefert. Ich hab es in https://github.com/contao/contao-manager/commit/4c473fa85d9fd686bc2a6daaf08dd59fd9fc2432 hinzugefügt 😊

**Comment by najbo** [comment]
Vielen dank !

**Comment by najbo** [comment]
Sorry @aschempp , ich wollte eigentlich #256 hier schreiben.
