### ISSUE TITLE
Autoscroll for console

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#21]
The console should automatically scroll to the latest line

**Comment by discordier** [comment]
Only if it was on the last line before adding new content. I hate when console jumps down when I have scrolled up before.

**Comment by Toflar** [comment]
Implemented in a0a52d57b715a94ed2004b69d955a7748f58ea07.

**Comment by aschempp** [comment]
But now it also scrolls if you're not at the bottom, right?

**Comment by Toflar** [comment]
It only scrolls down if you did not manually scroll (see https://github.com/contao/contao-manager/commit/d7e703ebcc89a7547468ebdd42fb19dfb0a464fa).

**Comment by discordier** [comment]
I enhanced it by detecting the "scrolled" flag in every iteration.
