### ISSUE TITLE
Contao Manager beta13 prüft falschen Pfad zum PHP-Binary

### ISSUE THREAD

**Issue by falkotimme** [contao/contao-manager#212]
Wenn man als Hostinganbieter "Timme Hosting" auswählt, prüft der Contao Manager einen falschen Pfad zum PHP-Binary. Hat man z.B. PHP 7.1.13 für die Website ausgewählt, liegt das PHP-Binary unter /opt/php-7.1.13/bin/php - der Contao Manager prüft aber auf /opt/php-7.1/bin/php und gibt dann eine Fehlermeldung aus. 

Das Setzen eines Symlinks ist keine Option, da es noch weitere PHP-Versionen unter 7.1 gibt. Generell folgt der Pfad diesem Schema: /opt/php-x.y.zz/bin/php

Auf https://github.com/contao/contao-manager/wiki/Timme-Hosting wird die Unterversion ebenfalls nicht berücksichtigt.

**Comment by aschempp** [comment]
Danke, ich habe den Pfad im Wiki und im Manager angepasst (wird mit dem nächsten Release ausgeliefert).
