### ISSUE TITLE
Add ICU requirements check for Contao 4.5

### ISSUE THREAD

**Issue by ausi** [contao/contao-manager#214]
See contao/check#136

**Comment by aschempp** [comment]
Is this still necessary since we changed the ICU requirements?

**Comment by ausi** [comment]
IMO yes. The minimum ICU version is 4.2.1 now, see https://github.com/contao/check/commit/3b06187e4a09081d91d92cf4b810433cca1ecc7f

**Comment by aschempp** [comment]
If I understand correctly, this is only a requirement for Contao 4.5 and later? So the manager should be able to install Contao 4.4, which means this can't be a "fail" check.

**Comment by ausi** [comment]
Correct.

**Comment by aschempp** [comment]
I think this is obsolete by now.
