### ISSUE TITLE
Hosting-Anbieter wird nicht erkannt

### ISSUE THREAD

**Issue by asdfasdfasa** [contao/contao-manager#215]
Folgende Hostinganbieter werden vom Contao Manager unter anderem nicht erkannt:
Iway
Hoststar

**Comment by frontendschlampe** [comment]
Wenn du uns die entsprechenden Infos gibst (wie z.B. hier: https://github.com/contao/contao-manager/issues/205), dann können wir die Anbieter gern hinzufügen. Auch das Anlegen eine WIKI-Seite https://github.com/contao/contao-manager/wiki wäre super!

Vielen Dank für Deine Mithilfe.

**Comment by asdfasdfasa** [comment]
Hallo Nicky

Herzlichen Dank für das schnelle Reagieren!
Der Binary Pfad für Iway lautet: /usr/bin/php7.1

Für das andere Hosting (Hoststar) werde ich mich zu einem späteren Zeitpunkt melden.

**Comment by asdfasdfasa** [comment]
Hallo Nicky

Vielleicht darf ich dich zu einem anderen Thema gleich noch etwas fragen. In den Foren steht teilweise, dass der web Ordner gar nicht zum Document-Root gemacht werden muss.
Trotzdem scheitere ich nun wiederholt an diesem Problem.

Bei mir erscheint folgende Fehlermeldung, wenn ich das Installtool abrufen möchte.

**Comment by xchs** [comment]
Diese Frage solltest Du im Forum stellen.

**Comment by frontendschlampe** [comment]
Du darfst gern Fragen stellen, aber nicht hier! ;-) Das würde das Ticket hier sprengen und vom eigentlichen Thema ablenken. Kannst mich gern im Forum anschreiben bzw. in einem Forumsthread erwähnen!
