### ISSUE TITLE
Respect user.ini

### ISSUE THREAD

**Issue by kikmedia** [contao/contao-manager#216]
On some web hosts one will need some configuration files, for example on setting the PHP version or on configuring PHP behaviour (like max_execution_time, memory_limit, allow_url_fopen and so on).

But on start up before installation on the initial check, the Manager doesn't expect these kind of files and will not run, forcing the user to delete a user.ini file (probably a php.ini file too, but I didn't check that out for now).

So, the only workaround is to remove that *.ini file and create it again after the Manager has shown up. IMO, the existence of a *.ini file should not prevent the Manager from starting up.

**Comment by xchs** [comment]
That is probably a limitation of the `composer create-project` command. Git and SVN also don't allow to clone in a non-empty directory.

**Comment by kikmedia** [comment]
At the first glance, I also thought it is, but this behavour is only shown on the initially performed check _before_ installation. If you manage to enter the Manager, it doesn‘t care about any files at all, so this can’t be the reason.

**Comment by xchs** [comment]
Ah, yes, you're right. The Contao Manager first creates the project in a temporary directory (e.g. `install-5a7c443cadf6b`) and then moves the entire contents of this directory to the actual Contao root directory.

**Comment by aschempp** [comment]
Added in 8c98eef4c3327f16c061a3b3ae6eb342903031d7
