### ISSUE TITLE
Hosting: world4you.com

### ISSUE THREAD

**Issue by jankout** [contao/contao-manager#218]
Leider wird der eingegebene PHP-Binary-Pfad nicht akzeptiert bzw. erkannt, obwohl laut Kundenservice alles stimmen sollte. 

Für 7.2 usr/bin/php72-cgi
Für 7.1 usr/bin/php71-cgi
Für 7 usr/bin/php7

Für 7.x hat es geklappt. Bei 7.1 oder 7.2 kommt folgende Fehlermeldung. 
<img width="432" alt="php" src="https://user-images.githubusercontent.com/3715050/35982287-b4830ba4-0cef-11e8-9c64-6cd1c4138e41.png">

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
