### ISSUE TITLE
Benutzerrechte

### ISSUE THREAD

**Issue by asdfasdfasa** [contao/contao-manager#220]
Wie kann ich einen neuen Benutzer für den Manager anmelden?
Vielen Dank im Voraus.

**Comment by frontendschlampe** [comment]
Aktuell ist es nicht möglich, weitere Benutzer zum Manager anzumelden!

**Comment by xchs** [comment]
Es ginge schon, nur müsste man derzeit weitere Benutzer manuell in der `users.json` hinzufügen.

**Comment by asdfasdfasa** [comment]
Super! Ganz herzlichen Dank..
Mein erster Versuch mit manuell hinzufügen klappte allerdings nicht.
Nun erscheint die Fehlermeldung:
«Bitte machen Sie den Unterordner web/ zum Document-Root, indem Sie das Domain-Routing in Ihrem Server-Control-Panel bzw. die Vhosts-Datei Ihres Webservers anpassen.»

Den Webordner hatte ich ja bereis zum Document-Root gemacht.
Das File:
contao-manager/users.json
löschen brachte nichts.

**Comment by asdfasdfasa** [comment]
Die Neuinstallation des Managers hat nun geklappt.
http://www.domainname.ch/web/contao-manager.phar.php

Die Frage ist nun nur noch, wie es manuell möglich ist, einen zweiten Benutzer in die users.json Datei einzufügen :-)

**Comment by xchs** [comment]
Ja, das ist durchaus möglich. Bei mir hat es jedenfalls einwandfrei funktioniert.

Was bei Dir aber noch immer falsch ist, ist der DocumentRoot. Wenn Du den DocumentRoot der Domain korrekt auf den `web/` Unterordner setzt, brauchst Du das URL-Fragment `web` in der URL nicht anzugeben.

**Comment by asdfasdfasa** [comment]
Der DocumentRoot wurde von meinem Hoster gesetzt:
<IfModule rewrite_module>
	#redirect to subdirectory /web (for contao)
	RewriteEngine On
	RewriteRule !^web(/.*)?$ /web%{REQUEST_URI} [QSA,L]
</IfModule>


Seltsamerweise befindet sich mein contao-manager im RootRoot also nicht im webRoot. Aber solange es funktioniert. (Die contao-manager.phar.php befindet sich im web Ordner)
In den Contao Backend komme ich.

Mein Problem ist aber immer noch, dass ich nicht weiss, wie ich einen zweiten Benutzer händisch in das users.json setzen kann.

**Comment by xchs** [comment]
> Mein Problem ist aber immer noch, dass ich nicht weiss, wie ich einen zweiten Benutzer händisch in das users.json setzen kann.

`contao-manager/users.json`
```json
    "users": {
        "k.jones": {
            "username": "k.jones",
            "password": "$2y$13$qHP4BYQ968vUCY2mDjceoeVIMZ8qwd27ztxswJd6SjX8Dz8Q8f.8u"
        },
        "foobar": {
            "username": "foobar",
            "password": "$3c$14$qHZ4BMQN16vUlY2yDjceoeMIAZ8qwd29ztxpwJd6ShC8Dz8Q5f.8u"
        }
    },
```

**Comment by asdfasdfasa** [comment]
Vielen Dank für den Code.

Bei mir sieht das Passwort so aus.
"password": "$2y$13$vadb6Mdzuh7.\/yZipF.\/Z.8Ieztv6FYwV5nSFe4b0LoEXo0xBCHJK"

Irgendwie komme ich nicht drauf, wie ich ein Passwort händisch beim zweiten User definieren kann.

**Comment by xchs** [comment]
Du kannst Dich diesbezüglich gerne im [Forum](https://community.contao.org) melden.

**Comment by aschempp** [comment]
Bitte das Forum für Fragen verwenden, hier geht es um Bugs und Feature Requests.
