### ISSUE TITLE
issue after update from 1.0.0-beta13 to 1.0.0-beta14

### ISSUE THREAD

**Issue by goransi** [contao/contao-manager#223]
![screenshot from 2018-02-15 21-45-24](https://user-images.githubusercontent.com/36036196/36280244-f761f1d8-1299-11e8-8cef-cd57342241c9.png)
Hello!
I have auto upgraded contao-manager.phar.php from 1.0.0-beta13 to 1.0.0-beta14
after upgrading can't move to list of modules, because it can't recognize my PHP Binary /opt/cpanel/ea-php71/root/usr/bin/php
What I can to do, to fix this issue?
best regards

**Comment by goransi** [comment]
after upgrading to 1.0.0-beta15 still the same issue :-(

**Comment by aschempp** [comment]
What do you mean by "the same errors"? One is a UI message and the other is a PHP exception?

**Comment by goransi** [comment]
first is a error from contao-manager second I found in error log file.
Do you have any idea how to I fix it?
regards
