### ISSUE TITLE
Contao Manager 1.0.0-beta15 / Neue Funktion Composer Abhängigkeiten / ERROR 500 Cannot delete a running process.

### ISSUE THREAD

**Issue by Zwergenmeister** [contao/contao-manager#224]
Hallo,

vielen Dank erstmal für die neuen Funktionen in beta 15 sieht sehr gut aus musste es auch direkt testen :-) 
Hab mich die ganzen letzten Tage mit dem composer befasst und 4 laufende C4 installation mit einer lokal aufgelösten composer.lock über ssh upgedatet. Mit diesem Befehl /usr/bin/php7.1-cli composer.phar install --optimize-autoloader  

Das funktioniert auch soweit prima wenn mann das mit dem Composer auch erstmal alles verstehen musst ist es doch eine gute Erleichterung. 

Deshalb direkt der Test leider ist nur das Task Fenster im Manger aufgegangen und nix passiert hab 10 Minuten gewartet dann abgebrochen und 5 min später das Fenster geschlossen. 

Jetzt hänge ich in das hier:
ERROR 500 Cannot delete a running process.

Wie werde ich den Prozess wieder los ?   

Würde gerne noch behilflich sein das zu testen oder das Problem zu finden. 

Gruß
Zwergenmeister

**Comment by aschempp** [comment]
Du kannst die entsprechenden Dateien im Ordner `contao-manager` (tenside-tasks.json und background-task.json oder ähnlich) löschen, dann ist der Task weg.
Bitte solche Fragen aber im Forum stellen, hier geht es um's Bug- und Feature-Tracking.
