### ISSUE TITLE
Label und Beschreibung für "dump-autoload"

### ISSUE THREAD

**Issue by fiedsch** [contao/contao-manager#225]
Die Bezeichnung
```
"ui.maintenance.dumpAutoload.button": "Autoloader leeren"
``` 
(https://github.com/contao/contao-manager/blob/master/src/assets/i18n/de.json#L142)
sollte m.E. in Analogie zu 
```
"ui.maintenance.rebuildCache.button": "Cache neu erstellen"
``` 
benannt werden ("Autoloader neu erstellen").

Die aktuellen Texte passen zwar zur Composer-Bezeichnung `dump-autoload`, aber mit 
`composer dump-autoload` wird ja nicht nur die alte Autoload-Info gelöscht (ge"dump"t), sondern auch neue erstellt.

Entsprechend auch der Hilfstext in
```
"ui.maintenance.dumpAutoload.description"
```

**Comment by aschempp** [comment]
"dump" bezieht sich in diesem Fall auf "schreiben" und nicht "wegwerfen". Ich habe die Übersetzung auf Transifex nun verbessert.
