### ISSUE TITLE
Suggested packages

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#23]
Allow the user to install suggested packages even if they are not of type `contao-bundle`. Probably provide a screen with suggestions.

**Comment by Toflar** [comment]
For anyone waiting for that feature, here's what you can do until that feature is built into the Manager:

1. Open the `contao-manager/manager.json` and copy the `php_cli` value. That's the php binary the Contao Manager works with and we want to use the very same.
2. SSH to your server and navigate to the project directory of Contao (so not within `web`).
3. Then run `<php_cli> ./web/contao-manager.phar.php composer require <package-name>`

Example:
Your project is in `/var/www/project/htdocs`, your `DirectoryIndex` points to `/var/www/project/htdocs/web` and your `php_cli` contains `/usr/bin/php` and you want to install `phpoffice/phpexcel`:

1. `cd /var/www/project/htdocs`
2. `/usr/bin/php ./web/contao-manager.phar.php composer require phpoffice/phpexcel`

**Comment by aschempp** [comment]
Added in Contao Manager 1.2
