### ISSUE TITLE
Feature: PHP option -d memory-limit=-1

### ISSUE THREAD

**Issue by arboc** [contao/contao-manager#230]
Wir haben das Problem, dass einige Hoster das memory-limit für ein composer update zu gering gesetzt haben. Hilfreich wäre bei der Ausführung die PHP-Option `-d memory-limit=-1`

**Comment by xchs** [comment]
Eigentlich versucht der Contao Manager eh schon, das Speicherlimit bei Bedarf entsprechend zu erhöhen: https://github.com/contao/contao-manager/issues/90#issuecomment-359832734

**Comment by arboc** [comment]
Leider wird aber folgender Fehler protokolliert:

```
[20-Feb-2018 16:54:01 Europe/Berlin] [2018-02-20 16:54:01] app.ERROR: Error: "Out of memory (allocated 454041600) (tried to allocate 50331656 bytes)" in phar:///kunden/426841_70794/rp-hosting/5146045/6146045/vernetzt/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/RuleSet.php on 83 [] []
```

**Comment by aschempp** [comment]
Die Einstellung lässt sich nur für bekannte Hosting-Anbieter vornehmen, und diese müssen das auch entsprechend unterstützen. Bei welchem Hosting-Anbieter hast du das Problem?

**Comment by arboc** [comment]
jweiland.net

**Comment by aschempp** [comment]
Der Anbieter ist zur Zeit nicht bekannt, wenn du die nötigen Informationen im Wiki ergänzt können wir den in die Liste aufnehmen.
