### ISSUE TITLE
Feature Request: Update just one particular bundle

### ISSUE THREAD

**Issue by Shoekrates** [contao/contao-manager#231]
It would be nice to have the possibility to update just one particular bundle or plugin (erweiterung). 
If you click on „Pakete aktualisieren“ the function will update all available bundles in your Contao installation. But it could be helpful to update just the bundle you want, not all.
Right now you can help yourself by setting all other installed bundles to a specific version before clicking the button „Pakete aktualisieren“ – but this is pretty cumbersome.

**Comment by aschempp** [comment]
Meanwhile implemented in Version 1.0
