### ISSUE TITLE
No Console Output / black window - Beta15

### ISSUE THREAD

**Issue by Stefko** [contao/contao-manager#232]
I've installed 4.4.14 on my local machine (MAMP, PHP7.1.12) with ConataoManager Beta15 and everything was ok.
Later tried to install some bundles, the console windows opened (Loading Console Task …) but there was no output about the progress - only a black empty window.
After about 30min I've terminated the process and reloaded the ContaoManager and NOW the green console box appeared and informed that the install was ok, incl. the "Installtool-Button" and complete output in the console window.
Tried it different times, always with the same result. Also no difference between install a new bundle or updating the existing bundles.

Link to the ContaoForum: https://community.contao.org/de/showthread.php?69868-Paketmanager-funktioniert-nicht-(4-4-14)-Keine-Reaktion-in-der-Konsole-(Hostpoint)

**Comment by aschempp** [comment]
This is most likely related to https://github.com/contao/contao-manager/issues/229 and closed in beta16. Let me know if it still appears so we can re-open the issue.
