### ISSUE TITLE
don't use overflow:scroll on body

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-manager#234]
This makes the page jump on browsers/systems with fixed scrollbars. Instead of adding this via JavaScript, the following should be added to the CSS:
```css
body {
    overflow-y: scroll;
}
```

**Comment by aschempp** [comment]
I disagree with this change. Forcing a scroll bar can never be a solution, there's a reason this is not the default in any browser …

**Comment by fritzmg** [comment]
Yet, it's the most common practise, otherwise you get jumping content on Windows ;)

**Comment by ausi** [comment]
I agree with @fritzmg adding `overflow-y: scroll` is best practice.

**Comment by fritzmg** [comment]
@leofeyer disagrees as well unfortunately. The Contao back end has the same problem.

**Comment by fritzmg** [comment]
And, as already pointed out [here](https://github.com/contao/core/issues/2832#issuecomment-312688403) - even the CSS specification recommends using this.

**Comment by Aybee** [comment]
I always put it successful to every CSS onto HTML.
```css
html {
  overflow-y: scroll;
}
```
This content jumping is very ugly and not user friendly. You open a palette or BE navigation item and content jumps from right to left without this CSS.

**Comment by aschempp** [comment]
Again, this is opinionated, and I don't think we will agree on this. If this is an issue for you, it will be an issue on every website you ever use. You should adjust your browser to fix this (e.g. https://www.userchrome.org), and not assume that every project will adjust to your preference.

**Comment by fritzmg** [comment]
> If this is an issue for you, it will be an issue on every website you ever use.

That's not true, since this is used on most websites anyway. You cannot make assumptions on how the scroll bars are rendered, hence you need to make sure an element's width does not change when its content changes due to scrollbars.

> You should adjust your browser to fix this (e.g. https://www.userchrome.org), and not assume that every project will adjust to your preference.

That won't help, since the scrollbars are rendered by the same in every browser.

**Comment by leofeyer** [comment]
> @leofeyer disagrees as well unfortunately.

Yes, and I stand by my opinion. Showing a scroll bar even if there is nothing to scroll is bad UX.

**Comment by fritzmg** [comment]
> Showing a scroll bar even if there is nothing to scroll is bad UX.

The content jumping left and right due varying content length is also a bad User Experience. The scroll bar always showing on Windows systems is imho negligible negative user experience, since you will have the scroll bar anyway, if you have enough content. (And if you never have enough content - or always a full screen application, then you do not need `overflow-y: scroll` anyway.)

**Comment by leofeyer** [comment]
A scroll bar is a **UX element** with a certain **meaning**, just like buttons, input fields etc. If there is a scroll bar, it means "you can scroll here to see more content". However, if there is no more content, the scroll bar is misleading.

You would not show a submit button if there is nothing to submit, either, would you?

**Comment by ausi** [comment]
> If there is a scroll bar, it means "you can scroll here to see more content".

The [CSS spec](https://www.w3.org/TR/css-overflow-3/#valdef-overflow-scroll) disagrees with that: _if the user agent uses a scrolling mechanism that is visible on the screen (such as a scroll bar or a panner), that mechanism should be displayed whether or not any of its content is clipped. This avoids any problem with scrollbars appearing and disappearing in a dynamic environment._

> You would not show a submit button if there is nothing to submit, either, would you?

I would show the submit button in a disabled state (presumed that it will be activated later).

**Comment by leofeyer** [comment]
> that mechanism should be displayed whether or not any of its content is clipped. This avoids any problem with scrollbars appearing and disappearing in a dynamic environment.

Hm, seems I need to reconsider. 😄

**Comment by aschempp** [comment]
> if _**the user agent**_ uses a scrolling mechanism that is visible on the screen (such as a scroll bar or a panner) …

I do not know if your user agent implements a scrolling mechanism. I don't care. It's your user agent's job to do that, not mine. My user agent (Mac OS X / Safari) does follow the CSS spec, sorry if yours does not…

**Comment by fritzmg** [comment]
The CSS specifications specifies whether a scroll bar should take up space?

**Comment by backbone87** [comment]
if you want to go fully overboard with this optimization: https://developers.google.com/web/updates/2017/03/custom-scrollbar :)

as a windows user, i much prefer an always visible scrollbar, than having a jumping page. and btw. the windows scrollbar has a disabled state, if no content is clipped and therefore no scrolling is possible.
