### ISSUE TITLE
Installation schlägt ohne Fehlermeldung fehl

### ISSUE THREAD

**Issue by ghost** [contao/contao-manager#238]
Hallo,
ich versuche seit Tagen eine Testinstallation mit Contao 4.x auf meinem Webspace durchzuführen. Leider schlägt diese immer ohne erkennbaren Grund fehl. Ich nutze den neusten Contao-Manager und den default-Pfad der PHP-Binary. Es läuft auch alles sauber durch bis zur Meldung Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication.
Hier geht dann nichts mehr. Bei der Version 4.4 steht noch was von "system/logs" und bei der 4.5 "...tcpdf...".
Nach einiger Zeit verschwindet der Dialog und zeigt auch kurz den Abschluss der Installation an (samt Button zum Installtool). Dieser wird dann aber von "ERROR 500 Unknown installation status" überlagert.

Hier sieht man den Abschlussdialog mit dem Error 500.
![ohne titel](https://user-images.githubusercontent.com/37046050/36947939-42d63d54-1fd3-11e8-80da-5507876e8d8a.jpeg)

Im Log finde ich kein Fehler. Der Log des Contao-Managers enthält nur die Konsolenausgaben:
Auszug des letzen Teils:
[OK] All assets were successfully installed.                                   

 * system
 * system/config
 * templates
 * web/system
 * files
 * assets/css
 * assets/js
 * system/cache
 * system/modules
 * system/themes
 * system/tmp
 * web/share
 * assets/images

 Added/updated the system/initialize.php file.

 Symlinked the system/config/tcpdf.php file.

 --- ------------------------ ---------------------------------------------------------------- 
      Symlink                  Target / Error                                                  
 --- ------------------------ ---------------------------------------------------------------- 
  ✔   system/themes/flexible   vendor/contao/core-bundle/src/Resources/contao/themes/flexible  
  ✔   web/assets               assets                                                          
  ✔   web/system/themes        system/themes                                                   
  ✔   system/logs              var/logs                                                        
 --- ------------------------ ---------------------------------------------------------------- 

Leider bin ich mit der neuen Contao-Generation nicht mehr so vertraut.

System: PHP 7.2
Hoster: serverprofis

**Comment by aschempp** [comment]
It looks like the vendor folder could not be moved from the temporary installation directory to your hosting root. This might be because there are a lot of files to move and I've seen hosting providers with horrible filesystem performance (e.g. a virus scanner) that caused the process to time out.

There's nothing the Manager can currently do for this, but an upcoming version will eventually solve this by not using a temporary installation folder (also to fix Windows issues).

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
