### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by srhinow** [contao/contao-manager#239]
Egal was ich ausführen will mit dem contao-manager "Pakete aktualisieren", "Cache neu aufbauen" etc kommt in dem halbtransparenten schwarzen Layer folgender Fehler:
`ERROR 500 Error: Uncaught Error: Call to a member function getId() on null in phar:///var/www/s/sr-tag/sr-tag_4.4/contao4/web/contao-manager.phar.php/api/Controller/TaskController.php:136 Stack trace: #0 phar:///var/www/s/sr-tag/sr-tag_4.4/contao4/web/contao-manager.phar.php/api/Controller/TaskController.php(81): Contao\ManagerApi\Controller\TaskController->putTask(Object(Symfony\Component\HttpFoundation\Request)) #1 phar:///var/www/s/sr-tag/sr-tag_4.4/contao4/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(151): Contao\ManagerApi\Controller\TaskController->__invoke(Object(Symfony\Component\HttpFoundation\Request)) #2 phar:///var/www/s/sr-tag/sr-tag_4.4/contao4/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #3 phar:///var/www/s/sr-tag/sr-tag_4.4/contao4/web/contao-manager.phar.php/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Obj`

**Comment by aschempp** [comment]
Sieht aus als könnte der Contao Manager seine Konfigurationsdateien nicht speichern. Ist ein Order "contao-manager" im Root vorhanden und stimmen die Berechtigungen?

**Comment by srhinow** [comment]
ja das lag an den Berechtigungen. War offline hab dann chmod -R 777 . gemacht und dann ging es. 

Sorry hab vergessen das issue hier zu schließen.
