### ISSUE TITLE
Feature Request: Composer Cache via Contao Manager löschen

### ISSUE THREAD

**Issue by mimamuxx** [contao/contao-manager#241]
Hallo zusammen,
ich habe ein Contao auf einem Server ohne SSH laufen (was auch aus diversen Gründen nicht aktiviert werden kann). Bei dieser Installation wäre es notwendig den Composer Cache zu löschen und nun bin ich aufgeschmissen und kann gerade Contao nicht mehr updaten ohne die Installation zu schrotten.

Immer wieder ist es wichtig den Compose Cache zu löschen. Daher schlage ich vor, dass als neues Feature in den Contao Manager mit aufzunehmen. Herzlichen Dank schon mal!

**Comment by aschempp** [comment]
Was meinst du genau mit dem Composer Cache?

**Comment by xchs** [comment]
@mimamuxx Meinst Du das?
```console
composer clear-cache
```
https://getcomposer.org/doc/03-cli.md#clear-cache-clearcache-

**Comment by mimamuxx** [comment]
ja genau.
`composer clear-cache`

**Comment by aschempp** [comment]
In welchem Fall muss man denn einen Composer Cache leeren?? Da sind die Pakete drin, oder?

**Comment by mimamuxx** [comment]
Vielleicht hier mal der Hintergrund meiner Anfrage: https://community.contao.org/de/showthread.php?70142-Contao-Update-schl%C3%A4gt-permanent-fehlt-(4-4-13-gt-4-4-16)

**Comment by BugBuster1701** [comment]
Offensichtlich liegen beim Ihm fehlerhafte Pakete drin. Daher der Versuch die über clearcache zu löschen.
```
- Updating contao/installation-bundle (4.4.13 => 4.4.16): Loading from cache 
    Invalid zip file, retrying... 
Loading from cache 
    Invalid zip file, retrying...
```

**Comment by mimamuxx** [comment]
Hallo, leider bin ich gerade auf diese Funktion angewiesen.
Wird das kommen @aschempp ?

**Comment by xchs** [comment]
Könntest Du den Cache inzwischen nicht auch manuell via SFTP löschen?

**Comment by mimamuxx** [comment]
stimmt, danke!
Wäre aber trotzdem eine gutes Feature. Gerade wenn nichts mehr geht und gerade kein FTP oder SSH bereit steht...
