### ISSUE TITLE
own debian 8 server with php-7.2 in /opt - manager can't find php-binary

### ISSUE THREAD

**Issue by rseffner** [contao/contao-manager#242]
I downloaded contao-manager 1.0.0-beta16 to an debian 8 server running apache2.4 and php (with suexec) using fcgid. So I installed php 7.2 from liveconfig repo to /opt. Via fgcid starter scripts I'm able to use php-configs per domain.

contao-manager's system-check reports to not be able to find a valid php-binary. So I select hoster->other and php-binary->/opt/php-7.2/bin/php where the real file is situated but I'cant save this.
What the hell contao-manager is trying to do wit this binary inside this check? contao-check reports 4.x compatibility.

I can't see anything in log files of apache or suexec. What to do, to get contao-manager working?

**Comment by aschempp** [comment]
Contao Manager tries to execute the binary to check the PHP version. Looks like the file cannot be executed on your server, or the web process might not have access to it?

**Comment by srhinow** [comment]
aschempp: ich habe neuerdings localhost (Linux Mate/Ubuntu) das gleiche Problem das der contao-manager nicht  mehr meine /usr/bin/php oder direkte Pfade zu der Version akzeptiert. 
```
which php
/usr/bin/php
```
/usr/bin/php ist nen Link zu /etc/alternative/php was wieder zu /usr/bin/php7.1 verlinkt ist
```
ls -la /usr/bin/php7.1 
-rwxr-xr-x 1 root root 4542496 Mär  6 13:15 /usr/bin/php7.1*

```
Die "normale"  Ausführung sämtlicher Websites mit PHP sind ja ohne Probleme möglich, nur das der contao-manager.phar.php das neuerdings nicht mehr akzeptiert. Was kann ich noch prüfen?

**Comment by aschempp** [comment]
Der Manager macht nichts anderes als ein `exec()` (bzw. `proc_open`) auf das Binary, wenn das fehlschlägt dann kann er die Datei nicht verwenden. Warum das nicht geh müsstest du mittels PHP-Script selber testen. Vielleicht kann dein Webserver keine Binaries ausführen die `root` gehören. Es kann 1000 Gründe geben warum das nicht funktioniert, und ich kann nicht beurteilen ob ein Host korrekt konfiguriert ist.

**Comment by srhinow** [comment]
ein `exec()` und auch das `proc_open()` funktioniert in einem test-php-Datei wunderbar. Wenn ich normal php und auch mit /usr/bin/php aufrufe.

Das du nicht beurteilen kannst ob ein Host korrekt konfiguriert ist, weiß ich und deshalb hatte ich auch "nur" danach gefragt was ich noch prüfen kann.

Da alles andere (Apache2, PHP7.1 etc) in allen Projekten prima funktioniert nur eben der contao-manager.phar.php neuerdings rumzickt, habe ich dich gefragt.

Kannst du mir die Stelle in dem contao-manager nennen, wo zusehen ist wie er das prueft?

**Comment by srhinow** [comment]
aah ok die php-cli wird benötigt und war bei mir (php7.1-cli) nicht "mehr" auf dem System. Jetzt hab ichs nachinstalliert und nun findet er es auch unter /usr/bin/php. 

Danke

evtl. fehlt ja auch @rseffner das php7.2-cli Paket.
