### ISSUE TITLE
Hosting: Greensta: Installation bleibt hängen

### ISSUE THREAD

**Issue by jankout** [contao/contao-manager#244]
Wenn ich den Contao-Manger starte, nachdem ich alles für den Server eingestellt habe, zeigt nur, dass er den Konsolenbefehl ausführt, aber weiter passiert nichts. Wenn ich die Seite erneut aufrufe, kommt die Fehlermeldung 

> Error 500 cannot delete a running process. 
<img width="793" alt="greensta_cm" src="https://user-images.githubusercontent.com/3715050/37510674-3b323742-28fc-11e8-9732-0cecc401c15d.png">
<img width="354" alt="greensta_cm_2" src="https://user-images.githubusercontent.com/3715050/37510675-3b4c1e14-28fc-11e8-92d4-b1d167c36e81.png">

**Comment by Toflar** [comment]
Möglicherweise zu wenig Memory, ich labele das Issue mal entsprechend, weil wir an einer Lösung arbeiten.

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
