### ISSUE TITLE
ERROR 500 Unknown installation status / Some files were found on your server ...

### ISSUE THREAD

**Issue by bopsoid** [contao/contao-manager#245]
Hello,

Contao Manager stops working with "ERROR 500 Unknown installation status" and telling me:

"Some files were found on your server but no known Contao version could be detected. You must either manually repair your application or remove the following files and folders to install Contao"

And then a list with folders and files follows that are outside (above) the installation folder in the folder hierarchy. To make it clear:

DOCROOT of Hosting
--> Folder A
--> Folder B
--> Folder C
--> Install Folder for Contao

The VHOST setting lets my selected subdomain directly point to the "Install Folder for Contao", so just by using a browser, there is no chance to access the other folder, but those folders (Fodler A, B, C, etc. connected with other subdomains via VHOST settings) are the ones, that are listed by Contao Manager as erroneous.

So Contao Manager is looking for folders and files that are outside the folder where it sits itself.

Any idea what to do? Or is it a known bug?

**UPDATE:** 
System: CentOS 6.6 with Plesk 12.5 / PHP 7.0

Thanks in advance for helping out,
Boris

**Comment by frontendschlampe** [comment]
> The VHOST setting lets my selected subdomain directly point to the "Install Folder for Contao"

That's wrong, you have to set "Install Folder for Contao/web" and in "web" you have to copy the manager ... that means your domain has to point to "Install Folder for Contao/web"

**Comment by bopsoid** [comment]
Ok, thanks. Seems to work now. :-)

**Comment by GwendalB** [comment]
Hi,

I am new here and Contao, and I have the same error, I work with xampp and PHP 7.2.26

I try to install the last version of contao.

I have also the list of choices for the server configuration but I don't know which one I shall use and when I write the path to my web file where contao-manager.phar.php is I have an error too.

What do I do wrong?

Thanks for your answers ;-)

Gwen

**Comment by bopsoid** [comment]
Hello Gwen,

the solution for me was to follow the hint of "frontendschlampe" and it worked. You have to set the document root of your virtual host to the web folder (and it HAS to be named like that). But be sure that the web process is still able to write into the upper folder (keyword: safe mode restriction).

Are you using Xampp on a Windows system? This will not work, as far as I know. Please anybody correct me, if it has changed in the meantime.

So, better use a linux environment.

Good luck and greetings,
Boris
