### ISSUE TITLE
Contao-Manager bricht die Installation auf Contabo mit der folgenden Meldung ab:

### ISSUE THREAD

**Issue by Patmanns** [contao/contao-manager#247]
Der Conatao-Manager konnte einen Konsolentask nicht starten! (Contabo Webspace M)
Die Ausführung ist fehlgeschlagen.
Sollte dies nochmal passieren unterstützt der Contao-Manager ihren Server ggf. nicht!

Hat jemand ähnliche Erfahrungen bzw. eine Lösung dafür parat?

**Comment by Toflar** [comment]
Möglicherweise zu wenig Memory, ich labele das Issue mal entsprechend, weil wir an einer Lösung arbeiten.

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
