### ISSUE TITLE
Contao-Manager 1.0.0-beta17 möchte auf 1.0.0-beta16 upgraden

### ISSUE THREAD

**Issue by Xendiadyon** [contao/contao-manager#248]
Ich habe gerade das Problem, dass mein Contao-Manager mich nicht mehr reinlässt. Ich erhalte die Fehlermeldung, dass die neue Version 1.0.0-beta16 verfügbar ist. Ich habe aber bereits die Version 1.0.0-beta17:
![image](https://user-images.githubusercontent.com/2657385/38088450-2a39fa78-335c-11e8-981e-971c0559c4ce.png)

Auch per Kommandozeile will es immer downgraden:
![image](https://user-images.githubusercontent.com/2657385/38088473-3c681e8c-335c-11e8-80df-3214caa0b4e6.png)

Cache ist bereits geleert.

**Comment by Xendiadyon** [comment]
Ich habe den vendor-Ordner gelöscht: keine Änderung.
Ich habe die composer.json einer anderen, funktionierenden Installation verwendet: Installation funktioniert
Ich habe die alte composer.json wiederhergestellt: Funktioniert weiterhin.

Ein ganz komisches Problem, aber es funktioniert jetzt wieder.

**Comment by aschempp** [comment]
sehr komisch. Es scheint als wird die Versions-Datei nicht korrekt abgerufen oder von deinem Server gecacht. Das sollte aber explizit deaktiviert sein. Ich kann daran leider nicht wirklich was ändern, und wenn der Fehler für dich behoben ist würde ich das Ticket schliessen. Bei neuen Infos können wir es gerne wieder öffnen.
