### ISSUE TITLE
CM bei WebHostOne

### ISSUE THREAD

**Issue by benyi001** [contao/contao-manager#250]
Die Installation bei WebHostOne über den CM geht nicht.
Es kommt immer diese Meldung
Serverkonfiguration
Es wurde kein valides PHP Programm auf dem Server gefunden.

**Comment by benyi001** [comment]
WebHostOne hat nun nach Rückfrage den Arbeitsspeicher erhöht und siehe da es funktioniert.
Gruß Norbert

**Comment by petrad** [comment]
Welches Paket nutzt Du bei Webhostone und wie viel Arbeitsspeicher hast Du nun? 

Bei SingleApp reichte bis vor kurzem der Arbeitsspeicher aus, seit dem Contao Manager v16 leider nicht mehr, es können damit keine Pakete mehr installiert werden.

**Comment by benyi001** [comment]
Single App mit 256 MB RAM

**Comment by aschempp** [comment]
Gerade selber festgestellt, das Problem tritt auch auf wenn z.B. `proc_open` auf dem Server nicht verfügbar ist. Dann kann die PHP-Datei nicht korrekt geprüft werden. In der nächsten Version (Beta18) wird das korrekt überprüft.

**Comment by xchs** [comment]
Seit dem Update des Contao Managers auf die stabile Version 1.0.0 wird offenbar die PHP Binary nicht mehr automatisch erkannt ("_Es wurde kein valides PHP Programm auf dem Server gefunden._"), was zuvor in den Beta-Versionen noch klappte. Es spielt dabei auch keine Rolle, ob man in der Serverkonfiguration des Contao Managers "_WebhostOne GmbH_" auswählt oder den Pfad zur PHP Binary manuell festlegt (`/usr/bin/php` oder `/usr/bin/php71` oder `/usr/bin/php72` - "_This path does not contain a valid PHP binary._"). Auf der Konsole kann die PHP CLI Binary hingegen problemlos über die genannten Pfade aufgerufen werden:
```console
$ php -v
PHP 7.2.4 (cli) (built: Apr 23 2018 14:24:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.1.1, Copyright (c) 2002-2017, by ionCube Ltd.

$ /usr/bin/php -v
PHP 7.2.4 (cli) (built: Apr 23 2018 14:24:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.1.1, Copyright (c) 2002-2017, by ionCube Ltd.

```

Laut PHP-Info und Contao Check ist die PHP-Funktion `proc_open()` vorhanden:
```console
$ php -i | grep disable_functions
disable_functions => no value => no value
```
![proc_open](https://user-images.githubusercontent.com/1218766/41435260-89be3e7e-701e-11e8-86fa-5acf9092d8df.jpg)

```console
$ php web/contao-manager.phar.php test
{"version":"7.2.4","version_id":70204,"sapi":"cli"}
```

**Comment by xchs** [comment]
Was ich zwischenzeitlich herausgefunden habe: Das PHP Binary wurde in der **Contao Manager v1.0.0-beta10** noch korrekt erkannt, in der **Contao Manager v1.0.0-beta16** jedoch bereits nicht mehr. Offenbar hat es also in einer der Beta-Versionen dazwischen irgendwann eine Änderung gegeben, sodass die PHP Binary nicht mehr gefunden wird.

Beim Aufruf der Contao Manager v1.0.0-beta10 wird jedenfalls

```json
{
    "php_cli": "\/usr\/bin\/php72",
    "php_can_fork": false,
    "php_force_background": false
}
```
in die `manager.json` geschrieben.

**Comment by xchs** [comment]
😄 Ja, das ist mir schon klar. Ich wollte das hier nur noch ergänzend anführen, da ich ja wusste, dass es in einer dieser Beta-Versionen seinerzeit noch problemlos funktioniert hatte. Daher habe ich mir aus den Backups des Webspaces die entsprechenden älteren Beta-Versionen des Contao Manager geholt und mit diesen getestet. Und tatsächlich wurde – wie schon oben ausgeführt – in der Beta10 die PHP-Binary offenbar noch korrekt detektiert, während dies in den Folgeversionen anscheinend nicht mehr klappte.

**Comment by lebleucleu** [comment]
Im Webpaket "Single App" mit 256 MB RAM stoppte bei einer aktuellen Installation der Contao-Manager 1.0.4 die Systemprüfung beim zweiten Punkt "Serverkonfiguration" ebenfalls mit der Meldung: _"Es wurde kein valides PHP Programm auf dem Server gefunden."_ Bei manuellem Eintrag des Pfades zur PHP-Binary (/usr/bin/php72) kam die Fehlermeldung _"This path does not contain a valid PHP binary."_
In einem identischen Webpaket - allerdings auf einem anderen WebhostOne-Server - funktionierte die Installation via Contao-Manager hingegen.

Vom WhO-Support, den ich kontaktierte, wurde im Adminpanel unter "Server" die Funktion **"System wieder herstellen"** ausgeführt. Danach lief auch dort die Contao-Manager-Systemprüfung reibungslos. Woran es genau gelegen hat, wusste er leider nicht; er vermutete aber, dass die Apache Konfiguration nicht korrekt auf dem Account hinterlegt war.
Gruß, Klaus

**Comment by xchs** [comment]
Kurze Rückmeldung auch von mir: Nach Rücksprache mit dem Support von WebhostOne, konnte die Ursache des Problems nun identifiziert werden. Der Pfad `/usr/bin/php` verwies offenbar auf diesem Host nicht auf die korrekte PHP-Version, wodurch der CM die PHP Binary nicht finden konnte. Der Fehler wurde inzwischen korrigiert. Die Systemprüfung des Contao Managers läuft wieder ordnungsgemäß durch.

@aschempp Ich denke, Du kannst das Ticket nun wieder schließen. Sorry für die Umstände und danke für die Lösungsansätze.
