### ISSUE TITLE
Incompatibility of Contao 4.5.7 and Symfony 3.4.7/3.4.8+

### ISSUE THREAD

**Issue by Xendiadyon** [contao/contao-manager#251]
I have problems installing Contao 4.5.7.
```
Chained exception: An error occurred while executing the "contao:install-web-dir" command: PHP Warning:  Module 'intl' already loaded in Unknown on line 0

In ArrayNode.php line 319:
                                                 
  Unrecognized option "security" under "contao"  
```

(the doubly loaded intl module is due to our webserver settings, this has nothing to do with this issue)

![image](https://user-images.githubusercontent.com/2657385/38487210-b9e0df44-3bdf-11e8-9c31-b519119f7f6d.png)

In composer.json:
```
    "conflict": {
        "contao/core-bundle": "<4.4.1",
        "symfony/finder": "^3.4.7|4.0.7"
    },
```
https://github.com/contao/manager-bundle/issues/61

If I allow symfony 3.4.8, this issue remains.

I will make further research on this issue.

**Comment by Xendiadyon** [comment]
Using
  "minimum-stability": "dev"
does not help.

In a fresh installation, I have no problems with PHP 7.2, Contao 4.5.7 and Symfony 3.4.8.

But the update from Contao 4.4.17 I can't get to work.

**Comment by Xendiadyon** [comment]
The app/config/config.yml is the issue:

```
# Contao configuration
contao:
    # Required parameters
    prepend_locale: false # "%prepend_locale%"

    # Optional parameters
    web_dir:              "%kernel.project_dir%/web"
    encryption_key:       "%kernel.secret%"
    url_suffix:           ""
    upload_path:          files
    csrf_token_name:      contao_csrf_token
    pretty_error_screens: true
    error_level:          8183 # E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_USER_DEPRECATED
    image:
        bypass_cache:     false
        target_dir:       "%kernel.project_dir%/assets/images"
        valid_extensions: ['jpg', 'jpeg', 'gif', 'png', 'tif', 'tiff', 'bmp', 'svg', 'svgz']
        imagine_options:
            jpeg_quality: 88
            interlace:    plane
    security:
        disable_ip_check: false
```

The security -> disable_ip_check:false does not exist anymore for Contao 4.5.
When deleting this, everything works fine.

Thank you.

**Comment by bytehead** [comment]
This is exactly what the error message tries to tell you: `Unrecognized option "security" under "contao"`.

**Comment by aschempp** [comment]
This is not a problem of the Contao Manager (our Composer UI) but of the application itself or your configuration. I'm therefore closing the issue here.
