### ISSUE TITLE
Contao Manager 500 auf Strato

### ISSUE THREAD

**Issue by Fruchuxs** [contao/contao-manager#255]
Hallo,

ich bekomme auf einem Strato Webspace die folgende Fehlermeldung:

> ERROR 500 Unknown installation status
> Some files were found on your server but no known Contao version could be detected.
> You must either manually repair your application or remove the following files and folders to install Contao:
> 
> - install-5ad10dbed0527

Nachdem es ca. eine Stunde gedauert hat bis ich den Ordner entfernt habe und nun wiederholt dieser Fehler auftritt, wüsste ich gerne, wie ich das Problem beheben bzw. an weitere Informationen komme.

PHP 7.2
Nachtrag: Umgestellt auf PHP 7.1 - selbes Problem. Auf 7.0 kann ich nicht gehen, da dort wohl der intl Support fehlt.
Danke.

**Comment by aschempp** [comment]
Der Ordner wird ja durch eine (unvollständige) Installation angelegt, relevant wäre der Fehler welcher beim Installieren auftritt.

**Comment by Fruchuxs** [comment]
Weder sehe, noch bekomme ich einen Fehler. Wenn das Log irgendwo gespeichert wird, habe ich es nicht gefunden.

**Comment by Fruchuxs** [comment]
Erneuter Versuch. Keine Fehler oder ähnliches, außer der Text vom Manager. Zur wirklichen Contao-Installation kommt es gar nicht erst. Mich würde auch sehr brennend interessieren, an was er sich stört und was genau das Problem ist.

**Comment by xchs** [comment]
Versuche es mal so wie hier beschrieben: https://community.contao.org/de/showthread.php?70652-Installation-von-Contao-4-5-Managed-Edition-bei-STRATO&p=471985&viewfull=1#post471985

**Comment by Fruchuxs** [comment]
Danke für den Link, aber den hint mit dem tmp-Verzeichnis hättest Du mir auch ohne das ganze Tutorial geben können. ;p
Aber egal, vielen Dank, das löste das Problem und die Installation ging danach ohne Probleme.

**Comment by mirkosmos** [comment]
Hallo, ich habe das gleiche Problem wie oben beschrieben auf "STRATO PowerWeb Plus", sodass der "ERROR 500" mit dem Hinweis auf den Ordner "install-xxxxXxxxxXxxx" auftritt, nachdem ich die "contao-manager.phar.php" ausgeführt habe.

@Fruchuxs: wie hast Du es denn jetzt genau gelöst? Kannst Du es bitte einmal detailliert beschreiben? Meine Versuche, z. B. mit dem Anlegen eines "tmp"-Ordners und wiederholtem Aufrufen des Managers schlugen bisher fehl. Oder muss ich den (für mich recht schwierigen) Weg mittels Composer gehen?

Danke schonmal!

**Comment by Fruchuxs** [comment]
Ich habe den Weg über Composer genommen. 

`/opt/RZphp72/bin/php-cli composer.phar create-project contao/managed-edition`


In vendor/bin/contao-console dann:
```
putenv('TMP=/home/strato/www/ex/www.example.com/htdocs/example.com/system/tmp'); 
putenv('TEMP=/home/strato/www/ex/www.example.com/htdocs/example.com/system/tmp'); 
putenv('TMPDIR=/home/strato/www/ex/www.example.com/htdocs/example.com/system/tmp');
```

Wobei die Temp-Pfade bei mir nicht gepasst haben, per `pwd` habe ich mir den aktuellen Pfad per SSH ausgegeben und ein eigenes Temp-Verzeichnis angelegt.

Dann erneut den unten stehenden Befehl erneut ausgeführt:
`/opt/RZphp72/bin/php-cli composer.phar update -o`

Den Manager habe ich ab dann prinzipiell ignoriert. Dieser scheint ein composer-update zu machen nachdem man Pakete ausgewählt hat, was dann in einer out-of-memory-Exception endet. Update frisst viel zu viel RAM bei Composer, weswegen der Manager defakto auf kleineren Webspaces nutzlos ist. Contao Module kannst Du einfach über composer install installieren und dann vom  `vendor` ins `/system/modules`-Ordner kopieren (wobei hier die Plugin-Datei für die managed Version reicht).

Bin mir nicht sicher, ob die Reihenfogle so richtig ist. Hatte mir vorgenommen nicht mehr Contao einzusetzen sondern werde in neuen Projekten auf Neos setzen. Wollte damals schon wechseln, weil Contao sich in bestimmten Dingen konzeptionell einfach nicht vorwärts bewegt wie andere CMS, aber Neos war mir da noch "zu jung". Einen Manager der ein install-Tool installiert was dann wiederum Contao installiert, ist mir einfach etwas zu bunt.

**Comment by mirkosmos** [comment]
Vielen Dank für die Hinweise! 

Mir war das jetzt zu kompliziert, sodass ich erstmal alles wieder vom Server gelöscht habe. Folgende Herangehensweise ohne Manager und/oder Composer führte dann recht schnell zum Erfolg.

**Installation Contao 4.4.18 (LTS ) auf STRATO PowerWeb Plus:**
1. Download und Entzippen von "contao-4.4.18.zip"
2. Übertragen aller Ordner und Dateien ("app", "assets", "var" usw.) per FTP auf den Server in einen separaten Ordner (z. B. "www.domainname.de/installation/")
3. Einrichten einer Weiterleitung der Domain auf "/installation/web/"
4. Install-Tool im Browser aufrufen: "www.domainname.de/app.php/contao/install"
5. Bestimmungen bestätigen und neues Passwort für Install-Tool vergeben
6. Datenbank eingeben (bei Host: "rdbms.strato.de" statt "localhost", Portnummer bleibt)
7. Datenbank aktualisieren
8. Administratorkonto anlegen und Backend aufrufen

Fertig :-)

**Comment by xchs** [comment]
FYI: Sobald Du aber Pakete/Erweiterungen installieren oder das System updaten möchtest, stehst Du ohne Composer wieder vor dem gleichen Problem.

**Comment by mirkosmos** [comment]
@xchs: Gut zu wissen, also führt irgendwann eh kein Weg am Composer vorbei. Ich scheu mich auch nicht wirklich davor und hab auch schon öfters mit "PuTTY" z. B. den Cache geleert :-) ... aber wenn es nicht unbedingt sein muss, geh ich lieber den "für mich einfacheren" Weg. Vielleicht gibt es ja diese Funktionen irgendwann auch mal im Backend von Contao?!

**Comment by Fruchuxs** [comment]
Sicherlich nicht, dafür haben sie ja den Contao Manager geschaffen. Der ist sozusagen das Frontend für Composer.

**Comment by mirkosmos** [comment]
Ok, so langsam hab ichs. Und für alle anderen Laiendarsteller wie mich hier nochmal die Zusammenfassung:

1. Installation ohne Contao-Manager ausführen
2. Nachträgliche Installation des Contao-Managers (wie bei einer Neuinstallation)

Somit kann das "ERROR 500"-Problem umgangen werden!

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
