### ISSUE TITLE
Contao Manager auf Hosting Infomaniak (CH)

### ISSUE THREAD

**Issue by najbo** [contao/contao-manager#256]
Hallo,

Ich habe versucht, den CM auf [Infomaniak](www.infomaniak.ch) zu installieren aber ohne Erfolg und ich bin jetzt blokiert. Die 1024 MB sind leider nicht genug.

`/opt/php{major}.{minor}/bin/php: ['-d', 'memory_limit=1024M']`

Ist es bitte möglich, die Einstellung für Infomaniak auf 2048MB zu ergänzen (oder sogar auf -1) ?

Es wäre auch noch toll, wenn man im Dropbox Feld unter "Anderen Anbieter" einfach ein zweites Text Feld hätte, wo man spezifische sachen reinschreiben könnte (wie memory_limit = 2G, usw). Es gibt ja schon das Feld für die PHP CLI.

Besten Dank für alles.

![php_memory_limit](https://user-images.githubusercontent.com/18056783/39230727-d4fd7eba-4867-11e8-85f7-1ce3e1654228.png)

#209

**Comment by aschempp** [comment]
ist in der Beta18 geändert.
