### ISSUE TITLE
Contao-Manager wirft ständig Fehler bei Repository Extensions

### ISSUE THREAD

**Issue by evo-web** [contao/contao-manager#259]
Contao 4.4 LTE installiert.
Test läuft sauber durch, aber Extensions werfen immer:

Process terminated with exit code 137
Reason: Kill (terminate immediately) [SIGKILL]

**Comment by Toflar** [comment]
Nicht genug Memory für ein Update, denk ich. Nichts was wir im Moment lösen können. Ich lass es aber offen, weil wir an einer Lösung arbeiten.

**Comment by mmiat** [comment]
same problel, when i try to update a package or install a new one
as https://github.com/BugBuster1701/contao-visitors-bundle/issues/35
sometimes it works, but the 90% of cases fails

**Comment by xchs** [comment]
https://github.com/contao/contao-manager/wiki/Hetzner

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
