### ISSUE TITLE
Erweiterungen können nicht mehr installiert werden

### ISSUE THREAD

**Issue by asdfasdfasa** [contao/contao-manager#261]
Die task.json Datei habe ich bereits gelöscht ohne Ergebnis.
Es erscheint folgende Fehlermeldung:

Contao Manager 1.0.0-beta18
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/php71/usr/local/lib/php/20160303/ldap.so' - Shared object "libldap-2.4.so.2" not found, required by "ldap.so" in Unknown on line 0

**Comment by Toflar** [comment]
Das ist eine Fehlkonfiguration auf Seiten des Servers. Dein PHP will eine Extension im Pfad `/usr/php71/usr/local/lib/php/20160303/ldap.so` laden, da ist aber nix.

**Comment by asdfasdfasa** [comment]
Vielen Dank für deine Hilfe, Yanick. 
Das heisst, ich soll irgendwelche Files löschen auf dem Server oder etwas umkonfigurieren?
Bis vor kurzem hat der Contao Manager problemlos funktioniert.

**Comment by Toflar** [comment]
Weder Contao noch der Contao Manager noch sonstige PHP-Software kann funktionieren, wenn PHP selber nicht korrekt läuft. Du musst das PHP-Setup korrigieren (lassen).

**Comment by asdfasdfasa** [comment]
Seltsamerweise hatte ja alles funktioniert. Auch im Contao Backend funktioniert alles bestens. (Seitens Hoster wurde nichts geändert.)
Leider ist das SSH bei diesem Hosting-Paket nicht enthalten.


Die Antwort vom Hoster:
------------
Im Error-Log der Entwicklungsumgebung sehen wir keine Fehlermeldung.

Die folgende Fehlermelung wird nun nicht mehr erscheinen:
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/php71/usr/local/lib/php/20160303/ldap.so' - Shared object "libldap-2.4.so.2" not found, required by "ldap.so" in Unknown on line 0
——————


Die Fehlermeldung erscheint nun nicht mehr, dafür bleibt die «Lade Konsolentask…» in der Endlosschleife hängen.

**Comment by asdfasdfasa** [comment]
Hallo Yanick

Vielen Dank für deine Antwort.
Der Hoster Webstyle hat nun alles mögliche ausprobiert. (Bis hin zur Anpassung der manager.json im Contao-Mangaer.)
Leider erscheint immer noch die Fehlermeldung Konsolentask beendet.

Die Prozess Dateien im Cotnao Manager habe ich gelöscht.
PHP-Setup sollte stimmen

Hast du mir vielleicht noch einen Tipp an was es liegen könnte?



Gruss Aitana

**Comment by asdfasdfasa** [comment]
Hier die Antwort vom Hoster:

«Was wir nach zwei Stunden Analyse und Support wissen: PHP funktioniert korrekt auf dem Server weil einerseits die Webseite nicht funktionieren würde und andererseits auch andere Kunden Störungen melden würden. Das Contao funktioniert; einzig der Contao Manager funktioniert nicht.»

**Comment by aschempp** [comment]
Bitte beachten dass der Contao Manager auch PHP-Befehle auf Kommandozeile ausführt. Nur weil der Webprozess richtig funktioniert heisst das nicht dass auch die Kommandozeile richtig funktioniert. Vielleicht lässt sich dort noch ein Fehler finden und erkennen?

**Comment by asdfasdfasa** [comment]
Von Seiten Hosting Einstellungen ist leider alles korrekt. Auch der binary Pfad stimmt.
Bis vor 2 Wochen funktionierte der Contao Manager einwandfrei.

Installiert ist derzeit PHP 7.1.16
Die PHP-Erweiterungen Intl. und OpenSSL sind verfügbar.
Wenn die php.71.ini verwendet wird sind keine PHP-Funktionen eingeschränkt/deaktiviert.
Die Option allow_url_fopen  ist eingeschaltet.

Die in der Datein contao-manager/manager.json konfigurierten Pfade sind ebenfalls korrekt:

    "php_cli": "\/usr\/php71\/usr\/local\/bin\/php",
    "php_cli_arguments": [
        "-c \/home\/diemagaziner.ch <http://diemagaziner.ch/>\/conf\/php.71.ini"
    ]


Könnte es was bringen, wenn ich den CM deinstalliere und neu installiere?

Vielen Dank für die Hilfe..

**Comment by aschempp** [comment]
Eine Einstellung für `php_cli_arguments` gibt es schon seit längerer Zeit nicht mehr, woher habt ihr das?

**Comment by asdfasdfasa** [comment]
Von dem Hoster webstyle.

**Comment by asdfasdfasa** [comment]
Alles klar :-)
Es wäre natürlich toll, eine Inkompatibilität im CM zu erkennen. Oder ich sehe es zumindest nicht.

Das Konsolentask-Laden bleibt auch bei kompatiblen Erweiterungen in der Endlosschleife.
Naja, nach einem Seitenreload ist die Erweiterung zumindest vorhanden.
Auch das «Leere den Composer-Cache» wird nach 10 Minuten nicht beendet. (Der Wert für max_execution_time ist auf 120 Sekunden)
