### ISSUE TITLE
Not valid php path

### ISSUE THREAD

**Issue by martinjohannes93** [contao/contao-manager#264]
Hi @all,

I have a synology DS1515+ running with PHP 70 and Apache 2.4. I followed the instructions here:

https://community.contao.org/de/showthread.php?69696-Schritt-f%C3%BCr-Schritt-Installation-auf-einer-Synology-Diskstation

Which means, I have a domain example.tld and a vhost to /volume1/web/example.tld/web whereas /volume1/web/example.tld contains folders like contao-manager and so on. Right now, this folder is empty. I also set the allow_url_fopen to "1" and also have any extensions activated (especially the phar extension).

When I run examole.tld/contao-manager.phar.php, it checks for the PHP 70 version and detect it, but has issues to detect a server config. I choose "other" and then I have to fill in the path to the corresponding php version which is "/usr/local/bin/php70" in my situation. But the installation wizard is proclaiming about an ivalid binary path. Please fix this bug ;) When I try "/bin/php" it says, that the Webserver and PHP version are mismatching. I'm also running php5.6 on my NAS. So I also tried to change the vhost settings to php5.6 - then, this error doesn't occur, but in other steps of the wizard, I get errors because of an outdated and deprecated php version. Neither php5.6 nor php7.0 get it through

**Comment by aschempp** [comment]
If the binary path `/usr/local/bin/php70` is not accepted, it means the PHP process the Contao Manager is running on cannot execute the binary, or it does not get expected output. Make sure the file is executable and accessible by the webserver user. You can also debug the output with:

`/usr/local/bin/php70 /path/to/contao-manager.phar.php test`

**Comment by martinjohannes93** [comment]
Thanks dir this hint, but I already changed the permissions. The http-user
group should have access. Maybe Synology changed the PHP 7.0 version which
ist why the output mismatches. I'll try to install a raw and unmodified 7.0
version later.

Andreas Schempp <notifications@github.com> schrieb am Fr., 25. Mai 2018,
08:05:
