### ISSUE TITLE
Korrekter PHP Binary Pfad wird nicht erkannt

### ISSUE THREAD

**Issue by webhebamme** [contao/contao-manager#266]
Hallo,
ich möchte gerne den Contao-Manger testen. Trotz korrekter Pfadangabe bekomme ich allerdings die Meldung : This path does not contain a valid PHP binary. 
Dazu bin ich wie folgt vorgegangen:
Verzeichnis /web angelegt sowie Rechte überprüft. Domain rootet dort hin
 [webhebamme.de]
 contao-manager.phar binär in Verzeichnis /web hochgeladen und umbenannt in
 contao-manager.phar.php
 php 7 ini angepasst wie folgt:
 memory_limit = 2G
 max_execution_time = 900
 max_input_time = 2000
 memory_limit = 2G
Aufruf in der Browserzeile, Account kreiiert. Serverkonfiguration: Andere ausgewählt.
Pfadangabe: /opt/php-7.0/bin/php bzw. /opt/php-7.0/bin/php-cgi ausprobiert.

Heute morgen alles auf Anfang und es mit einer Subdomain nochmal probiert mit dem gleichen Ergebniss wie gestern. Muss ich evt. noch was in der PHP ini anpassen ?

**Comment by aschempp** [comment]
Was ergibt folgender Aufruf bei dir auf der Kommandozeile?

```
/opt/php-7.0/bin/php /path/to/web/contao-manager.phar.php test
```

**Comment by webhebamme** [comment]
Could not open input file:

**Comment by xchs** [comment]
Wo hast Du denn das Kommando ausgeführt? Hast Du `/path/to/` entsprechend ersetzt?

**Comment by webhebamme** [comment]
Habe ich gestern Abend gemacht. Der Tip wurde mir im Forum gegeben aber mom ich mache es nochmal

**Comment by webhebamme** [comment]
Hm komme ich momentan nicht dran. Bekomme ein Timeout beim Verbinden. Also mein Befehl lautete
/opt/php-7.0/bin/php /contao4.4/web/contao-manager.phar.php test

**Comment by xchs** [comment]
Wahrscheinlich müsste das Kommando (bei Dir) so lauten:
```console
/opt/php-7.0/bin/php contao4.4/web/contao-manager.phar.php test
```
Du könntest aber auch einfach per `cd` in das `web/` Unterverzeichnis wechseln und dort dann
```console
/opt/php-7.0/bin/php contao-manager.phar.php test
```
ausführen.

**Comment by webhebamme** [comment]
ah ja da war was...
Nee kommt wieder: Could not open input file: contao4.4/web/contao-manager.phar.php

**Comment by xchs** [comment]
Könntest Du vielleicht die Konsolenausgabe komplett posten?

**Comment by webhebamme** [comment]
`/opt/php-7.0/bin/php /contao4.4/web/contao-manager.phar.php test
Could not open input file: /contao4.4/web/contao-manager.phar.php
`

**Comment by xchs** [comment]
Du hast wieder das "falsche" Kommando ausgeführt! Bitte mal so versuchen, wie ich es oben gepostet hatte:
```console
/opt/php-7.0/bin/php contao4.4/web/contao-manager.phar.php test
```
Ob das nun aber richtig oder falsch ist, hängt klarerweise davon ab, wo Du das Kommando ausführst.

**Comment by webhebamme** [comment]
Okay jetzt bin ich raus... ich bin im root-Verzeichnis
`pwd`
`ls -al` zeigt mir an welche dateien drin sind, wo hab ich den jetzt den Hänger, es wird mir langsam peinlich. Ich seh noch nicht einmal den Unterschied zwischen den beiden Komandos. *schäm*

**Comment by xchs** [comment]
Bitte melde Dich im Forum! Dort können wir das gerne weiterdiskutieren. Hier im Ticket können wir nicht auch noch einen Crashkurs für die Benutzung einer Linux-Konsole geben.

**Comment by webhebamme** [comment]
{"version":"7.0.7","version_id":70007,"sapi":"cli"}root@1a-8767:~#

**Comment by Toflar** [comment]
Bitte wiedereröffnen falls es sich um einen Bug handelt. Support ansonsten wie von @xchs bereits erwähnt im Forum.
