### ISSUE TITLE
contao-manager 1.0.0 problem

### ISSUE THREAD

**Issue by SK-Dyn** [contao/contao-manager#267]
Hello, the new contao-manager 1.0.0 gives me the error message:

"The Contao manager could not start a console task!

The execution of the background task failed.
If this happens again, the Contao Manager may not support your server. "

With contao-manager 1.0.0 beta18 I have already installed a contao homepage 4.4.18 on exactly the same server. What can I do now or can you help me?

Best regards, Heinz Klümper

**Comment by tacuarimedia** [comment]
Hey, I have the same problem. I'm trying to install Contao 4.5 with Contao Manager 1.0.0 on my local mamp server. 
PHP 7.1.12

**Comment by aschempp** [comment]
Can you please check the network requests in your browser console and check for anything strange? What happens if you reload the page, does the task continue or is it just gone?

**Comment by aschempp** [comment]
Changed in d096b49fa3563a0dd476b3fed21571f53a95707f to wait 75 seconds (!!) for task output, this should be enough for even the slowest machines 😄
