### ISSUE TITLE
CM 1.0.0 Systemtest: Contao-Version nicht erkannt

### ISSUE THREAD

**Issue by rustykowski** [contao/contao-manager#269]
Ich erhalte folgenden Fehler im Overlay:
ERROR 500 The Contao version could not be determined
The console returned unexpected content when asked for the Contao version. Please check the output for more information:

PHP Warning: Module 'intl' already loaded in Unknown on line 0
4.4.18

Unter dem Overlay noch mal schön auf deutsch:
Contao-Installation
Die Prüfung ist aufgrund einer unerwarteten Server-Antwort fehlgeschlagen.

Die PHP-Warnung blockiert somit den Start des Managers. Natürlich liegt die Ursache in der noch suboptimalen PHP-Konfiguration (Domainfactory). Aber wäre es nicht denkbar, dass man PHP-Warnungen überspringen kann?

**Comment by Toflar** [comment]
Duplicate of https://github.com/contao/contao-manager/issues/201
