### ISSUE TITLE
Thank you for the composer-cloud!

### ISSUE THREAD

**Issue by rustykowski** [contao/contao-manager#270]
![giphy](https://user-images.githubusercontent.com/1775048/41114313-5e184e26-6a84-11e8-9e7a-528336a119b5.gif)

**Comment by Toflar** [comment]
![200w](https://user-images.githubusercontent.com/481937/41114504-ec97c622-6a84-11e8-8cce-9fd6902679f1.gif)
🎉 🎉 🎉
