### ISSUE TITLE
Firewall Daten für die Cloud

### ISSUE THREAD

**Issue by BugBuster1701** [contao/contao-manager#271]
Wie sind die Daten, wohin der Contao Manager zur Cloud Connected?

Im Forum gibt es eine Nachricht mit einer HttpException Access Denied, das klingt doch danach, oder?

**Comment by Toflar** [comment]
Mehr Details bitte :)

**Comment by xchs** [comment]
@Toflar https://community.contao.org/de/showthread.php?70987-Contao-Manager-1-0-0-jetzt-mit-composer-cloud&p=474911&viewfull=1#post474911

**Comment by Toflar** [comment]
Sieht nicht nach Cloud Problem aus, eher nach einem Problem im Manager. /cc @aschempp

**Comment by aschempp** [comment]
Möglicherweise funktioniert die TLS-Verschlüsselung nicht weil auf dem entsprechenden Server ein Root-Zertifikat für Let'sEncrypt fehlt?

**Comment by BugBuster1701** [comment]
Beim Forum Nutzer geht es plötzlich ohne das was geändert wurde.

**Comment by Toflar** [comment]
Oder der Server wurde aktualisiert :D
