### ISSUE TITLE
CM 1.3.1: it´s not possible to delete any contao bundles

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#272]
it´s not possible to delete any contao bundles:

contao/calendar-bundle
contao/comments-bundle
contao/faq-bundle
contao/news-bundle
contao/newsletter-bundle

No response when you click on red button "Remove".

**Comment by Toflar** [comment]
Can you check your JavaScript console and tell us if there are any errors there?

**Comment by zonky2** [comment]
no error or warnungs - uBlock during test disabled...

**Comment by fkaminski** [comment]
Maybe duplicate with #268

**Comment by zonky2** [comment]
I don't think so.

**Comment by zonky2** [comment]
If I comment out "display: none;" the button works

`<div tabindex="-1" class="button-group__group" style="/*! display: none; */">`

I test it wit FF 60 an Chrome 66 and Win 7

**Comment by fkaminski** [comment]
Dito - seems to be just a frontend issue ...

**Comment by aschempp** [comment]
Duplicate of https://github.com/contao/contao-manager/issues/268

**Comment by zonky2** [comment]
wie in https://github.com/contao/contao-manager/issues/272#issuecomment-395965696 geschrieben, wenn man den Button das `display: none?` raus nimmt, gehts
