### ISSUE TITLE
composer cloud with repositories type path

### ISSUE THREAD

**Issue by arboc** [contao/contao-manager#274]
The new contao manager 1.0.0 uses composer cloud to resolve dependencies but this do not work with repositorues with type path.

For developing and maintaining extensions, we are using repositories with type path. This extensions are symlinked to a path, where the development is dones. 

Unfortunately the new contao manager hangs resolving the dependencies for this extensions.

Is there a way
- to permanently mark specific extension to not be updated?
- to disable the resolving over composer cloud?
- to cancel the resolving process (the button is disabled)?

**Comment by Toflar** [comment]
> to disable the resolving over composer cloud?

Yes, this is the way to go. If you want local repositories you cannot rely on the cloud. You can disable it in the hosting configuration of the manager.

**Comment by arboc** [comment]
can you explain, how to disable in the configuration?
Is there a documentaion of the configuration?

**Comment by Toflar** [comment]
![screen shot 2018-06-09 at 11 44 57](https://user-images.githubusercontent.com/481937/41190202-9dedc880-6bda-11e8-9df7-b3aeac4bb742.png)

**Comment by arboc** [comment]
🙏 thanks

**Comment by Toflar** [comment]
👍 😄
