### ISSUE TITLE
Konsolentask Contao Manger

### ISSUE THREAD

**Issue by wian-dd** [contao/contao-manager#276]
Der Contao Manager konnte einen Konsolentask nicht starten!
Die Ausführung des Hintergrundtasks ist fehlgeschlagen.
Sollte dies nochmals passieren, unterstützt der Contao Manager Ihren Server ggf. nicht.

Was muss man den tun, damit der Contao Manager den Server unterstützt?

**Comment by mlwebworker** [comment]
Dieses Problem trat ja bei unseren Tests bei mir auch sporadisch auf und wir konnten es deshalb bis jetzt nicht näher untersuchen. Ich habe jetzt aus der Contao Academy jemanden mit diesem Problem. Dort scheint es nahezu immer aufzutreten (Mac mit System 10.10.5 und MAMP Pro 4.5). Im Forum gab es auch ein Paar Threads mit Contao Manager 1.0 und Meldung "Der Contao Mager konnte einen Konsolentask nicht starten! 
Die Ausführung des Hinfergrundtasks ist fehlgeschlagen. 
Sollte dies nochmals passieren, unterstützt der Conato Manager Ihren Server ggf. nicht. "
https://community.contao.org/de/showthread.php?67359-Contao-Manager-MAMP-Pro-Mac-OS-Konsolentask-nicht-starten&p=475020&viewfull=1#post475020
https://community.contao.org/de/showthread.php?69868-Paketmanager-funktioniert-nicht-(4-4-14)-Keine-Reaktion-in-der-Konsole-(Hostpoint)&p=475041&viewfull=1#post475041
Scheint also kein Einzelfall zu sein.

**Comment by swinde** [comment]
Bei mir auf einem Server bei DF das gleiche Problem. Entstanden nach dem erfolglosem Versuch Contao 4.4.x zu installieren.

Steffen Winde

**Comment by torschiff** [comment]
Ich habe das gleiche Problem beim Mac (System 10.12.6 und MAMP Pro 4.5) und dem Contao Manager 1.01.
Bis vor einer Woche lief alles, dann kam ein Security Update auf 10.12.6 und das Update auf Mamp 4.5, seitdem geht nichts mehr. Erst hatte ich zu wenig Memory (Original waren es 128), nachdem ich diesen auf 256 gesetzt hatte kam der Fehler nicht mehr, dafür kommt nun diese

[Wed Jun 20 20:20:42 2018] [error] [client ::1] Directory index forbidden by Options directive: /Applications/MAMP/htdocs/contao/web/ 

Ich habe bei Mamp die "alte Version 4.4.1" bekommen, gleicher Fehler. 

Besteht die Möglichkeit Contao mit dem CM 1.0 zu installieren und das Update auf 1.01 zu umgehen?

Dirk Osterkamp

**Comment by aschempp** [comment]
@torschiff beide deine Meldungen scheinen nichts mit dem Originalfehler dieses Issues zu tun zu haben? Eine alte Version des Managers wird daran auch nichts ändern, es scheint dein Server funktioniert nicht richtig? Für solche Fragen wende dich bitte an's Contao Community Forum (https://community.contao.org)

**Comment by aschempp** [comment]
Duplicate of #267
