### ISSUE TITLE
Contao Manager 1.0.0 stable

### ISSUE THREAD

**Issue by standing-bear** [contao/contao-manager#280]
Es keimte ja ein kleiner Hoffnungsfunke auf, als die Version des Managers plötzlich von beta auf stable gesetzt wurde.

Habe ich natürlich direkt getestet. Und siehe da: Es geht weniger als mit der Beta-Version.

Getestet habe ich auf einem Hetzner Server Level 19, also nicht gerade ein kleines Päckchen. Zunächst ein Test über die Cloud. Nach sage und schreibe 46 Minuten dann die gleiche Fehlermeldung wie immer ... process killed etc. pp.

Dann habe ich es noch einmal nach der alten Methode probiert ohne Cloud, denn das ging bei Hetzner bisher schon mit der Beta-Version. Letztlich funktionierten ja nur die Updates bzw. die Installationen von Extensions nicht. Hier kam die Fehlermeldung dann sogar schon nach ca. 3 Minuten.

Insgesamt kann ich also sagen: Es geht weniger als vorher. Denn nun kann ich Contao über den Manager gar nicht mehr installieren.

Stable hin oder her ... so kann man nicht arbeiten. Wie gut, dass ich mich in der langen Zwischenzeit in verschiedene andere CMS eingearbeitet habe und nur noch funktionierende alte Contao-Systeme pflegen muss ;-)

Ich frage mich nach wie vor, warum hier ein sehr gut funktionierendes System vollkommen ohne Not kaputtprogrammiert wurde?!

**Comment by Toflar** [comment]
Magst du mal deine Kontaktdaten beim Github-Profil hinterlegen? Wir sind ja alles Menschen auf dieser Plattform und versuchen gemeinsam was zu erreichen. Da passen anonyme Profile und sinnlose Rants so gar nicht ins Konzept. Ich ruf dich dann gerne mal an und wir können über deine Probleme reden.

**Comment by fkaminski** [comment]
Ich bin zwar nicht bei Hetzner aber laut folgenden Foren Beiträgen funktioniert es u.a unter "Level 4 / Level 19" siehe: [Beitrag](https://community.contao.org/de/showthread.php?70974-Hilfe-Installation-bei-Hetzner-Level-19&p=474975&viewfull=1#post474975)

Mit dem CM 1.0.0 habe ich u.a einwandfrei getestet hostingwerk.de (ging schon immer), 1&1 und lokal Windows7/Xampp ...

**Comment by frontendschlampe** [comment]
Hallo @standing-bear - ich bin mir noch nicht sicher, ob du Langeweile hast oder einfach nur Unruhe stiften möchtest. Wenn du irgendwelche Probleme hast, dann schreib bitte ein qualifiziertes Ticket.

Wenn Du Contao nicht mehr nutzen kannst oder möchtest, dann nutze es nicht und hör bitte auf, diese unqualifizierten Tickets zu schreiben.

Wenn du wirklich und ehrlich daran interessiert bist, Contao weiterhin zu nutzen und qualifizierte Tickets zu schreiben, dann steht Dir das ebenfalls frei und es wird Dir sicherlich geholfen.

Aber das, was du hier machst, ist unverschämt.

In unseren Tests konnten wir mit Hetzner Level 19 keine Probleme feststellen (das kann Dir @mlwebworker so auch bestätigen), von daher scheint da irgendwas anderes bei Dir nicht zu passen.
