### ISSUE TITLE
Contao Manager Endlosschleife Hetzner vs Pakete Installieren 

### ISSUE THREAD

**Issue by Heiko-fl** [contao/contao-manager#282]
Hallo, 

ich habe den neuen Contao manager Version 1.0 installiert.  nun möchte ich ja gerne Pakete Installieren doch leider geht die Installation in die Endlosschleife. 
Ich benutze Contao 4.4 mit Hetzner Hoster zusammen ... 

mfg Heiko

**Comment by fkaminski** [comment]
Laut folgenden Foren Beiträgen funktioniert es u.a unter "Level 4 / Level 19" siehe: [Beitrag](https://community.contao.org/de/showthread.php?70974-Hilfe-Installation-bei-Hetzner-Level-19&p=474975&viewfull=1#post474975)

**Comment by Heiko-fl** [comment]
Contao 4.4 ist installiert, es geht nur um die Pakete wie Templates usw... zu den Hetzner einstellungen komme ich nur bedingt, da ich nicht der direkte Kunde bin . aber am Dealer bin ich schon bei ... denke der wird sich das mal anschauen ...

**Comment by Heiko-fl** [comment]
Wir haben bei Hetzner folgendes geändert und schon lief es 

allow_url_fopen ist aktiviert (war auch schon)
memory_limit hab ich auf 192MB und max_execution_time auf 90s gesetzt

Dabei handelt es sich bei mir um keinen´Level Server, sondern ein eigenen Server.

**Comment by aschempp** [comment]
was bedeutet für dich "Endlosschleife" ?

**Comment by Toflar** [comment]
Also wäre das Ticket ein Duplikat von https://github.com/contao/contao-manager/issues/279, verstehe ich das richtig?

**Comment by ringothiele** [comment]
Ich will da jetzt nicht für den Threaderöffner sprechen ... aber ja, das was ich egschrieben hab, wäre ein Duplikat zu 279.

**Comment by Toflar** [comment]
Gut, dann schliesse ich das mal, weil beim anderen habe ich Daten um das Problem womöglich nachstellen zu können. Danke für die Antwort :)
