### ISSUE TITLE
Installation auf altem All-Inkl Privat Paket erzeugt Error 500

### ISSUE THREAD

**Issue by Floxn** [contao/contao-manager#283]
Der CM läuft auf einem "alten" All-Inkl Privat Paket nicht und landet in einem Error 500.
Auf dem Server läuft PHP 5.5.38 auf der Domain ist PHP 7.1CLI eingestellt.

Da auf dem Server nichts läuft und nur zum Testen da ist kann ich damit etwas rumspielen falls bedarf ist. Ansonsten werde ich ein mein Paket auf einen neuen Server bei All-Inkl transferieren lassen. Das sollte das Problem dann beheben.

Hier noch der Screen dazu:
![bildschirmfoto-2018-06-13-um-09 27 12](https://user-images.githubusercontent.com/15326334/41337008-41595e4c-6eee-11e8-86e8-4cc7696519d0.jpg)

**Comment by Floxn** [comment]
Ist eine komplett frische "Installation". Installieren wollte ich die Contao 4.4.
Klar mit PHP 5.5.38 läuft Contao 4 nicht. Deshalb hab ich auf der Domain ja PHP 7.1CGI eingestellt.

**Comment by xchs** [comment]
> Deshalb hab ich auf der Domain ja PHP 7.1CGI eingestellt.

Hast Du das in den Domaineinstellungen im KAS gemacht oder via `AddHandler` Direktive in der `.htaccess`? Letzteres betrifft nämlich auf jeden Fall nur den Webprozess und nicht Prozesse, die via CLI ausgeführt werden. Es könnte also sein, dass solcherart Prozessen weiterhin nur PHP 5.5.38 auf der Kommandozeile zur Verfügung steht.

Ansonsten könntest Du auch mal versuchen, das PHP Memory Limit via `.htaccess` entsprechend hochzusetzen:
```
php_value memory_limit 256M
```

**Comment by Floxn** [comment]
Die Domaineinstellung hab ich über das KAS gemacht und ned als `AddHandler`.
Mit `php_value memory_limit 256M` läuft der CM wenigstens einmal durch. 

Dadurch das man nun aber eine `.htaccess` von Hand im `/web` angelegt hat funktioniert der Installationsaufruf nicht mehr. Die `.htaccess` von Contao wird dann wohl nicht mehr erstellt, bzw. die vorhandene wird nicht überschrieben. 
Man muss dann die angelegt `.htaccess` wieder löschen und aus dem CM das Core-Bundle aktualisieren. Danach kann die Installation wieder aufgerufen werden. Natürlich dann wieder in dern "neuen" `.htaccess` wieder `php_value memory_limit 256M` hinzufügen.

Ich denke bevor man sich damit rum plagt sollte man sein altes All-Inkl Paket auf einen aktuellen Server intern transferieren lassen. Ist ja kostenlos und passiert über Nacht. 

Ich konnte nebenher das selbe auf noch einen "alten" All-Inkl Paket testen und habe jeweils das selbe Ergebnis gehabt. Das war sogar eine Stufe vom Paket her größer. PrivatPlus war das nun.

Evtl. das irgendwie bei der Hosting-Auswahl im CM bei All-Inkl vermerken?

Grüße Flo

**Comment by Floxn** [comment]
memory_limit unterschiede voreingestellt:
"alte" Hostingpakete: `128M`
"neue" Hostingpakete: `256M`

**Comment by Floxn** [comment]
Das musst ich wohl zurück nehmen.
Ich habe nun ein Umzug machen lassen. Das voreingestellte `memory_limit` ist bei dem Paket All-Inkl Privat doch geblieben.
Also muss man den Weg über die `.htaccess` trotzdem gehen
