### ISSUE TITLE
System Check hangs (Bitte warten, Ihr Server wird überprüft …)

### ISSUE THREAD

**Issue by marebe1602** [contao/contao-manager#284]
Version: 1.0.0-beta19
no changes were made to the system since last successful manager call.
After waiting 15 minutes there's still a spinning spinner and nothing happens.

running on plesk server with PHP 7.1.18

**Comment by xchs** [comment]
You may want to (manually) download the stable release of the Contao Manager: https://download.contao.org/contao-manager/stable/contao-manager.phar

**Comment by marebe1602** [comment]
manually updated to current stable build 1.0.0.
Now it says, that the console task could not be started and maybe the manager does not support my server (but the older betas did support the server)
After closing the message box, theres the system check spinner endlessly spinning.

I tried opening manager twice and the message was the same both times.
Does the "stable" manager version support less server configurations than older manager versions?

**Comment by aschempp** [comment]
I'm closing this old issue. Feel free to reopen if the problem still exists.
