### ISSUE TITLE
Pakete aktualisieren hängt: Resolving dependencies using Composer Cloud

### ISSUE THREAD

**Issue by MaCo7** [contao/contao-manager#285]
Seit über 2000 s hängt der CM bei der "Resolving dependencies using Composer Cloud". Reload des Browsers führt wieder auf den "Updating Packages" Screen. Ich komme also aus dieser Schleife nicht mehr raus. Was ist zu tun um den Prozess abzubrechen, bzw. neu zu starten? 
Hosting: Mittwald, vServer, Job ID 5b212418ae9533.51467219 is running for 2336 seconds

Viele Grüße+ Dank, M

**Comment by aschempp** [comment]
Duplicate of #279
