### ISSUE TITLE
Fehlermeldung präzisieren

### ISSUE THREAD

**Issue by bekanntmacher** [contao/contao-manager#288]
<img width="719" alt="contao_manager_1_0_1" src="https://user-images.githubusercontent.com/1622464/41577673-824a70f4-738e-11e8-89f9-93fef04def5c.png">

Ist beides nicht der Fall. Was ist es dann?... Ich schätze der Server ist nicht erreichbar, weiss es aber nicht. Ev. könnte hier die Ursache genauer ermittelt werden und/oder Fehlermeldung präzisiert werden.

**Comment by chiron501** [comment]
Hallo zusammen,
habe gleiches Problem nach dem Update des Contao-Manager auf 1.0.1.

**Comment by thjapan** [comment]
Hallo,
gleiches Problem bei Netzone (PHP 7.1) und All-Inkl (PHP 7.2).
Braucht ihr weitere Angaben?

**Comment by aschempp** [comment]
Leider haben wir aktuell das API-Limit der Suchmaschine erreicht, daher funktioniert diese nicht. Ich habe den Support kontaktiert damit das Limit aufgehoben werden kann.

**Comment by giorgiojob** [comment]
Hallo, habe heute das gleich Problem mit dem Contao-Manager 1.0.1
Ab wann wir denn voraussichtlich der Manager wieder verwendbar sein um Erweiterungen etc. zu installieren?

**Comment by standing-bear** [comment]
Könnte man nicht alternativ einfach die Packagist API (Search packages by name) verwenden?

**Comment by fkaminski** [comment]
Kann man das autom. Manager Update verhindern?

**Comment by Toflar** [comment]
Wozu?

**Comment by standing-bear** [comment]
Wenn ich das richtig verstanden habe, hat das mit dem Manager-Update gar nichts zu tun, sondern mit dem Such-Limit von algolia?!

**Comment by aschempp** [comment]
> Wenn ich das richtig verstanden habe, hat das mit dem Manager-Update gar nichts zu tun, sondern mit dem Such-Limit von algolia?!

Korrekt, die Version des Managers hat damit nichts zu tun.

**Comment by giorgiojob** [comment]
Und ab wann wird man den Manager vermutlich wieder für die installation von Erweiterungen verwenden können?

**Comment by Toflar** [comment]
Wann immer der Support antwortet und eine Lösung für das Problem gefunden wurde. Du wirst es hier erfahren.

**Comment by rburch** [comment]
I'm hoping this can get resolved soon. Is there a work around that anyone can suggest?

**Comment by xchs** [comment]
You could manually add the desired package to your `composer.json`.

**Comment by fkaminski** [comment]
> Kann man das autom. Manager Update verhindern?
Na ja, habe mir angewöhnt mich zu informieren bevor ich Contao o. Pakete update. Beim CM ist das über das autom. Update so nicht möglich - (Ok - hat nichts mit diesem Issue zu tun ...)

**Comment by aschempp** [comment]
> Um wieviel Geld geht es da?

Das aktuelle Abo bekommen wir kostenlos dank Open Source, normal wäre ca. 300$ pro Monat 😉

**Comment by bekanntmacher** [comment]
Huch € 3600/Jahr sind viel... ist ein Sponsoring keine Option?

**Comment by standing-bear** [comment]
`You could manually add the desired package to your composer.json.`
Hast Du dafür mal ein Beispiel?

Meine composer.json sieht nach der frischen Installation mit dem CM aus wie folgt:
```
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0+",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": ">=5.6.0",
        "contao/manager-bundle": "4.4.*",
        "contao/calendar-bundle": "^4.4",
        "contao/comments-bundle": "^4.4",
        "contao/faq-bundle": "^4.4",
        "contao/listing-bundle": "^4.4",
        "contao/news-bundle": "^4.4",
        "contao/newsletter-bundle": "^4.4"
    },
    "config": {
        "component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```
Ich habe das dann geändert, um den Rocksolid-Slider zu installieren, auf:
```
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0+",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": ">=5.6.0",
        "contao/manager-bundle": "4.4.*",
        "contao/calendar-bundle": "^4.4",
        "contao/comments-bundle": "^4.4",
        "contao/faq-bundle": "^4.4",
        "contao/listing-bundle": "^4.4",
        "contao/news-bundle": "^4.4",
        "contao/newsletter-bundle": "^4.4",
        "contao/newsletter-bundle": "^4.4",
        "madeyourday/contao-rocksolid-slider":"^2.0.7"
    },
    "config": {
        "component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```
Das führt aber zu einer Fehlermeldung!? Ist der Eintrag falsch, oder muss man noch etwas anderes machen?

**Comment by xchs** [comment]
Bitte melde Dich im [Forum](https://community.contao.org). Hier ist nicht der richtige Ort, um das im Detail zu diskutieren.

**Comment by standing-bear** [comment]
OK ;-)
[https://community.contao.org/de/showthread.php?71122-Contao-4-Extension-installieren-per-composer-json](https://community.contao.org/de/showthread.php?71122-Contao-4-Extension-installieren-per-composer-json)

**Comment by Toflar** [comment]
Aaand we're back up.

**Comment by Toflar** [comment]
Jaja. Sie migrieren unseren Account auf den OpenSource-Account. Wir sind dran.
