### ISSUE TITLE
Es werden keine Pakete gefunden

### ISSUE THREAD

**Issue by arboc** [contao/contao-manager#289]
Mit Version 1.0.1 werden keine Pakete mehr gefunden. Es erscheint folgende Fehlermeldung:

> Konnte keine Ergebnisse laden.
> Prüfen Sie ihre Internet-Verbindung und deaktivieren Sie alle Javascript-Blocker.

Internetverbindung besteht und es werden auch keine JS geblockt.

In der Browser Console wird folgender Fehler protokolliert:

`algoliasearchLite.min.js:2 POST http://60dw2ljw0p-3.algolianet.com/1/indexes/v2_de/query?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.22.1&x-algolia-application-id=60DW2LJW0P&x-algolia-api-key=e6efbab031852e115032f89065b3ab9f 403 (Forbidden)`

Beim Aufruf der URL (http://60dw2ljw0p-3.algolianet.com/1/indexes/v2_de/query?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.22.1&x-algolia-application-id=60DW2LJW0P&x-algolia-api-key=e6efbab031852e115032f89065b3ab9f) erhalte ich die Rückmeldung:
`{"message":"Operations quota exceeded, change plan to get more Operations.","status":403}`

**Comment by xchs** [comment]
Duplicate of https://github.com/contao/contao-manager/issues/288
