### ISSUE TITLE
Manuelle Paketinstallation

### ISSUE THREAD

**Issue by xchs** [contao/contao-manager#290]
In manchen Situationen _(*)_ wäre es vielleicht ganz praktisch, wenn es im Contao Manager irgendwo die Möglichkeit gäbe, Drittanbieterpakete auch manuell via Eingabefeld zu installieren (quasi ein Pro Mode).

So könnte man sich z. B. via Packagist die betreffende Anweisung kopieren, im Contao Manager im entsprechenden Eingabefeld einfügen und anschließend das Update via Paketaktualisierung ausführen lassen:

![cm](https://user-images.githubusercontent.com/1218766/41588320-ae657a80-73b1-11e8-8e88-7b11074b4b08.jpg)

Falls das Ausführen solcher Kommandos via Eingabefeld zu "riskant" erscheint, könnte man eventuell auch nur den Paketnamen zulassen:

![cm2](https://user-images.githubusercontent.com/1218766/41588517-4b4fdf3e-73b2-11e8-90e1-0759278382ee.jpg)

_(*) Etwa wenn die Verbindung zu externen Suchanbietern – aus welchen Gründen auch immer – gestört ist und darüber hinaus auch kein direkter SSH-Zugang zum Webspace zur Verfügung steht._

**Comment by proplab** [comment]
Aktuell scheint es ja ein Problem mit der Paketsuche zu geben (Algolia). Da würde ich mir das auch wünschen.

**Comment by aschempp** [comment]
Aktuell ist das ganz einfach möglich indem du die `composer.json` editierst, den Eintrag hinzufügst, und danach über den Manager ein Update machst.

**Comment by proplab** [comment]
Ja natürlich. Aber irgendwie muss ich die Abhängigkeiten schon mal grob vorauflösen.
Die Composer Cloud weist dann falsch gesetzte Abhängigkeiten zurück.
Das ist schon sehr gut. Aber bei der oben genannten Lösung würdeman nur den Namen des Pakets eingeben. Das wäre schon bequemer. 
Oder geht das in der `composer.json` auch?

**Comment by Ynda** [comment]
Nein in der composer.json musst du schon den richtigen Paketnamen inkl. Version eintragen.

**Comment by aschempp** [comment]
Manuelle Pakete müssen manuell hinzugefügt werden. Mit ac3d7ad73fd25a3c06598da96027cd31210242c1 kann danach ein normales `composer update` ausgeführt werden.
