### ISSUE TITLE
Der Contao Manager konnte einen Konsolentask nicht starten!

### ISSUE THREAD

**Issue by Aotearoa59** [contao/contao-manager#292]
Ich habe bei Hostpoint zwei Projekte mit Contao 4.4.18 laufen, beide mit Contao Manager 1.0.0 installiert. Alles ging bestens.
Bei neuem Projekt habe ich alles gleich gemacht, nur musste ich neu  Contao Manager Version 1.0.1 akzeptieren, damit  es weiter geht.
Aber nun geht es nicht mehr weiter. Es erscheint die oben genannte Meldung mit dem Zusatz, der CM unterstützt ihren Server ggf nicht. Aber vorher konnte ich 2 Installationen mit dem CM 1.0.0 bei Hostpoint machen. Ich bin ratlos? 
Vielen Dank für Hilfe!

**Comment by Aotearoa59** [comment]
Klar, mach ich. Obwohl es fast peinlich ist.
Es war die falsche php Version. Ich habe zwar 7.2 ausgewählt, aber nicht richtig gespeichert.

**Comment by Toflar** [comment]
Ach, das passiert uns doch allen ständig 😄 Danke!
