### ISSUE TITLE
Errors while updating

### ISSUE THREAD

**Issue by Defcon0** [contao/contao-manager#293]
Hello,

I just installed the new contao manager for a customer. After doing the installation and selecting the manual server hoster profile (the php path is ok: /usr/bin/php) I wanted to update - first dry-run then the real deal - but it failed for both ways -> see attachment. What can I do?

Thanks!

![screen](https://user-images.githubusercontent.com/1485098/41780468-148d2580-7635-11e8-8491-070828f22760.png)

**Comment by Defcon0** [comment]
I guess I should add that it works perfectly when doing it without the cloud usage.

**Comment by aschempp** [comment]
Can you show a screenshot of the network request that fails? The promise rejection (at least the first one) is correct, your Contao 4.4 does not support access-key configuration.

**Comment by Defcon0** [comment]
No problem, the result is:

`{"title":"Updating Packages","summary":"Console task terminated!","detail":"The background task has stopped unexpectedly. Please check the console protocol.","console":"Loading composer repositories with package information\n\nAn error occured during resolving process.","cancellable":true,"autoclose":false,"audit":false,"status":"error"}`

And the response before that one is

`{"title":"Updating Packages","summary":"Resolving dependencies using Composer Cloud","detail":"Job ID 5b2d085f56e490.00490125 is running for 0 seconds","console":"\u003E Resolving dependencies using Composer Cloud v1.3.3\n\n Job ID 5b2d085f56e490.00490125 is running for 0 seconds","cancellable":true,"autoclose":false,"audit":false,"status":"active"}`

**Comment by dmolineus** [comment]
A customer had a similar error. It was caused by the usage of an artifact package which is currently not supported by the cloud resolver. Maybe you have a same setup with a protected repo/artifact?

**Comment by Defcon0** [comment]
Indeed I have a private repo installed which is the case since it‘s a customer repo and I cannot put it to public :‘(. For this to be working I would have to add the public ssh key to composer cloud, right?

**Comment by aschempp** [comment]
That is not and will not be possible.

**Comment by dmolineus** [comment]
I understand that's not possible to access protected repos at the moment. However it would be great to have a way to support custom repositories somehow. Usually customer related stuff is protected and often I only provide an extension for an customer. The contao-manager would keep unusable for them if the hosting provider does not have enough ram available. So it would be great to find a solution here.

Just an crazy idea, not really thought-out. Maybe the contao manager could act as a proxy respository for the cloud resolver to provide access to protected repositories and artifacts.

**Comment by Defcon0** [comment]
I also thought about how we could achieve this, but didn't really come to a solution if we don't pass the public ssh key into the resolver :-( But in fact I'm not very familiar with the architecture of it, yet (must do it if I have time).

But it is as @dmolineus says. One of the great features (cloud resolving) stays unusable if I don't put the customer repos to public (which I can't in any way due to legal restrictions).

But anyway I'd like to thank you guys for the great job with Contao Manager. Even if I can't use the cloud resolving, it offers a way to use composer if I don't have ssh. I can upload the composer.lock and do `composer install` (not done, yet, but should be possible I think) which should be enough in most cases. The only case is if the customer wants to do the contao or module updates on its own and the server is too slow for `composer update` (which is normally the case).

**Comment by aschempp** [comment]
> do composer install (not done, yet, but should be possible I think)

This is very much possible in the maintenance screen 😉

**Comment by Defcon0** [comment]
I know, but just didn't have done it, yet ;)

**Comment by Toflar** [comment]
> I also thought about how we could achieve this, but didn't really come to a solution if we don't pass the public ssh key into the resolver :-( But in fact I'm not very familiar with the architecture of it, yet (must do it if I have time).

Technically, that would be no problem. The authorization credentials would just have to be transferred to the cloud. I mean, it's not implemented yet but it's not technically an issue. The users just have to be aware of it. So in case we ever implement a way to manage repositories and/or authorization keys in the manager and the cloud resolver is enabled at the same time I think before the update process is started, the user should get a hint that these details will be transferred to the cloud.

**Comment by Defcon0** [comment]
@Toflar Sounds promising. Maybe this can be possible in the future.

Just for the record: I just did a `composer install` and it worked even for private repos. I guess, `composer install` never runs in the cloud even if I selected "use composer cloud resolver", right?

**Comment by Toflar** [comment]
Yeah, I'm not sure we'll ever implement that. Sending around keys sounds like a very bad idea. Maybe rather have some token stuff. But we'll see. It has no priority whatsoever atm.

Yes, installation is always local.

**Comment by Toflar** [comment]
BTW, you can read more techincal details here if you like: https://medium.com/@yanick.witschi/composer-cloud-resolver-e64254f5728e

**Comment by Toflar** [comment]
> Maybe it should as the cloud resolver isn't usable for commercial projects atm :-(

Yeah, there's a very long list of things that are important to other people. If you want to ensure it has priority, there's always to option to hire us :)

**Comment by Defcon0** [comment]
OK, got it ;-)
