### ISSUE TITLE
Feature-Request? Offer "composer install" (maybe also cloud based)

### ISSUE THREAD

**Issue by Defcon0** [contao/contao-manager#294]
Hello,

what would be very useful is if the developer had the choice not only to update (with or without dry run) but also to use `composer install` after I uploaded a new one to the server.

Is this planned or even already possible?

Bye

**Comment by frontendschlampe** [comment]
It's already implemented in v1.x. You will find it under "Maintenance"

**Comment by Defcon0** [comment]
Awesome :-)... I guess you mean version > 1.0.1 (which is the current one)?

**Comment by frontendschlampe** [comment]
current is 1.0.1, but the feature was already implemented in 1.0.0 :-)

**Comment by aschempp** [comment]
It's actually implemented since Beta15 or so ;-)

**Comment by Defcon0** [comment]
Ah, I found it, thanks ;-)
