### ISSUE TITLE
all-inkl.com - Installation under Subdomain does not work

### ISSUE THREAD

**Issue by jankout** [contao/contao-manager#295]
Hello, 

when I try to install Contao under a subdomain the installation cannot be started because of the following error

`ERROR 500 Error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 4718592 bytes)`

But I can install or update existed installation over the main domain.

**Comment by xchs** [comment]
Try to increase the PHP memory limit via `.htaccess`:
```
php_value memory_limit 256M
```

**Comment by jankout** [comment]
yes, that helped.
