### ISSUE TITLE
Contao Manager 1.0.1: Problem mit Paketen aus lokalem Repository bei aktivierter Composer Cloud

### ISSUE THREAD

**Issue by arno1979** [contao/contao-manager#299]
Hallo,

um eigene, nur lokal verfügbare, Bundles über den Contao Manager zu installieren, haben wir in der `composer.json` ein lokales Repository definiert:
```json
    "repositories": [
        {
            "type": "path",
            "url": "repo/VENDOR/*"
        }
```

Dort werden die fertigen Bundles hinterlegt, dann in der `composer.json` im require Teil notiert:
```json
        "VENDOR/events-registration": "dev-master",
```
Beim aktualisieren der Pakete über den Manager wurden diese Bundles dann entsprechend erkannt und per Symlink in Contao eingebunden.

Seit dem letzten Update des Managers bekomme ich bei der Neuinstallation eines Bundles allerdings eine Fehlermeldung:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package VENDOR/events-registration could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

Führe ich dagegen `composer update -o` per Shell aus wird das Bundle wie gewohnt ohne Probleme installiert. Es taucht dann auch wie erwartet im Manager in der Liste der installierten Pakete auf.

Ich konnte das soweit analysieren, dass das Problem nicht auftritt, wenn ich die Verwendung der Composer Cloud deaktiviere. Was ich fast nachvollziehbar finde, denn die Composer Cloud hat natürlich keine Möglichkeit diese Abhängigkeit aufzulösen.

Ich frage mich, ob es möglich ist, lokale Repositories auch bei Verwendung der Composer Cloud zu berücksichtigen. Oder schließt sich das einfach vom Konzept her einfach aus?

Lieben Dank und viele Grüße
Arno

**Comment by Toflar** [comment]
> Führe ich dagegen composer update -o per Shell aus wird das Bundle wie gewohnt ohne Probleme installiert. Es taucht dann auch wie erwartet im Manager in der Liste der installierten Pakete auf.

Dann wird die Cloud nicht verwendet. Deswegen geht das.

> Ich frage mich, ob es möglich ist, lokale Repositories auch bei Verwendung der Composer Cloud zu berücksichtigen. Oder schließt sich das einfach vom Konzept her einfach aus?

Das schliesst isch einfach aus. Die Cloud meldet das auch, die Meldung wird nur nicht korrekt angezeigt im Manager im Moment. Aber es ist geplant, das im Vornherein zu prüfen. Also im Manager bereits anzuzeigen, dass das nicht gehen kann bevor du überhaupt die Pakete zu aktualisieren versuchst.

**Comment by arno1979** [comment]
@aschempp @Toflar 
Lieben Dank für die schnellen Antworten.
Entspricht meiner Erwartung, wie geschrieben.

Lieben Gruß
Arno

**Comment by Toflar** [comment]
> Aber es ist geplant, das im Vornherein zu prüfen. Also im Manager bereits anzuzeigen, dass das nicht gehen kann bevor du überhaupt die Pakete zu aktualisieren versuchst.

Wir können das Ticket aber direkt für dieses Feature hernehmen 😄

**Comment by arno1979** [comment]
Okay!

**Comment by aschempp** [comment]
@Toflar welche Funktionen gehen denn nicht? Path-Repository, Artifact-Repository, Platform Config, noch was?

**Comment by Toflar** [comment]
* Verbotene Config-Keys:
```
        static $forbiddenConfigKeys = [
            'platform',
            'cache-dir',
            'cache-files-dir',
            'cache-repo-dir',
            'cache-vcs-dir',
            'cache-files-ttl',
            'cache-files-maxsize',
        ];
```

* Local repositories
* Artifact repositories

Und dann halt noch Dinge die du schlecht im Vornherein testen kannst:

* Private repositories (weil kein Zugang)

**Comment by aschempp** [comment]
The feature will be included in the next version

**Comment by Toflar** [comment]
Nice!
