### ISSUE TITLE
Add progress when searching packages

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#30]
We must add some sort of progress because it takes too long and people will abort the operation.

@discordier any idea what we could tell? Maybe the hosts we're searching? "Sending", "waiting for response from", etc?

**Comment by aschempp** [comment]
Maybe related to my custom repositories registered in the project's `composer.json`?

**Comment by leofeyer** [comment]
I never had any noticeable waiting time when searching so far.

**Comment by aschempp** [comment]
This was related to the old implementation (search through Tenside API). We're now using Packagist which is way faster.

**Comment by discordier** [comment]
Keep in mind that this now only searches packagist and none of the locally configured repositories.
Therefore no satis, path and the like repositories will be searchable and none of the packages from there installable anymore.

**Comment by Toflar** [comment]
Which is not a requirement of the manager.

**Comment by discordier** [comment]
It was a requirement that people may be able to install commercial extensions via repositories supplied by their vendors, but apparently not anymore?

**Comment by leofeyer** [comment]
A solution for commercial extensions is yet to be discussed and developed. Not a version 1.0.0 priority IMO.

**Comment by discordier** [comment]
I know, I simply wanted to point out that it is not possible anymore to install anything not originating from packagist.org via contao-manager.

**Comment by aschempp** [comment]
As you can imagine, I'm totally aware of that. But it's totally irrelevant at least for now, because anyone using local repository is an advanced user and should use the command line.

**Comment by discordier** [comment]
This is simply not true, at least @frontendschlampe has his own repository where customers get their extensions from.
However, I am fine with declaring own repositories as not supported.
