### ISSUE TITLE
Konsolentask kann nicht gestartet werden

### ISSUE THREAD

**Issue by marebe1602** [contao/contao-manager#300]
Meldung:
Der Contao Manager konnte einen Konsolentask nicht starten!
Die Ausführung des Hintergrundtasks ist fehlgeschlagen.
Sollte dies nochmals passieren, unterstützt der Contao Manager Ihren Server ggf. nicht.

Frage:
wo kann ich die Fehlermeldung sehen, die den spezifischen Grund nennt, bzw. wie kann ich selbst testen, an was es liegt?

**Comment by contaoacademy** [comment]
Kannst du etwas mehr über deine Konfiguration sagen.

**Comment by marebe1602** [comment]
ein phpinfo() Auszug oder was wäre denn hilfreich?

**Comment by aschempp** [comment]
Duplicate of #267
