### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by katgirl** [contao/contao-manager#301]
Es wäre schön wenn man auf Events die durch den Contao-Manager erfolgen reagieren könnte. 
z.B. Cache geleert oder Update erfolgreich durchgeführt

Hintergrund: um ein verteiltes System ebenfalls dann automatisch zu aktualisieren würde ich gerne auf die aktionen Zugriff haben

**Comment by aschempp** [comment]
Der Manager hat keine Events. Die Aktionen erfolgen in Symfony (bzw. Composer), also müsstest du dich dort registrieren. Allerdings bezweifle ich stark dass du den Contao Manager für ein verteiltes System einsetzen solltest … wir verwenden dazu beispielsweise www.magephp.com
