### ISSUE TITLE
Contao Manager 1.0.1 (Contao 4.4): Insufficient PHP memory limit

### ISSUE THREAD

**Issue by Mediazept** [contao/contao-manager#302]
Beim Aufruf des Contao Managers bekomme ich die Meldung:

> Insufficient PHP memory limit
> Your PHP configuration only allows for 128M memory (on the command line). 

Yanick Witschi schreibt in seiner Ankündigung des [Cloud Resolvers](https://medium.com/@yanick.witschi/composer-cloud-resolver-e64254f5728e) von geringen Speichervoraussetzungen:
> We did it and people are now happily updating packages on shared hostings with limits ~100 MB RAM.

In den momentan verfügbaren Dokumentationen hier auf Github oder in der Contao Doku findet sich keine Info zum Speicherlimit.

Könnt ihr vielleicht dazu etwas klärendes sagen? Geht es mit so wenig RAM oder doch nicht? Was seht ihr als Minimum?
Liegt ein (anderes) Problem bei meinem Provider vor?
Oder ist das ein Bug im Manager?

**Comment by Toflar** [comment]
Kannst du vielleicht mal beschreiben was genau nicht funktioniert? Also welche Operation führst du durch?

**Comment by Mediazept** [comment]
Ich starte den Contao Manager, er führt die Systemprüfung aus. 
Beim Punkt "Serverkonfiguration" wähle ich "sonstige" (Provider ist nicht in der Liste) und bestätige den angebotenen PHP Binary Pfad (/usr/lib64/php7.2/bin/php). 
Dann kommt der Check "PHP Command Line Interface" der mit der Fehlermeldung 

> Insufficient PHP memory limit
Your PHP configuration only allows for 128M memory (on the command line). This is not enough to run Composer and it was not possible to automatically increase this limit. Please contact your hosting provider for support.

gefolgt von

> Installation Issues Detected
Your installation has issues that must be fixed before Contao Manager can be used.

abbricht.

So wie es sich anhört, haben sie es beim Provider durch Patchen auch weiter geschafft. Die Frage ist natürlich, wie viel RAM Contao bzw. der CM für einen vernünftigen Betrieb braucht. Reicht es, wenn der CM die Installation fertig stellen kann oder kommen im Betrieb noch höhere Anforderungen dazu?

**Comment by aschempp** [comment]
Gute Frage… wohl eher ein Überbleibsel. Aber 128MB scheint mir schon arg wenig, selbst mit der Cloud?

**Comment by Toflar** [comment]
Ja, aber ich denke es macht nicht Sinn, das zu prüfen. Also es kann eine Empfehlung sein, dass man 2018 für eine Webapplikation durchaus 256 MB in Betracht ziehen sollte aber letztendlich sollte es eine Empfehlung bleiben. Kann ja sein, dass es läuft. Wir sollten nur fix abbrechen, wenn wir wissen, dass irgend eine Aktion (z.B. Cache leeren und neu aufbauen) bei uns eigentlich immer über 128 MB braucht.

**Comment by aschempp** [comment]
nur können wir das leider nicht wissen… nur raten können wir, und ich würde raten dass 128 zu wenig ist 😂

**Comment by Toflar** [comment]
Ja aber der Check muss weg.

**Comment by aschempp** [comment]
Also du würdest ihn entfernen und nicht nur die Prüfung auf z.B. 256MB ändern?

**Comment by Toflar** [comment]
Ja eben. Der Check besagt, dass die 128 MB nicht genug für Composer sind. Das ist sowieso nicht korrekt, weil eben, durch die Cloud ist das eigentlich Wurst.

Folgende Situation:

128 MB sind ziemlich knausrig. Vor allem auf Kommandozeile wo ggf. Cronjobs laufen, die von Natur aus vielleicht mehr RAM zur Verfügung haben sollten als der Webprozess, finde ich schon sollte man mehr verlangen dürfen.
Wir können aber nicht entscheiden, ob das System so grundsätzlich läuft. Ich würde den Check wegmachen und ihn ggf. eben in eine Performance-Empfehlung oder so packen (zukünftig mal). 

Ich würde ihn nur drin lassen, wenn wir genau wissen, dass gewisse Aktionen auf Kommandozeile (deswegen mein Beispiel mit Cache löschen, ein anderes Beispiel wäre `composer install`) mind. 128 MB RAM brauchen und das wissen wir im Moment nicht. Von daher würde ich ihn im Moment entfernen.

**Comment by xchs** [comment]
Wurde der oben angesprochene Check dann entfernt oder doch nicht?

**Comment by ronschi** [comment]
Das Problem besteht leider weiterhin. Tests haben ergeben, dass mindestens 1,5GB Ram benötigt werden, damit der Check durchläuft (unabhängig davon, ob die Contao Cloud-Lösung benutzt wird oder nicht).

**Comment by manuelm** [comment]
Da ich verschiedene Limits getestet habe: `composer require` benötigt ca. 180MB. Darunter ist es nicht möglich zusätzliche Pakete zu installieren. Die initiale Installation von Contao klappt aber auch schon mit 80MB. Das UI/Frontend kommt aber mit weniger Memory aus. Hier reichten bereits die 80MB. Mit weniger habe ich nicht getestet.

Ich schlage daher vor auf der Console/den CLI auf 256 zu checken oder den Fehler in eine Warnung umzuwandeln. Aktuell kommt man nämlich überhaupt nicht weiter und steht an.

**Comment by aschempp** [comment]
Leider kann der Manager aktuell keine *Warnungen* für sowas anzeigen, aber ich kann die Limit-Prüfung sicher entsprechend anpassen. Die stammt noch von der Vor-Cloud-Zeit 🙃
