### ISSUE TITLE
Composer-Umgebung: Composer-Abhängigkeiten sind nicht installiert.

### ISSUE THREAD

**Issue by D-72** [contao/contao-manager#304]
While trying to install Contao 4.4 via Manager 1.0.1 on a system that already hosts 15 contao websites I get an error message. 

$ /usr/iports/php71/bin/php '-q' '/usr/local/www/apache24/noexec/contao4.mydomain.de/web/contao-manager.phar.php' 'composer' 'install' '--prefer-dist' '--no-dev' '--no-progress' '--no-suggest' '--no-ansi' '--no-interaction' '--optimize-autoloader' 2>&1

In JsonFile.php line 300:
                                                                               
  "/usr/local/www/apache24/noexec/contao4.mydomain.de/composer.json"  
   does not contain valid JSON                                                 
  Parse error on line 1:                                                       
                                                                               
  ^                                                                            
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['       
                                                                               

# Process terminated with exit code 1
# Result: General error

**Comment by D-72** [comment]
Installer 1.0.0-beta19 did the jub as usual.

**Comment by aschempp** [comment]
Can you tell how your `composer.json` looks like?

**Comment by D-72** [comment]
I´m sorry - I deleted that installation.
