### ISSUE TITLE
Search Results Out Of Sync/Delayed 2 days?

### ISSUE THREAD

**Issue by intelligentspark** [contao/contao-manager#305]
Hi,

I asked on the contao forum, but could only confirm that someone else was reproducing my issue.  About two days ago I submitted this package: 

https://packagist.org/packages/intelligentspark/insert-tag-event-title-bundle

it is properly marked as a contao-bundle, but the package search will not return it in results, even after clearing cache.  I also removed a package from packagist that was being returned in the package search results just to test it a different way, and it still shows that package in the search results after clearing composer cache.  It has never taken longer than a few minutes for my packages to appear.  Help!

**Comment by rburch** [comment]
I'm having this same issue with Fred. I upgraded from 1.0.1 to 1.0.2 and the upgrade got stuck the first time. When I refreshed the page after 5 minutes it looked like the upgrade worked. It may or may not be related, but after the upgrade we're not seeing updated or new modules that we have in package list. We also removed one from package list but it's still showing in the search.

**Comment by aschempp** [comment]
I'm sorry for this issue. We are currently working around API rate limitations on the search index and can't update the packages every few minutes as we did before. We need to rewrite our indexer to be less API intensive, @Toflar is currently working on this at our Contao core dev meetup. I hope we'll have a solution by the end of this week.

**Comment by intelligentspark** [comment]
Thanks for the update @aschempp!  Don't be sorry, they should be more generous with their API!!

**Comment by Toflar** [comment]
They are actually very generous but we are having around 1m indexing requests per month which is way too many 😄 I've completely reworked the indexer (https://github.com/contao/package-indexer/pull/2) which should drastically reduce the number of index operations by keeping a local cache of the data. Right now it should update the data every 30 minutes except for download and fav stats which should be updated on the first and 15th of every month.
I hope it all works fine but please keep an eye on it. Also note that for translations and logo you have to submit a PR with your data as described in https://github.com/contao/package-metadata.

**Comment by aschempp** [comment]
Looks like the new package indexer works perfectly. Thanks @Toflar !
