### ISSUE TITLE
CM 1.0.2 Fehler mit Cpanel und aktiviertem PHP-FPM - hängt bei Lade Konsolentask

### ISSUE THREAD

**Issue by screenfox** [contao/contao-manager#306]
Wir versuchen den Contao-Manager 1.0.2 auf einem Cpanel-System zu laden, allerdings bleibt die Ansicht beim Aufruf mit dem Text "Lade Konsolentask" hängen.

Vorab kurz noch dazu, dass es mit deaktiviertem PHP-FPM funktioniert, da das PHP dann als nobody läuft, kommt es nicht infrage. Der Default ist PHP-FPM auch aktiviert und soll möglichst so bleiben.

Kurz zum System:
CentOS: 7.5
Cpanel: 72.0.10
PHP 7.2 (PHP-FPM aktiviert) 
Der Document_root wurde auf das Verzeichnis web gelegt.

Die Datei contao-manager.phar.php wurde binär ins Verzeichnis /home/usr1/public_html/web kopiert und per Browser https://www.usr1-sagichnicht.de/contao-manager.phar.php aufgerufen.

Die Darstellung bleibt aber mit dem Text "Lade Konsolendatenbank" hängen.

Im error_log sind dann folgende 2 Einträge zu finden
```
[20-Jul-2018 09:34:21 UTC] PHP Fatal error:  Phar::webPhar(): Failed opening required 'phar:///home/usr1/public_html/web/contao-manager.phar.php/web/api.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home/usr1/public_html/web/contao-manager.phar.php on line 99
[20-Jul-2018 09:34:21 UTC] PHP Fatal error:  Phar::webPhar(): Failed opening required 'phar:///home/usr1/public_html/web/contao-manager.phar.php/web/api.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home/usr1/public_html/web/contao-manager.phar.php on line 99
```

Die erste Zeile im Error_log kommt wohl durch den Aufruf von https://www.usr1-sagichnicht.de/contao-manager.phar.php/api/session?_locale=de
Die zweite Zeile im Error_log wird verursacht durch den Aufruf von https://www.usr1-sagichnicht.de/contao-manager.phar.php/api/task?_locale=de

**Comment by aschempp** [comment]
Ich glaube nicht dass der Contao Manager das Problem ist, sondern eher der Phar-Support bei eurere PHP-Version. Verwendet ihr den Standard der Distribution oder eigene Module?

**Comment by qzminski** [comment]
I have just encountered the very same problem but on PHP 7.1. I moved all the files from one destination to another and then it happened. Previously it worked just great and it still works great on other systems. The PHP path is the same so I'm a bit stuck where to look for the source of the problem.

**Comment by aschempp** [comment]
What *very same problem* did you experience?

**Comment by qzminski** [comment]
When I open the Contao Manager it tries to load some console task forever. The console log says there was an error:

```
Fatal error:  Phar::webPhar(): Failed opening required 'phar:///home/website/public_html/domain.com/web/contao-manager.phar.php/web/api.php' (include_path='.:/opt/cpanel/ea-php71/root/usr/share/pear') in /home/website/public_html/domain.com/web/contao-manager.phar.php on line 99
```

**Comment by aschempp** [comment]
Maybe there's a permission problem after copying the files?

**Comment by qzminski** [comment]
I have just checked the permissions and they seem perfectly fine. Not sure what else I could check. The path in the error looks a bit strange to me as it has the double `/web/` folder in it, not sure if that's correct?

**Comment by darkojic** [comment]
Hello,
I have asked my hosting provider to upgrade PHP version. After  upgrade to PHP 7.0.31 problem has been resolved.

I am not sure whether they removed some security checks too that could cause described problem.

**Comment by xchs** [comment]
> After upgrade to PHP 7.0.31

Why was it only updated to PHP 7.0 and not to PHP 7.1 or 7.2? The security support for PHP 7.0 ends in three months.

**Comment by darkojic** [comment]
xchs, I really don't know. :)

I think they upgraded it to any version of 7 to let me try if issue is resolved. I use same hosting for several accounts and I have 7.1 with another account.

I will ask for 7.1+ for sure.

**Comment by aschempp** [comment]
This issue was closed because it has not had recent activity.
