### ISSUE TITLE
Warning: Ambiguous class resolution (Manager Plugin + MatthiasMullie)

### ISSUE THREAD

**Issue by cubano** [contao/contao-manager#307]
Im Ordner vendor ist bei MatthiasMullie und bei Manager Plugin der Unterordner src doppelt vorhanden (src innerhalb von src), was zu Warnungen führt. Habe versucht, den Ordner src innerhalb von src zu löschen, aber dann funktioniert nichts mehr. Wie kann ich das Problem lösen und warum ist der Ordner doppelt vorhanden nach dem Update auf Manager 1.0.2?

Warning: Ambiguous class resolution, "MatthiasMullie\Minify\Exceptions\FileImportException" was found in both "/home/httpd/vhosts/domain.com/httpdocs/vendor/matthiasmullie/minify/src/Exceptions/FileImportException.php" and "/home/httpd/vhosts/domain.com/httpdocs/vendor/matthiasmullie/minify/src/src/Exceptions/FileImportException.php", the first will be used.

Warning: Ambiguous class resolution, "Contao\ManagerPlugin\Routing\RoutingPluginInterface" was found in both "/home/httpd/vhosts/domain.com/httpdocs/vendor/contao/manager-plugin/src/Routing/RoutingPluginInterface.php" and "/home/httpd/vhosts/domain.com/httpdocs/vendor/contao/manager-plugin/src/src/Routing/RoutingPluginInterface.php", the first will be used.

**Comment by aschempp** [comment]
This is a strange issue in Composer, not the Contao Manager. I have experienced it myself, but was never able to reproduce. The easiest solution was to just delete the vendor folder (or a specific vendor/package) and reinstall it.

**Comment by cubano** [comment]
I know how to delete a folder :-) but I have absolutely no idea of how to reinstall a vendor/package in Composer :-( is there maybe an easy documentation for a Composer analphabet? ;-)
