### ISSUE TITLE
CM 1.0.2: Pakete angeblich inkompatibel

### ISSUE THREAD

**Issue by manjarco** [contao/contao-manager#309]
Moin,

habe gerade eine neue Contao 4.4.20 Installation aufgesetzt, die sich den CM 1.0.2 geschnappt hat. Wenn ich nun versuche Pakete zu installieren, die auf anderen 4.4.20-Installationen mit CM 1.0.1 laufen, bekomme ich den Hinweis diese seien inkompatibel.

Getestet habe ich das mit den folgenden:
codefog/contao-cookiebar
jrgregory/m17-sticky-backend-footer
terminal42/contao-easy_themes

**Comment by Toflar** [comment]
Related https://github.com/contao/contao-manager/issues/305

**Comment by Toflar** [comment]
Fixed.
