### ISSUE TITLE
Contao Manager (Windows/XAMPP) hinter Proxyfirewall funktioniert nicht

### ISSUE THREAD

**Issue by rwinkler68** [contao/contao-manager#310]
Das contao-manager.phar Script/Archiv verwendet meiner Meinung nach nicht die Umgebungsvariablen http_proxy und https_proxy. Test ohne Firewall OK, gleicher Rechner hinter Proxy, erkennt keine neue Version. Composer Diagnose zeigt in beiden Fällen alles OK. Auch eine Contao Installation über Composer funktioniert.

Sobald der Rechner mit gesetzten Umgebungsvariaben wieder vor der Proxyfirewall betrieben wird, meldet  auch Composer die fehlerhafte https Proxyverbindung, CM erkennt aber die neue Version, was eigentlich mit gesetztem https_proxy gar nicht funktionieren sollte!

**Comment by rwinkler68** [comment]
kann das jemand bestätigen?

**Comment by aschempp** [comment]
Der Proxy wäre vermutlich eine Composer-Funktion, vielleicht hilft dir das weiter?
https://twitter.com/naderman/status/1029839134070853637

**Comment by rwinkler68** [comment]
das ist bestimmt so, aber der Composer funktioniert ja auch hinter der Firewall!
Meine Meinung ist, dass der Contao Manager dort die Umgebungsvariablen nicht (richtig) nutzt

**Comment by ReneLuecking** [comment]
Ich kann das Problem bestätigen. Ich nutze den Contao-Manager innerhalb eines Docker-Containers mit Debian als Gastsystem und Windows als Hostsystem. Das ganze läuft hinter dem Proxy des Firmennetzwerks. Innerhalb des Containers sind die Umgebungsvariablen `http_proxy` und `https_proxy` gesetzt. Dadurch funktioniert Composer problemlos, wenn man es direkt über die Kommandozeile ausführt. Wenn ich allerdings mithilfe des Contao-Managers Pakete installieren will, erhalte ich folgende Fehlermeldung:

	$ /usr/local/bin/php '-q' '/var/www/html/web/contao-manager.phar.php' 'composer' 'require' 'madeyourday/contao-rocksolid-custom-elements' '--no-progress' '--no-suggest' '--no-update' '--no-scripts' '--prefer-stable' '--sort-packages' '--no-ansi' '--no-interaction' 2>&1

	In RemoteFilesystem.php line 547:
																				   
	  The "https://packagist.org/packages.json" file could not be downloaded: php  
	  _network_getaddresses: getaddrinfo failed: Name or service not known         
	  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name o  
	  r service not known                                                          
																				   
	require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

	# Process terminated with exit code 1
	# Result: General error

Ich habe bereits versucht, die beiden Umgebungsvariablen mit [`PassEnv`](http://httpd.apache.org/docs/current/mod/mod_env.html#passenv) in der `.htaccess` an PHP zu übergeben. Somit waren `$_SERVER['http_proxy']` und `$_SERVER['https_proxy']` verfügbar. Außerdem habe ich eine Datei `.env`, in der ebenfalls `http_proxy` und `https_proxy` definiert sind, innerhalb des web-Ordners abgelegt. Keines von beidem hat zur Lösung des Problems geführt.

**Comment by rwinkler68** [comment]
dachte schon ich wäre der einzige mit diesem Problem!

bei mir kommt:
The background task has stopped unexpectedly. Please check the console protocol.
und 
The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.

**Comment by ReneLuecking** [comment]
Ich habe die Lösung des Problems gefunden. Wenn Composer im non-CLI Kontext genutzt wird, wird die Umgebungsvariable `CGI_HTTP_PROXY` herangezogen (siehe [Dokumentation](https://getcomposer.org/doc/03-cli.md#http-proxy-or-http-proxy)). Dazu habe ich am Anfang der `.htaccess`-Datei im web-Order folgendes eingefügt:

    <IfModule mod_env.c>
        SetEnv CGI_HTTP_PROXY http://wwwproxy.ser.net:8080
    </IfModule>

Dadurch ist die Variable `$_SERVER['CGI_HTTP_PROXY']` in PHP verfügbar. Composer nutzt diese in der Funktion [`StreamContextFactory::getContext`](https://github.com/composer/composer/blob/master/src/Composer/Util/StreamContextFactory.php#L34).

**Comment by rwinkler68** [comment]
Das bringt mich einen kleinen Schritt weiter.
Jetzt hab ich das Problem, dass er bein Versuch den Befehl
D:^\XAMPP^\php^\php.exe "-q" "D:/xampp/htdocs/web/contao-manager.phar.php" "composer" "install" "--prefer-dist" "--no-dev" "--no-progress" "--no-suggest" "--no-ansi" "--no-interaction" "--optimize-autoloader" 2>&1

eine leere composer.json anlegt aber mit dem Fehler 
Parse error on line 1: Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[' 

aussteigt.
Aber zumindest das Proxy Problem scheint damit gelöst bzw. es gibt einen Workaround.

**Comment by ReneLuecking** [comment]
Das Problem der leeren composer.json kann ich bestätigen für den Fall, dass Contao komplett neu über den Manager installiert wird. Wenn man Contao direkt mittels Composer installiert und den Manager nachträglich hinzufügt tritt der Fehler nicht auf.

**Comment by ReneLuecking** [comment]
Meine Vermutung ist, dass das Problem in [CreateProjectOperation::doRun](https://github.com/contao/contao-manager/blob/master/api/TaskOperation/Composer/CreateProjectOperation.php#L96) liegt. (Ich hatte allerdings bisher keine Zeit das ausgiebig zu testen.) Dort wird am Ende `file_get_contents` aufgerufen, um die Datei `composer.json` von githubusercontent.com herunterzuladen. Das schlägt hinter dem Proxy aber fehl, solange der Parameter `$context` nicht übergeben wird. Als Lösung könnte man beispielsweise mittels `getenv('http_proxy')` (bzw. `getenv('https_proxy')`) oder wie Composer über `$_SERVER['CGI_HTTP_PROXY']` den Proxy ermitteln:

```php
if (!empty($_SERVER['CGI_HTTP_PROXY'])) {
    $context = stream_context_create(array(
        'http' => array(
            'proxy' => str_replace($_SERVER['CGI_HTTP_PROXY'], array('http', 'https'), 'tcp'),
            'request_fulluri' => true, // Wird von manchen Proxy-Servern benötigt
        )
    ));
} else {
    $context = null;
}

$this->filesystem->dumpFile(
    $this->environment->getJsonFile(),
    file_get_contents('https://raw.githubusercontent.com/contao/managed-edition/'.$package->getDistReference().'/composer.json', false, $context)
);
```

**Comment by ReneLuecking** [comment]
@aschempp Mich würde interessieren, welches Entwicklungssetup du für den Contao-Manager nutzt? Ich arbeite mit einem Docker-Container basierend auf [php:7.2](https://hub.docker.com/_/php/) in dem ich dann Composer, NodeJS, etc. installiert habe. Ich habe das ganze zwar zum Laufen bekommen, aber nur durch etwas tricksen und nach einigen Problembehebungen. Der Container läuft auf Windows 10 als Hostsystem.

**Comment by aschempp** [comment]
Ich nutze einfach PhpStorm. Alle weiteren Infos stehen in der Doku (https://github.com/contao/contao-manager/blob/master/docs/development.md)

**Comment by aschempp** [comment]
Likely fixed by https://github.com/contao/contao-manager/pull/329
