### ISSUE TITLE
Show all packages in contao manager

### ISSUE THREAD

**Issue by iGweb** [contao/contao-manager#312]
Hello

A simple question ;-)

currently you have to enter a name in contao manager to do a search ...

Is it possible to display all packages in contao manager?

Thank you

**Comment by iGweb** [comment]
Is my question understandable? ;-)

**Comment by Toflar** [comment]
It is but no, it's not. It's about 2'500, it'll be pretty hard to show them in a list...

**Comment by iGweb** [comment]
ah ok I find it a shame, but if it's complex I understand.

**Comment by ausi** [comment]
You can take a look at all Contao Bundles and Contao Modules on Packagist:  
<https://packagist.org/?type=contao-bundle>  
<https://packagist.org/?type=contao-module>

**Comment by iGweb** [comment]
great, thank you !!! :-)))
