### ISSUE TITLE
hostpoint trouble with app_dev.php

### ISSUE THREAD

**Issue by Aybee** [contao/contao-manager#315]
Ich habe eine **Contao 4.4.20** Installation und möchte die app_dev.php einrichten.

Konsole:
`php vendor/bin/contao-console contao:install-web-dir --user=testuser --password=testpass`

Meldung:
```
PHP Warning:  Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Bundle/BundlePluginInterface.php on line 3

Warning:      Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Bundle/BundlePluginInterface.php on line 3
PHP Warning:  Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Config/ConfigPluginInterface.php on line 3

Warning:      Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Config/ConfigPluginInterface.php on line 3
PHP Warning:  Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Routing/RoutingPluginInterface.php on line 3

Warning:      Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Routing/RoutingPluginInterface.php on line 3
PHP Warning:  Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Config/ExtensionPluginInterface.php on line 3

Warning:      Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Config/ExtensionPluginInterface.php on line 3
PHP Warning:  Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Dependency/DependentPluginInterface.php on line 3

Warning:      Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Dependency/DependentPluginInterface.php on line 3
PHP Warning:  Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php on line 3

Warning:      Unsupported declare 'strict_types' in /home/***/www/***/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php on line 3
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /home/***/www/***/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php on line 22

Parse error:      syntax error, unexpected ':', expecting ';' or '{' in /home/***/www/***/vendor/contao/manager-plugin/src/Bundle/Parser/DelegatingParser.php on line 22
```
Mit `php ` läuft dort PHP 5.6.36 mit `php-head` 7.0.30 (rausgefunden mit `php [TAB TAB]`.

Auf dem gleichen Server läuft noch ne **Contao 4.4.18**, damit hatte es damals funktioniert.

Jetzt bin ich auf die Idee gekommen die 20 auf 18 downzugraden. Geht aber immer noch nicht. (Ok, sieht so aus, als hätte der Downgrade nicht funktioniert. Im BE wird immer noch 4.4.20 angezeigt. Der CM zeigt "Version 4.4.18" an.)

Mittlerweile läuft auch auf beiden Installationen der **CM 1.0.3** in der alten Installation geht das mit `install-web-dir`, bei der anderen nicht.

Weiß jemand, wie man bei hostpoint in der Konsole PHP 7.1 oder 2 zum Laufen bekommt?

**Comment by aschempp** [comment]
Das ganze hat aber nichts mit dem Contao Manager zu tun?

> Mit php läuft dort PHP 5.6.36 mit php-head 7.0.30 (rausgefunden mit php [TAB TAB].

Wie kannst du zwei PHP-Versionen verwenden?

Ich vermute du hast das `contao/manager-plugin` in einer neueren Version erhalten, welche PHP-Version gibt dir der Manager beim Start aus?

**Comment by Toflar** [comment]
> Weiß jemand, wie man bei hostpoint in der Konsole PHP 7.1 oder 2 zum Laufen bekommt?

https://github.com/contao/contao-manager/blob/master/api/Resources/config/servers.yml#L140

**Comment by aschempp** [comment]
Bzw. hier https://github.com/contao/contao-manager/wiki/Hostpoint :wink$

**Comment by Aybee** [comment]
> Das ganze hat aber nichts mit dem Contao Manager zu tun?

Weil die Fehlermeldung von PHP-Dateien aus dem manager-plugin verursacht werden und es früher einmal ging.

> Wie kannst du zwei PHP-Versionen verwenden?

Auf der Konsole kann man ja unterschiedliche PHP-Versionen starten. Habe jetzt herausgefunden, dass ich PHP 7.2 bei Hostpoint so starten kann und das Erstellen der .env Datei damit fehlerfrei funktioniert.
`/usr/local/php72/bin/php vendor/bin/contao-console contao:install-web-dir --user=testuser --password=testpass`

Normalerweise kann man in der Konsole `php [TAB TAB]` eingeben und sieht dann, welche PHP-Versionen man aufrufen kann. Hostpoint zeigt da aber nichts mit 7.1 oder 7.2 an.

> Ich vermute du hast das contao/manager-plugin in einer neueren Version erhalten, welche PHP-Version gibt dir der Manager beim Start aus?

Auf der Domain läuft PHP 7.2. CM ist 1.0.3 und Contao ist 4.4.20. Da ist alles ok mit dem Manager, er hat Hostpoint richtig erkannt und eingetragen. Ich konnte darüber aber nicht den Pfad zur PHP binary rausfinden. Das Einrichten der app_dev muss ich ja über die Konsole machen und da hatte ich nur PHP 5.6.36 oder PHP 7.0.30 ausführen können, welches in den Fehlermeldungen endete.
