### ISSUE TITLE
PHP 7.2 wird nicht akzepitert

### ISSUE THREAD

**Issue by eS-IT** [contao/contao-manager#316]
Ich verwende als Entwicklungsumgebung PHP-Fram in einem Docker-Container. So kann ich mit verschiedenen PHP-Versionen testen. 

Wenn ich PHP 7.2.3 aktiviere, wird die Binary im Manager nicht akzeptiert. 

![manager_7 2](https://user-images.githubusercontent.com/1199106/43838209-01f36c4e-9b1b-11e8-8b7e-f9f52326384a.png)

Wenn ich PHP 7.1.15, oder PHP 7.0.28 verwende klappt es problemlos. 

![manager_7 1](https://user-images.githubusercontent.com/1199106/43838218-0b36a4c4-9b1b-11e8-8887-05a06181206b.png)

Die Pfade sollten richtig sein, da ich sie kopiert habe.

![manager_php](https://user-images.githubusercontent.com/1199106/43838225-1049089e-9b1b-11e8-98d4-46fecb3d2389.png)

Müssen noch weitere Bedingungen erfüllt sein, damit der Manager die PHP-Binary als gültig erkennt, oder handelt es sich um einen Fehler? Gibt es diesbezüglich eine Dokumentation?

**Comment by Toflar** [comment]
What happens if you run

```
$ /phpfarm/inst/php-7.2.3/bin/php contao-manager.phar.php test
```

?

**Comment by eS-IT** [comment]
Da erscheint folgender Fehler:

```sh
Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0

Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
{"version":"7.2.3","version_id":70203,"sapi":"cli"}
```

Komisch, ist die mitgelieferte php.ini. Ich schmeiße es mal raus und schaue ob es dann läuft.

**Comment by eS-IT** [comment]
Läuft, danke für die Hilfe und entschuldige die Störung. Ich weiß ihr habt bessere zu tun.
