### ISSUE TITLE
Firefox: Problem beim authentifizieren

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao-manager#320]
Aufruf der Domain:
https://www.domain.com/contao-manager.phar.php/#/oauth?scope=admin&client_id=trakked.io%20DEV&return_url=https%3A%2F%2Fdev.app.trakked.io%2Foauth_confirm%3Ftype%3Dcontao_manager

Erhalte ich folgende Fehlermeldung:
![fehlermeldung](https://user-images.githubusercontent.com/1942550/44362816-7ba7b800-a4c2-11e8-9da2-703488d95a93.png)

Auf der Konsole:
```
Unhandled promise rejection undefined vendor.54629c06030c36fbe44e.js:16:13533
S/</e< https://www.domain.com/contao-manager.phar.php/assets/js/vendor.54629c06030c36fbe44e.js:16:13533
t.exports https://www.domain.com/contao-manager.phar.php/assets/js/vendor.54629c06030c36fbe44e.js:11:9281
S/< https://www.domain.com/contao-manager.phar.php/assets/js/vendor.54629c06030c36fbe44e.js:16:13410
i https://www.domain.com/contao-manager.phar.php/assets/js/vendor.54629c06030c36fbe44e.js:16:19066
a https://www.domain.com/contao-manager.phar.php/assets/js/vendor.54629c06030c36fbe44e.js:16:19244
n https://www.domain.com/contao-manager.phar.php/assets/js/vendor.54629c06030c36fbe44e.js:16:19777
```

Dann aktiviere ich die Netzwerkanlayse und erhalte einen ERROR 400 Unerwarteter API-Status:

`curl 'https://www.domain.com/contao-manager.phar.php/api/session?_locale=de' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' --compressed -H 'Referer: https://www.domain.com/contao-manager.phar.php/' -H 'XSRF-TOKEN: ' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: contao_manager_xsrf=KgZMoq_xrhderlhQoLAmbbml1LWwspx0_fCLKkj-cOU; contao_manager_auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzQ3OTM3MTYsImV4cCI6MTUzNDc5NTUxNiwidXNlcm5hbWUiOiJtbXFjb25zdWx0aW5nZ21iaCIsInhzcmYiOiJLZ1pNb3FfeHJoZGVybGhRb0xBbWJibWwxTFd3c3B4MF9mQ0xLa2otY09VIn0.0otyD-7o8BnYRVRcklIql18VSGl0hsk3DMObayQ_uMc' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'`

**Comment by aschempp** [comment]
Das Problem liegt daran dass Firefox (unter gewissen Umständen) das XSRF-Cookie blockiert und der Manager damit keine validen Requests mehr absenden kann. Ich habe kürzlich aber gelernt dass der XSRF-Schutz eigentlich gar nicht nötig wäre (https://knpuniversity.com/screencast/reactjs/csrf-protection#do-apis-need-protection), aber müsste erst mal den Manager entsprechend umbauen …

**Comment by christianbarkowsky** [comment]
Ich kann das Problem bestätigen. Siehe Firefox Netzwerkanalye. Im Chrome funktionierte die Authentifizierung übrigens.

<img width="1907" alt="bildschirmfoto 2018-08-21 um 08 44 12" src="https://user-images.githubusercontent.com/1230547/44393380-cc57f900-a534-11e8-8621-f5794379a667.png">

**Comment by aschempp** [comment]
Der Fehler ist in der Version 1.0.4 behoben.

**Comment by theDyingMountain** [comment]
Ein kleiner Nachtrag. Ich erhielt den gleichen Fehler leider immer noch in Version 1.0.4. und musste dann noch "per Hand" alle Cookies löschen.

**Comment by aschempp** [comment]
Was passiert denn wenn du den AdBlocker ausschaltest?

**Comment by theDyingMountain** [comment]
Kann ich leider nicht mehr reproduzieren. Ich vermute da war noch was altes im Cache. Nach löschen der Cookies trat der Fehler nicht mehr auf.
