### ISSUE TITLE
missing "Debug-Modus" at manager 1.0.3

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#321]
missing "Debug-Modus" at manager 1.0.3 - at another install with the same 1.0.3 I can see the "Debug-Modus"

![screenshot_196](https://user-images.githubusercontent.com/1045318/44366473-173e2600-a4cd-11e8-8622-01b8d67d5eaf.jpg)

**Comment by xchs** [comment]
The debug modus is only available for Contao 4.5 and higher.

**Comment by zonky2** [comment]
THX!
