### ISSUE TITLE
Indexer doesn´t add contao-bootstrap/bundle

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#322]
bug in indexer? it´s not possibel to install contao-bootstrap/bundle now

![screens](https://user-images.githubusercontent.com/1045318/44363384-5caa2580-a4c4-11e8-8582-a1e6ecf8ec8e.jpg)

I'm afraid with the bundle_all of MetaModels 2.1 for Contao 4 there will be the same problems :(

**Comment by Toflar** [comment]
Fixed in https://github.com/contao/package-indexer/commit/4005d00ff503abb3e7191c2774311ae38fd8ad82.

**Comment by zonky2** [comment]
thx!
