### ISSUE TITLE
Links “Paketdetails” und “Projekt-Webseite” in mobiler Ansicht nicht klickbar 

### ISSUE THREAD

**Issue by colonelpanick** [contao/contao-manager#323]
Popover mit weiterführenden Links verschwindet beim Antippen ohne Seitenaufruf. Dadurch kann es passieren, dass unabsichtlich der direkt hinter dem Popover befindliche Button “Paket hinzufügen” ausgelöst wird.

**Comment by aschempp** [comment]
Kannst du einen Screenshot davon machen?

**Comment by colonelpanick** [comment]
Gerne, Screenshot anbei. Antippen von bspw. „Support-Forum“ im angehängten Screenshot löst keinerlei Seitensufruf im Popover aus, das nach Tap einfach verschwindet. Ausgelöst wird stattdessen das darunter liegende „Paket aktualisieren“. Analog bspw. „Paket installieren“ bei aktiver Paketsuche.

![fc0336e4-790c-4bf8-aebd-bf78d0f432b1](https://user-images.githubusercontent.com/42584590/44479863-18dd2a80-a642-11e8-9d3e-b312d15a88b0.jpeg)

**Comment by aschempp** [comment]
Auf welchem Gerät/Browser hast du das?

**Comment by colonelpanick** [comment]
iPhone + iPad / iOS 11.4.1 / identisches Verhalten auf Safari, Firefox und iCab mobile

**Comment by aschempp** [comment]
Der Fehler ist in der Version 1.0.4 behoben

**Comment by colonelpanick** [comment]
Super, vielen Dank! Schönes WE!
