### ISSUE TITLE
Versions Angabe bei Erweiterungen

### ISSUE THREAD

**Issue by designpilot** [contao/contao-manager#324]
**Ist Zustand:** frische CT 4.4.21 Installation über CTM 1.0.3
**Frage:** Konnte man bis jetzt bei der Installation einer Erweiterung nicht die gewünschte Version noch manuell angeben

**Wieso diese Frage?**
Ich wollte die folgende Erweiterung installieren **_bugbuster/contao-be_user_online-bundle_** und der CTM 1.0.3 wollte natürlich die aktuelle 2.0.0 installieren, welche aber laut der composer.json von BugBuster zwingend die contao/core 4.5 voraussetzt (dies ist für mich der die 4.4.21 von Contao nutzt äusserst schlecht, da es zu Fehlermeldungen bei der Installation kommt).

Wie ich auf die Idee komme das der CTM 1.0.3 die aktuellste Version 2.0.0 der Erweiterung installieren möchte seht Ihr auf dem folgenden Screenshot: [https://picload.org/view/dllwriir/screenshot.jpg.html](https://picload.org/view/dllwriir/screenshot.jpg.html)

Der Version Button ist hier mit der Bezeichnung **_neuste Version_** beschriftet, durchstrichen und grau hinterlegt (nicht anklickbar) genau so beim Zahnrad daneben, welches ja eigentlich dazu da ist die Version vor der Installation manuell noch festlegen zu können (korrigiert mich bitte wenn ich hier falsch liegen sollte).

Auf jeden Fall bleibt mir so ja nichts anderes übrig als manuell in der composer.json das wie folgt anzulegen: "bugbuster/contao-be_user_online-bundle":"^1.0.1", um danach über Pakete aktualisieren die Erweiterung installiert zu bekommen.

Kann da jemand etwas dazu sagen, wieso man vor der Installation über das Zahnrad den Button daneben die Version nicht oder nicht mehr manuell festlegen kann ????

**Comment by cliffparnitzky** [comment]
Ich hab das mal ausprobiert. Nach der Suche und Auswahl des Pakets, landet man in der Haupt-View mit den Buttons "Testlauf", "Änderungen an....", usw.
Das Paket befindet sich ganz oben und man kann nun dort im Versionsfeld mittels Zahnrad was eintragen.
Im konkreten Fall muss `1.0.1` eingetragen werden.

Danach läuft alles durch:

![image](https://user-images.githubusercontent.com/1247552/44423598-c5f26d00-a586-11e8-80fc-183b0731530b.png)

**Comment by designpilot** [comment]
jetzt hab ich das verstanden was Andreas Burg gemeint hat, man muss das Paket erst hinzufügen für die Änderung und dann nich die Version mit dem Zahnrad anpassen und dann die Änderung nich durführen.

So hat es bei mir jetzt auch funktioniert.

**Comment by aschempp** [comment]
und selbst in der Suche kannst du die Version konfigurieren, wenn du das Paket vorher hinzufügst 😉

**Comment by cliffparnitzky** [comment]
Stimmt:

![image](https://user-images.githubusercontent.com/1247552/44461605-d4399b00-a611-11e8-8a8e-3013b5ff3a39.png)

**Comment by Aybee** [comment]
> jetzt hab ich das verstanden was Andreas Burg gemeint hat, man muss das Paket erst hinzufügen für die Änderung und dann noch die Version mit dem Zahnrad anpassen und dann die Änderung noch durführen.

Das hatte ich so nicht gesagt. Das bezog sich nur auf die bereits installierten Paket, dass man da die Version anpassen kann (nicht empfohlen).

Ich hatte dir heute auch ne Mail geschrieben, dass man, so wie @aschempp es auch sagt, die Version auch bei der Erstinstallation einstellen kann.

**Comment by Aybee** [comment]
Ich finde dies sollte aber nicht nötig sein, schließlich steht in der Erweiterung ja der Hinweis "erst ab Contao 4.5", oder irre ich mich da?

Siehe auch https://github.com/contao/contao-manager/issues/325#issuecomment-415065177
