### ISSUE TITLE
Error install Contao 4.4 over contao manager

### ISSUE THREAD

**Issue by goerlitzer** [contao/contao-manager#331]
Error install Contao 4.4 over contao manager on Hetzner Online

"Der Contao Manager konnte einen Konsolentask nicht starten!
Die Ausführung des Hintergrundtasks ist fehlgeschlagen.
Sollte dies nochmals passieren, unterstützt der Contao Manager Ihren Server ggf. nicht."

**Comment by Jaaaan** [comment]
Gleiches bei All Inkl. (Private) und Hosteurope (Webhosting Basic), wobei Hosteurope von Haus aus den CM weiterhin nicht unterstützt?

**Comment by AgentCT** [comment]
Ich bekomme seit heute bei All-Inkl (Private) auch keine Installation über den Contao Manager mehr hin.

**Comment by xchs** [comment]
@AgentCT Hast Du das PHP Memory Limit schon erhöht, so wie beispielsweise im Wiki angegeben: https://github.com/contao/contao-manager/wiki/All-Inkl ?

**Comment by AgentCT** [comment]
@xchs: Ich habe es schon mit verschiedenen Kombinationen von Speicherangaben versucht. Ich habe bis zu 8192M als Memory-Limit in der .htaccess versucht. Leider immer erfolglos.

**Comment by xchs** [comment]
@AgentCT Verwendest Du den Composer Cloud Resolver? Falls ja: Ändert sich etwas, wenn Du den Cloud Resolver in der Serverkonfiguration deaktivierst?

**Comment by AgentCT** [comment]
@xchs Bei den ersten Installationsversuchen von CT 4.4 und 4.6 habe ich ihn verwendet. 

Zum Schluss habe ich es sowohl bei CT 4.4 und 4.6 ohne Cloud Resolver versucht. Ohne Cloud Resolver hat die Installation zwar geklappt aber der Aufruf des Installationstools führt ins Leere.

**Comment by xchs** [comment]
> aber der Aufruf des Installationstools führt ins Leere

Das kann zwei Gründe haben: Entweder hast Du den DocumentRoot der Domain nicht korrekt auf den `web/` Unterordner gesetzt oder Du hattest bereits vor der eigentlichen Installation eine eigene `.htaccess` im `web/` Unterordner, sodass die contaoeigene `.htaccess` nicht mehr erstellt werden konnte.

**Comment by AgentCT** [comment]
Mit der Verwendung der .htaccess Datei läuft die Installation zwar durch aber beim Aufruf des Contao Installationstools kommt nur die Fehlermeldung, dass er die Seite nicht findet.

> Not Found
> 
> The requested URL /contao/install was not found on this server.

**Comment by xchs** [comment]
Das kann eigentlich nur daran liegen, dass Deine  `.htaccess` nicht berücksichtigt wird oder das ModRewrite Modul nicht zur Verfügung steht.

Funktioniert der Aufruf mit Angabe des Einstiegspunktes: `https://example.com/app.php/contao/install` ?

**Comment by AgentCT** [comment]
Das komische ist aber, dass ich mit einer alten Version vom Contao Manager eine vollständige Installation geschafft habe und nur die aktuelle Version nicht funktioniert.

Über ...../app.php/contao/install ist die Installation erreichbar und Contao funktioniert auch aber rufe ich das Frontend auf gibt es nur eine Fehlermeldung.

> Forbidden
> You don't have permission to access / on this server

Im Conto-Manager erhalten ich nun folgende Fehlermeldung:

> ERROR 500 The Contao version could not be determined
> The console returned unexpected content when asked for the Contao version. Please check the output for more information:

> PHP Parse error:  syntax error, unexpected '?' in /www/htdocs/w0138c83/new/contao/vendor/contao/manager-bundle/src/ContaoManager/Plugin.php on line 142

> Parse error: syntax error, unexpected '?' in /www/htdocs/w0138c83/new/contao/vendor/contao/manager-bundle/src/ContaoManager/Plugin.php on line 142

> 
> 
> 
>

**Comment by Toflar** [comment]
Inkompatible PHP version?

**Comment by AgentCT** [comment]
Bei dem Account läuft PHP 7.0 (Hoster: all-Inkl).

**Comment by xchs** [comment]
Contao 4.6 braucht PHP 7.1 oder höher.

**Comment by AgentCT** [comment]
Der Contao-Manager zeigt aber an das PHP 7.0 okay ist. ;)

**Comment by rainermueller** [comment]
Gleiches Problem `Der Contao Manager konnte einen Konsolentask nicht starten!` bei HostEurope WebPack 4 L (incl. mod_rewrite) mit PHP 7.2.

Contao Manager 1.1.2

**Comment by rainermueller** [comment]
> Gleiches bei All Inkl. (Private) und Hosteurope (Webhosting Basic), wobei Hosteurope von Haus aus den CM weiterhin nicht unterstützt?

Wir der Contao Manager bei HostEurope (Webhosting Produkte) nicht unterstützt?

**Comment by aschempp** [comment]
This issue was closed because it has not had recent activity.
