### ISSUE TITLE
contao 4.4 istallation nicht möglich

### ISSUE THREAD

**Issue by andreamargreiter** [contao/contao-manager#332]
![bildschirmfoto 2018-09-20 um 10 44 11](https://user-images.githubusercontent.com/43436347/45806774-30034c80-bcc2-11e8-8c94-fb3de1277646.png)
Contao 4.4. läst sich bei  mir nicht installieren ... gibt es keine andere möglichkeit ohne hintergrund-tasks?
Warum kann man das nicht wie früher ausfüher? 
Es nervt so sehr und ist so zeit-intesiv, weil der install-manager 1h lädt und mir dann sagt dass es nicht funkt. dass ich in spät. 1 woche wieder auf 3.5 zurück greifen muss 👎 
viell.könnt ihr mir helfen. ich hab php auf 7.1 gestellt und meinen host kontaktiert ... k.a. 
Danke LG Andrea :)

**Comment by ReneLuecking** [comment]
Du kannst Contao auch direkt mittels Composer installieren:

    php composer.phar create-project contao/managed-edition <ziel> '4.4.*'

Siehe dazu https://contao.org/de/download.html und https://getcomposer.org/

**Comment by aschempp** [comment]
@andreamargreiter bei welchem Hosting-Anbieter bist du denn?

**Comment by andreamargreiter** [comment]
Ok dann muss ich schauen wie das funktioniert.
Hab k.a. und bis jetzt auch immer wenn ich 2 Zeilen der Beschreibung gelesen hab abgebrochen ;D
nützt wohl nichts, wenn ich es nicht verstehe muss ich wohl noch bei 3.5 bleiben ..


Am 20.09.2018 um 14:21 schrieb Andrea Margreiter <andrea.margreiter@hotmail.com<mailto:andrea.margreiter@hotmail.com>>:

Hallo Andreas! Danke für deine Schnee Rückmeldung 😊
Alfahosting & world4you
Hab bei beiden eine Fehlermeldung bekommen und was nach-einrichten lassen (php URL Open & noch iwas)
Aber es kommt immer nicht die Fehlermeldung ... was könnte ich noch versuchen umzustellen?
Es ist echt voll zeitaufwendig weil der Fehler immer erst nach 1-2h kommt 🙄
Vielen Dank für deine Hilfe 😁

Liebe Grüße :)
Andrea

+436641030809
andrea.margreiter@hotmail.com<mailto:andrea.margreiter@hotmail.com>

----- Nachricht beantworten -----
Von: "Andreas Schempp" <notifications@github.com<mailto:notifications@github.com>>
An: "contao/contao-manager" <contao-manager@noreply.github.com<mailto:contao-manager@noreply.github.com>>
Cc: "andreamargreiter" <andrea.margreiter@hotmail.com<mailto:andrea.margreiter@hotmail.com>>, "Mention" <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: [contao/contao-manager] contao 4.4 istallation nicht möglich (#332)
Datum: Do., Sep. 20, 2018 12:51


@andreamargreiter<https://github.com/andreamargreiter> bei welchem Hosting-Anbieter bist du denn?

**Comment by aschempp** [comment]
🤔 gemäss Wiki werden beide Hosting-Anbieter unterstützt
https://github.com/contao/contao-manager/wiki/Alfahosting
https://github.com/contao/contao-manager/wiki/World4You

Versuch mal alle AdBlocker etc. zu deaktivieren

**Comment by andreamargreiter** [comment]
Danke Andreas!

Leider ist die Installation nicht mehr so einfach wie früher, nur 1 Schritt und der manager macht probleme und man muss alles wieder löschen… dass dauert stunden, aber ich denke ich hab es geschafft :D :D :D

Vielen Dank auf alle Fälle für deine rasche Rückmeldung und Inputs!
Ich werde dich garantiert irgendwann wieder belästigen ;)

Alles Gute!!

diAndi
andrea.margreiter@hotmail.com<mailto:andrea.margreiter@hotmail.com>
+436641030809
 o<:3-~-~-~


Am 25.09.2018 um 11:28 schrieb Andreas Schempp <notifications@github.com<mailto:notifications@github.com>>:


🤔 gemäss Wiki werden beide Hosting-Anbieter unterstützt
https://github.com/contao/contao-manager/wiki/Alfahosting
https://github.com/contao/contao-manager/wiki/World4You

Versuch mal alle AdBlocker etc. zu deaktivieren
