### ISSUE TITLE
PHP Warnings auf Konsole ignorieren

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#333]
Wäre es möglich, die PHP-Warnings auf der Konsole zu ignorieren... DomainFactory bekommt es bei PHP 72. leider nicht gebacken die Meldung
`PHP Warning:  Module 'intl' already loaded in Unknown on line 0`
auf der Konsole "verschwinden" zu lassen... das ist demzufolge auch bei allen Resellern wie z.B. jWeiland das Gleiche...

Durch die Meldung kommt eine 500er Meldung, mit der der Manager seinen Dienst quittiert :(

```ERROR 500 The Contao version could not be determined
The console returned unexpected content when asked for the Contao version. Please check the output for more information:

PHP Warning: Module 'intl' already loaded in Unknown on line 0
4.4.26
```

**Comment by aschempp** [comment]
Das sollte möglich sein 🤔

**Comment by srhinow** [comment]
Bei mir das gleiche. 
Hoster: DomainFactory
Contao: 4.4.26
PHP-Version: 7-72LATEST-STANDARD

Aber sowohl auf der Console als auch im Manager bleibt er mit folgedem Fehler stehen:
> ERROR 500 The Contao version could not be determined
The console returned unexpected content when asked for the Contao version. Please check the output for more information:

>PHP Warning: Module 'intl' already loaded in Unknown on line 0
4.4.26

**Comment by zonky2** [comment]
@aschempp Du meinst so?

```
(10:15:36) [contao4] /usr/local/bin/php7-72LATEST-CLI -q -v
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP 7.2.3 (cli) (built: Mar  5 2018 11:28:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.2, Copyright (c) 2002-2018, by ionCube Ltd.
```
dann ja, kommt dennoch

**Comment by Toflar** [comment]
@aschempp du musst sie selber strippen. Aber wäre halt gut, wenn in einem solchen Fall bei uns zwar die Ausgabe funktioniert, aber eine Warning angezeigt wird beim Test. Weil das passiert nur, wenn PHP falsch konfiguriert ist, wie man in den Beispielen sieht.

**Comment by zonky2** [comment]
@aschempp als "Stripper" - auch nicht schlecht :D

**Comment by zonky2** [comment]
thx

**Comment by srhinow** [comment]
thx
