### ISSUE TITLE
PHP binary mit eigener php.ini

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#334]
Eine Umgehung von https://github.com/contao/contao-manager/issues/333 ist lt. DF die Einbindung einer eigenen php.ini

meine `manager.json` sieht wie folgt aus:

```
{
    "server": "custom",
    "last_update": "2018-09-20T14:55:40+02:00",
    "latest_version": "1.0.4",
    "php_cli": "\/usr\/local\/bin\/php7-72LATEST-CLI -c \/kunden\/123\/rp-hosting\/234\/76789\/contaocms\/php.ini"
}
```

der Aufruf wird vom Manager aber nicht akzeptiert "Es wurde kein valides PHP Programm auf dem Server gefunden."

auch mit einem Alias z.B. auf `php` wurde das nicht akzeptiert

**Comment by aschempp** [comment]
Der Wert muss ein Pfad sein, Argumente werden aus Sicherheitsgründen nicht akzeptiert.

**Comment by aschempp** [comment]
Kann ich dir nicht sagen, aber es wäre nichts was der Manager können muss, sondern das Alias muss korrekt funktionieren (falls das überhaupt geht) …

**Comment by zonky2** [comment]
der Alias `php` geht als Konsolenaufruf - wenn ich im Manager "php" bei Pfad eintrage, wird das aber nicht akzeptiert...

**Comment by aschempp** [comment]
vermutlich weil der Manager noch weitere Argumente anhängt. Funktioniert das im Konsolenaufruf auch?
