### ISSUE TITLE
Manager always wants to update all packages regardless of installed version

### ISSUE THREAD

**Issue by kartoffelheinz** [contao/contao-manager#336]
Using Contao Manager 1.0.4 for 4.4 LTS, it always shows "Update Packages" on top and "Update" behind ANY installed package - even after you just made a full system update. 

There should only be "Update" buttons if there is at least one actual update (reading: version online > version installed) available. If the current version matches the latest version online, the only acceptable button would be "re-install" or something like that.

The current situation is confusing at best. And makes you sick every time you click that button only to find out, many minutes later I'd like to add, that there are no updates at all.

And while you're at it: Please indicate the version the manager wants to update to. That is very important, since you sometimes just don't want to update to a specific version (incompatible with the setup or the likes) or know that it's only a minor bugfix and not worth the hassle at that time.

**Comment by aschempp** [comment]
This is (currently) not possible by the whole concept of Composer. The installation possibly consists of 100 different packages that all depend on each other and might or might not have updated versions. It does actually take those minutes to calculate whether an update is available, so the Manager cannot show this upfront.

**Comment by aschempp** [comment]
If you want to read up on the problem, Composer uses a SAT solver (https://en.wikipedia.org/wiki/Boolean_satisfiability_problem) to determine package compatibility.

From wikipedia:
> There is no known algorithm that efficiently solves each SAT problem, and it is generally believed that no such algorithm exists;

--- 

What's the difference between a "Check for Update" and the "Update" button? If you want to have a preview, just use the "Dry-Run" button.

**Comment by kartoffelheinz** [comment]
Well, as I said, I will never understand why anybody would use a behemoth like composer in the first place. But that's another story and we have to live with this for now.

There is a huge difference. First of all, it's confusing and unexpected - you expect an Update button if there is updates available. And second, "Update" is supposed to be a modifying action, so as a sane sysadmin you should be wary of hitting that without knowing which changes are to expect. 

Having a "check for updates", that only checks for updates and never actually changes anything improves this a lot, even if it takes ages to calculate - this should actually be the most basic feature in any package manager. 

The system should then, after it has the state "updates checked", offer a second button "update X packages", which will only show if there are actually any updates to apply. Underneath that button should be a list of the packages that the preceding "dry-run" deemed updateable, shown together with the version which they would be updated to.

You could even offload that to a cronjob which runs once a day, so when you enter the manager, there should be no need to "check for updates" (although you should always capable of force-check), and the available updates should be listed, together with version numbers etc.

**Comment by kartoffelheinz** [comment]
Regarding your suggestion to do a dry-run:
After it ran, there is NO indication whatsoever in regard of which package will actually be updated nor any info on what version will the update move a package to. 

So my issue is still on point and needs to be re-opened.

**Comment by aschempp** [comment]
You need to look at the console log to see that information.

**Comment by kartoffelheinz** [comment]
> Because it allows us to combine and reliably use free open source software from many different vendors.
I understand, and it's okay. There will always be has trade-offs and everybody will rate them differently.

Your suggestion is spot-on, and I hope we can now re-open this issue. Maybe I can find one of my mates with composer expertise to work on this and to send in a PR.

**Comment by aschempp** [comment]
> Maybe I can find one of my mates with composer expertise to work on this and to send in a PR.

That would be great! Contributions are always welcome 😊
