### ISSUE TITLE
Standard "Hostinganbieter"

### ISSUE THREAD

**Issue by internethering** [contao/contao-manager#338]
Bzgl. der Serverkonfiguration wäre es nett, wenn der Contao-Manager eine Standard-Einstellung (ohne dass man per "Individuelle Konfiguration" das PHP-Binary kompliziert händisch eintragen muss) mit sich bringt und die Auswahl des Hosters optional ist. Der Default lautet: `(/usr/bin/)php` - wenn PHP sauber per distributionseigener Paketverwaltung installiert wurde, muss man sich nämlich null Gedanken darüber machen, wo das Binary liegt:

```
php -v
PHP 7.2.10 (cli) (built: Sep 21 2018 05:12:04) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by aschempp** [comment]
Das funktioniert leider bei vielen Hosting-Anbietern nicht. Die Binary wird normalerweise automatisch erkannt, wenn Sie in `PHP_BINARY` steht. Aber es gibt Hosting-Anbieter welche das irgendwie ausschalten …

**Comment by internethering** [comment]
Das funktioniert aber nicht in Umgebungen mit PHP-FPM, da gibt `PHP_BINARY` `/usr/lib64/php7.2/bin/php-fpm` zurück und FPM kann kein CLI. Da wäre 'n Fallback auf `/usr/bin/php` angebracht.

**Comment by Toflar** [comment]
Im Web-Umfeld aufgerufen soll `PHP_BINARY` ja auch den Pfad zu `php-fpm` zurückgeben. Auf der CLI aber nicht.

**Comment by internethering** [comment]
> Auf der CLI aber nicht.

Da ist das auch nicht üblich, keine Distribution setzt bei Installation von PHP diese Environmentvariable. Ich habe mal auf drei Systemen PHP installiert und auf diese Variable und den Standardinstallationspfad gecheckt:

Gentoo Linux: PHP_BINARY nicht gesetzt, which php: /usr/bin/php
Ubuntu 16.04.5 LTS: PHP_BINARY nicht gesetzt, which php: /usr/bin/php
Debian 8.11: PHP_BINARY nicht gesetzt, /usr/bin/php

Es wäre schön, wenn Contao nicht Dinge vorraussetzt, die man erst händisch einrichten muss sondern einfach den Standard unterstützen würde.

**Comment by aschempp** [comment]
Die Binary-Suche läut im Webprozess und nicht auf der CLI, von daher versteh ich eure Diskussion nicht ganz…

> Der Default lautet: (/usr/bin/)php - wenn PHP sauber per distributionseigener Paketverwaltung installiert wurde, muss man sich nämlich null Gedanken darüber machen, wo das Binary liegt:

Das ist leider nicht wirklich richtig. Du kannst dir nur das Wiki ansehen (https://github.com/contao/contao-manager/wiki) und bei jedem Hoster ist der Pfad anders. Dein Beispiel würde auch nicht funktionieren sobald man mehrere PHP-Versionen anbietet, was ja gerade nutzen von PHP-FPM ist.

Vielleicht kannst du mir erklären worauf du hinaus willst? Wurde der PHP Pfad von deinem Manager nicht automatisch erkannt?

**Comment by internethering** [comment]
Nein, wurde er nicht. Und sorry: Hoster sind Spezialfälle, Standard unter Linux ist ganz klar /usr/bin/php unter Linux. Ich verstehe nicht, warum das so schwierig sein soll, einfach den Standard zu unterstützen - neben der manuellen Auswahl des Hosters.

**Comment by kroerig** [comment]
Hoster sind in der Contao-Welt der Standard und die nutzen meinst nicht die Distri-PHP Pakete sondern installieren ihre eigenen, damit sie den Kunden auch mehrere Versionen parallel anbieten können.

Wenn ich bei mir "Andere" auswähle, dann erkennt der Manager, dass ich mein PHP in /opt/php-7.2/bin befindet und füllt das Feld richtig aus. Das macht man i.d.R. ja auch nur einmal (außer man ändert die PHP-Version)

**Comment by aschempp** [comment]
Das sehe ich definitiv auch so. Es gibt keinen "Standard" Hoster, jede Distro hat ihre eigenen Vorstellungen. Relevant ist dass der Manager den Pfad automatisch erkennt, ist das bei dir nicht der Fall?

**Comment by internethering** [comment]
> jede Distro hat ihre eigenen Vorstellungen. 

Bitte was? 
> Gentoo Linux: PHP_BINARY nicht gesetzt, which php: /usr/bin/php
> Ubuntu 16.04.5 LTS: PHP_BINARY nicht gesetzt, which php: /usr/bin/php
> Debian 8.11: PHP_BINARY nicht gesetzt, which php: /usr/bin/php

Ich gebs auf, bei euch ist Hopfen und Malz verloren :-1:

**Comment by xchs** [comment]
Sorry, aber warum muss man hier gleich so ausfallend werden? 👎

**Comment by leofeyer** [comment]
Also `/usr/bin/php` ist schon eindeutig der Standard-Pfad für PHP in so ziemlich jeder Linux-Distribution. Entweder befindet sich dort direkt das PHP-Binary oder es ist ein Symlink, der mittels `update-alternatives --set php` auf das gewünschte PHP-Binary gesetzt wird.

Ob es sinnvoll wäre, das als Fallback im Manager zu nutzen, kann ich nicht sagen.

**Comment by aschempp** [comment]
> Bei mir erkennt er aber (woran auch immer), dass mein Binary unter /opt/php-7.2/bin/php liegt, wenn ich "Andere" auswähle.

So sollte es ja eben sein, ich frage mich nur warum das bei @internethering nicht funktioniert. Ich würde lieber den Fehler beheben als einen Standard-Fallback einzubauen.

**Comment by kroerig** [comment]
Woran erkennt der Manager denn den Pfad zum Binary? Die genannte Variable kann es ja nicht sein, die gibt es mir nämlich auch nicht.

Bei mir läuft das so ab:
Ich starte den Manager, lege den Benutzer an, und bleibt er mit "Ihre Hostingumgebung ist nicht konfiguriert" stehen, und ich muss unter "Konfigurieren" "Andere" auswählen und dann steht der richtige Pfad im Textfeld.

@internethering welcher Schritt davon funktioniert bei dir nicht?

Was ich jetzt nicht sagen kann, ist ob der Manager den Hoster erkennen kann (über Hostnamen, Pfade durchprobieren, oder andere Magie) und dann diesen Auswahlschritt überspringt.

**Comment by aschempp** [comment]
https://github.com/contao/contao-manager/blob/master/api/Process/PhpExecutableFinder.php

**Comment by kroerig** [comment]
hm, mal schauen, ob ich herausfinde, was davon bei mir greift. Die Konstanten sind es schon mal nicht.

**Comment by kroerig** [comment]
Kommt hier noch was, oder hat sich das Thema für @internethering erledigt?
