### ISSUE TITLE
Error: clear cache, or start installtool from Contao-Manager (1.0.4)

### ISSUE THREAD

**Issue by colonelpanick** [contao/contao-manager#340]
Hallo zusammen, 
gehört das nicht eher hierher?

[Error: clear cache, or start installtool from Contao-Manager (1.0.4)](https://github.com/contao/contao/issues/108)
[Twig/Loader/Filesystem.php on line 145 bzw. Lexer.php bzw. ScriptHandler.php - Allowed memory size exhausted](https://community.contao.org/de/showthread.php?72119-Twig-Loader-Filesystem-php-on-line-145-Allowed-memory-size-exhausted)

**Comment by aschempp** [comment]
No it does not. Contao Manager is the UI that runs command lines. The command line issues are part of other applications, in this case of Contao.

**Comment by colonelpanick** [comment]
Ok, sorry for spamming!
