### ISSUE TITLE
Feature: Repositories über die Manager-API eintragen

### ISSUE THREAD

**Issue by eS-IT** [contao/contao-manager#341]
Da es in Contao bisher nicht möglich ist, Pakete aus private Repositories zu finden, bzw. zu installieren, wäre es schön, wenn man über die API des Managers Repositories eintragen könnte. Leider ist ein entsprechender Aufruf augenscheinlich im Moment nicht vorgesehen.

Nachfolgend beschreibe ich was bisher möglich ist und wo meiner Meinung nach der Knackpunkt liegt.

## Anmeldung

Um Anfragen senden zu können, muss zunächst der Benutzer angemeldet werden:
```
POST:   http://server.tld/contao-manager.phar.php/api/session
Body:   {"username": "USERNAME", "password": "PASSWORD"}
```

## Update-Task (_möglich_)

Nun kann man z.B. mit der folgenden Anfrage Pakete installieren:

```
PUT:    http://server.tld/contao-manager.phar.php/api/task
Body:   {"name":"composer/update","config":{"require":{"esit/corebundle":null}}}
```

## Comoser-Einstellungen bearbeiten (_möglich_)

Leider ist es scheinbar nicht möglich auf diese Art Repositories einzutragen. Es gibt zwar `http://server.tld/contao-manager.phar.php/api/config/composer`, allerdings scheint dies nur für allegemeine Konfiguration zu funktionieren. Die Daten landen in  der Datei `TL_ROOT/contao-manager/config.json` und nicht in `TL_ROOT/composer.json`.

## Repositories eintragen (_Wunsch_)

Wenn es einen Task vergleichbar zu `composer/update` gäbe ( z.B. `composer/config` oder `composer/repositories`), könnte man damit Repositories eintragen.

```
PUT:    http://server.tld/contao-manager.phar.php/api/task
Body:  {
    "name": "composer/config", 
    "config": {
        "repositories": {
            "esit/corebundle": {
                "type": "vcs", 
                "url": "https://gitlab+deploy-token-X:TOKENHERE@server.tld/esit/corebundle.git"
            }
        }
    }
}
```

Dies würde den Umgang mit privaten Repositories erheblich erleichtern, da die Leute nicht die `composer.json` manuell bearbeiten müssten. Leider sind viele Kunden dazu nicht in der Lage.

**Comment by aschempp** [comment]
Wie genau stellst du dir eine Nutzung der API vor, wenn das UI dies nicht kann?

**Comment by eS-IT** [comment]
Über die UI wäre natürlich super, dass würde  aber auch mehr Arbeit für Euch bedeuten. Mir würde es reichen, wenn ich es über die API bedienen kann. Ich kann dann erst einmal eine externe Lösung erstellen. Zur Note aus dem Cotnao-Backend, der per Hook in GitLab. Für die Funktion ist es ja erst einmal unerheblich, woher der Aufruf kommt.

Die UI kann man dann später nachrüsten. Es gibt ja ein paar Tickets, die sich mit dem Eintragen von Repositories befassen. Man wird also vermutlich früher oder später eine Lösung brauchen. Da wäre dass doch ein Schritt in die richtige Richtung.

**Comment by aschempp** [comment]
Dir ist schon klar dass es gerade **nicht** Sinn der Sache ist dass das Contao Backend Dinge im Manager macht? 😉
