### ISSUE TITLE
world5you funktioniert nicht

### ISSUE THREAD

**Issue by jankout** [contao/contao-manager#342]
Hallo, leider funktioniert die Einstellung für world4you nicht. Egal ob ich PHP 7.1.x oder 7.2.x für die Webseite einstelle und dann in der Anbieterliste den richtigen auswähle, wird mir gezeigt, dass keine binare PHP gefunden wurde.

**Comment by aschempp** [comment]
Funktioniert es wenn du den Pfad selber angibst? Wie müsste der lauten? Der Manager hält sich einfach an's Wiki (https://github.com/contao/contao-manager/wiki/World4You), vielleicht ist das falsch?

**Comment by aschempp** [comment]
Ich schliesse dies mangels Feedback. Ggf. gerne wieder öffnen.
