### ISSUE TITLE
Contao Manager 1.0.4  Popup lässt sich nicht schließen - Fehler: 401 (Unauthorized)

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao-manager#345]
Unter Contao 4.6.x und Contao Manager 1.0.4 der Hinweis-Popup durch klick auf Schließen-Button lässt sich nicht schließen.
Wenn man längere Zeit nicht aktiv war und durch system ausgeloggt ist, tritt der Fehler 401 (Unauthorized) in der Konsole auf und mann muss die URL erneut aufrufen oder die Seite Aktualisieren.

<img width="949" alt="bildschirmfoto 2018-10-16 um 12 44 19" src="https://user-images.githubusercontent.com/11348417/47011077-3cec5200-d141-11e8-908c-a56beca3e87c.png">

**Comment by AgentCT** [comment]
Das Problem, dass der Button "Schließen" nicht funktioniert ist unabhängig von der Dauer wie lange die Session bereits geöffnet ist. Ich habe den Fehler sofort. Betroffen ist Contao Manager 1.04 mit Contao 4.69.

**Comment by aschempp** [comment]
Der gezeigte Screenshot bezieht sich aber nur auf diesen Fall. "Natürlich" lässt sich das Popup nicht schliessen, weil man ja nicht mehr angemeldet ist, und entsprechend keine Rechte dazu hat. Allerdings sollte das Popup auch nicht erscheinen, es erscheint nur weil die Task-Daten nicht abgerufen werden konnten (eben **weil** man ja gerade nicht mehr eingeloggt ist) 😄 
Ist definitiv ein Bug den ich beheben muss.

**Comment by havutcuoglu** [comment]
Dann nach Ablauf der Idil-Zeit eine Weiterleitung auf Login wäre nicht schlecht. 😃

Wenn wir schon dabei sind, habe ich eine Frage bezüglich der Manager.
Wenn man den Manager aufruft, werden erst die Erweiterungen und Module untersucht und wenn hier etwas nicht aktuell ist zwingt der Manager es zu aktualisieren. z.B. den Manager selbst.
Aktualisiert man den Manager, kommt es im Frontend zu einer Fehler und die Website ist dann nicht mehr aufrufbar. Danach muss ich die Website über die Konsole und mit viel mühe zum laufen bringen oder vor dem aktualisieren komplett Backup durchführen. 😅 

1. Kann man die Aktualisierungen im Manager (auf der Startseite) umgehen?
2. Wie kann man vermeiden, dass die Frontend-Ausgabe nicht betroffen wird?

**Comment by aschempp** [comment]
> Wenn wir schon dabei sind

Bitte nicht verschiedene Themen mischen. Falls es andere Probleme gibt, neue Tickets eröffnen!

**Comment by havutcuoglu** [comment]
> > Wenn wir schon dabei sind
> 
> Bitte nicht verschiedene Themen mischen. Falls es andere Probleme gibt, neue Tickets eröffnen!

@aschempp, hast du recht. Sorry, mein Fehler.

Ich werde es weiterhin überprüfen und ggf. werde ich ein neues Ticket dafür öffnen. Ich wollte nur wissen, ob es bekannt ist.

@xchs genau, und dieser Self-Update sorgt dafür, dass die Frontend-Ausgabe nicht funktioniert. Aber wie oben beschrieben, muss ich nochmal genauer beobachten, dann ggf. neues Ticket anlegen.

Vielen Dank Leute.
