### ISSUE TITLE
Errormeldung

### ISSUE THREAD

**Issue by asdfasdfasa** [contao/contao-manager#346]
Einige Erweiterungen welche mit Contao 4.4.1 funktionieren, geben mit der Version 4.4.26 eine Fehlermeldung. 
Diese Erweiterungen werden nicht als inkompatibel gekennzeichnet.

**Comment by Toflar** [comment]
Der Hinweis "inkompatibel" hat nichts damit zu tun, ob die Erweiterung mit deinem Setup kompatibel ist. "Inkompatibel" steht bei alten Contao 3.5-Erweiterungen, die noch nicht für Contao 4/den Contao Manager aktualisiert wurden. Dies haben wir eingeführt, weil die Leute nicht verstanden haben, warum Erweiterungen die sie jahrelang genutzt haben plötzlich verschwunden sind.

Wenn "inkompatibel" nicht dort steht, heisst das einfach, dass der Manager die Erweiterung für dich installieren kann. Ob sie dann auch wie gewünscht funktioniert, hat damit nichts zu tun und kann vom Manager ja auch nicht geprüft werden. Dies sicherzustellen ist Aufgabe der jeweiligen Entwickler, du müsstest dich also an den Entwickler dieser Erweiterung wenden, damit er/sie das Problem beheben kann.
