### ISSUE TITLE
This path does not contain a valid PHP binary

### ISSUE THREAD

**Issue by deltatree** [contao/contao-manager#348]
it is not possible to select a php binary. 
I'm using cPanel - with ssh I searched for the right php binary with: find / -name "php" -type f 2>/dev/null
I tried all but every time I'm getting "This path does not contain a valid PHP binary"
I'm using php-fpm and I switched the domain to php 7.0 - I validated it with phpinfo.

**Comment by aschempp** [comment]
Have you tried the path on the command line?

**Comment by deltatree** [comment]
Hi, yes I tried all on the command line and verified the php version so it matched to the version displayed by phpinfo

**Comment by aschempp** [comment]
Unfortunately, some hosters do run Apache in a jailroot environment where the binary paths are not available. Maybe you can test with a simple php script if you can call the binary outside the manager?

**Comment by deltatree** [comment]
solved - thank you for your help! There was no logging ... so it was not really easy ...
Here is the link that helped me to solve it:
https://forums.cpanel.net/threads/enabling-php-fpm-forces-disable_functions.590799/

**Comment by deltatree** [comment]
Closed to fast ... 
I'm now able to execute binaries by myself but the installer does not ...

Here my script in action: https://contao4-tests.deltatree.de/test.php
"/opt/cpanel/ea-php70/root/usr/bin/php -v" is a working binary
If you need the output of phpinfo:
https://contao4-tests.deltatree.de/info.php
And on the same subdomain the installer if I choose an individual configuration and set the binary to /opt/cpanel/ea-php70/root/usr/bin/php I'm getting following error:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/6955880/47783677-a48acb80-dd03-11e8-8b94-e6599b917bef.png">

**Comment by deltatree** [comment]
The source of test.php
`
<?php
	$binary = '/opt/cpanel/ea-php70/root/usr/bin/php -v';
	echo "Executing " . $binary . " ...<br><br>";
	$output = shell_exec($binary);
	echo preg_replace("/\r\n|\r|\n/",'<br/>',$output);
?>
`

**Comment by aschempp** [comment]
Please be aware that the Contao Manager uses `proc_open` and `proc_close`, **not** `shell_exec`

**Comment by deltatree** [comment]
@ausi thank you: I added your code to another php file:
http://contao4-tests.deltatree.de/test2.php

Executing /opt/cpanel/ea-php70/root/usr/bin/php -r 'die(json_encode(["version"=>PHP_VERSION,"version_id"=>PHP_VERSION_ID,"sapi"=>PHP_SAPI]));' ...

{"version":"7.0.32","version_id":70032,"sapi":"cli"}

**Comment by deltatree** [comment]
@aschempp thanks for the hint -> tried also with proc_open and proc_close:

`<?php
$descr = array(
    0 => array(
        'pipe',
        'r'
    ) ,
    1 => array(
        'pipe',
        'w'
    ) ,
    2 => array(
        'pipe',
        'w'
    )
);
$pipes = array();
$binary = '/opt/cpanel/ea-php70/root/usr/bin/php -r \'die(json_encode(["version"=>PHP_VERSION,"version_id"=>PHP_VERSION_ID,"sapi"=>PHP_SAPI]));\'';
echo "Executing " . $binary . " ...<br><br>";
$process = proc_open($binary, $descr, $pipes);
if (is_resource($process)) {
    while ($f = fgets($pipes[1])) {
        echo "-pipe 1--->";
        echo $f;
    }
    fclose($pipes[1]);
    while ($f = fgets($pipes[2])) {
        echo "-pipe 2--->";
        echo $f;
    }
    fclose($pipes[2]);
    proc_close($process);
}
?>
`

See in action: http://contao4-tests.deltatree.de/test3.php

**Comment by aschempp** [comment]
It's hard to tell why it does not work with the Manager. I tried to reach out to you via e-mail but not sure if it got delivered?

**Comment by deltatree** [comment]
You have new mail too :-)

**Comment by aschempp** [comment]
As assumed, this is a misconfiguration of your server. The Zlib/Gzip output compression was enabled on the command line. The manager will not automatically try to disabled this (6b4316ed6b7072664733ef9daf49d9abf9982892), which solves the problem for your server.

**Comment by iGweb** [comment]
Hello, I have the same problem on a site: No valid PHP binary was found on the server.

If I understood correctly, it comes from the configuration of the hosting server?
What should I do to correct this?

Thanks :)

**Comment by rrabillo** [comment]
@iGweb Same problem here, everything was working well before. The website is on a ovh shared environment, i guess it might be the problem, but if you found any solution, i'd be glad if you could share it, thank you.

**Comment by iGweb** [comment]
> @iGwebMême problème ici, tout fonctionnait bien avant. Le site Web est sur un environnement partagé ovh, je suppose que cela pourrait être le problème, mais si vous trouviez une solution, je serais heureux si vous pouviez la partager, merci.

Salut Richard, idem pour moi c'est sur un hébergement mutualisé OVH. Je n'ai pas trouvé de solutions pour ce site pour le moment...

**Comment by aschempp** [comment]
feel free to add your hoster and configuration to the Wiki (https://github.com/contao/contao-manager/wiki) and we can include the PHP path if necessary in the next release.

**Comment by rrabillo** [comment]
> 

I'm going to call OVH and i'll let you know if i find any solution.

**Comment by rrabillo** [comment]
> > @iGwebMême problème ici, tout fonctionnait bien avant. Le site Web est sur un environnement partagé ovh, je suppose que cela pourrait être le problème, mais si vous trouviez une solution, je serais heureux si vous pouviez la partager, merci.
> 
> Salut Richard, idem pour moi c'est sur un hébergement mutualisé OVH. Je n'ai pas trouvé de solutions pour ce site pour le moment...


I'm going to call OVH and i'll let you know if i find any solution.

**Comment by iGweb** [comment]
> > > @iGwebMême problème ici, tout fonctionnait bien avant. Le site Web est sur un environnement partagé ovh, je suppose que cela pourrait être le problème, mais si vous trouviez une solution, je serais heureux si vous pouviez la partager, merci.
> > 
> > 
> > Salut Richard, idem pour moi c'est sur un hébergement mutualisé OVH. Je n'ai pas trouvé de solutions pour ce site pour le moment...
> 
> I'm going to call OVH and i'll let you know if i find any solution.

OK :)

**Comment by rrabillo** [comment]
> > > > @iGwebMême problème ici, tout fonctionnait bien avant. Le site Web est sur un environnement partagé ovh, je suppose que cela pourrait être le problème, mais si vous trouviez une solution, je serais heureux si vous pouviez la partager, merci.
> > > 
> > > 
> > > Salut Richard, idem pour moi c'est sur un hébergement mutualisé OVH. Je n'ai pas trouvé de solutions pour ce site pour le moment...
> > 
> > 
> > I'm going to call OVH and i'll let you know if i find any solution.
> 
> OK :)

Hi Samuel,

I've called OVH, and as you can imagine, they told that me that access to php binaries are restricted on their shared environments. Nothing much we can here. For now, i'm using composer to install exentions and stuff. Have a good day.

**Comment by iGweb** [comment]
> > > > > @iGwebMême problème ici, tout fonctionnait bien avant. Le site Web est sur un environnement partagé ovh, je suppose que cela pourrait être le problème, mais si vous trouviez une solution, je serais heureux si vous pouviez la partager, merci.
> > > > 
> > > > 
> > > > Salut Richard, idem pour moi c'est sur un hébergement mutualisé OVH. Je n'ai pas trouvé de solutions pour ce site pour le moment...
> > > 
> > > 
> > > I'm going to call OVH and i'll let you know if i find any solution.
> > 
> > 
> > OK :)
> 
> Hi Samuel,
> 
> I've called OVH, and as you can imagine, they told that me that access to php binaries are restricted on their shared environments. Nothing much we can do here. For now, i'm using composer to install exentions and stuff. Have a good day.

Hi,
Yes I'm not really surprised by their response... I do the same thing as you on this site.
Have a good day

**Comment by aschempp** [comment]
if you can use Composer on the command line, it usually means there is a PHP binary available. But please reach out to the Contao Community (https://to.contao.org/support). I'm sure others have the same problem, but GitHub is only to track bugs and feature requests 😊
