### ISSUE TITLE
"Stopping current operation …" keine Reaktion bei "Bestätigen & Schließen"

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#349]
"Stopping current operation …" keine Reaktion bei "Bestätigen & Schließen"

![screenshot_260](https://user-images.githubusercontent.com/1045318/47740392-000f7780-dc78-11e8-9f8a-f644eff55028.jpg)

Edit: wer die Sache abschießen möchte: in `/contao-manager`die Datei `task.json` löschen...

**Comment by iainmacnab** [comment]
Habe 3 Neuinstallationen Contao 4.4 zwischen 15 und 25 Oktober gemacht. Seit dem - sogar mit php Speicher bis auf 512 MB hochgesetzt - gibt es (jeweils bei Neuinstallationen) o,g, Loop. ?? Fehlermeldungen liefer ich gerne. Danke im voraus!

**Comment by aschempp** [comment]
This has been improved in version 1.1.0
