### ISSUE TITLE
add logging for getServerInfo

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-manager#351]
Currently `PhpExecutableFinder::getServerInfo` simply returns `null` if any exception occurs while testing the given PHP CLI path:
```php
try {
    $process = (new Process($commandline))->mustRun(null, array_map(function () { return false; }, $_ENV));

    return json_decode(trim($process->getOutput()), true);
} catch (RuntimeException $e) {
    return null;
}
```
However it would be helpful to at least log the error message in the Contao Manager's log to debug such server issues. Currently we are trying to get the Contao Manager running on a web server from Internex for example, however the CLI paths do not work for some reason (the paths themselves are correct and work via SSH).

**Comment by fritzmg** [comment]
Btw. could you may be also add
```php
try {
    $process = (new Process($commandline))->mustRun(null, array_map(function () { return false; }, $_ENV));
    $output = json_decode(trim($process->getOutput()), true);

    if (null === $output) {
        throw new RuntimeException('Received unexpected output from console: ' . $process->getOutput());
    }

    return $output;
} catch (RuntimeException $e) {
    if (null !== $this->logger) {
        $this->logger->error($e->getMessage());
    }

    return null;
}
```
I had a special case on a Hoster where the console output was returned compressed - but only when console process was spawned via the web server process. It was fixed by turning off the `output_compression` for the PHP CLI, but having some sort of feedback about the output might also help tracking down such issues.

**Comment by aschempp** [comment]
Good point, added in a6bfc6fa0426c441a434b074a66edd03e4f8bf89
