### ISSUE TITLE
Kommandozeile

### ISSUE THREAD

**Issue by kroerig** [contao/contao-manager#353]
Hallo!

Manchmal könnte es hilfreich sein, ein paar Composer-Befehle auf einer Shell ausführen zu können. Nicht immer hat man die aber parat (oder ist gar nicht möglich).
Wäre es möglich, den Manager mit einer Eingabezeile für Composerbefehle auszustatten?

Also ich meine das wirklich so, dass dazu eine _composer.phar.php_ im Installationsverzeichnis liegen muss, der dann nur die Optionen übergeben werden, sodass kein Ausbruch auf eine Shell möglich ist. Könnte sonst Ärger mit den Anbietern geben. PHPShells sind nicht gerne gesehen.

**Comment by xchs** [comment]
Related: https://github.com/contao/contao-manager/issues/290

> Also ich meine das wirklich so, dass dazu eine _composer.phar.php_ im Installationsverzeichnis liegen muss

Das wäre nicht zwingend notwendig, zumal der Contao Manager die `composer.phar` bereits selbst mitbringt.

**Comment by kroerig** [comment]
Ok, dann dann der Contao-Manager sich ja selbst aufrufen, nur sollte da halt keine PHPShell raus werden.

**Comment by Toflar** [comment]
Richtig. Deshalb kann man nicht generell was nutzen. Wenn du konkret was bräuchtest, müsste es explizit in die GUI eingebaut werden (à la update und install). Aber ich sehe hier keinen Handlungsbedarf.

**Comment by kroerig** [comment]
Was ich letztens wieder schmerzlich vermisste habe, war die Möglichkeit über den Contao-Manger das Install-Tool wieder zu entsperren.

**Comment by aschempp** [comment]
Der Manager ist eine Abstraktion der Kommandozeile für nicht-Kommandozeilen-Nutzer. Aus meiner Sicht kommt eine CLI nicht in Frage.

@kroerig das hat mit diesem Issue nichts zu tun, dazu gibt es bereits eins.

**Comment by kroerig** [comment]
@aschempp Wo?

Moment, auch wenn ich mit einer Linux-Shell umgehen kann, so habe ich im Forum doch den ein oder anderen Beitrag gefunden, wo Anwendern geraten wurde ein spezielles Composer-Kommando in einer SSH-Sitzung auszuführen, und die sind daran gescheitert weil,

- das Hostingpaket kein SSH bietet

- Die Zugangsdaten dafür nicht bekannt waren

- Derjenige keine Erfahrungen mit einer Linux-Shell hat.

Diese Kollegen nutzen dann den Contao-Manager, und dann sollte es auch hier eine Möglichkeit geben Composer-Befehle abzusetzen, die ggf. nicht alltäglich sind, aber für eine Fehlersuche nötig sind.
