### ISSUE TITLE
CM und XAMPP - kein valides PHP Programm

### ISSUE THREAD

**Issue by adnan-dev** [contao/contao-manager#354]
Hallo,
habe hier und im contao-forum nach ner Lösung gesucht, aber leider nicht fündig geworden.
Habe unter XAMPP ein VHost eingerichtet (mit nem web-Ordner als doc-root), die cm-phar-Datei dort hinein geleget, umbenannt und aufgerufen. Dann den Server konfiguriert, sprich XAMPP ausgewählt und dann kommt eben leider die Info, daß kein valides PHP Programm gefunden wurde.
php.exe ist systemweit eingerichtet und kann über die Konsole aufgerufen werden. Version stimmt mit der vom CM angezeigten Version überein.
Auch mit der Einstellung "Andere" hatte ich keinen Erfolg (c:\xampp\php)

**Comment by adnan-dev** [comment]
habe mal das script aus post 348 leicht modifiziert:
`<?php
$descr = array(
    0 => array('pipe','r') ,
    1 => array('pipe','w') ,
    2 => array('pipe','w')
);
$pipes = array();
$binary = 'php -r';
echo "Executing " . $binary . " ...<br><br>";
$process = proc_open($binary, $descr, $pipes);
if (is_resource($process)) {
    while ($f = fgets($pipes[1])) {
        echo "-pipe 1--->";
        echo $f;
    }
    fclose($pipes[1]);
    while ($f = fgets($pipes[2])) {
        echo "-pipe 2--->";
        echo $f;
    }
    fclose($pipes[2]);
    proc_close($process);
}
?>`

und folgendes ergebnis erhalten:

`Executing php -r ...

-pipe 1--->Usage: php [options] [-f] [--] [args...] -pipe 1---> php [options] -r [--] [args...] -pipe 1---> php [options] [-B ] -R [-E ] [--] [args...] -pipe 1---> php [options] [-B ] -F [-E ] [--] [args...] -pipe 1---> php [options] -S : [-t docroot] [router] -pipe 1---> php [options] -- [args...] -pipe 1---> php [options] -a -pipe 1---> -pipe 1---> -a Run as interactive shell -pipe 1---> -c | Look for php.ini file in this directory -pipe 1---> -n No configuration (ini) files will be used -pipe 1---> -d foo[=bar] Define INI entry foo with value 'bar' -pipe 1---> -e Generate extended information for debugger/profiler -pipe 1---> -f Parse and execute . -pipe 1---> -h This help -pipe 1---> -i PHP information -pipe 1---> -l Syntax check only (lint) -pipe 1---> -m Show compiled in modules -pipe 1---> -r Run PHP without using script tags -pipe 1---> -B Run PHP before processing input lines -pipe 1---> -R Run PHP for every input line -pipe 1---> -F Parse and execute for every input line -pipe 1---> -E Run PHP after processing all input lines -pipe 1---> -H Hide any passed arguments from external tools. -pipe 1---> -S : Run with built-in web server. -pipe 1---> -t Specify document root for built-in web server. -pipe 1---> -s Output HTML syntax highlighted source. -pipe 1---> -v Version number -pipe 1---> -w Output source with stripped comments and whitespace. -pipe 1---> -z Load Zend extension . -pipe 1---> -pipe 1---> args... Arguments passed to script. Use -- args when first argument -pipe 1---> starts with - or script is read from stdin -pipe 1---> -pipe 1---> --ini Show configuration file names -pipe 1---> -pipe 1---> --rf Show information about function . -pipe 1---> --rc Show information about class . -pipe 1---> --re Show information about extension . -pipe 1---> --rz Show information about Zend extension . -pipe 1---> --ri Show configuration for extension . -pipe 1--->`

**Comment by fritzmg** [comment]
> Auch mit der Einstellung "Andere" hatte ich keinen Erfolg (c:\xampp\php)

Wenn, dann muss es natürlich `C:\XAMPP\php\php.exe` lauten - also `\php.exe` fehlt bei dir.

Siehe auch #351 
Vielleicht siehst du dann im Log einen genaueren Grund.

**Comment by aschempp** [comment]
Der Fehler in #348 lag daran, dass im Server die Gzip Kompression aktiv war. Ich vermute das löst diesen Fehler auch, sonst können wir das Ticket gerne wieder eröffnen.
