### ISSUE TITLE
Probleme mit Hostpoint (Schweiz)

### ISSUE THREAD

**Issue by evo-web** [contao/contao-manager#355]
Hallo zusaammen

könnt Ihr mir sagen, ob etwas bekannt ist, das Contao 4.4 bei Hostpoint nicht mehr installiert werden kann (über den Manager)?

Bekomme nach dem Starten des Managers gleich 

Stopping current operation …
The background task is being cancelled.

Dann läuft er ins leere.

Kennt jemand das Phänomen und wenn ja, wie kann ich das fixen / umgehen?

Danke

**Comment by iainmacnab** [comment]
Habe 3 Neuinstallationen Contao 4.4 zwischen 15 und 25 Oktober gemacht. Seit dem - sogar mit php Speicher bis auf 512 MB hochgesetzt - gibt es (jeweils bei Neuinstallationen) o,g, Loop. ?? Fehlermeldungen liefer ich gerne. Danke im voraus!

**Comment by evo-web** [comment]
Scheint bereits in #349 aufgenommen zu sein und liegt somit vermutlich nicht am Hoster Hostpopint
