### ISSUE TITLE
Strato Webhosting - Symlinks

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao-manager#356]
Ich habe ein Problem mit dem Strato Webhosting und Contao 4.6.8 festgestellt.
Wenn ich bei der PHP-Version 7.2 einstelle kann ich das Contao CMS ganz normal über den Contao Manager installiern, wenn Composer über Contao-Cloud mit angewählt ist, und es auch soweit einwandfrei verwenden. Auch Erweiterungen lassen sich einwandfrei z.B. "jrgregory/m17-sticky-backend-footer" und "terminal42/contao-easy_themes" installiern und verwenden. Das frühere "PHP intl" Problem existiert nicht mehr. Ich kann alles sauber im Backend von Contao machen und auch Problemlos die erstellt Contao Website aufrufen.
**Das Problem, was allerdings auftraucht ist, dass nicht die Symlinks für den Ordner "files" erstellt werden, die Contao braucht.**
Somit können z.B. keine Bilder, die unter dem Ordner "files" liegen auf der Webseite angezeigt werden.
Leider habe ich bisher keine funktionierende Lösung gefunden, verschiedennes aus den Contao-Foren ausprobiert, zumindestens soweit ich es richtig verstanden habe.
Wenn ich mich per "sftp://ssh.strato.de" auf dem Strato Webserver per FileZilla einlogge, sehe ich, dass Contao benötigte Symlinks angelgt hat allerdings nicht für für "files" d.h. von "web/files" auf "files" , für die jeweiligen Unterordner. Wichtig ist noch zu erwähnen, dass bei einem normalen FTP-Zugriff die Symlinks im FileZilla bei Strato Webhoster nicht sichtbar sind.
Ist das ein Strato Problem oder ein Contao Problem bzw. eine Rechteproblem im Zusammenspiel, welches eventl. gelöst werden kann?
Des Weiteren kann ich über die SSH-Console Symlinks anlegen in "web/files", nur den genauen Zielpfad, der auch fukntioniert habe ich noch nicht raus gefunden z.B. "ln -s files/Theme web/files" geht nicht wenn ich im Hauptverzeichnis von Contao bin. Habe auf Strato.de noch "/home/strato/www/wu/www.wunschname.de/htdocs/joomla_01/logs" als Beispiel gefunden, komme damit auch nicht weiter.

![strato symlinks](https://user-images.githubusercontent.com/17680074/48371756-eda42d80-e6bc-11e8-92c2-bad44068ca73.png)

![contao manager it erweiterungen](https://user-images.githubusercontent.com/17680074/48371844-217f5300-e6bd-11e8-8c11-11472df7edf1.png)

![symlinks files](https://user-images.githubusercontent.com/17680074/48376521-73c77080-e6cb-11e8-9084-f64cf740492b.png)

**Comment by Toflar** [comment]
Das ist doch normal? Seit Contao 4.0 kannst du nicht mehr direkt `files` veröffentlichen. Dieses Verzeichnis ist immer geschützt. Du kannst nur Unterverzeichnisse davon veröffentlichen und die Symlinks werden automatisch generiert, sobald du die Verzeichnisse im Backend anlegst.

**Comment by sdahlmann** [comment]
Sorry ich hatte vergessen die files zu veröffentlichen. Jetzt geht alles korrekt. Somit kann ich sagen, dass Strato Hosting (endlich) kompatibel ist zu Contao 4.x, auch wenn andere Webhoster besser mit Contao funktionieren.
Beim Installieren mit dem Contao Manager braucht die Installation nur eine ganze weile und bricht vereinzelt zwischendrin ab.
Bezüglich FTP-Zugriff auf Strato Webhosting z.B. mit FileZilla sollten die in dem Link: https://blog.julius-cordes.de/2016/01/strato-und-sftp/ beschriebennen Einstellungen genommen werden, damit zum einen FileZilla alle Dateien inkl. Symlinks sauber anzeigt werden und Mann alle Dateien, auch mit Sonderzeichen etc. sauber kopiert, gelöscht etc. bekommt.
