### ISSUE TITLE
CM 1.0.4 - No valid package to install 

### ISSUE THREAD

**Issue by syncgw** [contao/contao-manager#361]
Ahoi!
Ich komme - wenn ich Contao 4.6 (Latest) auswähle - nur bis zu "No valid package to install".

**Comment by cliffparnitzky** [comment]
Zu solcherlei Fragen wird dir im Forum geholfen: z.B. da --> https://community.contao.org/de/showthread.php?72734-CM-1-0-4-No-valid-package-to-install
