### ISSUE TITLE
contao-manager 1.1.0: Error Message: "PHP Command Line Interface The PHP symlink method is unavailable or does not work correctly"

### ISSUE THREAD

**Issue by toubibe** [contao/contao-manager#364]
While / after updating contao-manager 1.0.5 to 1.1.0 the following issue is reported:
"PHP Command Line Interface. The PHP symlink method is unavailable or does not work correctly."
Contao-manager 1.0.5 was working properly without any issue.

**Comment by dmolineus** [comment]
The checks are new in 1.1.0. I Ran into the same error message today though the real issue was that the system temp dir defined vor PHP CLI is not writable. Maybe it's the same issue in your environment.

**Comment by toubibe** [comment]
I got this reply from my hoster:
"das Default tmp Verzeichnis ist bei uns beschreibbar" ("default tmp file is writeable")
Not sure, if this is the correct tmp file...
