### ISSUE TITLE
config security can generate a false positive

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-manager#367]
If you do not rename the `contao-manager.phar` to `contao-manager.phar.php` as instructed, but use the name `contao-manager.php` instead, the config security check
https://github.com/contao/contao-manager/blob/aa8859726f4e297e6f186d143a9d91c22814cb98/src/components/App.vue#L77-L84
can generate a false positive in some server environments apparently.

https://community.contao.org/de/showthread.php?72800-Fehlermeldung-nach-Update-des-Mangers&p=489058&viewfull=1#post489058

¯\\_(ツ)\_/¯

**Comment by aschempp** [comment]
Should be fixed in 7704366d1241a9a38c453fe02b2b6d66a19ccbcf
