### ISSUE TITLE
Manager's language is reset to English

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao-manager#368]
Ich habe beobachtet, das die Sprache des Managers sich wieder auf Englisch zurück stellt. 
Im Forum wurde darüber auch berichtet. https://community.contao.org/de/showthread.php?72789-Umzug-einer-contao4-Installation-zu-neuem-Provider&p=489053&viewfull=1#post489053

**Comment by aschempp** [comment]
Duplicate of #362

**Comment by mlwebworker** [comment]
Tritt aber in der 1.1.1 auch noch auf.
