### ISSUE TITLE
Beim CM Update auf 1.1.x (Meldung auch bei den vorherigen Updates)

### ISSUE THREAD

**Issue by Ainschy** [contao/contao-manager#371]
Wenn der CM sich updatet und neu lädt. Bleibt er mit dieser 500er Meldung stehen:

> Compile Error: require(): Failed opening required 'phar:///var/customers/webs/XXX/test/web/cm.phar.php/api/Resources/cache/ContainerIws66io/getPhpWebControllerService.php' (include_path='.:/usr/share/php/:/usr/share/php5/')

Nach dem Reload gehts normal weiter, als wäre nichts gewesen.

**Comment by aschempp** [comment]
Das ist leider ein Server-Cache-Problem, daran kann der Manager von sich aus nichts ändern 😞
