### ISSUE TITLE
# Process terminated with exit code 137

### ISSUE THREAD

**Issue by daniel-nemeth** [contao/contao-manager#372]
Hi.
I tried to install Contao 4.6 with the Contao Manager v1.1.2. It works as it should but only with the "Composer Cloud" activated.

When i deactivate the option "Composer Cloud" it aborts all time with:

---

`Loading composer repositories with package information
Updating dependencies
sh: line 1: 718773 Killed                  /opt/plesk/php/7.2/bin/php '-q' '/var/www/vhosts/daniel-nemeth.com/bundles.daniel-nemeth.com/web/contao-manager.phar.php' 'composer' 'install' '--prefer-dist' '--no-dev' '--no-progress' '--no-suggest' '--no-ansi' '--no-interaction' '--optimize-autoloader' 2>&1

Process terminated with exit code 137
Result: Kill (terminate immediately)

The background task has stopped unexpectedly`

---

I need to deactivate the Composer Cloud because otherwise I'm not able to work with local repositories for developing some bundles. Composer Cloud is not allowing local paths.

My current server settings should be high enough, I guess.
hosttech.at
PHP: 7.2.12
memory_limit: 512M
max_execution_time: 600
max_input_time: 300
post_max_size: 512M
upload_max_size: 256M
max_input_vars: 10240

Thx for your feedback!

**Comment by daniel-nemeth** [comment]
It seems the problem is, that the Hosttech "easyhosting" packages have to less RAM. 256MB in this case.
So it doesnt help to maximize the PHP settings since the server requirements are to high.

Just for info for everybody who considers hosting on hosttech.at - do not take the easyhosting Aktion special for Contao 4 hosting.

**Comment by daniel-nemeth** [comment]
Is their a possiblity to work with the "Composer Cloud" activated and local repositories?

**Comment by aschempp** [comment]
It is not possible to use the Cloud and local repositories. Also, I don't see a reason to ever support that. If you have local repositories, you are a developer. Why not use developer tools (Composer) directly on the command line?

**Comment by daniel-nemeth** [comment]
Thanks for the feedback.
I use the command line on development stack. I was just interested if this works.

However it is strange that the server needs such high resources for a installation without the composer cloud.

**Comment by Toflar** [comment]
We‘re at about 1.6 GB RAM for most updates now. This is not strange, I‘m sure you have a lot more locally which is where you work with path repositories.

**Comment by aschempp** [comment]
Private packages are now supported in Contao Manager 1.2. I'm therefore closing this.
