### ISSUE TITLE
Win + Mamp Pro 4 | ERROR 500 Malformed UTF-8 characters

### ISSUE THREAD

**Issue by sascha-mueller** [contao/contao-manager#373]
Fehlermeldung:

`ERROR 500 Malformed UTF-8 characters, possibly incorrectly encoded`

Plattform: Win10 + Mamp Pro 4

Bis vor kurzem habe ich noch problemlos über den Manager lokal Contao verwalten können. Nun bekomme ich jedoch ständig diese Fehlermeldung un damit nicht weiter..

Selbst das frische Laden der contao-manager.phar.php con contao.org brachte keine Änderung.
Auf den ersten Blick via PHPStorm sehen auch die Dateien im Ordner "contao-manager" aus, als seien sie korrekt mit UTF8 versehen.

Habt Ihr eine Idee wo ich noch nach dem Fehler schauen kann?

**Comment by ausi** [comment]
Der Fehler scheint beim Laden einer JSON-Datei verursacht zu werden. Eventuell wurde eine JSON-Datei die der Manager ausliest bearbeitet und nicht korrekt als UTF-8 (ohne BOM) abgespeichert, z. B. die *composer.json*?

**Comment by sascha-mueller** [comment]
Soweit ich das mit Notepad++ sehen kann, hab ich nirgendwo nen bom drin.
Der Fehler tritt bei der Systemprüfung am Anfang auf.

`Der Contao Manager konnte einen Konsolentask nicht starten`

**Comment by daniel-nemeth** [comment]
Hallo.
Ich hatte das selbe Problem schon mal mit meinem Macbook. Damals war bei mir das Problem, dass ich in einer Datei ein unsichtbares Zeichen hatte, konkret als ich eine Pipe (|) machen wollte. Bei Mac gibt es eine Kombination, die ähnlich der für die Pipe ist, welche ein unsichtbares Zeichen einfügt. Dieses unsichtbare Zeichen wird dann als Fehler gewertet und wird aber leider nicht von jedem Editor erkannt.

**Comment by xchs** [comment]
Im Forum wurde das auch erst kürzlich diskutiert: https://community.contao.org/de/showthread.php?72823-Nach-update-auf-CM-1-1-2-Fehler-bei-erneutem-Login-in-CM

**Comment by sascha-mueller** [comment]
Vielen Dank für den Hinweis. Das hatte ich bisher nicht gefunden.
Interessanterweise ist es bei mir so, dass der Fehler weg ist, seit ich das Update des Managers auf die 1.1.x gemacht habe.
