### ISSUE TITLE
[contao/package-indexer] Rawgit is no more

### ISSUE THREAD

**Issue by discordier** [contao/contao-manager#375]
As the real repo (contao/package-indexer) has no issue tracker activated where I could post this, I assume this is the next appropriate place to file this.

See [https://rawgit.com/](https://rawgit.com/):
> RawGit has reached the end of its useful life
October 8, 2018
RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
If you're currently using RawGit, please stop using it as soon as you can.

So it would be much better to have a worker that transpiles the contents to github-pages or the like before the lights go out.

**Comment by Toflar** [comment]
Configured github pages and updated the indexer accordingly in https://github.com/contao/package-indexer/commit/7ddb1011d673234fe7cd570b3e5ecf2cdcad3fb6. Thanks for the heads up @discordier !!
