### ISSUE TITLE
Login lässt sich im Passwort Manager nicht mehr speichern

### ISSUE THREAD

**Issue by Olli** [contao/contao-manager#376]
Seit dem Update auf 1.1.2 lassen sich die Login Daten im Browsereigenen Passwortmanager nicht mehr speichern vermutlich weil kein `<form>` um die Login inputs erzeugt wird.
Ohne Passwortmanager zu arbeiten nervt auf die Dauer besonders bei sehr vielen Logins.
Könnte das "Feature" wieder hinzugefügt werden?

**Comment by aschempp** [comment]
I changed the implementation in d83dae6151c8c484f923155733ecb8a8a72517dd, which was good anyway. Not sure if that fixes the issue, my password manager did still not pop up (but maybe because I already saved something). Let me know if the next release does not fix the issue.
