### ISSUE TITLE
Issues without Composer Cloud enabled

### ISSUE THREAD

**Issue by andreheeke** [contao/contao-manager#377]
Since I updated the Contao Manager to version 1.1 there are problems with installation and update without the Composer Cloud. The solution would be to simply activate the Composer Cloud, but before updating to version 1.1 it worked fine without it and I would like to be self-sufficient from external factors.

Is there an explanation why you can't do without the cloud now?

This is the error message:
```
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///www/htdocs/w0125630/teamvahrenkamp.nexper.app/contao/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/Solver.php on line 220

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
Process terminated with exit code 255
Result: Unknown error
```

**Comment by xchs** [comment]
The process was terminated due to lack of memory.

**Comment by andreheeke** [comment]
Yes, that's correct. I could see that from the error message. There must be a solution that Contao can also be installed without the cloud. It worked as described before the update to 1.1.  I just don't want to be dependent on external factors.

**Comment by aschempp** [comment]
The problem might be that the complexity of a Composer update increases each day, when new package versions are released. According to that screenshot, 1.5GB of memory was not enough to run a composer update in your situation. Have you tried setting `memory_limit` to `-1` on your server?

**Comment by xchs** [comment]
> There must be a solution that Contao can also be installed without the cloud.

A solution that always works: Run the dependency resolution on your local machine.

**Comment by Toflar** [comment]
If you don't want to run it in the cloud, provide more memory. That is your solution.

**Comment by andreheeke** [comment]
Sure, more memory would be a possible solution, but is not included in most managed hosting packages.
However, I have experimented a bit. If you enter the following command in the console, it will run without problems.
```
/usr/bin/php72 composer -d memory_limit=-1 composer.phar create-project contao/managed-edition <directory> '<version>'
```
Tested in All-Inkl's premium-package.

Wouldn't it be an option to include the flag and the addition in the manager's console call? For example in combination with the configuration of the provider?

**Comment by xchs** [comment]
Your command line is wrong. That should read like this:

```
/usr/bin/php72 -d memory_limit=-1 composer.phar create-project contao/managed-edition <directory> '<version>'
```

**Comment by Toflar** [comment]
I don't understand your arguments, really. You don't want to use the cloud because you want to run things locally but at the same time you're complaining about the fact that hoster's do not provide enough memory? Yeah, that's why we built the cloud. Either you use it or you provide enough memory, where's the point? 😄 

`composer create-project` is not executed in the Manager anymore.

**Comment by andreheeke** [comment]
@xchs Oh, now I see that, too. Wrongly copied, sorry.

@Toflar The `create-project` thing was now just to see if it works at all. With the commands `install` and `update` I made the same game and it works fine when I add the flag and the parameter.
I just wanted to throw it into the room if it wouldn't make sense to include these two things in the composer command at the manager.

**Comment by xchs** [comment]
> I just wanted to throw it into the room if it wouldn't make sense to include these two things in the composer command at the manager.

It's already there in the server configuration file (for certain hosters), e.g. https://github.com/contao/contao-manager/blob/master/api/Resources/config/servers.yml#L63

**Comment by Toflar** [comment]
Yeah we might want to pass `-d memory_limit=-1` to all commands. But still it may result in a failure on your hosting. Instead of getting a `PHP Fatal error:  Allowed memory size of` your process would just get killed by some OS supervisor without further notice (likely just `Process terminated`).

**Comment by bytehead** [comment]
So the option could be added to the `allinkl` config: https://github.com/contao/contao-manager/blob/master/api/Resources/config/servers.yml#L69

**Comment by xchs** [comment]
Does it hurt if the parameter is used **by default** on all servers (as suggested above by @Toflar )? Then we would not need to adjust each server configuration individually.

**Comment by aschempp** [comment]
I have added support for a custom `php.ini` to the next Contao Manager version in 8baf913d0fe35e61b4517d4432c064579d24d51e. Simply add a `php.ini` to the `contao-manager` directory. Be aware that this will override the servers default `php.ini`, so this should be for experts only.
