### ISSUE TITLE
Automatic cache refresh on package indexer

### ISSUE THREAD

**Issue by syncgw** [contao/contao-manager#379]
Ich habe vor 2 Wochen zwei Bundles gebastelt und bei GitHub und Packagist geladen ("syncgw/contao-spambotblock" und "syncgw/contao-istope_stin"). Wurde auch brav angezeigt und ließ sich auch über den CM installieren. 

Dann habe ich mit einen anderen Namen ausgedacht "syncgw/contao-spambot" und "syncgw/contao-isotope_stin" und auf Packagist und GitHub die "alten" Repos gelöscht. 

Die gelöschten Repos erscheinen aber immer noch hartnäckig in der Paket-Suche beim CM (und lassen sich sogar installieren).... 

Es scheint kein lokales Problem zu sein - ich habe den Composer Cache gelöscht. Kann das am Cache vom Composer Cloud Resolver liegen? Wie oft wird der neu geladen? Gibt es eine Möglichkeit gelöschte Bundles aus der Such-Ansicht heraus zu bekommen?

**Comment by Toflar** [comment]
Fixed with https://github.com/contao/package-indexer/commit/583888a749a60dd6199266f523710338318d95a0
