### ISSUE TITLE
Error message after installing C 4.4.31

### ISSUE THREAD

**Issue by Schneetiger** [contao/contao-manager#380]
### **Error message after installing C 4.4.31 with CM 1.1.2.**

Please, have a look at both attached screenshots. Checked in Doctrine and searched for the problem but was not able to find it by myself. 

![screenshot_2018-12-14 es ist ein fehler aufgetreten](https://user-images.githubusercontent.com/29976466/49997534-1fe1cd00-ff92-11e8-82f4-a97087eda8ae.png)
![contao-installation 4 431 fehlermeldung in doctrine](https://user-images.githubusercontent.com/29976466/49997536-1fe1cd00-ff92-11e8-8b74-283f47cdaaba.png)

**Comment by aschempp** [comment]
This is a Contao error, not the Contao Manager.
