### ISSUE TITLE
Contao Manager in repair-modus install the wrong version of calendar-bundle

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao-manager#384]
Ich habe gerade in einer Version Contao 4.4. Das calendar-bundle über den Contao Manager entfernt. Danach hatte ich einen Fehler wegen eines fehlenden calendar-bundles - welche andere Erweiterung das calendar-bundle benötigt aber nicht requiert habe ich noch nicht untersucht. Ich habe also den repair-modus des Contao-Managers gestartet und bekomme die Meldung, dass die Abhängigkeiten nicht aufgelöst werden können. Schaue ich mir dann die composer.json an, finde ich den Eintrag 
"contao/calendar-bundle": "^4.6",
Das sollte m.E. in einer Contao 4.4 nicht passieren.
Eintrag auf "^4.4" geändert und damit läuft dann alles wieder.

**Comment by aschempp** [comment]
Da kann der Manager nichts dagegen tun… ich kann dir leider nicht sagen woher der Eintrag in deiner composer.json kam…

**Comment by mlwebworker** [comment]
Entstanden ist der Eintrag während des Repair-Vorgangs. Ich schaue mal, ob ich das demnächst in Testinstallation reproduzierbar hin bekomme.
