### ISSUE TITLE
PHP Binary Pfad nicht erkannt [Froxlor]

### ISSUE THREAD

**Issue by eleionomai** [contao/contao-manager#386]
Bei der Installation wird der PHP Binary Pfad nicht erkannt. PHP läuft als CGI mit der Verwaltungsplattform Froxlor.

Ein manueller Aufruf per SSH ergibt folgende Ausgabe:
```
/usr/bin/php7.2 '-q' '/var/customers/webs/test/web/contao-manager.phar.php' 'test'
{"version":"7.2.12-1+0~20181112102353.11+jessie~1.gbp55f21
```

Die entsprechenden Weberserver logs sehen so aus:

```
cat /var/customers/logs/test-error.log`

mod_fcgid: stderr: [] request.INFO: Matched route "contao_managerapi_server_config__invoke". {"route":"contao_managerapi_server_config__invoke","route_parameters":{"_controller":"Contao\\\\ManagerApi\\\\Controller\\\\Server\\\\ConfigController","_route":"contao_managerapi_server_config__invoke"},"request_uri":"https://test.domain.org/contao-manager.phar.php/api/server/config?_locale=de","method":"PUT"} [], referer: https://test.domain.org/contao-manager.phar.php/

mod_fcgid: stderr: [] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":2} [], referer: https://test.domain.org/contao-manager.phar.php/

[fcgid:warn] [pid 8978] [] mod_fcgid: stderr: [] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://test.domain.org/contao-manager.phar.php/

[fcgid:warn] [pid 8978] [] mod_fcgid: stderr: [] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://test.domain.org/contao-manager.phar.php/

[fcgid:warn] [pid 8978] [] mod_fcgid: stderr: [] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\\\Component\\\\Security\\\\Guard\\\\Token\\\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\\"<USER>\\", authenticated=true, roles=\\"\\"))","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://test.domain.org/contao-manager.phar.php/

[fcgid:warn] [pid 8978] [] mod_fcgid: stderr: [] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://test.domain.org/contao-manager.phar.php/

[fcgid:warn] [pid 8978] [] mod_fcgid: stderr: [] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://test.domain.org/contao-manager.phar.php/

[fcgid:warn] [pid 8978] [] mod_fcgid: stderr: [] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\TokenAuthenticator"} [], referer: https://test.domain.org/contao-manager.phar.php/

[fcgid:warn] [pid 8978] [] mod_fcgid: stderr: [] app.ERROR: The command "/usr/bin/php7.2 '-q' '/var/customers/webs/test/web/contao-manager.phar.php' 'test'" failed.  Exit Code: ()  Working directory: /var/customers/webs/test  Output: ================   Error Output: ================  {"exception":"[object] (Symfony\\\\Component\\\\Process\\\\Exception\\\\ProcessFailedException(code: 0): The command \\"/usr/bin/php7.2 '-q' '/var/customers/webs/test/web/contao-manager.phar.php' 'test'\\" failed.\\n\\nExit Code: ()\\n\\nWorking directory: /var/customers/webs/test\\n\\nOutput:\\n================\\n\\n\\nError Output:\\n================\\n at phar:///var/customers/webs/test/web/contao-manager.phar.php/vendor/symfony/process/Process.php:239)"} [], referer: https://test.domain.org/contao-manager.phar.php/
```

Da der manuelle Aufruf erfolgreich ist muss der angegebene Pfad korrekt sein.
Gibt es hier noch ein Rechteprobleme oder ähnliches?

**Comment by aschempp** [comment]
Interessant ist eigentlich die letzte Zeile. 

> The command "/usr/bin/php7.2 '-q' '/var/customers/webs/test/web/contao-manager.phar.php' 'test'" failed.  
> Exit Code: ()  
> Working directory: /var/customers/webs/test  
> Output: ================   
> Error Output: ================  

Hast du hier eine Ausgabe abgeändert oder gibt der wirklich `================` aus?

**Comment by eleionomai** [comment]
@aschempp Benötigst du noch weitere Informationen?

**Comment by aschempp** [comment]
Ich wüsste nicht welche… hast du mal den Support gefragt ob es auch eine CLI-Version der PHP-Binary gibt?

**Comment by GerritK** [comment]
Habe auf meinem Server das gleiche Problem. 🤔 Fängt PHP oder PHP-FPM das irgendwie ab?

**Comment by eleionomai** [comment]
> Ich wüsste nicht welche… hast du mal den Support gefragt ob es auch eine CLI-Version der PHP-Binary gibt?

Ist kein managed/shared Hosting, voller Zugriff also vorhanden. Was meinst du genau mit "auch eine CLI-Version"? Der Output aus meinem ersten Post wurde ja durch die CLI-Version erzeugt.

**Comment by eleionomai** [comment]
Ein Aufruf durch das vorgeschlagene Script aus Issue #348 liefert bei mir folgenden Output: 

```
<?php
$descr = array(
    0 => array(
        'pipe',
        'r'
    ) ,
    1 => array(
        'pipe',
        'w'
    ) ,
    2 => array(
        'pipe',
        'w'
    )
);
$pipes = array();
$binary = '/usr/bin/php7.2 -r \'die(json_encode(["version"=>PHP_VERSION,"version_id"=>PHP_VERSION_ID,"sapi"=>PHP_SAPI]));\'';
echo "Executing " . $binary . " ...<br><br>";
$process = proc_open($binary, $descr, $pipes);
if (is_resource($process)) {
    while ($f = fgets($pipes[1])) {
        echo "-pipe 1--->";
        echo $f;
    }
    fclose($pipes[1]);
    while ($f = fgets($pipes[2])) {
        echo "-pipe 2--->";
        echo $f;
    }
    fclose($pipes[2]);
    proc_close($process);
}
?>
```
```
Executing /usr/bin/php7.2 -r 'die(json_encode(["version"=>PHP_VERSION,"version_id"=>PHP_VERSION_ID,"sapi"=>PHP_SAPI]));' ...

-pipe 1--->{"version":"7.2.14-1+0~20190113100657.14+jessie~1.gbpd83c69","version_id":70214,"sapi":"cli"}
```

Verwendete Contao Manager Version ist 1.1.2, da sollte doch der gzip Issue ([6b4316e](https://github.com/contao/contao-manager/commit/6b4316ed6b7072664733ef9daf49d9abf9982892)) schon gefixt sein?

**Comment by aschempp** [comment]
Ich habe anhand des initialen Tickets verstanden dass du eine CGI-Version auf der Kommandozeile nutzt, und nicht eine CLI-Version?

**Comment by eleionomai** [comment]
Nein, eine CGI Variante von PHP auf der Kommandozeile auszuführen ist ja so ohne weiteres nicht möglich (Umgebungsvariablen etc...). So wie im 1. Post beschrieben verwendet der Webserver (Apache2) CGI um PHP auszuliefern:

> Bei der Installation wird der PHP Binary Pfad nicht erkannt. **PHP läuft als CGI** mit der Verwaltungsplattform Froxlor.

Was der Contao Manager dann erwartet als Angabe bei der Installation ist ja dann der Pfad zur CLI Variante von PHP (in der selben Version). Der korrekte Pfad zur CLI Variante wird dann nicht erkannt.

Überprüft wird das ganze ja scheinbar anhand des Aufrufs "contao-manager.phar.php' 'test'" der dann fehl schlägt. Wird das Kommando allerdings von Hand auf der Shell ausgeführt (genauso wie in den Webserver logs aus dem 1. Post) kommt die entsprechende korrekte Ausgabe. Daraus schließe ich, dass der Pfad eigentlich korrekt ist und die CLI Version von PHP auch korrekt läuft.

**Comment by aschempp** [comment]
Frage 1: `7.0.32-0ubuntu0.16.04.1` -> du hast echt PHP 7.0?

Frage 2: Wenn im PHP Script `echo PHP_VERSION` ausgegeben wird, was erscheint dann? genau dasselbe, inkl `...ubuntu0…`=

**Comment by eleionomai** [comment]
> Frage 1: `7.0.32-0ubuntu0.16.04.1` -> du hast echt PHP 7.0?

Nein, das war der Post von GerritK.
Ich verwende folgende Version:

```
php7.2-cgi    7.2.14-1+0~20190113100657.14+jessie~1.gbpd83c69
php7.2-cli    7.2.14-1+0~20190113100657.14+jessie~1.gbpd83c69
```

> Frage 2: Wenn im PHP Script `echo PHP_VERSION` ausgegeben wird, was erscheint dann? genau dasselbe, inkl `...ubuntu0…`?

Genau die gleiche Version:

``
7.2.14-1+0~20190113100657.14+jessie~1.gbpd83c69
``

**Comment by eleionomai** [comment]
> Interessant ist eigentlich die letzte Zeile.
> 
> > The command "/usr/bin/php7.2 '-q' '/var/customers/webs/test/web/contao-manager.phar.php' 'test'" failed.
> > Exit Code: ()
> > Working directory: /var/customers/webs/test
> > Output: ================
> > Error Output: ================
> 
> Hast du hier eine Ausgabe abgeändert oder gibt der wirklich `================` aus?

@aschempp Die Ausgabe kommt übrigens aus der 'Symfony Process Component'.

**Comment by eleionomai** [comment]
Habe zwischenzeitlich die development Version auf dem System installiert um besser debuggen zu können und festgestellt, dass der Fehler auf die auf dem System deaktivierte 'proc_get_status' Funktion zurückzuführen ist.

**Comment by Toflar** [comment]
https://github.com/contao/contao-manager/blob/03ab7c8ea49191df6b3bd65e4d36c97298d92362/api/IntegrityCheck/ProcessCheck.php#L19 müsste durch `proc_get_status` erweiteret werden.

**Comment by aschempp** [comment]
Ausserdem um `proc_terminate`
