### ISSUE TITLE
Problem mit memory limit beim warm up cache

### ISSUE THREAD

**Issue by arboc** [contao/contao-manager#388]
Bei unserem Hoster liegt das Limit von PHP-CLI bei 128MB.  Ich kann das mit einer eigenen PHP.INI übersteuern. Diese müsste dann vom Manager über php `-c pfad/zur/php.ini` berücksichtigt werden.
(Es gab schon mal einen ähnlichen Wunsch: #334  )

Alternativ könnte auch mit einer Paramterübergabe in der Form  `-d memory_limit` das Speicherlimit überschrieben werden.

In der Konfiguration müssten dann entsprechende Werte hinterlegt werden.

**Comment by aschempp** [comment]
Bei welchem Hoster bist du denn?

**Comment by arboc** [comment]
Das Problem tritt bei hosting.de auf. Nach Rücksprache mit dem Hoster wird das memory-limit auf 1024MB erhöht.

Das Problem soll auch im Zusammenhang mit https://github.com/contao/contao/issues/108 stehen.

**Comment by aschempp** [comment]
Das Problem mit einer eigenen `php.ini` ist, dass dann die "anderen" php.inis des Systems nicht mehr gelesen werden. Ich bezweifle stark ob das von Vorteil ist…?

**Comment by arboc** [comment]
@fritzmg das habe ich gelesen, ist aber keine dauerhafte Lösung....

Mit dem Update zu Contao 4.4.33 wurde das Issue geschlossen und es läuft auch alles soweit wieder.

Dennoch kann es vorkommen, dass aus irgenwelchen Gründen das memory_limit überschritten wird.
Wenn ich den Contao Manager ohne den Composer Cloud Resolver nutze, wird ja auch das `memory_limit=-1` gesetzt.

Meine Bitte ist ja, das memory_limit konfigurierbar zu machen (mit / ohne Nutzung des Composer Cloud Resolvers)

**Comment by fritzmg** [comment]
> @fritzmg das habe ich gelesen, ist aber keine dauerhafte Lösung....

Eine andere gibt es zur Zeit nicht.

**Comment by fritzmg** [comment]
> Daher habe ich ja dies Issue aufgemacht.

Hat aber nichts mit dem Contao Manager zu tun ;)

Meine Aussage

> Eine andere gibt es zur Zeit nicht.

stimmt auch nicht, denn der Workaround wurde bereits in den neuesten Contao Versionen implementiert und muss daher nicht mehr selbst gemacht werden.

**Comment by arboc** [comment]
@fritzmg 
> Hat aber nichts mit dem Contao Manager zu tun ;)

Hat es doch, weil ich vorgeschlagen habe, im Contao Manager eine Option einzurichten, in der das Memory Limit angegeben werden kann, damit es bei PHP-CLI aufruf berücksichtigt wird.  

> In der Konfiguration müssten dann entsprechende Werte hinterlegt werden.  

und  

> Meine Bitte ist ja, das memory_limit konfigurierbar zu machen (mit / ohne Nutzung des Composer Cloud Resolvers)

**Comment by aschempp** [comment]
Contao Manager 1.2 now supports a custom `php.ini` in the `contao-manager` folder.

**Comment by fritzmg** [comment]
Related: https://github.com/contao/contao/pull/840
