### ISSUE TITLE
Change the "Update" button for contao-core

### ISSUE THREAD

**Issue by Paddy0174** [contao/contao-manager#389]
I'd propose a change to the buttons "Update" and "Update packages" to make the difference between those more clear.

In the last few weeks there have been a few problems in the community forum, that depend only on people using just the button to update the core, and not all necessary packages (calendar, news,...), ending in an error, that packages aren't compatible (correct behaviour).

I can think of two possible solutions for this:
* if one clicks on the update button for the core, there will be a js alert, asking _"Do you really only want to update the core, and not all necessary packages? Press no, if you want to upgrade all contao packages together with the core."_ . If the user chooses to update all, then all contao packages should be selected, or the user is simply taken back to push the "Update packages" button.
* check, which contao extensions are installed, and if the user pushes the update button for the core, all installed contao extensions are automtically selected.

What do you think about it? Do you have better ideas to solve this?

**Comment by aschempp** [comment]
I think the core package should actually not be handled as separate packages. Here are two screen manipulations I did over a year ago, but I haven't come up with the right solution yet.
![Bildschirmfoto 2018-05-24 um 18 17 44](https://user-images.githubusercontent.com/1073273/62927660-45d89f00-bdb7-11e9-9263-ddbdd3c7b2cc.png)
![Bildschirmfoto 2018-05-25 um 08 13 05](https://user-images.githubusercontent.com/1073273/62927661-45d89f00-bdb7-11e9-9973-d345ff6b59b2.png)

**Comment by leofeyer** [comment]
I prefer the first variant.

**Comment by aschempp** [comment]
This has been added in Contao Manager 1.2 through "feature" packages.
