### ISSUE TITLE
Adjust file names

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#39]
Files of the Contao Manager must not be tenside-related (though noone cares what the bundles are named!).

 - *contao-manager.phar.php* for the PHAR
 - *contao-manager.json* for the config / auth file
 - *contao-manager/* for the configuration folder

**Comment by discordier** [comment]
... and of course `composer.json` must get named `contao-manager.packages.json`?
In the end no one cares what file names exist as long as it works.

But ok, we need to replace all names in `tenside/core` and make them configurable via `parameters.yml` then, will hunt them down.

**Comment by aschempp** [comment]
The name "tenside" must not exist to the user of the Contao Manager, therefore we should not need to tell him "please reset the password in tenside.json".

**Comment by aschempp** [comment]
Implemented in the latest version (see https://github.com/contao/contao-manager/tree/develop)
