### ISSUE TITLE
Element Tabelle mit "auge"

### ISSUE THREAD

**Issue by Bigga63** [contao/contao-manager#390]
Von einem Kunden kommt die Frage, ob man nicht auch bei dem Tabellenelement dies praktische "Auge" haben könne, mit dem einzelne Zeilen dann zeitweilig unsichtbar geschaltet werden. 
Ich würde mich freuen, wenn daran reges Interesse besteht!

**Comment by xchs** [comment]
Den Feature Request müsstest Du in diesem Repository posten: https://github.com/contao/contao/issues

**Comment by Bigga63** [comment]
doof ich!

**Comment by leofeyer** [comment]
Ich hätte es auch verschieben können. 😄 

<img width="195" alt="" src="https://user-images.githubusercontent.com/1192057/50976779-1b58f780-14f1-11e9-9533-18253ad29453.png">
