### ISSUE TITLE
console with error

### ISSUE THREAD

**Issue by my-om** [contao/contao-manager#391]
This news coming:
`Der Contao Manager konnte einen Konsolentask nicht starten!
Die Ausführung des Hintergrundtasks ist fehlgeschlagen.
Sollte dies nochmals passieren, unterstützt der Contao Manager Ihren Server ggf. nicht.
Webgo v Server
I migrate 3.5 to 4.4 - 44 modules I want to install with contao manager. 
I delete var/cache and system/modules( where i has my old modules)

**Comment by xchs** [comment]
Did you check the console log?
