### ISSUE TITLE
4.6.12 Strato und Warmup

### ISSUE THREAD

**Issue by jankout** [contao/contao-manager#393]
Hallo, 

leider kann ich die Contao-Installation aus folgenden Gründen nicht abschließen. Es passierte schon mit anderen Erweiterungen, die woanders keine Probleme machen. 

```
$ /opt/RZphp72/bin/php-cli '-q' '-d' 'max_execution_time=300' '/mnt/web221/e3/75/54138075/htdocs/contao4/vendor/contao/manager-bundle/bin/contao-console' 'cache:clear' '--env=prod' '--no-warmup' 2>&1


 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  


# Process terminated with exit code 0
# Result: OK


$ /opt/RZphp72/bin/php-cli '-q' '-d' 'max_execution_time=300' '/mnt/web221/e3/75/54138075/htdocs/contao4/vendor/contao/manager-bundle/bin/contao-console' 'cache:warmup' '--env=prod' 2>&1


 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

14:42:48 ERROR     [console] Error thrown while running command "cache:warmup --env=prod". Message: "RecursiveDirectoryIterator::__construct(/mnt/web221/e3/75/54138075/htdocs/contao4/vendor/bugbuster/contao-grid_16-bundle/src/Resources/contao/languages/de): failed to open dir: Too many open files" ["exception" => UnexpectedValueException { …},"command" => "cache:warmup --env=prod","message" => "RecursiveDirectoryIterator::__construct(/mnt/web221/e3/75/54138075/htdocs/contao4/vendor/bugbuster/contao-grid_16-bundle/src/Resources/contao/languages/de): failed to open dir: Too many open files"]

In RecursiveDirectoryIterator.php line 48:
                                                                               
  RecursiveDirectoryIterator::__construct(/mnt/web221/e3/75/54138075/htdocs/c  
  ontao4/vendor/bugbuster/contao-grid_16-bundle/src/Resources/contao/language  
  s/de): failed to open dir: Too many open files                               
                                                                               

cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>


# Process terminated with exit code 1
# Result: General error


---

### The background task has stopped unexpectedly ###
```

Woran kann es liegen?

**Comment by Toflar** [comment]
Sounds like a server issue to me. The server tells you: `Too many open files`.
Every OS only allows to open a certain number of files (or sockets/handles for that matter). It might be that this number is way too low. It also depends on how the system is virtualized.
Can you try running `ulimit -n` on the console and tell us the output?

**Comment by jankout** [comment]
Ich kann nichts mit der Konsole machen, weil ich nicht den entsprechenden Zugang habe. Die ganze Installation läuft über CM.

**Comment by Toflar** [comment]
Dann musst du wohl den Support bitten, das für dich zu tun. Ich gehe davon aus, dass dieses Limit einfach viel zu tief ist.

**Comment by jankout** [comment]
Danke für den Tipp. Kannst du mir bitte schreiben, was ich ihnen konkret sagen soll? Memorylimit erhöhen? Danke.

**Comment by jankout** [comment]
@Toflar Danke. Ich habe den Kundenservice kontaktiert. Sobald sie sich bei mir gemeldet haben, gebe ich euch Bescheid.

**Comment by jankout** [comment]
@Toflar Danke. Ich habe den Kundenservice kontaktiert. Sobald sie sich bei mir gemeldet haben, gebe ich euch Bescheid.

**Comment by jankout** [comment]
Leider sind die gar nicht entgegenkommend und wollen nichts ändern. Kann ich noch etwas in die _**php.ini**_ schreiben?

**Comment by fritzmg** [comment]
@jankout hast du viele Dateien im `/templates` Ordner?

**Comment by jankout** [comment]
@fritzmg es passiert mit Erweiterungen, die 2 oder mehr Ordner installieren, wie eure Mailchimp-Erweiterung. Bei der Installation war egal, ob schon eigene Templates waren oder nicht. Meine Lösung ist einfach: Ich werde den Kunden zu einem besseren Anbieter bringen.

**Comment by aschempp** [comment]
Ich denke nicht dass der Manager da etwas tun kann, und die Meldung kommt auch eigentlich von Contao (von der Konsole). Ich schliesse das mal, wir können es bei neuen Erkenntnissen natürlich gerne wieder öffnen.
