### ISSUE TITLE
CM 1.1.2 on uberspace only runs in safe mode

### ISSUE THREAD

**Issue by Aybee** [contao/contao-manager#395]
Die Systemprüfung wirft immer diese Meldung hier aus:

![bildschirmfoto am 2019-01-23 um 13 45 18](https://user-images.githubusercontent.com/1143013/51607676-a71d4b80-1f15-11e9-919b-0bfb609018e2.png)

Die "Automatische Reparatur" bleibt erfolglos.

Hier die Ansicht der Systemwartung:

![bildschirmfoto am 2019-01-23 um 13 51 19](https://user-images.githubusercontent.com/1143013/51607820-1135f080-1f16-11e9-9a0c-d718c2791e77.png)

Ich hatte Contao LTS 4.4.33 installiert, welches auch zu laufen scheint und konnte auch eine Erweiterung installieren.

Liegt das jetzt an mir, Contao oder dem Manager?

**Comment by aschempp** [comment]
Es scheint als funktioniert dein Contao auf der Kommandozeile nicht. Die Bilder helfen dabei aber nicht wirklich weiter. Kannst du mal sehen welche Ausgabe du per SSH bei `vendor/bin/contao-console` bekommst?

**Comment by Aybee** [comment]
Bitteschön
```
Failed loading /package/host/localhost/php-5.6.21/lib/php/extensions/no-debug-non-zts-20131226/opcache.so:  /package/host/localhost/php-5.6.21/lib/php/extensions/no-debug-non-zts-20131226/opcache.so: undefined symbol: zend_opcode_handlers
Symfony 3.4.21 (kernel: app, env: prod, debug: false)

Usage:
...
```

**Comment by aschempp** [comment]
Das liegt wohl daran dass dein PHP falsch konfiguriert ist und eine Warnung ausgibt. Die solltest du beheben – in der nächsten Version versucht der Manager sie zu ignorieren: 9b088c804919533dc05f8f0df05c4e0dc454193c

**Comment by Aybee** [comment]
Ich danke dir. Also Mail an Support von Uberspace? Weil Uberspace benutzen doch bestimmt so einige, da sollte die default Konfiguration eigentlich für Contao 4 passen, denke ich. Ist auf **Uberspace 6**.

**Comment by Toflar** [comment]
Ja, das Modul wird nicht korrekt eingebunden. Aber wer nutzt noch PHP 5.6? Deswegen ist das wohl keinem aufgefallen :)

**Comment by Aybee** [comment]
Im FE läuft PHP 7.2.13 und das hier bekomme ich auf der Konsole
```
$ php -v
Failed loading /package/host/localhost/php-5.6.21/lib/php/extensions/no-debug-non-zts-20131226/opcache.so:  /package/host/localhost/php-5.6.21/lib/php/extensions/no-debug-non-zts-20131226/opcache.so: undefined symbol: zend_opcode_handlers
PHP 7.2.13 (cli) (built: Dec 11 2018 17:05:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by xchs** [comment]
Auf meinem U6 Host erhalte ich

```console
$ php -v
PHP 7.2.13 (cli) (built: Dec 11 2018 17:05:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies
```

Vielleicht ist mit Deinem Uberspace irgendetwas nicht in Ordnung.

**Comment by Aybee** [comment]
Bin auch auf Uberspace 6. `[dav@capella ~]$`

Werde die Tage mal den Support kontaktieren.
