### ISSUE TITLE
(solved) Pb to launch Install tool at the end of contao-manager install with Gandi.net Simplehosting

### ISSUE THREAD

**Issue by JLBA** [contao/contao-manager#398]
**Affected version(s)**
Contao 4.4 or 4.7 - Contao-manager 1.3

**Description**  
I'm trying to install Contao 4.4 with contao-manager on gandi.net Simplehosting. 
DocumentRoot is vhosts/my.domain.ext/htdocs.
I add inside /web/contao-manager.phar.php 
In host list I choose other and all prerequired are ok. 
But at the end of files download, impossible to launch Install tool event if I specify my.domain.ext/web/contao/intall

Gandi's HL says it's not possible to modify DocumentRoot so I should use htdocs/ instead of htdocs/web directory. Is it possible ? Or do I need to use a htaccess for url rewriting like with Contao 3.5 ?

**How to reproduce**  
I can create a test host if needed.

Thanks for help.

**Comment by xchs** [comment]
You might want to set a symlink for the DocumentRoot if you have shell access.

However, it would still be much better if you could specify the DocumentRoot of the domain.

**Comment by JLBA** [comment]
Thanks xchs.
How can I do the symlink ?

**Comment by xchs** [comment]
`ln -s htdocs/web htdocs`

**Comment by JLBA** [comment]
ok.
Could url rewrite in .htaccess be a solution too (as with former Contao 3.x.x) ?

**Comment by JLBA** [comment]
I tried with symlink in /htdocs and in htdocs/web but this worked no more.
When I type directly : my.domain.ext/web/contao/install/ I'm redirected to my.domain.ext/web/contao/login with a blank page.

**Comment by xchs** [comment]
The topic with the symlink is also described here: https://lab.uberspace.de/guide_contao.html#installation
Basically the same thing as in your case.

**Comment by JLBA** [comment]
1. The path is vhosts/mydomain.ext/**htdocs**/web (htdocs is default DocumentRoot). 
Where do I need to create the symlink ?

2. I've read the guide but dosen't urderstand more. They say : 

> Since Contao uses the subdirectory web/ as web root of your website you should not install Contao in your default Uberspace DocumentRoot. Instead, we install it **next** to that and then use a symlink to make it accessible to the web.

Does this mean I have to create mydomain.ext/web/ instead of mydomain.ext/htdocs/web/ ?
Then where to put the symlink too ?

3. Gandi's HL suggests I install Contao in htdocs/ instead of htdocs/web and change the parameter in Contao. Possible ? Good idea ?

4. Could contao-manager create itself the symlink when needed ?

**Comment by xchs** [comment]
> 1. The path is vhosts/mydomain.ext/**htdocs**/web (htdocs is default DocumentRoot).
>    Where do I need to create the symlink ?

* Rename your `htdocs` folder to e.g. `cms`
* Create a symlink in `vhosts/mydomain.ext/`:
```console
ln -s cms/web/ htdocs
```

**Comment by JLBA** [comment]
This works !! Many thanks

Last question : Do I need to create the symlink before to create the 
web/ directory. It seems that when I first created web/ I had an error 
like "impossible to create symlink, file does exist".

Le 24/02/2019 à 21:55, Hannes a écrit :

**Comment by xchs** [comment]
> Do I need to create the symlink before to create the web/ directory.

I would do it like this:

* Rename `htdocs` to `cms` (`vhosts/mydomain.ext/htdocs/` --> `vhosts/mydomain.ext/cms/`). Make sure that `vhosts/mydomain.ext/cms/` is empty.
* Create a new subfolder `web` in `vhosts/mydomain.ext/cms/`
* Create the symlink in `vhosts/mydomain.ext/`: `ln -s cms/web/ htdocs`
* Download the `contao-manager.phar`, put it into the `vhosts/mydomain.ext/cms/web/` subfolder and rename it to `contao-manager.phar.php`
* Run the Contao Manager (`https://mydomain.ext/contao-manager.phar.php`) and install Contao

**Comment by JLBA** [comment]
OK.

In facts, I tested again with /web created first and had no error. The 
error was probably because /htdocs was first created and this couldn't 
be a directory and the symlink with the same name.

Thanks again and have a good night ;-

Le 24/02/2019 à 22:43, Hannes a écrit :
