### ISSUE TITLE
Contao Version Supported

### ISSUE THREAD

**Issue by katgirl** [contao/contao-manager#399]
In https://github.com/contao/contao-manager/blob/aa8859726f4e297e6f186d143a9d91c22814cb98/api/Controller/Server/ContaoController.php#L136
wird geprüft, welche Version noch supported ist. Hier sollte auch der Release-Plan ran gezogen werden, sonst täuscht das z.B. vor das die 4.6 noch supported ist.

**Comment by aschempp** [comment]
Inwiefern sollte das etwas vortäuschen? Die Ausgabe sieht man ja nirgends?

**Comment by katgirl** [comment]
ich habe das zur abfrage ob die Version noch aktuell ist genutzt, daher werden mir alle 4.6.14 als aktuell angezeigt, obwohl ja die 4.7.1 bereits draußen ist und ich ein Upgrade machen müsste.

**Comment by aschempp** [comment]
Wenn ich dich richtig verstehe verwendest du die API des Managers? Das entsprechende Feld sagt nicht aus ob die Contao-Version noch supported ist, sondern ob der Manager diese Contao-Version supported…

**Comment by aschempp** [comment]
Vor der 4.3.5 gab es keine Managed Edition 😉

**Comment by katgirl** [comment]
OK, dann habe ich das an der Stelle falsch verstanden, gibt es denn einen Wert zum prüfen ob Contao selbst noch Updates bekommt

**Comment by aschempp** [comment]
Nein, und mit dem Manager hätte das ja auch nichts zu tun.
