### ISSUE TITLE
Make PHAR work

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#40]
The phar compilation currently does not work, and is not documented.

 1. Make sure the phar works exactly the same as the without phar
 2. Write a documentation (e.g. PHAR.md in root) how to compile the application

The Phar does not need to be optimized for now (e.g. #20)

**Comment by discordier** [comment]
Works for me with a474525b6543.
Problem was that @Toflar forgot to install the translation and assets components when defining resources in these "well known" folders and symfony 3 now complains if these folders are present but the handling components are not installed.

**Comment by discordier** [comment]
Documentation issue still stands however, therefore I leave this open.

**Comment by aschempp** [comment]
Can you please add documentation so I can create the PHAR myself as well?
