### ISSUE TITLE
lead excel-Ausgabe

### ISSUE THREAD

**Issue by baslerbikes** [contao/contao-manager#402]
Ich möchte gern mit leads eine Exceltabelle ausgeben. Leads empfiehlt "phpexcel". Das taucht aber im ContaoManager nicht mehr auf. Leider genauso wenig wie die von "phpexcel" selbst bevorzugt empfohlene "phpspreadsheet" als Nachfolger.

Ich ärgere mich gerade über Abstürze bei manueller Installation per composer. Zum einen weil ich als Gelegenheitsnutzer ständig irgendwo "hängenbleibe" und mir jeden Schritt im Forum und  Google erarbeiten muss und dann dennoch der Prozess "gekilled" wird. Das ist unbefriedigend.

Spooky meinte ich solle ein Ticket aufmachen um die Installation über den Manager anzuregen. Er geht davon aus, dass auch phpexcel noch funktioniert. 

https://community.contao.org/de/showthread.php?70630-Contao-Leads-mit-PhpSpreadsheet&p=497660#post497660

**Comment by fritzmg** [comment]
Nein, mein Punkt war, dass der Contao Manager vermutlich keine als _abandoned_ markierte Pakete im Suchergebnis anzeigt, wie es eben _phpoffice/phpexcel_ eines ist. _phpoffice/phpexcel_ wird allerdings weiterhin noch für Extensions wie _terminal42/contao-leads_ benötigt - daher meine Anregung auf GitHub zu disktuieren, ob der Contao Manager tatsächlich _abandoned_ Projekte nicht mehr anzeigen soll - oder doch nicht.

**Comment by aschempp** [comment]
Der Manager zeigt `phpoffice/phpexcel` nicht an, weil es sich um kein Contao-Paket handelt. Die empfohlenen Pakete wollen wir in einer zukünftigen Version anzeigen: https://github.com/contao/contao-manager/issues/23

Zur Zeit kannst du dir damit behelfen dass du das requirement manuell in deine `composer.json` einträgst und danach über den Manager (neu laden!) eine Installation machst.
