### ISSUE TITLE
Contao 4.7 contao/install - 404 Not Found

### ISSUE THREAD

**Issue by andreaszaugg** [contao/contao-manager#403]
Trotz Installation mit Contao Manager 1.1.3 kann das Verzeichnis contao/install nicht aufgerufen werden. Das Verzeichnis existiert auf den Server nicht.

**Comment by fritzmg** [comment]
Please use the support forum for these kinds of questions.

**Comment by andreaszaugg** [comment]
> Please use the support forum for these kinds of questions.

I don't find support forum!

**Comment by fritzmg** [comment]
> I don't find support forum!

* https://community.contao.org/en/
* https://community.contao.org/de/
