### ISSUE TITLE
Version request returned incorrectly formatted response.

### ISSUE THREAD

**Issue by Acta2000** [contao/contao-manager#404]
Trying to get CM worked on XAMPP 7.2.15 / Windows Server 2016

STATUS:
PHP Webprozess OK
SerberKonfiguration OK
PHP Kommandozeilen-Programm OK
Updates für den Contao Manager

```
Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] request.INFO: Matched route "contao_managerapi_server_selfupdate__invoke". {"route":"contao_managerapi_server_selfupdate__invoke","route_parameters":{"_controller":"Contao\\\\ManagerApi\\\\Controller\\\\Server\\\\SelfUpdateController","_route":"contao_managerapi_server_selfupdate__invoke"},"request_uri":"http://localhost/contao4/web/contao-manager.php/api/server/self-update?_locale=de","method":"GET"} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":2} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\\\Component\\\\Security\\\\Guard\\\\Token\\\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\\"contaosvc\\", authenticated=true, roles=\\"\\"))","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\TokenAuthenticator"} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:56:02] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\TokenAuthenticator"} [], referer: http://localhost/contao4/web/contao-manager.php/
[Tue Mar 05 11:57:27.095750 2019] [php7:notice] [pid 2340:tid 1844] [client ::1:52306] [2019-03-05 11:57:27] app.CRITICAL: Uncaught PHP Exception RuntimeException: "Version request returned incorrectly formatted response." at phar://D:/htdocs/contao4/web/contao-manager.php/api/System/SelfUpdate.php line 234 {"exception":"[object] (RuntimeException(code: 0): Version request returned incorrectly formatted response. at phar://D:/htdocs/contao4/web/contao-manager.php/api/System/SelfUpdate.php:234)"} [], referer: http://localhost/contao4/web/contao-manager.php/
```

If i try to self-update with cmd:
```
D:\htdocs\contao4\web>php contao-manager.phar.php self-update

In SelfUpdate.php line 234:

  Version request returned incorrectly formatted response.


self-update
```

**Comment by aschempp** [comment]
Looks like something on your server is blocking the request. What do you get when downloading https://download.contao.org/contao-manager/stable/contao-manager.version ?

**Comment by Acta2000** [comment]
```{"version":"1.1.3","sha1":"916a5784ed37ba889e81c70648230cdbbe5ae993","requires":{"php":"^5.5.9 || ^7"}}
```

**Comment by Toflar** [comment]
Just to be sure: You didn't just click on that link, did you? You have to get it from the server in question using e.g. `wget` or `curl`.

**Comment by mkonline** [comment]
Hi,
ich bekomme die gleichen Fehler, wenn ich den cobntao-manager über das Web-Interface aufrufe. 
wget der URL (oben) auf der Console:`{"version":"1.1.3","sha1":"916a5784ed37ba889e81c70648230cdbbe5ae993","requires":{"php":"^5.5.9 || ^7"}}`

Contao-Manager bricht beim Versuch des Updates (Update für den Contao Manager) ab:
"ERROR 500 Version request returned incorrectly formatted response."

**Comment by Acta2000** [comment]
`D:\Programme\wget>wget https://download.contao.org/contao-manager/stable/contao-manager.version -e https_proxy=http://xxx --proxy-user=xxx --proxy-passwd=xxxx -v --debug
DEBUG output created by Wget 1.20 on mingw32.

Reading HSTS entries from D:\Programme\wget/.wget-hsts
URI encoding = 'CP1252'
converted 'https://download.contao.org/contao-manager/stable/contao-manager.version' (CP1252) -> 'https://download.contao.org/contao-manager/stable/contao-manager.version' (UTF-8)
URI encoding = 'CP1252'
Converted file name 'contao-manager.version' (UTF-8) -> 'contao-manager.version' (CP1252)
--2019-03-07 14:45:45--  https://download.contao.org/contao-manager/stable/contao-manager.version
seconds 0,00, Connecting to 172.17.1.14:3128... seconds 0,00, connected.
Created socket 3.
Releasing 0x0000000000b3bc20 (new refcount 0).
Deleting unused 0x0000000000b3bc20.

---request begin---
CONNECT download.contao.org:443 HTTP/1.1
User-Agent: Wget/1.20 (mingw32)
Proxy-Authorization: Basic QmFyZy5TOkFudGplMDEyMDE5TWlh
Host: download.contao.org:443

---request end---
proxy responded with: [HTTP/1.1 200 Connection established
Proxy-Connection: keep-alive

]
Initiating SSL handshake.
seconds 900,00, Winsock error: 0
Handshake successful; connected socket 3 to SSL handle 0x0000000000b3c980
certificate:
  subject: CN=sni201978.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
  issuer:  CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
X509 certificate successfully verified and matches host download.contao.org

---request begin---
GET /contao-manager/stable/contao-manager.version HTTP/1.1
User-Agent: Wget/1.20 (mingw32)
Accept: */*
Accept-Encoding: identity
Host: download.contao.org
Connection: Keep-Alive
Proxy-Connection: Keep-Alive

---request end---
Proxy request sent, awaiting response... seconds 900,00, Winsock error: 0
seconds 900,00, Winsock error: 0

---response begin---
HTTP/1.1 200 OK
Date: Thu, 07 Mar 2019 13:45:45 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 103
Connection: keep-alive
Set-Cookie: __cfduid=d934b1bd0289b656840ce10e9479b9fe41551966345; expires=Fri, 06-Mar-20 13:45:45 GMT; path=/; domain=.contao.org; HttpOnly
Last-Modified: Sat, 16 Feb 2019 17:44:00 GMT
ETag: "5c684be0-67"
Cache-Control: s-maxage=10
Accept-Ranges: bytes
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 4b3d02fbd811c4ba-DUS

---response end---
200 OK
cdm: 1

Stored cookie contao.org -1 (ANY) / <permanent> <insecure> [expiry 2020-03-06 14:45:45] __cfduid d934b1bd0289b656840ce10e9479b9fe41551966345
Registered socket 3 for persistent reuse.
URI content encoding = 'utf-8'
Length: 103 [text/plain]
Saving to: 'contao-manager.version.1'

contao-manager.version.1        0%[                                                  ]       0  --.-KB/s               seconds 900,00, Winsock error: 0
contao-manager.version.1      100%[=================================================>]     103  --.-KB/s    in 0,008s

2019-03-07 14:45:45 (12,7 KB/s) - 'contao-manager.version' saved [103/103]


D:\Programme\wget>`

**Comment by Acta2000** [comment]
I set up the environment variable HTTP_PROXY

I can install Contao and Addons using CMD comands like:
composer create-project and composer require

**Comment by aschempp** [comment]
Dann liegt das Problem wohl daran dass der Contao Manager beim Update keine Proxy-Einstellungen liest…

**Comment by Acta2000** [comment]
Kann ich das irgendwie erzwingen, einstellen oder irgendwas in irgend ne config schreiben damit er das tut?

**Comment by aschempp** [comment]
Es wird `file_get_contents` verwendet (https://github.com/contao/contao-manager/blob/master/api/System/SelfUpdate.php#L267), ich weiss allerdings nicht ob PHP nativ Proxys kann

**Comment by Toflar** [comment]
Kann es. Der dritte Parameter bei `file_get_contents` erlaubt die Übergabe eines Contexts. Da kannst du einen Streamcontext übergeben. Aber können wir nicht die `RemoteFilesystem` von Composer wiederverwenden?

**Comment by ReneLuecking** [comment]
Ist das nicht dasselbe Problem wie in #310? Das heißt wenn man `RemoteFilesystem` verwendet und `$_SERVER['CGI_HTTP_PROXY']` gesetzt ist, sollte es funktionieren.

**Comment by aschempp** [comment]
Theoretisch… Aber `RemoteFilesystem` kommt aus Composer, ich weiss nicht ob wir das für unsere eigenen Anwendungen nutzen können.

**Comment by mkonline** [comment]
Bei mir ist die CGI_HTTP_PROXY vorhanden (gesetzt in der root des vHost, Ausgabe phpinfo im /web), das System zeigt das gleiche Verhalte wie vorher, auch wird die Installierte Instanz von Contao vom Manager nicht erkannt.

**Comment by aschempp** [comment]
> auch wird die Installierte Instanz von Contao vom Manager nicht erkannt.

Das scheint aber wenig mit diesem Issue zu tun zu haben?

**Comment by ReneLuecking** [comment]
> Aber RemoteFilesystem kommt aus Composer, ich weiss nicht ob wir das für unsere eigenen Anwendungen nutzen können.

Zumindest Lizenztechnisch wäre das kein Problem. Composer ist ja unter der MIT-Lizenz veröffentlicht

**Comment by aschempp** [comment]
The Contao Manager now uses the proxy configuration everywhere (see c5deefd7483fe7fdf72084b1a3fed8497b167b54)

**Comment by Acta2000** [comment]
Wird die Änderung in einer neuen contao-manager-phar auf Contao.org zur Verfügung stehen?

**Comment by Toflar** [comment]
Ist sie schon. Der Manager aktualisiert sich automatisch beim Einloggen.

**Comment by Acta2000** [comment]
Setzt voraus, das der Manager ins Internet kann -> Die Proxyänderungen greifen aber erst mit 1.1.4. Beim Aufruf des Managers wird bei nach wie vor 1.1.3 angezeigt.

**Comment by Toflar** [comment]
Ach so, ja du kannst ja auch manuell downloaden.

**Comment by Acta2000** [comment]
Und müsste dann via tool zu einer phar datei zusammenstellen richtig?

**Comment by aschempp** [comment]
Dann musst du manuell von contao.org herunterladen und installieren.

**Comment by Acta2000** [comment]
Ich habe den Contao-Manager neu über Contao.org gedownloadet.

Den Web Ordner und den darüberliegenden Ordner geleert und die Contao-manager.phar in den Ordner web abgelegt. Die Datei um die Endung .php erweitert. 

Domain aufgerufnen -> contao manager zeigt unten Version 1.1.3 an.

Was mach ich falsch?

**Comment by contaoacademy** [comment]
Hab es gerade auch getestet. Bei mir wurde die 1.1.4 geladen.

**Comment by Acta2000** [comment]
Nach dem ich statt Firefox, den Chrome genommen habe zum Download der Phar... hat es geklappt... Scheinbar ein internes Cache Problem. 

Im IE startet der Manager nicht -> ? Statuszeile zeigt 1.1.4  der Rest der Website bleibt leer

-> Im Firefox läuft er.

Aber bei Updates für den Contao Manager kommt wieder:
Version request returned incorrectly formatted response.

**Comment by Acta2000** [comment]
Ich nutze die PHP umgebungsvariable um via Composer Contao manuell zu installieren (funktioniert)

Wenn ich  aschempp richtig verstanden habe, greift der Contao Manager nun auch auf diese Umgebungsvariable zu?

**Comment by aschempp** [comment]
Hast du `CGI_HTTP_PROXY` auch gesetzt?

**Comment by Acta2000** [comment]
Als Umgebungsvariable ja!

**Comment by Acta2000** [comment]
Also nochmal zu nachverfolgen:

- Ich habe in den Umgebungsvariablen sowohl den http_proxy als auch den CGI_HTTP_PROXY gesetzt. 
- Contao Manager in Version 1.1.4 in Verwendung (im IE funktioniert dieser nicht-> nur graue seite)

Was habe ich versucht:

1. Contao Manager geöffnet und geschaut ob es eine Änderung gibt -> immernoch Version request Meldung nach 3 Minuten (max_execution_time liegt bei ca. 5 Minuten)  
2. CMD geöffnet -> set CGI_HTTP_PROXY ausgeführt -> php contao-manager-phar.php self-update -> Version request returned incoccrectly formatted response
3. in Ordner Web eine .htaccess angelegt

```
<IfModule mod_env.c>
    SetEnv CGI_HTTP_PROXY http://BN:PW@PROXYIP:PORT
</IfModule>
```
hinterlegt. Contao Manager aufgerufen -> "Version request returned incorrectly formatted response." erscheint nun nach ca. 5 Sekunden statt 3 Minuten

-> .htaccess inhalt wieder gelöscht -> CM aufgerufen -> "Version request returned incorrectly formatted response." nach ca. 3 Minuten

**Comment by ReneLuecking** [comment]
In einer VM mit einer frischen LAMP-Installation (Ubuntu 18.04, Apache 2.4, MySQL 5.7, PHP 7.2) konnte ich Contao mit dem Manager Version 1.1.4 erfolgreich installieren. Als Browser habe ich Chrome benutzt. Den Proxy habe ich im vHost wie folgt gesetzt:

    SetEnv CGI_HTTP_PROXY http://proxy.example.com:port

Die Installation eines zusätzlichen Paketes (Rocksolid Custom Elements) hat ebenfalls funktioniert.

**Comment by Acta2000** [comment]
Alles sehr kurios.
Ich verwende hier einen Windows Server 2016 mit Apache 2.4,, PHP 7.2. und Mysqli 5

Erstaunlich finde ich, dass wenn ich den CGI zusätzlich in der .htaccess eintrage, die Fehlermeldung nach wenigen Sekunden erscheint.

Noch weniger logisch für mich ist, dass ich Contao + einige Erweiterungen ohne den CM via Composer installieren kann. Mit dem Windowsinstaller des Composers wurde die Path-Variable für http_proxy gesetzt. Auf diese greift der Composer zu.

**Comment by Acta2000** [comment]
Habe die CGI_HTTP_PROXY zum test in den Vhost hinterlegt -> gleiches Ergebnis wie bei Hinterlegung in der .htaccess

Der Apache log sagt:

```
Wed Mar 13 12:47:21.906165 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] request.INFO: Matched route "contao_managerapi_server_selfupdate__invoke". {"route":"contao_managerapi_server_selfupdate__invoke","route_parameters":{"_controller":"Contao\\\\ManagerApi\\\\Controller\\\\Server\\\\SelfUpdateController","_route":"contao_managerapi_server_selfupdate__invoke"},"request_uri":"http://contao4.local/contao-manager.phar.php/api/server/self-update?_locale=de","method":"GET"} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.906165 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":2} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.906165 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.921790 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.921790 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.921790 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\\\Component\\\\Security\\\\Guard\\\\Token\\\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\\"XXX\\", authenticated=true, roles=\\"\\"))","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.921790 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.921790 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.921790 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\TokenAuthenticator"} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.921790 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\TokenAuthenticator"} [], referer: http://contao4.local/contao-manager.phar.php/
[Wed Mar 13 12:47:21.921790 2019] [php7:notice] [pid 2800:tid 1848] [client 127.0.0.1:58242] [2019-03-13 12:47:21] app.CRITICAL: Uncaught PHP Exception RuntimeException: "Version request returned incorrectly formatted response." at phar://D:/htdocs/contao4/web/contao-manager.phar.php/api/System/SelfUpdate.php line 240 {"exception":"[object] (RuntimeException(code: 0): Version request returned incorrectly formatted response. at phar://D:/htdocs/contao4/web/contao-manager.phar.php/api/System/SelfUpdate.php:240)"} [], referer: http://contao4.local/contao-manager.phar.php/

```

**Comment by pswerbung** [comment]
Habe auch einen ERROR 500 Version request returned incorrectly formatted response bekommen bei allen Installationen mit Manager Version 1.1.3 (verschiedene Provider). Sobald ich den neuesten Manager lade (aktuell 1.1.4) und im Ordner /web platziere, fährt der Manager wieder hoch. Somit ist es gefixtaber die Version 1.1.3 kann nicht automatisch updaten ohne Eingriff … richtig?

**Comment by aschempp** [comment]
Der Fehler wurde auf dem Update-Server behoben.
