### ISSUE TITLE
Abgesicherter Modus trotz funktionierender Installation

### ISSUE THREAD

**Issue by SGehle** [contao/contao-manager#406]
Trotz einer funktionierenden Contao-Version wird mir beim Aufruf des Managers der abgesicherte Modus vorgeschlagen. Manager Version 1.1.3.
Evtl hat es mit den Fehlermeldungen in der Konsole zutun - jedoch konnte ich keine Probleme bei der Nutzung des Managers feststellen.

MIB search path: /var/www/vhosts/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp
Cannot find module (SNMPv2-TC): At line 10 in /usr/share/snmp/mibs/UCD-DLMOD-MIB.txt

**Comment by aschempp** [comment]
Ja, der Manager funktioniert nur wenn die Konsole (ohne Fehlermeldung) funktioniert.
