### ISSUE TITLE
Contao manager try to load file /contao-manager/users.json which does not exist

### ISSUE THREAD

**Issue by dmolineus** [contao/contao-manager#408]
This issue is highly related to #383. In a current installation the `/contao-manager/` directory is created in the project root directory and not in the `web` directory.

As @aschempp described [here](https://github.com/contao/contao-manager/issues/383#issuecomment-451744407), the behaviour is described as follow:

> That is correct, it will be installed in the same folder as the Phar, except if the parent folder is web.

That's causes the issue in my current case. At timme hosting the project directory /parent directory is also named `web` by default. Shouldn't the contao manager check if the public folder is named `web` instead of checking the parent?

**Comment by aschempp** [comment]
How would you know the difference? And if that's the case, you always have `web/web`, so that should not be a problem with the manager?

**Comment by aschempp** [comment]
Any ideas?

**Comment by leofeyer** [comment]
> Shouldn't the contao manager check if the public folder is named `web` instead of checking the parent?

I doubt that there is a reliable way to do this. We could check `$_SERVER['DOCUMENT_ROOT']`, however, there is no guarantee that it points to the real document root.

**Comment by aschempp** [comment]
Well that wouldn't really help, would it? The document root will point to web folder in the project directory nonetheless. And technically it's totally fine to install Contao into that folder, if the parent is writeable.

**Comment by leofeyer** [comment]
It would be a "don't install into the parent folder if the current folder is the document root" check.

**Comment by aschempp** [comment]
The current folder is (or should always be) the document root. The document root should point to `web` within your installation directory...

**Comment by leofeyer** [comment]
You are right. Then this is not possible.

**Comment by aschempp** [comment]
The only option I can imagine would be something like adding this information to the server list… which kinda sucks to be honest…
