### ISSUE TITLE
easyphp This path does not contain a valid PHP binary

### ISSUE THREAD

**Issue by DVeris** [contao/contao-manager#409]
Configuration: Other ...

PHP Binary
C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-binaries\php\php704vc14x86x160918120644\php.exe

error: This path does not contain a valid PHP binary

but it valid path...

ps
easyphp devserver

**Comment by DVeris** [comment]
i think problem in path
because
when i install easyphp devserver in D:\myserver\

problem is gone

**Comment by aschempp** [comment]
Do I assume correctly that this can be closed then?

**Comment by DVeris** [comment]
if it normal ? - yes
but C:\Program Files (x86)\ it is very popular path...

**Comment by aschempp** [comment]
well it's an issue with the path, probably with the whitespace or brackets. Unfortunately I don't use Windows, so I can't debug this. It would be great if you could debug this, but you would need to build your own dev version of the Contao Manager 😞

**Comment by aschempp** [comment]
This issue was closed because it has not had recent activity.
