### ISSUE TITLE
Allow to cancel a process

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#41]
It must be possible to cancel a task in the UI. Ideally that should also cancel the process.

Looking at the documentation (https://symfony.com/doc/current/components/process.html#running-processes-asynchronously) it should be possible to store the process ID between `$process->start()` and `$process->wait()`. Or handle cancellation in the `wait()` callback.

**Comment by discordier** [comment]
Again, as written in #42. The determination of the CURRENT pid is not the big problem and works most of the times.
The problem is fetching the LIST of running processes.

Handling the cancellation is already discussed in tenside/core-bundle#14

**Comment by aschempp** [comment]
Implemented in https://github.com/contao/contao-manager/commit/37bd0fb2f9eea5e16800b039908d357f092da448
