### ISSUE TITLE
This path does not contain a valid PHP binary. PHP installed from scratch on Windows

### ISSUE THREAD

**Issue by SeanDolan** [contao/contao-manager#411]
My php path is "c:\Data\PHP\php.exe". During the installation I select "Other.." and it still says the path is not valid. I am running on Windows Server 2016. I can execute "c:\Data\PHP\php.exe -v" within test.php file.

**Comment by ausi** [comment]
Please test if `c:\Data\PHP\php.exe -q c:\PATH\TO\CONTAO\web\contao-manager.phar.php test` works and if so, post the output of it here.

**Comment by SeanDolan** [comment]
Put that into my test.php file and got the following result:

Executing c:\Data\PHP\php.exe -q c:\Data\Apache\htdocs\website\web\contao-manager.phar.php ...

Contao Manager 1.1.4

Usage:
command [options] [arguments]

Options:
-h, --help Display this help message
-q, --quiet Do not output any message
-V, --version Display this application version
--ansi Force ANSI output
--no-ansi Disable ANSI output
-n, --no-interaction Do not ask any interactive question
--disable-events Disables the event dispatcher.
-v|vv|vvv, --verbose Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
about Displays information about Contao Manager and the current server
composer Run Composer within Contao Manager
help Displays help for a command
integrity-check Performs integrity check for the Contao Manager
list Lists commands
run Execute a background task
self-update Updates Contao Manager to the latest version
task
task:abort Aborts the current task and returns the status information.
task:delete Deletes the current task if it is not active.
task:update Updates the current task and returns the status information.

**Comment by SeanDolan** [comment]
Went back into the installer and without me entering in a value, just selecting Other it came up with the correct address. The only thing different was the capitalisation on ".EXE". Ran with what was in there automatically and it worked.

**Comment by SeanDolan** [comment]
After getting through this part of the setup it directed me to an install path of /contao/install that could not be found. This is all too much trouble. Spent about 20 hours trying to get the software installed and it seems to have so many issues with a base install of Apache and PHP manually setup on Windows. Going to look at another CMS. Thanks for your time.
