### ISSUE TITLE
Contao-Manager 1.1.3 meldet Error 500

### ISSUE THREAD

**Issue by Schneetiger** [contao/contao-manager#412]
Hallo zusammen,

teste aktuell Contao 4.7.1 mit dem Contao-Manager 1.1.3. Nach erfolgreicher Anmeldung im CM erhalte ich nach einigen Sekunden einen abgedunkelten Bildschirm mit der Ausgabe einer Error 500-Meldung (Version request returned incorrectly formatted response) links oben. Beim Update des CM friert dieser dann ein (siehe beiliegenden Screenshot) und eine Überprüfung der Contao-Installation schlägt fehl. Eine Anmeldung im BE der Contao-Installation ist jedoch problemlos möglich.
![Screenshot_2019-03-22 Contao Manager 1 1 3](https://user-images.githubusercontent.com/29976466/54813109-19e44200-4c8d-11e9-869f-e69fa2105df4.png)

**Comment by bibib** [comment]
Das Problem habe ich auch gerade gehabt: [hier](https://community.contao.org/de/showthread.php?74402-ERROR-500-Version-request-returned-incorrectly-formatted-response)
Einfach die aktuelle Version des Managers runterladen und nach /web kopieren, dann geht's wieder.

**Comment by mlwebworker** [comment]
Ja hatte ich gestern auch. Einfach die neuste Version des Managers von contao.org herunterladen, auf den Webspace schieben alte Variante löschen, neue umbenennen (.php) und läuft.

**Comment by aschempp** [comment]
Der Fehler wurde auf dem Update-Server behoben.
