### ISSUE TITLE
ERROR 500 Unknown installation status 

### ISSUE THREAD

**Issue by RubyBadlands** [contao/contao-manager#413]
**Affected version(s)**
Contao Manager 1.1.4

**Description**  

I'm trying to install Contao with the Contao Manager, but in step 6 Contao-Installation "Die Prüfung ist aufgrund einer unerwarteten Serverantwort fehlgeschlagen" there is a mistake which results in an error screen:

> ERROR 500 Unknown installation status
> Some files were found on your server but no known Contao version could be detected.
> You must either manually repair your application or remove the following files and folders to install Contao:
> 
>  - contao-manager.phar.php
> 

Removing the file stops everything, installation fails.

How to proceed?

**Comment by xchs** [comment]
The Contao root installation directory must be empty. Move the `contao-manager.phar.php` into the `web/` subfolder, define this directory as the document root and run the Contao Manager again.

**Comment by RubyBadlands** [comment]
Thanks, but doesn't work.

**Comment by RubyBadlands** [comment]
Can I migrate an installation (Contao 4)  from one server to the other without the use of the Contao Manager?

**Comment by xchs** [comment]
Please refer to the [forums](https://community.contao.org/) and elaborate what you've done so far.
