### ISSUE TITLE
Contao-Manager 1.1.4 meldet Error 500

### ISSUE THREAD

**Issue by rodolfodicaino** [contao/contao-manager#414]
Hallo zusammen,

wollte heute Contao 4.4 LTS über CM 1.1.4 lokal auf XAMPP (Windows) installieren und erhalte denselben Fehler wie in #412 beschrieben. Der Fehler wurde also auf dem Update-Server zumindest nicht für alle Plattformen behoben. Ich teste noch bei 1&1.

**Comment by rodolfodicaino** [comment]
OK, der Test bei 1&1  hatte das Problem nicht, allerdings zunächst das:
![CM01](https://user-images.githubusercontent.com/49202698/55438415-ceda0100-55a1-11e9-814f-8f2fe75187bf.JPG)
Nach dem Neustart lief es dann irgendwie doch durch.

Das Problem bezgl. XAMPP bleibt offen und grundsätzlich macht mir Contao 4.x gegenüber der zuverlässigen und einfach handhabbaren Version 3.x keinen stabilen Eindruck. Würde das nicht veröffentlichen.

**Comment by aschempp** [comment]
Kannst du bitte das Konsoleprotokoll der 1&1-Fehlermeldung dazu posten? Ohne Protokoll lässt sich nicht herausfinden warum etwas nicht funktioniert.

**Comment by rodolfodicaino** [comment]
Hallo, bei 1&1 läuft alles - der anfängliche Fehler lässt sich nicht mehr reproduzieren!

Bleibt also die Einrichtung unter XAMPP (Windows):
![image](https://user-images.githubusercontent.com/49202698/55727139-9ad36580-5a11-11e9-8628-caf718ae64aa.png)

**Comment by xchs** [comment]
What output do you get by running
```
php -q C:\xampp\htdocs\[CONTAO-INSTALL-DIR]\web\contao-manager.phar.php test
```
(replace `[CONTAO-INSTALL-DIR]` with the folder name of your Contao installation)?

**Comment by rodolfodicaino** [comment]
Thank you, output is as follows:

# php -q D:\xampp\htdocs\pocoloco\web\contao-manager.phar.php test
{"version":"7.3.3","version_id":70303,"sapi":"cli"}
info@BERGBC09 d:\xampp

**Comment by Patric96** [comment]
Bei mir läuft es leider unter Xampp auch nicht mehr. 
Bekomme folgende Fehlermeldung: ERROR 500 Version request returned incorrectly formatted response.
Download des aktuellen CM hat nichts gebracht, Cookies und Cache wurden gelöscht

**Comment by aschempp** [comment]
Kann es sein dass eine Firewall auf deinem Computer die ausgehende Verbindung blockiert?

**Comment by Patric96** [comment]
Nein leider nicht, das habe ich schon getestet. Das Problem tritt auch erst seit kurzem und nur bei Xampp auf. Alte Contao Mangager lassen sich problemlos aufrufen.

**Comment by christian-schattat** [comment]
Bei mir lässt sich der Manager seit einigen Tagen lokal innerhalb einer Mac-Homebrew-Umgebung auch nicht mehr starten. Genauer gesagt bleibt er bei Schritt 4 _Updates für den Contao Manager_ hängen.

Im Terminal lässt sich soweit aber alles ausführen. Möglicherweise ist das hilfreich:

### php contao-manager.phar.php -V
`Contao Manager 1.1.4`

### php contao-manager.phar.php integrity-check
`Running PHP 7.2.19, all checks successful.`

### php contao-manager.phar.php self-update -v

**In UpdateCommand.php line 46:**

`[RuntimeException] Your server does not meet the requirements of the next Contao Manager version.`

**Exception trace:**

`() at phar:///[Pfad]/web/contao-manager.phar.php/api/Command/UpdateCommand.php:46`

`Contao\ManagerApi\Command\UpdateCommand->execute() at phar:///[Pfad]/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php:255`

`Symfony\Component\Console\Command\Command->run() at phar:///[Pfad]/web/contao-manager.phar.php/vendor/symfony/console/Application.php:960`

`Symfony\Component\Console\Application->doRunCommand() at phar:///[Pfad]/web/contao-manager.phar.php/vendor/symfony/console/Application.php:255`

`Symfony\Component\Console\Application->doRun() at phar:///[Pfad]/web/contao-manager.phar.php/api/ApiApplication.php:76`

`Contao\ManagerApi\ApiApplication->doRun() at phar:///[Pfad]/web/contao-manager.phar.php/vendor/symfony/console/Application.php:148`

`Symfony\Component\Console\Application->run() at phar:///[Pfad]/web/contao-manager.phar.php/api/console:84`

`require() at /[Pfad]/web/contao-manager.phar.php:54`

`self-update`

**Comment by dennis-sagasser** [comment]
Ich kann mich nur anschließen.

**php contao-manager.phar.php -V**
Contao Manager 1.1.4

**php contao-manager.phar.php integrity-check**
Running PHP 7.1.8, all checks successful.

**php contao-manager.phar.php self-update -v**

In SelfUpdate.php line 240:
                                                            
  [RuntimeException]                                        
  Version request returned incorrectly formatted response.  
                                                            

Exception trace:
 () at phar:///Applications/AMPPS/www/domain.local/web/contao-manager.phar.php/api/System/SelfUpdate.php:240
 Contao\ManagerApi\System\SelfUpdate->getRemoteInfo() at phar:///Applications/AMPPS/www/domain.local/web/contao-manager.phar.php/api/System/SelfUpdate.php:216
 Contao\ManagerApi\System\SelfUpdate->checkForUpdate() at phar:///Applications/AMPPS/www/domin.local/web/contao-manager.phar.php/api/System/SelfUpdate.php:74
 Contao\ManagerApi\System\SelfUpdate->supportsUpdate() at phar:///Applications/AMPPS/www/domain.local/web/contao-manager.phar.php/api/Command/UpdateCommand.php:45
 Contao\ManagerApi\Command\UpdateCommand->execute() at phar:///Applications/AMPPS/www/domain.local/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///Applications/AMPPS/www/domain.local/web/contao-manager.phar.php/vendor/symfony/console/Application.php:960
 Symfony\Component\Console\Application->doRunCommand() at phar:///Applications/AMPPS/www/domain.local/web/contao-manager.phar.php/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at phar:///Applications/AMPPS/www/domain.local/web/contao-manager.phar.php/api/ApiApplication.php:76
 Contao\ManagerApi\ApiApplication->doRun() at phar:///Applications/AMPPS/www/domain.local/web/contao-manager.phar.php/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at phar:///Applications/AMPPS/www/domain.local/web/contao-manager.phar.php/api/console:84
 require() at /Applications/AMPPS/www/domain.local/web/contao-manager.phar.php:54

self-update
![grafik](https://user-images.githubusercontent.com/8061288/59600932-e8034000-9102-11e9-8803-f0b3dfd8cdef.png)
![grafik](https://user-images.githubusercontent.com/8061288/59600956-f94c4c80-9102-11e9-97b6-64d772edb4cb.png)

**Comment by xchs** [comment]
Was liefert denn die Ausgabe von
```
php -v
```
bzw.
```
php -q [PATH-TO-INSTALLDIR]\web\contao-manager.phar.php test
```
?

**Comment by christian-schattat** [comment]
**php -v**
`PHP 7.2.19 (cli) (built: Jun  1 2019 00:03:09) ( NTS )`
`Copyright (c) 1997-2018 The PHP Group`
`Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.2.19, Copyright (c) 1999-2018, by Zend Technologies`

**php -q contao-manager.phar.php test**
`{"version":"7.2.19","version_id":70219,"sapi":"cli"}`

**Comment by fritzmg** [comment]
Statt `php` musst den konfigurierten PHP Pfad nehmen um das besser verifizieren zu können.

**Comment by christian-schattat** [comment]
**/usr/local/Cellar/php@7.2/7.2.19/bin/php -q contao-manager.phar.php test**
`{"version":"7.2.19","version_id":70219,"sapi":"cli"}`

**Comment by fritzmg** [comment]
Wir hatten mal den Fall, dass eine falsche Ausgabe der Konsolenoperationen nur über den Kontext des Web Servers erfolgte.

**Comment by aschempp** [comment]
Kann es sein dass die Option `allow_url_fopen` bei euch deaktiviert ist?
https://www.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen

**Comment by christian-schattat** [comment]
Gemäss Contao Check sieht es soweit gut aus:

<img width="780" alt="Bildschirmfoto 2019-06-19 um 10 47 47" src="https://user-images.githubusercontent.com/10039087/59750915-deebad80-927f-11e9-8d06-a782db673bc6.png">

`allow_url_fopen` ist gesetzt:

<img width="777" alt="Bildschirmfoto 2019-06-19 um 10 47 08" src="https://user-images.githubusercontent.com/10039087/59750961-f3c84100-927f-11e9-925d-a115565f0874.png">

Allerdings scheitert die Verbindung zu [contao.org](https://contao.org/de/):

<img width="778" alt="Bildschirmfoto 2019-06-19 um 10 48 14" src="https://user-images.githubusercontent.com/10039087/59750984-00e53000-9280-11e9-8b98-942c12a6c3c4.png">

(Randbemerkung: Die URL lässt sich jedoch auch über den Browser nicht öffnen.)

**Comment by aschempp** [comment]
Also besteht doch eine Blockierung der ausgehenden Verbindung...?

**Comment by dennis-sagasser** [comment]
Bei mir exakt das Gleiche. Ja, irgendwie kommt er nicht raus bzw. wenn er rauskommt, wird er abgewiesen. Was können wir tun, um das rauszufinden?

**Comment by aschempp** [comment]
Dieser Fehler sollte in der 1.1.5 behoben sein. Der Fehler tritt auf wenn der Webserver das SSL-Zertifikat nicht prüfen kann. Wir umgehen das jetzt durch einen eigenen Certificate Store.

**Comment by darkojic** [comment]
Hello, I am running contao-manager on shared hosting with PHP 7.2.20 and struggling with this error.

This is a part of error log, closely before and in the moment when error has occured.

`request.INFO: Matched route "contao_managerapi_server_selfupdate__invoke". {"route":"contao_managerapi_server_selfupdate__invoke","route_parameters":{"_controller":"Contao\\\\ManagerApi\\\\Controller\\\\Server\\\\SelfUpdateController","_route":"contao_managerapi_server_selfupdate__invoke"},"request_uri":"https://**********/contao-manager.phar.php/api/server/self-update?_locale=sr","method":"GET"} [], referer: https://***********/contao-manager.phar.php/

security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":2} [], referer: https://************/contao-manager.phar.php/

security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://**********/contao-manager.phar.php/

security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://********.org/contao-manager.phar.php/

security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://**********/contao-manager.phar.php/

security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\\\Component\\\\Security\\\\Guard\\\\Token\\\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\\"dkojic\\", authenticated=true, roles=\\"\\"))","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://****************/contao-manager.phar.php/

security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://***********/contao-manager.phar.php/

security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Contao\\\\ManagerApi\\\\Security\\\\JwtAuthenticator"} [], referer: https://***********/contao-manager.phar.php/

security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\TokenAuthenticator"} [], referer: https://*********/contao-manager.phar.php/

security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\\\ManagerApi\\\\Security\\\\TokenAuthenticator"} [], referer: https://*********/contao-manager.phar.php/

app.CRITICAL: Uncaught PHP Exception RuntimeException: "Version request returned incorrectly formatted response." at phar:///var/www/vhosts/*************/httpdocs/web/contao-manager.phar.php/api/System/SelfUpdate.php line 240 {"exception":"[object] (RuntimeException(code: 0): Version request returned incorrectly formatted response. at phar:///var/www/vhosts/*********/httpdocs/web/contao-manager.phar.php/api/System/SelfUpdate.php:240)"} [], referer: https://*********/contao-manager.phar.php/

`
