### ISSUE TITLE
Contao Fehler bei 1&1 IONOS

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao-manager#415]
Wenn ich Contao 4.7.2 über den Contao Manager installieren möchte, bricht der Download immer ab, siehe Bilder. gibt es da zur Zeit einen Fehler mit dem Contao Manager?
Wenn mir da jemand helfen kann, würde mich dieses sehr freuen.
![Contao1](https://user-images.githubusercontent.com/17680074/55516714-55f4ab00-566e-11e9-8d20-4bdabf45de3d.png)
![Contao2](https://user-images.githubusercontent.com/17680074/55516716-58570500-566e-11e9-8a86-9c2b49d4c4d6.png)

**Update: Im dritten Versuch hat es geklappt, werde es weiter beobachten.**

**Comment by aschempp** [comment]
Wenn du den Cloud Resolver benutzt, sollte die Installation mehrfach versucht werden bis alles heruntergeladen ist. Ich schliesse das aber mal, da es für dich ja funktioniert. Falls es reproduzierbar ist, können wir es gerne wieder öffnen.
