### ISSUE TITLE
CM does not find two packages of MM

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#417]
CM does not find two packages of MM

CM found 4
http://easycaptures.com/fs/uploaded/1195/8275255573.png

I miss

- https://packagist.org/packages/metamodels/bundle_all
- https://packagist.org/packages/metamodels/bundle_start

**Comment by dmolineus** [comment]
The problem here is that only packages of metapackages are required. Seems like the the package indexer only checks if a metapackage has contao modules/bundles on the first level. And it doesn't check if a sub metapackage is considered as supported.

**Comment by zonky2** [comment]
maybe it´s possible to support this feature

**Comment by Toflar** [comment]
That's correct. And I don't want to build a recursive logic there because it would end in a never-ending loop. But maybe we can support a second level sometime in the future but it won't happen anytime soon for sure.

**Comment by zonky2** [comment]
@Toflar I just try to add the package core as requirement, but that doesn't help to display the packages either...

https://github.com/MetaModels/bundle_all/blob/master/composer.json

The resolution of the dependencies is done by the composer anyway - why then the restriction with CM?

**Comment by Toflar** [comment]
It's done for the search index. It's not related to dependency resolution at all.
We filter for all the packages of type `contao-bundle` or meta packages that require at least one `contao-bundle`.

**Comment by zonky2** [comment]
> It's done for the search index. 

hmm... what do you mean by "done" - should it work like this or not?

**Comment by zonky2** [comment]
ok - now works...
