### ISSUE TITLE
Schließen nach Session-Ablauf geht nicht

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#418]
Schließen nach Session-Ablauf geht nicht - Button zeigt keine Reaktion

http://easycaptures.com/fs/uploaded/1200/2187331989.png

JS: 
```Unhandled promise rejection undefined chunk-vendors.cb15b9bc.js:9:10728```

**Comment by Funbug** [comment]
Kann ich bestätigen. Habe ich auch manchmal.

**Comment by aschempp** [comment]
Duplicate of #400
