### ISSUE TITLE
xammp/Contao/ error 500

### ISSUE THREAD

**Issue by jcontao** [contao/contao-manager#419]
Habe xampp auf Windows10 mit dem Contaomanager installiert und bekomme immer diese Fehlermeldung. siehe screenshot
Woran liegt das? 
Danke für Infos.

![Screenshot_2019-04-05 Contao Manager 1 1 4](https://user-images.githubusercontent.com/49510589/55935325-a43c1800-5c33-11e9-9edf-08a3fae410c4.png)

**Comment by contaoacademy** [comment]
Es sind Contao fremde Dateien und Ordner in deiner Installation. Das mag der Manager nicht.
Bitte Contao immer in einen eigenen leeren Ordner installieren.
Außerdem die Struktur einhalten.

Siehe auch: https://www.youtube.com/watch?v=GIgmdc1QJVA

**Comment by Toflar** [comment]
Steht doch eigentlich im Klartext da? Was an der Meldung müssen wir verbessern, damit du es vestanden hättest?

**Comment by jcontao** [comment]
Das mit dem Klartext ist deine vorgefasste Meinung, entstanden durch dein Hintergrundwissen, dass nicht alle teilen. Versuch mal es so zu sehen.

**Comment by Toflar** [comment]
Äh ja, deswegen frag ich ja wie die Meldung deiner Meinung nach lauten soll?
