### ISSUE TITLE
Catch memory limit issues

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#42]
The task queue must check the log file of tasks marked as "running" if the process has died due to memory limit issues.

**Comment by discordier** [comment]
Again the problem, HOW shall I tell?
The only thing I could do is assume they are dead when running for more than XX seconds/minuts/hours which still might be wrong.
I can get the PID from the running process but not the list of running processes as most providers restrict access to the process information.

**Comment by aschempp** [comment]
I assume we can read the log, so searching for "out of memory" or similar should be possible.

**Comment by discordier** [comment]
I suspect this will not end up in the log as it is an fatal error, we have to test.

**Comment by aschempp** [comment]
The current version now displays at least the respective error message.
