### ISSUE TITLE
Problem loading contao-manager

### ISSUE THREAD

**Issue by t-me** [contao/contao-manager#420]
**version(s)**
```json
"contao/manager-bundle": "4.7.*",
"contao/calendar-bundle": "^4.7",
"contao/comments-bundle": "^4.7",
"contao/faq-bundle": "^4.7",
"contao/listing-bundle": "^4.7",
"contao/news-bundle": "^4.7",
"contao/newsletter-bundle": "^4.7",
"contao/conflicts": "*@dev"
```

**Description**  
When i opened the manager it will reinstall contao but that hangs, i have tried it for 3 times than canceld the job. Now when i open the manager i see the below message for 24 hours now.
even when i reopen the manager and login.

![contao-manager](https://user-images.githubusercontent.com/14944366/56150572-78ac8b00-5faf-11e9-9c4e-d9265e96eb23.PNG)

i already removed the task.json but that dit not fix this.

The config.json
```json
{
    "preferred-install": "dist",
    "store-auths": false,
    "optimize-autoloader": true,
    "sort-packages": true,
    "discard-changes": true
}
```

The manager.json
```json
{
    "server": "custom",
    "php_cli": "\/opt\/alt\/php71\/usr\/bin\/php",
    "last_update": "2019-04-13T23:17:31+02:00",
    "latest_version": "1.1.4",
    "latest_requires": {
        "php": "^5.5.9 || ^7"
    }
}
```

The task.json
`{"name":"contao\/install","options":{"version":"4.7","core-only":"0","no-update":"0"},"state":{"create-project":"error","backup-created":true,"cloud-job-queued":1555190308,"cloud-job":"*******REMOVED*******","cloud-job-processing":1555190309,"cloud-job-finished":1555190387,"cloud-job-successful":true},"cancelled":true}`

**Comment by xchs** [comment]
This must be set to `"contao/manager-bundle": "4.7.*"`

**Comment by ausi** [comment]
@xchs it already is `4.7.*` (the star got removed by GitHubs formatting)

**Comment by t-me** [comment]
@xchs it is set to 4.7.* markup removes the *

**Comment by xchs** [comment]
Ah, okay.

**Comment by t-me** [comment]
This is the log file


> Installing contao/managed-edition 4.7

$ /opt/alt/php71/usr/bin/php '-q' '/home/removed/domains/sitenzo.nl/contao/web/contao-manager.phar.php' 'composer' 'install' '--prefer-dist' '--no-dev' '--no-progress' '--no-suggest' '--no-ansi' '--no-interaction' '--optimize-autoloader' 2>&1

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 159 installs, 0 updates, 0 removals
  - Installing contao-components/installer (1.3.1): Downloading (100%)
  - Installing ocramius/package-versions (1.4.0): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.11.0): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.11.0): Downloading (100%)
  - Installing symfony/http-foundation (v4.2.5): Downloading (100%)
  - Installing symfony/contracts (v1.0.2): Downloading (100%)
  - Installing symfony/event-dispatcher (v4.2.5): Downloading (100%)
  - Installing psr/log (1.1.0): Downloading (100%)
  - Installing symfony/debug (v4.2.5): Downloading (100%)
  - Installing symfony/http-kernel (v4.2.5): Downloading (100%)
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing symfony/dependency-injection (v4.2.5): Downloading (100%)
  - Installing symfony/filesystem (v4.2.5): Downloading (100%)
  - Installing symfony/config (v4.2.5): Downloading (100%)
  - Installing symfony/routing (v4.2.5): Downloading (100%)
  - Installing contao/manager-plugin (2.7.0): Downloading (100%)
  - Installing ausi/slug-generator (v1.1.0): Downloading (100%)
  - Installing dasprid/enum (1.0.0): Downloading (100%)
  - Installing bacon/bacon-qr-code (2.0.0): Downloading (100%)
  - Installing contao-components/ace (1.4.2): Downloading (100%)
  - Installing contao-components/chosen (1.2.1): Downloading (100%)
  - Installing contao-components/colorbox (1.6.4.1): Downloading (100%)
  - Installing contao-components/colorpicker (1.5.0): Downloading (100%)
  - Installing contao-components/compass (0.12.2.1): Downloading (100%)
  - Installing contao-components/contao (8.0.3): Downloading (100%)
  - Installing contao-components/datepicker (2.3.0): Downloading (100%)
  - Installing contao-components/dropzone (5.5.0): Downloading (100%)
  - Installing contao-components/highlight (9.14.2): Downloading (100%)
  - Installing contao-components/html5shiv (3.7.3): Downloading (100%)
  - Installing contao-components/jquery (3.3.1): Downloading (100%)
  - Installing contao-components/jquery-ui (1.12.1.1): Downloading (100%)
  - Installing contao-components/mediabox (1.5.4.2): Downloading (100%)
  - Installing contao-components/mediaelement (4.2.10): Downloading (100%)
  - Installing contao-components/mootools (1.6.0.5): Downloading (100%)
  - Installing contao-components/respimage (1.4.2): Downloading (100%)
  - Installing contao-components/simplemodal (2.1.0): Downloading (100%)
  - Installing contao-components/swipe (2.1.1): Downloading (100%)
  - Installing contao-components/tablesort (3.4.11): Downloading (100%)
  - Installing contao-components/tablesorter (2.1.0): Downloading (100%)
  - Installing contao-components/tinymce4 (4.9.3): Downloading (100%)
  - Installing symfony/yaml (v4.2.5): Downloading (100%)
  - Installing patchwork/utf8 (v1.3.1): Downloading (100%)
  - Installing symfony/options-resolver (v4.2.5): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing php-http/message-factory (v1.0.2): Downloading (100%)
  - Installing clue/stream-filter (v1.4.1): Downloading (100%)
  - Installing php-http/message (1.7.2): Downloading (100%)
  - Installing php-http/discovery (1.6.1): Downloading (100%)
  - Installing php-http/promise (v1.0.0): Downloading (100%)
  - Installing php-http/httplug (v1.1.0): Downloading (100%)
  - Installing ralouphie/getallheaders (2.0.5): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.5.2): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)
  - Installing php-http/guzzle6-adapter (v1.1.1): Downloading (100%)
  - Installing php-http/client-common (1.9.1): Downloading (100%)
  - Installing friendsofsymfony/http-cache (2.5.4): Downloading (100%)
  - Installing true/punycode (v2.1.1): Downloading (100%)
  - Installing symfony/finder (v4.2.5): Downloading (100%)
  - Installing symfony/var-exporter (v4.2.5): Downloading (100%)
  - Installing psr/simple-cache (1.0.1): Downloading (100%)
  - Installing psr/cache (1.0.1): Downloading (100%)
  - Installing symfony/cache (v4.2.5): Downloading (100%)
  - Installing symfony/framework-bundle (v4.2.5): Downloading (100%)
  - Installing friendsofsymfony/http-cache-bundle (2.6.1): Downloading (100%)
  - Installing terminal42/header-replay-bundle (1.5.3): Downloading (100%)
  - Installing twig/twig (v2.7.4): Downloading (100%)
  - Installing symfony/twig-bridge (v4.2.5): Downloading (100%)
  - Installing symfony/twig-bundle (v4.2.5): Downloading (100%)
  - Installing symfony/translation (v4.2.5): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.11.0): Downloading (100%)
  - Installing symfony/polyfill-intl-idn (v1.11.0): Downloading (100%)
  - Installing symfony/polyfill-iconv (v1.11.0): Downloading (100%)
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)
  - Installing egulias/email-validator (2.1.7): Downloading (100%)
  - Installing swiftmailer/swiftmailer (v6.2.0): Downloading (100%)
  - Installing symfony/swiftmailer-bundle (v3.2.5): Downloading (100%)
  - Installing symfony/inflector (v4.2.5): Downloading (100%)
  - Installing symfony/property-access (v4.2.5): Downloading (100%)
  - Installing symfony/security (v4.2.5): Downloading (100%)
  - Installing symfony/security-bundle (v4.2.5): Downloading (100%)
  - Installing symfony/process (v4.2.5): Downloading (100%)
  - Installing symfony/lock (v4.2.5): Downloading (100%)
  - Installing symfony/expression-language (v4.2.5): Downloading (100%)
  - Installing symfony/console (v4.2.5): Downloading (100%)
  - Installing symfony/asset (v4.2.5): Downloading (100%)
  - Installing symfony-cmf/routing (2.1.0): Downloading (100%)
  - Installing symfony-cmf/routing-bundle (2.1.1): Downloading (100%)
  - Installing paragonie/constant_time_encoding (v2.2.3): Downloading (100%)
  - Installing beberlei/assert (v3.2.0): Downloading (100%)
  - Installing spomky-labs/otphp (v9.1.4): Downloading (100%)
  - Installing simplepie/simplepie (1.5.2): Downloading (100%)
  - Installing sonata-project/google-authenticator (2.2.0): Downloading (100%)
  - Installing lcobucci/jwt (3.2.5): Downloading (100%)
  - Installing scheb/two-factor-bundle (v3.18.0): Downloading (100%)
  - Installing phpunit/php-token-stream (3.0.1): Downloading (100%)
  - Installing phpspec/php-diff (v1.1.0): Downloading (100%)
  - Installing oyejorge/less.php (v1.7.0.14): Downloading (100%)
  - Installing nelmio/cors-bundle (1.5.5): Downloading (100%)
  - Installing michelf/php-markdown (1.8.0): Downloading (100%)
  - Installing matthiasmullie/path-converter (1.1.2): Downloading (100%)
  - Installing matthiasmullie/minify (1.3.61): Downloading (100%)
  - Installing league/uri-parser (1.4.1): Downloading (100%)
  - Installing league/uri-interfaces (1.1.1): Downloading (100%)
  - Installing league/uri-schemes (1.2.1): Downloading (100%)
  - Installing league/uri-hostname-parser (1.1.1): Downloading (100%)
  - Installing league/uri-components (1.8.2): Downloading (100%)
  - Installing league/uri-manipulations (1.5.0): Downloading (100%)
  - Installing league/uri (5.3.0)
  - Installing leafo/scssphp (v0.7.7): Downloading (100%)
  - Installing symfony/templating (v4.2.5): Downloading (100%)
  - Installing knplabs/knp-time-bundle (1.8.0): Downloading (100%)
  - Installing knplabs/knp-menu (2.3.0): Downloading (100%)
  - Installing knplabs/knp-menu-bundle (v2.2.1): Downloading (100%)
  - Installing imagine/imagine (1.2.0): Downloading (100%)
  - Installing doctrine/annotations (v1.6.1): Downloading (100%)
  - Installing doctrine/reflection (v1.0.0): Downloading (100%)
  - Installing doctrine/event-manager (v1.0.0): Downloading (100%)
  - Installing doctrine/collections (v1.6.1): Downloading (100%)
  - Installing doctrine/cache (v1.8.0): Downloading (100%)
  - Installing doctrine/persistence (v1.1.0): Downloading (100%)
  - Installing symfony/doctrine-bridge (v4.2.5): Downloading (100%)
  - Installing doctrine/inflector (v1.3.0): Downloading (100%)
  - Installing doctrine/doctrine-cache-bundle (1.3.5): Downloading (100%)
  - Installing jdorn/sql-formatter (v1.2.17): Downloading (100%)
  - Installing doctrine/dbal (v2.8.1): Downloading (100%)
  - Installing doctrine/doctrine-bundle (1.10.2): Downloading (100%)
  - Installing contao/imagine-svg (0.2.2): Downloading (100%)
  - Installing webmozart/assert (1.4.0): Downloading (100%)
  - Installing webmozart/path-util (2.3.0): Downloading (100%)
  - Installing contao/image (0.3.9): Downloading (100%)
  - Installing contao/core-bundle (4.7.4): Downloading (100%)
  - Installing contao/calendar-bundle (4.7.4): Downloading (100%)
  - Installing contao/comments-bundle (4.7.4): Downloading (100%)
  - Installing contao/conflicts (dev-master 04c0e80)
  - Installing contao/faq-bundle (4.7.4): Downloading (100%)
  - Installing contao/listing-bundle (4.7.4): Downloading (100%)
  - Installing toflar/psr6-symfony-http-cache-store (1.1.2): Downloading (100%)
  - Installing symfony/var-dumper (v4.2.5): Downloading (100%)
  - Installing symfony/web-profiler-bundle (v4.2.5): Downloading (100%)
  - Installing zendframework/zend-eventmanager (3.2.1): Downloading (100%)
  - Installing zendframework/zend-code (3.3.1): Downloading (100%)
  - Installing ocramius/proxy-manager (2.1.1): Downloading (100%)
  - Installing symfony/proxy-manager-bridge (v4.2.5): Downloading (100%)


---

### The background task is being cancelled ###

**Comment by aschempp** [comment]
> i already removed the task.json but that dit not fix this.

What happens after you removed the task.json ?

**Comment by t-me** [comment]
Whe i removed the task.json i can see the manager.
When i update all packages (default contao installation) it will hang on 

![contao-manager-2](https://user-images.githubusercontent.com/14944366/56218204-d353ee80-6064-11e9-9216-ce84a35e122d.PNG)

**Comment by aschempp** [comment]
Did you **only** remove the tasks.json? Because these packages should be cached on the second update, so that's pretty interesting...

**Comment by t-me** [comment]
Yes i removed only the task.json nothing more.

**Comment by t-me** [comment]
I removed all the cache updated to php 7.3 still not working.

When i ssh to the server and type 

`/opt/alt/php73/usr/bin/php /home/removed/domains/sitenzo.nl/contao/web/contao-manager.phar.php composer update`

the process get killed 

![contao-manager-3](https://user-images.githubusercontent.com/14944366/56300354-19c54e00-6136-11e9-9e56-7cf2518072bd.PNG)

**Comment by fritzmg** [comment]
The process gets probably killed due to high memory consumption. You need to use the cloud resolver.

**Comment by t-me** [comment]
How many ram does the manager need with and without cloud resolver?

**Comment by aschempp** [comment]
That depends on your setup, but it can easily be 2GB

**Comment by aschempp** [comment]
This issue was closed because it has not had recent activity.
