### ISSUE TITLE
Add jweiland.net to the known hosting list

### ISSUE THREAD

**Issue by Aybee** [contao/contao-manager#421]
**Description**  
Bitte nicht vergessen jweiland.net zu den Anbietern hinzuzufügen. Danke.
https://github.com/contao/contao-manager/wiki/jweiland.net

**Comment by aschempp** [comment]
Was im Wiki ist wird in der nächsten Version hinzugefügt, wenn vollständig.

**Comment by Aybee** [comment]
Was heißt "wenn vollständig"? Fehlt bei meinen Angaben etwas?

**Comment by aschempp** [comment]
alle anderen sehen anders aus, wenn du mal einen Vergleich machst.

**Comment by Aybee** [comment]
Mmh, ich hatte da keine Vorlage gefunden. Naja, die Infos sind ja alle da. Vielleicht kann der nächste das so anpassen, dass es verstanden wird. Wüsste jetzt nicht, was fehlt.

**Comment by xchs** [comment]
Ich habe den Wiki-Eintrag entsprechend angepasst und fehlende Daten ergänzt.

**Comment by Aybee** [comment]
Danke, sehr nett.
