### ISSUE TITLE
Abbruch der Updates bei großer Anzahl an Jobs in der Resolver-Cloud

### ISSUE THREAD

**Issue by Floxn** [contao/contao-manager#422]
**Affected version(s)**
1.1.4
**Description**  
Der Update-Prozess wurde unterbrochen nachdem, ich glaube es waren 68 Jobs, durchgelaufen waren. Leider kann kein neuer Job mehr gestartet werden da: 
`Too many jobs on the Composer Resolver queue.`

Klar, heute ist ein Security-Update gekommen.

**How to reproduce**  
Viele Composer Updates laufen lassen.

**Comment by Toflar** [comment]
Ja, das ist auch gut so, die Queue lässt nur 100 Jobs zu. Das alleine sind schon 2.5h Wartezeit, ich glaube nicht, dass jemand wirklich so lange wartet 😄 Wir sollten die aktuelle Wartezeit anzeigen, bevor jemand einen Job startet, aber gegen die allgemeine Situation können wir nicht wirklich was tun.

**Comment by Floxn** [comment]
Klar, gegen die Situation ist nichts zu machen. Die Ausgabe der Wartezeit und wieviele Jobs davor "wären" ist ne gute Idee. Würde einiges klarer machen am Anfang.

**Comment by aschempp** [comment]
@Toflar kannst du bitte Ajax-Requests (CORS) für die Cloud API freigeben?

**Comment by Toflar** [comment]
Done.

**Comment by aschempp** [comment]
In 34d6f765bc912670a9f7eb8bbbf402689f3e7b6c wird der aktuelle Cloud-Status jetzt angezeigt. Trotzdem kann man einen 101 Job starten, aber ich weiss nicht ob/wie wir das verhindern können/sollen?

**Comment by aschempp** [comment]
You can now check the cloud status before submitting a job in version 1.3 😎
