### ISSUE TITLE
This path does not contain a valid php binary [lando]

### ISSUE THREAD

**Issue by rabauss** [contao/contao-manager#424]
**Affected version(s)**
Contao Manager 1.1.4
lando-v3.0.0-rc.16

**Description**  

I wanted to test the contao manager with lando for the ContaoCamp19.
Unfortunately, the php binary cannot be validated by the manager.
Just with composer every contao project is working fine.

**How to reproduce**  

1. Install lando (https://github.com/lando/lando/releases)
2. Create a new project folder and paste the following config to `<project>/lando.yml`

```
name: contao-manager
recipe: lamp
config:
  webroot: web

```

3. Download the ``contao-manager.phar`` and move it into `<project>/web/contao-manager.phar.php`
4. Run `lando start` in the command line
5. Open https://contao-manager.lndo.site/contao-manager.phar.php and create an account
6. The binary `/usr/local/bin/php` won't get accepted.
7. Run `lando ssh` in the command line
8. Run `/usr/local/bin/php /app/web/contao-manager.phar.php test` - the output will be:
   `{"version":"7.3.5","version_id":70305,"sapi":"cli"}`

What's the reason - maybe we can discuss at the camp?

**Comment by rabauss** [comment]
Okay, I did some debugging:

1. the default memory_limit on lando for internal cli is only 1G - so the `Phar::mapPhar()` cannot be executed for server info

2. then I tested the path `/usr/local/bin/php -d memory_limit=-1`, which is accepted to save custom configuration but unfortunately the second test with `is_executable($path)` will fail and the manager wont' accept the configuration - see:
https://github.com/contao/contao-manager/blob/8ef785f23484b8d29873d5af49c2fba8df712de9/api/Process/PhpExecutableFinder.php#L189


Finally, I set a global `php.ini` for the whole appserver with `memory_limit = -1` and now it's running - also the automatic suggestion on first run.

But I'm not sure if the test with `is_executable` is the right way, if no restrictions for `open_basedir` exist.

**Comment by aschempp** [comment]
You cannot pass arguments to the PHP path for security reasons, so option 2 will never work. However, I wonder why 1G should not be enought for your option 1?

**Comment by rabauss** [comment]
Well, I also wondered why 1G was not enough - perhabs because of xdebug?
But also without xdebug I could not set the binary path manually.

The `PhpExecutableFinder->getServerInfo($cli)` crashed with the following exception:

````
The command "/usr/local/bin/php '-q' '/app/web/contao-manager.php' 'test'" failed.

Exit Code: 255(Unknown error)

Working directory: /app

Output:
================

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 4096 bytes) in /app/web/contao-manager.php on line 51

Call Stack:
    0.0008     415384   1. {main}() /app/web/contao-manager.php:0
    0.0009     418080   2. Phar::mapPhar() /app/web/contao-manager.php:51



Error Output:
================
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 4096 bytes) in /app/web/contao-manager.php on line 51
PHP Stack trace:
PHP   1. {main}() /app/web/contao-manager.php:0
PHP   2. Phar::mapPhar() /app/web/contao-manager.php:51
````

**Comment by ausi** [comment]
`Allowed memory size of 2097152 bytes` shows that the memory limit is set to only 2 MB. This is way to low I think.

**Comment by rabauss** [comment]
You're absolutely right - I did not realize the real size.
But it's strange that the sub process has no memory_limit.

Output of `echo 'memory_limit:'. ini_get('memory_limit');` will be `memory_limit:` in sub process on lando.
