### ISSUE TITLE
config.preferred-install "source" wird ignoriert

### ISSUE THREAD

**Issue by chuckki** [contao/contao-manager#429]
Contao Manager 1.1.4, Contao 4.4.40

Für die Entwicklung eines Bundels habe ich den folgenden Eintrag in der ``composer.json``hinzugefügt:
```
    "config": {
        "preferred-install": {
            "chuckki/*": "source",
            "*": "dist"
        }
    },
```
Der Manager irgnoriert jedoch beim Update sowie auch bei Installation das "source"-Flag und die Pakete unter "chuckki/*" werden nicht als git-Repo gezogen.
Über die console ``composer install`` klappt alles.

**Comment by aschempp** [comment]
das liegt vermutlich an der config.json. Aber warum willst du Pakete mit dem Manager überhaupt als Source installieren?

**Comment by chuckki** [comment]
Danke für die Antwort.
Sagen wir mal so - der Kunde mag gerne den "Source"-Status entsprechend vom live Betrieb mitsichern.
Mir ist aufgefallen, dass nicht immer eine ``config.json``angelegt wird. Wann passiert dies bzw. wann wird diese Datei auch berücksichtigt?

**Comment by aschempp** [comment]
> Mir ist aufgefallen, dass nicht immer eine config.json angelegt wird. Wann passiert dies bzw. wann wird diese Datei auch berücksichtigt?

siehe https://github.com/contao/contao-manager/commit/80e557d43e9e016a78b8462014e1a201535a8869 / https://github.com/contao/contao-manager/issues/397
