### ISSUE TITLE
Update-Probleme auf Version 1.1.4

### ISSUE THREAD

**Issue by wivisions** [contao/contao-manager#431]
Versuche seit gestern bestehende Installationen vom CM auf 1.1.2 auf 1.1.4 upzudaten. Entweder dreht der Konsolentask ins Leere oder aber gleich zu Beginn erscheint die Fehlermeldung «Contao konnte einen Konsolentask nicht starten». PHP-Memory Limit erhöht (hatte aber auch bisher ohne wunderbar funktioniert).

Habe versch. probiert.: contao-manager.phar.php inkl. dem Ordner gelöscht und neuen ab der Website installiert. Ergebnis ist immer dasselbe. Gemäss Hostingsupport keine Änderungen ausser definitive Umstellung auf PHP 7.2.

Hoster: Hostpoint
PHP: 7.2
Contao Version 4.4.34

Contao Check wurde ebenfalls ausgeführt - alles ok. Habe eben noch eine neue Version auf einer Subdomain angelegt. Da ist genau dasselbe Problem. Ich komm nicht mal zur Installation von Contao...

Seit diesem Jahr mit Hostpoint nie Probleme weder bei Update noch sonst was bezgl. Contao daher bin ich echt ratlos.

**Comment by fritzmg** [comment]
Du meinst wohl 1.1.4?

Im Zweifelsfall einfach die neueste  `contao-manager.phar` manuell runterladen und auf den Server kopieren.

**Comment by wivisions** [comment]
Hallo fritzmg

> Du meinst wohl 1.1.4?
Ja, sorry, habs korrigiert.

> Im Zweifelsfall einfach die neueste `contao-manager.phar` manuell runterladen und auf den Server kopieren.
Wie du oben bei mir liest, habe ich diese bereits ab der Contao Seite heruntergeladen und neu installiert. Ohne Erfolg.

**Comment by fritzmg** [comment]
Aber dann hast du ja Version 1.1.4. Welches Problem existiert nun konkret?

**Comment by wivisions** [comment]
Sobald ich den Contao-Manager starte und ein Update auf 1.1.4 versuche erscheint entweder die Fehlermeldung «Contao konnte einen Konsolentask nicht starten». Lade ich die Site erneut und logge mich im Manager ein, dann dreht der Konsolentask endlos und der Contao-Manager startet nicht mehr bezw. ich komme nicht mehr rein. Ich hab mal das Errorlog-Protokoll runtergeladen. Hilft das um zu sehen wo der Fehler liegt?

**Comment by fritzmg** [comment]
> Sobald ich den Contao-Manager starte und ein Update auf 1.1.4

Aber du hast doch schon auf die neueste Contao Manager Version aktualisiert. Bist du dir sicher, dass du die richtige `contao-manager.phar` auf den richtigen Server geladen hast?

**Comment by wivisions** [comment]
Ja, ich habe es mehrmals versucht. Doch entweder kommt die Fehlermeldung das der Konsolentask nicht gestartet werden kann oder der Konsolentask läuft endlos.

Darum habe ich eine komplett neue Contao Version inklusive Manager auf meinen Server geladen und auch dort habe ich denselben Fehler.

**Comment by fritzmg** [comment]
> Darum habe ich eine komplett neue Contao Version inklusive Manager auf meinen Server geladen und auch dort habe ich denselben Fehler.

Aber nicht beim Updaten des Contao Managers, sondern bei etwas anderem vermutlich - denn du solltest ja jetzt die neueste Contao Manager Version haben.

**Comment by wivisions** [comment]
Doch, beim Update. 
Ich habe nun mit dem Hoster gesprochen und anscheinend schien da wirklich was im Hintergrund zu hängen. Nach einem Reboot seitens des Hosters, klappt es nun einwandfrei und das grüne Bestätigungsfenster vom Contao-Manager erschien. Auch die Neuinstallation funktioniert nun wieder.

**Comment by leofeyer** [comment]
Gleiches Problem wie in #229. Es muss ja einen Grund geben, warum das immer wieder auftritt, oder?
