### ISSUE TITLE
Individuelle Konfiguration - bekannte Serververwaltungssoftware integrieren

### ISSUE THREAD

**Issue by juehau** [contao/contao-manager#433]
**Description**  
Viele User werden ihre Server mittels Serversoftware verwalten. Vielleicht kann man diese in den Installationprozess integrieren.

**Example**  
hier mal ein Beispiel für Plesk Onyx 17.8.11
PHP-Binary /opt/plesk/php/7.2/bin/php
7.2 ist die PHP-Version (weitere Unterteilungen z.B. 7.2.19 werden unterschlagen)

**Comment by cliffparnitzky** [comment]
Kann man doch schon eintragen: 
![image](https://user-images.githubusercontent.com/1247552/59426788-5d0c0800-8dd9-11e9-9c00-d32b29f46ed2.png)

**Comment by juehau** [comment]
Ja, das stimmt. Das benutze ich ja auch. Aber genauso wie man Voreinstellungen für verschiedene Hoster anbietet, könnte das auch für verschiedene Verwaltungssoftwaren funtkionieren. Nur so ein Idee.

**Comment by aschempp** [comment]
Die Idee find ich prinzipiell nicht schlecht, aber dann hätten wir irgendwann "Plesk 1", Plesk 2, Plesk 3, Plesk 27 ?

**Comment by juehau** [comment]
Man könnte meiner Meinung nach die jeweilige Verwaltungssoftware + die PHP-Version als Pulldown einrichten.

**Comment by aschempp** [comment]
Die PHP-Version auszuwählen wäre sicher nicht richtig, denn wir kennen ja die aktuelle Version. Sie muss ja deinem Webserver entsprechen.

**Comment by aschempp** [comment]
Die PHP-Version auszuwählen wäre sicher nicht richtig, denn wir kennen ja die aktuelle Version. Sie muss ja deinem Webserver entsprechen.

**Comment by aschempp** [comment]
Die Option hat sich mit Version 1.3 erledigt, es muss kein Hoster mehr konfiguriert werden.
https://contao.org/de/news/contao-manager-1-3-0-verfuegbar.html

**Comment by juehau** [comment]
Vielen Dank für die Info

BG
Jürgen 

Am 23. September 2020 16:15:15 MESZ schrieb Andreas Schempp <notifications@github.com>:
>Die Option hat sich mit Version 1.3 erledigt, es muss kein Hoster mehr
>konfiguriert werden.
>https://contao.org/de/news/contao-manager-1-3-0-verfuegbar.html
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/contao/contao-manager/issues/433#issuecomment-697423469

Beste Grüße
Jürgen Haubeil
