### ISSUE TITLE
Check if the contao-manager is running in "web" folder before installation

### ISSUE THREAD

**Issue by Marion04** [contao/contao-manager#434]
If the contao-manager.phar.php is not in a folder called "web", the installation is running anyway. 

It's stopping with the error message: 
"ERROR 500 Unknown installation status
Some files were found on your server but no known Contao version could be detected.
You must either manually repair your application or remove the following files and folders to install Contao:
- contao-manager.phar.php"

There's no hint to the real error cause: wrong directory name.

Would it be possible to add to the pre-installation checks another check for the directory? And if it's not "web", having an error message clearly stating that the folder name has to be "web"? Before trying to run an installation which will fail to 100%?

Thank you!

**Comment by aschempp** [comment]
Thanks for your feedback! Here's how we want to fix this: https://github.com/contao/contao-manager/issues/150
