### ISSUE TITLE
composer-install.set.json wird nicht gefunden

### ISSUE THREAD

**Issue by Samson1964** [contao/contao-manager#438]
Der CM 1.1.6 (und auch schon 1.1.4) findet manchmal die Datei composer-install.set.json nicht, obwohl sie vorhanden ist, wenn man nach Anzeige der Fehlermeldung schaut:
`
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating optimized autoload files
InvalidArgumentException: Config file "/x/contao-manager/composer-install.set.json" does not exist. in phar:///x/web/contao-manager.phar.php/vendor/terminal42/background-process/src/AbstractProcess.php:52
Stack trace:
#0 phar:///x/web/contao-manager.phar.php/vendor/terminal42/background-process/src/ProcessRunner.php(175): Terminal42\BackgroundProcess\AbstractProcess::readConfig('/kunden/107305_...')
#1 phar:///x/web/contao-manager.phar.php/vendor/terminal42/background-process/src/ProcessRunner.php(106): Terminal42\BackgroundProcess\ProcessRunner->loadConfig()
#2 phar:///x/web/contao-manager.phar.php/vendor/terminal42/background-process/src/ProcessRunner.php(53): Terminal42\BackgroundProcess\ProcessRunner->wait(1)
#3 phar:///x/web/contao-manager.phar.php/vendor/terminal42/background-process/src/Command/ProcessRunnerCommand.php(36): Terminal42\BackgroundProcess\ProcessRunner->run()
#4 phar:///x/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(255): Terminal42\BackgroundProcess\Command\ProcessRunnerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///x/web/contao-manager.phar.php/vendor/symfony/console/Application.php(987): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///x/web/contao-manager.phar.php/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Terminal42\BackgroundProcess\Command\ProcessRunnerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///x/web/contao-manager.phar.php/api/ApiApplication.php(76): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///x/web/contao-manager.phar.php/vendor/symfony/console/Application.php(148): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///x/web/contao-manager.phar.php/api/console(84): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#10 /x/web/contao-manager.phar.php(54): require('phar:///kunden/...')
#11 {main}
# Process terminated with exit code 143
# Result: Termination (request to terminate) [signal 15]
`
Der Fehler tritt z.B. auf, wenn sich der CM mit der Systemwiederherstellung meldet und man dort die Reparatur auswählt.

**Comment by fritzmg** [comment]
Ich hatte den Fehler auch schon öfter - und habe ihn auch schon öfter im Forum gesehen. Holzhammer Lösung war `/vendor`, `/var` und `/contoa-manager/composer-install.set.json` zu löschen - dann nochmal ein composer install ausführen.

**Comment by MacKP** [comment]
Problem ist mit dem Fix für mich noch nicht gelöst.
Selbe Fehlermeldung (beim deinstallieren von Erweiterungen).
Inzwischen konnte ich durch 'reparieren' die Erweiterung deinstallieren. Deswegen hab ich gerade nicht mehr den ganzen Stack-Trace :(

Viele Grüße

**Comment by MacKP** [comment]
Problem ist mit dem Fix für mich noch nicht gelöst.
Selbe Fehlermeldung (beim deinstallieren/installieren von Erweiterungen):

```
> Resolving dependencies using Composer Cloud v2.0.11

# Job ID LtYzOtEl0m5dG4vs78BmIUXEbMPTEpG2QY0G2n7mVoT93rZ1pHpR2n94dmG1NzxUM completed in 136 seconds
# Memory usage: 776.55MB (peak: 3493.72MB), time: 135.96s.

$ /opt/php-7.2.14/bin/php -q /xxx/web/web/contao-manager.phar.php composer install --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader

Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
InvalidArgumentException: Config file "/xxx/web/contao-manager/composer-install.set.json" does not exist. in phar:///xxx/web/web/contao-manager.phar.php/api/Process/AbstractProcess.php:56
Stack trace:
#0 phar:///xxx/web/web/contao-manager.phar.php/api/Process/ProcessRunner.php(183): Contao\ManagerApi\Process\AbstractProcess::readConfig('/var/www/client...')
#1 phar:///xxx/web/web/contao-manager.phar.php/api/Process/ProcessRunner.php(114): Contao\ManagerApi\Process\ProcessRunner->loadConfig()
#2 phar:///xxx/web/web/contao-manager.phar.php/api/Process/ProcessRunner.php(59): Contao\ManagerApi\Process\ProcessRunner->wait(1)
#3 phar:///xxx/web/web/contao-manager.phar.php/api/Command/ProcessRunnerCommand.php(46): Contao\ManagerApi\Process\ProcessRunner->run()
#4 phar:///xxx/web/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(255): Contao\ManagerApi\Command\ProcessRunnerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///xxx/web/web/contao-manager.phar.php/vendor/symfony/console/Application.php(933): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///xxx/web/web/contao-manager.phar.php/vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Contao\ManagerApi\Command\ProcessRunnerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///xxx/web/web/contao-manager.phar.php/api/ApiApplication.php(72): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///xxx/web/web/contao-manager.phar.php/vendor/symfony/console/Application.php(148): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///xxx/web/web/contao-manager.phar.php/api/console(86): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#10 /xxx/web/web/contao-manager.phar.php(57): require('phar:///var/www...')
#11 {main}
# Process terminated with exit code 143
# Result: Termination (request to terminate) [signal 15]


---
```

Viele Grüße

**Comment by mwoelke** [comment]
Bug kommt unter der aktuellen 1.2.4 immer noch vor.

So wie ich das beobachtet habe, steht der Bug in Zusammenhang mit folgendem Fehler:

https://community.contao.org/de/showthread.php?72798-composer-no-unzip-command-installed

Da unzip nicht gefunden wird, werden die Dateien von PHP unzipped. Hierbei werden diese mit falschen Rechten angelegt und der Manager kann die Dateien später nicht einsehen.

**Comment by jacob418** [comment]
> Bug kommt unter der aktuellen 1.2.4 immer noch vor.
> 
> So wie ich das beobachtet habe, steht der Bug in Zusammenhang mit folgendem Fehler:
> 
> https://community.contao.org/de/showthread.php?72798-composer-no-unzip-command-installed
> 
> Da unzip nicht gefunden wird, werden die Dateien von PHP unzipped. Hierbei werden diese mit falschen Rechten angelegt und der Manager kann die Dateien später nicht einsehen.

Ich kann bestätigen, nachdem ich `unzip` in meinem Docker-Image installiert habe der Fehler verschwunden ist.
