### ISSUE TITLE
Install Contao from ZIP file

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#44]
It would be way easier to install Contao from a ZIP file instead of `composer create-project`. Should be sufficient to install a managed edition if that is the default download.

In that case we also don't need `contao/managed-edition` on Packagist.

Btw. this is similar to what the Symfony installer and the Contao check does.

**Comment by discordier** [comment]
We could do so but what benefit will this provide over `create-project`?

**Comment by aschempp** [comment]
It will be extremly much faster.

**Comment by aschempp** [comment]
That will only work if we can correctly determine the requirements though (see #74)

**Comment by aschempp** [comment]
This is obsolete with version 1.0
