### ISSUE TITLE
Abbruchproblem Contao-Manager 1.1.6

### ISSUE THREAD

**Issue by chschneiderobl** [contao/contao-manager#442]
Der von mir auf Hostingwerk installierte Contao-Manager 1.1.6 verursacht bei einer Paketinstallation volgende Fehlermeldung:

Using version ^2.0 for contao-bootstrap/core
/srv/www/chschneider/public/contaoboot/composer.json has been updated

# Process terminated with exit code 0
# Result: OK

"/srv/www/chschneider/public/contaoboot/composer.lock" does not contain valid JSON
Parse error on line 1:

^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

---

### Der Hintergrundprozess wurde unerwartet beendet ###

Ich habe schon alles mögliche versucht, bekomme immer wieder die gleiche Fehlermeldung!
Danke für Ihre Hilfe.

**Comment by aschempp** [comment]
Am besten versuchst du die Datei `"/srv/www/chschneider/public/contaoboot/composer.lock"` zu löschen, der Manager wird beim nächsten Aufruf entsprechend reagieren.
