### ISSUE TITLE
memory_limit=-1 für hosting.de

### ISSUE THREAD

**Issue by arboc** [contao/contao-manager#443]
für den Provider: "hosting.de" wird die Option "-d memory_limit=-1" benötigt.

**Comment by aschempp** [comment]
bei Verwendung der Composer Cloud?

**Comment by arboc** [comment]
ohne Cloud.  
Es wird beim Update folgender Befehl aufgerufen:  
`$ /opt/php-7.2/bin/php '-q' '/home/.../contao-manager.phar.php' 'composer' 'update' ... '--with-dependencies' '--prefer-dist' '--no-dev' '--no-progress' '--no-suggest' '--no-ansi' '--no-interaction' '--optimize-autoloader' 2>&1`

und das ist dann die Rückmeldung:
```
Loading composer repositories with package information
Updating dependencies

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
# Process terminated with exit code 255
# Result: Unknown error


---

### The background task has stopped unexpectedly ###
```

Ich meinte, ich hätte das Problem auch bei der Verwendung der Cloud, kann es aber derzeit nicht reproduzieren.

**Comment by fritzmg** [comment]
@arboc bei der Verwendung des Cloud Resolvers wird (am Server) kein composer update aufgerufen.

**Comment by arboc** [comment]
@fritzmg ich habe ja auch geschrieben "ohne Cloud".
