### ISSUE TITLE
`zlib.output_compression=1` breaks contao-manager

### ISSUE THREAD

**Issue by discordier** [contao/contao-manager#445]
**Affected version(s)**

All I guess.

**Description**  

Ok, this is rather a multi issue regarding the contao-manager, the manager-bundle and PHP itself.

I noticed that the Contao manager does throw an 500 when trying to determine the Contao version:
```
Uncaught PHP Exception UnexpectedValueException: "The Response content must be a string or object implementing __toString(), "boolean" given."
```
After hacking a wrapper script around the .phar, I got to the source of the exception:
[code](https://github.com/contao/contao-manager/blob/23e170c91e88759f029c07d500bec95981546f1a/api/Controller/Server/ContaoController.php#L100-L106), issue: contao/contao-manager#441.

Then the real miracle began, what I was getting as version was: `4.4.40\n0x1f8b080000000000000303`
So the version is there but suffixed with binary data (zlib header).

The problem here now is the `zlib.output_compression = On` in the PHP ini, which is defined as (emphasis mine):
> **If** this option is **set to "On" in php.ini or the Apache configuration**, pages are compressed **if** the **browser sends** an **"Accept-Encoding: gzip" or "deflate" header**. "Content-Encoding: gzip" (respectively "deflate") and "Vary: Accept-Encoding" headers are added to the output. In runtime, it can be set only before sending any output.

The big problem here is now, we do not have a browser anymore, we are a console application running by a CGI script.
The nature of how contao-manager spawns it's processes causes the child processes to inherit the whole environment of the parenting process and therefore also sees the `HTTP_ACCEPT` variables for which PHP happily starts the output buffer.

Verified by putting this in `contao-console` at the very top:
```
$buffers = ob_list_handlers();
while (ob_get_level()){ob_end_clean();}
var_export($buffers);
var_dump($_SERVER);
exit;
```

This produces (line breaks and abbreviation for readability):
 ```json
{
  "title": "The Contao version could not be determined",
  "type": "about:blank",
  "status": 502,
  "detail": "The console returned unexpected content when asked for the Contao version.
Please check the output for more information:
array (0 => 'zlib output compression',)
array(65) { [...] [\"HTTP_ACCEPT_ENCODING\"]=> string(17) \"gzip, deflate, br\" [...]"
}
```
So the output handler is active and kicking.

**How to reproduce**  

Shared `php.ini` for cli SAPI and fpm SAPI:
```
zlib.output_compression = On
```
Simply try to open contao-manager in any browser, it should fail with HTTP 500 on:
`/api/server/php-web?_locale=en`

**Suggested fix**
1. `while (ob_get_level()){ob_end_clean();}` in `contao-console` to fix the problem with the output buffer
2. Redact the environment variables being passed to the console to omit the HTTP headers - they are of no good to the CLI - however, this should most likely be tracked in a new issue in https://github.com/contao/contao-manager.

**Comment by aschempp** [comment]
(I also just transferred this to the Contao Manager, as it seems a Manager issue)

**Comment by discordier** [comment]
I fail to see the relevance of the CLI binary as it is used from terminal... are you mixing up things here?

The workflow is:
- weserver gets headers from browser
- CGI binary gets headers from webserver as environment
- CGI starts CLI binary which inherits the whole environment from CGI
- CLI sees header in environment and starts output compression buffer.
- zlib compressed output is returned to CGI as process output
- CGI reads output
- Contao Manager dies miserably trying to cope with the output:
  - tries to parse version number from zlib compressed output
  - decides it can not parse it
  - tries to write a proper json error response
  - dies doing so with "invalid utf-8 sequence" (See contao/contao-manager#441)
  - => HTTP 500

**Comment by aschempp** [comment]
A real CLI binary does not inherit the CGI environment variables, and usually does not have output compression enabled as it uses a different `php.ini`. However, because not all servers have an actual CLI binary available, the Contao Manager can also run the CGI binary. You already said your binary is `/api/server/php-web`, which is likely CGI. Is there no `/api/server/php-cli` on your server?

**Comment by discordier** [comment]
> A real CLI binary does not inherit the CGI environment variables

Not true as EVERY process inherits the environment of the process it is started from.
I also fail to see the difference between a "real CLI binary" and a what is not a "real" binary as I can start ANY binary from CLI and also from GUI or a combination of both?
It comes down to the same unix principle which is: environment is passed from parent process to child process.
You can even read it up on [wikipedia](https://en.wikipedia.org/wiki/Environment_variable#Design) if you don't believe me): "In all Unix and Unix-like systems, each process has its own separate set of environment variables. By default, when a process is created, it inherits a duplicate environment of its parent process, except for explicit changes made by the parent when it creates the child."

>and usually does not have output compression enabled as it uses a different php.ini.

Not true per se as it completely boils down to how the binary is built. The ini files in use can be a complete bunch of files varying over include files etc.
There may be a dozen of files scattered over various `conf.d` and `mod-enabled` sub-directories (i.e. Debian) but the "root" php.ini  is also often just `/etc/php/php.ini` (i.e. for php compiled straight from source without adjustments) or let alone `/home/user/etc/php.ini` for chrooted environments.
All of the above support cgi and cli usage and, normally, there is no problem because there normally is NO environment variable named `HTTP_ACCEPT` et. al. in CLI context (where CLI context means: the PHP CLI SAPI) and therefore PHP did not decide to restrict it to a certain SAPI.

> However, because not all servers have an actual CLI binary available, the Contao Manager can also run the CGI binary.

True, however that is not the case here (versions see below) and does not make any difference at all as CLI SAPI and FCGI SAPI behave the same in this case.

> You already said your binary is /api/server/php-web, which is likely CGI. Is there no /api/server/php-cli on your server?

I never said that, I said the Contao manager URL to obtain the version number is `/api/server/php-web?_locale=en`.

The php paths on this test system are (this one is an Uberspace):
- `/package/host/localhost/php-7.1/bin/php-cgi` (PHP 7.1.30 (cgi-fcgi) (built: Jun 14 2019 13:37:40))
- `/package/host/localhost/php-7.1/bin/php` (PHP 7.1.30 (cli) (built: Jun 14 2019 13:35:57) (NTS))

**Comment by aschempp** [comment]
https://github.com/contao/contao/pull/616 fixes the issue for the Contao console as far as possible. We should still fix the header imho, but this will be a task in Contao Manager 1.2

**Comment by discordier** [comment]
Have you tested the fix?

I have not tested it yet but from the implementation I'd guess the execution is "too late" as I suspect PHP will check the flag at boot time and start the output compression buffer immediately then.
Hence I suggested to clear all buffers in the startup sequence.

**Comment by aschempp** [comment]
All environment variables should already be cleared. Can you maybe post an example where and how to achieve/fix that?

**Comment by discordier** [comment]
Can you point me to the location where you are cleaning the environment?
I fail to find it by searching for `putenv` calls

**Comment by aschempp** [comment]
https://github.com/contao/contao-manager/blob/master/api/System/ServerInfo.php#L176-L183
