### ISSUE TITLE
Apply dry-run without re-resolving

### ISSUE THREAD

**Issue by wiphi** [contao/contao-manager#447]
**Description**  
Es wäre schön, wenn bereits aufgelöste dependencies über den Testlauf (dry-run) einfach im Anschluss installiert werden könnten, ohne dabei während "Änderungen übernehmen" nochmal alle Abhängigkeiten über den resolver aufzulösen.

Dies würde den Composer Cloud Resolver entlasten und die Installation nach einem Testlauf beschleunigen. Außerdem hätte es den Vorteil, dass man wirklich das installiert, was der Testlauf auch ermittelt hat. Würde zwischen Testlauf und "Änderungen anwenden" derzeit ein Package aktualisiert werden, was man so nicht getestet hat, würde es installiert werden ohne das man es evtl. merkt. 

**Example**  
Testlauf (composer.lock wird erstellt und gespeichert) -> Änderungen anwenden (gespeicherte composer.lock wird nur noch installiert)

**Comment by fritzmg** [comment]
Diese Anfrage müsstest du an composer stellen, nicht an den Contao Manager.

**Comment by Toflar** [comment]
Nein, das passt schon hier.

**Comment by aschempp** [comment]
Passt hier, aber duplicate of https://github.com/contao/contao-manager/issues/423 😉
