### ISSUE TITLE
Contao Manager "Process terminated with exit code 1 - Result: General error"

### ISSUE THREAD

**Issue by danielr-mm** [contao/contao-manager#448]
Hallo und Grüße,
beim updaten der Abhängigkeiten bricht der Manager mit folgendem Fehler ab: https://pastebin.com/xagxp01G

Wir nutzen die Composer-Cloud, kann es sein das 3.3GB Spitze für den Prozess zu hoch ist? Auf dieser Seite laufen ein paar Erweiterungen welche sich in den Wochen vorher ohne Probleme installieren ließen. Allerdings bricht es jetzt immer ab. Wir haben auch schon Contao 4 neu aufgesetzt und alles wieder importiert aber der gleiche Fehler besteht.

Fehler:
`> Resolving dependencies using Composer Cloud v2.0.11

# Job ID 0ulrP1OPqscYLsf0eK7TvDmT1JlFNLAQGY9zp6QHfFNtwTmyRjaG1dXYvd9SMDw4JHKZgK7mpPxgIVkJJUmzCBBl2KZkLP1tvuGLKGnJw completed in 155 seconds
# Memory usage: 737.16MB (peak: 3368.93MB), time: 153.84s.

$ /opt/RZphp72/bin/php-cli '-q' '-d' 'max_execution_time=300' '/mnt/web318/e1/81/52170081/htdocs/MOB-Neu/web/contao-manager.phar.php' 'composer' 'install' '--prefer-dist' '--no-dev' '--no-progress' '--no-suggest' '--no-ansi' '--no-interaction' '--optimize-autoloader' 2>&1

Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class User not found in /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/contao/core-bundle/src/Resources/contao/classes/BackendUser.php:32
Stack trace:
#0 /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/composer/ClassLoader.php(444): include('/mnt/web318/e1/...')
contao/contao#1 /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/mnt/web318/e1/...')
contao/contao#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Contao\\BackendU...')
contao/contao#3 [internal function]: spl_autoload_call('Contao\\BackendU...')
contao/contao#4 /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ClassExistenceResource.php(78): class_exists('Contao\\BackendU...')
contao/contao#5 /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(371): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
contao/contao#6 /mnt/web318/e1/81/52170081/htdocs/MOB in /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/contao/core-bundle/src/Resources/contao/classes/BackendUser.php on line 32
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception

In ScriptHandler.php line 113:
                                                                               
  An error occurred while executing the "contao:install-web-dir" command: PHP  
   Fatal error:  During class fetch: Uncaught ReflectionException: Class User  
   not found in /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/contao/core-  
  bundle/src/Resources/contao/classes/BackendUser.php:32                       
  Stack trace:                                                                 
  #0 /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/composer/ClassLoader.ph  
  p(444): include('/mnt/web318/e1/...')                                        
  contao/contao#1 /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/composer/ClassLoader.ph  
  p(322): Composer\Autoload\includeFile('/mnt/web318/e1/...')                  
  contao/contao#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Contao\\B  
  ackendU...')                                                                 
  contao/contao#3 [internal function]: spl_autoload_call('Contao\\BackendU...')             
  contao/contao#4 /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/symfony/symfony/src/Sym  
  fony/Component/Config/Resource/ClassExistenceResource.php(78): class_exists  
  ('Contao\\BackendU...')                                                      
  contao/contao#5 /mnt/web318/e1/81/52170081/htdocs/MOB-Neu/vendor/symfony/symfony/src/Sym  
  fony/Component/DependencyInjection/ContainerBuilder.php(371): Symfony\Compo  
  nent\Config\Resource\ClassExistenceResource->isFresh(0)                      
  contao/contao#6 /mnt/web318/e1/81/52170081/htdocs/MOB in /mnt/web318/e1/81/52170081/htdo  
  cs/MOB-Neu/vendor/contao/core-bundle/src/Resources/contao/classes/BackendUs  
  er.php on line 32                                                            
                                                                               

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

# Process terminated with exit code 1
# Result: General error

---

**Comment by aschempp** [comment]
@Toflar why is this a contao-manager issue to you?

**Comment by danielr-mm** [comment]
Noch ein paar weitere Infos: Manager ist v1.17 und Contao v 4.4.39

Der Fehler passiert beim "updating composer dependencies", manchmal bei Versuch 1/5 oder auch 4/5. Das Schlimme ist, dass nach diesem Fehler die ganze Contao Installation/Seite nicht mehr angezeigt wird (weiße Seite, Error 500) und man auch nicht mehr ins Backend kommt. Der Manager weißt danach auf eine fehlerhafte Installation hin und bietet die Reparatur oder den Safe Mode an. Beides ended auch in dem Fehler und man muss die Seite neu aufsetzen.

**Comment by Schneetiger** [comment]
Habe seit ein paar Wochen das gleiche Problem mit dem CM 1.1.2; verwende PHP 7.3 und hoste bei Webgo. Außerdem kann ich anscheinden keine Paketaktualiserung mehr fahren, denn wenn ich nach komplett durchgelaufener Aktualisierung erneut die Prüfung durchlaufen lasse, zeigt er mir die selbe Anzahl an möglichen Updates an wie beim ersten Mal.

Nun habe ich nachfolgende Meldung des CM erhalten; muss dazu sagen, dass ich mein Mailformular auf das smtp-Protokoll umgestellt habe und Webgo aös Verschlüsselung StartTLS verwendet. Mit denen habe ich auch schon Kontakt aufgenommen; allerdings ist meine Website noch aufrufbar und funktionsfähig. Lediglich das Mailformular übermittelt keine Mails.
![Screenshot_2020-01-17 Contao Manager 1 2 2 contao4 Fehlermeldung](https://user-images.githubusercontent.com/29976466/72599268-a1342d80-3911-11ea-8304-7423647e10a9.png)

**Comment by contaoacademy** [comment]
@Schneetiger 
Wie sieht die Mailkonfiguration in deiner `parameters.yml` aus?
Als Verschlüsselung ist nur `tls` bzw `ssl` möglich.
Hast du hier `StartTLS` geschrieben?

**Comment by Schneetiger** [comment]
@contaoacaemy
Ja. webGo bietet standardmäßig StartTLS an; auf Nachfrage bekommt man aber auch SSLTLS; SSL oder TLS angeboten. Die haben aus Performancegründen, lt. deren Aussage ,erst kürzlich auf StartTLS umgestellt. Inzwischen habe ich auch SSLTLS; SSl und TLS ausprobiert; das Ergebnis ist unverändert und ich erhalte sogar eine weiße Seite, wenn ich meine Website aufrufe; habe das über einen Restore inzwischen wieder hingebogen.
Also verstehe ich das richtig; Contao 4.4 versteht aktuell lediglich SSL und TLS?

**Comment by fritzmg** [comment]
`STARTTLS` ist keine Verschlüsselungsmethode. Das ist ein verfahren um unverschlüsselte Verbindungen auf verschlüsselte Verbindungen hochzuheben. 

Du musst als Verschlüsselungsmethode für deinen SMTP Server entweder `ssl` oder `tls` wählen.

**Comment by fritzmg** [comment]
@Schneetiger bitte in Zukunft bei solchen Dinge zuerst die Community konsultieren. Du bist hier abgesehen davon auch im falschen Ticket.

**Comment by Schneetiger** [comment]
Sorry, danke für die Info. Die Community hatte ich schon kontaktiert; leider bisher ohne Ergebnis. Da es sich um einen General Error dreht, dachte ich, das wäre ein Thema für hier, da hier jemand schon mal so ein Problem hatte (danielr-mm). Übrigens, danke für die Aufklärung und Antworten. Ich behalte jetzt mal SSL-Methode. Ich melde mich dann mal hier ab.

**Comment by fritzmg** [comment]
> Die Community hatte ich schon kontaktiert; leider bisher ohne Ergebnis.

Mir wäre kein Thread bekannt 😁

**Comment by Schneetiger** [comment]
@fritzmg; das wäre der Link dazu
[https://community.contao.org/de/showthread.php?74592-Formular-wird-nicht-gesendet](url). habe auch ne Menge Screenshots und zwei PDFs dort beigelegt. Der Titel des Threads lautet  "4.7.x Formular wird nicht gesendet". Ich verwende aktuell die C 4.4.

Noch eine letzte Bitte: Ich möchte hier nicht unnötig aufschlagen und eure wertvolle Zeit stehlen; wie kann ich in Zukunft so was verhindern oder wann soll/kann man sich hier melden? Vielen Dank für deine Hilfe und Geduld.

**Comment by fritzmg** [comment]
In diesem Contao Community Thread wurde dir ja schon gesagt was du machen musst.

**Comment by Schneetiger** [comment]
Sorry für meine späte Antwort. Ja, anfänglich hatte ich die StartTLS eingetragen, weil ich die Daten aus meinem Account eines zu eins übernommen hatte. Nun habe ich die auf tls und Port 587 geändert.

Funktioniert trotzdem nicht; ich glaube, dass beim letzten Update was schief lief. Die Internetverbindung bricht bei mir nämlich manchmal ab; anscheinend zu viel Traffic in der Umgebung.

Ich werde jetzt mal ein Backup einspielen und melde mich dann wieder; braucht aber etwas Zeit.

Was mir auffiel, der CM meldet mir 13 Updates und versucht diese einzuspielen. Wenn ich dann den ganzen Prozess habe durchlaufen lassen, und erneut nach Updates suche, meldet er mir wieder diese 13 Updates. Ergo, diese konnte er nicht installieren. Daher dürfte evtl. auch das Mailformular trotz smtp-Einstellung nicht funktionieren.

Vielen Dank für Deine Geduld und Hilfe. Ich melde mich, wie gesagt, wieder

⁣Freundliche Grüße
Detlef Rimböck

Gesendet mit BlueMail ​
