### ISSUE TITLE
Link "Passwort vergessen?"

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#450]
Der Link "Passwort vergessen?" im Anmeldeformular führt derzeit zu https://github.com/contao/contao-manager/issues/14.

Eine direkte Verlinkung zu https://docs.contao.org/books/manager/de/faq.html#contao-manager-zugangsdaten-vergessen würde dies abkürzen.

**Comment by aschempp** [comment]
Let's update this once the new manual is here 🙃 

/cc @netzarbeiter

**Comment by aschempp** [comment]
New link: https://docs.contao.org/manual/installation/contao-manager/#hast-du-die-zugangsdaten-vom-contao-manager-vergessen

**Comment by aschempp** [comment]
Closed in favor of #14
