### ISSUE TITLE
Sprache springt zu Englisch

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#451]
In Chrome springt die Sprache während des Ladevorgangs von Deutsch zu Englisch:
1. Browserdaten löschen
2. contao-manager.phar.php aufrufen
3. Das Login-Formular wird geladen und in Deutsch angezeigt
4. Wenige Sekunden später, nach vollständigem Abschluss des Ladevorgangs, wechselt die Sprache automatisch zu Englisch

In Firefox konnte ich dieses Problem nicht feststellen.

**Comment by xchs** [comment]
Das beobachte ich auch immer wieder. Dazu gibt es auch schon einige Tickets: https://github.com/contao/contao-manager/issues/362, https://github.com/contao/contao-manager/issues/368

**Comment by Mynyx** [comment]
Dann hoffe wir mal, dass dieses Ticket nicht auch geschlossen wird. :wink:

Ich habe außerdem noch herausgefunden, dass das Problem unabhängig davon auftritt, ob `contao_manager_locale` gesetzt ist oder nicht.

**Comment by Mynyx** [comment]
Könnte es sein, dass die Ursache im Aufruf `i18n.load('en');` in https://github.com/contao/contao-manager/blob/master/src/i18n/index.js#L74 liegt?

**Comment by fritzmg** [comment]
> Dann hoffen wir mal, dass dieses Ticket nicht auch geschlossen wird. 😉

#368 was closed because it's a duplicate of #362 and #362 was closed by @xchs because it was reportedly fixed back then.

**Comment by aschempp** [comment]
Bug should be fixed in version 1.2
