### ISSUE TITLE
Hosting: EDIS - PHP binary

### ISSUE THREAD

**Issue by pressi** [contao/contao-manager#452]
**Affected version(s)**
Contao: 4.4.43
Contao Manager: 1.1.7

**Description**  
Contao Manager - System Check läuft nicht durch.

![image](https://user-images.githubusercontent.com/1610762/65487930-3b2a2300-dea8-11e9-9eaf-97af3c44e1ca.png)

Wenn Ich bei der Konfiguration "Other" auswähle und beim PHP Binary den Pfad von hier [EDIS PHP INFO](https://support.edis.at/kb/a93/nuetzliche-infos-zu-php-eigenen-einstellungen-mittels-_user_ini-und-beispiel-php_ini-dateien.aspx) eingebe, lässt er das nicht zu.

LG

**Comment by aschempp** [comment]
EDIS müsste doch bereits in der Auswahl der Hosting-Optionen erscheinen? Geht es damit auch nicht?

**Comment by pressi** [comment]
> EDIS müsste doch bereits in der Auswahl der Hosting-Optionen erscheinen? Geht es damit auch nicht?

Nein, der Screenshot ist wenn EDIS GmbH ausgewählt wurde.

**Comment by aschempp** [comment]
dann hat der Hoster wohl etwas an seinem Setup geändert. Solche Fehler treten auch auf wenn das PHP Binary auf der Kommandozeile eine Warnung ausgibt (z.B. weil eine Bibliothek geladen werden soll die es auf dem Server nicht gibt). Vielleicht siehst du etwas dazu wenn du die PHP-Binary selber per SSH auf der Kommandozeile ausführst.

**Comment by aschempp** [comment]
Alternativ kannst du dich gerne auch per E-Mail bei mir melden (siehe mein GitHub Profil) wenn du mir einen SSH-Zugang zu diesem Server geben kannst.

**Comment by pressi** [comment]
> Alternativ kannst du dich gerne auch per E-Mail bei mir melden (siehe mein GitHub Profil) wenn du mir einen SSH-Zugang zu diesem Server geben kannst.

Danke, habe jetzt das Contao Manager Update auf 1.2.0 gemacht und jetzt funktioniert es.

![image](https://user-images.githubusercontent.com/1610762/66765944-3bb54880-eead-11e9-85fe-db840e191e98.png)
