### ISSUE TITLE
Installationsproblem mit CM 1.17 und C 4.8

### ISSUE THREAD

**Issue by Schneetiger** [contao/contao-manager#457]
Beim Update innerhalb der Version 4.8 und bei der Neuinstallation von 4.8 wird der Konsolentask mit einer Fehlermeldung abgebrochen. Der Webspace bei WebGo ist ordnungsgemäß eingerichtet, aber die Installation der Composer-Umgebung läuft nicht durch und wird abgebrochen. Auch im abgesicherten Modus erscheint diese Fehlermeldung/dieser Hinweis.
![Screenshot_2019-10-04 Contao Manager 1 1 7](https://user-images.githubusercontent.com/29976466/66226775-ed998b80-e6db-11e9-8baa-fc7b22d947e6.png)
![Screenshot_2019-10-04 Contao Manager 1 1 7](https://user-images.githubusercontent.com/29976466/66226841-1457c200-e6dc-11e9-82e7-4b78f0e88fbe.png)

**Comment by aschempp** [comment]
Hast du eine Fehlermeldung in der Kommandozeilen-Ausgabe?

**Comment by Schneetiger** [comment]
Servus Andreas,

entschuldige meine späte Antwort. "Leider" arbeite ich nur mit dem CM; zeitlich konnte ich mich noch nicht mit der Kommandozeile befassen. Im CM erscheint weiter keine Meldung, aber er fällt immer wieder in die Prüfroutine zurück. Ich checke das heute nochmal und melde mich dann umgehend bei Dir
Vielen Dank für die Rückfrage.

⁣Freundliche Grüße
Detlef Rimböck

Gesendet mit BlueMail ​

**Comment by Schneetiger** [comment]
Servus Andreas,

habe gestern den CM auf 1.2.0 aktualisiert und konnte die Composer-Umgebung ohne Probleme installieren. Soweit alles gut. Bzgl. der Kommandozeile; die hatte ich damals deaktiviert gehabt.
Vielen Dank für die schnelle Hilfe und die tolle Arbeit des Core-Teams und des gesamten Teams👍👍.

⁣Liebe Grüße
Detlef Rimböck

Gesendet mit BlueMail ​
