### ISSUE TITLE
More compact list view

### ISSUE THREAD

**Issue by leofeyer** [contao/contao-manager#46]
Here is a mockup for a more compact list view, because the current view takes up a lot of height and requires a lot of scrolling. Also, most packages will never have an image, so I have removed the grey placeholder icon.

![bildschirmfoto 2017-01-24 um 13 29 26](https://cloud.githubusercontent.com/assets/1192057/22247262/32c5c5b6-e239-11e6-8f19-9f9e8360f329.png)

Obviously, this is not a top priority change.

**Comment by aschempp** [comment]
The package list is now more compact (5bc97ada64322539c452dbc3db4481bfaef6f8a7)
