### ISSUE TITLE
Eigene URL für ComposerCloud

### ISSUE THREAD

**Issue by muellerlukas** [contao/contao-manager#462]
Eine Möglichkeit eine eigene URL für ComposerCloud zu hinterlegen wäre toll.
Die Grundidee die Berechunngen einen anderen Server zu machen finde ich super.
Die Gründe dazu auch klar.
Unschön finde ich aber die Tatsache, dass das meinen Einflussbereich dann verlässt.
Auch wenn die Serversoftware wohl nicht veröffentlicht werden soll würde ich es begrüßen die URL dazu manuell einstellen zu können.
Die APIs dazu sind ja gut dokumentiert. Somit kann auch jeder seine eigene Serversoftware schreiben.

**Comment by aschempp** [comment]
Ich sehe aktuell keinen Sinn für eine solche Option, welche von 0.01% der Nutzer verwendet würde. Wenn du die Cloud nicht nutzen willst, kannst du sie deaktivieren, dann musst du dafür sorgen dass dein Server entsprechend funktioniert. Falls das nicht reicht, der Contao Manager ist Open Source und du kannst dir jederzeit eine Version bauen welche das nach allen Bedürfnissen anpasst.
