### ISSUE TITLE
Installation bricht nach dem herunterladen der Dateien ab

### ISSUE THREAD

**Issue by Vrathos** [contao/contao-manager#463]
**Affected version(s)**
4.4

**Description**  
Meine Installation bricht immer an der selben stelle ab. (Siehe Screenshot. Wenn ich dann versuche den Manager nochmal aufzurufen bekomme ich ein "403 Zugriff verweigert" fehler.
Die einzige Möglichkeit wieder in den Manager zu kommen ist die .htaccess Datei zu löschen was mir aber nicht viel bringt da die Installation trotzdem nicht abgeschlossen ist. Wenn ich dann eine Reparatur durchführe geht das Spiel von vorn los.
![Screenshot_1](https://user-images.githubusercontent.com/14226181/66403283-9e5aa000-e9e6-11e9-97af-c1953f86d526.png)

**Comment by xchs** [comment]
Ist am Webspace noch genügend freier Speicher für die Installation vorhanden?

**Comment by Vrathos** [comment]
Ja mehr als genug, 2 GB.
