### ISSUE TITLE
Cache für cloud resolver

### ISSUE THREAD

**Issue by Coding-Kiwi** [contao/contao-manager#464]
**Description**  

Wäre es nicht sinnvoll, die composer.json zu hashen und das dazugehörige Ergebnis des Cloud Resolvers abzuspeichern wenn es ankommt?

Momentan ist es so dass wenn ich einen dry-run mache und danach einen richtigen run, resolved er zweimal komplett die composer abhängigkeiten obwohl es nur einmal nötig wäre.

Oder verstehe ich die Funktionsweise falsch?

**Comment by xchs** [comment]
Duplicate of https://github.com/contao/contao-manager/issues/423
