### ISSUE TITLE
Favicon blinkt immer

### ISSUE THREAD

**Issue by thjapan** [contao/contao-manager#465]
Manager 1.2.0
Im Manager angemeldet kein blicken.
Prod.-Cache gelöscht: Favicon blinkt (Hacken, dann Contao-Logo usw.... )
Dann unter dem Zahnrad auf Abmelden geklickt. Favicon blinkt weiter.
Erst nach einem Reload ist es vorbei.

Browser Chrome

**Comment by rburch** [comment]
Yeah the favicon flashing is generally annoying. I can live with it if it only flashed while processing something but prefer an unanimated icon.
