### ISSUE TITLE
CM 1.2.0 erkennt PHP-Binary nicht mehr

### ISSUE THREAD

**Issue by exscorp** [contao/contao-manager#466]
**Affected version(s)** 
1.2.0

**Description**  
gestern mit der Version 1.1.8 und drunter funktionierte die **Individuelle Konfiguration** für PHP-Binary ohne Probleme. Wenn ich unter **Configuration** » **Andere …** ausgewählt hatte, erkannte CM die PHP-Binary automatisch und nahm diese auch an.

Gerade hat der CM auf 1.2.0 aktualisiert und seit dem erkennt er keine PHP-Binary und nimmt auch keine an, wenn ich diese Manuell eintrage.

Habe auch versucht alles vom CM zu löschen und neu zu installieren ohne Erfolg.

» **php contao-manager.phar.php about** gibt folgendes aus:

**Contao Manager**
Version                 1.2.0
Environment             prod
Debug                   false
Cache directory         phar:///home/demo/public_html/web/contao-manager.phar.php/api/Resources/cache
Contao directory        /home/demo/public_html/web
Data directory          /home/demo/public_html/web/contao-manager

**PHP**
Version                 7.3.9
Architecture            64 bits
Server API              cli
Intl locale             de_DE
Timezone                UTC
Binary Path             /opt/cpanel/ea-php73/root/usr/bin/php

**Edit:** eine Fehlermeldung gibt der CM nicht aus aber der Server gibt folgendes aus:

`[Fri Oct 11 12:04:05.690876 2019] [fcgid:warn] [pid 11379:tid 139912298927872] [client xx.xx.xx.xx:53364] mod_fcgid: stderr: [2019-10-11 10:04:05] app.ERROR: Unexpected output from "/opt/cpanel/ea-php73/root/usr/bin/php -q /home/demo/public_html/web/contao-manager.phar.php test": \x1f\x8b\b, referer: https://domain.de/contao-manager.phar.php/`

**Comment by ngdot** [comment]
Gleiches Problem hier, allerdings bei einer Neuinstallation. 
Der Prozess schlägt bei "Serverkonfiguration" fehl und schmeißt die untenstehende Fehlermeldung.

Wenn ich eine ältere contao-manager.phar.php benutze, findet er meinen individuellen PHP-Pfad und alles funktioniert problemlos.

`2019/10/11 09:17:10 [error] 28144#28144: *389 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: explode() expects parameter 2 to be string, bool given in phar:///usr/share/nginx/html/web/contao-manager.phar.php/api/Process/PhpExecutableFinder.php:129
Stack trace:
#0 phar:///usr/share/nginx/html/web/contao-manager.phar.php/api/Process/PhpExecutableFinder.php(129): explode(':', false)
#1 phar:///usr/share/nginx/html/web/contao-manager.phar.php/api/Process/PhpExecutableFinder.php(71): Contao\ManagerApi\Process\PhpExecutableFinder->findExecutables()
#2 phar:///usr/share/nginx/html/web/contao-manager.phar.php/api/Controller/Server/ConfigController.php(108): Contao\ManagerApi\Process\PhpExecutableFinder->find()
#3 phar:///usr/share/nginx/html/web/contao-manager.phar.php/api/Controller/Server/ConfigController.php(87): Contao\ManagerApi\Controller\Server\ConfigController->getTestResult()
#4 phar:///usr/share/nginx/html/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(151): Contao\ManagerApi\Controller\Server\ConfigController->__...PHP message: [2019-10-11 09:17:10] request.INFO: Matched route "contao_managerapi_server_config__invoke". {"route":"contao_managerapi_server_config__invoke","route_parameters":{"_route":"contao_managerapi_server_config__invoke","_controller":"Contao\\ManagerApi\\Controller\\Server\\ConfigController"},"request_uri":"https://192.168.50.11/contao-manager.phar.php/api/server/config","method":"GET"} []PHP message: [2019-10-11 09:17:10] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":2} []PHP message: [2019-10-11 09:17:10] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []PHP message: [2019-10-11 09:17:10] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []PHP message: [2019-10-11 09:17:10] security.DEB
`

**Comment by aschempp** [comment]
Ich kann den Fehler nur reproduzieren wenn mir jemand von euch einen SSH-Zugang zum entsprechenden Server per E-Mail senden kann (Mail in meinem GitHub Profil).

**Comment by Metis77** [comment]
gleicher Fehler auf default Plesk Servern.

Ist ein SSH Zugang noch benötigt?

**Comment by ngdot** [comment]
Ich kann leider keinen bereitstellen, Problem tritt lokal in meiner VM auf. Könnte höchstens die Vagrantfile inkl. provision zur Verfügung stellen.

**Comment by aadlung** [comment]
Hi,

schaut man sich die Datei PhpExecutableFinder.php an - sieht man dass sie sich auf ein `getenv('PATH')` verlässt. Das gibt's normalerweise in PHP z.B. über FPM garnicht. Generell, das ganze Routing über die phar.php mit den sub-pfaden erfodert spezielle Nginx/FPM Konfiguration um das zu erlauben.

In dem PHP pool (php-fpm) hat bei mir folgendes geholfen:

`env["PATH"] = $PATH`

LG
Andy

**Comment by aschempp** [comment]
`PATH` sollte keine Anforderung sein, das wir nur genutzt um Binaries zu finden. Wenn du einen Pfad explizit angibst kommen die entsprechenden Methoden nicht zum Zug. Die Methode `findBestBinary` wird direkt mit dem angegebenen Pfad ausgeführt.

**Comment by aadlung** [comment]
OK - bei meinem Server hat das zumindest geholfen die PFAD Variable hinzuzufügen, da ich dem Browser bei /contao-manager.phar.php ja keine Infos weiter mitgegeben habe.

**Comment by aschempp** [comment]
wie meinst du das? Du hast in den Hosting-Einstellungen keinen Pfad zum Binary von Hand eingegeben?

**Comment by aadlung** [comment]
So weit kam ich garnicht - der Fehler trat vorher auf, bei "Serverkonfiguration" wurde es rot, danach kommt ein fullscreen overlay mit dem Fehler.  Mit der PATH variable klappts.
`
ERROR 500 Error: Uncaught TypeError: explode() expects parameter 2 to be string, bool given in phar:///var/www/example/web/contao-manager.phar.php/api/Process/PhpExecutableFinder.php:129 Stack trace: #0 phar:///var/www/example/web/contao-manager.phar.php/api/Process/PhpExecutableFinder.php(129): explode(':', false) #1 phar:///var/www/example/web/contao-manager.phar.php/api/Process/PhpExecutableFinder.php(71): Contao\ManagerApi\Process\PhpExecutableFinder->findExecutables() #2 phar:///var/www/example/web/contao-manager.phar.php/api/Controller/Server/ConfigController.php(108): Contao\ManagerApi\Process\PhpExecutableFinder->find() #3 phar:///var/www/example/web/contao-manager.phar.php/api/Controller/Server/ConfigController.php(87): Contao\ManagerApi\Controller\Server\ConfigController->getTestResult() #4 phar:///var/www/example/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(151): Contao\ManagerApi\Controller\Server\ConfigController->__invoke(Object(Symfony\Component\HttpFoundation\Request)) #5 phar:///var/www/example/web
`

**Comment by aschempp** [comment]
Ah, das bezieht sich auf einen zweiten Fehler. Gibt es bei dir/PHP-FPM in den Environment Variablen irgend einen Pfad den wir nutzen können, da `PATH` nicht existiert?

**Comment by aadlung** [comment]
Nein, die normale LAMPP/NginX Konfiguration bietet keinerlei Pfade aus der Linux Umgebung wie eine $PATH Variable.
Aber wie gesagt - für mich ist das Problem gelöst, wobei das natürlich mein eigener Server ist wo das leicht geht.

**Comment by aschempp** [comment]
das initiale Problem von @exscorp ist damit aber wohl (noch) nicht gelöst…

**Comment by aadlung** [comment]
> das initiale Problem von @exscorp ist damit aber wohl (noch) nicht gelöst…

das stimmt - das hat damit nichts zu tun

**Comment by exscorp** [comment]
SSH-Zugang darf ich bei diesem Kundenserver nicht bereitstellen, kann aber versuchen zu debuggen wenn du mir eine kurze Anleitung gibst.

**Comment by kroerig** [comment]
Ich hatte diesen Effekt gerade auch mit 1.2.2. Hatte PHP von 7.2 auf 7.3 geändert und bisher hat der CM den richtigen Pfad zum Binary selbst gefunden.

**Comment by exscorp** [comment]
Hallo, das Problem hat sich erledigt.

Habe die Tage nochmal das Forum und die issues hier durchgeschaut und mir ist die Sache mit dem "zlib.output_compression" hier https://github.com/contao/contao-manager/issues/348 aufgefallen. Da dies auf dem Server auch aktiv ist, habe ich es testweise deaktiviert. Jetzt wird die Binary wieder direkt erkannt und akzeptiert.

@kroerig vielleicht ist es bei dir auch so? Ansonsten kann das Ticket geschlossen werden.
