### ISSUE TITLE
CM 1.2.0 unter XAMPP kann Erweiterungen nicht installieren bzw. updaten

### ISSUE THREAD

**Issue by berecont** [contao/contao-manager#467]
Contao 4.8.4 und CM 1.2.0 und XAMPP lokal
Installation läuft durch aber es lassen sich keine Erweiterungen installieren. Der CM bricht mit Fehlermeldung ab
https://community.contao.org/de/showthread.php?76168-Installationen-mit-CM-schlagen-fehl&p=512417&viewfull=1#post512417

Via Konsole lassen sich die Erweiterungen korrekt installieren.

**Comment by aschempp** [comment]
da ich selber kein XAMPP und Windows habe, kann ich das nur schwerlich testen. Vielleicht kann ein PHP Entwickler das mit dem Contao Manager debuggen?

**Comment by webwerkwien** [comment]
Ich habe das selbe Problem mit CM 1.2.0, unter PHP 7.2, Contao 4.4.44. Ich habe dann alles neu aufgesetzt, Contao Core lies sich noch installieren. Aber von den Erweiterungen geht keine einzige.

**Comment by Kahru** [comment]
Hallo Andreas, es gibt ein Routing-Problem zwischen Xampp und Contao 4. Bei einer Extension die ich gerade aufsetze habe ich gesehen, dass die Pfade in der plugin.php unter Xampp nicht korrekt aufgelöst werden. Da steht dann so ein Mist al la c:\xampp\htdocs\c4\.../foo/foo.php im Routing-Pfad.

**Comment by fritzmg** [comment]
@Kahru das ist grundsätzlich nicht falsch und insbesondere kein "Mist" ;)

**Comment by fritzmg** [comment]
@Kahru das ist grundsätzlich nicht falsch und insbesondere kein "Mist" ;)

**Comment by fritzmg** [comment]
> Ich habe das selbe Problem mit CM 1.2.0, unter PHP 7.2, Contao 4.4.44. Ich habe dann alles neu aufgesetzt, Contao Core lies sich noch installieren. Aber von den Erweiterungen geht keine einzige.

Poste die Konsolenausgabe. Evt. hat dein Problem gar nichts mit diesem Ticket zu tun.

**Comment by webwerkwien** [comment]
Ich kann das Problem nun eingrenzen! Wenn ich die Composer Resolver Cloud nicht verwende, laufen die Installationen durch! Eventuell ist das Kontingent wieder aufgebraucht.

**Comment by Toflar** [comment]
Nope, ist es nicht. Sowas wie ein Kontingent gibt es auch nicht :)

**Comment by berecont** [comment]
Ohne 'Die Composer Resolver Cloud verwenden', also Häkchen raus, läuft ein Update und die Installation einwandfrei durch.

**Comment by mlwebworker** [comment]
@aschempp Wir können gern bei mir debuggen. Ich kann das Problem bestätigen sobald der Cloud Resolver verwendet wird.

**Comment by masterbekky** [comment]
Ich hatte das gleiche Problem... Lokale XAMPP installation mit Contao 4.8. Mit Composer Cloud schlug die installation von Isotope fehl. Danach war alles kaputt. Ohne Cloud funktioniert die installation allerdings funktioniert nun das css meiner Theme nicht mehr :(

**Comment by aschempp** [comment]
Meine Güte… @mlwebworker und ich hab das nun ca. 5 Stunden debuggt. Aus unbekanntem Grund wird die erste Verbindung zwischen dem Manager und der Cloud blockiert und der Manager-Prozess beendet. Wir starten jetzt einfach ein zweites Mal und dann geht's 🤷‍♂
