### ISSUE TITLE
Metapackages are not recognized anymore

### ISSUE THREAD

**Issue by dmolineus** [contao/contao-manager#468]
**Affected version(s)**

 - Contao Manager 1.2.0

**Description**  

As #135 was implemented, meta packages are recognized and available for installing with the Contao Manager. Since version 1.2.0 was released, it isn't anymore. @aschempp noted in the slack channel, the automated detected was removed but using package metadata would help. In fact, it doesn't. A meta package which is described with metadata isn't avialable in the Contao Manager.

https://contao.slack.com/archives/CLTUNH78X/p1570704499004000?thread_ts=1570704374.002700&cid=CLTUNH78X
https://contao.slack.com/archives/CLTUNH78X/p1570712017007200?thread_ts=1570704374.002700&cid=CLTUNH78X

**How to reproduce**  

1. Confirm that the bundle is documented in the package metadata, see https://github.com/contao/package-metadata/tree/master/meta/contao-bootstrap/bundle
2. Search for "contao bootstrap bundle" in the contao manager
3. The packages `contao-bootstrap/bundle` isn't listed

**Comment by zonky2** [comment]
the same with https://github.com/contao/package-metadata/pull/144
search with https://extensions.contao.org/?q=metamodels%2Fbundle_all&pages=1 is empty

**Comment by Toflar** [comment]
This should be fixed now.

**Comment by zonky2** [comment]
thx
