### ISSUE TITLE
Aktuelle Aktion wird gestoppt … stoppt nicht

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#470]
**Affected version(s)**
C 4.4.44
CM 1.2.0

**Description** 
* es wurde versucht das Paket `metamodels/country` zu laden - folgende Meldung:
```
$ /usr/bin/php72 -q -d memory_limit=-1 /www/htdocs/xyz123/html/contao4/web/contao-manager.phar.php composer require metamodels/attribute_country --no-suggest --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL: Handshake timed out
Failed to enable crypto
failed to open stream: operation failed
https://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
``` 
* Button Abbruch
```
### Der Hintergrundprozess wird abgebrochen ###
```
* dann gehts nicht weiter... bei reload der CM-Startseite kommt man immer wieder auf das Fenster
* Konsole: `task.json`wird per Ajax geladen mit 200 und es erscheint die Meldung `Ein Versuch wurde unternommen, eine Nicht-UTF8-Kodierung für JSON zu verwenden, das per XMLHttpRequest geholt wurde. Nur UTF-8 wird für die Dekodierung von JSON unterstützt.`

**Workaround**
* task.json gelöscht

**Hinweis**
Installation über
```/usr/bin/php72 -d memory_limit=-1 web/contao-manager.phar.php composer require metamodels/attribute_country```
hat funktioniert

**Comment by aschempp** [comment]
War das ein einmaliger/zufälliger Fehler oder lässt sich das wiederholen, auch auf verschiedenen Browsern und Servern?

**Comment by zonky2** [comment]
Im Grunde wird das Fenster nicht gekillt, wenn Button "Abbruch" gesetzt
* kann wiederholt werden
* FF, Chrome getestet

**Comment by aschempp** [comment]
bekommst du einen Fehlermeldung in der Javascript-Konsole?

**Comment by aschempp** [comment]
This issue was closed because it has not had recent activity.
