### ISSUE TITLE
Unklare Anzeige der Anzahl unbestätigte Änderungen

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#474]
Bei einer Installation von Contao mit einer Erweiterung, wird nach Klick auf den Button "Pakete aktualisieren" der Hinweis "Sie haben 4 unbestätigte Änderungen." angezeigt. Es ist unklar, wie sich die Anzahl von 4 ergibt.

![image](https://user-images.githubusercontent.com/1632642/67617356-a38b5d80-f7e2-11e9-9152-40620dd3b660.png)

**Comment by aschempp** [comment]
Vermutlich aus allen vorhandenen Paketen, wobei `contao/conflicts` nicht angezeigt wird, und `contao/calendar-bundle` immer automatisch aktualisiert wird. Denke das ist ein Bug im Button.
