### ISSUE TITLE
Fehlermeldung "Der Contao Manager konnte einen Konsolentask nicht starten!" während Update auf 1.2.1

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#479]
Während dem Update von 1.2.0 auf 1.2.1 wird folgende Fehlermeldung angezeigt, die nach wenigen Sekunden automatisch verschwindet. Anschließend erscheint ein Meldung, dass das Update erfolgreich durchgeführt wurde.

![image](https://user-images.githubusercontent.com/1632642/68059376-9697ce00-fcfc-11e9-990b-992afe0c9eb4.png)

**Comment by fritzmg** [comment]
Konnte ich auch bei früheren Versionen schon feststellen - bin mir aber nicht sicher bei welchen Versionssprüngen.

**Comment by aschempp** [comment]
In Version 1.3 wurde diese Behandlung verbessert. Ich gehe davon aus dass dies damit erledigt ist.
https://contao.org/de/news/contao-manager-1-3-0-verfuegbar.html
