### ISSUE TITLE
Manager < 1024px Menü nicht lesbar

### ISSUE THREAD

**Issue by Stefko** [contao/contao-manager#480]
Mir ist auf einem Mobilgerät aufgefallen, dass sich das Menü über das Burger-Icon zwar öffnet, dessen Inhalt aber nicht lesbar ist. Kann dies auch auf dem Desktop nachvollziehen., siehe Screenshot.
![Bildschirmfoto 2019-11-03 um 11 43 35](https://user-images.githubusercontent.com/418962/68083996-fd69d400-fe2f-11e9-9c6c-ce72fdead1c4.png)

**Comment by aschempp** [comment]
Auf welchem Browser/OS hast du dieses Problem?

**Comment by saress** [comment]
Kann ich auf meinem Android Handy Samsung Galaxy S10 mit Google Chrome ebenfalls bestätigen. Version 78.0.x

Beste Grüße 
Saress

**Comment by Stefko** [comment]
Mobil: iOS13 Safari (aktuell)
Desktop: macOS 10.12 mit aktuellem Chrome und Firefox
gerade mal noch in ner VM unter elemtaryOS mit Midori (alt) getestet, da ist der Manager gar nicht erreichbar, sprich die Seite bleibt leer

**Comment by ausi** [comment]
This issue is caused by `#app { overflow-y: scroll; }` from https://github.com/contao/package-list/commit/a1424b851fe18189f99fa0f9e30fb13dabb74da9 I think.
