### ISSUE TITLE
Uncaught TypeError: trim() expects parameter 1 to be string, boolean given

### ISSUE THREAD

**Issue by baddy1000** [contao/contao-manager#481]
**Affected version(s)**
Contao 1.2.1, 1.2.0, maybe more

Contao 1.1.4, 1.1.3 with a different error report.

**Description**  
Tried a fresh Contao installation.

Reported back with this:

```
ERROR 500 Error: Uncaught TypeError: trim() expects parameter 1 to be string, boolean given in phar:///.../web/contao-manager.phar.php/api/System/SelfUpdate.php:211 Stack trace: 
#0 phar:///.../web/contao-manager.phar.php/api/System/SelfUpdate.php(211): trim(false)
#1 phar:///.../web/contao-manager.phar.php/api/System/SelfUpdate.php(196): Contao\ManagerApi\System\SelfUpdate->getRemoteInfo()
#2 phar:///.../web/contao-manager.phar.php/api/System/SelfUpdate.php(122): Contao\ManagerApi\System\SelfUpdate->checkForUpdate()
#3 phar:///.../web/contao-manager.phar.php/api/Controller/Server/SelfUpdateController.php(40): Contao\ManagerApi\System\SelfUpdate->getNewVersion()
#4 phar:///.../web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(151): Contao\ManagerApi\Controller\Server\SelfUpdateController->__invoke(Object(Contao\ManagerApi\System\SelfUpdate))
```

Someone on the Contao forums suggested using an older Contao version, so I tried running 1.1.3 and 1.1.4, both returning the error
`
Version request returned incorrectly formatted response.
`

**How to reproduce**  

Not exactly sure, I installed Contao like usual.

**Comment by fritzmg** [comment]
@baddy1000 try the [Contao Check](https://github.com/contao/check/) if an SSL connection to contao.org can be made on your hosting environment.

**Comment by baddy1000** [comment]
![image](https://user-images.githubusercontent.com/15890453/68195204-bd812900-ffb6-11e9-81c7-c47ba58d9b32.png)

![image](https://user-images.githubusercontent.com/15890453/68195234-cc67db80-ffb6-11e9-90db-7bfaf364581f.png)

![image](https://user-images.githubusercontent.com/15890453/68195275-dc7fbb00-ffb6-11e9-9362-d18e542239e9.png)

**Comment by baddy1000** [comment]
Provider also sent me a message telling me SSL connection should work:

root@path:/# curl https://update.contao.org
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<meta http-equiv="refresh" content="0;url=https://update.contao.org/en/"/>
<title>Redirecting to https://update.contao.org/en/</title>
</head>
<body>
Redirecting to <a href="https://update.contao.org/en/">https://update.contao.org/en/</a>.
</body>

**Comment by fritzmg** [comment]
Yeah as suspected you are unable to connect to contao.org via SSL, just as the other forum user with the same problem. The Contao Manager cannot fix that for you.

However, what should be fixed within the Contao Manager is the error message itself. May be the Contao Manager should also do a connection test to contao.org before self updating, to make it more clear to the user what is not working.


> Provider also sent me a message telling me SSL connection should work:

The provider needs to test this from within the web server's environment, not from within the console.

**Comment by aschempp** [comment]
> However, what should be fixed within the Contao Manager is the error message itself. May be the Contao Manager should also do a connection test to contao.org before self updating, to make it more clear to the user what is not working.

How do we do that? Any hint how the Contao Check does it?

**Comment by fritzmg** [comment]
> How do we do that? Any hint how the Contao Check does it?

https://github.com/contao/check/blob/master/check/controller/repository.php#L73-L88
