### ISSUE TITLE
Composer Cloud nicht erreichbar

### ISSUE THREAD

**Issue by hinzke** [contao/contao-manager#482]
Ausgabe im CM 1.2.1. Problem tritt seit 9 Uhr auf. Getestet mit Installationsversuchen von 4.4 LTS und 4.8.x

`**Warte auf freie Rechenleistung der Composer Cloud seit 1911 Sekunden**
Berechnung startet in ca. 278 Sekunden (aktuell 19 Aufgaben auf 6 Servern)`

EDIT: Ah ok, konnte wohl nicht abwarten. Läuft zur Zeit nen Update scheinbar 
https://community.contao.org/de/showthread.php?76389-Konsolenfenster-im-Contao-Manager-h%C3%A4ngt-l%C3%A4sst-sich-nicht-beenden&p=514016&viewfull=1#post514016

**Comment by fritzmg** [comment]
Ein Update der Cloud läuft wohl nicht - aber unter Umständen benutzen gerade viele User die Cloud für Contao 4.4.45 & 4.8.5 Updates.
