### ISSUE TITLE
Probleme mit PHP-Version 7.1.2

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao-manager#484]
**Affected version(s)**
Contao Manager V 1.1.8
PHP-Version 7.1.2

**Description**  
Beim Start des Contao Managers wird ein Update vorgeschlagen. Nach dem Update wird automatisch wieder ein Downgrade durchgeführt.

Bei einem manuellen Update wird beim 1. Start ebenfalls ein Downgrade durchgeführt.

Somit lässt sich der Manager mit PHP 7.1.2 nicht nutzen.

**Comment by aschempp** [comment]
Da haben sich tatsächlich zwei Fehler eingeschlichen.

1. Der Manager 1.1 hat auf 1.2 aktualisiert, wenn die PHP Version mindestens 7.1.0 erfüllt hat, obwohl die Version erst ab 7.1.3 funktioniert (und vorher automatisch wieder auf 1.1 downgraded).
2. Der Manager 1.1 prüft nur unter PHP 5 ob eine neue 1.1er-Version verfügbar ist.
