### ISSUE TITLE
Eweiterungen und "Entdecken" suchen 

### ISSUE THREAD

**Issue by ChrMue** [contao/contao-manager#485]
**Affected version(s)**
Version 1.2.1

**Description**  
bei "Entdecken" eerden keine Erweiterungen gefunden, die sich noch nicht im Status **stable** befinden.

**How to reproduce**  
z.B. meine Erweiterung ChrMue/cm_membermaps

**Comment by aschempp** [comment]
Das ist korrekt. Instabile Erweiterungen können vom Manager nicht (auf Knopfdruck) installiert werden, weshalb wir diese entsprechend aus der Liste entfernt haben.
Aus meiner Sicht richten sich nicht-stable Erweiterungen nicht an unbedarfte Anwender:innen. Und bedarfte Anweder:innen (gibts den Ausdruck? 😂 ) können die Erweiterung in die `composer.json` schreiben.

**Comment by fritzmg** [comment]
Imho können Entwickler auch unbedarften Usern sagen, sie können eine sich noch in Entwicklung befindende Erweiterung installieren. Indem sie das Paket hinzufügen und dann halt `dev-master` in der Versionsfeld schreiben (oder passiert das dann nicht ohnehin automatisch?). Ich finde es nicht notwendig Contao Pakete auszublenden, die noch keinen Release Tag haben.

**Comment by fritzmg** [comment]
Weiterer use-case: https://packagist.org/packages/dma/dma_elementgenerator#dev-managed-edition

Auch unbedarfte User könnten hier die Test Version für Contao 4 installieren - jetzt finden sie diese Extension aber plötzlich nicht mehr.

**Comment by zonky2** [comment]
beim ER2 gab es doch die Einstellung "auch nicht kompatible Erweiterungen anzeigen" - ggf. könnte man ein äquivalentes Flag im CM setzen..?

**Comment by aschempp** [comment]
> Weiterer use-case: https://packagist.org/packages/dma/dma_elementgenerator#dev-managed-edition
> 
> Auch unbedarfte User könnten hier die Test Version für Contao 4 installieren - jetzt finden sie diese Extension aber plötzlich nicht mehr.

Genau wegen dieser Erweiterung haben wir das angepasst. Ein Nutzer kann die Erweiterung installieren und erhält immer nur eine Fehlermeldung, wenn er nicht von Hand den validen Branch eingibt. Eine Erweiterung die eine "stabile" Version hat wird angezeigt, danach lassen sich Feature-Branches und ähnliches ja weiterhin testen?

**Comment by fritzmg** [comment]
> Genau wegen dieser Erweiterung haben wir das angepasst. Ein Nutzer kann die Erweiterung installieren und erhält immer nur eine Fehlermeldung, wenn er nicht von Hand den validen Branch eingibt.

Dieser Fall tritt aber auch bei Paketen ein, die Stable Releases haben. Beispiele:

* https://packagist.org/packages/bugbuster/contao-visitors-bundle
* https://packagist.org/packages/terminal42/contao-autoregistration

Diese Pakete können in Contao 4.4 gefunden und hinzugefügt werden. Wendet man dann die Änderungen an, kommt es zu einem Fehler, weil keine kompatible Version gefunden werden kann.

Bei `bugbuster/contao-visitors-bundle` deswegen, weil der Contao Manager (bzw. Composer) automatisch `^1.6` als Version Requirement hinzufügt - für Contao 4.4 muss es aber `^1.0` (bzw. `^1.5`) sein.

Bei `terminal42/contao-autoregistration` weil alle verfügbaren Versionen erst ab Contao 4.5 verwendet werden können.

**Comment by aschempp** [comment]
Das ist ein anderes Problem, welches wir leider nur schwer beheben können. Composer auf Kommandozeile verhält sich genauso, er nimmt einfach immer die neuste Version bei einer Installation…

**Comment by aschempp** [comment]
Wie per Mumble am 28.11.2019 besprochen war die Mehrheit der Meinung dass dieses Verhalten richtig ist. Wenn die Erweiterung von **Anwendern** installiert werden soll, sollte sie stable sein. Man kann auch eine fast-fertige Version als _stable_ taggen und dann Patches veröffentlichen. Alle anderen Anwendungsfälle lassen sich durch manuelle Bearbeitung der `composer.json` lösen.
