### ISSUE TITLE
Erweiterungen, die als Abhängigkeit installiert sind, lassen sich nicht installieren

### ISSUE THREAD

**Issue by dmolineus** [contao/contao-manager#486]
**Betroffene Versionen**

- Contao Manager 1.2.1

**Beschreibung**  

Sind Erweiterungen als Abhängigkeiten einer anderen Erweiterung installiert, so lassen sich diese im Contao Manager nicht mehr hinzufügen.

Dies ist dann sinnvoll, wenn

 - Eine Erweiterung als direkte Abhängigkeit installiert bleiben soll
 - Eine spezifische Version der Abhängigkeit erforderlich ist

**Comment by aschempp** [comment]
Interessante Feststellung 😆

**Comment by aschempp** [comment]
Wie per Mumble am 28.11.2019 besprochen wollen wir erlauben, normale Suchresultat-Pakete auch dann in einer bestimmten Version zu installieren wenn sie bereits installiert sind.

**Comment by aschempp** [comment]
In Version 1.2.3 lässt sich bei jedem bereits installieren Paket den Constraint anpassen. Damit werden die Pakete entsprechend lokal required, es lässt sich damit auch die Version jedes Pakets steuern (z.B. eine ältere Version eines Pakets installieren, wenn die neuste einen Fehler hat).
