### ISSUE TITLE
ERROR 500 Unknown installation status

### ISSUE THREAD

**Issue by baymax88** [contao/contao-manager#487]
contao 4.4 LTS

Hello.

I've tried to install contao 4.4 LTS. I downloaded contao-manager.phsr and renamed with .php.
I passed 5 steps of system checking successfully but in the final step <contao installation>, it generates the following error message.

=====================================

` ERROR 500 Unknown installation status`

`Some files were found on your server but no known Contao version could be detected.`
`You must either manually repair your application or remove the following files and folders to install Contao:`

`- contao-manager.phar.php`

Please let me know how to fix this issue.

**Comment by aschempp** [comment]
Did you place the `contao-manager.phar.php` in the `web` folder?

**Comment by baymax88** [comment]
Thanks for your time
I've just fixed that issue.

**Comment by baymax88** [comment]
I placed `contao-manager.phar.php` in the `web` folder.
And set `web` folder to `documentroot`
