### ISSUE TITLE
Server configuration not possible

### ISSUE THREAD

**Issue by kchristmann** [contao/contao-manager#489]
**Affected version(s)**
Contao Manager 1.2.1 on a Windows 2012 Server (Windows NT WEB5 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) i586) - PHP Version 7.3.11
![Serverkonfiguration](https://user-images.githubusercontent.com/56255126/69226483-8303b880-0b80-11ea-8777-b99cb3817b60.png)

**Description**  
Server is a small hosting service. Neither a pre-configured nor a manual configuration ("Andere...") is possible.

**Comment by lukasbenes** [comment]
I have a similar server configuration - Windows Server 2012 and the same error. Is there any solution?

**Comment by aschempp** [comment]
This should be obsolete with version 1.3 as the hosting selection was removed.
