### ISSUE TITLE
Shebang prevents execution

### ISSUE THREAD

**Issue by Olli** [contao/contao-manager#49]
The bundle.js gets a shebang (contao-manager.phar is used) so it's throwing an js syntax error.
Also the contao-manager.phar generates html that has a shebang on beginning which results in faulty html.

**Comment by discordier** [comment]
What is your server configuration? Apache, nginx?
What is your PHP configuration? mod_php, php-fcgi, cgi?

Please provide us with output from `phpinfo()` and ensure output buffering is present.
We are handling this case explicitely [here](https://github.com/tenside/core-bundle/blob/master/src/Resources/stub.php#L68).

**Comment by Olli** [comment]
Hosting-Provider: All-Inkl
Server: apache
PHP: FPM/FastCGI 
What information from phpinfo should I provide? I don't want to post this huge html here.
output_buffering has "no value". 
I assume output buffering works - otherwise it wouldn't interpret the app.php . 
The html output (and js also) only have the shebang on the beginning.

**Comment by discordier** [comment]
I finally found the reason for the shebang line at least for phars compiled on Windows.
You most likely have `git config core.autocrlf` set to true. This breaks the parser in pharpiler as we never thought about git replacing the line endings of the files.
If you would use a proper checkout containing `lf` the generated binary should work.

I will add an .gitattributes file which will enforce force the line endings, however, you should also fix your git config.

**Comment by Olli** [comment]
Ok did a complete new clone of the git respo and rebuild the phar.
It's the same problem like before. I use Debian Linux.

**Comment by discordier** [comment]
I can not reproduce this...

Anyone else?

**Comment by Olli** [comment]
Do you need anything for investigation? FTP access?
Am I right? There should be no shebang at the beginning of the contao-manager.phar ?
If it's not right then it's a problem of the hosting provider. If it's right then it's a problem of the building process. Then maybe we should compare the composer.lock . 
There must be a solution for this. :)

**Comment by discordier** [comment]
The shebang must be line 1 of the phar but it mustn't be written to screen.

**Comment by Olli** [comment]
The question is why it mustn't be written. From my point of view it's normal php behavior ... the interpreter interprets everything inside of <?php ?> and outputs everything outside of it unchanged. 
Is it possible to remove the shebang while creating the phar with pharpiler?

**Comment by Olli** [comment]
I did an local installation of nginx and php7.0-fpm ... it works in such way that the shebang is ignored.

**Comment by discordier** [comment]
> The question is why it mustn't be written.

Because WE do not want to see it (and php-cli does not print it by default).
So we only need to clear it in web environment for which we have the `ob_clean()` call to clear the shebang from the output in web.

> From my point of view it's normal php behavior ... the interpreter interprets everything inside of and outputs everything outside of it unchanged.

In general, you are right on this one. However, there is one exception to this rule, the first line of a script will not be printed from CLI as long as it is a shebang. For php-cgi, fpm, ... it will get written.

> Is it possible to remove the shebang while creating the phar with pharpiler?

It would be possible but then not be working anymore by calling `./contao-manager.php.php` as the system would not know how to handle the file anymore. That is the reason what the shebang is there for.

> I did an local installation of nginx and php7.0-fpm ... it works in such way that the shebang is ignored.

Which it should have been doing all the time, could you pinpoint the other installation why it is not ignored over there?

**Comment by Olli** [comment]
Ok I did a local test with my apache and fpm - it works (ok Composer isn't get executed but it's not executed in any other of my test installation).
So I assume it's an all-inkl only problem. That would be fun. :-\

**Comment by fritzmg** [comment]
Would be interesting to find the reason though, as I consider All-Inkl as a Hoster with a good reputation.

**Comment by aschempp** [comment]
Please don't worry too much about this stuff in a development build 😉

**Comment by discordier** [comment]
Well, this is something that will not change even for the final build. It is the fundamental base.

**Comment by Olli** [comment]
It'll be nice if someone can confirm that all-inkl behavior.

**Comment by fritzmg** [comment]
I may be able to test, but someone needs to provide me with the `.phar` since I cannot build it myself.

**Comment by aschempp** [comment]
This is obsolete with the latest version (see https://github.com/contao/contao-manager/tree/develop)
