### ISSUE TITLE
Ausgewählte Pakete auch bei Fehler behalten

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#495]
hat man verschiedene Pakete zum Installieren ausgewählt und es gebt beim Install irgend etwas schief, wird der CM neu geladen und alle Auswahlen sind weg :(

Wäre schön, wenn sich der CM sich das merken könnte...

**Comment by aschempp** [comment]
Duplicate of https://github.com/contao/contao-manager/issues/357
