### ISSUE TITLE
weiterer Button "Hinzufügen" bei Tab Empfehlungen

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#496]
weiterer Button "Hinzufügen" bei Tab "Empfehlungen"

... insbesondere bei MetaModels, wo man viele andere Pakete installieren kann, wäre ein Button "Hinzufügen" in Liste "Empfehlungen" super - aktuell sind es viele "Klicks-in-Schleife"

**Comment by aschempp** [comment]
Der Button sollte da sein, sobald du das Paket installiert hast?

**Comment by zonky2** [comment]
sieht aktuell so aus, dass nur Button "Details" da ist... daneben könnte Button "Hinzufügen"

https://easycaptures.com/fs/uploaded/1432/4913454127.png

**Comment by aschempp** [comment]
I have improved this in e43b4a2edcd5e9c08e694f72891e414ad03f1ad6
