### ISSUE TITLE
Button zum Kopieren der "Konsolenausgabe"

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#499]
Wenn Fehler auftreten, wäre es schön, wenn man "einfach" den Inhalt der Konsolenausgabe kopieren könnte - wenn ich das mit der Maus mache, erwische ich immer "zu viel ringsrum"...

**Comment by aschempp** [comment]
Hinzugefügt in 1.3
https://contao.org/de/news/contao-manager-1-3-0-verfuegbar.html
