### ISSUE TITLE
Debug-Modus nach Deaktivierung weiterhin aktiv

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#500]
Contao 4.8.5
Contao Manager 1.2.1

Wenn im Bereich Systemwartung der Debug-Modus aktiviert und anschließend wieder deaktiviert wird, ist dieser anschließend immer noch aktiv. Das Deaktivieren funktioniert nicht.

**Comment by aschempp** [comment]
Funny thing, the cookie has been renamed in Contao (https://github.com/contao/contao/issues/638) but that never happened in the Manager …
