### ISSUE TITLE
Deinstallation schlägt fehlt

### ISSUE THREAD

**Issue by eBlick** [contao/contao-manager#502]
In einer Contao 4.4 LTS wollte ich eine Erweiterung deinstallieren.
Dies war aber mit folgender Fehlermeldung nicht möglich.
Auch ein zuvor manuell geleerter Cache hilft nichts.

**Affected version(s)**
1.2.1

**Description**  
$ /usr/local/bin/php7.3.6-cli -q /xxx/web/contao-manager.phar.php composer remove alnv/prosearch --no-update --no-scripts --no-ansi --no-interaction

# Process terminated with exit code 0
# Result: OK

> Resolving dependencies using Composer Cloud v2.1.1

# Job ID KdgDGRWyMEGYGuUGfrr4Ldsf1qngqAva0LB2ceBj9kJ0ngvLtW1qDlHalwZSuBYNxdLZgtCiaEDEqVcFA1 completed in 45 seconds
# Memory usage: 392.05MB (peak: 2142.71MB), time: 40.62s.

$ /usr/local/bin/php7.3.6-cli -q /kunden/xxx/web/contao-manager.phar.php composer install --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader

contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  

 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /kunden/xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 75

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /kunden/xxx/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/OutOfMemoryException.php on line 1
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 0 installs, 0 updates, 1 removal
  - Removing alnv/prosearch (1.1.0)
Generating optimized autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception

In ScriptHandler.php line 113:
                                                                 
  An error occurred while executing the "cache:warmup" command:  
                                                                 

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>...]

# Process terminated with exit code 1
# Result: General error

---

### Der Hintergrundprozess wurde unerwartet beendet ###

**How to reproduce**

**Comment by fritzmg** [comment]
Please post logs etc. in three back ticks, not plain.

Regarding your problem: you need to use the enable the Composer Cloud Resolver in the server settings of the Contao Manager.

**Comment by eBlick** [comment]
Sorry, next time.

Attached the Composer.json
https://pastebin.com/BaG3mYEy

**Comment by eBlick** [comment]
And the composer.lock
https://pastebin.com/sgmjix13

**Comment by xchs** [comment]
Increase your PHP memory limit (> 128 MB)!

**Comment by fritzmg** [comment]
> Sorry, next time.

@eBlick Just edit your post ;)

> And the composer.lock
> https://pastebin.com/sgmjix13

@eBlick This link is broken.

**Comment by aschempp** [comment]
This issue was closed because it has not had recent activity.
