### ISSUE TITLE
Fix footer at https://extensions.contao.org/

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao-manager#503]
Normally you will find the possibility to change the language at the end of the page.
Unfortunately the field is hidden and can only be guessed.
(see screenshot)

The problem only occurs under extensions.contao.org
In the contao manager, the appearance is fine.
![extensions contao org](https://user-images.githubusercontent.com/23719181/70218294-04dc1000-1743-11ea-8120-42f30ae22f61.jpg)

**Comment by leofeyer** [comment]
I cannot reproduce this in Safari 13 on macOS.

**Comment by fritzmg** [comment]
I can reproduce this on Firefox 71.0 on Windows 10.

**Comment by fritzmg** [comment]
It's because of `#contao-network`, which pushes the `#app` container down, out of the view port.

**Comment by aschempp** [comment]
@leofeyer so something to fix in the network bar or in the extension list?

**Comment by leofeyer** [comment]
IDK. The network bar is injected into the `<body>` element, which does not work for the extension list as there is an additional `<div id="app">` element with 100% height and custom overflow settings. There are two possible solutions:

1. Reduce the width of the `#app` element to `calc(100% - 34px)`
2. Inject the network bar into the `#app` element

I would vote for no. 2.

**Comment by aschempp** [comment]
that would be fine with me, but I guess you need to adjust that on the bar?

**Comment by leofeyer** [comment]
Done. BTW, you should require `network.min.js` instead of `network.js`.

**Comment by aschempp** [comment]
done 😎
