### ISSUE TITLE
"Keep logged in" not working

### ISSUE THREAD

**Issue by akroii** [contao/contao-manager#504]
**Affected version(s)**
1.2.1

**Description**  
The "Keep logged in" Button not working, because I'am unauthorized.
![Bildschirmfoto 2019-12-10 um 15 55 50](https://user-images.githubusercontent.com/8830861/70540651-e8d2d700-1b65-11ea-8ecb-194f17475c58.png)

**How to reproduce**  
1. Open Manager
2. Do nothing until warning message appears
3. Press "Keep logged in" Button

**Comment by aschempp** [comment]
This has been improved in 1.3, I assume the issue has been fixed.
