### ISSUE TITLE
Strato Managed Server "The PHP Intl extension is not available."

### ISSUE THREAD

**Issue by stefan2** [contao/contao-manager#505]
Hi Leute,

ich wollte den CM auf einem Managed Server bei Strato aufsetzen, aber er startet nicht, weil die Prüfung auf die "intl"-Erweiterung fehlschlägt.

Die Erweiterung muss man erst aktivieren in den Einstellungen am Server, das habe ich getan.

PHP-Binary wie im CM eingestellt ist  "/usr/bin/php73"

Dieser Test schlägt wohl fehl: https://github.com/contao/contao-manager/blob/master/api/IntegrityCheck/PhpExtensionsCheck.php#L39

Wenn ich das auf der Kommandozeile probiere klappt das:

```
$ /usr/bin/php73 -r "var_dump(extension_loaded('intl'));"
// > bool(true)
```
Per Apache ebenfalls

```php
<?php
var_dump(PHP_VERSION);
var_dump(extension_loaded('intl'));
$formatter = new NumberFormatter('de_DE', NumberFormatter::CURRENCY);
var_dump($formatter->getTextAttribute(NumberFormatter::CURRENCY_CODE));

// string(6) "7.3.10" bool(true) string(3) "EUR"
```
`phpinfo()` zeigt:

``` 
// configure
--enable-intl=shared
```
Internationalization support | enabled
-- | --
ICU version | 50.2
ICU Data version | 50.2
ICU TZData version | 2018e
ICU Unicode version | 6.2

Directive | Local Value | Master Value
-- | -- | --
intl.default_locale | no value | no value
intl.error_level | 0 | 0
intl.use_exceptions | 0 | 0

Irgendwelchen Ideen? Die Einstellungen des Servers bei Strato ist auch etwas gewöhnungsbedürftig. Vielleicht muss man da noch mal irgendwas verändern. Dazu bräuchte ich aber ein tieferes Verständnis wie das genau funktioniert/zusammenhängt.

Oder gibt es bereits das Thema "Strato und CM" vielleicht schon? 
Es gibt zwar https://github.com/contao/contao-manager/wiki/Strato, aber darin finde ich mich nicht wieder. Oder doch und ich seh's bloß nicht? Links sind willkommen. Danke.

**Comment by aschempp** [comment]
reklamiert denn der Manager dass Intl auf CLI oder Web fehlt?

**Comment by stefan2** [comment]
Ah! Wer lesen kann ist im Vorteil :-) Kommandozeile.

```
PHP Kommandozeilen-Programm
The PHP Intl extension is not available.
Contao 4 requires the PHP Intl extension for internationalization purposes.
```

**Comment by aschempp** [comment]
Dann kann ich mir das nur erklären, dass Strato die php.ini auf der CLI – bzw. im Webserver-Umfeld der CLI nicht liest. Du kannst eine eigene `php.ini` im contao-manager Ordner anlegen; aber Vorsicht, dort musst du **alles** neu konfigurieren, er übernimmt keine Einstellungen einer *globalen* php.ini

**Comment by stefan2** [comment]
Alles klar, Danke. Ich versuche es und melde mich wieder mit dem Ergebnis.

**Comment by stefan2** [comment]
Das Ergebnis war enttäuschend, ich habe es nicht hinbekommen. Eine php.ini hatte keine Wirkung, wurde auch nicht gelesen (laut phpinfo()). Auflösen direkt am Server klappte auch nicht wegen RAM-Mangel und/oder praktischem Stillstand während der Auflösung (ist eine sehr kleine Kiste).  Ich habe es seither aber auch nicht mehr versucht, vielleicht  habe ich was übersehen oder es hat sich mittlerweile was geändert. Keine Ahnung. Die Pakete löse ich lokal auf und am Server installiere ich nur noch (). Nicht sonderlich toller Workflow, aber eine bessere Lösung habe ich nicht gefunden, tut mir leid, keine sonderlich ermutigende Auskunft. Schönen Tag noch.

**Comment by Samson1964** [comment]
Danke für die Rückmeldung. Contao 4.12 läuft leider überhaupt nicht auf einem Managed Server D 300 (das kleinste MS-Paket), dafür aber super im billigsten Webhosting Power Web Basic. Mittlerweile ist der Managed Server storniert und wir sehen uns nach einem anderen Hoster um.
