### ISSUE TITLE
Dialog "Aktuelle Aktion wird gestoppt ..." kann nicht geschlossen werden

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#506]
Der Dialog "Aktuelle Aktion wird gestoppt …" kann nicht manuell geschlossen werden. Auch nach dem Neuladen der Seite wird der Dialog erneut angezeigt. Es ist dadurch kein Zugriff auf den Contao Manager mehr möglich.

![image](https://user-images.githubusercontent.com/1632642/71035676-42b23e80-211c-11ea-8960-2e9cc5b08f5c.png)

Im Hintergrund werden regelmäßig Requests an ``https://xxx/contao-manager.phar.php/api/task`` gestellt, die mit folgender Response beantwortet werden:
``{"title":"Pakete werden aktualisiert","summary":"Aktuelle Aktion wird gestoppt \u2026","detail":"Der Hintergrund-Prozess wird abgebrochen.","console":"$ \/usr\/bin\/php73 -q -d memory_limit=-1 \/www\/htdocs\/xxx\/contao-contaomanager\/web\/contao-manager.phar.php composer update contao\/manager-bundle terminal42\/contao-easy_themes contao\/calendar-bundle contao\/listing-bundle --with-dependencies --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader\n\nLoading composer repositories with package information\nUpdating dependencies\n\n\n---\n\n### Der Hintergrundprozess wird abgebrochen ###","cancellable":true,"autoclose":false,"audit":true,"status":"aborting"}``

**Comment by xchs** [comment]
Related: https://github.com/contao/contao-manager/issues/470

**Comment by aschempp** [comment]
This issue was closed because it has not had recent activity.
