### ISSUE TITLE
Reiter "Entdecken": Javascript-Fehler: TypeError: "can't convert null to object"

### ISSUE THREAD

**Issue by mathContao** [contao/contao-manager#507]
Beim Aufruf/Aktualisieren der Seite "Entdecken" erscheint ein JavaScript-Fehler
![grafik](https://user-images.githubusercontent.com/1645099/71420041-37f32e80-2673-11ea-80a0-61161d6222be.png)

Contao 4.4
Contao Manager 1.2.2

**Comment by aschempp** [comment]
ist das in allen Browsern reproduzierbar?

**Comment by mathContao** [comment]
Im Internet Explorer kommt der Fehler:

![grafik](https://user-images.githubusercontent.com/1645099/72011406-12147f00-325a-11ea-8867-191970e566e4.png)

**Comment by aschempp** [comment]
Ich habe die Slider-Komponente ausgetauscht, damit dürfte der Fehler in der nächsten Version behoben sein (unter https://extensions.contao.org bereits sichtbar).
