### ISSUE TITLE
Reiter "Pakete": JavaScript-Fehler:  TypeError: "e.root is null"

### ISSUE THREAD

**Issue by mathContao** [contao/contao-manager#508]
Nach dem Klick auf den Button "Pakete aktualisieren" im Reiter "Pakete" erscheint folgende Fehlermeldung:

![grafik](https://user-images.githubusercontent.com/1645099/71420111-a89a4b00-2673-11ea-8380-deeae6f2e542.png)

Contao 4.4
ContaoManager 1.2.2
Browser: Firefox 71.0

**Comment by aschempp** [comment]
Duplicate of  #507
