### ISSUE TITLE
Login nicht möglich (Authentication credentials could not be found)

### ISSUE THREAD

**Issue by seaneble** [contao/contao-manager#51]
Wir testen zum Spaß mal gerade den Contao Manager. Gebaut habe ich das Phar nach den Anweisungen aus dem kürzlichen Commit von @discordier.

Das Phar läuft prinzipiell (sieht übrigens sehr hübsch aus!) und möchte gerne einen Benutzernamen und ein Passwort  haben. Danach werden fünf Requests gestartet:

 * get_state
 * autoconfig
 * configure
 * create-project
 * run

Und der fünfte schlägt fehl (mit Code 401):
    {"status":"ERROR","message":"Authentication credentials could not be found."}

In der tenside.json sieht es prinzipiell gut aus (würde ich sagen):

```json
{
    "secret": "359f0344c5f9cbbec9a233bae6a6ca669790ead6084325fde84ace2ce7637988676e1c94de2646c0",
    "php_cli": "/opt/remi/php71/root/usr/bin/php",
    "php_cli_arguments": [
        "-d memory_limit=2G"
    ],
    "php_can_fork": true,
    "auth-password": {
        "admin": {
            "acl": 15,
            "salt": "589d87c3ecaf21.72196327",
            "username": "admin",
            "password": "$2y$13$UozWiuLBbaMmYyNdRSRpUOobQYWYNHVL8OSVe6wIRAJ2xmWey3k4u"
        }
    }
}
```

Das kann man beliebig oft wiederholen (wenn man den tenside-Ordner zwischendurch löscht). Was könnte der Grund sein?

**Comment by discordier** [comment]
Kannst du bitte noch ein log der header der requests anhaengen?
Anscheinend verliert dein client irgendwo die auth header.

**Comment by seaneble** [comment]
Anbei die fünf Header sowie einmal eine .har aus dem Chrome-Inspektor, der auch die Payload enthält.
[request.zip](https://github.com/contao/contao-manager/files/766693/request.zip)

**Comment by discordier** [comment]
I hope you changed the credentials on your side because the password is in the har file.

Thanks for the data however, I will have a look into it.

**Comment by seaneble** [comment]
Never mind, the environment is not meant to last and the domain name does not resolve.

**Comment by aschempp** [comment]
This is likely obsolete with the latest version (see https://github.com/contao/contao-manager/tree/develop)
