### ISSUE TITLE
Contao manager update from 1.2.1 to 1.2.2 is hanging

### ISSUE THREAD

**Issue by robvis** [contao/contao-manager#510]
When calling contao-manager the manager will update automatically from 1.2.1 to version 1.2.2, but the system is hanging during the update process.
So every time I call contao-manager.phr.php this is the case.
Any solution for this issue?

thanks,
Rob

**Comment by robvis** [comment]
Addition: my contoa version is 4.4.45

**Comment by xchs** [comment]
Did you encounter the same problem as already reported here: https://github.com/contao/contao-manager/issues/479

When in doubt, you can always download the latest version of the Contao Manager from contao.org and replace your existing one.

**Comment by robvis** [comment]
At the end I must upgrade to a newer version of contao-manager. I manually uploaded Contao-Manager and renamed, but again hanging with message showing **Updating from 1.2.4 to 1.2.4**. This looks strange isn't it?
Could it be some temp file is not cleared? (In my test environment I never had theses issues)
It's not related to #405 
Hope someone can help me out.

**Comment by robvis** [comment]
Solved the issue by removing "task.json" in folder "contao-manager"
