### ISSUE TITLE
Contao Manager 1.2.2 - Reiter "Entdecken": tns-slider: CSS fehlerhaft (firefox)

### ISSUE THREAD

**Issue by UlrichHolland** [contao/contao-manager#511]
![Auswahl_005](https://user-images.githubusercontent.com/3481866/71911153-7f99b000-3173-11ea-8c8f-468eab27ed26.png)

**Comment by aschempp** [comment]
Das sollte in der nächsten Version behoben sein (auf https://extensions.contao.org bereits sichtbar).
