### ISSUE TITLE
Installations check meldet falsche contao Version

### ISSUE THREAD

**Issue by nkleber78** [contao/contao-manager#516]
Nach dem manuellen update von 2.9 über 2.11, 3.5 meldet der contao-manager dass die Version 2.11 installiert sei. Allerdings wird im Backend ganz klar die Version 3.5.40 angezeigt. Somit kann ich nicht installieren

**Comment by fritzmg** [comment]
? Mit dem Contao Manager kannst du nicht von Contao 3.5 direkt auf Contao 4 aktualisieren.

**Comment by nkleber78** [comment]
Wie denn dann? Ich habe die 3.5.40, was meiner meinung nach die letzte Version ist. Und ich möchte nun auf 4.8 gehen. Wie kann ich das bewerkstelligen. Wenn ich eine komplett neue Installation mit dem contao manager versuche dann wird zwar installiert, aber ich kann kein /contao/install machen. Hier wird The requested URL /contao/install was not found on this server. auch wenn ich app.php/contao/install verwende is das selbe problem

**Comment by fritzmg** [comment]
Hier zB eine Anleitung von Leo Feyer: https://youtu.be/rwC8xfdO3Ao

Bei weiteren Fragen wende dich bitte an die Community.
