### ISSUE TITLE
Contao Manager Paket Update

### ISSUE THREAD

**Issue by umwelttaucher** [contao/contao-manager#517]
Ich hoffe das kann jemand in deutsch lesen. Bin sehr neu auf dem Gebiet unterwegs und habe gestern für unsere Pakete im Contao Manager ein Update gemacht. Nun komme ich weder auf das Frontend noch in das Backend.
Habe das aktuelle Fehler-log file im Anhang mit dabei. Brauche dringend hilfe, da nichts mehr geht. :(

Vielen Dank schonmal euch allen!
[prod-2020-01-28.log](https://github.com/contao/contao-manager/files/4121382/prod-2020-01-28.log)

**Comment by fritzmg** [comment]
Wende dich bei solchen Problemen an das Community Forum.
