### ISSUE TITLE
The Composer Cloud failed with status code 200 

### ISSUE THREAD

**Issue by NinaG** [contao/contao-manager#518]
Ich wollte auf einem Projekt eine Kleinigkeit im Manager updaten. Er bricht mit einem Fehler ab, für den ich keinen Lösungsansatz finde. Es ist dabei egal ob ich diese Erweiterung update oder versuche eine beliebige andere Erweiterung zu installieren/upzudaten. Der Fehler kommt immer.

In den Logs finde ich keine Hinweise.

Infos zur composer.json siehe hier im Forum:
https://community.contao.org/de/showthread.php?77011-The-Composer-Cloud-failed-with-status-code-200&p=518682&viewfull=1#post518682

Fehlermeldung von Contao manager:

```
> The Composer Cloud failed with status code 200

  Composer Resolver returned an unexpected status code

Response:
{"jobId":"XXXXXXX","status":"finished_with_errors","retries":0,"worker":"worker-contao-production-XXXXX-XXXXX","queuePosition":1,"links":{"composerJson":"\/jobs\/XXXXXXX\/composerJson","composerLock":"\/jobs\/XXXXXX\/composerLock","composerOutput":"\/jobs\/XXXXXXX\/composerOutput"},"stats":{"averageProcessingTimeInMs":85921,"numberOfJobsInQueue":0,"numberOfWorkers":10,"appVersion":"2.2.2","phpVersion":"7.4.2","composerVersion":"1.9.2","host":"web-production-XXXXXXXX"},"sponsoredBy":{"name":"terminal42 gmbh","link":"https:\/\/www.terminal42.ch"}}

Request:
XXXXXXX

---

### Der Hintergrundprozess wurde unerwartet beendet ##
´´´

**Comment by NinaG** [comment]
Zur Info: Die Website läuft schon länger. Ich vermute, dass es ggf. etwas mit den Änderungen zu tun hat, die laut Patrick letzte Woche am Cloud Server/Resolver o.ä. gemacht wurden?

**Comment by NinaG** [comment]
Ich laufe gerade in das selbe Problem bei einem anderen Webhoster. Auch dort laufen im Projekt Extensions wie im Forenbeitrag erwähnt.

**Comment by NinaG** [comment]
Ich konnte den Fehler jetzt darauf eingrenzen, dass der Contao Manager scheinbar plötzlich nicht mehr mit Privatextensions und dem artifacts-Ordner umgehen kann. Sobald diese aus der JSON entfernt sind, läuft alles sauber durch. Da die Extensions ihrerseits nicht technisch geändert wurden, muss es wohl an Änderungen liegen die im Contao Manager oder Resolver passiert sind. Ich sende Toflar dazu eine E-Mail mit den beiden JSON (vorher/nachher).

**Comment by aschempp** [comment]
Gemäss meiner Info von @Toflar lag der Fehler eigentlich an einer invaliden `composer.json`, aber wir haben den Fehler in der Composer Resolver Cloud behoben.
