### ISSUE TITLE
Add donate or donation in support section of packages

### ISSUE THREAD

**Issue by MDevster** [contao/contao-manager#519]
Would it make sense to add a new sponsoring section under support so that an additional link to the sponsors page for free extensions can be added.

"ui.package.support_donate": "Spenden Sie",
or
"ui.package.support_donation": "Spende",

see or new energy saving theme for example
https://extensions.contao.org/?q=zero&pages=1&p=contao-themes-net%2Fzero-one-theme-bundle
(click "more")

If that were desired, I could prepare a PR ;)

**Comment by aschempp** [comment]
The support links are based on what Composer offers. The schema validation does not allow additional fields in the composer.json. https://getcomposer.org/doc/04-schema.md#support

As a lot of services (including GitHub) are adding sponsoring stuff, maybe you can find out if there's a generic approach in Composer for that?

**Comment by aschempp** [comment]
This was actually added in Composer 1.10 😎 
https://github.com/composer/composer/pull/8453

**Comment by MDevster** [comment]
@aschempp Should I make a pull request or do we just leave the labels like patreon or corporate etc.?

**Comment by aschempp** [comment]
no idea yet… Adding this is probably a UI question, isn't it?
