### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by Olli** [contao/contao-manager#52]
I got an "404 - File /web/index.html Not Found" if I run the generated phar file on my webspace.

**Comment by aschempp** [comment]
you're aware that is not really helpful, right?

- what OS did you build on
- what OS are you running on
- what webserver
- what runtime (mod_php, FCGI, …)
- …

so many questions, so few answers :(

**Comment by Olli** [comment]
Sorry I forgot.
BuildOS: debian sid 
Hosting-Provider: All-Inkl
OS: 3.13.0-112-generic #159-Ubuntu
Server: apache
PHP: FPM/FastCGI
Any more details?
I did the installation as in the readme described and then executed phing.

**Comment by discordier** [comment]
Refuses to work for me without adding at least one tag due to git exit code.
```
    <exec executable="git" outputProperty="version" checkreturn="true">
        <arg value="describe" />
        <arg value="--tags" />
    </exec>
```

This does not work when there is nothing to describe, we might want to allow this task to fail.
@aschempp what do you think?

**Comment by aschempp** [comment]
It will work as soon as there is one tag. You can temporarily add a tag locally just for the build.

**Comment by discordier** [comment]
I already did so, however I fail to see the reason for this describe action.

P.S.: `git describe --tags --always` might be better here, even if only as a temporary solution.

**Comment by BugBuster1701** [comment]
Mit der Anpassung geht zwar der Build, ohne bei mir nicht, aber die 404 Meldung von Olli bleibt.
(Ubuntu, PHP 7.0)

**Comment by leofeyer** [comment]
Ich nutze folgendes:

```xml
    <exec executable="git" outputProperty="version" checkreturn="true">
        <arg value="describe" />
        <arg value="--always" />
    </exec>
```

Die Fehlermeldung verschwindet, wenn Du vor dem eigentlichen Build einmal `composer install` und einmal `npm install` aufrufst.

**Comment by aschempp** [comment]
I've added `--always` to fix the build issue.

**Comment by BugBuster1701** [comment]
Ändert bei mir nichts, der 404 bleibt. Und ja, `composer install` sowie `npm install` habe ich vorher aufgerufen.
Ich bekomme allergings beim phing Aufruf beim ersten Mal ein
```
Contao Manager > npm:
     [echo] Installing UI dependencies
     exec] npm ERR! Maximum call stack size exceeded
```
Ich rufe es dann nochmal auf und dann läuft es durch.

**Comment by BugBuster1701** [comment]
Welche node.js / npm Version verwendet ihr? Ich habe hier noch eine Fehlermeldung bei mir gefunden:
```
Contao Manager > build:

     [echo] Compiling UI files
Property ${version} => af70fd1
     [exec] Executing command: npm run build 2>&1
     [exec] 
     [exec] > contao-manager@ build /daten/github_sammlung/contao-manager/contao-manager-af70fd1
     [exec] > node build/build.js
     [exec] 
     [exec] /daten/github_sammlung/contao-manager/contao-manager-af70fd1/build/build.js:20
     [exec] let webpackConfig = require('./webpack.config.js');
     [exec] ^^^
     [exec] 
     [exec] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
     [exec]     at exports.runInThisContext (vm.js:53:16)
     [exec]     at Module._compile (module.js:374:25)
     [exec]     at Object.Module._extensions..js (module.js:417:10)
     [exec]     at Module.load (module.js:344:32)
     [exec]     at Function.Module._load (module.js:301:12)
     [exec]     at Function.Module.runMain (module.js:442:10)
     [exec]     at startup (node.js:136:18)
     [exec]     at node.js:966:3
     [exec] 
     [exec] npm ERR! Linux 4.4.0-66-generic
     [exec] npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
     [exec] npm ERR! node v4.2.6
     [exec] npm ERR! npm  v3.5.2
     [exec] npm ERR! code ELIFECYCLE
     [exec] npm ERR! contao-manager@ build: `node build/build.js`
     [exec] npm ERR! Exit status 1
     [exec] npm ERR!
     [exec] npm ERR! Failed at the contao-manager@ build script 'node build/build.js'.
     [exec] npm ERR! Make sure you have the latest version of node.js and npm installed.
     [exec] npm ERR! If you do, this is most likely a problem with the contao-manager package,
     [exec] npm ERR! not with npm itself.
     [exec] npm ERR! Tell the author that this fails on your system:
     [exec] npm ERR!     node build/build.js
     [exec] npm ERR! You can get information on how to open an issue for this project with:
     [exec] npm ERR!     npm bugs contao-manager
     [exec] npm ERR! Or if that isn't available, you can get their info via:
     [exec] npm ERR!     npm owner ls contao-manager
```
Wie zu sehen habe ich hier
* node v4.2.6
* npm  v3.5.2

**Comment by leofeyer** [comment]
Ich habe node v7.7.3 und npm 4.1.2.

**Comment by BugBuster1701** [comment]
Dann werde ich das mal mit einer aktuelleren Ubuntu Version in einer VM probieren, habe gelesen das webpack2 mindestens node 5.x braucht.

**Comment by tsarma** [comment]
I can not build the phar file, my environment is set up with:

System Debian 8 Jessie
Phing 2.8.2
node v7.7.3
npm 4.1.2
PHP: Apache 2.0 Handler

I have also discussed this in forum. https://community.contao.org/de/showthread.php?65487-Installation-%C3%BCber-contao-manager-phar-schl%C3%A4gt-fehl

**Comment by Olli** [comment]
Danke an @leofeyer und @BugBuster1701 ... lag wohl an der Node Version. Die von Debian mit gelieferte ist 4.irgendwas. Die sind aus irgend einem Grund überhaupt nicht akutell.
Nächster Punkt - custom php executeable für die Tenside Tasks aber das ist ein neues Issue (#59 )
