### ISSUE TITLE
Always update contao/conflicts

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-manager#522]
Currently, the Contao Manager never allows a true, full package update, but only updates specific packages that have been selected/are visible under _Packages_. Even when using the package update button, only the visible packages will be included in the update.

This means however, that the `contao/conflicts` package never gets updated, once it has been installed, because it's a "hidden" package. Thus, whenever any package gets updated by the Contao Manager, `contao/conflicts` should be included in the update as well.

**Comment by aschempp** [comment]
Fixed in ddc59fc0974b82f98b8135a43593ac321e265d22

> Currently, the Contao Manager never allows a true, full package update

Not exactly true, you _can_ do a full `composer update` in the maintenance screen 😉

**Comment by fritzmg** [comment]
> Not exactly true, you _can_ do a full `composer update` in the maintenance screen 😉

Right, forgot about that ;)
