### ISSUE TITLE
Systemprüfung nach Update meldet Installationsprobleme für Contao

### ISSUE THREAD

**Issue by rentieropa** [contao/contao-manager#523]
Leider liegt bei mir das gleiche Problem wie in #187 vor. Die dortigen Hinweise helfen mir nicht. Wir betreiben Contao 4.5. Wenn ich das Install-Tool starte ist scheinbar alles in Ordnung.

**Comment by aschempp** [comment]
Vielleicht hast du dasselbe Problem wie #187 ?

> es scheint ein Problem deines Servers und nicht des Contao Managers zu sein
