### ISSUE TITLE
Falsche Bezeichnung für Version 4.9

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#524]
Während einer Neuinstallation mit dem Contao Manager wird bei der Version 4.9 die Bezeichnung "Neuste" statt "Langzeit-Support" angezeigt.

![image](https://user-images.githubusercontent.com/1632642/74826323-b08d0900-530b-11ea-8e6d-6d31999dc6e5.png)

**Comment by fritzmg** [comment]
Der LTS Zeitraum der 4.9 beginnt im August 2020: https://contao.org/en/release-plan.html

**Comment by Mynyx** [comment]
Jedenfalls in Zusammenhang mit den daneben angezeigten Erläuterungen kann ich das so nicht nachvollziehen.

Die Version 4.9 ist eine LTS-Version, auch wenn der LTS-Zeitraum noch nicht begonnen hat.

![image](https://user-images.githubusercontent.com/1632642/74829097-9144aa80-5310-11ea-8c38-5a697216e188.png)

**Comment by fritzmg** [comment]
> **Neuste:** Eine neue Version wird alle sechs Monate jeweils im Februar und August veröffentlicht.

Contao **4.9** kam 6 Monate nach Contao **4.8**. Contao **4.9** ist nun die **Neuste** Version. Danach ist Contao **4.10** die **Neuste** Version, während Contao **4.4** und Contao **4.9** Versionen mit **Langzeit-Support** sind.

So ist zumindest meine Interpretation und Sicht der Dinge ;)

**Comment by frontendschlampe** [comment]
@fritzmg deine Beschriebung ist schon korrekt, aber trotzdem ist es etwas verwirrend, da muss ich @Mynyx zustimmen, denn ein (neuer) Nutzer, wird ggfs. die 4.4 LTS installieren, weil die ihm einen langen Support suggeriert, statt die 4.9, weil diese ja die neuste Version ist und (noch) keine LTS. Des weiteren wird die 4.9 ja bereits überall als LTS beschrieben. Die 4.9 ist aktuell beides: die neuste und LTS Version.

**Comment by aschempp** [comment]
Valider Punkt. Eigentlich müssten wir nur noch die Installation von Contao 4.9 erlauben, was meint ihr @contao/developers ?

**Comment by Toflar** [comment]
Ganz ehrlich? Ich hätte am liebsten, dass es eine JSON-Version von https://contao.org/en/release-plan.html gäbe, wie das viele andere Projekte auch haben. Dann lassen sich die aktuell unterstützten Versionen automatisiert abfragen und erfordern auch kein neues Release des Managers.
Beispiele:
* Symfony: https://symfony.com/releases.json
* PHP: https://www.php.net/releases/index.php?json

Beide Formate find ich nicht sonderlich gut. Ich würde sowas erwarten:

```json
{
    "4.4": {
        "current": "4.4.47",
        "supported_until": "2021-12-31",
        "lts": true
    },
    "4.9": {
        "current": "4.9.0",
        "supported_until": "2024-02-29",
        "lts": true
    }
}
```

Und bei Release der 4.10 dann halt ein weiterer Eintrag mit `"lts": false`.
Imho sollte der Manager einfach alle aktuell supporteten Versionen mit deren EOL-Daten ausgeben, über Sinn oder Unsinn noch eine 4.4 zu installieren, wenn die 4.9 da ist, sollten wir nicht diskutieren. Sie ist ja noch supported.

**Comment by aschempp** [comment]
> Dann lassen sich die aktuell unterstützten Versionen automatisiert abfragen

was nicht wirklich meine Frage beantwortet. Zeigen wir jetzt (zum Release einer neuen LTS) die alte LTS noch an, oder nur noch die aktuelle Version?
Für "was anderes installieren" gibt es die Experten-Option, oder wir könnten das bereits im Install-Screen erlauben (Option "eigenen Constraint eingeben").

**Comment by Toflar** [comment]
Die Frage habe ich doch beantwortet?

> Imho sollte der Manager einfach alle aktuell supporteten Versionen mit deren EOL-Daten ausgeben, über Sinn oder Unsinn noch eine 4.4 zu installieren, wenn die 4.9 da ist, sollten wir nicht diskutieren. Sie ist ja noch supported.

**Comment by fritzmg** [comment]
I agree with @Toflar here.

**Comment by aschempp** [comment]
Geändert in e6472be18e845a578c577b6051619d433d93757e
