### ISSUE TITLE
Konsolenausgabe bei Fehler automatisch einblenden

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#525]
Wenn ein Fehler auftritt, wird folgende Meldung angezeigt;
> Konsolentask beendet!
> Der Hintergrund-Prozess wurde unerwartet beendet. Bitte prüfen Sie die Konsolenausgabe.

Es wäre hilfreich, wenn in diesem Fall die Konsolenausgabe automatisch eingeblendet werden würde. Denn dass hierzu das Icon oben rechts angeklickt werden muss, erschließt sich nicht unbedingt von alleine.

**Comment by aschempp** [comment]
das sollte eigentlich bereits der Fall sein …
