### ISSUE TITLE
Unterverzeichnisse in /vendor oder /assets werden doppelt installiert

### ISSUE THREAD

**Issue by Babelfisch** [contao/contao-manager#527]
Heute ist die Installation von Contao 4.9 über den Contao Manager im Browser bei mir fehlgeschlagen. Installiert habe ich es auf einem Server von TimmeHosting und nginx. Die Einstellungen auf dem Server sollten passen und TimmeHosting wurde als Hoster ausgewählt.

In der Konsole standen viele Warnungen in dieser Art drin

```
Generating optimized autoload files
Warning: Ambiguous class resolution, "webignition\RobotsTxt\Inspector\Inspector" was found in both "/var/www/…/web/vendor/webignition/robots-txt-file/src/src/Inspector/Inspector.php" and "/var/www/…/web/vendor/webignition/robots-txt-file/src/Inspector/Inspector.php", the first will be used.
```

Und das stimmt auch, alle Vendor-Pakete haben ein `/src` Verzeichnis und darin noch mal ein `/src/src` mit noch mal allen PHP-Dateien. Das sollte sicherlich nicht so sein. Alle anderen Verzeichnisse innerhalb der Pakete und Dateien sind ebenfalls doppelt. Das sieht dann also bspw. so aus:

```
/vendor/clue
/vendor/clue/stream-filter
/vendor/clue/stream-filter/examples
/vendor/clue/stream-filter/examples/examples
/vendor/clue/stream-filter/src
/vendor/clue/stream-filter/src/src
/vendor/clue/stream-filter/tests
/vendor/clue/stream-filter/tests/tests
```

Bei /assets das gleiche. Auch dort sind alle Verzeichnisse innerhalb doppelt, also bspw. `/assets/ace/js/js`.

Da bei TimmeHosting der DocumentRoot `…/web` heißt und meine Vermutung war, dass es möglicherweise an der dadurch bedingten Verzeichnistruktur `…/web/web` liegen könnte, habe ich testweise einen Ordner `…/web/contao` angelegt und den DocumentRoot darauf gelegt. Damit lieft die Installation dann mit ansonsten identischen Einstellungen probemlos durch und es gibt auch keine doppelten Verzeichnisse mehr.

Vermutlich tritt der Fehler also nur dann auf, wenn der DocumentRoot schon auf einem Ordner `/web` liegt und der Contao Manager dann im Order `/web/web` liegt.

**Comment by aschempp** [comment]
Ich habe diesen Fehler auch schon gesehen. Ich denke es liegt aber eher daran, dass Composer sich "verschluckt". Wenn du den Vendor-Ordner einfach löschst und neu installierst sollte es auch funktionieren. Kannst du das testen?

**Comment by fritzmg** [comment]
@Babelfisch were you able to reproduce this consistently, multiple times this way?

**Comment by Babelfisch** [comment]
Hmm, merkwürdig. Habe es gerade noch mal auf dem gleichen Server in ./web/web installiert und da lief die Installation gleich beim ersten Versuch anstandslos durch. Es gibt auch keine doppelten Verzeichnisse. Da hast du wohl Recht Andreas, dass sich der Composer nur mal „verschluckt“ hat.

**Comment by fritzmg** [comment]
Schade. Der Fehler tritt im Forum öfter auf - aber eine zuverlässige Reproduktion gibt es bisher nicht. Mit dem Contao Manager wird es auch nichts direkt zu tun haben, sondern ist irgendein seltsamer Fehler innerhalb von Composer.

**Comment by aschempp** [comment]
Ich schliesse das mal, da der Manager daran nicht wirklich viel ändern kann. Vielleicht sollte jemand suchen ob der Fehler bei [composer/composer](https://github.com/composer/composer) bekannt ist oder dort melden.

**Comment by fritzmg** [comment]
Duplicate of #307 actually.
