### ISSUE TITLE
Session-Timeout ohne Login

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao-manager#529]
Wenn der Contao Manager aufgerufen wird, ich mich aber nicht anmelde, bekomme ich nach einer gewissen Zeit die Meldung «Session-Timeout».

Diese Meldung sollte ich aber nur erhalten, wenn ich auch wirklich eingeloggt bin.

![cm](https://user-images.githubusercontent.com/1942550/75113476-98402580-564e-11ea-8016-5ac13f641294.png)

**Comment by aschempp** [comment]
hast du dich explizit abgemeldet oder einfach nur die Seite geöffnet?

**Comment by netzarbeiter** [comment]
Nur die Login-Seite geöffnet und nichts gemacht.

**Comment by aschempp** [comment]
In Version 1.3 wurde diese Behandlung verbessert. Ich gehe davon aus dass dies damit erledigt ist.
https://contao.org/de/news/contao-manager-1-3-0-verfuegbar.html

**Comment by netzarbeiter** [comment]
Auch in der Version 1.3 erhalte ich den Countdown ohne angemeldet zu sein.
