### ISSUE TITLE
Nicht nachvollziehbare Datumsangaben bei Paketen

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#530]
Die Datumsangaben sind nicht nachvollziehbar. Für Contao 4.9.0 wird als Veröffentlichungsdatum der 07.02.2020 statt dem 18.02.2020 angezeigt.

![image](https://user-images.githubusercontent.com/1632642/75188009-a6c03700-574b-11ea-80c4-3a9a5e39021b.png)

![image](https://user-images.githubusercontent.com/1632642/75188066-c6575f80-574b-11ea-8c8a-59fcdb971650.png)

**Comment by xchs** [comment]
Wie auf Deinem Screenshot zu sehen ist, geht es hier um das [contao/manager-bundle](https://github.com/contao/manager-bundle). Das aktuellste Release stammt vom 07.02.2020: https://github.com/contao/manager-bundle/releases/tag/4.9.0
