### ISSUE TITLE
CM will Verzeichnis außerhalb des "web"-Ordners anlegen

### ISSUE THREAD

**Issue by the-unknown** [contao/contao-manager#531]
Hallo zusammen,

ich nutze auf meinem Server ISPConfig zur Verwaltung des Webspace.
Jeder "Kunde" hat einen eigenen Ordner in dem es noch einmal Unterordner gibt. 
Einer davon heißt "web" und das ist der Root-Ordner der Website.

Wenn ich nun den contao-manager.phar.php über den Browser aufrufe, dann kommt sofort folgende Fehlermeldung:
`ERROR 500 Failed to create "/var/www/clients/client3/web19/contao-manager": mkdir(): open_basedir restriction in effect. File(/var/www/clients/client3/web19/contao-manager) is not within the allowed path(s): (/var/www/clients/client3/web19/web).`

Das ist natürlich absolut richtig, denn wie es mir scheint versucht contao-manager den Ordner in einem Bereich anzulegen, wo er gar nicht hin darf - nämlich genau ein Verzeichnis höher als der "web"-Ordner und das soll und darf natürlich nicht sein.

Jetzt frage ich mich: Warum will der contao-manager aus dem Web-Verzeichnis ausbrechen?

**Comment by fritzmg** [comment]
> Das ist natürlich absolut richtig, denn wie es mir scheint versucht contao-manager den Ordner in einem Bereich anzulegen, wo er gar nicht hin darf - nämlich genau ein Verzeichnis höher als der "web"-Ordner und das soll und darf natürlich nicht sein.

Das darf und muss so sein. Hier eine kurze Übersicht der Verzeichnisstruktur von Contao: https://docs.contao.org/dev/getting-started/starting-development/#structure

**Comment by the-unknown** [comment]
@fritzmg sorry, aber eben nicht. 
Vielleicht hab ich mich nicht klar genug ausgedrückt:

Ich nehme das Beispiel aus der Doku, die du mir hier verlinkt hast:

`Beispiel: example.com zeigt auf das Verzeichnis /www/example/web`

Der Contao-Manager versucht sich in den Ordner `/www/example` zu installieren und nicht in `/www/example/web`, denn da hat er keine Schreibrechte und die soll er auch mit Absicht nicht haben. 

In keiner einzigen Doku steht etwas davon, dass der Contao-Manager versucht aus dem "web" Verzeichnis auszubrechen.

**Comment by fritzmg** [comment]
Wie bereits erwähnt, ist das normal.

**Comment by leofeyer** [comment]
@the-unknown Du musst bitte in Deinem Document-Root einen Ordner `/web` anlegen. Der gesamte Pfad wäre dann `/www/example/web/web` (zweimal `/web`).

**Comment by aschempp** [comment]
Die Version 1.3 kann die benötigten Verzeichnisse nun automatisch anlegen 😎 
https://contao.org/de/news/contao-manager-1-3-0-verfuegbar.html
