### ISSUE TITLE
Konfiguration error_log auf nicht vorhandenes Verzeichnis

### ISSUE THREAD

**Issue by Mynyx** [contao/contao-manager#532]
Der Contao Manager definiert die PHP-Direktive ``error_log`` mit dem Pfad ``/www/htdocs/xxx/contao-manager/logs/error.log``. Der Ordner ``logs`` ist jedoch nicht vorhanden.

**Comment by aschempp** [comment]
Wird der Ordner nicht automatisch angelegt? Das wäre ja ein Apache/Webserver-Problem?

**Comment by Mynyx** [comment]
Offenbar nicht (siehe auch https://stackoverflow.com/questions/18556710/does-php-create-the-directory-for-the-error-log-if-it-does-not-exist).

Ist es denn tatsächlich sinnvoll, den Pfad festzulegen? In Contao selbst geschieht dies nicht.
