### ISSUE TITLE
Fehler beim Start des Contao Managers

### ISSUE THREAD

**Issue by Andi-cto** [contao/contao-manager#536]
_Edit: 
Das beschriebene Problem konnte ich mindestens fünfmal reproduzieren. Beim sechsten Mal ist es nicht mehr aufgetreten.

Fehlermeldung beim Starten des Contao Managers:

> System Recovery
> The Contao Manager detected files that look like Contao, but the Command Line Interface does not work as expected. Please choose an option to repair your installation.
> Automatic Repair (…)

Beim Ausführen der Automatic  Repair dann folgende Fehlermeldung:

> Installing Composer Dependencies 
> Console task terminated!
> The background task has stopped unexpectedly. Please check the console protocol.

Ok-Button ausgegraut (“wheel” bzw. lässt sich nicht drücken; siehe Screenshot)

Hier das Protokoll:

```
$ /usr/bin/php7.3 -q /srv/www/ff01/public/web/contao-manager.phar.php composer install --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 5 installs, 1 update, 0 removals
  - Downgrading contao/listing-bundle (4.9.1 => 4.4.47): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
Downloading
In RemoteFilesystem.php line 686:
                                             
  Could not authenticate against github.com  
                                             

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>...]


# Process terminated with exit code 255
# Result: Unknown error


---

### The background task has stopped unexpectedly ###
```
<img width="780" alt="Bildschirmfoto 2020-03-25 um 10 21 14" src="https://user-images.githubusercontent.com/62643903/77522226-2db81a80-6e84-11ea-9efe-758df8529164.png">

**Comment by aschempp** [comment]
Kannst du noch erwähnen warum du das Ticket geschlossen hast?

**Comment by joseluisq** [comment]
We have faced the same problem with v4.9.2 problem after a zip example extension was uploaded.
The console interface gives us nothing about what was going on and also we have no found any logs on var/logs/prod-...

How can we debug it? Because we really don't know what is failing.
