### ISSUE TITLE
composer-install.set.json wird nicht gefunden

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#537]
Bug kommt unter der aktuellen 1.2.4 immer noch vor.

So wie ich das beobachtet habe, steht der Bug in Zusammenhang mit folgendem Fehler:

https://community.contao.org/de/showthread.php?72798-composer-no-unzip-command-installed

Da unzip nicht gefunden wird, werden die Dateien von PHP unzipped. Hierbei werden diese mit falschen Rechten angelegt und der Manager kann die Dateien später nicht einsehen.

_Originally posted by @mwoelke in https://github.com/contao/contao-manager/issues/438#issuecomment-603132794_

**Comment by jankout** [comment]
Es gibt diesen Fehler auch noch mit 1.2.7. Aber das wisst ihr wahrscheinlich schon, wenn es noch offen ist.Bei mir tritt es bei United Domains. Woanders läuft es problemlos.

**Comment by aschempp** [comment]
Gibt es eine Möglichkeit wie wir das reproduzieren können?

**Comment by mwoelke** [comment]
Mir fällt auf die schnelle nicht ein wie man das gezielt reproduzieren könnte. Auch weil ich mir immer noch nicht ganz sicher bin, was genau den Fehler verursacht.

Erst gestern hatte ich den Fehler wieder bei Mittwald, das composer update hat aber trotzdem funktioniert.

Was ist überhaupt der Zweck der composer-install.set.json ?

**Comment by aschempp** [comment]
Das ist die Konfigurationsdatei für den Hintergrund-Prozess, darin steht welcher Befehl im Hintergrund ausgeführt werden soll. Da es trotzdem funktioniert könnte es ein temporäres Problem sein, oder sowas wie dass die Datei langsamer geschrieben wird als der Prozess startet.

Tritt der Fehler denn bei jedem Update auf?

**Comment by localbranding-de** [comment]
Bei mir tritt der Fehler auf wenn ich versuche ein Eigenes Paket(zip) hochzuladen und zu installieren.

**Comment by aschempp** [comment]
In Version 1.3 wurde diese Behandlung verbessert. Ich gehe davon aus dass dies damit erledigt ist.
