### ISSUE TITLE
Fehler bei Neuinstallation - Contao Manager konnte einen Konsolentask nicht starten!

### ISSUE THREAD

**Issue by EliasC10** [contao/contao-manager#540]
ich versuche in Verbindung mit MAMP die aktuelle Contao Version 4.9 auf meinem Mac zu installieren. Trotz der richtigen Systemvorrausetzungen und Einstellungen bekomm ich diese Fehlermeldung.
<img width="756" alt="Bildschirmfoto 2020-04-01 um 18 49 45" src="https://user-images.githubusercontent.com/32737727/78164366-f203ee80-7449-11ea-833a-6ca3f4ebdc98.png">
Das Fenster lässt sich auch nicht schließen. Eine Systemprüfung liefert auch kein anderes Ergebnis.

Contao 4.9
MAMP 5.7
PHP 7.4.2
MySQL 5.7.26

**Comment by aschempp** [comment]
hast du mal versucht per Kommandozeile zu installieren? Verwendest du irgendwelche AntiVirus oder ähnliche Produkte?

**Comment by EliasC10** [comment]
Das Problem war, dass eine weitere Contao-Installation bereits in einem anderen Tab ausgeführt wurde.
