### ISSUE TITLE
Debug-Modus nach Logout im Contao Manager

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao-manager#541]
Ich bin gerade beim Testen des Debug-Modus über etwas gestolpert. Aktiviere ich den Debug-Modus über den Manager, wird ein Cookie gesetzt. Melde ich mich beim Manager ab, bleibt das Cookie und damit der Debug-Modus erhalten.
Im Backend bin ich dabei nicht eingeloggt. Getestet habe ich im Firefox. Über die Entwicklerwerkzeuge des Firefox ist der Cache deaktiviert.
Führe ich die Aktivierung des Caches über das Backend aus, melde mich danach ab wird das Session-Cookie gelöscht und der Debug-Modus ist deaktiviert.
Ist das Verhalten im Manager so gewollt oder technisch bedingt?

**Comment by aschempp** [comment]
Ich würde sage das ist technisch bedingt. Der Debug-Modus funktioniert über ein Cookie. Das Cookie kann entweder im Contao Backend (über den Button oben) gesetzt werden, oder über den Manager. Ein an/abmelden bei Manager hat darauf keinen Einfluss, denn der Manager weiss auch nicht ob dieses Cookie vom Manager gesetzt wurde.

Aus meiner Sicht ist das aber kein tieferes Problem, oder? Das Cookie gilt nur für dich, und es verfällt nach 30 Minuten wenn du Contao nicht benutzt.
