### ISSUE TITLE
Cloud Resolver is not resolving?

### ISSUE THREAD

**Issue by planepix** [contao/contao-manager#544]
Hi,
reported in the forum ( https://community.contao.org/de/showthread.php?77682-Manager-bricht-Konsolentask-grunds%C3%A4tzlich-ab&p=523386#post523386 ) and also tested by several installations, the error ”The background task was canceled ( Der Hintergrundprozess wurde unerwartet beendet ) occurs a few seconds after starting the resolving process.

Is there actually a maintenance of the resolver cloud?

Thank you for any hint.

**Comment by planepix** [comment]
Guess it happened while updating the resolver to 2.2.7.
Since this morning it works quite well.
So i close this issue.

**Comment by NinaG** [comment]
Happened here yesterday several times. Today quite often.

Depending on the situation I get an error like this (or more complicated):

> HTTP request to https://composer-resolver.cloud/jobs failed with status code 500 ()
> ---
> ### Der Hintergrundprozess wurde unerwartet beendet ###

Always something with status code 500.

I try to update or install any extension in the contao manager. It happens 2 out of 3 times today. Doesn't matter which extension.
