### ISSUE TITLE
Link to backend and install tool uses domain.tld+install or contao

### ISSUE THREAD

**Issue by mathContao** [contao/contao-manager#546]
Hi,

the both links "backend" and "install tool"
![grafik](https://user-images.githubusercontent.com/1645099/79071847-24310e00-7cde-11ea-862b-d56108763e21.png)
are linked directly "hard" to domain.tld/contao and domain.tld/contao/install 

the "problem": I installed the contao manager not in domain.tld/web (I did this: domain.tld/foo/bar/web). So the direct link is not working.

I think it would be nice to check if domain.tld/contao and domain.tld/contao/install exists. If not: give a message/hint.

**Comment by xchs** [comment]
You have to set the DocumentRoot accordingly.

**Comment by mathContao** [comment]
I know.

And it would be nice, if the contao manager would check this too.

**Comment by fritzmg** [comment]
An unsecure installation like that is only possible under the `localhost` domain.

**Comment by mathContao** [comment]
the contao manager does not mark it as unsecure. Everything is green.

(for myself I can manage/solve this issue without any problems.)

**Comment by fritzmg** [comment]
> (for myself I can manage/solve this issue without any problems.)

How? If you open the Contao front or back end in your case, Contao should tell you, that it is an unsecure installation. Or are you working under `localhost`?

**Comment by mathContao** [comment]
I am not working on my localhost.

my settings:

sub.domain.tld/foo/bar/contao-manager.php

CM links to install tool: sub.domain.tld/contao/install (there is nothing)

so I created a new sub domain:
sub2.domain.tld/contao-manager.php and it works for install tool too: sub2.domain.tld/contao/install

But I did not see any message, that sub.domain.tld/foo/bar/ is "unsecure".
![grafik](https://user-images.githubusercontent.com/1645099/79074715-46328c80-7cee-11ea-8b18-d64984273b5a.png)

**Comment by fritzmg** [comment]
> But I did not see any message, that sub.domain.tld/foo/bar/ is "unsecure".

You should see one, if you access `sub.domain.tld/foo/bar/`, `sub.domain.tld/foo/bar/app.php`, `sub.domain.tld/foo/bar/contao/install` or `sub.domain.tld/foo/bar/app.php/contao/install`.

**Comment by mathContao** [comment]
I get, when I access sub.domain.tld/foo/bar/web/contao/install/install.php and sub.domain.tld/foo/bar/web/app.php/contao/install/install.php:
![grafik](https://user-images.githubusercontent.com/1645099/79075040-7bd87500-7cf0-11ea-8ea9-0d362a72cc42.png)

var/logs:
[2020-04-12 19:08:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-04-12 19:08:03] request.CRITICAL: Uncaught PHP Exception Contao\CoreBundle\Exception\InternalServerErrorHttpException: "Your installation is not secure. Please set the document root to the /web subfolder." at /var/www/xxx/html/foo/bar/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 94 {"exception":"[object] (Contao\\CoreBundle\\Exception\\InternalServerErrorHttpException(code: 0): Your installation is not secure. Please set the document root to the /web subfolder. at /var/www/xxx/html/foo/bar/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:94, Contao\\CoreBundle\\Exception\\InsecureInstallationException(code: 0): Your installation is not secure. Please set the document root to the /web subfolder. at /var/www/xxx/html/foo/bar/vendor/contao/core-bundle/src/EventListener/InsecureInstallationListener.php:42)"} []

**Comment by aschempp** [comment]
that's exactly what you should get (on the command line). Interestingly, you should also see a more descriptive error message. However, that's not a Contao Manager issue. The Manager _assumes_ that you have set up your host correctly and use the correct domain. Any other than the default setup is not supported.

Feel free to open an issue on `https://github.com/contao/contao` about the non-descriptive error message though 😊
