### ISSUE TITLE
copied used contao-manager.php -> Uncaught PharException

### ISSUE THREAD

**Issue by mathContao** [contao/contao-manager#548]
I copied contao-manager.php from an existing to a new folder.

And got that uncaught Exception, when I want to use the copied file.

`Fatal error: Uncaught PharException: phar "/var/www/xxx/contao-4.9.x/web/contao-manager.php" SHA1 signature could not be verified: broken signature in /var/www/xxx/contao-4.9.x/web/contao-manager.php:102 Stack trace: #0 /var/www/xxx/contao-4.9.x/web/contao-manager.php(102): Phar::webPhar(NULL, 'index.html', '', Array, 'rewrites') #1 {main} thrown in /var/www/xxx/contao-4.9.x/web/contao-manager.php on line 102`

(I know, it is a stupid move to copy it instead to use a new one)

**Comment by xchs** [comment]
Only move/copy the PHAR file (i.e. `contao-manager.phar`) and not the `contao-manager.phar.php`.

**Comment by mathContao** [comment]
I know.

I think, that is not an unusual mistake.

The exeption is created but not handled.

A short error message could help.

**Comment by aschempp** [comment]
we cannot handle this case. Copying the `.php` file using a FTP program breaks the file in most cases, that's an issue of the FTP protocol not the Contao Manager.
