### ISSUE TITLE
Unable to install Contao 4.9 on Mac through localhost MAMP

### ISSUE THREAD

**Issue by hasnainshafqatmlt** [contao/contao-manager#549]
Hi everyone 

I am trying to install Contao manager through MAMP in my Macbook but I 'm stuck on this error everytime. I don't know what is the reason.

```
ERROR 500 Unknown installation status
Some files were found on your server but no known Contao version could be detected.
You must either manually repair your application or remove the following files and folders to install Contao:

```
here is my installation video and error 
https://www.youtube.com/watch?v=uMXUxNiO6Mk

Thanks in advance

**Comment by xchs** [comment]
The `web/` subdirectory must be empty (except `contao-manager.phar.php`), so remove the `project1/` subfolder and try again.

**Comment by hasnainshafqatmlt** [comment]
actually I just found solution that I've to set MAMP Apache webs server root path to my project web folder.
MAMP - Preferences -> Web Server 
here you have to set Document Root path to your project web folder.
then it runs the contao-manager.phar.php correctly.

Thanks
