### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by GwendalB** [contao/contao-manager#551]
Hi, 

i tried to install the Mate Theme but I had this failure, what did i do wrong? I am beginner with contao

Can anyone tell me what to do?
Thanks

Gwen

![contao bug1](https://user-images.githubusercontent.com/55398529/80019966-996bc280-84d8-11ea-98c6-f09b091da455.PNG)

**Comment by aschempp** [comment]
Please contact the Contao community forums or the Slack channel for support.
