### ISSUE TITLE
ALL INKL Hoster does no longer support Contao CMS

### ISSUE THREAD

**Issue by mirkotravel** [contao/contao-manager#553]
based on recommendation from Contao I signed up to all-inkl.com hosting only to find out that they no longer support Contao. So I cancelled my contract with them.
here the response from the support team 
“vielen Dank für Ihre Nachricht.

Contao bieten wieder leider über die Software-Installation nicht mehr an. Sie können es aber trotzdem manuell installieren.”

**Comment by fritzmg** [comment]
You should never use the installation option by the hoster itself. And as All-Inkl themselves said, it is perfectly possible to install Contao on All-Inkl hosting packages.

**Comment by contaoacademy** [comment]
I use several Contao Installations on All-Inkl. Pleas install by yourself.
https://youtu.be/GIgmdc1QJVA

**Comment by bezin** [comment]
We also run plenty Contao instances on All-Inkl. You can definitely install it with the Contao Manager.
