### ISSUE TITLE
Error 500 Uncaught TypeError 

### ISSUE THREAD

**Issue by herrweiss77** [contao/contao-manager#555]
Nachdem ich den Prod-Cache vom Contao Manager (1.2.4) gelöscht habe erscheint im CM folgende Fehlermeldung:

```
ERROR 500 Error: Uncaught TypeError: Return value of Contao\ManagerApi\Controller\Server\PhpCliController::runIntegrityChecks() must be of the type array, null returned in phar:///home/www/web/contao-manager.phar.php/api/Controller/Server/PhpCliController.php:52 Stack trace: `#0 phar:///home/www/web/contao-manager.phar.php/api/Controller/Server/PhpCliController.php(38): Contao\ManagerApi\Controller\Server\PhpCliController->runIntegrityChecks(Object(Contao\ManagerApi\Process\ConsoleProcessFactory)) 
#1 phar:///home/www/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(146): Contao\ManagerApi\Controller\Server\PhpCliController->__invoke(Object(Contao\ManagerApi\Config\ManagerConfig), Object(Contao\ManagerApi\System\ServerInfo), Object(Contao\ManagerApi\Process\ConsoleProcessFactory)) 
#2 phar:///home/www/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->ha
```

Der Fehler tritt wohl bei der Prüfung vom PHP Kommandozeilen-Programm auf.

Ich hatte vorher eine config.yml Datei angelegt, daraufhin habe ich den Prod-Cache gelöscht und dann erschien die Fehlermeldung. Die config.yml habe ich zwischenzeitlich wieder gelöscht, hat aber nichts gebracht.

Es handelt sich um ein stabiles Live-System, was schon seit einem Jahr sauber läuft. 

Hosting läuft über Webhostone (Power-App)
PHP Version 7.3.17-1+0~20200419.57+debian10~1.gbp0fda17, keine bekannten Probleme gefunden.

**Comment by fritzmg** [comment]
Someone on Slack had the same problem: https://contao.slack.com/archives/CK4J0KNDB/p1588746692076200

**Comment by aschempp** [comment]
This should be fixed already in https://github.com/contao/contao-manager/commit/aca1bdf2f80756c7a482a505cca2edac9826b3e8 (will be released in 1.2.5)
