### ISSUE TITLE
Update auf Contao 4.9.3 schlägt fehl

### ISSUE THREAD

**Issue by jaennert** [contao/contao-manager#557]
### > # Memory usage: 457.45MB (peak: 2184.6MB), time: 41.29s.

$ /opt/php-7.4/bin/php -q /var/www/v1696/htdocs/textil/web/contao-manager.phar.php composer install --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader

ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 1 update, 0 removals
  - Updating symfony/http-client-contracts (v2.0.1 => v2.1.1): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
Downloading (100%)
Generating optimized autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

Danach bricht die Konsolentask ab. Die bestehende Installation 4.9.2 läuft auf dem Server. Nach einigen Versuch konnte ich das Theme ODD aktualisieren.

Danke für euere Hilfe.
Erich Jännert

**Comment by planepix** [comment]
Link zum Forenthread: https://community.contao.org/de/showthread.php?77998-Update-von-4-9-2-auf-4-9-3-l%C3%A4uft-nicht-durch&p=525448#post525448

**Comment by fritzmg** [comment]
@jaennert please use the community forums for support questions.
