### ISSUE TITLE
Contao Manager does not support the IONOS server

### ISSUE THREAD

**Issue by GeisserS** [contao/contao-manager#558]
I cannot update my packages via the Contao Manager. There is always an error message that the background task has failed.
It is also not possible to install additional packages. e.g. the Contao Cookiebar - cookiebar extension for Contao Open Source CMS.

**Comment by contaoacademy** [comment]
Can you post the console output.
You can show it with the button to the upper right.

Do you use the Composer Cloud?

**Comment by GeisserS** [comment]
Yes I use the Composer Cloud.

This is the console output from install "cookiebar extension for Contao Open Source CMS"
```
$ /usr/bin/php7.3-cli -q -d memory_limit=-1 /homepages/12/d822532301/htdocs/contao/web/contao-manager.phar.php composer require codefog/contao-cookiebar --no-suggest --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction
mmap() failed: [12] Cannot allocate memory
mmap() failed: [12] Cannot allocate memory
# Process terminated with exit code 255
# Result: Unknown error
---
### Der Hintergrundprozess wurde unerwartet beendet ###
```

**Comment by fritzmg** [comment]
According to the console output, you are not using the composer cloud resolver.

**Comment by fritzmg** [comment]
Hm, may be the `-d memory_limit=-1` is causing a very low memory limit? I have seen this on other hosters as well, where using `-d memory_limit=-1` is not advisable.

**Comment by aschempp** [comment]
How can it _cause_ a low limit, if it tells PHP to havr **no** limit? You mean the server somehow overrides that?

**Comment by GeisserS** [comment]
I can't give an answer to that, I just installed Contao according to the textbook and now I wanted to implement a Contao cookie bar. I do not understand what the console edition writes, because I am not an expert for Contao.

**Comment by xchs** [comment]
> How can it _cause_ a low limit, if it tells PHP to havr **no** limit? You mean the server somehow overrides that?

See e.g. the PR from Cyon: https://github.com/contao/contao-manager/pull/543

**Comment by aschempp** [comment]
How did you initially install Contao? Also, what error message do you get when trying to update packages?

**Comment by GeisserS** [comment]
**_How did you originally install Contao?_**
I have copied the "contao-manager.phar" into the subfolder web.
"Web" is the root directory.
Then I renamed the contao-manager.phar to contao-manager.phar.php and started it in the browser.
1 & 1 IONOS entered and installed as server configuration. Waited until everything was ready and continued working with the theme installation.


**_What error message do you get when trying to update packages?_**
No errors are displayed in the test run.
No errors in the execution of the overall package "Contoo 4 manga bundle"

**Install Contao Cookiebar**
error
```
$ /usr/bin/php7.3-cli -q -d memory_limit = -1 /homepages/12/d822532301/htdocs/contao/web/contao-manager.phar.php composer require codefog / contao-cookiebar --no- suggest --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction
mmap () failed: [12] Cannot allocate memory
mmap () failed: [12] Cannot allocate memory
# Process terminated with exit code 255
# Result: Unknown error
---
### The background process ended unexpectedly ###
```

**Comment by aschempp** [comment]
I'm closing this as the discussion seems dead, feel free to reopen if necessary 😊
