### ISSUE TITLE
Aufruf des Installtools leitet auf das Login weiter

### ISSUE THREAD

**Issue by planepix** [contao/contao-manager#560]
Hallo zusammen,
ich habe seit einigen Tage das Phänomen, dass nach einem Update mit dem Manager und dem Aufruf des Installtools immer auf das Login ins Backend weitergeleitet wird.

`https://www.domain.com/contao/login?_hash=B7sETyFTpcnd%2FjucIZ3OCyOUzYMTy6UogoFxfJmUhr0%3D&redirect=https%3A%2F%2Fwww.domain.com%2Fcontao%2Finstall`

Ich habe den Symfony Cache geleert ( var/cache/prod ); ebenso in 5 verschiedenen Browsern das versucht. 

Contao 4.9.3
PHP 7.4.5
Hoster allinkl

Jemand eine Idee woran das liegen kann?
Danke und Grüße

**Comment by do-while** [comment]
Den Effekt kenne ich, ich habe auch verschiedenes probiert.
Ich glaube, dass nach dem Erhöhen des RAM-Speichers dann alles lief (oder es war Zufall).

**Comment by planepix** [comment]
Ich habe im Moment in der htaccess stehen:

```
php_value max_execution_time 300
php_value memory_limit 1G
```
Sollte ich erhöhen?

**Comment by do-while** [comment]
Nein, das sollte ausreichen, dann muss das Problem woanders liegen.
Hast Du noch eine .htaccess in höheren Verzeichnissen liegen, die ggf. einen negativen Einflass hat?

**Comment by planepix** [comment]
Das ist die htaccess im web/.
Sonst gibt nur eine weitere eine Ebene höher mit diesem Inhalt:

```
# This file must be present to prevent Composer from creating it
# see https://github.com/contao/contao-manager/issues/58
```

**Comment by do-while** [comment]
noch höher ist nichts?
dann bin ich ratlos

**Comment by planepix** [comment]
4G eingestellt. Lösche eben mal den prod cache…

**Comment by planepix** [comment]
Und heute versuche ich mich in mehreren Installationen im Backend anzumelden und werde auf die URL des Installtools weitergeleitet… Kurios.

Alle Installationen 4.9.3 mit CM 1.2.4 bei allinkl.

**Comment by planepix** [comment]
Es konnte eingegrenzt werden, dass es an einem Bundle (om-backend) lag.
Nach Deinstallation des Bundles konnte da Installtool wieder normal aufgerufen werden.
