### ISSUE TITLE
Installiere Composer-Abhängigkeiten - Mittwald - Webhosting XXL 9.0

### ISSUE THREAD

**Issue by codesache** [contao/contao-manager#561]
Hallo zusammen,
ich versuche gerade eine frische 4.9er als Grundinstallation auf einer Subdomain bei Mittwald (Webhosting XXL 9.0) zu installieren, die leider mitten drinnen bei "Installing contao-components/jquery (3.4.1): Downloading (100%)" hängen bleibt. 
Ein neuladen der Seite bringt nix.
Ich habe dann die Aktion gestopt!

Bei anderen Hostern (Strato) hatte ich die Grundinstallation und Verzeichnisse komplett gelöscht, Cookies im Browser gelöscht und frisch angefangen. Mit dem zweiten Anlauf hat es dann funktioniert.

Da aber zu dem Zeitpunkt der Grundinstallation noch keine Fehlermeldungen geschrieben werden, ist das etwas schwierig rauszufinden wo es genau klemmt.

Kann es was mit der max_execution_time für den PHP Prozess zu tun haben, das bei vielen Paketen die Installation abbricht?

Wie geht ihr damit vor? 

Viele Grüße
Markus

**Comment by aschempp** [comment]
_eigentlich_ sollte die `max_execution_time` nicht relevant sein, denn die Manager-Prozesse laufen unabhängig davon. Was passiert wenn du die Aktion nicht stoppst, bleibt es immer dort hängen? Bei jeder Installation am selben Punkt?

**Comment by codesache** [comment]
Hallo Andreas,
ich habe es eine Zeit lang laufen lassen, aber über den Manager wird scheinbar die Prozess-Ansicht unter Chrome eingefroren. Mir fällt das besonders mit dem Chrome unter Mac OS auf, das die Aktualisierung vom Prozessfenster sehr viele Ressourcen schluckt. Unter Firefox kommt es mir vor, das es weniger Ressourcen benötigt und das Prozessfenster aktuell bleibt. 

Zu deiner Frage ob die Installation immer beim gleichen Punkt hängen bleibt, kann ich keine Aussage treffen, da es bei einem anderen Projekt auch mitten drin hängen blieb. Bei einer frischen 4.4er bei Strato hatte ich das auch schon mal.

Die Lösung bei dem Mittwald Projekt war jetzt nur die Grundinstallation von Contao ohne zusätzlicher Erweiterungen. Nach dem die durchgelaufen war, habe ich Stück für Stück weitere hinzugefügt. So werde ich es jetzt bei allen Projekten machen, da der Aufwand bei einer missglückten Installation (Löschen aller Verzeichnisse) hinterher unnötig Zeit kostet. Bei anderen Hostern wie Webgo hatte ich das noch nicht erlebt. 

Viele Grüße nach CH und bleib gesund

Markus

**Comment by aschempp** [comment]
Manchmal klemmt es einfach daran, dass die Hoster die Prozesse beenden. Aber wenn du die Verzeichnisse nicht löschst, sondern Contao "drüber installierst", dann sollte es _schneller_ funktionieren. Insbesondere den Ordner `contao-manager` nicht löschen, denn dort werden die Downloads gecacht 😉

**Comment by codesache** [comment]
Danke für den Hinweis!

Gibt es einen Richtwert / Zeit wie lange der PHP Prozess mindestens laufen sollte?

Viele Hostings haben max 240 Sekunden was schon knapp werden kann.

**Comment by aschempp** [comment]
Der Prozess kann mehrere Minuten dauern. Auf der CLI gelten normalerweise bei PHP keine Prozesslimiten, und zusätzlich verwendet der Manager Wege um diese zu umgehen. Es gibt allerdings Hoster welche generell alle Prozesse limitieren, das würdest du ggf. auch merken wenn du per Kommandozeile/SSH einen entsprechenden ausführst.

**Comment by aschempp** [comment]
Interessant wird das ganze aber mit den (voraussichtlichen) Änderungen in Version 1.3, denn dort werden immer alle entsprechenden Limits überschrieben https://github.com/contao/contao-manager/blob/develop/api/Process/ConsoleProcessFactory.php#L229-L242 😉

**Comment by aschempp** [comment]
https://contao.org/de/news/contao-manager-1-3-0-verfuegbar.html
