### ISSUE TITLE
The Contao Manager failed to start a console task!

### ISSUE THREAD

**Issue by learner-kde2020** [contao/contao-manager#563]
After I tried to update (self-update) Contao Manager on Safari I received this message:

The Contao Manager failed to start a console task!
Something went wrong while trying to execute the task in the background.
If this happens again, your server might not be supported.

**Comment by aschempp** [comment]
but the update happened successfully, right?

**Comment by aschempp** [comment]
duplicate of https://github.com/contao/contao-manager/issues/479
