### ISSUE TITLE
Der Contao Manager konnte einen Konsolentask nicht starten!

### ISSUE THREAD

**Issue by Bexer74** [contao/contao-manager#568]
> Resolving dependencies using Composer Cloud v2.2.10

# Job ID wWydu3KJtjQLbXszhD5NJrDYBSd0QQCE1yOFgcIC583PLyxTWZGnBB5xfK2ESP7ew3ihtrREiKPFTG3nazIUF1HFZLHYdGSm5k7OW06XCD4cd completed in 243 seconds
# Memory usage: 471.46MB (peak: 2284.78MB), time: 241.66s.

$ /opt/RZphp73/bin/php-cli -q -d max_execution_time=300 /mnt/web510/e1/53/510601753/htdocs/crowd1-berlin/web/contao-manager.phar.php composer install --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader

composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 52 updates, 0 removals
  - Updating composer/package-versions-deprecated (1.8.0 => 1.8.1): Downloading (100%)
  - Updating symfony/mime (v5.1.0 => v5.1.2): Downloading (100%)
  - Updating symfony/http-foundation (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/event-dispatcher (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/var-dumper (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/debug (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/error-handler (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/http-kernel (v4.4.9 => v4.4.10): Downloading (100%)
  - Updating symfony/dependency-injection (v4.4.9 => v4.4.10): Downloading (100%)
  - Updating symfony/http-client (v4.4.9 => v4.4.10): Downloading (100%)
  - Updating symfony/dom-crawler (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/yaml (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/twig-bridge (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/twig-bundle (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/translation (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/filesystem (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/config (v4.4.9 => v4.4.10): Loading from cache
  - Updating egulias/email-validator (2.1.17 => 2.1.18): Downloading (100%)
  - Updating symfony/security-core (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/string (v5.1.0 => v5.1.2): Downloading (100%)
  - Updating symfony/property-info (v5.1.0 => v5.1.2): Downloading (100%)
  - Updating symfony/inflector (v5.1.0 => v5.1.2): Loading from cache
  - Updating symfony/property-access (v5.1.0 => v5.1.2): Downloading (100%)
  - Updating symfony/security-http (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/security-guard (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/security-csrf (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/security-bundle (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/routing (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/process (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/monolog-bridge (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/lock (v4.4.9 => v4.4.10): Downloading (100%)
  - Updating symfony/finder (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/var-exporter (v5.1.0 => v5.1.2): Downloading (100%)
  - Updating symfony/cache (v4.4.9 => v4.4.10): Downloading (100%)
  - Updating symfony/framework-bundle (v4.4.9 => v4.4.10): Downloading (100%)
  - Updating symfony/expression-language (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/console (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/asset (v4.4.9 => v4.4.10): Loading from cache
  - Updating symfony/templating (v5.1.0 => v5.1.2): Loading from cache
  - Updating symfony/options-resolver (v5.1.0 => v5.1.2): Loading from cache
  - Updating php-http/discovery (1.7.4 => 1.8.0): Downloading (100%)
  - Updating symfony/doctrine-bridge (v4.4.9 => v4.4.10): Downloading (100%)
  - Updating webmozart/assert (1.8.0 => 1.9.0): Downloading (100%)
  - Updating contao/image (1.0.1 => 1.0.2): Downloading (100%)
  - Updating codefog/contao-haste (4.24.6 => 4.24.7): Downloading (100%)
  - Updating nelmio/security-bundle (v2.9.1 => v2.10.1): Downloading (100%)
  - Updating sensiolabs/ansi-to-html (v1.1.3 => v1.2.0): Downloading (100%)
  - Updating symfony/debug-bundle (v4.4.8 => v4.4.10): Downloading (100%)
  - Updating symfony/dotenv (v4.4.8 => v4.4.10): Downloading (100%)
  - Updating symfony/proxy-manager-bridge (v4.4.8 => v4.4.10): Downloading (100%)
  - Updating symfony/stopwatch (v4.4.8 => v4.4.10): Downloading (100%)
  - Updating symfony/web-profiler-bundle (v4.4.8 => v4.4.10): Downloading (100%)
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Generating optimized autoload files
Deprecation Notice: Class League\Uri\Schemes\AbstractUri located in ./vendor/league/uri-schemes/src/Schemes/deprecated.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///mnt/web510/e1/53/510601753/htdocs/crowd1-berlin/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class League\Uri\Schemes\Data located in ./vendor/league/uri-schemes/src/Schemes/deprecated.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///mnt/web510/e1/53/510601753/htdocs/crowd1-berlin/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class League\Uri\Schemes\File located in ./vendor/league/uri-schemes/src/Schemes/deprecated.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///mnt/web510/e1/53/510601753/htdocs/crowd1-berlin/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class League\Uri\Schemes\Ftp located in ./vendor/league/uri-schemes/src/Schemes/deprecated.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///mnt/web510/e1/53/510601753/htdocs/crowd1-berlin/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class League\Uri\Schemes\Http located in ./vendor/league/uri-schemes/src/Schemes/deprecated.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///mnt/web510/e1/53/510601753/htdocs/crowd1-berlin/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class League\Uri\Schemes\Uri located in ./vendor/league/uri-schemes/src/Schemes/deprecated.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///mnt/web510/e1/53/510601753/htdocs/crowd1-berlin/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class League\Uri\Schemes\UriException located in ./vendor/league/uri-schemes/src/Schemes/deprecated.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///mnt/web510/e1/53/510601753/htdocs/crowd1-berlin/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class League\Uri\Schemes\Ws located in ./vendor/league/uri-schemes/src/Schemes/deprecated.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///mnt/web510/e1/53/510601753/htdocs/crowd1-berlin/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
61 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

**Comment by aschempp** [comment]
Please contact the [Contao Community Forums](https://community.contao.org) for support.
