### ISSUE TITLE
Extend abandoned badge to add replacement package

### ISSUE THREAD

**Issue by ngdot** [contao/contao-manager#572]
It would be nice if we could mark the replacement package for an abandoned package directly to install it.

Maybe something like this, or "add suggestion".
![idea](https://user-images.githubusercontent.com/8327905/85720384-aa130180-b6f0-11ea-92ff-8011efd70596.jpg)

**Comment by aschempp** [comment]
Here's what it will look like in 1.3 😊 
<img width="754" alt="Bildschirmfoto 2020-07-24 um 11 32 18" src="https://user-images.githubusercontent.com/1073273/88379004-6a4c4200-cda2-11ea-8e95-2f40d703aba4.png">

**Comment by ngdot** [comment]
Nice! Thanks for embedding this feature
