### ISSUE TITLE
Easyname.at Symlink only supported from terminal

### ISSUE THREAD

**Issue by fritz360** [contao/contao-manager#576]
My provider supports symlink only from terminal, so the manager does'nt work. 
Contao 4.x installation & symlink from terminal with composer works! (Do not forget to use the php command with version number (e.g. php73 ...). Can i bypass the symlink-test (e.g. with optional parameters on call of contao-manager.phar.php? or can i install the manager with terminal/composer.

**Comment by aschempp** [comment]
The symlink features are required by Contao, not (just) the Contao Manager. Contao creates symlinks for public files, e.g. if you add a new folder in the back end and set it to be public. You need to fix your hosting configuration to run Contao.

**Comment by aschempp** [comment]
@fritz360 (and/or @peasyname) would you mind contacting me by email to try to solve this issue? You can find my email in my GitHub profile.

**Comment by fritz360** [comment]
Hallo Andreas, we solved the problems with easyname. You can contact easyname support to activate their new server settings, then everything works fine. AND CHECK in their control-panel that the standard-php Version AND the web/subdomain setting is set to PHP 7.3
