### ISSUE TITLE
Contao-Manager does not complete most of the tasks

### ISSUE THREAD

**Issue by PotatoCarl** [contao/contao-manager#579]
Hi
I have very often the problem that a task of the Conto-Manager (package installation, updates etc.) is not completed in the web interface. It runs a while and then just the message "could not start task" is shown.
The console does not display any information.
Example:
(console)
```
$ /usr/bin/php -q /var/www/html/BRACE2/web/contao-manager.phar.php composer update cliffparnitzky/tiny-mce-plugin-loader contao/conflicts --with-dependencies --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader

Package "cliffparnitzky/tiny-mce-plugin-loader" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
```
I can however (if I am quick enough) copy the command line and insert it into a shell - where it is completed without any problem.

This happens in about 70-80% of the tasks to be performed.

Additionally, the displayed "close" button is not working, I have to reload the contao-manager to close that window.

My system:
Virtual Server
Ubuntu LTS 16.04.6

How can I make sure that the tasks are competed?

Greetings

**Comment by aschempp** [comment]
I looks like some server process manager is breaking the Contao Manager. How long does it take until the task stops running? Like the default ~30 seconds?

**Comment by PotatoCarl** [comment]
I did not take the time, but it is at last 30sec, maybe more. When I check on the server with ps -aef | grep php I see actually some manager processes still running.
Starting the (in the webinterface) shown command line on the command line and it typically works well.

**Comment by aschempp** [comment]
does this issue still exist or can we close it?

**Comment by PotatoCarl** [comment]
With the last update even full updates work nice and no problem anymore. You can close it, thanks.
