### ISSUE TITLE
"Errorlook" while updating

### ISSUE THREAD

**Issue by ngdot** [contao/contao-manager#580]
I almost get a heart attack every time I see this "error" while updating the manager to the newest version.
Maybe you should change it from error to information or success :D 

<img width="784" alt="Bildschirmfoto 2020-08-11 um 14 41 29" src="https://user-images.githubusercontent.com/8327905/89898341-d4f1e000-dbe0-11ea-9825-7dbf1e31d3d7.png">

**Comment by aschempp** [comment]
Thats interesting. Most likely happening because the manager already updated at that point and the request breaks. However, this will be fixed in 1.3 as I rebuilt the task handling.

**Comment by aschempp** [comment]
This has been improved/fixed in version 1.3
