### ISSUE TITLE
Composer intall Contao 4.9 under Win 10 + XAMPP "An error occurred while executing the "contao:install-web-dir" command"

### ISSUE THREAD

**Issue by syncgw** [contao/contao-manager#582]
I tried to install a new Contao instance in an empty directory with composer and got the following error message:

`Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 111.317 seconds
Analyzed 24234 packages to resolve dependencies
Analyzed 3835600 rules to resolve dependencies
Nothing to install or update
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
77 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
contao/manager-plugin: Generating plugin class...
 - Added plugin for bugbuster/contao-mobiledetection-bundle
 - Added plugin for con4gis/core
 - Added plugin for con4gis/forum
 - Added plugin for con4gis/groups
 - Added plugin for con4gis/projects
 - Added plugin for contao/core-bundle
 - Added plugin for contao/faq-bundle
 - Added plugin for contao/installation-bundle
 - Added plugin for contao/manager-bundle
 - Added plugin for isotope/isotope-core
 - Added plugin for syncgw/contao-isotope_stin
 - Added plugin for syncgw/contao-spambot
 - Added plugin for terminal42/contao-autoregistration
contao/manager-plugin: ...done generating plugin class
> post-update-cmd: Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception
  [RuntimeException]
  An error occurred while executing the "contao:install-web-dir" command:
Exception trace:
 () at xxx\contao\vendor\contao\manager-bundle\src\Composer\ScriptHandler.php:89
 Contao\ManagerBundle\Composer\ScriptHandler::executeCommand() at xxx\contao\vendor\contao\manager-bundle\src\Composer\ScriptHandler.php:30
 Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication() at phar://xxx/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:305
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar://xxx/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:209
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://xxx/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar://xxx/batch/composer.phar/src/Composer/Installer.php:338
 Composer\Installer->run() at phar://xxx/composer.phar/src/Composer/Command/UpdateCommand.php:163
 Composer\Command\UpdateCommand->execute() at phar://xxx/composer.phar/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar://xxx/composer.phar/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar://xxx/composer.phar/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar://xxx/composer.phar/src/Composer/Console/Application.php:281
 Composer\Console\Application->doRun() at phar://xxx/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://xxx/composer.phar/src/Composer/Console/Application.php:113
 Composer\Console\Application->run() at phar://xxx/composer.phar/bin/composer:61
 require() at xxx\composer.phar:24
update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
`
More @ [https://contao.slack.com/archives/CK4J0KNDB/p1597910235011900](url)

**Comment by aschempp** [comment]
This is not a Contao Manager issue, but rather a problem of Contao itself. It might be solved in the latest version though (https://github.com/contao/contao/pull/1964, https://github.com/contao/contao/pull/2184)
