### ISSUE TITLE
easyname hosting issues with symlinks via php

### ISSUE THREAD

**Issue by peasyname** [contao/contao-manager#583]
hello,

until recently we had actually disabled the php function symlink(). Now we have a new experimental setup where this function is no longer disabled. however, the issue with the web install tool / contao manager remains the same. you can check the php info via https://contao.easynametest.com/phpnf0.php

You can also try running the tool yourself under https://contao.easynametest.com/contao-manager.phar.php
user: easynamesupport
pass: fDq3LbNf9im2FRL

We would like to be able to offer an automatised setup for contao in the future, but will not be able to as long as this problem persists.

thank you for getting back to us.

regards
the easyname Support Team

**Comment by Toflar** [comment]
What's the problem? The Contao Manager reports that `symlink()` is missing on the CLI, not the web process. It has to be enabled in both SAPIs.

**Comment by peasyname** [comment]
Hello,

thank you for getting back to me so quickly.

We were able to fix this issue but ran into the next error:

[cid:image001.png@01D67BC4.74080F20]

It’s not like the tool asked me whether it should install in another folder, it’s complaining about itself 😃

Other than that I think we’re on the right way.

I’m looking forward to your reply.

Regards
Philipp Au
easyname Support

Von: Yanick Witschi <notifications@github.com>
Gesendet: Mittwoch, 26. August 2020 15:21
An: contao/contao-manager <contao-manager@noreply.github.com>
Cc: Philipp Au (EXT) <pa@easyname.at>; Author <author@noreply.github.com>
Betreff: Re: [contao/contao-manager] easyname hosting issues with symlinks via php (#583)


What's the problem? The Contao Manager reports that symlink() is missing on the CLI, not the web process. It has to be enabled in both SAPIs.

**Comment by fritzmg** [comment]
@peasyname you need to upload screenshots directly on GitHub, it does not work with email replies to comments ;)

Presumably you mean that the Contao Manager is complaining about a non empty directory?

**Comment by peasyname** [comment]
I see, here is the error message from the screenshot. The setup tool complains that it is in its own folder, but does not offer the possibility to use another folder instead:

ERROR 500 Unbekannter Installationsstatus
Auf Ihrem Server wurden Dateien gefunden, die keiner bekannten Contao-Version zugeordnet werden konnten.
Um Contao zu installieren, müssen Sie entweder Ihre Installation manuell reparieren oder folgende Dateien und Ordner entfernen:

 - contao-manager.phar.php

**Comment by fritzmg** [comment]
As explained in the documentation, you need to create an empty folder called `web/` within the desired installation directory of the new Contao installation. Both the target directory and the `web/` directory need to be empty. Then you put the `contao-manager.phar` into the newly created `web/` folder, rename it to `contao-manager.phar.php`, change the DocumentRoot of the domain to the newly created `web/` folder and then access `https://example.com/contao-manager.phar.php`. Is that the procedure you have done?

**Comment by peasyname** [comment]
the only contents of my folder are the contao-manager.phar.php and the additional contao-manager folder the setup tool created. Can I configure another folder by changing the script?

**Comment by fritzmg** [comment]
> the only contents of my folder

Which folder exactly?

> Can I configure another folder by changing the script?

No, the `contao-manager.phar.php` must be located in the `web/` sub-directory of the (future) Contao Installation.

**Comment by xchs** [comment]
@peasyname https://docs.contao.org/manual/de/installation/contao-manager/#hosting-konfiguration

**Comment by peasyname** [comment]
I have two test cases now, one with a folder /html/contao-manager/(contao-manager.phar.php) and the other with /html/contao-manager/web/(contao-manager.phar.php) and its the same error:

ERROR 500 Unbekannter Installationsstatus
Auf Ihrem Server wurden Dateien gefunden, die keiner bekannten Contao-Version zugeordnet werden konnten.
Um Contao zu installieren, müssen Sie entweder Ihre Installation manuell reparieren oder folgende Dateien und Ordner entfernen:

 - contao-manager.phar.php

**Comment by fritzmg** [comment]
> and the other with /html/contao-manager/web/(contao-manager.phar.php) and its the same error

Can you provide access to this test case?

The first test case is definitely wrong, as the contao-manager.phar.php needs to be within the `web/` sub-directory of the future Contao installation.

**Comment by peasyname** [comment]
user and pass are the same as in my previous post above

the one in the webfolder is reachable under https://contao-web.easynametest.com

the one in the contao-manager folder is still under https://contao.easynametest.com

if you need further access (ie. FTP) pleasy email me under pa@easyname.at

**Comment by xchs** [comment]
> and the other with /html/contao-manager/web/(contao-manager.phar.php) and its the same error

Did you set the DocumentRoot of https://contao-web.easynametest.com/ correctly to `/html/contao-manager/web/`? I would also choose an other name for the installation folder (i.e. instead of `contao-manager/`) since the Contao Manager also creates automatically a subdirectory with the same name (i.e. `/html/contao-manager/contao-manager/`) within your Contao installation. But well, of course it should still work. 😃

**Comment by aschempp** [comment]
I assume this has been solved, and it does not look like a bug but rather a question.

**Comment by fritzmg** [comment]
@aschempp the bug could be, that the installation does not work, if the target directory happens to be named `contao-manager`. But I haven't heard back from easyname about this yet, and I haven't confirmed this myself yet. I'll post here again if I do.

**Comment by aschempp** [comment]
That wouldn't really make sense to me. The Contao Manager only checks if the current directory is names `web`, and decides  to place the `contao-manager` in the parent or the current folder based on that. But yeah, lets wait for feedback and reopen if necessary.
