### ISSUE TITLE
Problem mit dem PHP-Pfad bei TimmeHosting

### ISSUE THREAD

**Issue by Babelfisch** [contao/contao-manager#586]
Ich nutze die TimmeCloud 2.0 und versuche gerade Contao über den Contao Manager 1.2.7 zu installieren. Bei der Auswahl von TimmeHosting in der Serverkonfiguration wird mir folgendes angezeigt:

`Konfiguriert als Timme Hosting GmbH & Co. KG, PHP-Binary in /opt/php-7.4/bin/php`

Der Pfad zu PHP ist also korrekt `/opt/php-7.4/bin/php`. Im letzten Schritt der Systemüberprüfung bekomme ich jedoch dann diesen Fehler:

> Contao-Installation
> Prüfung aufgrund fehlender Abhängigkeiten abgebrochen.
>
> Installationsprobleme erkannt
> Sie müssen die Installationsprobleme beheben, bevor der Contao Manager verwendet werden kann.

Die Fehlermeldung ist `error.log` deutet nun darauf, dass hier auf einmal PHP in `/opt/php-7.4.9/bin/php` gesucht wird. Den Pfad gibt es aber nicht.

Hier die komplette Fehlermeldung:

`[07-Sep-2020 16:54:57 Europe/Berlin] [2020-09-07 16:54:57] app.ERROR: The command "'/opt/php-7.4.9/bin/php' '-q' '/var/www/clients/client1/web30/web/web/contao-manager.phar.php' 'test'" failed.  Exit Code: 127(Command not found)  Working directory: /var/www/clients/client1/web30/web  Output: ================   Error Output: ================ sh: /opt/php-7.4.9/bin/php: No such file or directory  {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"'/opt/php-7.4.9/bin/php' '-q' '/var/www/clients/client1/web30/web/web/contao-manager.phar.php' 'test'\" failed.\n\nExit Code: 127(Command not found)\n\nWorking directory: /var/www/clients/client1/web30/web\n\nOutput:\n================\n\n\nError Output:\n================\nsh: /opt/php-7.4.9/bin/php: No such file or directory\n at phar:///var/www/clients/client1/web30/web/web/contao-manager.phar.php/vendor/symfony/process/Process.php:256)"} []`

Ich bin jetzt etwas ratlos, was ich da machen kann.

**Comment by oliverjkb** [comment]
Hallo @Babelfisch , 
für die Pfade unserer rolling release PHP-Versionen wurde für Version 1.2.5 bereits ein update von mir gemerged.  
https://github.com/contao/contao-manager/pull/539/commits/91d1f657a223ccefeb6b07598ec125af5ed007da  

Schreib mir doch gerne ein kurzes Ticket an unsere Support Adresse, dann schauen wir uns das gerne einmal an. :)

**Comment by aschempp** [comment]
In Version 1.3 wurde die Hosting-Auswahl entfernt und sollte nun überall automatisch funktionieren. 
https://contao.org/de/news/contao-manager-1-3-0-verfuegbar.html
