### ISSUE TITLE
1.3.0] Full console does not work

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/contao-manager#588]
When I go to the option "Show full console" a new tab with "about:blank" opens.

**Comment by Tastaturberuf** [comment]
Ah i see later there is some content. But the tab "unnamed" and url "about:blank" can be optimized.

**Comment by Tastaturberuf** [comment]
Nice feature BTW.

**Comment by aschempp** [comment]
> But the tab "unnamed" and url "about:blank" can be optimized.

No that can't be optimized. That's how browsers and javascript works 😉
