### ISSUE TITLE
logfile-handling (/web/contao-manager/logs)

### ISSUE THREAD

**Issue by jochi44** [contao/contao-manager#589]
Das file "error.log" im Verzeichnis /web/contao-manager/logs hat bei einigen unserer Installationen eine "ungute" Größe angenommen (> 100MB).
Wäre toll, wenn der Contao-Manager automatisiert ein "handling" (Archivierung/Löschung) der logfiles durchführen würde.

**Comment by aschempp** [comment]
Fixed in 891c0073ba662cbdd5dc12e08c591b2c24d8d509
