### ISSUE TITLE
php executeable nicht anpassbar

### ISSUE THREAD

**Issue by Olli** [contao/contao-manager#59]
Beim Hosting bei all Inkl kann ich auf PHP Executeables verschiedener Versionen zugreifen. Es muss die Möglichkeit geben, bei den Tenside Geschichten eine andere PHP Executeable Version mit zu geben (oder ggf auch CLI Parameter wenn z.B. zu wenig Speicher in der default php.ini eingestellt ist).
Kann das beim Phing build Prozess mit übergeben werden?

**Comment by discordier** [comment]
Das kann man doch in der config eintragen?

**Comment by aschempp** [comment]
Das ist eine Advanced Config währed der Installation

**Comment by Olli** [comment]
In der build.xml?

**Comment by Olli** [comment]
@aschempp welche advanced config während welcher installation?

**Comment by aschempp** [comment]
In der finalen Version des Managers wird diese Funktion enthalten sein. Zum aktuellen Entwicklungsstand kann ich keine Hilfe geben, falls du damit rumspielen willst nur zu, aber bitte erwarte nicht dass ich Zeit habe Fragen zu einer Entwicklungsversion zu beantworten…
