### ISSUE TITLE
CM startet nach Update nicht mehr

### ISSUE THREAD

**Issue by m-werk** [contao/contao-manager#590]
Hallo, gestern wurde bei einer Seite der CM auf die Version 1.3.0 upgedatet. Dannach bin ich auf "Pakete aktualisieren" gegangen. Dann hab ich das System laufen lassen und meinen Rechner ausgeschalten. 

Heute wollte ich wieder in den CM einsteigen und dann machte er gleich eine Systemprüfung, die dann ca. eine Minute gedauert hat. Dannach kam folgende Meldung: 
![Meldung_1](https://user-images.githubusercontent.com/1488276/94237668-7e7dfe00-ff0f-11ea-9d82-241c54ec6181.jpg)

Wenn ich hier dann auf "Schließen" klicke, kommt nach ca. einer weiteren Minute folgende Meldung:
![Meldung_2](https://user-images.githubusercontent.com/1488276/94237744-981f4580-ff0f-11ea-821e-2f29b987315a.jpg)

Das war's. Ich komm hier nicht mehr in den CM.

LG, Andi

**Comment by Kahmoon** [comment]
Ist bei zwei Installationen von mir auch so. Beide im gleichen Hostingpaket "Unlimited" bei Ionos.

**Comment by m-werk** [comment]
Bei mir ist es jetzt mal bei einer aufgetreten bei World4You

**Comment by BennyK80** [comment]
Aktuell gleiches Problem bei DomainFactory. 

Erneut gestartet. Danach composer update (mittels Resolver Cloud) Aktiv seit 2104 Sekunden.
Es geht nicht voran.

**Comment by Kahmoon** [comment]
Gerade eben im Forum gesehen.

Abhilfe: Die Datei /contao-manager/task.json per FTP löschen. Neu probieren.

Funktioniert bei mir

**Comment by m-werk** [comment]
Ja, dass wollte ich auch gerade schreiben. Diese Datei löschen und neu starten. Jetzt funktioniert es auch bei mir wieder

**Comment by UlrichHolland** [comment]
Nach Löschen von task.json läuft composer-update (mittels Resolver Cloud) jedoch nicht durch, terminiert nach 1 Stunde:

4.4.51 (sollte update auf 4.4.52) laufen...

**Comment by johannes-bittner** [comment]
Kann ich bestätigen für Hosting bei cyon.ch, eigentlich alle dort gehosteten Installationen ...

**Comment by kikmedia** [comment]
Confirmed. task.json löschen löst das Problem nicht unbedingt. Hosteurope Virtual Server Managed, PHP 7.3

**Comment by BugBuster1701** [comment]
Gleiches bei Uberspace mit PHP 7.3. 
Leider ist die Konsolenausgabe leer, jedenfalls kommt bei mir nichts über die drei Punkte und auch nichts über Zwischenablage.

**Comment by swinde** [comment]
Ist auch bei Hostingwerk so. Bei DF habe ich es gestern mal geschafft eine Contaoinstallation zu updaten.

**Comment by m-werk** [comment]
So, nun hab ich mal alles von CM gelöscht (ausgenommen config.json und user.json)
Dann hab ich mal den CM gestartet und dann wollte ich Contao updaten. Für ca. 20 Sek. lief folgendes durch:
![meldung_3](https://user-images.githubusercontent.com/1488276/94247275-2ea63380-ff1d-11ea-85cb-9ce3edd65a06.jpg)

Dann kam gleich folgende Meldung:
![meldung_4](https://user-images.githubusercontent.com/1488276/94247316-3a91f580-ff1d-11ea-8cac-9510775a9eeb.jpg).

Ich hab auch eine Installation bei Easyname. Dort lief alles durch ohne Probleme mit der neuen Version von CM

**Comment by tblumrich** [comment]
Kann/Muss das auch bestätigen. Updateversuch auf 4.9.7 bei netcup, PHP7.4. Die Neuinstalation war gestern schon extrem holprig und ging nur mit mehreren Anläufen, dazwischen die Fehler, die oben auch schon gepostet wurden. Jetzt beim Updateversuch das von meinem Vorposter.
...und das wo Contao in der 4.9.6 defacto nicht nutzbar ist.

**Comment by aschempp** [comment]
Das Problem ist, dass die Composer Resolver Cloud aktuell überlastet ist. Dadurch werden Tasks nicht korrekt abgearbeitet, was zu Endloslaufzeiten und anderem führt. Wir arbeiten am Problem, können aber noch nichts genaues sagen. Alternativ könnt ihr versuchen, die Cloud-Funktion zu deaktivieren, wenn euer Hoster die Voraussetzungen erfüllt.

**Comment by Kahmoon** [comment]
Danke für die Info. Ohne Cloud braucht man bei 1und1/Ionos sowas gar nicht versuchen :-D

**Comment by jxns** [comment]
Wie ließe sich die Cloud denn umgehen?

**Comment by tblumrich** [comment]
Unter Einstellungen - Systemprüfung - Serverkonfiguration - Ändern - Cloud Resolver Häkchen raus

**Comment by UlrichHolland** [comment]
> Unter Einstellungen - Systemprüfung - Serverkonfiguration - Ändern - Cloud Resolver Häkchen raus. Machen aber die wenigsten Shared Hoster mit - ich kenn keinen.
> 
> Update: Erstaunlicherweise funktionierte das eben bei Netcup ohne Cloud.

Hosting oder Server?

**Comment by tblumrich** [comment]
Webhosting 4000

**Comment by m-werk** [comment]
So, hab jetzt mal die task.json gelöscht, damit ich mal wieder ins CM komme. Hab jetzt zu Testzwecken den Punkt Installer ausführen bei Composer-Abhängigkeiten ausgeführt.
Dieser lief problemlos jetzt durch. 
Jetzt hab ich auf Datei aktualisieren geklickt bei Composer Class Loader. Das hat auch auch alles funktioniert. Auch der Anwendungs-Cache und der Composer-Cache wurden erfolgreich ausgeführt.

Nur wenn ich jetzt Contao von 4.10.0 auf 4.10.2 updaten möchte, funktioniert's nicht. Hängt sich gleich bei "composer update (mittels Resolver Cloud) auf.

**Comment by UlrichHolland** [comment]
> Webhosting 4000

... kann ich Webhosting 2000 (netcup) auch bestätigen!

**Comment by Misios** [comment]
Strato Server: Nix geht. Seit Stunden. Ab und zu rutsch mal eine Aktualisierung durch ... aber meistens wartet man ewig und es bricht dann ab.

**Comment by BugBuster1701** [comment]
Also jetzt (22:50 Uhr) konnte ich erfolgreich ein Update von 4.9.5. auf 4.9.7 durchführen.

**Comment by klimeckt** [comment]
Bei mir hat es jetzt auch erfolgreich funktioniert. Selbst bei Strato. ;-) Bei IONOS und All-Incl auch. Alles zwischen 22:50 und 23:00, 4.9.5. bzw. 4.9.6. auf 4.9.7.

**Comment by planepix** [comment]
Ergänzend bei einem Updateversuch angezeigte Fehlermeldung:
```Return value of Contao\ManagerApi\TaskOperation\Composer\CloudOperation::getOutput() must be of the type string, null returned```

**Comment by BennyK80** [comment]
Zur Info:

28.09.2020 | 11:33 Uhr 
Ein Hintergrund-Prozess wurde unerwartet beendet. Bitte prüfe die Konsolen-Ausgabe.
composer update (mittels Resolver Cloud)
HTTP request to https://composer-resolver.cloud/jobs failed with status code 500 ()

28.09.2020 | 11:37 Uhr 
Ein Hintergrund-Prozess wurde unerwartet beendet. Bitte prüfe die Konsolen-Ausgabe.
composer update (mittels Resolver Cloud)
HTTP request to https://composer-resolver.cloud/jobs failed with status code 503 ()

**Comment by Smurffson** [comment]
Das Ticket wurde zwar geschlossen, aber ich habe das gleiche Problem beim Webhoster "Webhosting AG" bei einer Contao 4.4 Installation. Seit dem Update auf 1.3.2 hängt sich der Contao Manager sofort beim Erkennen des Servers auf. 
Dann kommt ein Overlay mit der Meldung:

> Error 500 - HTTP-Anfrage für "GET api/task" fehlgeschlagen"

Unter dem Overlay kann man die Meldung finden:
> Der Contao Manager konnte den Hintergrund-Prozess nicht starten.

Im Apache Log sehe ich:
`401 - POST /contao-manager.phar.php/api/session HTTP/1.0`

Der PHP-Pfad in der manager.json sieht ok aus ("php_cli": "\/opt\/plesk\/php\/7.2\/bin\/php").

Das Löschen der task.json hat nichts gebracht, das Löschen der Caches auch nicht, das Ersetzen der PHAR durch eine neu herunter geladene auch nicht.

**Comment by aschempp** [comment]
> Seit dem Update auf 1.3.2 hängt sich der Contao Manager beim Erkennen des Servers auf.

Woher weisst du dass sich der Manager hier aufhängt? Konntest du das irgendwie debuggen?

**Comment by Smurffson** [comment]
Nicht direkt. Ich habe leider relativ eingeschränkte Möglichkeiten auf dem Server, z.B. kein SSH-Zugriff. 
Die letzte Meldung die ich vom CM sehen konnte war 
> Systemprüfung - Bitte warten, dein Server wird überprüft …

Dann kamen die oben beschriebenen Meldungen.

Inzwischen gab es eine wunderbare Spontanheilung. Ohne weitere Eingriffe meinerseits läuft der CM jetzt wie gewohnt durch.
