### ISSUE TITLE
Resolveserver throws 503

### ISSUE THREAD

**Issue by evo-web** [contao/contao-manager#591]
Tried to do security Updates 4.4... to 4.4.53 today.
5 out of 6 Updates throws 503 (Service unavailable).

**Comment by evo-web** [comment]
HTTP request to https://composer-resolver.cloud/jobs/zHV5iENPjJghp35fNM7nWtJKwUFeIK2Mgh9OEOPduEQwv1ydgXnfDccWE3yYwCeJkgtSc03MlUYXKXCCw5Ikwj4WRJ5xf71bB2ed0Fav failed with status code 503 ()

**Comment by Patric96** [comment]
Same issue, can't update since 24.09.2020...

**Comment by BennyK80** [comment]
28.09.2020 | 11:33 Uhr
Ein Hintergrund-Prozess wurde unerwartet beendet. Bitte prüfe die Konsolen-Ausgabe.
composer update (mittels Resolver Cloud)
HTTP request to https://composer-resolver.cloud/jobs failed with status code 500 ()

28.09.2020 | 11:37 Uhr
Ein Hintergrund-Prozess wurde unerwartet beendet. Bitte prüfe die Konsolen-Ausgabe.
composer update (mittels Resolver Cloud)
HTTP request to https://composer-resolver.cloud/jobs failed with status code 503 ()

**Comment by ericeggert** [comment]
Das Selbe Problem hier. Composer gibt bei allen Jobs auf verschiedenen Installationen ne 503:
HTTP request to https://composer-resolver.cloud/jobs failed with status code 503 ()
Problem tritt seit dem Update auf den Contao Manager 1.3.0 auf

**Comment by Toflar** [comment]
The Composer Resolver Cloud is being hit with more than 100 requests per second (!). It's simply not able to handle the incredible demand. We'll see on how we can improve the situation in the future but there's nothing we can do right now. All you can do is come back later.

PS: Also remember that you don't pay for this service. We're trying our best here. You can always disable using the cloud in the Manager settings if your server is powerful enough.

**Comment by Samson1964** [comment]
Den Ansturm auf den Cloud Resolver scheint es doch sicher erst seit Contao Manager 1.3 zu geben. Es staut sich halt alles auf, weil der CM schon nicht mehr richtig funktioniert. Dadurch hängt man den halben Tag mit Updates fest, wo man früher nach 5-10 Minuten wieder weg war. Statt nur einer Anfrage produziere ich so 30-40, weil 29-39 nicht funktionieren.

Es wäre schön, wenn es ohne Cloud Resolver funktioniert. Bei den ManagedServern von Hetzner und Domainfactory, wo wir jeweils den höchsten Tarif haben, funktioniert es allerdings nicht ohne Cloud. Und das obwohl genug RAM zur Verfügung steht. Der allerdings nicht an den (einzigen) Kunden weitergereicht wird. Die Hoster wollen ihre Webserver halt nicht mit Anwendungen belasten, die Gigabytes an Arbeitsspeicher verschleudern.

**Comment by fritzmg** [comment]
> Den Ansturm auf den Cloud Resolver scheint es doch sicher erst seit Contao Manager 1.3 zu geben.

The workload is likely due to the recent updates released for Contao 4.4, 4.9 and 4.10 and not related to version 1.3 of the Contao Manager.

> Es wäre schön, wenn es ohne Cloud Resolver funktioniert. Bei den ManagedServern von Hetzner und Domainfactory, wo wir jeweils den höchsten Tarif haben, funktioniert es allerdings nicht ohne Cloud. Und das obwohl genug RAM zur Verfügung steht. Der allerdings nicht an den (einzigen) Kunden weitergereicht wird. Die Hoster wollen ihre Webserver halt nicht mit Anwendungen belasten, die Gigabytes an Arbeitsspeicher verschleudern.

You can resolve locally and then just install the dependencies remotely.

**Comment by marcuslelle** [comment]
> Den Ansturm auf den Cloud Resolver scheint es doch sicher erst seit Contao Manager 1.3 zu geben. Es staut sich halt alles auf, weil der CM schon nicht mehr richtig funktioniert. Dadurch hängt man den halben Tag mit Updates fest, wo man früher nach 5-10 Minuten wieder weg war. Statt nur einer Anfrage produziere ich so 30-40, weil 29-39 nicht funktionieren.
> 
> Es wäre schön, wenn es ohne Cloud Resolver funktioniert. Bei den ManagedServern von Hetzner und Domainfactory, wo wir jeweils den höchsten Tarif haben, funktioniert es allerdings nicht ohne Cloud. Und das obwohl genug RAM zur Verfügung steht. Der allerdings nicht an den (einzigen) Kunden weitergereicht wird. Die Hoster wollen ihre Webserver halt nicht mit Anwendungen belasten, die Gigabytes an Arbeitsspeicher verschleudern.

Hi Samson,

ich kann mir so gar nicht vorstellen, dass ein dedizierter Managed Server das nicht kann. Wollen wir das am Donnerstag mal beim Stammtisch besprechen?

Gruß malle

**Comment by marcuslelle** [comment]
What I see after updating to Contao Manager 1.3 is a longer time while starting the Manager itself. A few seconds I guess. Just fyi, nothing that bothers me.

**Comment by Samson1964** [comment]
> 
> 
> > Den Ansturm auf den Cloud Resolver scheint es doch sicher erst seit Contao Manager 1.3 zu geben. Es staut sich halt alles auf, weil der CM schon nicht mehr richtig funktioniert. Dadurch hängt man den halben Tag mit Updates fest, wo man früher nach 5-10 Minuten wieder weg war. Statt nur einer Anfrage produziere ich so 30-40, weil 29-39 nicht funktionieren.
> > Es wäre schön, wenn es ohne Cloud Resolver funktioniert. Bei den ManagedServern von Hetzner und Domainfactory, wo wir jeweils den höchsten Tarif haben, funktioniert es allerdings nicht ohne Cloud. Und das obwohl genug RAM zur Verfügung steht. Der allerdings nicht an den (einzigen) Kunden weitergereicht wird. Die Hoster wollen ihre Webserver halt nicht mit Anwendungen belasten, die Gigabytes an Arbeitsspeicher verschleudern.
> 
> Hi Samson,
> 
> ich kann mir so gar nicht vorstellen, dass ein dedizierter Managed Server das nicht kann. Wollen wir das am Donnerstag mal beim Stammtisch besprechen?
> 
> Gruß malle

Gern :-)

**Comment by bear30** [comment]
Hallo, ich habe hier auch einen bei df der hängt. Der ist leider am Donenerstag Abend auf die 4.9.6 geupdatet worden mit den bekannten Folgen. Seitdem geht dort nichts mehr weiter. Alle weiteren Updates scheitern an den schon bekannten Fehlermeldungen. Das ist eine Produktivseite eines Kunden was irgendwann Ärger geben wird. Wann wird der Cloud Resolver wieder laufen?

**Comment by contaoacademy** [comment]
**Möglichkeiten zur Lösung**
1. Das Update außerhalb der normalen Arbeitszeiten versuchen (z.B. nach 20.00 Uhr)
2. Paketauflösung (composer.json und composer.lock) lokal vorbereiten und auf dem Server nur "composer install" laufen lassen

**Comment by klimeckt** [comment]
Hallo @bear30,

Hast du es mal nachts probiert?

Ich konnte heute nacht, rund Mitternacht, zwei Updates komplett durchlaufen lassen. (IONOS mit php7.4.10) Die Updates liefen schnell durch. Die Zwischenschritte des CM waren etwas verzögert. Damit meine ich das Laden abschliessenden Infos etc.

**Comment by bear30** [comment]
Die Tricks kenne ich auch. Aber das ist ja wohl ein schlechter Witz ...

**Comment by contaoacademy** [comment]
> Die Tricks kenne ich auch. Aber das ist ja wohl ein schlechter Witz ...

Eine dauerhafte Lösung ist das sicher nicht. Aber die Jungs arbeiten an einer Lösung. Wie schnell das geht, kann dir im Moment niemand sagen.

**Comment by Toflar** [comment]
Mein Timer zeigt im Moment 8h 45min seit Freitag. Ein schlechter Witz ist, dass ich dafür nicht bezahlt werde und es neben meiner Arbeit irgendwie unterkriegen muss. Ich locke dieses Issue jetzt, es ist besser für meinen Puls.
Für alle die konstruktiv beitragen möchten: https://github.com/sponsors/terminal42
