### ISSUE TITLE
Contao 3.5 Problem mit der vereinfachten Installation im web-Ordner 

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao-manager#592]
Wenn der Root-Ordner einer Contao 3.5 «web» heisst, geht der Manger fälschlicherweise davon aus sich in einer 4-Installation zu befinden und versucht dementsprechend den Contao-Manager-Ordner eine Ebene zu hoch anzulegen.

**Comment by aschempp** [comment]
Fixed in 418e1e50ca317ce6d3735e91d70f50b3e2582e7d
