### ISSUE TITLE
CM will ein neues Verzeichnis "web" obwohl er schon von dort aufgerufen wird

### ISSUE THREAD

**Issue by kubjo** [contao/contao-manager#594]
Ich wollte eben eine Testinstallation machen, dazu habe ich ein Verzeichnis (contao4xx) erstellt, darin ein Verzeichnis (web) und da habe ich den CM rein kopiert, umbenannt und aufgerufen. Jetzt will der CM in /web nochmal ein /web erstellen, weil... ja warum eigentlich? Im Verzeichnis contao4xx ist außer /web nichts drin.

**Comment by aschempp** [comment]
vermutlich ist im Parent-Verzeichnis bereits was drin?

**Comment by NoahNonsens** [comment]
Selbes Problem hier seit Contao Manager 1.3.2. Parent-Verzeichnis leer. Gleiches Vorgehen wie immer: Parentverzeichnis anlegen, web Verzeichnis angelegt und Domain auf web Ordner zeigen lassen.CM reinkopieren und umbenennen. Aufrufen und dann will der CM ein neues Verzeichnis web im Verzeichnis web anlegen.  Ab da geht im CM nix mehr. Wenn ich den zweiten web Ordner händisch anlege und da den CM reinlege läuft die Installation.

**Comment by fritzmg** [comment]
Ist das Parent Verzeichnis tatsächlich leer? Prüfe das mal mit `ls -la` via SSH.

**Comment by NoahNonsens** [comment]
> Ist das Parent Verzeichnis tatsächlich leer? Prüfe das mal mit `ls -la` via SSH.

Ja ist leer.

**Comment by hh-com** [comment]
Dito.. Neu erstellte Verzeichnisse root und root/web sind normallerweise leer. Auch geprüft mit SSH.

**Comment by kubjo** [comment]
Habe es bei mir auch mehrfach geprüft!

**Comment by aschempp** [comment]
Ich habe soeben die Version 1.3.3 veröffentlicht, bitte prüft ob sich damit etwas verändert.

**Comment by NoahNonsens** [comment]
Hier funktioniert es jetzt. Nach anfänglicher Fehlermeldung startet der CM neu und läuft dann wie gewohnt. Danke!

**Comment by kubjo** [comment]
Bei mir startet der CM garnicht mehr, er wirft folgende Fehlermeldung:
"The Contao Manager could not create the directory "/var/.../.../contao-4xx/contao-manager".

**Comment by kubjo** [comment]
Bei DomainFactory lief alles einwandfrei durch. Bei Netcup s.o.

**Comment by fritzmg** [comment]
> Bei mir startet der CM garnicht mehr, er wirft folgende Fehlermeldung:
> "The Contao Manager could not create the directory "/var/.../.../contao-4xx/contao-manager".

Does the folder contao-4xx have the correct access rights?

**Comment by NoahNonsens** [comment]
Bei mir ebenfalls netcup. Musste auch erst das bestehende Verzeichnis löschen und neu anlegen lassen, damit es funktioniert. Da netcup die Verzeichnissstruktur selbst anlegt, liegt vielleicht da ein Problem?

**Comment by fritzmg** [comment]
> Da netcup die Verzeichnissstruktur selbst anlegt

Why or how does netcup do that?

> liegt vielleicht da ein Problem?

If netcup creates the directories with the wrong access rights, then yes.

**Comment by NoahNonsens** [comment]
Aber lief ja vor dem CM Update auch Problemlos 🤷🏼‍♂️

**Comment by kubjo** [comment]
Auch ein Update von 1.3.2 auf 1.3.3 läuft bei netcup nicht durch. Der CM meldet:
--
The Contao Manager could not create the directory "/var/www/.../contao4/contao-manager".
It looks like your server is not configured correctly. If you are about to install Contao, please setup the DocumentRoot of your web server. Otherwise make sure the file access permissions are correct. If you are unsure how to fix this, contact your hosting provider for support.
--
Obwohl das Verzeichnis da ist. Löschen bringt nichts, gleiche Meldung

**Comment by kubjo** [comment]
> 
> 
> Bei mir ebenfalls netcup. Musste auch erst das bestehende Verzeichnis löschen und neu anlegen lassen, damit es funktioniert. Da netcup die Verzeichnissstruktur selbst anlegt, liegt vielleicht da ein Problem?

Was meinst Du damit, dass netcup die Verzeichnisstruktur selbst anlegt?

**Comment by aschempp** [comment]
Diese Fehlermeldungen bedeuten, dass der Manager bei `is_writable` einen Fehler bekommt. Entweder hat er keinen Zugriff auf diesen Ordner oder den Parent-Ordner und kann damit keine entsprechenden Dateien schreiben. Daher müsstest ihr die Zugriffsrechte korrigieren.

**Comment by kubjo** [comment]
Ich habe mit Hilfe des [Forums ](https://community.contao.org/de/showthread.php?79102-CM-bei-netcup-funktioniert-nicht&p=533058#post533058) den Fehler gefunden. In den php Einstellungen war ein falsches  "open_basedir" eingestellt. 
Sorry vielmals für den falschen Alarm hier! Die Test-Installation lief jetzt einwandfrei durch. 

Grüße
Jochen

**Comment by fritzmg** [comment]
@aschempp may be the Contao Manager could check for an `open_basedir` configuration such as this? There are a few hosters out there that set the `open_basedir` to the document root by default. And I think Plesk does that by default too.

**Comment by aschempp** [comment]
See https://github.com/contao/contao-manager/issues/599
