### ISSUE TITLE
Error after update to 1.3.1

### ISSUE THREAD

**Issue by planepix** [contao/contao-manager#596]
First: Thank you for every second you improve the environment aka manager.

After updating to 1.3.1 and run update all packages it runs into an error:
```Argument 1 passed to Contao\ManagerApi\Composer\CloudJob::__construct() must be of the type array, null given, called in phar:///www/htdocs/doamin.tld/web/contao-manager.phar.php/api/TaskOperation/Composer/CloudOperation.php on line 321```

**Comment by fritzmg** [comment]
Duplicate of #595

**Comment by planepix** [comment]
too slow :-)
