### ISSUE TITLE
CM Update läuft Ewigkeiten, ohne Fehler oder Erfolg

### ISSUE THREAD

**Issue by WebDucer** [contao/contao-manager#597]
Hallo.

Die Aktualisierung von Contao über CM scheitert wiederholbar, seit der neuen Version. Bei einer zweiter Homepage, mit denselben Erweiterungen und beim selben Hoster (IONOS) funktioniert einwandfrei. Ich bin mit meinem Latein am Ende, da das Fenster einfach weiter stehen bleibt, ohne dass eine Fehlermeldung angezeigt wird. Auch das Warten über 10 Minuten und mehrmalige Aktualisierung der Seite haben keine Besserung gebracht.

## composer.json

```json
{
    "type": "project",
    "require": {
        "contao/calendar-bundle": "^4.9",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "^4.9",
        "contao/listing-bundle": "^4.9",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "^4.9",
        "madeyourday/contao-rocksolid-columns": "^2.0",
        "madeyourday/contao-rocksolid-custom-elements": "^2.2",
        "madeyourday/contao-rocksolid-frontend-helper": "^2.0",
        "madeyourday/contao-rocksolid-icon-picker": "^2.0",
        "madeyourday/contao-rocksolid-mega-menu": "^2.0",
        "madeyourday/contao-rocksolid-slider": "^2.0",
        "madeyourday/contao-rocksolid-theme-assistant": "^2.0",
        "monolog/monolog": "^1.22",
        "numero2/contao-marketing-suite": "^1.0"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

## task-output.log

```
> Resolving dependencies using Composer Cloud v2.4.10
!!! Current server is sponsored by: Contao Association !!!
```

![Screenshot 2020-09-30 at 09 16 46](https://user-images.githubusercontent.com/761881/94654911-160f9200-02fe-11eb-98ff-5c0307369460.png)

Woran kann es liegen?

Als Workaround konnte ich den Update dadurch ausführen, dass ich loakal auf meinem Rechner die `composer.lock`-Datei erzeugte (aus der original `composer.json`) und auf den Server aufspielte. Aber auch danach ist das Verhalten des CM dasselbe. Es läuft ohne Fehlermeldung oder Erfolgsmeldung. Nach 15.000 Sekunden brach ich alle Versuche bis jetzt ab.

**Comment by frontendschlampe** [comment]
Ich habe das selbe Problem. Jegliches Löschen/Zurücksetzen von Cache, task.json usw. brachte keine Besserung. Habe es heute Nacht probiert, als auf der Cloud nichts los war. Bei drei anderen Installationen hatte ich das Problem aber nicht. Ohne Cloud lief es dann ohne Probleme. Ich habe es soeben nochmals mit der Cloud probiert, aber der Manager bleibt wie oben beschrieben, immer hängen.

**Comment by contaoacademy** [comment]
Gleiches Problem bei mir. Es läuft endlos.

**Comment by lebleucleu** [comment]
Gleiches Problem auch bei mir.  Der Contao-Manager 1.3.2 meldet:
x composer update (mittels Resolver Cloud) Aktiv seit 3583 Sekunden.
  > The Composer Resolver Cloud failed with status code 404
  Composer Resolver returned an unexpected status code
  Response:
  {"msg":"Job not found."}
x composer install

**Comment by WebDucer** [comment]
Auch mit 1.3.3 bleibt das Problem bestehen.

**Comment by Seefahrer** [comment]
Geht mir auch so ...

**Comment by derkosmonaut** [comment]
Das gleiche Problem bei mehreren Installationen. Zusätzlich werden die Pakete unter "Entdecken" nicht mehr angezeigt: "Konnte keine Ergebnisse laden. Prüfe deine Internet-Verbindung und deaktiviere alle JavaScript-Blocker." – Internetverbindung funktioniert – keine Blocker aktiv.

**Comment by contaoacademy** [comment]
Das Problem tritt bei mir nur noch vereinzelt auf. Am besten mehrmals versuchen.

**Comment by Cleanerrr** [comment]
Gleiches Problem auch bei mir...
Ich habe mehrmals versucht, aber wieder geht nicht

**Comment by aschempp** [comment]
könnt ihr versuchen die Paketauflösung ohne Resolver Cloud zu machen (Checkbox im Systemcheck entfernen)=

**Comment by webmurkser** [comment]
Habe auf einem all-inkl. "Premium" Webspace das gleiche Problem. Erst mit dem Update von 4.4.53 auf 4.4.54 (habe bei 7000 Sekunden abgebrochen). 

10 Minuten später war das Update innerhalb weniger Sekunden aber möglich. 

Anschließend wollte ich auf 4.9.x Updaten. Wieder mehrere Hundert Sekunden gewartet. Parallel dies hier gelesen, den Job abgebrochen und ohne der Resolver Cloud nochmals versucht. Mit Erfolg. (Alles mit CM1.3.3)

**Comment by WebDucer** [comment]
> könnt ihr versuchen die Paketauflösung ohne Resolver Cloud zu machen (Checkbox im Systemcheck entfernen)?

@aschempp Bei mir leider nicht möglich. Bei der kleinen Seite bin ich auf einen kleinen Shared-Host mit wenig Speicher. Bei der Seite mit genug Speicher funktioniert das Update bis jetzt ohne Probleme (auch mit dem Cloud-Resolver).

**Comment by aschempp** [comment]
see https://github.com/contao/contao-manager/issues/600

**Comment by contaoacademy** [comment]
My Jobs running without any issues now.
