### ISSUE TITLE
Feature: files und templates ignorieren bei der Installation

### ISSUE THREAD

**Issue by JensB74** [contao/contao-manager#598]
Seit Contao Manager 1.3.3 wird ja jetzt erkannt, wenn schon Dateien im Ordner liegen und es wird ein alternativer Pfad vorgeschlagen für die Installation.

Ich habe mich gerade dabei erwischt, dass ich "schon mal"™ die Ordner files und templates neben(! nicht IN) den Ordner web kopiert habe (von wo aus ich den Manager gestartet habe), leider gelten diese wohl auch als neue "Dateien" oder als etwas, was da nicht hingehört, und es wurde mir ein neuer Pfad vorgeschlagen für die Installation.
Vielleicht könnte man diese beiden Ordner bei der Installation ignorieren, da man sie im späteren Verlauf ja eh dort hin kopiert ..?!

Ansonsten gefällt mir der Manager mit jedem Versionssprung besser und besser, man sieht jedes mal Fortschritte! Klasse!

**Comment by fritzmg** [comment]
> Vielleicht könnte man diese beiden Ordner bei der Installation ignorieren, da man sie im späteren Verlauf ja eh dort hin kopiert ..?!

Well there are many more files that you might or might not copy into the Contao installation later, so I do not think it would make sense to include any exceptions like that.
