### ISSUE TITLE
[Feature] - Show latest available version of installed packages in overview

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao-manager#602]
As discussed in the Contao Show, it would be helpful, if the latest available versions of the installed packages and extensions would be shown in the overview and not only in the package detail view.

A problem is, that the latest version maybe couldn't be installed because the actual configuration doesn't allow this.

Example:
1) Contao 4.4 and PHP 7.1
2) Contao 4.9 and PHP 7.4

If a package needs Contao 4.9 or PHP 7.2 as minimum requirement, it isn't allowed to install this package for configuration 1. But the user always see, that there is a newer version. This could be confusing.

It should be discussed, if the benefit to show the latest version in overview is higher than confusing the user maybe not being able to install the latest version.

**Comment by aschempp** [comment]
added in 46a6312458645acb813d11002e836ab4fe45cca5
