### ISSUE TITLE
Theme ODD wird nicht installiert

### ISSUE THREAD

**Issue by jaennert** [contao/contao-manager#610]
Hallo,

Contao 4.10.4 wurde erfolgreich installiert. Das Backend ist erreichbar. Beim Installieren des OOD-themes erhalte ich im Composer immer die Meldung:
Hintergrund-Prozess

Ein Hintergrund-Prozess wurde unerwartet beendet. Bitte prüfe die Konsolen-Ausgabe.
Pakete werden aktualisiert
composer require contao-themes-net/odd-theme-bundle
composer update (mittels Resolver Cloud)
> Resolving dependencies using Composer Cloud v2.4.11
!!! Current server is sponsored by: Contao Association !!!
[6.4MiB/0.30s] Loading composer repositories with package information
[6.9MiB/0.41s] Updating dependencies
[2951.8MiB/46.52s] Your requirements could not be resolved to an installable set of packages.
[2951.8MiB/46.52s] 
  Problem 1
    - Conclusion: don't install contao-themes-net/odd-theme-bundle 1.4.4
    - Conclusion: don't install contao-themes-net/odd-theme-bundle 1.4.3
    - Conclusion: don't install contao-themes-net/odd-theme-bundle 1.4.2
    - Conclusion: don't install contao-themes-net/odd-theme-bundle 1.4.1
    - Installation request for contao-themes-net/odd-theme-bundle ^1.4 -> satisfiable by contao-themes-net/odd-theme-bundle[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4].
    - Conclusion: don't install doctrine/doctrine-bundle 2.1.2
    - contao-themes-net/odd-theme-bundle 1.4.0 requires contao-bootstrap/bundle ~2.0 -> satisfiable by contao-bootstrap/bundle[2.0.0, 2.1.0, 2.1.1].
    - contao-bootstrap/bundle 2.0.0 requires contao-bootstrap/core ~2.0 -> satisfiable by contao-bootstrap/core[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - contao-bootstrap/bundle 2.1.0 requires contao-bootstrap/core ~2.0 -> satisfiable by contao-bootstrap/core[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - contao-bootstrap/bundle 2.1.1 requires contao-bootstrap/core ~2.0 -> satisfiable by contao-bootstrap/core[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - contao-bootstrap/core 2.0.0 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
    - contao-bootstrap/core 2.0.1 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
    - contao-bootstrap/core 2.0.2 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
    - contao-bootstrap/core 2.0.3 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
    - Can only install one of: doctrine/doctrine-bundle[1.10.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.2, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.3, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.11.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.11.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.11.2, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.10, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.2, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.3, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.4, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.5, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.6, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.7, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.8, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.9, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.8.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.8.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.9.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.9.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.10, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.11, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.12, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.13, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.2, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.3, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.4, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.5, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.6, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.7, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.8, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.9, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.7.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.7.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.7.2, 2.1.2].
    - Installation request for doctrine/doctrine-bundle (locked at 2.1.2) -> satisfiable by doctrine/doctrine-bundle[2.1.2].
[2951.8MiB/46.52s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[547.7MiB/48.14s] Memory usage: 547.72MB (peak: 2952.66MB), time: 48.15s.
[547.7MiB/48.15s] Finished Composer Cloud resolving.
# Cloud Job ID plEtCr9CjBPUSW1eFkyTp8SQ75wCQ8A2hUo7y86cXodNQgjo3LSImkPS1XFB5e7PPoMWQ0g1BLkLIS8ejYmOlCLuvvwsUvJ2MY4Y5EgFViBnKgIYubel failed
composer install
Contao Manager 1.3.3

    HilfeProbleme melden

Im Debugmodus wird folgendes ausgegeben:

Symfony\Component\HttpKernel\Exception\
NotFoundHttpException
in vendor/symfony/http-kernel/EventListener/RouterListener.php (line 136)
in vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 126)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 264)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> doDispatch (line 239)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 73)
in vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 168)
in vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 134)
in vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 80)
in vendor/symfony/http-kernel/Kernel.php -> handle (line 201)
Kernel->handle(object(Request))
in web/index.php (line 31)
Symfony\Component\Routing\Exception\
ResourceNotFoundException
None of the routers in the chain matched this request GET / HTTP/2.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Encoding: gzip, deflate, br Accept-Language: de-de Connection: close Content-Length: 0 Cookie: contao_settings=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkZWJ1ZyI6dHJ1ZSwiaWF0IjoxNjA0MzA5MzM4LCJleHAiOjE2MDQzMTExMzh9.Zc-5GEGrw6xMl9jiqQLQNF7I4RAebsoCD0tGX3dQ6-Q; PHPSESSID=foveip7h798p83hcpjpcceer5a; csrf_https-contao_csrf_token=yKAbeq9t_9575W-xA2CmS5ykTZeWbykiEcqMz3dutIk Host: roa-nv.de User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15 X-Php-Ob-Level: 1 Cookie: contao_settings=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkZWJ1ZyI6dHJ1ZSwiaWF0IjoxNjA0MzA5MzM4LCJleHAiOjE2MDQzMTExMzh9.Zc-5GEGrw6xMl9jiqQLQNF7I4RAebsoCD0tGX3dQ6-Q; PHPSESSID=foveip7h798p83hcpjpcceer5a; csrf_https-contao_csrf_token=yKAbeq9t_9575W-xA2CmS5ykTZeWbykiEcqMz3dutIk

Bin etwas ratlos und für eine Hilfe dankbar.
Erich

**Comment by aschempp** [comment]
das Theme scheint noch nicht mit Contao 4.10 kompatibel, das ist kein Fehler im Contao Manager. Bei Fragen wende dich bitte an das Community Forum oder den Slack-Kanal.

**Comment by jaennert** [comment]
Es ist nur merkwürdig, dass das Theme unter 4.10.4 auf der Seite roa.jaennert24.de <http://roa.jaennert24.de/> läuft.

Erich

**Comment by fritzmg** [comment]
@jaennert in any case, the problem is not related to the Contao Manager itself. You need to analyze why the dependencies do not allow the installation of this package within that specific environment.
