### ISSUE TITLE
Installation Marketing Suite schlug fehl.

### ISSUE THREAD

**Issue by snakybaby78** [contao/contao-manager#615]
Contao Manager lädt ewig und die Seite wird nicht mehr angezeigt! 

Fehlermeldung: An exception occurred while executing 'SELECT COUNT(*) AS count FROM tl_page WHERE cms_root_license!=''': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cms_root_license' in 'where clause'

**Comment by fritzmg** [comment]
Please use the community forum for these kinds of questions.

As for your error in the front end: you need to update your database via the Install Tool or via 

```
vendor/bin/contao-condole contao:migrate --no-interaction
```
