### ISSUE TITLE
4.9. LTS The background task has stopped unexpectedly

### ISSUE THREAD

**Issue by theking2** [contao/contao-manager#616]
Steps:
1) create a new subdomain on my hoster (Metanet)
2) download from https://contao.org/de/download.html select Contao 4.9 LTS
3) upload to a subfolder /web, and rename to contao-manager.phar.php
4) Open /web/contao-manager.phar.php

` The Composer Cloud failed with status code 405

  Composer Resolver returned an unexpected status code

Response:

Request:
{"composerJson":{"type":"project","require":{"contao\/manager-bundle":"4.8.*","contao\/calendar-bundle":"^4.8","contao\/comments-bundle":"^4.8","contao\/faq-bundle":"^4.8","contao\/listing-bundle":"^4.8","contao\/news-bundle":"^4.8","contao\/newsletter-bundle":"^4.8","contao\/conflicts":"*@dev"},"extra":{"contao-component-dir":"assets"},"scripts":{"post-install-cmd":["Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"],"post-update-cmd":["Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"]}},"composerLock":[],"platform":{"php":"7.4.13.0","php-64bit":"7.4.13.0","php-ipv6":"7.4.13.0","ext-date":"7.4.13.0","ext-libxml":"7.4.13.0","ext-openssl":"7.4.13.0","ext-pcre":"7.4.13.0","ext-zlib":"7.4.13.0","ext-bz2":"7.4.13.0","ext-calendar":"7.4.13.0","ext-ctype":"7.4.13.0","ext-hash":"7.4.13.0","ext-filter":"7.4.13.0","ext-ftp":"7.4.13.0","ext-gettext":"7.4.13.0","ext-gmp":"7.4.13.0","ext-spl":"7.4.13.0","ext-iconv":"7.4.13.0","ext-pcntl":"7.4.13.0","ext-readline":"7.4.13.0","ext-reflection":"7.4.13.0","ext-session":"7.4.13.0","ext-simplexml":"7.4.13.0","ext-sockets":"7.4.13.0","ext-mbstring":"7.4.13.0","ext-tokenizer":"7.4.13.0","ext-xml":"7.4.13.0","ext-cgi-fcgi":"7.4.13.0","ext-mysqlnd":"0.0.0.0","ext-bcmath":"7.4.13.0","ext-curl":"7.4.13.0","ext-dba":"7.4.13.0","ext-dom":"20031129","ext-fileinfo":"7.4.13.0","ext-gd":"7.4.13.0","ext-imagick":"3.4.4.0","ext-imap":"7.4.13.0","ext-intl":"7.4.13.0","ext-json":"7.4.13.0","ext-ldap":"7.4.13.0","ext-exif":"7.4.13.0","ext-mysqli":"7.4.13.0","ext-odbc":"7.4.13.0","ext-pdo":"7.4.13.0","ext-pdo_mysql":"7.4.13.0","ext-pdo_odbc":"7.4.13.0","ext-pdo_sqlite":"7.4.13.0","ext-phar":"7.4.13.0","ext-posix":"7.4.13.0","ext-pspell":"7.4.13.0","ext-redis":"5.3.2.0","ext-soap":"7.4.13.0","ext-sodium":"7.4.13.0","ext-sqlite3":"7.4.13.0","ext-sysvmsg":"7.4.13.0","ext-sysvsem":"7.4.13.0","ext-sysvshm":"7.4.13.0","ext-tidy":"7.4.13.0","ext-xmlreader":"7.4.13.0","ext-xmlrpc":"7.4.13.0","ext-xmlwriter":"7.4.13.0","ext-xsl":"7.4.13.0","ext-zip":"1.15.6.0","ext-ioncube-loader":"10.4.5.0","ext-zend-opcache":"7.4.13.0","lib-libxml":"2.9.1.0","lib-openssl":"1.0.2.11","lib-pcre":"10.35.0.0","lib-iconv":"2.17.0.0","lib-curl":"7.71.1.0","lib-imagick":"7.0.8.51","lib-icu":"50.2.0.0","lib-xsl":"1.1.28.0"}`

**Comment by aschempp** [comment]
Please try a bit later. Maybe the cloud service has too many requests.

**Comment by do-while** [comment]
You have an error at point 4.
The domain must point to the /web directory, so that you can call **http://yourdomain.tld/contao-manager.phar.php**.

**Comment by aschempp** [comment]
I assume this has been solved (#616)

**Comment by theking2** [comment]
> You have an error at point 4.
> The domain must point to the /web directory, so that you can call **http://yourdomain.tld/contao-manager.phar.php**.

That was it, sorry for the bandwidth
