### ISSUE TITLE
discover phase 

### ISSUE THREAD

**Issue by theking2** [contao/contao-manager#618]
According to the documentation the contao-managere.phar.php sits in a folder called web. The root of the site is pointing to  this web folder (see screenshot).

The contents of the vhost.conf also shows this folder relation:

```
<VirtualHost *:80>
	ServerName contao.kino-roxy.local
	DocumentRoot "d:/projekten/kino-roxy/dev/contao/web"
	<Directory  "d:/projekten/kino-roxy/dev/contao/web/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>
```

![image](https://user-images.githubusercontent.com/1612152/103094632-7a40aa00-45fe-11eb-8376-dc33f6e168fa.png)

**Comment by aschempp** [comment]
The Contao Manager will (ask to) create a new directory if your web directory is not empty (as described on the left side).

**Comment by theking2** [comment]
According to the log this command is the problem:
` C:\wamp64\bin\apache\apache2.4.41\bin\httpd.exe -f  "D:/dev/contao_local/web/contao-manager.phar.php" test`

Option -q for httpd.exe does not exist:
`httpd.exe: illegal option -- q`

Its also not documented on [Apache](https://httpd.apache.org/docs/2.4/programs/httpd.html)

**Comment by fritzmg** [comment]
That seems unrelated to the Contao Manager and more related to your web server setup.

**Comment by aschempp** [comment]
How is the command related to the new web directory?

**Comment by aschempp** [comment]
I'm closing this due to missing feedback. Feel free to reopen if there is more information.
