### ISSUE TITLE
Extension verweist/archiviert => Empfehlung = true?

### ISSUE THREAD

**Issue by mathContao** [contao/contao-manager#619]
![grafik](https://user-images.githubusercontent.com/1645099/103094871-1074d000-45ff-11eb-928c-39453abe494a.png)
https://extensions.contao.org/?q=&pages=1&p=twig%2Fextensions

Die Empfehlung heißt "true" und der dazugehörige Link: https://extensions.contao.org/?p=true

Liegt hier ein Fehler beim Auslesen der Empfehlung vor, die zu "true" fälschlicherweise konvertiert wird?

Wo finde ich eine Dokumentation, wie die Empfehlung korrekt gesetzt wird?

**Comment by Toflar** [comment]
Das ist tatsächlich ein Bug. Es muss nicht zwingend ein Ersatz vorgeschlagen werden. In diesem Fall sollte also sowas in der Art stehen:

>  Diese Erweiterung ist verwaist und wird nicht mehr gepflegt. Der Autor hat keine Empfehlung für einen Ersatz hinterlassen.

**Comment by mathContao** [comment]
> Wo finde ich eine Dokumentation, wie die Empfehlung korrekt gesetzt wird?

**Comment by Toflar** [comment]
Das sind die Empfehlungen vom Composer-Paket selbst. Du bist nicht der Autor dieses Pakets, also was willst du setzen?

**Comment by fritzmg** [comment]
> Wo finde ich eine Dokumentation, wie die Empfehlung korrekt gesetzt wird?

I don't think there is a documentation about this Packagist feature as it is pretty self explanatory when using it.

**Comment by mathContao** [comment]
OK. It did not knew it that it is a feature of packagist (I thought it is a setting by github/composer.json).

If you click on "abandon" in Packagist than you get this form
![grafik](https://user-images.githubusercontent.com/1645099/103149718-6024da00-476c-11eb-8be3-4c9a8a9728d3.png)

**Comment by aschempp** [comment]
Fixed in https://github.com/contao/package-list/commit/de58d70b31798d98e54ea7e144e3cc42491796e4
