### ISSUE TITLE
Contao Logo: align to the left edge + home link

### ISSUE THREAD

**Issue by mathContao** [contao/contao-manager#621]
I guess that the Contao logo is to narrow on the left edge. Please see the added red lines in the screen print:
![grafik](https://user-images.githubusercontent.com/1645099/103417764-50522f00-4b8c-11eb-9bdc-29ee6d93dfc4.png)

And I would suggest to add a "home" hyperlink on the Contao logo or Contao Manager image. In my opinion it would meet the expactions of user to go to the "home/start page".

**Comment by aschempp** [comment]
Logo position fixed in 32c5ba5043edeaecd25a400311200738c45b1161
As there is no "home page"/all navigation options are in the menu, I don't think we should add a link to the logo.
