### ISSUE TITLE
An error occurred while executing the "contao:install-web-dir" command

### ISSUE THREAD

**Issue by spirescreative** [contao/contao-manager#622]
Trying to perform a new install of 4.10. Get to this point and the install exits:

> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
In ScriptHandler.php line 95:
                                                                           
  An error occurred while executing the "contao:install-web-dir" command:  
                                                                           
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>...]
# Process terminated with exit code 1
# Result: General error

**Comment by spirescreative** [comment]
Here is a text file with the full composer install text: https://www.dropbox.com/s/le3vptap43l0044/contao-install-error.txt?dl=0

**Comment by spirescreative** [comment]
Tried installing 4.9 and received the same error.

**Comment by spirescreative** [comment]
Tried installing 4.4 and received a different error, but with the same script:

`> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
In ScriptHandler.php line 113:
                                                                               
  An error occurred while executing the "cache:warmup" command:                
  In 92da9b7be0f3e39acac0688ecaaa96aa765326d41e9aca5df03d4962681f3698.php lin  
  e 351:                                                                       
                                                                               
                                                                               
    Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate  
   4                                                                           
    0960 bytes)                                                                
                                                                               
                                                                               
                                                                               
                                                                               
  cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--  
  verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--en  
  v ENV] [--no-debug] [--] <command>                                           
                                                                               
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>...]
# Process terminated with exit code 1
# Result: General error`

**Comment by aschempp** [comment]
This error means there is a problem in the Contao application, not the Contao Manager. If you have command line access, can you try to run the `contao:install-web-dir` command manually if there is any error output?

It would be best if you contact the community forums or Slack channel, as this here is the bug and feature tracker of Contao Manager. https://to.contao.org/support

**Comment by spirescreative** [comment]
So, I've done my homework and performed an SSH command on the server to run "contao:install-web-dir" (actually ran "vendor/bin/contao-console contao:install-web-dir".) The server takes the command and doesn't report any output message. I'm assuming it accepted the command, but I'm at a loss as to what is next as nothing has changed.

I also opened a thread at the Community, but I'm concerned this is not an issue that the Community will solve as it needs your coding skills to decipher. 
https://community.contao.org/en/showthread.php?24903-Issues-with-installation-4-10-4-9-amp-4-4-contao-install-web-dir-amp-scriptHandler

Please advise. Thank you.

**Comment by spirescreative** [comment]
Running the following command -> php vendor/bin/contao-console contao:install-web-dir
Outputs the following: 
Updated the web/.htaccess file.
Added the web/preview.php file.
Added the web/app.php file.
Added the web/index.php file.

The Install Tool of the Contao Manager now throws a 500 Internal Server Error.

**Comment by aschempp** [comment]
Let's try to keep the discussion in the community forum, as the issue is clearly the memory limit of your server 😊
