### ISSUE TITLE
more menu: ui.package-details.support_website

### ISSUE THREAD

**Issue by mathContao** [contao/contao-manager#628]
the "more" menue looks broken in this case 
![grafik](https://user-images.githubusercontent.com/1645099/106943903-46d95b00-6726-11eb-85cb-08e9abff6830.png)
but the composer.json looks fine
![grafik](https://user-images.githubusercontent.com/1645099/106943998-62446600-6726-11eb-86c3-247e8b849ef6.png)

I could not find this problem at other extensions.

**Comment by aschempp** [comment]
`support.website` is not a valid support option: https://getcomposer.org/doc/04-schema.md#support

If that's your extension, you should probably use the `homepage` key: https://getcomposer.org/doc/04-schema.md#homepage

**Comment by aschempp** [comment]
I have improved the list to just show the json key if no translation is available (already available on https://extensions.contao.org/?q=contao-utils&pages=1&p=webexmachina%2Fcontao-utils)

**Comment by mathContao** [comment]
it is not my extension.

**Comment by LupusVII** [comment]
Thanks @aschempp, I should learn how to read a doc :)
Repo was updated with a better syntax: https://github.com/Web-Ex-Machina/contao-utils/releases/tag/0.3.6
