### ISSUE TITLE
Hintergrundprozess abbrechen bricht nicht ab

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#629]
Nach Button Abbruch bleibt es hängen

https://easycaptures.com/fs/uploaded/1339/9546180705.png

Beim erneuten Laden der Seite kommt man wieder an dem Stand an.

CM 1.3.3

**Comment by aschempp** [comment]
since this is rather old and we were unable to reproduce, I'm closing the issue. Feel free to reopen if it still happens and someone can add more details.
