### ISSUE TITLE
Composer findet Pfad nicht bei lokalen repositories in vendor/vendorname/bundlename

### ISSUE THREAD

**Issue by markocupic** [contao/contao-manager#634]
Hallo 
Beim Versuch mit dem Manager ein lokales Bundle zu installieren (composer.json: repositories->path), kommt es zu folgender Fehlermeldung. Die Fehlermeldung tritt nur im Manager auf. 
Ein `php composer update`, ausgeführt auf der Konsole, läuft sauber ohne Fehler durch.
```
> Resolving dependencies using Composer Cloud v3.0.0
!!! Current server is sponsored by: Contao Association !!!
[7.7MiB/0.24s] Loading composer repositories with package information
[8.1MiB/1.65s] [8.1MiB/2.08s] 
An error occurred during resolving process:
The `url` supplied for the path (vendor/markocupic/contao-test-bundle) repository does not exist`

```
root composer.json:
```
{
    "type": "project",
    "require": {
        "contao/calendar-bundle": "4.10.*",
        "contao/comments-bundle": "4.10.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "4.10.*",
        "contao/listing-bundle": "4.10.*",
        "contao/manager-bundle": "4.10.*",
        "contao/news-bundle": "4.10.*",
        "contao/newsletter-bundle": "4.10.*",
        "markocupic/contao-test-bundle": "1.0"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    },
    "repositories": [
        {
            "type": "path",
            "url": "vendor/markocupic/contao-test-bundle"
        }
    ]
}
```

Auszug composer.json des zu installierenden Bundles:
```
{
    "name": "markocupic/contao-test-bundle",
    "description": "*****",
    "keywords": [
        //
    ],
    "type": "contao-bundle",
    "license": "GPL-3.0-or-later",
    "authors": [
        {
           //
        }
    ],
    "support": {
        "issues": "https://github.com/markocupic/contao-test-bundle/issues",
        "source": "https://github.com/markocupic/contao-test-bundle"
    },
    "version": "1.0",
    "require": {
        "contao/core-bundle": "^4.9"
    },
    "autoload": {
        "psr-4": {
            "Markocupic\\ContaoTestBundle\\": "src/"
        },
        "classmap": [
            "src/Resources/contao"
        ],
        "exclude-from-classmap": [
            "src/Resources/contao/config",
            "src/Resources/contao/dca",
            "src/Resources/contao/languages",
            "src/Resources/contao/templates"
        ]
    },
    "extra": {
        "contao-manager-plugin": "Markocupic\\ContaoTestBundle\\ContaoManager\\Plugin"
    }
}
```

**Comment by fritzmg** [comment]
May be repository paths that point to `vendor/` aren't supported. Presumably the path you defined (`vendor/markocupic/contao-test-bundle`) is already the path that composer would install the package to. This is fine for initial development of a bundle but probably not recommended for a productive setup.

**Comment by markocupic** [comment]
Hi Fritz 
Development would be the usecase. ;-)
See the dev documentation:
https://docs.contao.org/dev/getting-started/extension/#installation

"When running a composer update, Composer will now symlink the given path into the vendor directory of the Contao 4 installation and everything is ready to go. You can now continue developing within vendor/somevendor/contao-example-bundle."

**Comment by fritzmg** [comment]
Yes, it should work when you use composer and not the Cloud Resolver via the Contao Manager.

**Comment by markocupic** [comment]
Yes, I noticed that too.

**Comment by aschempp** [comment]
I wonder if this is actually a cloud issue @Toflar? Since we convert the repository paths, maybe the cloud cannot have a dependency in `/vendor`?

**Comment by Toflar** [comment]
There's a lot of maybes in this world. If you can provide a log of what exactly is sent to the cloud, we can start reproducing and find the bug (if any).

**Comment by aschempp** [comment]
Here's the JSON I get when adding the package locally and retrieving the cloud data: 
[2022-03-04T091654.200.json.txt](https://github.com/contao/contao-manager/files/8184175/2022-03-04T091654.200.json.txt)

**Comment by markocupic** [comment]
I tested this again with Contao Manager in version 1.5.0 and Contao 4.13. The problem no longer occurs. 

I'm sorry that I'm only realizing it now. Thanks to [Composer's speed update](https://medium.com/@yanick.witschi/the-long-journey-of-making-phps-composer-memory-efficient-and-fast-63d12944aaa8), I was no longer dependent on the manager.
