### ISSUE TITLE
verfügbare Versionen sollte nur stabile Versionen anzeigen

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#637]
> Ich denke diese Funktion wurde mit der Version 1.4 eingeführt.

Vielen Dank. Ggf. könnte man noch `unstable` Pakete herausfiltern, sodass man nur Informationen zu neuen Versionen bekommt?

![2021-02-22 11 06 50 contao-bootstrap de aaa656d771c7](https://user-images.githubusercontent.com/1186266/108693395-13f0de80-74fe-11eb-8b11-4b793ae536d5.png)

__Originally posted by @dmolineus in https://github.com/contao/contao-manager/issues/350#issuecomment-783256628__

**Comment by aschempp** [comment]
@dmolineus dazu müssten wir eigentlich die Minimum-Stability im Projekt prüfen, oder? Denn dein Version Constraint würde tatsächlich die Installation dieser Version erlauben, wenn die Minimum-Stability auf beta gesetzt ist?

**Comment by dmolineus** [comment]
Meiner Meinung sind für die meisten Nutzer nur stabile Pakete interessant und nicht entsprechende Beta-Releases. Auf einer Live-Website möchte ich ja nur bedingt Beta-Versionen einsetzen. Die Berücksichtigung der Minimum-Stability Einstellung klingt aber auch plausibel und ist ein guter Weg.

**Comment by aschempp** [comment]
Leider scheint es aktuell einen Bug in Node-SemVer zu geben, weshalb das nicht korrekt funktioniert: https://github.com/npm/node-semver/issues/357
Wir müssen wohl erst mal warten bis das dort behoben ist.

**Comment by aschempp** [comment]
Ich konnte das nun verbessern. Wenn die "normale" Paketversion von `semver` verstanden wird, dann werden nur stabile Versionen angezeigt. Bei `erusev/parsedown` hat das bei mir funktioniert 😊
