### ISSUE TITLE
Directory Setup breaks Install if directory is already properly configured

### ISSUE THREAD

**Issue by asconsulting** [contao/contao-manager#647]
![Screenshot_2021-04-22 Contao Manager dev-dws brightcloudstudioserver com](https://user-images.githubusercontent.com/23730581/115755287-302cc280-a36b-11eb-95af-c2f412ffc8d5.png)

There seems to be no way to skip this step if the directory is already setup properly. As you can see the directory structure is already setup and /web is set as the web root with Contao installing to public_html, and world readable files living in /web. Ideally there should be a way to skip this step if everything is already setup. 

Related, is the empty directory warning. On cpanel hosts for example, AutoSSL creates .well-known folder for Let's Encrypt validation. It would be nice to also be able to ignore the directory not being empty messages as well. If you know what you are doing and have already customized your environment.

**Comment by asconsulting** [comment]
So if the directory structure is indeed empty all the way up to the /web directory you can get around the first step. However it would be nice to be able to ignore the empty directory warning because of the AutoSSL creating the validation file. This is frequently out of the control of the person installing Contao on cPanel hosts since those directories are created automatically and will respawn if deleted.

**Comment by aschempp** [comment]
I have improved the Contao Manager to ignore the `.well-known` directory if present in 1f0073fb616e47868525eeb38ba943618edc7224. I hope this fixed your issue 😊
