### ISSUE TITLE
Installprozess erzwingt Neuanlage eines Ordners

### ISSUE THREAD

**Issue by mathContao** [contao/contao-manager#650]
Ich habe die phar-Datei im Web-Ordner angelegt.

![grafik](https://user-images.githubusercontent.com/1645099/118553231-57a35f00-b760-11eb-8eb0-4bc3c98b425a.png)

Im Installprozess muss ich jedoch zwingend einen neuen Ordner anlegen, was jedoch aus meiner Sicht nicht notwendig ist.
![grafik](https://user-images.githubusercontent.com/1645099/118553046-101cd300-b760-11eb-9d06-99bb1040c86e.png)

Da der Ordner nicht erstellt werden soll, blockiert das doppelslash

**Comment by mlwebworker** [comment]
Hast Du mal probiert den übergeordneten Ordner anders zu benennen - also die Struktur nicht `.../contao/web` sondern `.../irgend_etwas_anderes/web`

**Comment by fritzmg** [comment]
The target directory needs to be empty. According to your screenshot there is an `index.html` file in your target directory.

**Comment by mathContao** [comment]
"...oder diese Ordner nicht leer sind" Upps.... Wer lesen kann ist klar im Vorteil. Danke.
