### ISSUE TITLE
Feature: Eigene Pfade für Shell-Scripts hinterlegen, ähnlich Composer-Scripts

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao-manager#651]
Um beispielsweise ein automatisiertes Backup (composer.lock, DB) vor jedem Update durchzuführen, wäre es sehr hilfreich, wenn es die Möglichkeit gäbe vor und nach bestimmten Schritten ein individuelles Script anzugeben.

**Beispiel:**
Vor Update: `/path/to/shellscript_a`
Vor Install: `/path/to/shellscript_b`
Nach Install: `/path/to/shellscript_c`

**Warum**
Mit Composer-Scripts (https://getcomposer.org/doc/articles/scripts.md) ist das zwar technisch möglich, da der Contao Manager allerdings in Verbindung mit der Composer Cloud eine etwas andere Logik verfolgt, wäre es hilfreich diese Scripte über den Contao Manager zu triggern.

Außerdem gäbe es die Möglichkeit unabhängig vom Composer nach Abschluss der Installation ein `contao:migrate` zu starten.

**Comment by aschempp** [comment]
Wie diskutiert am Mumble Call wollen wir keine Scripts einbauen, sondern irgendwann eine Backup-Funktion (see #87). 

Wir haben festgestellt dass das einzige Problem beim Composer `pre-install-cmd` die fehlende `composer.lock` ist. Allerdings wird die vom Manager selber bereits in `contao-manager/composer.lock~` gesichert, könnte also da geholt werden.
