### ISSUE TITLE
Fehler beim  Installieren von Composer-Abhängigkeiten auf XMAPP

### ISSUE THREAD

**Issue by hoeldrich** [contao/contao-manager#652]
> Resolving dependencies using Composer Cloud v3.2.0
!!! Current server is sponsored by: Contao Association !!!

[3.3MiB/0.18s] Loading composer repositories with package information
[51.4MiB/2.08s] Updating dependencies
[1377.0MiB/10.37s] Your requirements could not be resolved to an installable set of packages.
[1377.0MiB/10.37s] 
  Problem 1
    - contao/newsletter-bundle 4.9.10 requires contao/core-bundle 4.9.10 -> satisfiable by contao/core-bundle[4.9.10].
    - contao/newsletter-bundle 4.9.11 requires contao/core-bundle 4.9.11 -> satisfiable by contao/core-bundle[4.9.11].
    - contao/newsletter-bundle 4.9.12 requires contao/core-bundle 4.9.12 -> satisfiable by contao/core-bundle[4.9.12].
    - contao/newsletter-bundle 4.9.13 requires contao/core-bundle 4.9.13 -> satisfiable by contao/core-bundle[4.9.13].
    - contao/newsletter-bundle 4.9.14 requires contao/core-bundle 4.9.14 -> satisfiable by contao/core-bundle[4.9.14].
    - contao/newsletter-bundle 4.9.15 requires contao/core-bundle 4.9.15 -> satisfiable by contao/core-bundle[4.9.15].
    - contao/newsletter-bundle 4.9.16 requires contao/core-bundle 4.9.16 -> satisfiable by contao/core-bundle[4.9.16].
    - contao/newsletter-bundle[4.9.0, ..., 4.9.9] require php ^7.2 -> your php version (8.0.7.0) does not satisfy that requirement.
    - contao/core-bundle[4.9.10, ..., 4.9.16] require ext-gd * -> it has the wrong version (8.0.8) installed. Install or enable PHP's gd extension.
    - Root composer.json requires contao/newsletter-bundle 4.9.* -> satisfiable by contao/newsletter-bundle[4.9.0, ..., 4.9.16].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.0/cli/php.ini
    - /etc/php/8.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/8.0/cli/conf.d/10-opcache.ini
    - /etc/php/8.0/cli/conf.d/10-pdo.ini
    - /etc/php/8.0/cli/conf.d/15-xml.ini
    - /etc/php/8.0/cli/conf.d/20-bcmath.ini
    - /etc/php/8.0/cli/conf.d/20-bz2.ini
    - /etc/php/8.0/cli/conf.d/20-calendar.ini
    - /etc/php/8.0/cli/conf.d/20-ctype.ini
    - /etc/php/8.0/cli/conf.d/20-curl.ini
    - /etc/php/8.0/cli/conf.d/20-dba.ini
    - /etc/php/8.0/cli/conf.d/20-dom.ini
    - /etc/php/8.0/cli/conf.d/20-exif.ini
    - /etc/php/8.0/cli/conf.d/20-ffi.ini
    - /etc/php/8.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.0/cli/conf.d/20-ftp.ini
    - /etc/php/8.0/cli/conf.d/20-gd.ini
    - /etc/php/8.0/cli/conf.d/20-gettext.ini
    - /etc/php/8.0/cli/conf.d/20-gmagick.ini
    - /etc/php/8.0/cli/conf.d/20-gmp.ini
    - /etc/php/8.0/cli/conf.d/20-iconv.ini
    - /etc/php/8.0/cli/conf.d/20-igbinary.ini
    - /etc/php/8.0/cli/conf.d/20-imap.ini
    - /etc/php/8.0/cli/conf.d/20-intl.ini
    - /etc/php/8.0/cli/conf.d/20-ldap.ini
    - /etc/php/8.0/cli/conf.d/20-mbstring.ini
    - /etc/php/8.0/cli/conf.d/20-mysqli.ini
    - /etc/php/8.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/8.0/cli/conf.d/20-pdo_sqlite.ini
    - /etc/php/8.0/cli/conf.d/20-phar.ini
    - /etc/php/8.0/cli/conf.d/20-posix.ini
    - /etc/php/8.0/cli/conf.d/20-readline.ini
    - /etc/php/8.0/cli/conf.d/20-redis.ini
    - /etc/php/8.0/cli/conf.d/20-shmop.ini
    - /etc/php/8.0/cli/conf.d/20-simplexml.ini
    - /etc/php/8.0/cli/conf.d/20-soap.ini
    - /etc/php/8.0/cli/conf.d/20-sockets.ini
    - /etc/php/8.0/cli/conf.d/20-sqlite3.ini
    - /etc/php/8.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/8.0/cli/conf.d/20-xmlreader.ini
    - /etc/php/8.0/cli/conf.d/20-xmlwriter.ini
    - /etc/php/8.0/cli/conf.d/20-xsl.ini
    - /etc/php/8.0/cli/conf.d/20-zip.ini
    - /etc/php/8.0/cli/conf.d/50-serverctl.ini
    - /etc/php/8.0/cli/conf.d/51-serverctl.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
[1377.0MiB/10.37s] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
[73.0MiB/11.73s] Memory usage: 72.98MB (peak: 1377.34MB), time: 11.73s.
[73.0MiB/11.73s] Finished Composer Cloud resolving.

# Cloud Job ID Dlfz04ypxIlCPddoL4yW8sBknBKAisHqOuEY3sW6220s2vm6yXxRgdbIvDq2uNBB9Kzk6648vW3lAxXYIN86CbzvO1S87enWFrxuT failed

**Comment by aschempp** [comment]
> Install or enable PHP's gd extension.
