### ISSUE TITLE
Contao Manager 1.4.7 issue with MAMP PRO 6.5 ...

### ISSUE THREAD

**Issue by vav-medientechnik** [contao/contao-manager#660]
Hello dear Contao Manager Team, it looks like there is a small bug with the new Contao Manager Tool and MAMP PRO 6.5. The install tool told me that I need to **create a /web directory**, but I have this directory already created! It´s strange ... (screenshots added). Thank you for your help 🍀👋🏻
<img width="932" alt="Bildschirmfoto 2021-10-01 um 09 43 04" src="https://user-images.githubusercontent.com/85862643/135584351-2ab2f8c3-0f16-4f44-b7c9-55c7bcf957b7.png">
<img width="931" alt="Bildschirmfoto 2021-10-01 um 09 43 18" src="https://user-images.githubusercontent.com/85862643/135584371-f45bc416-985a-4188-9de0-35070da58327.png">

**Comment by frontendschlampe** [comment]
I have also issues with Contao Manager 1.4.7 and MAMP PRO 6.5:

If I make an update I got the following message:

`Error handling the Composer Resolver Cloud. Please try again later.`

**Comment by aschempp** [comment]
Please read the screen carefully:

> Contao kann zur Zeit nicht installiert werden weil die Ordnerstruktur **nicht stimmt** oder diese Ordner **nicht leer sind**.

--- 

@frontendschlampe I don't think your issue is even remotely related … so please create a separate issue with more information or a screenshot etc.
