### ISSUE TITLE
no update possible since Contao Manager 1.4.7 with MAMP PRO 6.5

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao-manager#661]
I want to make an update on my local installation. In the past there was no problems, but after updating to Manager 1.4.7 I got the following message, if I want to make an update:

`Error handling the Composer Resolver Cloud. Please try again later.`

There was only an update for Contao Manager but not for MAMP PRO.

![image](https://user-images.githubusercontent.com/1232819/135614794-9d3f897b-1225-46a5-847e-20e5179757c1.png)

![image](https://user-images.githubusercontent.com/1232819/135614980-bd32b628-b10c-461e-bf47-9d03f6eaf178.png)

**Comment by V15** [comment]
Same here. Same setup.

**Comment by Toflar** [comment]
I think this is neither a Manager nor a Cloud issue. It seems like the intermediate CA information has changed.

Probably MAMP Pro does not have access to the CA installed on the local system, thus falling back to the bundled one (https://github.com/contao/contao-manager/blob/1.x/api/System/Request.php#L217). 
This has been updated lately and the X3 has been removed as it expired September 30. See https://github.com/composer/ca-bundle/pull/66. Related discussion: https://github.com/composer/composer/issues/10121

/cc @leofeyer

**Comment by fritzmg** [comment]
As far as I understand the issue, the PHP OpenSSL extensions needs to have a minimum version to work with the recent Composer version. This apparently also affects some Hosters and not just MAMP Pro: #662

**Comment by basselin** [comment]
Replace **/Applications/MAMP/Library/OpenSSL/certs/cacert.pem**
with **https://curl.se/ca/cacert.pem**

And you can specify this **cacert.pem** to composer with the command :
`composer config --global cafile '/Applications/MAMP/Library/OpenSSL/certs/cacert.pem'`

**Comment by herrweiss77** [comment]
I have the same problem. MAMP Pro / macOS 11.6

**Comment by speedweb** [comment]
leider das selbe Problem auf mehreren Hosting mit Plesk.
Was kann hier genau dagegen unternommen werden?

**Comment by leofeyer** [comment]
Das Paket `ca-certificates` muss auf dem Server aktualisiert werden (z.B. mit `apt-get` oder mit `aptitude`), damit das neue Root-Zertifikat installiert wird.

**Comment by herrweiss77** [comment]
> Das Paket `ca-certificates` muss auf dem Server aktualisiert werden (z.B. mit `apt-get` oder mit `aptitude`), damit das neue Root-Zertifikat installiert wird.

Auch wenn kein SSL genutzt wird (unter MAMP Pro)?

**Comment by herrweiss77** [comment]
> bitte schaut ob das Problem mit dem neuen Manager 1.4.8 behoben ist.

Leider nein (MAMP Pro / MacOS)

**Comment by dazzle89** [comment]
Anfangs sah es gut aus, am Ende bekam ich dann aber diese Meldung:

`Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
90 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php vendor/bin/contao-setup
In AbstractMySQLDriver.php line 112:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for u  
  ser 'root'@'localhost' (using password: NO)                                  
                                                                               
In Exception.php line 18:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using pas  
  sword: NO)                                                                   
                                                                               
In PDOConnection.php line 40:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using pas  
  sword: NO)                                                                   
                                                                               
Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 1
# Process terminated with exit code 1
# Result: General error`

**Comment by herrweiss77** [comment]
Bei mir erscheint immer noch die gleiche Fehlermeldung:
Zuerst `HTTP request to https://www.composer-resolver.cloud/jobs failed with status code 500 ()`
Dann `Error handling the Composer Resolver Cloud. Please try again later.`

**Comment by V15** [comment]
Bei mir leider auch keine Besserung:
`$ /Applications/MAMP/bin/php/php7.4.12/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /Users/v15/Projekte/fku/web/contao-manager.phar.php composer remove alpdesk/alpdesk-parallax --no-update --no-scripts --no-ansi --no-interaction

Using config.component-dir has been deprecated. Please use extra.contao-component-dir instead.
/Users/xxx/composer.json has been updated

# Process terminated with exit code 0
# Result: OK


Error handling the Composer Resolver Cloud. Please try again later.

`

**Comment by frontendschlampe** [comment]
> bitte schaut ob das Problem mit dem neuen Manager 1.4.8 behoben ist.

same problem with Manager 1.4.8 and Mamp Pro 6.6

**Comment by vav-medientechnik** [comment]
Bei mir auch unter Contao CMS 4.9, MAMP PRO 6.6 und PHP 8.0.8 (CM = 1.4.8) leider das selbe Problem.
<img width="931" alt="Contao-Manager-Issue" src="https://user-images.githubusercontent.com/85862643/136331335-0917a16f-3616-4f14-a766-78ff220caa6b.png">

**Comment by vav-medientechnik** [comment]
Vielen Dank, genau das war jetzt die Lösung! 😃

**Comment by MaCo7** [comment]
Habe das gleich Problem immer noch, trotz des Workarounds con Patrick Weiss. Ich bekomme kein COntao Upgrade oder UPdate mehr zum Laufen.

**Comment by contaoacademy** [comment]
Ich konnte das Problem mit dem Workaround lösen. Hast du die richtige php.ini bearbeitet?

**Comment by MaCo7** [comment]
@contaoacademy  ICh hoffe ja ;). Wie genau bekomme ich das raus? Habe auch mehrere versucht. 
/Programme/MAMP/bin/php/php7.3.29/conf/php.ini .Ok?

**Comment by fritzmg** [comment]
> /Programme/MAMP/bin/php/php7.3.29/conf/php.ini .Ok?

Wenn der Contao Manager bei dir das PHP CLI unter `/Programme/MAMP/bin/php/php7.3.29` nutzt, dann ja. Wenn nicht, dann nicht.

**Comment by contaoacademy** [comment]
In folgendem Beitrag habe ich es auch noch mal dokumentiert:
https://contao-academy.de/contao-faq/mamp-6-6-fehler-error-handling-the-composer-resolver-cloud-please-try-again-later

**Comment by MaCo7** [comment]
HEy, es klappt. Dankkkeeeee Chris! ICh bin nochmal den Beitrag von Christian durchgegangen. HAbe dabei unter Parallels ein komplett neues macOS Monterey installiert, sowie MAmp Pro, etc. Die Resolver Cloud läuft!! Es funktioniert aber nur, wenn ich die Template php Dateien Bearbeite, nicht die, die Contao im Manager anzeigt. Seltsam!! Nun versuche ich es mal ob es so auch ohne VM hinbekomme.

**Comment by aschempp** [comment]
Closing this since it has to be solved locally on MacOS (see https://github.com/contao/contao-manager/issues/661#issuecomment-966169812)

**Comment by fritzmg** [comment]
It still can be solved on the server as well by removing the expired root certificate from the chain.

**Comment by aschempp** [comment]
thanks @fritzmg for the heads-up! We finally fixed this on the cloud directly, so this should be solved for anyone using MacOS/MAMP now 🎉

**Comment by rustykowski** [comment]
Leider habe ich unter MAMP 6.6 weiterhin das Problem. Sowohl mit Cloud-Resolver als auch ohne.
Ich bin dem Workaround von @herrweiss77 gefolgt. Habe natürlich auf das richtige Template (sprich: die richtige php.ini) geachtet, Mamp neu gestartet etc. 

Die Fehlermeldung lautet:
```
In CurlDownloader.php line 354:
                                                                               
  curl error 60 while downloading https://repo.packagist.org/packages.json: S  
  SL certificate problem: unable to get local issuer certificate
```

**Comment by fritzmg** [comment]
@rustykowski that seems to be a different problem. In your case your local CA file is not available or not accessible.

**Comment by rustykowski** [comment]
@fritzmg Can you please explain this a bit more? What would be the local CA file in the case of Mamp? Among other things, I find these files in the OpenSSL directory: 
MAMP_PRO_Root_CA.crt
MAMP_PRO_Root_CA.key
MAMP_PRO_Root_CA.srl
