### ISSUE TITLE
Contao Manger: Error handling the Composer Resolver Cloud. Please try again later.

### ISSUE THREAD

**Issue by dazzle89** [contao/contao-manager#662]
- Contao Manager 1.4.7
- zu installierende Version: sowohl 4.9 als auch 4.12
- Host Europe, also nicht lokal
- PHP 7.3.5

Seit einigen Tagen funktioniert die Installation über den Manager nicht. Ich erhalte die Meldung

_The Composer Cloud failed with status code 500_ (o.ä.) 

und kurz danach:

_Error handling the Composer Resolver Cloud. Please try again later._

Das Problem habe ich nun seit 3-4 Tagen, "try again later" scheint also nicht zu helfen...

Was mir gerade noch einfällt: Als ich im gleichen Zeitraum bei einer anderen Installation eine Erweiterung installieren wollte, kam die gleiche Meldung.

**Comment by fritzmg** [comment]
Possibly duplicate of #661
