### ISSUE TITLE
Inconsistent german translation

### ISSUE THREAD

**Issue by fiedsch** [contao/contao-manager#663]
The Options 

* Rebuild Procuction Cache
* Rebuild Development Cache
* Clear Production Cache
* Clear Development Cache

are labeled

* Prod.-Cache erneuern
* Dev.-Cache erneuern
* Cache der Produktionsumgebung leeren
* Cache der Entwicklungsumgebung leeren

with "Prod.-Cache" vs "der Produktionsumgebung" and "Dev.-Cache" vs "der Entwicklungsumgebung" that might cause irritations (they did: I was asked just that on yesterdays "Stammtisch"). 

Before making a commit on transifex I would like to discuss the change. My suggestion would be to use

* Production-Cache erneuern
* Development-Cache erneuern
* Production-Cache leeren
* Development-Cache leeren

Thanks!

**Comment by fiedsch** [comment]
Die Abkürzung war weniger das Verwirrende,sondern eher die Tatsche, daß für das Gleiche zwei verschiedene Begriffe verwendet wurden. In diesem Sinne wäre 

* Prod.-Cache erneuern
* Dev.-Cache erneuern
* Prod.-Cache leeren
* Dev.-Cache leeren

genauso eine „Lösung“.

**Comment by aschempp** [comment]
habe es in Transifex angepasst (siehe 859de4cad1eaef1707ad1f1d4493cca05dbcaf30)
