### ISSUE TITLE
Public folder /public still not valid

### ISSUE THREAD

**Issue by mp-itconsulting** [contao/contao-manager#664]
Although /public can be used as the new root directory in the documentation since 4.12, this is not recognised during installation via the contao manager. 

The manager then wants to set up a new structure:

Current root directory
    /srv/www/html/example.de/public

New root directory
    /srv/www/html/example.de/public/web

**Comment by mp-itconsulting** [comment]
Sorry, aber das stimmt nicht mit der Dokumentation überein:

...
Beispiel: example.com zeigt auf das Verzeichnis /www/example/web
( ab 4.12 Dem Standard von Symfony folgend, wurde der öffentlich erreichbare Unterordner von /web in /public umbenannt. Falls in deiner Installation ein Verzeichnis /web existiert, wird dieses von Contao automatisch anstelle von /public verwendet.)

Ein Ordner /web unter /public gibt keinen Sinn

**Comment by aschempp** [comment]
See https://github.com/contao/contao-manager/issues/654
