### ISSUE TITLE
Error 500 bei pct_customelements_attribute_isotope

### ISSUE THREAD

**Issue by TS16V** [contao/contao-manager#669]
Hallo,

Contao-Manager > Pakete > pct_customelements_attribute_isotope

Nach Insallation des Paketes im Contao-Manager ERROR 500 bei Aufruf des Installation-Tools.

**Comment by mlwebworker** [comment]
Wird wohl ein Problem mit pct_customelements_attributs_isotope sein. 
Error 500 ist ein interner Serverfehler. Die Ursachen können sehr vielfältig sein, z.B. ein ausgelasteter Server. Das kann ich mir bei PCT-Themes immer gut vorstellen. Kann aber auch diverse andere Ursachen haben. Vielleicht gibt das Error-Log des Servers einen Aufschluss.
Ich denke dass Du eine Lösung eher nicht beim Contao-Manager findest sondern beim Theme bzw. beim Ersteller der Erweiterung
