### ISSUE TITLE
Cloud Resolver is not resolving?

### ISSUE THREAD

**Issue by throny** [contao/contao-manager#670]
Related to #544 
It looks like the installer is not working at the moment, as the server unfortunately only responds:
`HTTP request to https://www.composer-resolver.cloud/jobs failed with status code 500 ()` (@Toflar?)

**Comment by aschempp** [comment]
It seems to be either resolved or a local problem. Other Contao users have no problem resolving dependencies. If the problem persists, please reach out to one of the community support options (https://to.contao.org/support), maybe someone can help with your local setup.
