### ISSUE TITLE
Use the tempdir from the web process

### ISSUE THREAD

**Issue by ausi** [contao/contao-manager#672]
Some hosters seem to have different TMPDIR settings on the CLI.

Could it be helpful to pass the correct directory manually to the php-process?

Like adding to https://github.com/contao/contao-manager/blob/d7d7e4102bfe1a83c4580c089414643f9ec1c688/api/Process/ConsoleProcessFactory.php#L238 the following line:

```php
$defaultArgs[] = '-dsys_temp_dir='.@sys_get_temp_dir();
```

Just a wild guess ☺️

**Comment by aschempp** [comment]
what if the TMPDIR on CLI is _intentionally_ set different and works correctly, but the CGI directory does not work on the CLI?

**Comment by ausi** [comment]
I think you’re right. We would have to use that “fix” only if the temp directory from CLI does not work actually. 

This detection would probably be too much overhead only to fix some misconfigured hosts?

**Comment by aschempp** [comment]
I would think so too… also, if you really need to, you can create your own `php.ini` for the command line and correctly configure the temp-dir there 🤷
