### ISSUE TITLE
Neuinstallation bei goneo scheitert / Error handling the Composer Resolver Cloud

### ISSUE THREAD

**Issue by FrischBlau** [contao/contao-manager#675]
Bei goneo scheitert die Neuinstallation von 4.9. und 4.13. via Contao Manager 1.5.1 gleich beim Schritt "Composer update" mit der Meldung "Error handling the Composer Resolver Cloud. Please try again later." Das ist auch die einzige Meldung im task-output.log
PHP-Version ist 7.4.28, goneo-Paket ist Webhosting Profi.

![screenshot](https://user-images.githubusercontent.com/6159447/158021113-7cf91227-ea4e-4cc6-8df2-df349b2a3565.png)

**Comment by aschempp** [comment]
Hört sich nach einem Hosting-Problem an, möglicherweise sind ausgehende Verbindungen von einer Firewall deaktiviert?

**Comment by FrischBlau** [comment]
Inzwischen gibt es Feedback von Goneo. Die wollen Contao + PHP 7.4 nicht mehr unterstützen und verweisen auf PHP 8. Also klares Hosting-Problem.

**Comment by aschempp** [comment]
nunja, PHP 7.4 ist end-of-life, von daher macht PHP8 schon Sinn 🙃 
https://www.php.net/supported-versions.php

**Comment by FrischBlau** [comment]
Absolut richtig. Schwierig ist nur dass Goneo PHP 7.4 nicht nur anbietet, sondern den Einsatz von PHP 7.4 sogar ausdrücklich empfiehlt. Da stimmt dann etwas nicht.
