### ISSUE TITLE
Updating ContaoManager from 1.5.0 to 1.5.1 fails

### ISSUE THREAD

**Issue by sebfach** [contao/contao-manager#676]
Self-update of contao-manager.phar.php fails with message "Cannot rename "[...]/public/contao-manager.temp" to "[...]/public/contao-manager.phar.php"."

System: Windows 10 Home (x64), Build 19044 with XAMPP v3.3.0
Contao: 4.13.0
Browser: Firefox 97.0.1 (x64)

How it happened: Called Contao Manager as usual, self-checks were running and detected and update for Contao Manager. Pressed red update button, update was tried and failed with the message above. Closing this returned me to the previous self-check page, where the update button popped up again.

**Comment by aschempp** [comment]
I'm not very familiar with Windows. Did you possibly add the Contao Manager from your user profile (desktop user) and the XAMPP server trying to update the file does not have the same access permissions?

**Comment by mlwebworker** [comment]
Ich habe es gerade bei mir getestet XAMPP mit PHP 7.4.27 getestet. Das Update des Managers läuft bei mir problemlos durch. XAMPP v3.3.0 dürfte nur die Version des Control Panels sein. Ist bei mir allerdings Windows Professional.
Wo ist XAMPP bei Dir installiert. Wenn es auf dem gleichen Laufwerk liegt, wie das Betriebssystem, habe ich schon häufiger von Problemen gehört.

**Comment by sebfach** [comment]
Oh, sorry, habe mich in die Irre führen lassen: XAMPP-Version ist 8.1.2 (x64), PHP-Version ebenso 8.1.2 laut phpinfo.
Das XAMPP-Control-Panel wird mit Admin-Rechten ausgeführt. XAMPP liegt in C:\xampp, wobei C: durchaus die Systempartition ist. Die Rechte auf die contao-manager.phar.php des User-Accounts, unter dem XAMPP und in Folge dessen dann auch Apache etc. laufen, sind ausreichend (ändern, lesen, ausführen, schreiben). XAMPP Control Panel und Apache etc. neustarten bzw. sogar händisch killen hat nichts gebracht. Die "Lösung" war ein händisches Update der contao-manager.phar.php durch Herunterladen der neusten Version und manuelles Ersetzen im Dateisystem. Dann läuft der Selbstcheck (natürlich) wieder einwandfrei durch, wenn man vorher noch einmal den Fehler "wegklickt", der vermutlich irgendwo noch gespeichert war. D.h. läuft nun erstmal wieder, die Ursache konnte ich aber leider nicht identifizieren. Ich muss leider sagen, dass Contao imho früher mal deutlich robuster gebaut war, als es den Contao Manager noch nicht gab und ein Update durch "Drüberbügeln" der Dateien erledigt war. Aber ich will hier jetzt nicht die Designentscheidungen in Frage stellen, sicher gab es gute Gründe dafür.
