### ISSUE TITLE
Oops! An Error Occurred

### ISSUE THREAD

**Issue by Justman10000** [contao/contao-manager#678]
Hi, nach der Installation von Contao kommt dies im Frontent:

![grafik](https://user-images.githubusercontent.com/49990629/158423049-8503cb26-c925-484e-8d8a-121f3c97e403.png)

**Comment by fritzmg** [comment]
More specifically: https://docs.contao.org/manual/en/guides/add-first-index-page/

**Comment by Justman10000** [comment]
> More specifically: https://docs.contao.org/manual/en/guides/add-first-index-page/

Wouldn't it make more sense to use a placeholder instead of just throwing an error?

**Comment by fritzmg** [comment]
If you have no site structure defined yet - and thus you also have not customized the 404 page of your domain yet - then what you will see is Symfony's default error page.

**Comment by aschempp** [comment]
I have some ideas about this as well, also see https://github.com/contao/contao/issues/601
And yes, this is not related to the Contao Manager 😊
