### ISSUE TITLE
Webside shows white screen after app.CRITICAL: Uncaught PHP Exception Symfony

### ISSUE THREAD

**Issue by Jens1204** [contao/contao-manager#682]
Best friends,
after installing the Contao extention newslinklist, error 500 occured in the Contao manger and my website only shows a white screen after calling it. Does anyone have an idea, how to handle this problem? This is the error log createt by contao manger while checking the PHP files on the host server:

... app.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Compile Error: require(): Failed opening required '/homepages/13/d898679681/htdocs/www.mywebsite.info/vendor/symfony/deprecation-contracts/function.php' (include_path='.:/usr/lib/php7.4')" at phar:///homepages/13/d898679681/htdocs/www.mywebsite.info/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/AutoloadGenerator.php line 1422 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Compile Error: require(): Failed opening required '/homepages/13/d898679681/htdocs/www.mywebsite.info/vendor/symfony/deprecation-contracts/function.php' (include_path='.:/usr/lib/php7.4') at phar:///homepages/13/d898679681/htdocs/www.mywebsite.info/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/AutoloadGenerator.php:1422)"} 

And this the html-code behind the white screen in the Firefox Inspector:
`<html>; <head></head>; <body cz-shortcut-listen="true">; </body>; </html>`

**Comment by cliffparnitzky** [comment]
@Jens1204 The ticket system is not intended to solve individual problems. Please discuss the problem at https://community.contao.org/de/index.php or in the Contao Slack workspace: https://contao.slack.com

**Comment by Jens1204** [comment]
I placed this topic here and did find the solution:
#683 : Webside shows white screen after CM Error 500 and app.CRITICAL: Uncaught PHP Exception Symfony
