### ISSUE TITLE
Contao / Manager error

### ISSUE THREAD

**Issue by wuwu1893** [contao/contao-manager#687]
Hello,

I'm completely stuck in my contao manager. Whatever I try to do, I get the following error:
 
 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

11:16:43 ERROR     [console] Error thrown while running command "cache:warmup --env=prod". Message: "File "../app/config/config.yml" does not exist." ["exception" => Symfony\Component\Yaml\Exception\ParseException { …},"command" => "cache:warmup --env=prod","message" => "File "../app/config/config.yml" does not exist."]

In Parser.php line 68:
                                                   
  File "../app/config/config.yml" does not exist.  
                                                   

cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

I have cleared the cache, event manually and tried many times, but without success. When I try to update the composer, I get the same error.

Can anyone help me out? 

Thanks a lot

Marc

**Comment by aschempp** [comment]
This is the bug and feature tracker of the Contao Manager. Your error looks like a misconfiguration, please reach out to the community support options (https://to.contao.org/support), e.g. the forums or Slack channel.
