### ISSUE TITLE
CM 1.5.5 Can´t change php version to 8.0

### ISSUE THREAD

**Issue by Schneetiger** [contao/contao-manager#689]
Hi folks,

at present I am using CM 1.5.5 and C 4.9.29; hosting is at WebGo. My problem: in CM 1.5.5 I can´t change the php version from 7.4 to 8.0; means, I can´t save it. The version freezes at 7.4. I talked with WebGo today and have changed the php version in the Webspace-Admin correctly to 8.0 and saved it of course. After the action I changed back to CM and tried to change the php version there again, but without any effort.

Has anybody a clue what is going wrong? The screenshot shows my manual overwrite to 8.0 but wihtout the possibility to save it.

![Screenshot 2022-05-30 at 18-41-37 Contao Manager contao4](https://user-images.githubusercontent.com/29976466/171034162-c50bcd8c-33be-485f-abab-e68d7f1a9807.png)
.

**Comment by fritzmg** [comment]
Which error occurs when you try to save it?

**Comment by Schneetiger** [comment]
Hi Fritz,

as far as I can tell, the save-button does not work and the screen does not change back to further testing the Contao Installation.

⁣Freundliche Grüße
Detlef Rimböck ​

**Comment by mlwebworker** [comment]
Normal erkennt der Manager den Pfad zur PHP-Cli selbständig, nach dem Du die PHP-Version umgestellt hast.
Was ergibt denn die Suche der PHP-Version auf der Konsole.
Mit 
`php8.0 -v`
solltest Du etwas in der Art bekommen
```
PHP 8.0.18 (cli) (built: Apr 21 2022 10:47:41) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.18, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.18, Copyright (c), by Zend Technologies
```

Wenn nicht, dann ist m.E. eventuell die Serverkonfiguration fehlerhaft.

Als Pfad

**Comment by Schneetiger** [comment]
Hallo Maren,

da muss ich morgen mal nachsehen. Auf der Konsole war ich Ewigkeiten nicht mehr; die Antwort kann also etwas dauern; bitte hierzu um Nachsicht.
Deine Erläuterung zum CM ist nachvollziehbar, da die gleiche CM-Version bei einem anderen Kunden problemlos auf PHP 8.0 umgestellt werden konnte; was m.E. Deiner Annahme einer fehlerhaften Serverkonfiguration als sehr wahrscheinlich entgegenkommt.

Werde also die Konsole befragen und mich wieder melden. Vielen herzlichen Dank erstmal und einen schönen Abend.

⁣Liebe Grüße
Detlef ​

**Comment by fritzmg** [comment]
> as far as I can tell, the save-button does not work and the screen does not change back to further testing the Contao Installation.

Have you tried a different browser? Does the network tab in the developer console of your browser show an unsuccessful request/response?

**Comment by Schneetiger** [comment]
Hi Fritz,

 

I haven´t tried it with another browser and haven´t checked the network tab yet because I have little time to work on that. I have a myin job during the week but I can tell you that wit hanother domain on Webgo and the same version of CM there was no problem to chenge the php version to 8.0.

 

Maren wrote me yesterday and asked me to test the php version via console. I will to that within the next days; she considered that the webspace could be wrong configured. Maybe she is right because Webgo trannferred their hostings a while ago to another location. I will check this out and answer as soon as possible.

 

Thanks a lot for your help.

 

Gesendet: Montag, 30. Mai 2022 um 20:07 Uhr
Von: "Fritz Michael Gschwantner" ***@***.***>
An: "contao/contao-manager" ***@***.***>
Cc: "Schneetiger" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [contao/contao-manager] CM 1.5.5 Can´t change php version to 8.0 (Issue #689)


 


as far as I can tell, the save-button does not work and the screen does not change back to further testing the Contao Installation.


Have you tried a different browser? Does the network tab in the developer console of your browser show an unsuccessful request/response?

**Comment by Schneetiger** [comment]
Hallo Maren,

entschuldigen meine späte Antwort. Komme erst heute dazu dir zu atund musste mich erst mit der Neueinrichtung meines SSH-Tools herumschlagen, nachdem mir vor einigen Wochen mein Rechner total abgeschmiert war.

So, also das Tool meldet mir die etwas neuere Version 8.0.19 und entspricht damit genau der Info, die du mir gesandt hast. Serverseitig sollte also alles passen?

Lieben Dank nochmal für deine Hilfe.

⁣Herzliche Grüße
Detlef ​

**Comment by fritzmg** [comment]
@Schneetiger ➡️  https://github.com/contao/contao-manager/issues/689#issuecomment-1141388881

**Comment by Schneetiger** [comment]
Servus Fritz,

ich denke es ist etwas einfacher in Deutsch zu schreiben 😉.

Habe jetzt folgendes gemacht:

1. Mit Marens Hinweis die php-Version des Servers eruiert. Dort ist definitiv PHP 8.0 hinterlegt. Am Webserver scheint es nicht zu liegen?

2. Mit Chrome den CM aufgerufen und auch der zeigt mir hier die PHP-Version 7.4 an und ich kann nicht einmal manuell auf 8.0 umstellen; lässt sich einfach nicht speichern!

Vielen Dank für Deine immer hervorragenden Hilfestellungen.

⁣Herzliche Grüße
Detlef

**Comment by fritzmg** [comment]
> lässt sich einfach nicht speichern!

Wie schon erwähnt: öffne die Developer Tools deines Browsers vorher, gehe auf den Netzwerk Tab, versuche dann zu speichern und analysiere dann den Response (ggf. auch nach Fehlermeldungen in der Konsole sehen).

**Comment by Schneetiger** [comment]
Gerade mit Webgo gesprochen und habe dann dort einen Systemcheck durchgeführt. Das Problem lag serverseitig; PHP 8.0 wird jetzt von CM erkannt; alles gut 👍.

Problem gelöst mittels Systemcheck bei Webgo.

Issued kann geschlossen werden; vielen Dank. ​
