### ISSUE TITLE
route_prefix in config.yml not respected

### ISSUE THREAD

**Issue by falkgeist** [contao/contao-manager#692]
E.g. when updating packages, you can directly update the database. The href for that button uses the URL "/contao/install", but with the changes from contao/contao#1999 it should respect the changes in the config.yml for the route_prefix, if present.

**Comment by aschempp** [comment]
The Contao Manager unfortunately cannot know about that configuration. Luckly, we'll get rid of the install tool soon, so this link shouldn't be necessary anymore 🙃

**Comment by falkgeist** [comment]
I additionally just noticed that this issue also applies to all other backend links in the manager. Namely the ones in the "Tools" section... If the manager can't know about this configuration, maybe get rid of the links (although I find them relatively useful) or introduce a variable in the manager itself, where you can copy the route from the Contao configuration.
Anyways, was just a small issue, nothing important.

**Comment by Toflar** [comment]
I've created a PR to fix this in Symfony which has now been merged into 6.3: https://github.com/symfony/symfony/pull/50637

**Comment by aschempp** [comment]
This will be supported in the next Contao Manager with the latest Contao versions.
