### ISSUE TITLE
Error Message (php symlink) before installation process start (system check)

### ISSUE THREAD

**Issue by skyflyofsw** [contao/contao-manager#693]
ERROR:
PHP-Webprozess
Die PHP Symlink-Methode ist nicht verfügbar oder funktioniert nicht korrekt.

This error message came across before I have even started to install this (via contao-manager 1.5.5) on my server (debian 10)
I think all the other websites are running smooth without any issue with symlink issues. Configuration is pretty much the same.

Any help would be appreciated in advance!

Thanks

Cheers and bye

**Comment by aschempp** [comment]
Any other Contao websites? It looks like a server configuration issue to me. Please refer to the community support options (https://to.contao.org/support) the get help with that.
