### ISSUE TITLE
Also set the database version when storing the database credentials

### ISSUE THREAD

**Issue by ausi** [contao/contao-manager#705]
This is how the install tool does it currently: https://github.com/contao/contao/blob/2c914e74c29956612522911067d7bb1251d406cf/installation-bundle/src/Controller/InstallationController.php#L336-L346

See also https://github.com/contao/contao/pull/4158#issuecomment-1169685620

Not sure how to do this though, as the manager itself doesn’t connect to the database.

**Comment by aschempp** [comment]
Would it make sense to allow the user to select a database version? As far as I know it only matters between MySQL 5 and 8?

**Comment by ausi** [comment]
> As far as I know it only matters between MySQL 5 and 8?

If this is the case, I’d agree that a select box for the user might make most sense :+1:

**Comment by aschempp** [comment]
Implemented in a4e084dcfe04ef55c458494c1ab89c6c1f4383f6.

**Comment by fritzmg** [comment]
Man wählt dann zwischen:

* MySQL 8.0+
* MySQL 5.7.9+
* MariaDB 10.2.7+
* Older MySQL or MariaDB
