### ISSUE TITLE
Also allow Safe Mode alternative for Setup

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-manager#707]
If you run a fresh `composer install` operation and something fails during that process (e.g. because a Git repo was included, but the target server did not have `git` available) the next time you start the Contao Manager it won't give you the opportunity to boot into the Safe Mode anymore, so that you can run `composer install` again (after you have fixed the previous issue). It only gives you the _Setup_ option. Instead you would currently have to delete the whole `vendor/` folder so that the Contao Manager offers you the Safe Mode again.

Ideally you should always be able to boot into the Safe Mode, so that you can always run `composer install` for instance.

**Comment by aschempp** [comment]
added in 40fe7cc62913ae4d984862016e898e1149eaed84. It does not work without a composer.json though, as the Contao Manager is not supposed to manage _any_ composer project, and a lot of API endpoints fail if there is no composer info.
