### ISSUE TITLE
404 bei Aufruf

### ISSUE THREAD

**Issue by Olli** [contao/contao-manager#71]
All-Inkl - PHP 7.0

ich rufe /composer.phar.php auf und bekomme
`404 - File /web/index.html Not Found`

**Comment by aschempp** [comment]
A development version is not supposed to be stable or even useable, please do not report your local issues with it.

**Comment by Olli** [comment]
Möchtest du das der Contao-Manager getestet wird? Wenn nicht, dann werde ich mich in Zukunft mit Issues zurück halten.

**Comment by leofeyer** [comment]
Im Moment machen Issues noch keinen Sinn; es gibt ja noch nicht mal eine Alpha-Version! Warte einfach, bis Andi eine Version zum Testen freigibt und dann kannst Du loslegen.
