### ISSUE TITLE
Datenbank-Änderungen über den Contao-Manager 1.6.x dauert sehr lange

### ISSUE THREAD

**Issue by codesache** [contao/contao-manager#715]
Mir ist mit der Umstellung im Contao Manager 1.6.x aufgefallen, das das ausgelagerte Installtool sehr langsam ist.

Der Durchlauf für die Aktualisierung der DB von einer 4.9.28 auf 4.9.33 mit dem neuen Manager 1.6 dauert ungewöhnlich lange. Bisher ging das sehr zügiger über contao/install

Getestet habe ich auf einem Server der eigentlich genügend Last ab kann.

**Comment by ausi** [comment]
Wie lange dauert es mit dem Install-Tool? Und wie lange im Vergleich mit dem Manager? Und könntest du testweise auch messen wie lange es über die Kommandozeile `vendor/bin/contao-console contao:migrate` dauert?

**Comment by codesache** [comment]
Ich kann es nur schätzen ca. Faktor 10 im Vergleich zum Installtool da ich nicht die ganze Zeit drauf geschaut habe.

Aber bei einer einzelnen Zeile hat die Prozessanzeige sehr lange gebraucht, bis die zur nächsten weiter springt.

Mit der Console schau ich noch bei einem anderen Projekt, da es bei dem Projekt schon durchgelaufen ist.

**Comment by cliffparnitzky** [comment]
Kann ich nicht bestätigen. Hab nen mariginalen Unterschied festgestellt.

**Comment by Ainschy** [comment]
Ich habe gestern einige Installationen mit dem CM 1.6.0 aktualisiert einen Verzögerung bei der DB Aktualisierung konnte ich nicht feststellen.

**Comment by aschempp** [comment]
Ich schliesse das Ticket mal mangels Alternativen. _Möglicherweise_ ist das neue DB Update langsamer, was aber (auch) daran liegt dass der Manager eine wiederum eine Kommandozeile ausführt, und nicht wie das Install-Tool "direkt im Prozess" was gemacht hat.
