### ISSUE TITLE
Version 1.6.0 - nach Contao Update wird die alte Version weiterhin angezeigt und ein Update angeboten.

### ISSUE THREAD

**Issue by Ainschy** [contao/contao-manager#716]
Versionsnummer nach dem Update einer Contao Version wird nicht aktualisiert.

Beispiel: 
Update Contao 4.13.5 -> 4.13.8 erfolgreich durchgeführt (!) 
Der CM zeigt immer noch die 4.13.5 als installierte Version an und bietet das Update auf 4.13.8 an.

Nachtrag: Nach ein paar Minuten wird die installierte Version erkannt, ggf. ein Cache Problem?

**Comment by aschempp** [comment]
ich vermute ein temporäres Problem bei dir 🙃
