### ISSUE TITLE
Can point Contao PHP path in new Contao manager / Shut off composer cloud

### ISSUE THREAD

**Issue by rburch** [contao/contao-manager#719]
We run multiple versions of PHP on our server and in the new Contao manager I can't update the path. When Contao manager loads and does the checks it still gives the button to update the path but clicking on it doesn't seem to do anything and skips over it. This same issue makes it so I can't shut off composer cloud.

**Comment by aschempp** [comment]
Duplicate of https://github.com/contao/contao-manager/issues/714
