### ISSUE TITLE
Icons are misplaced in Safari

### ISSUE THREAD

**Issue by akroii** [contao/contao-manager#720]
Hi all,
add and details icons are misplaced in safari.
<img width="592" alt="Bildschirmfoto 2022-08-29 um 08 45 17" src="https://user-images.githubusercontent.com/8830861/187139608-d11a3d7a-db52-4181-87ec-ae6175d20799.png">
<img width="290" alt="Bildschirmfoto 2022-08-29 um 08 55 02" src="https://user-images.githubusercontent.com/8830861/187141219-9c114234-f6c3-4737-8306-ff5785ab7e6d.png">

I wanted to make an pull request but i did not find the file -,-

You can simple change this line here:
```
.widget-button--add:before, .widget-button--check:before, .widget-button--cloud-off:before, .widget-button--cloud:before, .widget-button--console:before, .widget-button--database:before, .widget-button--details:before, .widget-button--edit:before, .widget-button--gear:before, .widget-button--hide:before, .widget-button--link:before, .widget-button--lock:before, .widget-button--maintenance:before, .widget-button--more:before, .widget-button--power:before, .widget-button--run:before, .widget-button--save:before, .widget-button--search:before, .widget-button--show:before, .widget-button--trash:before, .widget-button--unlock:before, .widget-button--update:before, .widget-button--upload:before, .widget-button .icon-selector:before {
position: relative;
display: inline-block;       <----- here
top: 5px;
width: 20px;
height: 20px;
margin-right: 8px;
background-position: 50%;
background-repeat: no-repeat;
background-size: 20px 20px;
content: "";
}
```
 
from 
`display: inline-block;`
to
`display: inline-table;`

Contao Manager 1.6.0

**Comment by aschempp** [comment]
I don't have this problem on my Safari 15.6 on macOS 12.5. What exact version are you on and did you make sure to clear any caches?
