### ISSUE TITLE
Typo: Dieses Paket wird entfernt, wenn du die Änderungen anwenden

### ISSUE THREAD

**Issue by k-webdesign** [contao/contao-manager#721]
Wurde ein Paket manuell entfernt, kommt ja diese Info. Da hat sich ein Typo eingeschlichen:

Dieses Paket wird entfernt, wenn du die Änderungen anwenden -> Dieses Paket wird entfernt, wenn du die Änderungen anwendest
<img width="585" alt="Bildschirmfoto 2022-08-30 um 14 26 10" src="https://user-images.githubusercontent.com/4130440/187436607-0f955874-39df-41ad-8e7f-8733cc07d901.png">

**Comment by aschempp** [comment]
Thanks, fixed on www.transifex.com
