### ISSUE TITLE
Grammatikfehler im CM 1.6

### ISSUE THREAD

**Issue by skipman** [contao/contao-manager#723]
Nach erfolgter Installation (4.13) folgt der Hinweis:
Um die Installation fertig zu stellen, **bitte öffne** das Install-Tool um die Datenbank zu verbinden und ein Backend-Konto hinzuzufügen.
Klingt für mich nicht ganz deutsch :zwinkern:

**Comment by netzarbeiter** [comment]
Kannst du uns einen Text vorschlagen oder passt folgender?

Um die Installation abzuschliessen, stelle im Installtool* die Verbindung zur Datenbank her und richte ein Backend-Konto ein.

*offizielle Schreibweise

**Comment by jscholtysik** [comment]
Hi Bjarke,

ich denke, es geht Ronald nicht um den Begriff "Install-Tool", sondern um diese Formulierung:

Bisher: Um die Installation fertig zu stellen, bitte öffne das Install-Tool...

Besser: Um die Installation fertig zu stellen, öffne bitte das Install-Tool...


Joachim

**Comment by netzarbeiter** [comment]
Das ist mir klar, mich hat nur gestört, dass die Lösungsfindung wieder an Andy ausgelagert wurde.

**Comment by skipman** [comment]
@jscholtysik hats erfasst: Es ging mir lediglich um die Reihenfolge der Wörter "bitte" und "öffne"
@netzarbeiter Dein Vorschlag ist PERFEKT!

**Comment by aschempp** [comment]
habe es bei https://www.transifex.com/contao/contao-manager geändert, wird in der nächsten Version übernommen 😊
