### ISSUE TITLE
CM 1.6 / C 4.13.8: Datenbank-Migrationen werden angezeigt obwohl im Install-Took keine vermerkt sind

### ISSUE THREAD

**Issue by herrrilke** [contao/contao-manager#724]
In der Systemwartung wird beim Punkt "Datenbank-Migrationen" die Meldung ausgegeben  "Datenbank-Problem gefunden."
![C4-13-8](https://user-images.githubusercontent.com/791989/189613062-16f49e96-51d2-41e1-9ada-ad8296347687.JPG)

Öffnet man daraufhin das Install-Tool, gibt es dort aber nichts zu tun: "Die Datenbank ist aktuell."

**Comment by aschempp** [comment]
welche Contao-Version verwendest du? Ist das reproduzierbar bzw. noch immer so wenn du dich anmeldest?

**Comment by herrrilke** [comment]
hi,

contao ist 4.13.10 - ich vermute aber, dass es daran liegt, dass der MySQL server die version 5.5 hat

**Comment by V15** [comment]
Ist bei mir auch so:

- Contao 4.13.10
- Lokal unter MAMP Pro
- MySQL 5.7.34

**Comment by contaoacademy** [comment]
Vielleicht identisch mit #726

Was passiert auf der Console bei der Eingabe von `contao:migrate `
Werden dort Fehler oder Warnings aufgeführt?

**Comment by aschempp** [comment]
Könnt ihr bitte prüfen was in der Browser-Konsole ausgegeben wird? Es wird ein Ajax-Request auf `.../server/database` oder so ähnlich abgesetzt, was kommt dort als Resultat?

**Comment by herrrilke** [comment]
mh, 
habe gerade eine installation auf C4.13.12 umgezogen (gleicher DB server): das lief problemlos durch.

**Comment by Songworks** [comment]
Hallihallo, ich hatte das gleiche oder zumindest ein ähnliches Problem.

@aschempp Habe geprüft was die `.../server/database`-Anfrage in der Browser-Console geprüft und ja, da kam eine Fehlermeldung zurück.

Für mich war es der Fehler `Wrong database version configured, [...]`.
Mit der Info konnte ich das auch problemlos lösen und nun wird im CM kein DB-Fehler mehr angegeben.

Ich vermute die Komponente zu dem DatabaseMigration Zeug prüft nur ob der Response einen Fehler/Problem liefert, verwendet aber nicht die mit gelieferte Message?

**Comment by aschempp** [comment]
@ausi @m-vo die Prüfung der Server-Version wurde doch erst in den neueren Versionen ergänzt, wird die Warnung im Install-Tool nicht ausgegeben?

**Comment by ausi** [comment]
> wird die Warnung im Install-Tool nicht ausgegeben?

Nur im migrate command soweit ich weiß.

**Comment by aschempp** [comment]
das ist natürlich blöd… 😅

**Comment by aschempp** [comment]
@contao/developers are there any plans to fix this in Contao 4.13? Then we should transfer/copy this issue, because the Contao Manager cannot fix it …

**Comment by aschempp** [comment]
Thinking of it, I think this is obsolete because the latest Contao Manager already handles the database for 4.13 as well 😎
