### ISSUE TITLE
Nach Update wird die Contao-Version nicht mehr erkannt

### ISSUE THREAD

**Issue by rustykowski** [contao/contao-manager#725]
nach einem erfolgreichen Update auf Contao 4.9.34 meldet die Systemprüfung:

> Contao-Installation
> Es wurde keine Contao-Installation gefunden.

Es erscheint ein Button „Abgesicherten Modus starten".
Beim Starten des abgesicherten Modus erschien zunächst ein Error 500: `The process has been signaled with signal “11"`.

Ich habe dann den Ordner "contao-manager" gelöscht, den CM neu gestartet und wieder einen Benutzer angelegt.
Das Ergebnis war wie zuvor, nur dass nun der abgesicherte Modus erfolgreich startet. Im Standard-Modus wird die Contao-Installation weiterhin nicht erkannt.
(PHP: 7.3.5)

**Comment by aschempp** [comment]
ich kann dieses Problem leider nicht reproduzieren. Wenn noch es noch besteht gerne melden.

**Comment by rustykowski** [comment]
ich kann es jetzt auch nicht mehr reproduzieren, da die Installation kürzlich auf einen anderen Server umgezogen ist.
