### ISSUE TITLE
Contao 5 - Contao-Manager

### ISSUE THREAD

**Issue by MiWoe-Contao-User** [contao/contao-manager#727]
Probleme mit dem Contao 5 - (Install-Manager)

Habe gestern bei gleichem ISP, vergleichbarem Hosting-Paket, eine Contao 5-Installation gemacht.
Super!
In 10 Minuten alles durchgelaufen, Theme drauf installiert. Alles bestens!

Heute versuche ich, ebenfalls bei Strato, vergleichbares Hosting-Paket, den identischen Ablauf für ein Kundenprojekt.
Nichts!

Der Contao-Manager hängt sich jedesmal beim "Composer Install" auf.
Jedemal in Zeile #182 "Installing Contao-Components/installer (1.4.1) Extraction Archive"

Auch der "alte Trick" das File task.json zu entfernen, bringt keine Besserung.

Techn. alles identisch zu gestern. 
Gestern in wenigen Minuten alles top.
Heute, "juckelt" er Stunden und hängt sich auf ....

Klar, der Kunde wartet!

Was kann ich tun?
Hat jemand einen Trick, Hilfe für mich?

Vielen Dank im Voraus
Michael

**Comment by mlwebworker** [comment]
Dabei handelt es sich aber nicht um einen Fehler des Managers. Dein Problem ist sicher besser im Forum aufgehoben.

**Comment by MiWoe-Contao-User** [comment]
Ok
Was muss ich tun?

Merci schonmal ....

**Comment by aschempp** [comment]
Unter https://to.contao.org/support findest du die Contao Support-Kanäle 😊
