### ISSUE TITLE
Datenbank-Migration nach Update von Contao 4.13 auf 5.0

### ISSUE THREAD

**Issue by jxns** [contao/contao-manager#730]
Nach dem Update auf Contao 5.0 zeigt mir der Contao Manager (1.6.0) in der Systemwartung an, dass 3 Datenbank-Migrationen ausstehen.
Die Datenbank-Überprüfung schlägt mir die folgenden Migrationen vor:

`Contao\CoreBundle\Migration\Version500\BasicEntitiesMigration
Contao\CoreBundle\Migration\Version500\BooleanFieldsMigration
Contao\CoreBundle\Migration\Version500\OrderFieldMigration`

Führe ich diese aus, so läd das Tool kurz, bricht dann aber mit der folgenden Meldung ab:
`
Die Änderungen konnten nicht angewendet werden. Möglicherweise wurde die Datenbank geändert, bitte prüfe nochmals und versuche es erneut.
`

Eine weitere Fehlermeldung erhalte ich nicht. Lässt sich das irgendwie beheben?

**Comment by mlwebworker** [comment]
Das hatte ich kürzlich bei einem Test auch. Das hat aber m.E. nichts mit dem Manager zu tun sondern mit irgendeiner Erweiterung, deren DB-Migration hängen bleibt.
Welche Erweiterungen sind installiert und sind diese schon mit Contao 5.0 kompatibel?

Da es sich hier m.E. nicht um ein Problem des Managers handelt wäre das [Contao-Forum](https://community.contao.org/de/index.php) oder [Slack-Kanal ](https://contao.slack.com/join/shared_invite/enQtNjUzMjY4MDU0ODM3LWVjYWMzODVkZjM5NjdlNDRiZjk2OTI3OWVkMmQ1YjA0MTQ3YTljMjFjODkwYTllN2NkMDcxMThiNzMzZjZlOGU#/shared-invite/email)besser geeigenet um das Problem weiter einzugrenzen

**Comment by jxns** [comment]
Ich hatte anfangs mit dem Update probleme, daher hatte ich alle Erweiterungen deinstalliert. Es sind nur die Core-Extensions installiert.

**Comment by jxns** [comment]
https://github.com/contao/contao/issues/5300
