### ISSUE TITLE
Feature Request - display newest version of extension in listview

### ISSUE THREAD

**Issue by berecont** [contao/contao-manager#732]
Feature Request:
Would it be possible to display newest version of installed extension, shown in details. As additional information on listview?
So, you save one click to details to check, if there's a newer possible version.
![contao-manager-request-version](https://user-images.githubusercontent.com/33038265/194222607-91da8c0f-e5a9-4565-a62f-d1b29443fe1c.jpg)

**Comment by Toflar** [comment]
> if there's a newer possible version.

This question cannot be answered. You don't know if it's "possible" upfront.

**Comment by aschempp** [comment]
I think the problem is noticing new major version (or anything outside your constraint). I agree this would be useful, not sure how to add it without adding too much clutter to the interface

**Comment by aschempp** [comment]
<img width="1208" alt="Bildschirmfoto 2022-10-13 um 20 51 02" src="https://user-images.githubusercontent.com/1073273/195681615-369e6363-af79-4254-bb77-f6c9491a930c.png">

What do you think about a hint like that? I would add a title attribute, not sure what it should say. Something like `A newer version outside your version constraint is available.`?

**Comment by berecont** [comment]
That sounds good. Those hint helps.
I think so too, adding a title attribute could be useful.
`A newer version outside your version constraint is available.`
`Es ist eine neuere Version ausserhalb Ihrer Versionseinschränkung verfügbar.`

**Comment by aschempp** [comment]
Implemented in 99845ed451b99924f21582bb5d4bc038f97022f1
