### ISSUE TITLE
Manager skips migrations if the database was subsequently emptied

### ISSUE THREAD

**Issue by MDevster** [contao/contao-manager#733]
I have emptied the database on an existing Contao 5 installation for testing. The use case is very common, because theme users first want to play around and then want to work with a fresh database.

**The error can be reproduced as follows**
1. Empty database

2. Call Manager and run check

3. Manager now wants to create an administrator account directly
![grafik](https://user-images.githubusercontent.com/10244240/195022222-25ce4776-d26f-4ba0-9def-b2268c9b6c01.png)

4. Create backend account does not work
![grafik](https://user-images.githubusercontent.com/10244240/195022269-a83cde23-faa2-4b1e-89b8-1cff7298baab.png)

The log shows the following
`Base table or view not found: 1146 Table 'xyz.tl_user' does not exist`

Reponse server/database
`
{
	"url": "",
	"pattern": "^([^:]+)://(([^:@]+)(:([^@]+))?@)?([^:/]+(:[0-9]+)?)/([^?]+)(\\?.+)?$",
	"status": {
		"type": "schema",
		"total": 41,
		"warnings": 0
	}
}
`

As seen in the repsonse, the number of schema changes is returned correctly, yet the manager wants to create an administrator account.

**Expected behavior**
So the manager should be able to see that he needs to run the migrations first.

**Comment by aschempp** [comment]
looks related to https://github.com/contao/contao-manager/issues/728#issuecomment-1266764563

**Comment by aschempp** [comment]
should be fixed by 78518825af4d9be9f79f5f2767474dfb4d7c869c
