### ISSUE TITLE
Better usability for creating user accout via a password manager

### ISSUE THREAD

**Issue by MDevster** [contao/contao-manager#734]
If a password manager is used to set the credentials for a new user account in the Contao Manager, the button still appears disabled after the input. I first have to click in one of the fields and trigger a keyup with the left or right key (enter also works), then I can use the button "Create Account".

![image](https://user-images.githubusercontent.com/10244240/195492653-6728108f-2d12-40b2-a86a-fdda62ef7949.png)

**Expected behavior**
The "Create Account" button will be visible immediately after inserting the new credentials. Or even better, the form will be sent directly after filling both fields.

**Comment by aschempp** [comment]
This does not happen with 1Password, looks like an issue in your password manager. What software do you use? I'm not sure we can fix this, does it happen on other websites?

**Comment by MDevster** [comment]
I use [KeePass](https://keepass.info/download.html) and [KeePassHttp-Connector for Chrome](https://chrome.google.com/webstore/detail/keepasshttp-connector/dafgdjggglmmknipkhngniifhplpcldb?hl=de) and [KeePassHttp-Connector for Firefox](https://addons.mozilla.org/de/firefox/addon/keepasshttp-connector/). In both the same behavior.

**Comment by fritzmg** [comment]
This is a pretty common problem with auto-fill mechanisms in general in my experience when there is JavaScript to detect changes in the input fields.

**Comment by aschempp** [comment]
@MDevster can you somehow debug this on your local computer? I would think that `onchange`-events or similar are not fired by the password manager. Could you for example create an empty HTML page with such a password field and check if `onkeyup` or any other events are fired when you paste into the field using your PW manager?

**Comment by ausi** [comment]
I think we should probably listen to `@input` here https://github.com/contao/contao-manager/blob/0a977c16f8605d0f511e058a1c8fc75514a95663/src/components/views/Account.vue#L35 and here https://github.com/contao/contao-manager/blob/0a977c16f8605d0f511e058a1c8fc75514a95663/src/components/views/Account.vue#L44 as `oninput` should always fire if the value changes (e.g. also when pasted via context menu or similar).

**Comment by aschempp** [comment]
Ah I was confusing this with the login form. Changed in b84abfb4d24688324017455b6cc72031bf14234a
