### ISSUE TITLE
Error 501 - HTTP-Anfrage für "GET api/server/database" fehlgeschlagen - nach Login

### ISSUE THREAD

**Issue by BugBuster1701** [contao/contao-manager#735]
Ich wollte ein Update von Contao 4.9 auf 4.13 durchführen. 
Umgebung: 
- Contao 4.9.19 
- PHP7 
- Contao Manager 1.6.0

Nach dem Login im CM 1.6.0 (wurde vorher noch per Update hochgezogen)  kommt es zur Meldung.

![Error501](https://user-images.githubusercontent.com/1218809/195990409-b90a2a92-7262-4103-9470-3d76d79b45b2.png)

Habe mal den CM komplett gelöscht und neu installiert, brachte keine Besserung.

Wenn ich auf Kommandozeile auf 4.13 update, dann funktioniert der CM wieder.

**Comment by BugBuster1701** [comment]
Passiert auch, wenn ich eine frische 4.13 über den Manager installieren will.
Wähle ich 4.13 und "weiter" kommt es zur Meldung, jedoch im Hintergrund scheint es weiterzulaufen, es ist dann plötzlich "Geschafft!" zu lesen.
![Error501-geschafft](https://user-images.githubusercontent.com/1218809/195994248-a6b367d9-910c-458d-a775-4ddf145376c2.png)

**Comment by aschempp** [comment]
I am unable to reproduce this. What webserver do you use? The error messages do not come from the Contao Manager, it looks like IIS or something thelike is replacing the response content because of the status code. I think I read about this somewhere recently …

**Comment by BugBuster1701** [comment]
That was directly on the hoster uberspace.
I am probably not the first.
https://community.contao.org/de/showthread.php?84024-Contao-Manager-1-6-1-uberspace-GET-not-supported-for-current-URL

**Comment by BugBuster1701** [comment]
Forum: "501 is returned on this endpoint if the Contao Console does not support certain contao:migrate commands or other CLI API functions."

**Comment by folkfreund** [comment]
I'd like to try to disable 501web errorpage (https://manual.uberspace.de/web-errorpage/)
Where can I find the contao-manager.phar 1.6.0 to reproduce the error again?

**Comment by aschempp** [comment]
This seems to be outdated. Let me know if the issue still exists.
