### ISSUE TITLE
Leerer User-Account Screen wenn User CLI fehlschlägt

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#737]
Leider kann ich es nicht bestätigen. Immer noch kommen keine Felder, wenn ich zum Anlegen eines Administrators komme. In der Konsole kommen folgende Fehler vor. 
<img width="577" alt="Bildschirm­foto 2022-10-18 um 11 53 43" src="https://user-images.githubusercontent.com/3715050/196398545-0419ce79-e828-4caf-bbfd-390347bf4ad3.png">

https://user-images.githubusercontent.com/3715050/196408526-bce737c0-86eb-41eb-82da-e5dd9d873489.mov

Hilft noch zu wissen, dass ich PHP 8.1 und MariaDB 10.5.16 nutze?

_Originally posted by @jankout in https://github.com/contao/contao-manager/issues/728#issuecomment-1282129368_

**Comment by markusmilkereit** [comment]
Wir haben aktuell genau dasselbe Problem, seit einem Upgrade des Contao Managers von 1.6.4 auf 1.7.0 mit Contao 5.1 und 5.2 (tritt nicht auf wenn 4.x verwendet wird).

**Comment by markusmilkereit** [comment]
Unser Problem hatte nicht (direkt) was mit dem Contao Manager zu tun: eine alte Erweiterung hat noch über eine alte Code-Zeile `if (!defined('TL_ROOT')) die('You can not access this file directly!');` die Ausführung unterbrochen. 

Die Erweiterung ist seit Contao 3.5 im Einsatz und war bis jetzt nicht auf CLI-Einsatz vorbereitet. Die neue Integration der Install/Setup-Routine seit Contao Manager 1.7.0 wurde durch den alten Aufruf geblockt. Bestimmt nicht die Lösung für alle, aber ein möglicher Ansatz. Danke @ausi für den Hinweis :)
