### ISSUE TITLE
Custom table deletion default checked

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao-manager#739]
Hi,

the install tool marks the checkbox to delete tables by default. This behaviour is risky to accidently delete custom tables.

![SCR-20221021-fkq](https://user-images.githubusercontent.com/6390770/197159951-6eb6399d-251d-4b95-a805-23637a2a6a02.png)

Greetz

**Comment by ausi** [comment]
As there is a backup of the database automatically before executing the migrations I’m not sure if this is considered risky.

**Comment by fritzmg** [comment]
I think it is, because if you lost data unnoticed, it will be at the very least inconvenient to restore and at worst impossible due to the backup retention policy.

**Comment by Kahmoon** [comment]
> As there is a backup of the database automatically before executing the migrations I’m not sure if this is considered risky.

Didn´t know that. Where is this backup in case i would need it?

**Comment by ausi** [comment]
> Where is this backup in case i would need it?

https://docs.contao.org/manual/de/cli/datenbank-backups/

**Comment by Kahmoon** [comment]
> > Where is this backup in case i would need it?
> 
> https://docs.contao.org/manual/de/cli/datenbank-backups/

I don´t want to create a backup (i already got one). I thought contao install tool will create automatically a backup when doing db updates.

**Comment by fritzmg** [comment]
As already said, Contao automatically creates a backup.

**Comment by Kahmoon** [comment]
OK? I misunderstood! 
I just did an update and at var/backups it is. Now i get it :)

**Comment by Toflar** [comment]
Running `contao:migrate` does. So the Manager does as well.

**Comment by aschempp** [comment]
> Running `contao:migrate` does. So the Manager does as well.

In Contao 4.13+ that is! Not for Contao 4.9 though. I will change the checkbox to be unchecked by default, since that's also the default behaviour of the command.

**Comment by aschempp** [comment]
Fixed in version 1.6.2
