### ISSUE TITLE
Add IntegrityCheck for basic requirements

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#74]
PHP version: >=5.5
PHP extensions: Intl, GD, etc.

https://docs.contao.org/books/manual/4.3/en/01-installation/configuring-the-live-server.html

This obviously depends on the Contao version to install.

**Comment by Toflar** [comment]
Actually Composer checks this when resolving dependencies.

**Comment by aschempp** [comment]
Yeah, but it's rather uncomfortable to click on install and then get a console error message.

**Comment by aschempp** [comment]
implemented in version 1.1.0
