### ISSUE TITLE
Use real version numbers for database configuration

### ISSUE THREAD

**Issue by ausi** [contao/contao-manager#740]
For better forwards compatibility with doctrine/dbal 4.0, see https://github.com/contao/conflicts/pull/38

In https://github.com/contao/contao-manager/blob/b84abfb4d24688324017455b6cc72031bf14234a/src/components/setup/DatabaseConnection.vue#L99-L114 we should use `8.0.0`, `5.7.9`, `10.2.7-MariaDB` and `5.1.0`

**Comment by aschempp** [comment]
are these compatible with older versions of Doctrine as well?

**Comment by aschempp** [comment]
Fixed in version 1.6.2
