### ISSUE TITLE
Erfolgreich nach x Sekunden: zu große Zahl

### ISSUE THREAD

**Issue by Xendiadyon** [contao/contao-manager#742]
Beim Update/Installieren einer Erweiterung wird composer update ausgeführt.
Dort steht dann als Meldung "erfolgreich nach 1667900868 Sekunden". Ich bin mir ziemlich sicher, dass ich nicht knapp 53 Jahre auf die Installation gewartet habe ;)

![grafik](https://user-images.githubusercontent.com/2657385/200532026-0f851788-b01e-40ba-abd8-94c9e3f178ef.png)

Edit:
![grafik](https://user-images.githubusercontent.com/2657385/200532369-05a64b81-1121-4f8c-babe-abca0e9d3733.png)

**Comment by aschempp** [comment]
should be fixed by a5eb631b46052e791dabbb75427377b943e88545
