### ISSUE TITLE
Improve the message for the diasbled upload button

### ISSUE THREAD

**Issue by MDevster** [contao/contao-manager#743]
With some "wild" hosters the zip extension for PHP seems not to be active by default, that leads to the manager disabling the upload button with the error message "Uploads are not supported in your installation. Please update the dependencies". The user has now tried to update the Contao installation multiple times, of course without success. Maybe you could specify the message a bit more, could solve the user himself or let the hoster do it.

![grafik](https://user-images.githubusercontent.com/10244240/201391454-2406b2cb-fd05-49ec-882a-00bb85112efc.png)

https://github.com/contao/contao-manager/blob/1dbbb264e4dedbdc707aeb17da3411c4ca3e1bcb/api/Controller/Packages/UploadPackagesController.php#L310

**Comment by aschempp** [comment]
Fixed in version 1.6.2
