### ISSUE TITLE
Do not update composer.json scripts to contao-setup

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-manager#744]
In the community it occurs very frequently that users get stuck when updating from Contao 4.4 or 4.5 etc. to Contao 4.9, because the Contao Manager automatically replaces

```json
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
```

with

```json
    "scripts": {
        "post-install-cmd": [
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "@php vendor/bin/contao-setup"
        ]
    }
```

which will not work in Contao 4.9. I think the Contao Manager should not change this at all and leave it up to the user to change it.

**Comment by aschempp** [comment]
It should only be changed when upgrading to Contao 5.0 🤔 
https://github.com/contao/contao-manager/blob/bd4d585cbb585295dfbc42836a955449708f7fb8/api/Task/Packages/UpdateTask.php#L225-L238

**Comment by aschempp** [comment]
and I doubt they all downgraded their Contao 5?

**Comment by fritzmg** [comment]
Yes, they all either updated from 4.5 to 4.9 or 4.9 to 4.13 (but that updated failed and thus they were still at 4.9 - but with `vendor/bin/contao-setup` in their scripts section).

**Comment by fritzmg** [comment]
Here is another recent case: https://community.contao.org/de/showthread.php?83736-Update-4-9-als-Vorbereitung-auf-4-13&p=565696&viewfull=1#post565696
