### ISSUE TITLE
Ein Hintergrund-Prozess wurde unerwartet beendet. Bitte prüfe die Konsolen-Ausgabe.

### ISSUE THREAD

**Issue by markYmarkgo** [contao/contao-manager#747]
Hello, everyone,

wanted to familiarize myself with Contao and try to install Contao with the contao-manager. Everything seemed to be fine so far. But when I arrived at the Contao installation, I had selected "Contao 4.13" and pressed the installation button.

`"Composer create"` ran without any problems.
But `"composer update --no-install --no-scripts"` produced errors including: " Your requirements could not be resolved to an installable set of packages."

I would be very grateful for any help.
![image](https://user-images.githubusercontent.com/88718969/204839427-aa000875-20d9-468c-b0ed-a9680517a434.png)

LG mark

**Comment by markYmarkgo** [comment]
composer update --no-install --no-scripts

> Resolving dependencies using Composer Cloud v3.5.1
[3.1MiB/0.14s] Loading composer repositories with package information
[50.0MiB/5.23s] Updating dependencies
[89.5MiB/5.55s] Your requirements could not be resolved to an installable set of packages.
[89.5MiB/5.55s] 
  Problem 1
    - contao/newsletter-bundle 4.13.0 requires contao/core-bundle 4.13.0 -> satisfiable by contao/core-bundle[4.13.0].
    - contao/newsletter-bundle 4.13.1 requires contao/core-bundle 4.13.1 -> satisfiable by contao/core-bundle[4.13.1].
    - contao/newsletter-bundle 4.13.2 requires contao/core-bundle 4.13.2 -> satisfiable by contao/core-bundle[4.13.2].
    - contao/newsletter-bundle 4.13.3 requires contao/core-bundle 4.13.3 -> satisfiable by contao/core-bundle[4.13.3].
    - contao/newsletter-bundle 4.13.4 requires contao/core-bundle 4.13.4 -> satisfiable by contao/core-bundle[4.13.4].
    - contao/newsletter-bundle 4.13.5 requires contao/core-bundle 4.13.5 -> satisfiable by contao/core-bundle[4.13.5].
    - contao/newsletter-bundle 4.13.6 requires contao/core-bundle 4.13.6 -> satisfiable by contao/core-bundle[4.13.6].
    - contao/newsletter-bundle 4.13.7 requires contao/core-bundle 4.13.7 -> satisfiable by contao/core-bundle[4.13.7].
    - contao/newsletter-bundle 4.13.8 requires contao/core-bundle 4.13.8 -> satisfiable by contao/core-bundle[4.13.8].
    - contao/newsletter-bundle 4.13.9 requires contao/core-bundle 4.13.9 -> satisfiable by contao/core-bundle[4.13.9].
    - contao/newsletter-bundle 4.13.10 requires contao/core-bundle 4.13.10 -> satisfiable by contao/core-bundle[4.13.10].
    - contao/newsletter-bundle 4.13.11 requires contao/core-bundle 4.13.11 -> satisfiable by contao/core-bundle[4.13.11].
    - contao/newsletter-bundle 4.13.12 requires contao/core-bundle 4.13.12 -> satisfiable by contao/core-bundle[4.13.12].
    - contao/newsletter-bundle 4.13.13 requires contao/core-bundle 4.13.13 -> satisfiable by contao/core-bundle[4.13.13].
    - contao/newsletter-bundle 4.13.14 requires contao/core-bundle 4.13.14 -> satisfiable by contao/core-bundle[4.13.14].
    - contao/core-bundle[4.13.0, ..., 4.13.14] require ext-gd * -> the ext-gd package is disabled by your platform config. Enable it again with "composer config platform.ext-gd --unset".
    - Root composer.json requires contao/newsletter-bundle 4.13.* -> satisfiable by contao/newsletter-bundle[4.13.0, ..., 4.13.14].
To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.1/cli/php.ini
    - /etc/php/8.1/cli/conf.d/10-mysqlnd.ini
    - /etc/php/8.1/cli/conf.d/10-opcache.ini
    - /etc/php/8.1/cli/conf.d/10-pdo.ini
    - /etc/php/8.1/cli/conf.d/15-xml.ini
    - /etc/php/8.1/cli/conf.d/20-bcmath.ini
    - /etc/php/8.1/cli/conf.d/20-bz2.ini
    - /etc/php/8.1/cli/conf.d/20-calendar.ini
    - /etc/php/8.1/cli/conf.d/20-ctype.ini
    - /etc/php/8.1/cli/conf.d/20-curl.ini
    - /etc/php/8.1/cli/conf.d/20-dba.ini
    - /etc/php/8.1/cli/conf.d/20-dom.ini
    - /etc/php/8.1/cli/conf.d/20-exif.ini
    - /etc/php/8.1/cli/conf.d/20-ffi.ini
    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.1/cli/conf.d/20-ftp.ini
    - /etc/php/8.1/cli/conf.d/20-gd.ini
    - /etc/php/8.1/cli/conf.d/20-gettext.ini
    - /etc/php/8.1/cli/conf.d/20-gmagick.ini
    - /etc/php/8.1/cli/conf.d/20-gmp.ini
    - /etc/php/8.1/cli/conf.d/20-iconv.ini
    - /etc/php/8.1/cli/conf.d/20-igbinary.ini
    - /etc/php/8.1/cli/conf.d/20-imap.ini
    - /etc/php/8.1/cli/conf.d/20-intl.ini
    - /etc/php/8.1/cli/conf.d/20-ldap.ini
    - /etc/php/8.1/cli/conf.d/20-mbstring.ini
    - /etc/php/8.1/cli/conf.d/20-mysqli.ini
    - /etc/php/8.1/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/8.1/cli/conf.d/20-pdo_sqlite.ini
    - /etc/php/8.1/cli/conf.d/20-phar.ini
    - /etc/php/8.1/cli/conf.d/20-posix.ini
    - /etc/php/8.1/cli/conf.d/20-readline.ini
    - /etc/php/8.1/cli/conf.d/20-redis.ini
    - /etc/php/8.1/cli/conf.d/20-shmop.ini
    - /etc/php/8.1/cli/conf.d/20-simplexml.ini
    - /etc/php/8.1/cli/conf.d/20-soap.ini
    - /etc/php/8.1/cli/conf.d/20-sockets.ini
    - /etc/php/8.1/cli/conf.d/20-sqlite3.ini
    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini
    - /etc/php/8.1/cli/conf.d/20-xmlreader.ini
    - /etc/php/8.1/cli/conf.d/20-xmlwriter.ini
    - /etc/php/8.1/cli/conf.d/20-xsl.ini
    - /etc/php/8.1/cli/conf.d/20-zip.ini
    - /etc/php/8.1/cli/conf.d/50-serverctl.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-gd` to temporarily ignore these required extensions.
[89.5MiB/5.55s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[30.3MiB/5.58s] Memory usage: 30.3MB (peak: 129.47MB), time: 5.59s.
[30.3MiB/5.58s] Finished Composer Cloud resolving.
# Cloud Job ID lVWHYLlqCSC0oxb68lSfndVjRzPpdTEZdosbppkaH2VV0SxmpS7P1cQiIVuTyxRx4VrhrxYvR5lfx4MzxpT26Jzr failed

**Comment by fritzmg** [comment]
Your server does not have the GD image processing library enabled. See also https://docs.contao.org/manual/en/installation/system-requirements/#php-extensions

**Comment by markYmarkgo** [comment]
`Your server does not have the GD image processing library enabled. See also https://docs.contao.org/manual/en/installation/system-requirements/#php-extensions`

Many Thanks!! Yes, that was my problem! Now the contao installation is complete!
