### ISSUE TITLE
The requested URL was not found on this server.

### ISSUE THREAD

**Issue by markYmarkgo** [contao/contao-manager#748]
Hello, everyone,

I finally managed to successfully go through the installation process of Contao. 

![contao1](https://user-images.githubusercontent.com/88718969/204892904-3c959c66-beea-47e3-8f2f-a7adaaddfc39.png)

But when I try to connect to the database and press the "Open install tool" link (http://localhost/contao/install) the file isn't found, it just doesn't exist! "The requested URL was not found on this server."

How do I have to carry out the installation process so that the "install" file also exists?

Many Thanks.

LG Mark

**Comment by aschempp** [comment]
It looks like you are using a local webserver that does not correctly apply URL rewriting. You might need to configure your webserver, please refer to the community support (Slack or forum, see https://to.contao.org/support) if you need any help with this 😊

**Comment by markYmarkgo** [comment]
I think the web server (XAMPP) is set up correctly. The file is just not created by vontao-manager.

**Comment by fritzmg** [comment]
You need to make sure that the `AllowOverride All` directive for your `Directory` in your `VirtualHost` definition is set, so that the `.htaccess` is actually processed by Apache. Furthermore you will need `mod_rewrite` to be enabled in your Apache web server so that URLs like `https://example.com/contao/install` will work.

If either of these conditions are not met, only URLs like `https://example.com/index.php/contao/install` will work.

**Comment by markYmarkgo** [comment]
All rights are set to full access in the directory. The problem is that this file is not created during the contao installation process.

**Comment by fritzmg** [comment]
> All rights are set to full access in the directory. The problem is that this file is not created during the contao installation process.

You misunderstand. There is no file - `/contao/install` is a route that is supposed to be processed by the `index.php`. See also https://symfony.com/doc/current/setup/web_server_configuration.html

**Comment by fritzmg** [comment]
See also https://docs.contao.org/manual/en/installation/system-requirements/#web-server-configuration

**Comment by markYmarkgo** [comment]
@fritzmg: Thank you, that was the solution! Yeaaah!
