### ISSUE TITLE
Install Script gelöscht

### ISSUE THREAD

**Issue by badde-media** [contao/contao-manager#749]
Hallo,

Ist das Absicht, dass das Install Script gelöscht wird, bevor so Sachen wie die Datenbankeinrichtung, die darauf zugreifen, abgeschlossen sind? Ich meine, der Contao Manager sagt mir, dass die DB nicht eingerichtet ist, mit nem großen roten Button, dann klick ich auf den und kriege 404. Ich weiß schon, warum ich allen meinen Kunden dringend von Contao abrate. Nicht mal die Installation klappt ohne Probleme, und dauert auch noch ewig. Und das ist ja erst der Anfang...

**Comment by badde-media** [comment]
Hab den Fehler gefunden. Das Install Tool findet sich nicht unter dem Contao Stammverzeichnis, sondern unter /web. Wundert mich ehrlich gesagt, dass es anscheinend noch niemandem aufgefallen ist, dass euer Contao Manager da nen falschen Link drin stehen hat. Ich meine, Contao 4.9 ist jetzt wie lange draußen?

**Comment by V15** [comment]
Guten Morgen,
glaubst du wirklich, dass du da einen Fehler gefunden hast?
"Ich meine, Contao 4.9 ist jetzt wie lange draußen?"

Warum "ärgerst" du dich denn mit Contao rum, wenn du es micht magst?
Nimm doch ein anderes System.

**Comment by fritzmg** [comment]
`/contao/install` is a route, not a physical script. If you had to access it via `...web/contao/install` then you likely did not configure a domain that is pointing to the web subfolder.

**Comment by aschempp** [comment]
Closing since this is a support request that should be placed in the forums or Slack channel.
