### ISSUE TITLE
Datenbank-Änderung funktioniert nicht Ausstehende Änderungen)

### ISSUE THREAD

**Issue by merlincom** [contao/contao-manager#753]
Contao Version 4.13.14

Contao Manager > Systemwartung > Datenbank-Migration 
**Meldung (orange hinterlegt): 3 ausstehende Schema-Änderungen**

Schema - überprüfen > Schema-Änderungen:

`ALTER TABLE tl_member CHANGE company_address_prefered_my company_address_prefered_my VARCHAR(4) DEFAULT '0' NOT NULL
ALTER TABLE tl_preview_link DROP expiresInDays
ALTER TABLE tl_preview_link ADD restrictToUrl CHAR(1) DEFAULT '1' NOT NULL`
Ausführen > [X] Alle Änderungen inklusive Löschung anwenden > Ausführen

Meldung: Datenbank-Änderungen 
(nur Schema)
Keine ausstehenden Schema-Änderungen gefunden. Bitte prüfe auch die Migrationen > Alles überprüfen

Meldung: 
Datenbank-Änderungen
(nur Migrationen)
Keine ausstehenden Migrationen gefunden. Bitte prüfe auch die Schema-Änderungen.

Datenbank-Änderungen
Keine ausstehenden Migrationen oder Schema-Änderungen gefunden. Deine Datenbank ist auf dem aktuellsten Stand. > Schliessen

Meldung bleibt weiterhin bestehen: **Datenbank-Migrationen 3 ausstehende Schema-Änderungen**
Den Kreislauf zu wiederholen oder den Cache zu leeren bringt keine Besserung.

**Comment by aschempp** [comment]
Ich hatte dieses Problem soeben auch bei einem Kundensystem. Scheinbar wird der Hintergrund-Prozess beim lesen der öffenen Migration nicht immer korrekt gestartet. Ich habe das in ef9afba5b9d43ae1be34aa4db6cbc4a3cd43b3ea behoben.
