### ISSUE TITLE
Contao install problem

### ISSUE THREAD

**Issue by NKaufeld** [contao/contao-manager#755]
Hi,
I'm doing step by step instalation like always on Google Chrome.

i'm getting this error on 'Composer Environment | Composer dependencies are not installed.'

composer update --no-install --no-scripts
'HTTP request to https://www.composer-resolver.cloud/jobs failed with status code 500 ()' and 'Error handling the Composer Resolver Cloud. Please try again later.' from console in Background Task.

**Comment by Toflar** [comment]
I think external requests are blocked on your server. Hence nothing works at all.

**Comment by Toflar** [comment]
Do you have command line access? If so, what happens if you run `curl https://packagist.org`?

**Comment by NKaufeld** [comment]
> I think external requests are blocked on your server. Hence nothing works at all.

You had right. I unlocked it on server and works. TY!
