### ISSUE TITLE
Abbruch

### ISSUE THREAD

**Issue by ticktacktu** [contao/contao-manager#756]
Wenn ich MATE installiere kommt Abbruch.
![Screenshot 2023-01-26 185950](https://user-images.githubusercontent.com/123665087/214913159-2d6d7caf-0386-4edc-8db2-ec7a27e33bad.jpg)

**Comment by mlwebworker** [comment]
Bitte poste Dein Problem im Contao-Forum https://community.contao.org/de/index.php. Hier geht es um Probleme des Managers. Du hast ein Problem mit den Anforderungen des Mate-Themes. Die von Dir verwendete Version des Mate-Themes benötigt Contao 5.

**Comment by ticktacktu** [comment]
Vielen Dank für die schnelle und kompetente Antwort ich bin begeistert viele Grüße Helmut RöllVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Maren Lange ***@***.***> Datum: 26.01.23  19:06  (GMT+01:00) An: contao/contao-manager ***@***.***> Cc: ticktacktu ***@***.***>, Author ***@***.***> Betreff: Re: [contao/contao-manager] Abbruch (Issue #756) 

Bitte poste Dein Problem im Contao-Forum https://community.contao.org/de/index.php. Hier geht es um Probleme des Managers. Du hast ein Problem mit den Anforderungen des Mate-Themes. Die von Dir verwendete Version des Mate-Themes benötigt Contao 5.
