### ISSUE TITLE
suche contao hilfe 

### ISSUE THREAD

**Issue by BeaH85** [contao/contao-manager#758]
Hallo in die Runde, 
ich bin neu im programmieren und contao - wollte eine funktionierende Seite updaten und jetzt geht sie leider nicht mehr - reparatur tool schlägt fehl:

$ /opt/RZphp80/bin/php-cli -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -ddisplay_startup_errors=0 -derror_reporting=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=MET /mnt/web524/b3/58/5912858/htdocs/sgseehausen/web/contao-manager.phar.php composer install --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.
  Problem 1
    - contao-community-alliance/composer-plugin is locked to version 3.0.9 and an update of this package was not requested.
    - contao-community-alliance/composer-plugin 3.0.9 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.2.0] but it does not match the constraint.
  Problem 2
    - contao-components/installer is locked to version 1.3.1 and an update of this package was not requested.
    - contao-components/installer 1.3.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.2.0] but it does not match the constraint.
  Problem 3
    - contao/manager-plugin is locked to version 2.7.1 and an update of this package was not requested.
    - contao/manager-plugin 2.7.1 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.2.0] but it does not match the constraint.
  Problem 4
    - ocramius/package-versions is locked to version 1.4.0 and an update of this package was not requested.
    - ocramius/package-versions 1.4.0 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.2.0] but it does not match the constraint.
  Problem 5
    - lib-xsl is present at version 1.1.26.0 and cannot be modified by Composer
    - Only one of these can be installed: lib-libxslt[1.1.37], lib-xsl[1.1.26.0]. lib-libxslt replaces lib-xsl and thus cannot coexist with it.
    - lib-libxslt is present at version 1.1.37 and cannot be modified by Composer
# Process terminated with exit code 2
# Result: Misuse of shell builtins
Contao Manager 1.6.3[Hilfe](https://docs.contao.org/)[Probleme melden](https://github.com/contao/contao-manager/issues/new)

kann mir jemand helfen?

**Comment by mlwebworker** [comment]
Bitte wende Dich mit solchen Problem an das [Contao-Forum](https://community.contao.org/de/index.php). Github ist für die Unterstützung bei individuelle Probleme eher nicht der richtige Ort.
In Deiner Installation können derzeit die Abhängigkeiten nicht aufgelöst werden.
Du solltest über die Systemwartung im Contao Manager oder auf der Konsole ein `composer update` ausführen.
Bei weiteren Fragen dann bitte im Contao Forum melden.
