### ISSUE TITLE
Wrong version displayed when uploading a new version of a zip file

### ISSUE THREAD

**Issue by Toflar** [contao/contao-manager#760]
Reproduce:

1. Create a custom zipped bundle with `"version": "1.0.0"` in its `composer.json`
2. Install in Manager using drag n' drop.
3. Create another zip file, this time it's version `1.0.1`.
4. Drag n' drop again

It will correctly ask you to update the package but it will still show `1.0.0` instead of `1.0.1`.

**Comment by aschempp** [comment]
Fixed in c079913873f7f298e93229c1b258abe0d7f63554
