### ISSUE TITLE
Systemprüfung - Auswahl des CloudResolver nicht möglich (CM 1.6.3)

### ISSUE THREAD

**Issue by planepix** [contao/contao-manager#762]
Hallo zusammen,

möchte man die Composer Resolver Cloud aktivieren / deaktivieren, wird zu schnell weitergeleitet.

Während die Systemprüfung startet und man sofort auf „Serverkonfiguration” klickt, wird dies kurz angezeigt und dann wieder geschlossen.

Bei manchen Aktionen bleibt nach der Prüfung die Seite aktiv und man kann den Contao Manager starten.
Dann lässt sich auch die Resolver Cloud aktivieren oder deaktivieren.

Manchmal wird nach der Systemprüfung sofort zum Contao Manager weitergeleitet - somit keine Chance, die Auswahl der Resolver Cloud zu ändern.

https://community.contao.org/de/showthread.php?84665-Nach-Entfernen-manuell-installierter-Erweiterungen-kein-Composer-Update-m%C3%B6glich

Danke

**Comment by aschempp** [comment]
fixed in 10f19353d38a5e73290a7a041b8355825ae16113
