### ISSUE TITLE
Lead seems to ne be actual version

### ISSUE THREAD

**Issue by pgunzelmann** [contao/contao-manager#766]
i got 
terminal42/contao-leads[1.4.7, ..., 1.4.20] require php ^5.3.2 || ^7.0 -> your php version (8.1.16.0) does not satisfy that requirement.

if i look ar gitub of project it shows at 

https://github.com/terminal42/contao-leads/blob/main/composer.json

    "require": {
        "php": "^7.0 || ^8.0",
        "contao/core-bundle": "^3.5.1 || ^4.1",
        "contao-community-alliance/composer-plugin": "^2.4.0 || 3.*",
        "codefog/contao-haste": "^4.10.0",
        "menatwork/contao-multicolumnwizard": "~3.2"
    },

may the packed could bes updated at contao manager

**Comment by fritzmg** [comment]
https://github.com/terminal42/contao-leads/issues/137#issuecomment-1464890830

**Comment by aschempp** [comment]
Closing this as it is not an issue of the Contao Manager.
