### ISSUE TITLE
Nach Update von 4.13.16 auf 4.13.17 wird der Maintenance Modus nicht beendet

### ISSUE THREAD

**Issue by planepix** [contao/contao-manager#767]
Ich habe auf die 4.13.17 aktualisiert. Beim Aufruf, die Datenbank zu aktualisieren, wird der Hinweis „Service unavailable” ausgegeben.

Sprich der Maintenance-Modus wird nicht beendet…

Unter „/vars” liegt dann „maintenance.html”. Die habe ich manuell gelöscht; danach konnte das Backend wie das Frontend wieder aufgerufen werden.

**Comment by skipman** [comment]
Korrekt, der Maintenance-Mode kann wie von planepix beschrieben beendet werden. Jedoch sind der Wartungsmodus und die DB-Migration weiterhin nicht verfügbar (siehe https://contao.slack.com/archives/CK4J0KNDB/p1678898132327549)

**Comment by fritzmg** [comment]
Likely fixed by https://github.com/contao/contao/pull/5879

**Comment by aschempp** [comment]
Closing as this is not a bug in Contao Manager but in Contao (but thanks for reporting @planepix!)
