### ISSUE TITLE
 MATE installing issue 

### ISSUE THREAD

**Issue by anelluk** [contao/contao-manager#771]
Hello,
I'm new at the GitHub and I am installing a contao theme myself for the first time.  When the databases are updated, a message like the one shown below appears. When I ask the manager to run it, I get stuck in an infinite loop. There are always the same table rows, they appear again and again, manual deletion is useless. I am at all-inkl.com

<img width="972" alt="Bildschirmfoto 2023-04-09 um 20 21 44" src="https://user-images.githubusercontent.com/130310389/230790811-ce54f07c-f06e-4afe-aab1-a94a7ae97cc0.png">

**Comment by MDevster** [comment]
@anelluk Which MATE version do you have installed? Can you provide more information about your setup, like the Contao version or composer.json? Currently there are no known issues with all-inkl.

**Comment by MDevster** [comment]
Für Contao 4.13 musst du die MATE Version 2.x installieren, du müsstest also Version 2.20.1 installiert haben?

![grafik](https://user-images.githubusercontent.com/10244240/231132404-edda0436-b535-480a-9508-359e7b44e15e.png)
![grafik](https://user-images.githubusercontent.com/10244240/231132448-41789821-5af6-4680-acb6-5c31e07a2518.png)

**Comment by anelluk** [comment]
Ich habe leider keine Notitzen gemacht. Ich bin mir sicher, dass ich im ersten Anlauf PHP 8.0 genommen habe, im zweiten Contao 4.13 und PHP 7.4. Das ist meine erste Theme-Installation, ich tausche meine eigenen Websites aus, die laufen noch mit Contao 2.11. und sind nicht responsive.
Ich probiere nochmal mit der vorgeschlagenen Konfiguration und melde mich.

**Comment by anelluk** [comment]
Hallo, ich habe eine Installation von Contao 4.13 mit PHP 7.4 und MATE 2.0 getestet. Leider bin ich wieder auf das gleiche Problem aufgelaufen. Hier der Einblick in die Datenbankeinstellung

<img width="952" alt="Bildschirmfoto 2023-04-11 um 21 02 59" src="https://user-images.githubusercontent.com/130310389/231265392-e2d1b108-ec76-4b4b-a8bf-4e3b001a08a5.png">

**Comment by MDevster** [comment]
An den Einstellungen sollte es nicht liegen, du kannst uns gern mal an support ÄÄTT pdir Punkt de eine E-Mail mit einem Manager Zugang senden und wir schauen mal wo das Problem ist! Das Bild kannst du sicherheitshalber wieder löschen aus deinem Beitrag.

**Comment by MDevster** [comment]
Is due to this issue https://github.com/contao/contao-manager/issues/325, Problem is solved for @anelluk gelöst.
