### ISSUE TITLE
Crashing down server - Server configuration

### ISSUE THREAD

**Issue by xApep** [contao/contao-manager#772]
Hey. 
I have installed many Contao on our server, and I always could select here "change" and then select "Composer resolver cloud".
But now it sticks here and it crashes down the server. 

![image](https://user-images.githubusercontent.com/1315340/234508748-4dd7f99b-2a51-435d-8dfb-e6723dbcdc9f.png)

1.6.3 (screen shot 1.6.1 was also a test)

**Comment by aschempp** [comment]
> it crashes down the server

what do you mean by that?

**Comment by xApep** [comment]
The problem was that we have enabled "zlib.output_compression" in some previous project where we did speed optimisation...but it seems that it is conflicting with contao manager.

crashes down the server = cpu 100%, out of memory, 500 errors on all pages, ... so we need to kill "‘/usr/bin/php’ ‘-q’ ‘/home/x/public_html/public/contao-manager.phar.php’ ‘test’”

**Comment by aschempp** [comment]
that sounds like you enabled `zlib.output_compression` on the command line and/or do not not use a CLI binary (but a CGI binary for example)?

**Comment by xApep** [comment]
Will check with server admin and write the feedback. Thanks!

**Comment by aschempp** [comment]
I'm closing this for now, feel free to reopen if you have more feedback.
