### ISSUE TITLE
Need possibility to update from Contao Version 2.11.13

### ISSUE THREAD

**Issue by BoskeJos** [contao/contao-manager#774]
Sorry I don't think it should be in this section, but just trying something. 
I'm trying to update a very old contao website to the today's standard. 
Sadly the original administrator did never update the contao version, and it is still a 2.11.13 version. 
Is there a way to update it to at least version 3.5 So we could use the update manager?

Thank you very much for the help. 

Regards,
Jos Winter Rubingh.

**Comment by aschempp** [comment]
That should still be possible, but manually and not through the Contao Manager. Please refer to the [support channels](https://to.contao.org/support) (forum/Slack) if you need help from the community or contact a [Contao Partner](https://to.contao.org/partner) in your region.
