### ISSUE TITLE
Contradictory statement about the version

### ISSUE THREAD

**Issue by Aybee** [contao/contao-manager#776]
I have 2 installations 4.13.25 on the same server with the same extensions and versions. composer.json also are identical. PHP 8.1.20 also the same. However, the statements about the versions of an extension is different on every domain.

In addition, "2.2.1 installed, new version 2.2.0 available" somehow makes no sense. Or?

![Bildschirmfoto am 2023-06-30 um 18 15 14](https://github.com/contao/contao-manager/assets/1143013/c097b8e8-831a-49ba-902b-29d3360f15f8)
![Bildschirmfoto am 2023-06-30 um 18 15 31](https://github.com/contao/contao-manager/assets/1143013/b31f722b-076e-4a76-aa19-43eaca0a50b1)

The specifications of both versions are the same.

![Bildschirmfoto am 2023-06-30 um 18 33 02](https://github.com/contao/contao-manager/assets/1143013/580e44fa-f40d-4133-b24d-96f49b3b59f6)
![Bildschirmfoto am 2023-06-30 um 18 33 12](https://github.com/contao/contao-manager/assets/1143013/79d79df1-d503-4286-87f1-8baa089315ab)

**Comment by ausi** [comment]
I think we should remove this green/grey box, see #764

**Comment by aschempp** [comment]
The Contao Manager retrieves this info from packagist.org, which has an API cache layer. Your browser cache might be outdated, or any other API glitch in between. There's not much we can do about that, but I belive the info is more helpful than problematic for the most part 🙃

**Comment by mlwebworker** [comment]
Wenn die Informationen möglicherweise falsch sind, dann führt das immer wieder zu Verwirrungen bzw. Verunsicherung. Mich stört es nicht wirklich, aber die Fragen dazu auch im Forum sind einfach immer wieder vorhanden.

**Comment by ausi** [comment]
> aber die Fragen dazu auch im Forum sind einfach immer wieder vorhanden.

Ich muss im Support regelmäßig (auch heute z. B.) erklären, dass diese grüne box nur ein Hinweis ist und dass es kein Fehler ist wenn sich diese durch ein Update nicht „loswerden“ lässt. Sehr viele von unseren Kunden sind betroffen (weil unsere Erweiterungen in der neuesten Version nicht mit Contao 4.9 kompatibel sind).

**Comment by Aybee** [comment]
Thank you for the explanations. In general, I like this green box. Just wanted to have reported it because it was a bit strange because I had this different result with 2 same installations.
