### ISSUE TITLE
Contao Manager 1.6.4 - Abhängigkeiten und Konflikte nicht mehr anzeigbar

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao-manager#778]
Nach Update des Manager auf Version 1.6.4 können unter Details die Abhängigkeiten nicht mehr angezeigt werden (Reiter sind ausgegraut)
Siehe auch https://community.contao.org/de/showthread.php?85464-Contao-Manager-1-6-4-zeigt-keine-Abh%C3%A4ngigkeiten-Konflikte-bei-den-Paketen-an

**Comment by lukasbableck** [comment]
Zusätzlich können Details nur noch von installierten Paketen geöffnet werden. Nicht installierte Pakete hängen dann bei "Loading" fest.
<img width="752" alt="image" src="https://github.com/contao/contao-manager/assets/42083846/c53c5497-229d-423b-9462-72db0121cd77">

**Comment by contaoacademy** [comment]
Kann ich bestätigen.

**Comment by aschempp** [comment]
Fixed in 7dd61f1f425b0d5468da09c91ac9e7b8231a6e70
