### ISSUE TITLE
Manager ruft unbekannten Befehl auf

### ISSUE THREAD

**Issue by a-v-l** [contao/contao-manager#779]
Nach einem Update von 4.13 auf 5.1 via Kommandozeile scheint die Methode `getVersion()` in https://github.com/contao/contao-manager/blob/17ee66ebd4782b96dfdc57bc8b0e6c381c0845b6/api/Process/ContaoConsole.php#L62 immer noch einen CLI-Befehl aus der 4.13 aufzurufen ([contao:version](https://github.com/contao/core-bundle/blob/4.13/src/Command/VersionCommand.php)), der in 5.1 aber nicht mehr existiert:

![image](https://github.com/contao/contao-manager/assets/3359867/e6845ef8-e6f6-4cc8-a53b-842c4b9a3a52)

**Comment by ausi** [comment]
Was passiert wenn du auf der CLI `vendor/bin/contao-console list --format=json` ausführst?

**Comment by a-v-l** [comment]
`vendor/bin/contao-console list --format=json > list.json` spuckt eine 266KB Datei aus. Soll ich die hier posten? Scheint keine sensiblen Daten zu beinhalten – habe die 10440 Zeilen nach Pritty-Print aber noch nicht ganz durchgeschaut! ;-)

**Comment by a-v-l** [comment]
> Was passiert wenn du auf der CLI `vendor/bin/contao-console list --format=json` ausführst?

Oh, scheint doch was damit zu tun gehabt zu haben! Es gab nämlich erst eine Fehlermeldung wegen dem mailer_transport: ich verwende mailhog. Nachdem ich die Mailkonfiguration in `/config/parameters.yml` angepasst habe, ist `contao-console list --format=json` ohne Fehler durchgelaufen. Seit dem funktioniert auch der Manager wieder!

Idealerweise könnte es eine etwas hilfreichere Fehlermeldung in der Konsolenausgabe geben…

**Comment by aschempp** [comment]
Ich habe in 963095ac3b08f98282166b243ad90f73aac0187b eine Verbesserung eingebaut, sodass man hoffentlich die "echte" Fehlermeldung sieht.
