### ISSUE TITLE
"Pakete hochladen" ist nicht aktiviert

### ISSUE THREAD

**Issue by PatContao** [contao/contao-manager#783]
Hallo zusammen!
Ich bin ganz neu hier und möchte gern das Theme "Optimist" als Impuls installieren und testen.
Leider stelle ich fest, dass das Botton "Pakete hochladen" im Contao Manager bei mir nicht aktiv ist (s. Screenshot) . Ich konnte Optimist nicht per Drag-and-Drop hochladen. Auch bei einem unter §Entdecken" ausgesuchte Theme (z.B. Mate) bekomme ich nach "Hinzufügen" und "Änderung anwenden" einen Fehlermeldung.

Hat jemand eine Idee, was ich falsch gemacht habe und dies korrigieren kann?
Im Voraus vielen Dank!
Pat
![Pakete_Hochladen_inactiv](https://github.com/contao/contao-manager/assets/144127226/cc50a7f1-d2e3-4694-b3f8-55a6ecb3d774)

**Comment by pressi** [comment]
Hallo,
welche Fehlermeldung hast Du?

Am besten wäre es wahrscheinlich den Theme-Herstellter zu kontaktieren.
Anleitung funktioniert nicht?
https://erdmann-freunde.de/contao-themes/optimist/installation

LG

**Comment by Toflar** [comment]
Die Warning ist egal, weiter oben steht die Fehlermeldung. Irgendwas von wegen das `mate-theme-bundle` möchte Contao 5. Wahrscheinlich einfach die falsche Version ausgewählt?

**Comment by pressi** [comment]
Für Contao 4.13.* brauchst du beim MATE Theme die Version 2.20.4 damit du es installieren kannst.

Warum Paket hochladen nicht aktiv ist kann ich dir nicht genau sagen, eventuell am Server eine Extension nicht aktiviert?Aber warum das nicht auswählbar ist kann Dir wahrscheinklich @aschempp  oder @Toflar  genauer sagen?
Bei welchem Hoster bist Du?

**Comment by PatContao** [comment]
Danke Pressi und Toflar für den Hinweis. Ich probiere dann weiter, ob ich Mate Theme installiert bekomme, und vor allem bin gespannt darauf, ob das Botton "Pakete hochladen" noch aktiviert bekomme und OPTIMIST doch benutzen kann.

Ich bin nicht bei den gängigen Hostern wie IONOS, Stratos oder All-Inkl-com etc, sondern bei einem kleinen Anbieter Planinternet, der nach meinem Bedarf anpaßbar ist.

Viele Grüße
Pat

**Comment by pressi** [comment]
Ok, meine Vermutung wäre der Server kann keine Zip Dateien verarbeiten, daher der ausgegraute Button "Pakete hochladen". Ist aber wie gesagt nur eine Vermutung.

**Comment by PatContao** [comment]
Danke Taflar. Das war der Grund: Zip wurde in PHP nicht unterstützt. (Bis PHP 7.3 hieß der Schalter beim Kompilieren --enable-zip, jetzt heißt er --with-zip)

**Comment by zonky2** [comment]
habe auch so einen Fall - kurzer Hinweis als Tooltipp wäre schön...

**Comment by aschempp** [comment]
> habe auch so einen Fall - kurzer Hinweis als Tooltipp wäre schön...

genau das ist schon vorhanden als HTML title-Attribut, sollte man also bei drüberfahren sehen 😉

**Comment by zonky2** [comment]
> genau das ist schon vorhanden als HTML title-Attribut, sollte man also bei drüberfahren sehen

das Title-Attribut habe ich entdeckt - der Tooltipp wird bei mir aber so lange nicht ausgespielt, wie der Button `disabled` ist - nehme ich das Attribut `disabled`  raus, gehts

Getestet: Debian 12, FF und Chrome

**Comment by aschempp** [comment]
das war am Ende kein Problem des `disabled`, sondern dass das CSS in diesem Fall ein `pointer-event: none` gesetzt hat.
