### ISSUE TITLE
Retrieving API Token - request parameter `return_url` invalid althought https protocol is present

### ISSUE THREAD

**Issue by M-Zoldak** [contao/contao-manager#784]
While trying to retrieve the Contao Manager API Token, i encountered this error message 

> Ungültiger OAuth-Versuch. Bitte überprüfe die Request-Parameter.
> Die Rückleitungs-URL MUSS eine sichere Verbindung (https:) nutzen, um die Übertragung der Anmeldedaten im Klartext zu verhindern.

I think the problem occurs since version 1.7.0. Everything worked finde before that.

URL:
`https://www.here-im-asking-about-token.de/contao-manager.phar.php/#/oauth?scope=admin&client_id=some_id&return_url=https%3A%2F%2Fwww.some-return-site.de%2Fadd_manager_token%2F290`

**Comment by aschempp** [comment]
Unfortunately, the Contao Manager documentation is outdated, `return_url` is no longer valid. Please see my docs pull request for details until this is merged: https://github.com/contao/docs/pull/1244
