### ISSUE TITLE
Displaying an error when HTTP 401

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#786]
In case of an authentication error (401) a green check mark is currently displayed although an update was not possible.

A red cross would be a better feedback here.

```
> Resolving dependencies using Composer Cloud v3.6.0-1-g9d9036c
[8.0MiB/0.20s] Loading composer repositories with package information
[8.5MiB/0.52s] <warning>https://token:geheim@packages.packmanager.de/r could not be fully loaded (The 'https://token:geheim@packages.packmanager.de/r/packages.json' URL required authentication (HTTP 401).
You must be using the interactive console to authenticate), package information was loaded from the local cache and may be out of date</warning>
...
```

**Comment by aschempp** [comment]
I don't understand what you're trying to suggest. Looks like a warning in your log, the task did not fail though?

**Comment by aschempp** [comment]
> <warning>https://token:geheim@packages.packmanager.de/r could not be fully loaded

This is a warning. Maybe the package could be loaded from somewhere else. The process must have been successful, otherwise it would have been reported as an error?

**Comment by zonky2** [comment]
> The process must have been successful, otherwise it would have been reported as an error?

No!

**Comment by aschempp** [comment]
I'm sorry I can't really help with this limited information. I would need to see at least some output to guess what you're trying to say 🤷
