### ISSUE TITLE
Contao Manager API rejects Token

### ISSUE THREAD

**Issue by M-Zoldak** [contao/contao-manager#792]
I can't read data from Contao manager API after retrieving token.  API returns `Access denied - 403` for any call.

It's still working with tokens retrieved old way, saved in DB for other websites.

**Comment by aschempp** [comment]
Please explain exactly what you're doing.

**Comment by M-Zoldak** [comment]
1. I'm saving token which comes with access_token parameter.
2. Making curl request to `example.com/contao-manager.phar.php/api/server/php-web` with headers, including `Authorization: Bearer "previously saved token"`, and some more.

And at this point, for Tokens created before (I assume) `contao-manager < ~1.8.0` this call works perfectly, and for calls with tokens received from `contao-manager > 1.8.0`, I become 403 response.

**Comment by aschempp** [comment]
Are you sure you‘re saving the token? The token return URL has changed, there is no query parameter for the token, it is in the URL hash only!

**Comment by M-Zoldak** [comment]
Yes, I'm sure whole Token is saved - from hash, and not from parameter.

**Comment by M-Zoldak** [comment]
Ok, my big mistake.

I made call to my own website instead of client website.
