### ISSUE TITLE
Contao-Manager Background Process won't stop

### ISSUE THREAD

**Issue by JanWehyve** [contao/contao-manager#793]
```
composer remove oveleon/contao-cookiebar
 $ /opt/RZphp80/bin/php-cli -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -ddisplay_startup_errors=0 -derror_reporting=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=MET /mnt/web321/e1/63/59604463/htdocs/web3dev/web/contao-manager.phar.php composer remove oveleon/contao-cookiebar --no-update --no-scripts --no-ansi --no-interaction

composer update oveleon/contao-cookiebar contao/conflicts --no-install

composer install
```

What does that mean and how can i stop this?

**Comment by JanWehyve** [comment]
Ja genau, wie nutze ich die Konsole da?

**Comment by JanWehyve** [comment]
Habe ich geschafft. Was genau kann ich dann dort ändern, damit der Prozess abbricht? 
Was genau passiert überhaupt bei diesem Prozess?

**Comment by mlwebworker** [comment]
Den Prozess bricht Du unabhängig davon ab in dem Du im Ordner `contao-manager` die `task.json` löschst.
Alle weiteren Fragen solltest Du bitte im [Contao-Forum](https://www.strato.de/faq/hosting/so-nutzen-sie-ihren-ssh-sftp-zugang/.) klären bzw. dort nachlesen. Da gibt es einige Threads im Zusammenhang mit Strato und dem Updateprozess

**Comment by JanWehyve** [comment]
Vielen Dank - es hat alles geklappt und ich kann weiterarbeiten!
