### ISSUE TITLE
Add a reload option for the log files

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao-manager#799]
The log files are no longer updated after the Contao Manager is started.
It would be helpful if there was a «reload button» to reload the latest logs from the server.

![screen-20240229_8pQmMYac](https://github.com/contao/contao-manager/assets/23719181/93fa7abf-296c-4c91-9b3f-d67f0284b624)

**Comment by aschempp** [comment]
It _does_ reload if you select another file, but I agree a button would make sense.

**Comment by aschempp** [comment]
see https://github.com/contao/contao-manager/pull/809
