### ISSUE TITLE
Delete OpCode Cache

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#80]
The manager must run `opcache_reset()`

- [ ] after self-update
- [ ] after package changes (require/remove/update)
- [ ] maybe after `ApiError`?

**Comment by leofeyer** [comment]
This is what we should run:

```php
        // Zend OPcache
        (function_exists('opcache_reset')) &&
            opcache_reset()
        ;

        // Zend Optimizer
        (function_exists('accelerator_reset')) &&
            accelerator_reset()
        ;

        // APC
        (function_exists('apc_compile_file') && !ini_get('apc.stat')) &&
            apc_compile_file('contao-manager.phar.php')
        ;

        // eAccelerator
        (function_exists('eaccelerator_purge') && !ini_get('eaccelerator.check_mtime')) &&
            @eaccelerator_purge()
        ;

        // XCache
        if (function_exists('xcache_count') && !ini_get('xcache.stat')) {
            if (($count = xcache_count(XC_TYPE_PHP)) > 0) {
                for ($id = 0; $id < $count; $id++) {
                    xcache_clear_cache(XC_TYPE_PHP, $id);
                }
            }
        }
```

**Comment by leofeyer** [comment]
The code is taken from the Live Update client.

**Comment by aschempp** [comment]
FYI this must also be done in the install tool…

**Comment by Toflar** [comment]
Also, regarding the manager, this should be done in the web process, not via command line :) I know it might be obvious but leaving this here for reference.

**Comment by leofeyer** [comment]
Implemented in the install tool in contao/installation-bundle@e90ce21a3fe4482dc0824dd81d2157e2bfc42c9c.

**Comment by leofeyer** [comment]
Please note my adjusted [comment](https://github.com/contao/contao-manager/issues/80#issuecomment-300582005) above. I have removed all caches that are no longer maintained or not compatible with PHP 5.6 (let alone PHP 7).
