### ISSUE TITLE
"Check database" is running wild

### ISSUE THREAD

**Issue by Bigga63** [contao/contao-manager#801]
I have updated an installation from 4.13.13 to 4.13.38. Including all extensions:
Mobile page layout for Contao 4.8+
mmenu - Mobile Navigation for Contao
RockSolid Columns
RockSolid Slider
Contao Cookiebar
spotbot2k/webfont-generator-bundle

works wonderfully. 

Then the database should be added and since the Contao-Manager needed hours for this, I - slightly impatient - did it via the install tool. 
Everything is fine.
Website fine.
No error message in the logs

But: the Contao Manager thinks the database is not up to date, I can only start it in safe mode and when I try to check the database, the Contao Manager hangs.

Does anyone have any idea why this could be?

Bigga

Translated with DeepL.com (free version)

**Comment by V15** [comment]
Same problem here with two installations:

1)
Contao Update 4.13.26 -> 4.13.39

With this update I marked all extensions for update and one extension (EasyThemes) for delete.
Everything works but the Contao Manger hangs while trying to update the database.

I did the same like @Bigga and updated the database with the install tool. The database is up to date.
The Contao Manager still hangs.

Re-Installing EasyThemes doesn't help.
Deleting EasyThemes again doesn't help either.

2)
Contao Update 5.3.0 -> 5.3.1

I updated this installation and install some extensions.
Same problem. No way out. Safe mode and hanging Manager...

Thorsten

**Comment by xprojects-de** [comment]
For me it was because there was still an old database_version in the parameter.yml / env. Remove it, build the cache and you're done!

**Comment by kikmedia** [comment]
Probably we should display some kind of hint if there are settings in parameters.yaml, shouldn't we?

**Comment by V15** [comment]
I guess this is not necessary.
The entry in the parameters.yml is set automatically and looks normal.
I did delete the database version (database_version: 10.5.18-MariaDB-0+deb11u1-log) in the parameters.yml (and kept everything else) and after the update it was set again and it actually looks exactly the same like before. But now the update works again.

**Comment by aschempp** [comment]
should be fixed in a9fa864eac121aa26beb23e56f1ab86a0b085c90
