### ISSUE TITLE
erreur 403 & 404 - new installation

### ISSUE THREAD

**Issue by JIDEAQT** [contao/contao-manager#810]
Bonjour,
Nouvel utilisateur du cms Cantao, je rencontre un probleme d'acces au back office aisni que sur le site web.
J'ai procédé a l'installation de catao via le fichier téléchargé sur le site officiel.
La base de données est bien connectée et le manager est accessible.
J'ai procédé a l installation comme indiqué sur le site de cantao.

J'ai une erreur 403 lors de l'acces au back office et 404 sur la page d 'accueil du site web.
J'ai installé la version 4.13 et le manager est en version 1.8.4

Je pratique depuis plusieurs années le cms wordpress, j'ai quelques connaissances et aujourd'hui  je souhaite tester Cantao.

Je suis hébergé chez infomaniak avec acces ftp et php my admin.

Par avance je vous remercie pour votre retour.

**Comment by zoglo** [comment]
Hey @JIDEAQT,

il semble que la racine de votre site ne se trouve pas dans le répertoire '/public/'.

Une fois que votre installation pointera vers ce répertoire, le problème sera probablement résolu.

Veuillez parler en anglais pour ces questions, car peu de gens parlent français. En fait, j'utilise un traducteur pour vous aider à résoudre votre problème en ce moment même.

**Comment by JIDEAQT** [comment]
Bonjour,
Merci pour votre réponse.
J'ai effectué la modification et cela fonctionne.
Je rencontre un nouveau probleme: " Error handling the Composer Resolver Cloud. Please try again late" lors de l'installation d'un theme. Dois-je mettre a jour contao ? 

--

Good morning,
Thank you for your reply.
I made the modification and it works.
I encounter a new problem: "Error managing Composer Resolver Cloud. Please try again late" when installing a theme. should I update contao?

**Comment by aschempp** [comment]
> I encounter a new problem: "Error managing Composer Resolver Cloud. Please try again late" when installing a theme. 

This looks like your server is blocking outgoing connections. I assume you already fixed this in the last three weeks, if not please feel free to reopen the issue!
