### ISSUE TITLE
Contao Manager not launching after database error

### ISSUE THREAD

**Issue by maxjung13** [contao/contao-manager#811]
I wanted to start setting up a new contao and launched the contao manager. After adding new user etc, I ended up at connecting a database. As I couldn't move on due to missing database, I wanted to restart today. 

So I launched contao manager again, logged in and server review staded with an error on database (obviously). Clicking on button to change database settings I end up in a never ending loading page: 

![image](https://github.com/contao/contao-manager/assets/171554235/b2842489-8421-4ef0-9e1e-0fd5d1aa6ab0)

Multiple restarts of process didn't help out. Please support, as I am not aware how to proceed

**Comment by contaoacademy** [comment]
Please check once in the root directory of Contao if an `.env` and `.env.local` file has been created and delete both files once and restart the manager.

**Comment by piotrwarsztocki** [comment]
I had the same problem. Deleting .env files did not help. After reviewing the .env.local file I deleted the serverVersion parameter at the end of DATABASE_URL (all with and after "?" character) and ... Contao Manager came to life :)

**Comment by aschempp** [comment]
fixed in a9fa864eac121aa26beb23e56f1ab86a0b085c90
