### ISSUE TITLE
Contao packages highlighted in CM 1.8.5

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao-manager#812]
Many thanks for the dark mode and the small improvements.

To highlight the Contao packages, an orange border is placed around them.

I therefore briefly have the feeling that an action is needed here.

If we omit the border and insert a margin to the packages, this effect could also be achieved.

```css
.package--contao:has(+ .package) {
    margin-bottom: 5em;
}
```

## Contao Manager 1.8.5
![cm-dark1](https://github.com/contao/contao-manager/assets/1942550/0cbdadb3-c883-4b98-831e-d3f8aa015ea9)
![cm-light1](https://github.com/contao/contao-manager/assets/1942550/06a30959-22cb-4fa1-9b99-64eb17c0f380)

## Contao Manager 1.8.6
![cm-dark2](https://github.com/contao/contao-manager/assets/1942550/cdb3b369-0e42-4464-a083-c0376977c98b)
![cm-light2](https://github.com/contao/contao-manager/assets/1942550/21cc3666-ed1b-4e7e-8270-064dd3c27f43)

**Comment by aschempp** [comment]
see https://github.com/contao/contao-manager/pull/813
