### ISSUE TITLE
Add support for badge title

### ISSUE THREAD

**Issue by MDevster** [contao/contao-manager#816]
It would be nice if the manager also supported the [badge_title](https://docs.contao.org/manual/en/system/settings/#back-end-configuration) feature of the Contao installation. Either by directly reading the `config/config.yaml` or by an additional configuration file in the manager folder.

![grafik](https://github.com/contao/contao-manager/assets/10244240/43ba6f8e-ce4e-49ac-8077-eb920889da32)

![grafik](https://github.com/contao/contao-manager/assets/10244240/34339e38-20c2-4e2f-ad77-d54a016831f5)

**Comment by zoglo** [comment]
@MDevster please check the mentioned PR. This PR needs your help to be implemented

**Comment by aschempp** [comment]
Closed in favor of #819
