### ISSUE TITLE
Wrong PHP version / path

### ISSUE THREAD

**Issue by xApep** [contao/contao-manager#820]
Hey.
There have been couple of threads here, but everything was more or less closed because of a stale issue.

The problem is that we are using WHM and on each we have different accounts / domains; some of them use contao 3, some 4, and now we are trying to bring life to contao 5.

Default System PHP version is 8.1.

Even if we set account / domain version to PHP 8.2, in this project (contao 5) Contao Manager will still only detect PHP 8.1 (binary path which can't be changed in Contao Manager Server config field).

Did you guys found any good solution durning all this time?

![image](https://github.com/contao/contao-manager/assets/1315340/ec4b6fee-c2b1-46c1-a903-6f410602bdfe)

![Screenshot 2024-07-09 at 18 01 46](https://github.com/contao/contao-manager/assets/1315340/45a16f7a-209f-482f-9433-42574bce29d5)

**Comment by fritzmg** [comment]
> (binary path which can't be changed in Contao Manager Server config field).

What do you mean? Why can't it be changed?

**Comment by fritzmg** [comment]
> Even if we set account / domain version to PHP 8.2, in this project (contao 5) Contao Manager will still only detect PHP 8.1

You need to double check that. Because if the Contao Manager detects that PHP 8.1 is in use for the _web process_, then you have indeed only set PHP 8.1 for the web process for that domain.

**Comment by xApep** [comment]
> > Even if we set account / domain version to PHP 8.2, in this project (contao 5) Contao Manager will still only detect PHP 8.1
> 
> You need to double check that. Because if the Contao Manager detects that PHP 8.1 is in use for the _web process_, then you have indeed only set PHP 8.1 for the web process for that domain.

I have I quadro checked :) WHM and also in cpanel account / domain, everything is set to 8.2 for this account / domain. 
But overall default server PHP version is set to 8.1, that is what I was wondering if someone had similar experience.

**Comment by fritzmg** [comment]
> I have quadro checked :)

Check it again the following way:

* Create a `public/pi.php` file with the content `<?php phpinfo();`
* Open `<your-domain>/pi.php` in your browser.

**Comment by xApep** [comment]
After some switching php versions in WHM now Contao Manager uses PHP 8.2 (PHP web process and Server config). 
Also pi.php shows PHP 8.2.

But after trying to install dependencies this error happens. 

![image](https://github.com/contao/contao-manager/assets/1315340/3c86e8d7-6f02-431e-b3bb-7e394562fa17)

**Comment by fritzmg** [comment]
> now Contao Manager uses PHP 8.2

It solely depends what your web server is using. Clearly your web server used the wrong PHP version before, as you were able to now independently check.

**Comment by fritzmg** [comment]
Post the output of `/usr/local/bin/php -v`, executed under the same user as the web process.

**Comment by xApep** [comment]
Thank you @fritzmg
There seems to be a problem within server, after restarting it, all was in the right place.
