### ISSUE TITLE
Irregular regexp: invalid character in class in regular expression

### ISSUE THREAD

**Issue by math-GH** [contao/contao-manager#821]
Contao Manager 1.8.6

`<input pattern='^([^:]+)://(([^:@]+)(:([^@]+))?@)?([^:/]+(:[0-9]+)?)/([^?]+)(\?.+)?$'> kann nicht überprüft werden, da das Muster keine gültige Regexp ist: invalid character in class in regular expression [chunk-vendors.d5895f06.js:26:58062](..../contao-manager.phar.php/js/chunk-vendors.d5895f06.js)`

![grafik](https://github.com/contao/contao-manager/assets/1645099/cf86c1a8-c8b6-49eb-971c-14bfbcf8a0cd)

**Comment by zoglo** [comment]
I stumbled upon this when creating the tool for the docs 👍 
https://github.com/contao/docs/blob/4e99fef22a8076bbdea1a8cc6caee7e01b3459a2/page/static/js/tools.js#L10

Should be (check the double escaping at the end)
```diff
- ^([^:]+)://(([^:@]+)(:([^@]+))?@)?([^:/]+(:[0-9]+)?)/([^?]+)(\?.+)?$
+ ^([^:]+)://(([^:@]+)(:([^@]+))?@)?([^:/]+(:[0-9]+)?)/([^?]+)(\\?.+)?$
```
