### ISSUE TITLE
Using usernames with url reserved characters cause issues

### ISSUE THREAD

**Issue by Toflar** [contao/contao-manager#824]
If you have a username like e.g. `foo#bar` or `foo?bar`, certain actions won't work. For example OAuth: https://github.com/contao/contao-manager/blob/65e416d3646e6f94b070923a679ce64cc5f427ff/src/components/routes/OAuthRoute.vue#L46

Not sure, if there are other places that need a fix.

**Comment by zoglo** [comment]
That's expected behavior due to the request and how the URI is build right now

I bet you got an error like:
```
HTTP request for "POST api/users/foo#bar/tokens" failed
HTTP request for "POST api/users/foo?bar/tokens" failed
```

Afaik, everything after a `#` doesn't get to the server, anything after a `?` is seen as a query string.
Should we disallow these characters in usernames?

**Comment by zoglo** [comment]
Or they should be encoded

**Comment by fritzmg** [comment]
They definitely need to be encoded.

**Comment by zoglo** [comment]
The only other "not really critical" occurences would be the 
- `$token` for the opcache reset (which shouldn't have any invalid characters like that) 
- and the logfile name within the LogFileViewer (logfiles don't have names like that)

So just the username would need to be encoded and decoded within the route

**Comment by aschempp** [comment]
Not sure I understand this. Should it be encoded by the Vue UI? Or should it be encoded in the API? Or the storage JSON file? or somewhere else?

**Comment by zoglo** [comment]
The username in the store needs to be encoded and decoded in the API I guess.

**Comment by Toflar** [comment]
Well it needs to be encoded correctly depending on the context. To be stored in JSON as a key, it needs to be encoded for JSON. Meaning `#` is not a problem, but `"` is. So `"` needs to be encoded by `\"`.
And in the URL it needs to be URL encoded. There both, `"` and `#` need to be encoded.

**Comment by aschempp** [comment]
> Well it needs to be encoded correctly depending on the context. To be stored in JSON as a key, it needs to be encoded for JSON. Meaning `#` is not a problem, but `"` is. So `"` needs to be encoded by `\"`. 

I'm pretty sure that's already the case, since we are using `json_encode` on the data, so that should take care of encoding? Also if that was not the case, the mentioned system would have a broken JSON file?

> And in the URL it needs to be URL encoded. There both, `"` and `#` need to be encoded.

By the server (API) or by the client (UI)? Because the API sends `json_encode` data, so again I would assume it is correctly encoded. The UI uses an HTTP client, I would have assumed it takes care of encoding. But I'm not sure if it does not.

Maybe we have a request that failed in the browser so we can see what actually happens?

**Comment by Toflar** [comment]
> I'm pretty sure that's already the case, since we are using `json_encode` on the data, so that should take care of encoding? Also if that was not the case, the mentioned system would have a broken JSON file?

Yes it is, nobody in this issue ever questioned the encoding in the JSON file. You brought that topic up - I don't know why you did.

> Maybe we have a request that failed in the browser so we can see what actually happens?

I linked the problematic lines? It's a very obvious issue? Again, you have to apply `encodeURIComponent()` here: https://github.com/contao/contao-manager/blob/65e416d3646e6f94b070923a679ce64cc5f427ff/src/components/routes/OAuthRoute.vue#L46

The only reason I did not create a PR is because I don't know if other places are affected. It's super easy to reproduce, just use a username with a `#` in it and start the OAuth flow and you'll see that everything after `#` (and including) of the username gets lost.
