### ISSUE TITLE
Badge Title via .env.local unterstützen

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao-manager#829]
Wir machen den Badge Title via Eintrag in der `config.yml` mit einem Platzhalter dann in der `.env.local` Beim Backend-Login funktioniert das ohne Probleme und gibt den Badge Title korrekt aus. Der Manager mag es nicht. Kann man das ggf. ändern?

![image](https://github.com/user-attachments/assets/7e5a36da-56b3-461a-b4ff-7410022fcedb)

**Comment by zoglo** [comment]
Wie schon erwähnt, müsste man mal schauen, wie es PHP-seitig aufgelöst wird -> also über die Route `/server/contao`

**Comment by aschempp** [comment]
Fixed in 282ee307a64d4cb01d2e8e0861b059e2b8841519
