### ISSUE TITLE
Add log viewer

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#84]
It should be possible to view the log files in the Contao Manager, otherwise there's no way to see why the installation fails without using FTP access (as there is no app_dev.php in the ME either).

**Comment by fenepedia** [comment]
Maybe it would be helpful to only implement a download-function. Without a complete integration of a complete logfile-viewer.

**Comment by aschempp** [comment]
Implemented the basics in 771643a4696665dbff86f7d27ee13a0359f71421
