### ISSUE TITLE
phar error when calling "http://domain.tld/contao-manager.phar.php

### ISSUE THREAD

**Issue by Seefahrer** [contao/contao-manager#88]
Calling "http://domain.tld/contao-manager.phar.php 
(real address: 
http://www.schuhe-alsguth.eu/contao-manager.phar.php 

throws error message:

`Fatal error: Uncaught PharException: phar "/www/htdocs/w00cfd4f/cmsc4ME/web/contao-manager.phar.php" SHA1 signature could not be verified: broken signature in /www/htdocs/w00cfd4f/cmsc4ME/web/contao-manager.phar.php:97 Stack trace: #0 /www/htdocs/w00cfd4f/cmsc4ME/web/contao-manager.phar.php(97): Phar::webPhar('contao-manager....', 'index.html', '', Array, 'rewrites') #1 {main} thrown in /www/htdocs/w00cfd4f/cmsc4ME/web/contao-manager.phar.php on line 97`

**Comment by xchs** [comment]
How did you transfer the Phar file?

**Comment by Seefahrer** [comment]
I used the transmit ftp-program. It worked fine with my own site, but unfortunately not with the site of my companion ...

**Comment by xchs** [comment]
Did you transfer the file in binary mode? You can also try to download the file directly using `wget` or `curl`.

**Comment by aschempp** [comment]
The file was not transferred in binary mode (see https://docs.contao.org/books/manager/en/faq.html).

**Comment by Seefahrer** [comment]
I didn't know anything abt. the last but it seems to be the explanation. But nonetheless, it remains strange to me as the ftp-transfer to my own side resulted in a fully functional "contao-manager.phar.php". It looks much like that the behaviour of transmit ist somehow unpredictable...
