### ISSUE TITLE
Contao Manager (All-Inkl Webhost)

### ISSUE THREAD

**Issue by pressi** [contao/contao-manager#89]
Hallo!

Ich bekomme beim aufrufen der Contao Manager Datei folgende Meldung:
`ERROR 500 Unknown installation status
Some files were found on your server but no known Contao version could be detected.
You must either manually repair your application or remove the following files and folders to install Contao:

cgi-bin`
Der cgi-bin Ordner kann aber nicht gelöscht werden da ich sonst keine PHP-Dateien mehr aufrufen kann.

Contao wurde noch nicht aufgesetzt. Es ist nur ein "web" ordner mit der contao-manager.phar.php Datei darin hochgeladen worden.

Gibt es eine Lösung zu dem Problem?
Oder muss Contao vorher aufgesetzt sein?

**Comment by k-webdesign** [comment]
Soweit ich weiß, musst du Contao schon vollständig hochladen und dann die phar in /web legen. Anders kann das ja nicht funktionieren, auf welche Dateien soll die phar denn sonst zugreifen?

**Comment by xchs** [comment]
> Soweit ich weiß, musst du Contao schon vollständig hochladen und dann die phar in /web legen. Anders kann das ja nicht funktionieren, auf welche Dateien soll die phar denn sonst zugreifen?

Nein, das ist nicht notwendig. Der Contao Manager kann natürlich auch Contao installieren. Siehe:
* https://docs.contao.org/books/manager/de/
* https://leofeyer.de/files/slides/2017/konferenz/#9
* https://leofeyer.de/files/slides/2017/konferenz/videos/contao-manager.mp4

**Comment by MDevster** [comment]
Du solltest deine Installation am besten nicht im Root machen. Verwende einfach Unterordner für deine Domains wie z.B. /example.de/ und leite die Domains dann auf /example.de/web/ um, dann klappt es.

**Comment by bezin** [comment]
Mit dem Hinweis von @MDevster sollte es klappen. Ich habe gerade auf einem All-Inkl Premium-Paket den CM  unter einer Subdomain ohne Probleme eingesetzt.

**Comment by Jaaaan** [comment]
Versuche mal die PHP Version zu ändern, anfangs hatte ich PHP 5.6 als ApacheModul, unter PHP 5.6 CGI war die Installation dann möglich.

Unter PHP 7 findet der CM bei All Inkl. noch nicht den PHP-Binary.

Dabei den Hinweis von @MDevster beachten.

**Comment by aschempp** [comment]
Das Problem wurde in der 1.0.0-beta2 behoben. Eventuell musst du die neu herunterladen oder das Self-Update auf der Kommandozeile ausführen, weil der Manager ja den Dienst gleich verweigert.

**Comment by fritzmg** [comment]
Commit for reference: d321f109a23fac883a7f6c5543babaf7656d7c7d

However, there might be more folders than that. All-Inkl. might also have a _usage_ folder. On other hosters an _.awstats_ folder might exist.
