### ISSUE TITLE
Vorschlag: "Benutzerkonto" klarer vom Backend-Konto trennen

### ISSUE THREAD

**Issue by k-webdesign** [contao/contao-manager#91]
Wenn man den Manager zum ersten Mal aufruft, muss ein Benutzerkonto erstellt werden. Evtl. sollte man textlich hervorheben, dass es sich hierbei nicht um das Backend-Konto handelt, sondern um ein separates Admin-Konto zur Konfiguration des Managers.

**Comment by Samson1964** [comment]
Das sorgte auch bei mir gestern bei der Erstinstallation mit dem CM für etwas Unsicherheit. Generell sollte deutlicher hervorgehoben werden, das man gerade den CM installiert (hat) und die Installation von Contao (eventuell) noch komplett fehlt.

**Comment by aschempp** [comment]
das ist aber doch gar nicht der Fall? Wenn du den Manager installierst, installierst du damit auch gleich Contao (vorausgesetzt es war noch nicht da, dann heisst der Button aber auch nicht *Installieren*)?

**Comment by aschempp** [comment]
The message has been improved in Beta 11
