### ISSUE TITLE
Feature: Paketnamen mit Packagist verlinken

### ISSUE THREAD

**Issue by k-webdesign** [contao/contao-manager#92]
Könnte man den Paketnamen in der Übersicht mit der Detailseite auf Packagist verlinken? So kann man leichter nachsehen, welche Abhängigkeiten die Extension hat, wo die Doku liegt, etc.

**Comment by BugBuster1701** [comment]
Beim Suchergebnis gibt es den "Mehr" Link der zu Packagist führt. 
Stimme zu, der wäre auch in der Übersicht gut je Paket.

**Comment by k-webdesign** [comment]
In der Übersicht fände ich es klasse, damit ich mir einen besseren Überblick über die Extensions verschaffen kann, wenn ich zB eine fremde Installation übernehme oder nach sehr langer Zeit wieder in eine alte Installation schaue. Oder wenn ich schlicht und ergreifend was nachschauen möchte, so spart man sich ein paar Klicks 😊

**Comment by xchs** [comment]
+1

**Comment by Schmidty2** [comment]
+1

**Comment by aschempp** [comment]
1.0.0-beta9 bietet nun Links zu Packagist und weiteren Quellen (falls entsprechend definiert) 😎
