### ISSUE TITLE
[WIN] CM does not find PHP binary

### ISSUE THREAD

**Issue by bezin** [contao/contao-manager#93]
Hello there,

I tried running the Contao Manager on Windows and gonna report all the issues I found here as precisely as possible. I run a local MAMP with PHP 7.1.0.

CM does not find the PHP binary, even though the given path is correct. It turns out that [running the test command fails](https://github.com/contao/contao-manager/blob/develop/api/Process/PhpExecutableFinder.php#L82). 

It does run, though, if you do not pass an empty env array to Process():

```php
// File: /api/Process/PhpExecutableFinder.php#L82
 $process = (new Process($commandline))->mustRun();

```

Thanks for all the work done on CM so far. I am going to test and report more. Just tell me, if you need some testing on specific issues.

**Comment by aschempp** [comment]
This should already be fixed in https://github.com/contao/contao-manager/blob/5f9699e4c08daa44df44e32db6d956b19366f629/api/Process/PhpExecutableFinder.php#L82, can you check that?

**Comment by bezin** [comment]
I can confirm this fixes it 👍
