### ISSUE TITLE
Menü funktioniert nicht unter iOS 10.3.2

### ISSUE THREAD

**Issue by Schmidty2** [contao/contao-manager#97]
Das Hauptmenü des Contao-Manager 1.0.0-beta2 funktioniert nicht unter iOS 10.3.2 auf einem iPad Pro 9,7".
Die Menüpunkte PAKETE - TOOLS - SYSTEMWARTUNG - ZAHNRAD lassen sich durch antippen nicht auswählen bzw. die Submenüpunkte öffnen sich nicht.

**Comment by aschempp** [comment]
Verstehe ich richtig dass du das Menü oben hast, nicht als Slide-Out, und sich die Dropdowns nicht öffnen lassen?

**Comment by ausi** [comment]
Das sollte sich durch #102 lösen lassen.

**Comment by aschempp** [comment]
closed in favor of #102
