### ISSUE TITLE
is ipify strictly necessary?

### ISSUE THREAD

**Issue by fritzmg** [contao/contao-manager#98]
Some hosters (DomainFactory apparently) seem to have problems connecting to https://api.ipify.org/, probably due to a local certificate misconfiguration on their part, leading to an "unexpected API status".

While the hoster should definitely fix this misconfiguration, is it wise to strictly rely on this service to be able to use the manager? What if that service goes down momentarily or for good? Shouldn't the usage of the Contao Manager not be strictly dependent on that service?

**Comment by BugBuster1701** [comment]
Meine Idee wäre mit `try catch` abfangen und eine Alternative in dem Fall ansteuern.
Beispiel ipinfo.io/ip
Oder für die Alternative einen eigenen Service auf dem CCA Server :-)

**Comment by aschempp** [comment]
ipify is not necessary, the host detection just does not work without it. Which means we cannot tell about pre-known paths to PHP binaries. But they are detected most of the time anyway. On the other hand we should look into [composer/ca-bundle](https://github.com/composer/ca-bundle) to fix the certificate issues.

**Comment by aschempp** [comment]
Fallback to insecure connection added in 349e3744a409e1fdc060e3175a9df99996bcf409. Keeping this open regarding *composer/ca-bundle*.

**Comment by fritzmg** [comment]
> On the other hand we should look into composer/ca-bundle to fix the certificate issues.

Hm, composer uses this as a fallback in case the local certificates are not readable. However in this case, the local certificates are readable, but seem to contain an error preventing an SSL connection to api.ipify.org (SSL connections to other services like contao.org or api.github.com work).

**Comment by BugBuster1701** [comment]
Hmm, von Arbeit aus mal getestet über https: richtige IP, über http: <nil>
Also irgendwas fuktioniert da nicht über http (bei http://api.ipify.org/)
Könnte aber dran liegen, das ich nur über Proxy ins Internet komme. 
ipinfo.io/ip hingegen zeigt die richtige IP über http und https.

**Comment by aschempp** [comment]
Switched to ipinfo.io in bb201e5017839cb6e1b94eb8554ee169a58f5a80, let's hope the rate limits are not an issue.
